<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam – Mô hình Kinh tế Y tế với R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../kb/m01-ee-foundations/l05-decision-tree.html" rel="next">
<link href="../../kb/m01-ee-foundations/l03-decision-rules.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9e7f0c659d5fa2cace8548cb57964278.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c18d72663580ed8ca19ce2a2f99af51b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=JetBrains+Mono:wght@400;600&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m01-ee-foundations/index.html">M01 · Nền tảng đánh giá kinh tế và cây quyết định</a></li><li class="breadcrumb-item"><a href="../../kb/m01-ee-foundations/l04-thresholds.html"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Mô hình Kinh tế Y tế với R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lời mở đầu</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m00-r-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M00 · R cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l02-vectors-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l03-functions-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hàm, cấu trúc điều khiển, vòng lặp và vectơ hóa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l04-data-frames.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Data frame — nhập, làm sạch, tóm tắt và chuyển dạng dữ liệu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l05-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Biểu đồ với ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l06-randomness-monte-carlo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 6: Ngẫu nhiên, mô phỏng Monte Carlo và sai số Monte Carlo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m01-ee-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M01 · Nền tảng đánh giá kinh tế và cây quyết định</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l01-evaluation-types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại đánh giá kinh tế, quan điểm, khung thời gian và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l02-health-outcomes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Năm sống, QALY và DALY</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l03-decision-rules.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l04-thresholds.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l05-decision-tree.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Xây cây quyết định từ đầu trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m02-cohort-markov/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l01-state-transition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao cần mô hình chuyển trạng thái</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l03-cohort-trace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l04-time-dependence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Phụ thuộc thời gian: lão hóa, trạng thái đường hầm và mảng 3 chiều</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l05-results-verification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị gắn với lần chuyển, đường biên hiệu quả và xác minh mô hình</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m03-uncertainty-voi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l01-deterministic-sa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại bất định và phân tích độ nhạy tất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l02-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Chọn phân phối cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l03-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích độ nhạy xác suất (PSA) trong R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l05-voi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m04-microsimulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M04 · Mô phỏng vi mô (microsimulation)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l01-why-microsimulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l02-microsim-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l03-vectorisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vectơ hóa theo cá thể và đo hiệu năng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l04-parallel-rcpp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tính toán song song và Rcpp cho vòng lặp nóng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l05-mc-error-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bao nhiêu cá thể là đủ? Sai số Monte Carlo, PSA và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m05-dynamic-transmission/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M05 · Mô hình lây truyền động</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l01-static-vs-dynamic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Mô hình tĩnh và mô hình lây truyền động</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l02-sir-seir-desolve.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình SIR và SEIR trong R với deSolve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l03-vaccination-herd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Tiêm chủng, hiệu quả trực tiếp và gián tiếp</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l04-dengue-host-vector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Mô hình vật chủ–véc tơ cho sốt xuất huyết Dengue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l05-dynamic-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế với mô hình lây truyền động</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m06-amr-economics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M06 · Kinh tế học kháng kháng sinh (AMR)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l01-amr-burden.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l02-attributable-los.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l03-ward-transmission.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Mô hình lây truyền CRE trong khoa hồi sức</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l04-two-strain-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m07-survival-psm/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M07 · Phân tích sống còn cho mô hình quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l01-survival-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ôn tập phân tích sống còn cho người làm mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l02-parametric-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình sống còn tham số với flexsurv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l03-extrapolation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Ngoại suy sống còn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l04-reconstruct-ipd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tái tạo dữ liệu cá thể từ đường KM đã công bố và dùng HR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l05-partitioned-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Mô hình sống còn phân vùng trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m08-calibration/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M08 · Hiệu chuẩn mô hình (calibration)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l01-why-calibrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l02-search-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l03-bayes-sir.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hiệu chuẩn Bayes và thuật toán SIR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l04-psa-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đưa kết quả hiệu chuẩn vào PSA, thẩm định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m09-inputs-vietnam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l01-costing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ước tính chi phí cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l05-decision-context.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bối cảnh ra quyết định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m10-policy-bia-equity/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m11-software-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l01-code-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Cấu trúc mã cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l02-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Xác minh và kiểm thử mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l03-version-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quản lý phiên bản với Git và tái lập môi trường với renv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l04-r-package.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đóng gói mô hình thành gói R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l05-shiny-living.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Ứng dụng Shiny và mô hình “sống”</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bảng thuật ngữ Anh–Việt</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Trong bài</h2>
   
  <ul class="collapse">
  <li><a href="#mục-tiêu-học-tập" id="toc-mục-tiêu-học-tập" class="nav-link active" data-scroll-target="#mục-tiêu-học-tập">Mục tiêu học tập</a></li>
  <li><a href="#ý-chính" id="toc-ý-chính" class="nav-link" data-scroll-target="#ý-chính">Ý chính</a></li>
  <li><a href="#nội-dung" id="toc-nội-dung" class="nav-link" data-scroll-target="#nội-dung">Nội dung</a></li>
  <li><a href="#thực-hành" id="toc-thực-hành" class="nav-link" data-scroll-target="#thực-hành">Thực hành</a></li>
  <li><a href="#bài-tập" id="toc-bài-tập" class="nav-link" data-scroll-target="#bài-tập">Bài tập</a></li>
  <li><a href="#tài-liệu-tham-khảo" id="toc-tài-liệu-tham-khảo" class="nav-link" data-scroll-target="#tài-liệu-tham-khảo">Tài liệu tham khảo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m01-ee-foundations/index.html">M01 · Nền tảng đánh giá kinh tế và cây quyết định</a></li><li class="breadcrumb-item"><a href="../../kb/m01-ee-foundations/l04-thresholds.html"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></h1>
<p class="subtitle lead">Ngưỡng là chi phí cơ hội, không chỉ là một bội số GDP: hiểu ngưỡng của khóa học, chọn và báo cáo cho đúng</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled" title="Vì sao bạn nên quan tâm?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vì sao bạn nên quan tâm?
</div>
</div>
<div class="callout-body-container callout-body">
<p>GDP bình quân đầu người của Việt Nam năm 2025 là 125.5 triệu VNĐ <span class="citation" data-cites="gso2026gdp2025">(<a href="../m00-r-foundations/index.html#ref-gso2026gdp2025" role="doc-biblioref">Cục Thống kê (Bộ Tài chính) 2026</a>)</span>. Lấy đúng con số đó làm ngưỡng nghĩa là coi một năm sống khỏe mạnh đáng giá tới 125.5 triệu VNĐ, bằng 24 tháng lương tối thiểu vùng I, tức gần 2 năm làm việc của một công nhân ở Hà Nội hay TP.HCM <span class="citation" data-cites="chinhphu2025nd293">(<a href="../m00-r-foundations/index.html#ref-chinhphu2025nd293" role="doc-biblioref">Chính phủ 2025</a>)</span>. Ở mức nửa GDP, con số đó còn 12 tháng lương. Quỹ có hạn: tiền trả cho xét nghiệm nhanh ở ICU là tiền không dùng được cho thuốc huyết áp ở trạm y tế xã. Bài này giải thích vì sao khóa học chọn 1 lần GDP bình quân đầu người làm ngưỡng cơ sở, 0.5 lần làm ngưỡng thấp, và cách kiểm tra kết luận có đổi khi đổi ngưỡng.</p>
</div>
</div>
<section id="mục-tiêu-học-tập" class="level2">
<h2 class="anchored" data-anchor-id="mục-tiêu-học-tập">Mục tiêu học tập</h2>
<p>Sau bài này, bạn có thể:</p>
<ol type="1">
<li>Giải thích ngưỡng chi phí-hiệu quả (cost-effectiveness threshold) như lượng sức khỏe bị mất ở nơi khác khi ngân sách dùng cho can thiệp mới.</li>
<li>Phân biệt ngưỡng phía cung (chi phí cơ hội) với ngưỡng phía cầu (mức sẵn lòng chi trả), và nêu vì sao quy tắc 1–3 lần GDP bình quân đầu người không đủ làm căn cứ.</li>
<li>Giải thích ngưỡng của khóa học (1 lần GDP bình quân đầu người, kèm 0.5 lần) và tính các ngưỡng ứng viên từ số liệu GDP.</li>
<li>Xác định ngưỡng làm quyết định đổi chiều, và diễn giải lợi ích sức khỏe ròng: QALY can thiệp mang lại trừ QALY mất do chi phí cơ hội.</li>
</ol>
</section>
<section id="ý-chính" class="level2">
<h2 class="anchored" data-anchor-id="ý-chính">Ý chính</h2>
<ul>
<li>Ngưỡng <span class="math inline">\(\lambda\)</span> là chi phí để hệ thống y tế hiện tại tạo thêm một QALY ở biên. Chi thêm <span class="math inline">\(\Delta C\)</span> làm mất khoảng <span class="math inline">\(\Delta C/\lambda\)</span> QALY ở nơi khác, nên can thiệp chỉ làm tăng sức khỏe dân số khi ICER &lt; <span class="math inline">\(\lambda\)</span> <span class="citation" data-cites="claxton2015methods woods2016country">(<a href="../m00-r-foundations/index.html#ref-claxton2015methods" role="doc-biblioref">Claxton và c.s. 2015</a>; <a href="../m00-r-foundations/index.html#ref-woods2016country" role="doc-biblioref">Woods và c.s. 2016</a>)</span>.</li>
<li>Quy tắc 1–3 lần GDP bình quân đầu người có gốc từ báo cáo năm 2001 của Ủy ban Kinh tế vĩ mô và Y tế của WHO <span class="citation" data-cites="bertram2016costeffectiveness">(<a href="../m00-r-foundations/index.html#ref-bertram2016costeffectiveness" role="doc-biblioref">Bertram và c.s. 2016</a>)</span>, không phản ánh chi phí cơ hội và đặt tiêu chuẩn quá dễ đạt <span class="citation" data-cites="marseille2015thresholds">(<a href="../m00-r-foundations/index.html#ref-marseille2015thresholds" role="doc-biblioref">Marseille và c.s. 2015</a>)</span>.</li>
<li>Ước tính dựa trên chi phí cơ hội cho nước thu nhập thấp và trung bình thường thấp hơn 1 lần GDP bình quân đầu người <span class="citation" data-cites="woods2016country ochalek2018estimating">(<a href="../m00-r-foundations/index.html#ref-woods2016country" role="doc-biblioref">Woods và c.s. 2016</a>; <a href="../m00-r-foundations/index.html#ref-ochalek2018estimating" role="doc-biblioref">Ochalek, Lomas, và Claxton 2018</a>)</span>, nhưng quy tắc GDP vẫn chiếm đa số trong các nghiên cứu ở các nước này, thường không có biện luận <span class="citation" data-cites="leech2018use kazibwe2022use">(<a href="../m00-r-foundations/index.html#ref-leech2018use" role="doc-biblioref">Leech và c.s. 2018</a>; <a href="../m00-r-foundations/index.html#ref-kazibwe2022use" role="doc-biblioref">Kazibwe và c.s. 2022</a>)</span>.</li>
<li><strong>Ngưỡng của khóa học:</strong> 1 lần GDP bình quân đầu người (125.5 triệu VNĐ/QALY) là mốc mà các phân tích chi phí-hiệu quả gần đây ở Việt Nam dùng trên thực tế <span class="citation" data-cites="ong2026costutility kieu2025costeffectiveness">(<a href="../m00-r-foundations/index.html#ref-ong2026costutility" role="doc-biblioref">Ong và c.s. 2026</a>; <a href="../m00-r-foundations/index.html#ref-kieu2025costeffectiveness" role="doc-biblioref">Kieu, Le, và Nguyen 2025</a>)</span>, không phải ngưỡng do cơ quan nhà nước ban hành. 0.5 lần (62.75 triệu VNĐ) là ngưỡng thấp theo hướng chi phí cơ hội, dùng cho phân tích độ nhạy.</li>
<li>Trong ví dụ, ICER bằng 1.4% GDP bình quân đầu người: quyết định chỉ đổi chiều với ngưỡng thấp hơn mức đó, tức thấp hơn cả cận dưới của El Salvador (11%). Chỉ một ngưỡng rất thấp như cận dưới của Malawi (1%) mới làm thường quy thắng.</li>
<li>Ngưỡng phải cùng đơn vị với ICER: ICER theo DALY không được so với khoảng ngưỡng tính theo QALY (Bài 2).</li>
<li>Ngưỡng chỉ là một đầu vào; tác động ngân sách, tính khả thi và công bằng cũng phải được cân nhắc <span class="citation" data-cites="bertram2016costeffectiveness">(<a href="../m00-r-foundations/index.html#ref-bertram2016costeffectiveness" role="doc-biblioref">Bertram và c.s. 2016</a>)</span>.</li>
</ul>
</section>
<section id="nội-dung" class="level2">
<h2 class="anchored" data-anchor-id="nội-dung">Nội dung</h2>
<section id="ngưỡng-nghĩa-là-gì" class="level3">
<h3 class="anchored" data-anchor-id="ngưỡng-nghĩa-là-gì">Ngưỡng nghĩa là gì</h3>
<p>Ngân sách y tế có hạn. Mỗi đồng chi cho xét nghiệm nhanh là một đồng không chi cho thuốc thiết yếu, nhân lực hay tiêm chủng; sức khỏe mà các việc đó lẽ ra tạo ra là <strong>chi phí cơ hội</strong> (opportunity cost). Nếu ở biên hệ thống tạo một QALY với chi phí <span class="math inline">\(\lambda\)</span> đồng, thì chi thêm <span class="math inline">\(\Delta C\)</span> làm mất khoảng <span class="math inline">\(\Delta C/\lambda\)</span> QALY. Lợi ích sức khỏe ròng (NHB) của can thiệp là:</p>
<p><span class="math display">\[
\text{NHB gia tăng} = \Delta E - \frac{\Delta C}{\lambda}.
\]</span></p>
<p>Đây là ngưỡng <strong>phía cung</strong> (supply side), phản ánh năng suất biên của hệ thống y tế; Claxton và cộng sự ước tính nó cho Anh <span class="citation" data-cites="claxton2015methods">(<a href="../m00-r-foundations/index.html#ref-claxton2015methods" role="doc-biblioref">Claxton và c.s. 2015</a>)</span>, Ochalek và cộng sự cho nước thu nhập thấp và trung bình <span class="citation" data-cites="ochalek2018estimating">(<a href="../m00-r-foundations/index.html#ref-ochalek2018estimating" role="doc-biblioref">Ochalek, Lomas, và Claxton 2018</a>)</span>. Ngưỡng <strong>phía cầu</strong> (demand side) hỏi người dân sẵn lòng trả bao nhiêu cho một QALY; câu hỏi đó liên quan đến quy mô ngân sách y tế, không phải cách phân bổ một ngân sách cố định <span class="citation" data-cites="woods2016country">(<a href="../m00-r-foundations/index.html#ref-woods2016country" role="doc-biblioref">Woods và c.s. 2016</a>)</span>.</p>
</section>
<section id="quy-tắc-theo-gdp-và-vì-sao-không-đủ-làm-căn-cứ" class="level3">
<h3 class="anchored" data-anchor-id="quy-tắc-theo-gdp-và-vì-sao-không-đủ-làm-căn-cứ">Quy tắc theo GDP và vì sao không đủ làm căn cứ</h3>
<p>WHO-CHOICE từng coi can thiệp là “rất chi phí-hiệu quả” nếu chi phí cho mỗi DALY tránh được dưới 1 lần GDP bình quân đầu người, và “chi phí-hiệu quả” nếu dưới 3 lần <span class="citation" data-cites="marseille2015thresholds hutubessy2003generalized">(<a href="../m00-r-foundations/index.html#ref-marseille2015thresholds" role="doc-biblioref">Marseille và c.s. 2015</a>; <a href="../m00-r-foundations/index.html#ref-hutubessy2003generalized" role="doc-biblioref">Hutubessy, Chisholm, và Edejer 2003</a>)</span>. Các con số này nhằm biện luận cho việc tăng đầu tư y tế, không nhằm chọn giữa các can thiệp trong một ngân sách cho trước <span class="citation" data-cites="bertram2016costeffectiveness woods2016country">(<a href="../m00-r-foundations/index.html#ref-bertram2016costeffectiveness" role="doc-biblioref">Bertram và c.s. 2016</a>; <a href="../m00-r-foundations/index.html#ref-woods2016country" role="doc-biblioref">Woods và c.s. 2016</a>)</span>. Hai điểm yếu chính, đo bằng số của chính module:</p>
<ul>
<li><strong>Không phản ánh chi phí cơ hội, nên quá dễ đạt.</strong> 1 lần GDP bình quân đầu người là 125.5 triệu VNĐ, gấp 71 lần ICER của ví dụ; gần như can thiệp hiệu quả nào cũng “đạt” <span class="citation" data-cites="marseille2015thresholds kazibwe2022use">(<a href="../m00-r-foundations/index.html#ref-marseille2015thresholds" role="doc-biblioref">Marseille và c.s. 2015</a>; <a href="../m00-r-foundations/index.html#ref-kazibwe2022use" role="doc-biblioref">Kazibwe và c.s. 2022</a>)</span>. Ngưỡng quá cao dẫn đến chấp nhận can thiệp làm giảm tổng sức khỏe dân số <span class="citation" data-cites="woods2016country ochalek2018estimating">(<a href="../m00-r-foundations/index.html#ref-woods2016country" role="doc-biblioref">Woods và c.s. 2016</a>; <a href="../m00-r-foundations/index.html#ref-ochalek2018estimating" role="doc-biblioref">Ochalek, Lomas, và Claxton 2018</a>)</span>. Một ngưỡng quy ước khác, 50,000 đô la Mỹ/QALY, cũng tồn tại bền bỉ <span class="citation" data-cites="neumann2014updating">(<a href="../m00-r-foundations/index.html#ref-neumann2014updating" role="doc-biblioref">Neumann, Cohen, và Weinstein 2014</a>)</span>.</li>
<li><strong>Bỏ qua khả năng chi trả và đặc thù quốc gia.</strong> Can thiệp “đạt ngưỡng” vẫn có thể vượt ngân sách <span class="citation" data-cites="marseille2015thresholds">(<a href="../m00-r-foundations/index.html#ref-marseille2015thresholds" role="doc-biblioref">Marseille và c.s. 2015</a>)</span>; hai nước cùng GDP có năng suất hệ thống y tế rất khác nhau <span class="citation" data-cites="bertram2016costeffectiveness">(<a href="../m00-r-foundations/index.html#ref-bertram2016costeffectiveness" role="doc-biblioref">Bertram và c.s. 2016</a>)</span>.</li>
</ul>
</section>
<section id="ngưỡng-dựa-trên-chi-phí-cơ-hội" class="level3">
<h3 class="anchored" data-anchor-id="ngưỡng-dựa-trên-chi-phí-cơ-hội">Ngưỡng dựa trên chi phí cơ hội</h3>
<p>Woods và cộng sự ngoại suy ước tính của Anh sang các nước theo thu nhập. Cận dưới của khoảng tăng theo thu nhập: Malawi (nước nghèo nhất khi nghiên cứu) 1%–51% GDP bình quân đầu người, El Salvador (ranh giới trung bình thấp và trung bình cao) 11%–51%, Kazakhstan (ranh giới trung bình cao và cao) 32%–59% <span class="citation" data-cites="woods2016country">(<a href="../m00-r-foundations/index.html#ref-woods2016country" role="doc-biblioref">Woods và c.s. 2016</a>)</span>. Việt Nam hiện thuộc nhóm thu nhập trung bình cao <span class="citation" data-cites="worldbank2026class">(<a href="../m00-r-foundations/index.html#ref-worldbank2026class" role="doc-biblioref">World Bank 2026</a>)</span>, tức nằm giữa El Salvador và Kazakhstan. Ochalek và cộng sự ước tính ngưỡng <strong>theo DALY</strong> cho từng nước, và thấy chúng có xu hướng thấp hơn khoảng 1–3 lần GDP bình quân đầu người của WHO <span class="citation" data-cites="ochalek2018estimating">(<a href="../m00-r-foundations/index.html#ref-ochalek2018estimating" role="doc-biblioref">Ochalek, Lomas, và Claxton 2018</a>)</span>. Cả hai nguồn có số riêng cho Việt Nam trong phụ lục mà module chưa đọc được (xem <code>_pending.md</code>); các khoảng ở đây chỉ cho biết độ lớn.</p>
</section>
<section id="ngưỡng-của-khóa-học-1-lần-và-0.5-lần-gdp-bình-quân-đầu-người" class="level3">
<h3 class="anchored" data-anchor-id="ngưỡng-của-khóa-học-1-lần-và-0.5-lần-gdp-bình-quân-đầu-người">Ngưỡng của khóa học: 1 lần và 0.5 lần GDP bình quân đầu người</h3>
<p>Việt Nam chưa ban hành ngưỡng chính thức. Khóa học vì vậy theo thông lệ của các nghiên cứu trong nước và đặt hai mốc, cùng lấy từ <code>../_shared/params/vn_context.csv</code> (cùng giá trị cho mọi module):</p>
<ul>
<li><strong>Ngưỡng cơ sở, 1 lần GDP bình quân đầu người</strong>: 125.5 triệu VNĐ/QALY, theo GDP 2025 của Cục Thống kê <span class="citation" data-cites="gso2026gdp2025">(<a href="../m00-r-foundations/index.html#ref-gso2026gdp2025" role="doc-biblioref">Cục Thống kê (Bộ Tài chính) 2026</a>)</span>. Đây là mốc các phân tích gần đây ở Việt Nam dùng, ví dụ phân tích chi phí-thỏa dụng theo quan điểm BHXH cho thuốc điều trị đái tháo đường <span class="citation" data-cites="ong2026costutility">(<a href="../m00-r-foundations/index.html#ref-ong2026costutility" role="doc-biblioref">Ong và c.s. 2026</a>)</span> và phân tích thuốc điều trị lạc nội mạc tử cung <span class="citation" data-cites="kieu2025costeffectiveness">(<a href="../m00-r-foundations/index.html#ref-kieu2025costeffectiveness" role="doc-biblioref">Kieu, Le, và Nguyen 2025</a>)</span>. Dùng mốc này giúp kết quả của khóa học so được với các báo cáo người học sẽ đọc. Nó <strong>không</strong> dựa trên chi phí cơ hội, và vượt cận trên của mọi khoảng Woods ước tính.</li>
<li><strong>Ngưỡng thấp, 0.5 lần GDP bình quân đầu người</strong>: 62.75 triệu VNĐ/QALY. Mốc này nằm trong khoảng Woods ước tính cho các nước có mức thu nhập như Việt Nam (từ 11% đến 59%), và đã được các nghiên cứu vắc xin ở Việt Nam dùng, tính theo DALY <span class="citation" data-cites="dang2026impact do2023impact">(<a href="../m00-r-foundations/index.html#ref-dang2026impact" role="doc-biblioref">Dang và c.s. 2026</a>; <a href="../m00-r-foundations/index.html#ref-do2023impact" role="doc-biblioref">Do và c.s. 2023</a>)</span>. Khóa học dùng nó cho phân tích độ nhạy: một kết luận chỉ đứng vững ở 1 lần GDP mà đổ ở 0.5 lần thì phải được nói rõ.</li>
<li>Cận trên 3 lần GDP chỉ dùng để thấy quy tắc cũ dễ dãi đến đâu.</li>
</ul>
<p>Bảng đặt các ngưỡng ứng viên cạnh nhau (hàng 3 lần GDP gốc tính theo DALY, ở đây chỉ dùng làm con số tham chiếu):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Ngưỡng</th>
<th>Triệu VNĐ/QALY</th>
<th>Chiến lược tối ưu</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Malawi (Woods), cận dưới, 1% GDP/người</td>
<td>1.25</td>
<td>Thường quy</td>
</tr>
<tr class="even">
<td>El Salvador (Woods), cận dưới, 11% GDP/người</td>
<td>13.80</td>
<td>Xét nghiệm nhanh + AMS</td>
</tr>
<tr class="odd">
<td>Kazakhstan (Woods), cận dưới, 32% GDP/người</td>
<td>40.16</td>
<td>Xét nghiệm nhanh + AMS</td>
</tr>
<tr class="even">
<td>Ngưỡng thấp của khóa học, 0.5 × GDP/người</td>
<td>62.75</td>
<td>Xét nghiệm nhanh + AMS</td>
</tr>
<tr class="odd">
<td>Ngưỡng cơ sở của khóa học, 1 × GDP/người</td>
<td>125.50</td>
<td>Xét nghiệm nhanh + AMS</td>
</tr>
<tr class="even">
<td>3 × GDP/người (cận trên của quy tắc WHO-CHOICE)</td>
<td>376.50</td>
<td>Xét nghiệm nhanh + AMS</td>
</tr>
</tbody>
</table>
</section>
<section id="ngưỡng-làm-thay-đổi-quyết-định-ra-sao" class="level3">
<h3 class="anchored" data-anchor-id="ngưỡng-làm-thay-đổi-quyết-định-ra-sao">Ngưỡng làm thay đổi quyết định ra sao</h3>
<p>ICER của xét nghiệm nhanh kèm AMS so với thường quy là 1.76 triệu VNĐ/QALY. Ở ngưỡng 1% GDP/người (cận dưới của Malawi), chi thêm 0.69 triệu VNĐ mỗi người bệnh làm mất 550.8 QALY ở nơi khác trên mỗi 1,000 người bệnh, trong khi can thiệp chỉ mang lại 392.2: lợi ích ròng <strong>âm</strong> (-158.6 QALY). Ở cận dưới của El Salvador, lợi ích ròng là 342.1 QALY; ở ngưỡng thấp của khóa học là 381.2 QALY. Với ví dụ này, kết luận đứng vững từ cận dưới của El Salvador trở lên, tức trên mọi ngưỡng trong bảng trừ hàng Malawi. Với một can thiệp có ICER nằm giữa hai ngưỡng của khóa học (từ 62.75 triệu VNĐ đến 125.5 triệu VNĐ/QALY), hai ngưỡng cho hai kết luận trái ngược, và khi đó phải nêu rõ và biện luận.</p>
<p>Thước đo kết cục tương tác với ngưỡng. ICER theo DALY bằng 0.9% GDP bình quân đầu người, nhưng con số đó không được so với khoảng tính theo QALY của Woods (Bài tập 2).</p>
</section>
<section id="báo-cáo-khi-chưa-có-ngưỡng-chính-thức" class="level3">
<h3 class="anchored" data-anchor-id="báo-cáo-khi-chưa-có-ngưỡng-chính-thức">Báo cáo khi chưa có ngưỡng chính thức</h3>
<p>Ba việc nên làm: (1) trình bày kết quả trên <strong>một dải ngưỡng</strong> và chỉ rõ điểm đổi quyết định (<a href="#fig-l04-curve" class="quarto-xref">Hình&nbsp;<span>11.1</span></a>; M03 mở rộng bằng CEAC); (2) báo cáo cả ngưỡng cơ sở 1 lần GDP lẫn ngưỡng thấp 0.5 lần, và ghi rõ ngưỡng theo GDP chỉ là quy ước so sánh; (3) báo cáo kèm tác động ngân sách và công bằng <span class="citation" data-cites="bertram2016costeffectiveness">(<a href="../m00-r-foundations/index.html#ref-bertram2016costeffectiveness" role="doc-biblioref">Bertram và c.s. 2016</a>)</span>.</p>
</section>
</section>
<section id="thực-hành" class="level2">
<h2 class="anchored" data-anchor-id="thực-hành">Thực hành</h2>
<p>Nạp mô hình, dựng đường biên, lấy ICER của chiến lược duy nhất còn lại trên đường biên ngoài thường quy, và đổi nó thành tỷ lệ GDP bình quân đầu người. Chunk cũng kiểm tra hai ngưỡng của khóa học đúng bằng 1 lần và 0.5 lần GDP.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">isTRUE</span>(<span class="fu">l10n_info</span>()[[<span class="st">"UTF-8"</span>]])) <span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_CTYPE"</span>, <span class="st">"en_US.UTF-8"</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/helpers.R"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/vn_data.R"</span>)   <span class="co"># course-wide values: threshold, life table, CPI, prices</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"code/model.R"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">load_params</span>()                   <span class="co"># module parameters + shared values, costs in 2025 VND</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">run_tree</span>(p)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>fr <span class="ot">&lt;-</span> <span class="fu">efficiency_frontier</span>(res<span class="sc">$</span>strategy, res<span class="sc">$</span>cost, res<span class="sc">$</span>qaly)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>icer_main <span class="ot">&lt;-</span> fr<span class="sc">$</span>icer[fr<span class="sc">$</span>strategy <span class="sc">==</span> <span class="st">"rdt_ams"</span>]</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>gdp <span class="ot">&lt;-</span> p<span class="sc">$</span>gdp_pc_vnd                  <span class="co"># 2025 GDP per capita (shared, GSO)</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># The same ICER as a share of GDP per capita: decisions flip only below this share</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>icer_share_gdp <span class="ot">&lt;-</span> icer_main <span class="sc">/</span> gdp</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">icer_million =</span> icer_main <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">share_of_gdp =</span> icer_share_gdp), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>icer_million share_of_gdp 
      1.7624       0.0140 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The course thresholds are fixed multiples of GDP per capita (vn_context() also checks this)</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>wtp_high <span class="ot">&lt;-</span> <span class="fu">param_bounds</span>(p, <span class="st">"wtp"</span>)[[<span class="st">"high"</span>]]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">wtp =</span> p<span class="sc">$</span>wtp, <span class="at">wtp_low =</span> p<span class="sc">$</span>wtp_low, <span class="at">wtp_high =</span> wtp_high) <span class="sc">/</span> gdp, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     wtp  wtp_low wtp_high 
     1.0      0.5      3.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(p<span class="sc">$</span>wtp <span class="sc">/</span> gdp <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">&lt;</span> <span class="fl">1e-12</span>, <span class="fu">abs</span>(p<span class="sc">$</span>wtp_low <span class="sc">/</span> gdp <span class="sc">-</span> <span class="fl">0.5</span>) <span class="sc">&lt;</span> <span class="fl">1e-12</span>, <span class="fu">abs</span>(wtp_high <span class="sc">/</span> gdp <span class="sc">-</span> <span class="dv">3</span>) <span class="sc">&lt;</span> <span class="fl">1e-12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Tính các ngưỡng ứng viên từ GDP bình quân đầu người năm 2025, rồi tìm chiến lược tối ưu ở mỗi ngưỡng bằng NMB lớn nhất. Kiểm tra: quyết định chỉ khác ở ngưỡng thấp hơn ICER.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Candidate thresholds for Viet Nam (VND per QALY), from 2025 GDP per capita</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>thresholds <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">code =</span> <span class="fu">c</span>(<span class="st">"mwi_low"</span>, <span class="st">"slv_low"</span>, <span class="st">"kaz_low"</span>, <span class="st">"course_low"</span>, <span class="st">"course"</span>, <span class="st">"gdp3"</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">rule =</span> <span class="fu">c</span>(<span class="fu">paste0</span>(<span class="st">"Malawi (Woods), cận dưới, "</span>, <span class="fu">fmt_pct</span>(p<span class="sc">$</span>ocet_pct_low_mwi, <span class="dv">0</span>), <span class="st">" GDP/người"</span>),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>           <span class="fu">paste0</span>(<span class="st">"El Salvador (Woods), cận dưới, "</span>, <span class="fu">fmt_pct</span>(p<span class="sc">$</span>ocet_pct_low_slv, <span class="dv">0</span>), <span class="st">" GDP/người"</span>),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>           <span class="fu">paste0</span>(<span class="st">"Kazakhstan (Woods), cận dưới, "</span>, <span class="fu">fmt_pct</span>(p<span class="sc">$</span>ocet_pct_low_kaz, <span class="dv">0</span>), <span class="st">" GDP/người"</span>),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>           <span class="st">"Ngưỡng thấp của khóa học, 0.5 × GDP/người"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>           <span class="st">"Ngưỡng cơ sở của khóa học, 1 × GDP/người"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>           <span class="st">"3 × GDP/người (cận trên của quy tắc WHO-CHOICE)"</span>),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">k =</span> <span class="fu">c</span>(p<span class="sc">$</span>ocet_pct_low_mwi <span class="sc">*</span> gdp, p<span class="sc">$</span>ocet_pct_low_slv <span class="sc">*</span> gdp, p<span class="sc">$</span>ocet_pct_low_kaz <span class="sc">*</span> gdp,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>        p<span class="sc">$</span>wtp_low, p<span class="sc">$</span>wtp, wtp_high)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>thresholds<span class="sc">$</span>k_million <span class="ot">&lt;-</span> <span class="fu">round</span>(thresholds<span class="sc">$</span>k <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">2</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>thresholds<span class="sc">$</span>share_gdp <span class="ot">&lt;-</span> <span class="fu">round</span>(thresholds<span class="sc">$</span>k <span class="sc">/</span> gdp, <span class="dv">3</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>thresholds<span class="sc">$</span>best <span class="ot">&lt;-</span> <span class="fu">sapply</span>(thresholds<span class="sc">$</span>k, <span class="cf">function</span>(k) <span class="fu">best_strategy</span>(res, k))</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(thresholds) <span class="ot">&lt;-</span> thresholds<span class="sc">$</span>code</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>thresholds[, <span class="fu">c</span>(<span class="st">"rule"</span>, <span class="st">"k_million"</span>, <span class="st">"share_gdp"</span>, <span class="st">"best"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                      rule k_million share_gdp
mwi_low             Malawi (Woods), cận dưới, 1% GDP/người      1.25      0.01
slv_low       El Salvador (Woods), cận dưới, 11% GDP/người     13.80      0.11
kaz_low        Kazakhstan (Woods), cận dưới, 32% GDP/người     40.16      0.32
course_low       Ngưỡng thấp của khóa học, 0.5 × GDP/người     62.75      0.50
course            Ngưỡng cơ sở của khóa học, 1 × GDP/người    125.50      1.00
gdp3       3 × GDP/người (cận trên của quy tắc WHO-CHOICE)    376.50      3.00
              best
mwi_low      usual
slv_low    rdt_ams
kaz_low    rdt_ams
course_low rdt_ams
course     rdt_ams
gdp3       rdt_ams</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The decision flips only at the very low Malawian bound, because the ICER (about 1.4% of</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GDP per capita) lies between the Malawian and the Salvadoran lower bounds; the prose relies on this</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(thresholds[<span class="st">"mwi_low"</span>, <span class="st">"best"</span>] <span class="sc">==</span> <span class="st">"usual"</span>, <span class="fu">all</span>(thresholds<span class="sc">$</span>best[<span class="sc">-</span><span class="dv">1</span>] <span class="sc">==</span> <span class="st">"rdt_ams"</span>),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>          p<span class="sc">$</span>ocet_pct_low_mwi <span class="sc">&lt;</span> icer_share_gdp, icer_share_gdp <span class="sc">&lt;</span> p<span class="sc">$</span>ocet_pct_low_slv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Vẽ NMB gia tăng so với thường quy theo ngưỡng. Đường của xét nghiệm nhanh kèm AMS phải đổi dấu đúng tại ICER (kiểm tra trên chính các điểm của đường vẽ).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Incremental NMB of each strategy versus usual care across thresholds:</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># a line crosses zero exactly at that strategy's ICER versus usual care</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>k_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">1.2</span> <span class="sc">*</span> gdp, <span class="at">length.out =</span> <span class="dv">241</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>curve <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (s <span class="cf">in</span> STRATEGIES[<span class="sc">-</span><span class="dv">1</span>]) {</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> <span class="fu">incremental</span>(res, s, <span class="st">"usual"</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  curve <span class="ot">&lt;-</span> <span class="fu">rbind</span>(curve, <span class="fu">data.frame</span>(<span class="at">strategy =</span> STRATEGY_LABELS[[s]], <span class="at">k =</span> k_grid,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">inmb =</span> d[[<span class="st">"qaly"</span>]] <span class="sc">*</span> k_grid <span class="sc">-</span> d[[<span class="st">"cost"</span>]]))</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>curve<span class="sc">$</span>strategy <span class="ot">&lt;-</span> <span class="fu">factor</span>(curve<span class="sc">$</span>strategy, <span class="at">levels =</span> STRATEGY_LABELS[<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>marks <span class="ot">&lt;-</span> thresholds[<span class="fu">c</span>(<span class="st">"slv_low"</span>, <span class="st">"kaz_low"</span>, <span class="st">"course_low"</span>, <span class="st">"course"</span>), ]</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>fig_curve <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(curve, <span class="fu">aes</span>(k <span class="sc">/</span> <span class="fl">1e6</span>, inmb <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">colour =</span> strategy)) <span class="sc">+</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">colour =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"segment"</span>, <span class="at">x =</span> marks<span class="sc">$</span>k <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">xend =</span> marks<span class="sc">$</span>k <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">y =</span> <span class="fu">min</span>(curve<span class="sc">$</span>inmb) <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">yend =</span> <span class="fl">1.07</span> <span class="sc">*</span> <span class="fu">max</span>(curve<span class="sc">$</span>inmb) <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">linetype =</span> <span class="st">"22"</span>, <span class="at">colour =</span> <span class="st">"grey60"</span>) <span class="sc">+</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> marks<span class="sc">$</span>k <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">y =</span> <span class="fl">1.1</span> <span class="sc">*</span> <span class="fu">max</span>(curve<span class="sc">$</span>inmb) <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="fu">c</span>(<span class="fu">paste0</span>(<span class="st">"El Salvador</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">fmt_pct</span>(p<span class="sc">$</span>ocet_pct_low_slv, <span class="dv">0</span>), <span class="st">" GDP"</span>),</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">paste0</span>(<span class="st">"Kazakhstan</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">fmt_pct</span>(p<span class="sc">$</span>ocet_pct_low_kaz, <span class="dv">0</span>), <span class="st">" GDP"</span>), <span class="st">"0.5 × GDP"</span>, <span class="st">"1 × GDP"</span>),</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>           <span class="at">vjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_limits</span>(<span class="at">y =</span> <span class="fl">1.25</span> <span class="sc">*</span> <span class="fu">max</span>(curve<span class="sc">$</span>inmb) <span class="sc">/</span> <span class="fl">1e6</span>) <span class="sc">+</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> pal_course[<span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">2</span>)], <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Ngưỡng chi phí-hiệu quả (triệu VNĐ/QALY)"</span>,</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"NMB gia tăng so với thường quy (triệu VNĐ)"</span>,</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Chiến lược tốt nhất phụ thuộc vào ngưỡng"</span>,</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Đường cắt trục 0 tại ICER so với thường quy; đường cao nhất là lựa chọn tối ưu"</span>) <span class="sc">+</span></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_curve, <span class="st">"l04-nmb-threshold.png"</span>)</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Check on the plotted curve itself (not on the ICER formula): the rapid test + AMS line</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a><span class="co"># changes sign exactly where the grid crosses the ICER</span></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>d_main <span class="ot">&lt;-</span> <span class="fu">incremental</span>(res, <span class="st">"rdt_ams"</span>, <span class="st">"usual"</span>)</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>line_ams <span class="ot">&lt;-</span> curve[curve<span class="sc">$</span>strategy <span class="sc">==</span> STRATEGY_LABELS[[<span class="st">"rdt_ams"</span>]], ]</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>sign_change <span class="ot">&lt;-</span> line_ams<span class="sc">$</span>k[<span class="fu">which</span>(<span class="fu">diff</span>(<span class="fu">sign</span>(line_ams<span class="sc">$</span>inmb)) <span class="sc">!=</span> <span class="dv">0</span>)[<span class="dv">1</span>] <span class="sc">+</span> <span class="dv">1</span>]</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(sign_change <span class="sc">-</span> icer_main) <span class="sc">&lt;=</span> <span class="fu">diff</span>(k_grid)[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-l04-curve" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-l04-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/l04-nmb-threshold.png" class="img-fluid figure-img" style="width:85.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-l04-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Hình&nbsp;1: NMB gia tăng so với thường quy theo ngưỡng. Đường cao nhất ở mỗi ngưỡng là lựa chọn tối ưu; thường quy là trục 0.
</figcaption>
</figure>
</div>
<p>Quy chi phí gia tăng thành QALY bị mất ở nơi khác. Kiểm tra: lợi ích sức khỏe ròng dương đúng khi ICER thấp hơn ngưỡng (so trên giá trị chưa làm tròn).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># What a threshold means: extra spending displaces health elsewhere.</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Per 1,000 patients: QALYs gained vs QALYs forgone (= extra cost / k)</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>k_set <span class="ot">&lt;-</span> thresholds[<span class="fu">c</span>(<span class="st">"mwi_low"</span>, <span class="st">"slv_low"</span>, <span class="st">"course_low"</span>, <span class="st">"course"</span>), <span class="st">"k"</span>]</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>opp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">k_million =</span> <span class="fu">round</span>(k_set <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">2</span>),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">qaly_gained =</span> <span class="dv">1000</span> <span class="sc">*</span> d_main[[<span class="st">"qaly"</span>]],</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">qaly_forgone =</span> <span class="dv">1000</span> <span class="sc">*</span> d_main[[<span class="st">"cost"</span>]] <span class="sc">/</span> k_set</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>opp<span class="sc">$</span>net_health <span class="ot">&lt;-</span> opp<span class="sc">$</span>qaly_gained <span class="sc">-</span> opp<span class="sc">$</span>qaly_forgone</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Net health benefit is positive exactly when the ICER is below the threshold</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co"># (checked on unrounded values; rounding is only for display)</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>((opp<span class="sc">$</span>net_health <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">==</span> (icer_main <span class="sc">&lt;</span> k_set)))</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>opp[, <span class="sc">-</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(opp[, <span class="sc">-</span><span class="dv">1</span>], <span class="dv">1</span>)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>opp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  k_million qaly_gained qaly_forgone net_health
1      1.25       392.2        550.8     -158.6
2     13.80       392.2         50.1      342.1
3     62.75       392.2         11.0      381.2
4    125.50       392.2          5.5      386.7</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Mẹo thực hành">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mẹo thực hành
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Vẽ NMB gia tăng theo một dải ngưỡng trước khi viết kết luận: hình trả lời ngay “ở ngưỡng nào kết luận đổi”.</li>
<li>Lấy ngưỡng từ cùng một nguồn cho mọi phân tích (trong khóa học là <code>vn_context()</code>), và quy về cùng năm giá, đơn vị tiền tệ với mô hình (M09).</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Lỗi thường gặp">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lỗi thường gặp
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Viết “đạt chi phí-hiệu quả theo khuyến cáo của WHO (1–3 lần GDP)”</strong> như một căn cứ. Hãy nói rõ 1 lần GDP là quy ước thực hành, và báo cáo thêm ngưỡng theo chi phí cơ hội.</li>
<li><strong>Mượn khoảng ngưỡng của nước khác</strong> mà không nói. Cận dưới tăng theo thu nhập, nên có thể đảo kết luận.</li>
<li><strong>Trộn đơn vị</strong>: ICER theo DALY với ngưỡng theo QALY, hoặc USD với VNĐ, hoặc GDP khác năm giá.</li>
</ul>
</div>
</div>
</section>
<section id="bài-tập" class="level2">
<h2 class="anchored" data-anchor-id="bài-tập">Bài tập</h2>
<p><strong>Bài 1 (dễ).</strong> Có ngưỡng nào mà phủ CR cho mọi ca là lựa chọn tối ưu không? Giải thích bằng kết quả Bài 3.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Không. Trên lưới 241 ngưỡng, chiến lược tối ưu chỉ là Xét nghiệm nhanh + AMS hoặc Thường quy (bảng dưới). Phủ CR (kháng carbapenem) cho mọi ca bị lấn át tuyệt đối: đắt hơn và ít QALY hơn xét nghiệm nhanh kèm AMS, nên NMB thấp hơn ở mọi ngưỡng dương. Điều này đúng với độ nhạy hiệu dụng cơ sở; Bài 3 cho thấy nó đổi khi xét nghiệm kém hơn.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 1: is there any threshold at which "cover-all" is the best choice?</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>best_on_grid <span class="ot">&lt;-</span> <span class="fu">sapply</span>(k_grid, <span class="cf">function</span>(k) <span class="fu">best_strategy</span>(res, k))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(best_on_grid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>best_on_grid
rdt_ams   usual 
    238       3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(best_on_grid <span class="sc">==</span> <span class="st">"cover_all"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
</div>
</div>
</div>
<p><strong>Bài 2 (trung bình).</strong> Tính ICER theo DALY tránh được và theo QALY tăng thêm, mỗi cái bằng tỷ lệ GDP bình quân đầu người. Vì sao không được so ICER theo DALY với cận dưới 11% của Woods?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>ICER theo DALY là 1.14 triệu VNĐ, bằng 0.9% GDP/người; theo QALY là 1.4%. Khoảng của Woods tính theo QALY, nên so ICER theo DALY với nó là sai đơn vị. Phải so ICER theo DALY với ngưỡng theo DALY (như của Ochalek), hoặc ICER theo QALY với ngưỡng theo QALY. Ngưỡng 1 lần GDP của khóa học được dùng cho cả hai đơn vị chỉ vì nó là quy ước, không phải ước tính.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 2: spot the unit error. The ICER per DALY averted is a different number from</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the ICER per QALY gained, so it cannot be set against a per-QALY threshold</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>fr_daly <span class="ot">&lt;-</span> <span class="fu">efficiency_frontier</span>(res<span class="sc">$</span>strategy, res<span class="sc">$</span>cost, <span class="sc">-</span>res<span class="sc">$</span>daly)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>icer_daly <span class="ot">&lt;-</span> fr_daly<span class="sc">$</span>icer[fr_daly<span class="sc">$</span>strategy <span class="sc">==</span> <span class="st">"rdt_ams"</span>]</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">icer_per_qaly_million =</span> icer_main <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">icer_per_daly_million =</span> icer_daly <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">share_gdp_qaly =</span> icer_main <span class="sc">/</span> gdp, <span class="at">share_gdp_daly =</span> icer_daly <span class="sc">/</span> gdp), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>icer_per_qaly_million icer_per_daly_million        share_gdp_qaly 
                1.762                 1.138                 0.014 
       share_gdp_daly 
                0.009 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p><strong>Bài 3 (khó).</strong> Ở ngưỡng thấp của khóa học (0.5 lần GDP bình quân đầu người), giá xét nghiệm tối đa để xét nghiệm nhanh kèm AMS vẫn tốt hơn thường quy là bao nhiêu? So với giá BHYT hiện hành.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Giá xét nghiệm cộng thẳng vào chi phí kỳ vọng, nên giá tối đa <span class="math inline">\(= c_{\text{test}} + \Delta E \cdot \lambda - \Delta C\)</span>: 24.69 triệu VNĐ, gấp 32 lần giá 771,700 VNĐ <span class="citation" data-cites="byt2024qd3220">(<a href="../m00-r-foundations/index.html#ref-byt2024qd3220" role="doc-biblioref">Bộ Y tế 2024</a>)</span>. Chunk kiểm tra bằng bộ tìm nghiệm của Bài 5. Lưu ý: đây là so với thường quy; với nhiều chiến lược, đối thủ mạnh nhất có thể khác và giá tối đa thấp hơn (Bài 5).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 3: highest test price at which rapid test + AMS still beats usual care at the</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># course's low threshold (0.5 x GDP per capita). The test price adds one-for-one to expected</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># cost, so the maximum price solves  dQALY x k - (dCost + (price - base price)) = 0</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>k_low <span class="ot">&lt;-</span> p<span class="sc">$</span>wtp_low</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>price_max <span class="ot">&lt;-</span> p<span class="sc">$</span>c_test <span class="sc">+</span> d_main[[<span class="st">"qaly"</span>]] <span class="sc">*</span> k_low <span class="sc">-</span> d_main[[<span class="st">"cost"</span>]]</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">threshold_million =</span> k_low <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">price_max_million =</span> price_max <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">base_price_million =</span> p<span class="sc">$</span>c_test <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">ratio =</span> price_max <span class="sc">/</span> p<span class="sc">$</span>c_test), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> threshold_million  price_max_million base_price_million              ratio 
            62.750             24.692              0.772             31.997 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check against the root finder of Lesson 5 (a preview of threshold_value())</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>q <span class="ot">&lt;-</span> <span class="fu">modifyList</span>(p, <span class="fu">list</span>(<span class="at">wtp =</span> k_low))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>price_root <span class="ot">&lt;-</span> <span class="fu">threshold_value</span>(q, <span class="st">"c_test"</span>, <span class="at">lower =</span> <span class="dv">0</span>, <span class="at">upper =</span> <span class="dv">100</span> <span class="sc">*</span> price_max, <span class="at">outcome =</span> inmb)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(price_root <span class="sc">-</span> price_max) <span class="sc">&lt;</span> <span class="dv">1</span>, price_max <span class="sc">&gt;</span> p<span class="sc">$</span>c_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="tài-liệu-tham-khảo" class="level2">
<h2 class="anchored" data-anchor-id="tài-liệu-tham-khảo">Tài liệu tham khảo</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-bertram2016costeffectiveness" class="csl-entry" role="listitem">
Bertram, Melanie Y, Jeremy A Lauer, Kees De Joncheere, Tessa Edejer, Raymond Hutubessy, Marie-Paule Kieny, và Suzanne R Hill. 2016. <span>“Cost-effectiveness thresholds: pros and cons”</span>. <em>Bulletin of the World Health Organization</em> 94 (12): 925–30. <a href="https://doi.org/10.2471/BLT.15.164418">https://doi.org/10.2471/BLT.15.164418</a>.
</div>
<div id="ref-byt2024qd3220" class="csl-entry" role="listitem">
Bộ Y tế. 2024. <span>“Quyết định số 3220/<span>QĐ-BYT</span> ngày 01/11/2024 về giá dịch vụ khám bệnh, chữa bệnh áp dụng tại Bệnh viện Bạch Mai”</span>. 1 Tháng Mười-Một 2024. <a href="https://apicms.bachmai.gov.vn/documents/37204/1543632/8_Nov_2024_022948_GMTupload_00004592.pdf/b3ab6717-2151-db08-9913-3cfbfd7e0738">https://apicms.bachmai.gov.vn/documents/37204/1543632/8_Nov_2024_022948_GMTupload_00004592.pdf/b3ab6717-2151-db08-9913-3cfbfd7e0738</a>.
</div>
<div id="ref-chinhphu2025nd293" class="csl-entry" role="listitem">
Chính phủ. 2025. <span>“Nghị định 293/2025/<span>NĐ-CP</span> quy định mức lương tối thiểu đối với người lao động làm việc theo hợp đồng lao động (hiệu lực từ 1/1/2026)”</span>. 2025. <a href="https://hatinh.gov.vn/vi/bai-viet/tang-luong-toi-thieu-vung-tu-112026">https://hatinh.gov.vn/vi/bai-viet/tang-luong-toi-thieu-vung-tu-112026</a>.
</div>
<div id="ref-claxton2015methods" class="csl-entry" role="listitem">
Claxton, Karl, Steve Martin, Marta Soares, Nigel Rice, Eldon Spackman, Sebastian Hinde, Nancy Devlin, Peter C Smith, và Mark Sculpher. 2015. <span>“Methods for the estimation of the National Institute for Health and Care Excellence cost-effectiveness threshold”</span>. <em>Health technology assessment (Winchester, England)</em> 19 (14): 1–503, v–vi. <a href="https://doi.org/10.3310/hta19140">https://doi.org/10.3310/hta19140</a>.
</div>
<div id="ref-gso2026gdp2025" class="csl-entry" role="listitem">
Cục Thống kê (Bộ Tài chính). 2026. <span>“Họp báo công bố tình hình kinh tế – xã hội quý <span>IV</span> và năm 2025”</span>. 5 Tháng Giêng 2026. <a href="https://www.nso.gov.vn/?p=59699">https://www.nso.gov.vn/?p=59699</a>.
</div>
<div id="ref-dang2026impact" class="csl-entry" role="listitem">
Dang, Huyen Thi Thanh, Andrew Clark, An Le Thanh Nguyen, Hong Thi Duong, Trung Thanh Nguyen, Thanh Trung Tran, Lam Ngoc Tung Cu, Dung Chi Tham, Nga Tuyet Nguyen, và Frédéric Debellut. 2026. <span>“Impact and cost-effectiveness of national implementation of rotavirus vaccination in <span>Vietnam</span>: A modeling study”</span>. <em>Vaccine</em> 93: 129220. <a href="https://doi.org/10.1016/j.vaccine.2026.129220">https://doi.org/10.1016/j.vaccine.2026.129220</a>.
</div>
<div id="ref-do2023impact" class="csl-entry" role="listitem">
Do, Lien Anh Ha, Nguyen Thanh Nhan Le, Sarwat Mahmud, Kim Mulholland, Clint Pecenka, và Andrew Clark. 2023. <span>“Impact and cost-effectiveness of strategies to prevent respiratory syncytial virus (<span>RSV</span>) disease in <span>Vietnam</span>: A modelling study”</span>. <em>Vaccine</em> 41 (46): 6782–90. <a href="https://doi.org/10.1016/j.vaccine.2023.09.003">https://doi.org/10.1016/j.vaccine.2023.09.003</a>.
</div>
<div id="ref-hutubessy2003generalized" class="csl-entry" role="listitem">
Hutubessy, Raymond, Dan Chisholm, và Tessa Tan-Torres Edejer. 2003. <span>“Generalized cost-effectiveness analysis for national-level priority-setting in the health sector”</span>. <em>Cost effectiveness and resource allocation : C/E</em> 1 (1): 8. <a href="https://doi.org/10.1186/1478-7547-1-8">https://doi.org/10.1186/1478-7547-1-8</a>.
</div>
<div id="ref-kazibwe2022use" class="csl-entry" role="listitem">
Kazibwe, Joseph, Adrian Gheorghe, David Wilson, Francis Ruiz, Kalipso Chalkidou, và Y-Ling Chi. 2022. <span>“The Use of Cost-Effectiveness Thresholds for Evaluating Health Interventions in Low- and Middle-Income Countries From 2015 to 2020: A Review”</span>. <em>Value in health : the journal of the International Society for Pharmacoeconomics and Outcomes Research</em> 25 (3): 385–89. <a href="https://doi.org/10.1016/j.jval.2021.08.014">https://doi.org/10.1016/j.jval.2021.08.014</a>.
</div>
<div id="ref-kieu2025costeffectiveness" class="csl-entry" role="listitem">
Kieu, Mai Thi Tuyet, Minh Hong Le, và Chi Phuong Nguyen. 2025. <span>“Cost-effectiveness of dienogest compared to gonadotropin releasing hormone agonists for the management of endometriosis in <span>Vietnam</span>”</span>. <em>Cost Effectiveness and Resource Allocation</em> 23 (1): 51. <a href="https://doi.org/10.1186/s12962-025-00655-3">https://doi.org/10.1186/s12962-025-00655-3</a>.
</div>
<div id="ref-leech2018use" class="csl-entry" role="listitem">
Leech, Ashley A, David D Kim, Joshua T Cohen, và Peter J Neumann. 2018. <span>“Use and Misuse of Cost-Effectiveness Analysis Thresholds in Low- and Middle-Income Countries: Trends in Cost-per-DALY Studies”</span>. <em>Value in health : the journal of the International Society for Pharmacoeconomics and Outcomes Research</em> 21 (7): 759–61. <a href="https://doi.org/10.1016/j.jval.2017.12.016">https://doi.org/10.1016/j.jval.2017.12.016</a>.
</div>
<div id="ref-marseille2015thresholds" class="csl-entry" role="listitem">
Marseille, Elliot, Bruce Larson, Dhruv S Kazi, James G Kahn, và Sydney Rosen. 2015. <span>“Thresholds for the cost-effectiveness of interventions: alternative approaches”</span>. <em>Bulletin of the World Health Organization</em> 93 (2): 118–24. <a href="https://doi.org/10.2471/BLT.14.138206">https://doi.org/10.2471/BLT.14.138206</a>.
</div>
<div id="ref-neumann2014updating" class="csl-entry" role="listitem">
Neumann, Peter J, Joshua T Cohen, và Milton C Weinstein. 2014. <span>“Updating cost-effectiveness–the curious resilience of the $50,000-per-QALY threshold”</span>. <em>The New England journal of medicine</em> 371 (9): 796–97. <a href="https://doi.org/10.1056/NEJMp1405158">https://doi.org/10.1056/NEJMp1405158</a>.
</div>
<div id="ref-ochalek2018estimating" class="csl-entry" role="listitem">
Ochalek, Jessica, James Lomas, và Karl Claxton. 2018. <span>“Estimating health opportunity costs in low-income and middle-income countries: a novel approach and evidence from cross-country data”</span>. <em>BMJ global health</em> 3 (6): e000964. <a href="https://doi.org/10.1136/bmjgh-2018-000964">https://doi.org/10.1136/bmjgh-2018-000964</a>.
</div>
<div id="ref-ong2026costutility" class="csl-entry" role="listitem">
Ong, The Due, Anh Son Dao, Quoc Trung Ly, Thi Tuyet Mai Kieu, và Hong Minh Le. 2026. <span>“Cost-effectiveness of luseogliflozin for the management of type 2 diabetes mellitus in <span>Vietnam</span>: a <span>Markov</span> model analysis from the <span>Vietnam</span> social health insurance perspective”</span>. <em>Cost Effectiveness and Resource Allocation</em> 24 (1). <a href="https://doi.org/10.1186/s12962-026-00797-y">https://doi.org/10.1186/s12962-026-00797-y</a>.
</div>
<div id="ref-woods2016country" class="csl-entry" role="listitem">
Woods, Beth, Paul Revill, Mark Sculpher, và Karl Claxton. 2016. <span>“Country-Level Cost-Effectiveness Thresholds: Initial Estimates and the Need for Further Research”</span>. <em>Value in health : the journal of the International Society for Pharmacoeconomics and Outcomes Research</em> 19 (8): 929–35. <a href="https://doi.org/10.1016/j.jval.2016.02.017">https://doi.org/10.1016/j.jval.2016.02.017</a>.
</div>
<div id="ref-worldbank2026class" class="csl-entry" role="listitem">
World Bank. 2026. <span>“Country record for <span>Viet Nam</span>: income level <span>‘Upper middle income’</span> (country API)”</span>. <a href="https://api.worldbank.org/v2/country/VNM?format=json">https://api.worldbank.org/v2/country/VNM?format=json</a>.
</div>
</div>
<div class="video-script">
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kịch bản video (~14 phút)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Slide</th>
<th>Lời giảng chính</th>
<th>Hình/Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Câu hỏi</td>
<td>Trả bao nhiêu cho một năm sống khỏe mạnh? 1 lần GDP bằng gần hai năm lương tối thiểu</td>
<td>Hộp “Vì sao bạn nên quan tâm?”</td>
</tr>
<tr class="even">
<td>2</td>
<td>Chi phí cơ hội</td>
<td>Ngân sách cố định; tiền cho việc này là sức khỏe mất ở việc khác</td>
<td>Công thức NHB</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Phía cung và phía cầu</td>
<td>Năng suất biên của hệ thống so với mức sẵn lòng chi trả</td>
<td>Sơ đồ hai khái niệm</td>
</tr>
<tr class="even">
<td>4</td>
<td>Quy tắc 1–3 lần GDP</td>
<td>Nguồn gốc 2001; vì sao bị phê phán</td>
<td>Hai điểm yếu</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Vẫn được dùng nhiều</td>
<td>Đa số nghiên cứu ở nước thu nhập thấp và trung bình; ít biện luận</td>
<td>Leech 2018, Kazibwe 2022</td>
</tr>
<tr class="even">
<td>6</td>
<td>Ước tính chi phí cơ hội</td>
<td>Cận dưới tăng theo thu nhập; Việt Nam nằm giữa El Salvador và Kazakhstan</td>
<td>Woods 2016, Ochalek 2018</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Ngưỡng của khóa học</td>
<td>1 lần GDP: thông lệ các CEA ở Việt Nam; 0.5 lần: độ nhạy theo chi phí cơ hội</td>
<td>Chunk <code>l04-candidates</code></td>
</tr>
<tr class="even">
<td>8</td>
<td>Quyết định đổi chiều</td>
<td>Chỉ ở ngưỡng thấp hơn ICER; NMB gia tăng theo ngưỡng</td>
<td><code>figs/l04-nmb-threshold.png</code></td>
</tr>
<tr class="odd">
<td>9</td>
<td>QALY được và QALY mất</td>
<td>Trên 1,000 người bệnh, ở bốn ngưỡng</td>
<td>Chunk <code>l04-opportunity</code></td>
</tr>
<tr class="even">
<td>10</td>
<td>Báo cáo đúng cách</td>
<td>Dải ngưỡng; cả 1 lần và 0.5 lần GDP; kèm tác động ngân sách và công bằng</td>
<td>Danh sách ba bước</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../kb/m01-ee-foundations/l03-decision-rules.html" class="pagination-link" aria-label="Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../kb/m01-ee-foundations/l05-decision-tree.html" class="pagination-link" aria-label="Bài 5: Xây cây quyết định từ đầu trong R">
        <span class="nav-page-text"><span class="chapter-title">Bài 5: Xây cây quyết định từ đầu trong R</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>