project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "write/**"
    - "learn/**"
    - "dissect/**"

lang: vi

website:
  title: "quan nguyen"
  repo-url: https://github.com/quan-nk/quan-nk.github.io
  search:
    location: sidebar
    type: textbox
  navbar:
    background: dark
    left:
      - text: "write"
        href: write/index.qmd
      - text: "learn"
        href: learn/index.qmd
      - text: "dissect"
        href: dissect/index.qmd
      - text: "resources"
        href: resources.qmd
      - text: "about"
        href: about.qmd
  sidebar:
    style: docked
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "home"
      - text: "---"
      - section: "write"
        contents:
          - href: write/index.qmd
            text: "all posts"
          - section: "blogs"
            contents: write/blogs
          - section: "books"
            contents: write/books
      - text: "---"
      - section: "learn"
        contents:
          - href: learn/index.qmd
            text: "overview"
          - section: "measure"
            contents:
              - learn/measure/index.qmd
          - section: "compare"
            contents:
              - learn/compare/index.qmd
          - section: "explain"
            contents:
              - learn/explain/index.qmd
          - section: "predict"
            contents:
              - learn/predict/index.qmd
      - text: "---"
      - section: "dissect"
        contents:
          - href: dissect/index.qmd
            text: "overview"
      - text: "---"
      - href: resources.qmd
        text: "resources"
      - href: about.qmd
        text: "about"

format:
  html:
    theme: theme-dark.scss
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 3
    code-fold: true
    link-external-newwindow: true
    grid:
      body-width: 950px
      sidebar-width: 250px
      margin-width: 200px
