<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bài 1: Phân tích tác động ngân sách – Mô hình Kinh tế Y tế với R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" rel="next">
<link href="../../kb/m10-policy-bia-equity/index.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9e7f0c659d5fa2cace8548cb57964278.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c18d72663580ed8ca19ce2a2f99af51b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=JetBrains+Mono:wght@400;600&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m10-policy-bia-equity/index.html">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</a></li><li class="breadcrumb-item"><a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Mô hình Kinh tế Y tế với R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lời mở đầu</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m00-r-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M00 · R cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l02-vectors-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l03-functions-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hàm, cấu trúc điều khiển, vòng lặp và vectơ hóa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l04-data-frames.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Data frame — nhập, làm sạch, tóm tắt và chuyển dạng dữ liệu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l05-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Biểu đồ với ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l06-randomness-monte-carlo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 6: Ngẫu nhiên, mô phỏng Monte Carlo và sai số Monte Carlo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m01-ee-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M01 · Nền tảng đánh giá kinh tế và cây quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l01-evaluation-types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại đánh giá kinh tế, quan điểm, khung thời gian và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l02-health-outcomes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Năm sống, QALY và DALY</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l03-decision-rules.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l04-thresholds.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l05-decision-tree.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Xây cây quyết định từ đầu trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m02-cohort-markov/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l01-state-transition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao cần mô hình chuyển trạng thái</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l03-cohort-trace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l04-time-dependence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Phụ thuộc thời gian: lão hóa, trạng thái đường hầm và mảng 3 chiều</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l05-results-verification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị gắn với lần chuyển, đường biên hiệu quả và xác minh mô hình</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m03-uncertainty-voi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l01-deterministic-sa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại bất định và phân tích độ nhạy tất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l02-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Chọn phân phối cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l03-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích độ nhạy xác suất (PSA) trong R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l05-voi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m04-microsimulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M04 · Mô phỏng vi mô (microsimulation)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l01-why-microsimulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l02-microsim-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l03-vectorisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vectơ hóa theo cá thể và đo hiệu năng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l04-parallel-rcpp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tính toán song song và Rcpp cho vòng lặp nóng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l05-mc-error-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bao nhiêu cá thể là đủ? Sai số Monte Carlo, PSA và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m05-dynamic-transmission/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M05 · Mô hình lây truyền động</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l01-static-vs-dynamic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Mô hình tĩnh và mô hình lây truyền động</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l02-sir-seir-desolve.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình SIR và SEIR trong R với deSolve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l03-vaccination-herd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Tiêm chủng, hiệu quả trực tiếp và gián tiếp</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l04-dengue-host-vector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Mô hình vật chủ–véc tơ cho sốt xuất huyết Dengue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l05-dynamic-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế với mô hình lây truyền động</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m06-amr-economics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M06 · Kinh tế học kháng kháng sinh (AMR)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l01-amr-burden.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l02-attributable-los.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l03-ward-transmission.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Mô hình lây truyền CRE trong khoa hồi sức</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l04-two-strain-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m07-survival-psm/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M07 · Phân tích sống còn cho mô hình quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l01-survival-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ôn tập phân tích sống còn cho người làm mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l02-parametric-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình sống còn tham số với flexsurv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l03-extrapolation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Ngoại suy sống còn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l04-reconstruct-ipd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tái tạo dữ liệu cá thể từ đường KM đã công bố và dùng HR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l05-partitioned-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Mô hình sống còn phân vùng trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m08-calibration/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M08 · Hiệu chuẩn mô hình (calibration)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l01-why-calibrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l02-search-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l03-bayes-sir.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hiệu chuẩn Bayes và thuật toán SIR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l04-psa-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đưa kết quả hiệu chuẩn vào PSA, thẩm định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m09-inputs-vietnam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l01-costing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ước tính chi phí cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l05-decision-context.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bối cảnh ra quyết định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m10-policy-bia-equity/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m11-software-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l01-code-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Cấu trúc mã cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l02-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Xác minh và kiểm thử mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l03-version-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quản lý phiên bản với Git và tái lập môi trường với renv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l04-r-package.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đóng gói mô hình thành gói R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l05-shiny-living.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Ứng dụng Shiny và mô hình “sống”</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bảng thuật ngữ Anh–Việt</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../references.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tài liệu tham khảo</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Trong bài</h2>
   
  <ul class="collapse">
  <li><a href="#mục-tiêu-học-tập" id="toc-mục-tiêu-học-tập" class="nav-link active" data-scroll-target="#mục-tiêu-học-tập">Mục tiêu học tập</a></li>
  <li><a href="#ý-chính" id="toc-ý-chính" class="nav-link" data-scroll-target="#ý-chính">Ý chính</a></li>
  <li><a href="#nội-dung" id="toc-nội-dung" class="nav-link" data-scroll-target="#nội-dung">Nội dung</a></li>
  <li><a href="#thực-hành" id="toc-thực-hành" class="nav-link" data-scroll-target="#thực-hành">Thực hành</a></li>
  <li><a href="#bài-tập" id="toc-bài-tập" class="nav-link" data-scroll-target="#bài-tập">Bài tập</a></li>
  <li><a href="#tài-liệu-tham-khảo" id="toc-tài-liệu-tham-khảo" class="nav-link" data-scroll-target="#tài-liệu-tham-khảo">Tài liệu tham khảo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m10-policy-bia-equity/index.html">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</a></li><li class="breadcrumb-item"><a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></h1>
<p class="subtitle lead">Ước tính ngân sách tăng thêm hoặc tiết kiệm khi mở rộng BPaLM toàn quốc, theo năm và theo đơn vị chi trả</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled" title="Vì sao bạn nên quan tâm?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vì sao bạn nên quan tâm?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cuối mỗi năm, Chương trình Chống lao và các bệnh viện phổi tỉnh phải dự trù thuốc và kinh phí cho người bệnh lao kháng thuốc của năm sau. Năm 2024 cả nước có 3,050 người bắt đầu điều trị, trong đó 751 người (25%) đã dùng phác đồ 6 tháng <span class="citation" data-cites="who2026tbnotif">(<a href="#ref-who2026tbnotif" role="doc-biblioref">World Health Organization 2026a</a>)</span>. Chương trình báo cáo chi khoảng US$458 tiền thuốc cho mỗi người bệnh <span class="citation" data-cites="who2026tbfinance">(<a href="#ref-who2026tbfinance" role="doc-biblioref">World Health Organization 2026c</a>)</span>, tức khoảng 11.4 triệu VNĐ, bằng 1.4 tháng thu nhập bình quân của một người lao động <span class="citation" data-cites="gso2026population2025">(<a href="#ref-gso2026population2025" role="doc-biblioref">Cục Thống kê (Bộ Tài chính) 2026</a>)</span>. M02 đã cho thấy BPaLM rẻ hơn và tốt hơn cho từng người bệnh, nhưng người giữ ngân sách hỏi khác: nếu từ năm 2026 đưa phần lớn người bệnh sang BPaLM, ngân sách từng năm tăng hay giảm, và quỹ nào chịu? Bài này dựng phân tích tác động ngân sách để trả lời.</p>
</div>
</div>
<section id="mục-tiêu-học-tập" class="level2">
<h2 class="anchored" data-anchor-id="mục-tiêu-học-tập">Mục tiêu học tập</h2>
<p>Sau bài này, bạn có thể:</p>
<ol type="1">
<li>Phân biệt câu hỏi của phân tích tác động ngân sách (budget impact analysis, BIA) với câu hỏi của phân tích chi phí-hiệu quả (CEA), và kể các thành phần của một BIA, kể cả cơ cấu điều trị hiện tại.</li>
<li>Chuyển vết đoàn hệ (Markov trace) của M02 thành dòng tiền theo tháng cho một người bệnh lao đa kháng/kháng rifampicin (MDR/RR-TB), rồi cộng dồn cho nhiều đoàn hệ bắt đầu điều trị ở các tháng khác nhau, gồm cả người đã điều trị từ trước khung thời gian.</li>
<li>Tính tác động ngân sách theo năm, theo cấu phần chi phí và theo đơn vị chi trả khi mở rộng BPaLM.</li>
<li>Làm phân tích độ nhạy một chiều và phân tích kịch bản cho BIA, rồi tìm giá thuốc trung hòa ngân sách.</li>
</ol>
</section>
<section id="ý-chính" class="level2">
<h2 class="anchored" data-anchor-id="ý-chính">Ý chính</h2>
<ul>
<li>CEA hỏi “có đáng tiền không”; BIA hỏi “có trả nổi không, ai trả và trả năm nào”. Một can thiệp chi phí-hiệu quả vẫn có thể vượt quá khả năng chi trả <span class="citation" data-cites="bilinski2017when">(<a href="#ref-bilinski2017when" role="doc-biblioref">Bilinski và c.s. 2017</a>)</span>.</li>
<li>BIA được làm cho một <strong>đơn vị chi trả ngân sách</strong> (budget holder) cụ thể, trong khung thời gian ngắn theo chu kỳ kế hoạch ngân sách, với tiền <strong>không chiết khấu</strong> và giá giữ cố định. Kết quả là tiền, không phải năm sống điều chỉnh theo chất lượng (QALY).</li>
<li>Tác động ngân sách năm <span class="math inline">\(y\)</span> = chi phí của “thế giới mới” trừ chi phí của “thế giới hiện tại” trong năm đó, cộng trên mọi người bệnh đang được theo dõi.</li>
<li>Quần thể là <strong>quần thể mở</strong>: người bệnh mới vào mỗi tháng, chi phí của một người kéo dài sang năm sau, và ngân sách năm đầu còn phải trả cho người đã bắt đầu điều trị từ trước. Phép cộng dồn này là một phép tích chập.</li>
<li><strong>Cơ cấu điều trị hiện tại</strong> quyết định BPaLM thay thế cái gì. Thay phác đồ ngắn rẻ hơn thì tiết kiệm ít hơn thay phác đồ 18 tháng; một phần người bệnh đã dùng BPaLM thì phần còn lại để tiết kiệm nhỏ hơn.</li>
<li><strong>Tỷ lệ áp dụng</strong> (uptake) tăng dần; năm đầu thường ít tiết kiệm hơn vì phác đồ mới tốn tiền ngay, còn khoản tiết kiệm đến muộn hơn.</li>
<li>Khoản tiết kiệm ở quỹ này có thể đi kèm khoản chi thêm ở quỹ khác. Hãy báo cáo theo từng đơn vị chi trả.</li>
<li>BIA nên dùng cùng mô hình và giả định với CEA, và trình bày bằng các kịch bản mà người ra quyết định quan tâm <span class="citation" data-cites="mauskopf2007principles sullivan2014budget">(<a href="#ref-mauskopf2007principles" role="doc-biblioref">Mauskopf và c.s. 2007</a>; <a href="#ref-sullivan2014budget" role="doc-biblioref">Sullivan và c.s. 2014</a>)</span>.</li>
</ul>
</section>
<section id="nội-dung" class="level2">
<h2 class="anchored" data-anchor-id="nội-dung">Nội dung</h2>
<section id="bia-trả-lời-câu-hỏi-gì" class="level3">
<h3 class="anchored" data-anchor-id="bia-trả-lời-câu-hỏi-gì">BIA trả lời câu hỏi gì</h3>
<p>M02 kết luận BPaLM chiếm ưu thế so với cả phác đồ ngắn 9 tháng lẫn phác đồ dài hạn: rẻ hơn và tạo nhiều QALY hơn cho mỗi người bệnh, tính bằng chi phí có chiết khấu, cộng trọn đời. Người giữ ngân sách lại cần số tiền thực chi trong từng năm, cho cả quần thể, trong ngân sách của chính họ. Một can thiệp tiết kiệm trọn đời vẫn có thể cần thêm tiền trong năm triển khai, nên cần xét cả hai khi xếp ưu tiên <span class="citation" data-cites="bilinski2017when">(<a href="#ref-bilinski2017when" role="doc-biblioref">Bilinski và c.s. 2017</a>)</span>.</p>
</section>
<section id="các-thành-phần-của-một-bia" class="level3">
<h3 class="anchored" data-anchor-id="các-thành-phần-của-một-bia">Các thành phần của một BIA</h3>
<p>Nhóm công tác ISPOR khuyến nghị một BIA ước tính quy mô quần thể đủ điều kiện, cơ cấu điều trị hiện tại và cơ cấu dự kiến khi có can thiệp mới, chi phí của từng cơ cấu, và thay đổi trong các chi phí liên quan đến bệnh <span class="citation" data-cites="sullivan2014budget">(<a href="#ref-sullivan2014budget" role="doc-biblioref">Sullivan và c.s. 2014</a>)</span>. Bảng dưới đây áp các thành phần đó vào ví dụ.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Thành phần</th>
<th>Câu hỏi</th>
<th>Trong ví dụ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Đơn vị chi trả</td>
<td>Ngân sách của ai?</td>
<td>Chương trình Chống lao (thuốc) và quỹ BHYT (khám, xét nghiệm, nằm viện)</td>
</tr>
<tr class="even">
<td>Quần thể</td>
<td>Bao nhiêu người, mỗi năm?</td>
<td>3,050 người bắt đầu điều trị năm 2024 <span class="citation" data-cites="who2026tbnotif">(<a href="#ref-who2026tbnotif" role="doc-biblioref">World Health Organization 2026a</a>)</span>; 85% đủ điều kiện nhận BPaLM (giá trị minh họa)</td>
</tr>
<tr class="odd">
<td>Cơ cấu điều trị hiện tại</td>
<td>Ai đang dùng phác đồ nào?</td>
<td>năm 2024: 33% phác đồ từ 18 tháng, 42% phác đồ 9 tháng, 25% phác đồ 6 tháng <span class="citation" data-cites="who2026tbnotif">(<a href="#ref-who2026tbnotif" role="doc-biblioref">World Health Organization 2026a</a>)</span></td>
</tr>
<tr class="even">
<td>Cơ cấu dự kiến</td>
<td>Bao nhiêu người chuyển sang phác đồ mới, năm nào?</td>
<td>BPaLM từ 38% người bệnh năm đầu lên 76% năm cuối (giá trị minh họa), thay hai phác đồ còn lại theo tỷ lệ hiện có</td>
</tr>
<tr class="odd">
<td>Khung thời gian</td>
<td>Bao nhiêu năm?</td>
<td>5 năm, từ 2026</td>
</tr>
<tr class="even">
<td>Chi phí</td>
<td>Chi phí nào, giá năm nào?</td>
<td>thuốc, theo dõi, biến cố bất lợi, đánh giá cuối điều trị, điều trị lại, chăm sóc sau điều trị; giá năm 2025 của khóa học</td>
</tr>
<tr class="odd">
<td>Kịch bản</td>
<td>Thay đổi gì làm kết quả đổi?</td>
<td>cơ cấu hiện tại, tỷ lệ áp dụng, giá thuốc, tỷ lệ biến cố bất lợi, số người bệnh</td>
</tr>
</tbody>
</table>
<p>Con số 3,050 khớp bậc độ lớn với 2,407 người mỗi năm trong đoàn hệ toàn quốc 2021–2022 <span class="citation" data-cites="nguyen2026from">(<a href="#ref-nguyen2026from" role="doc-biblioref">Nguyen và c.s. 2026</a>)</span>, nhưng chỉ bằng 32% số ca lao kháng rifampicin mới mà WHO ước tính cho Việt Nam (9,400 ca năm 2024) <span class="citation" data-cites="who2026rrestimates">(<a href="#ref-who2026rrestimates" role="doc-biblioref">World Health Organization 2026b</a>)</span>. Nếu phát hiện ca tốt hơn, ngân sách sẽ lớn hơn nhiều; Bài 4 xem kịch bản đó. Nhóm công tác ISPOR cũng khuyên dùng cách tính đơn giản nhất cho kết quả đáng tin, và ít nhất phải được người ra quyết định thấy hợp lý (face validity) cùng với xác minh các phép tính <span class="citation" data-cites="sullivan2014budget">(<a href="#ref-sullivan2014budget" role="doc-biblioref">Sullivan và c.s. 2014</a>)</span>. Ta đã có mô hình M02 đã xác minh, nên chỉ cần lấy ra dòng tiền theo tháng.</p>
</section>
<section id="từ-vết-đoàn-hệ-đến-dòng-tiền" class="level3">
<h3 class="anchored" data-anchor-id="từ-vết-đoàn-hệ-đến-dòng-tiền">Từ vết đoàn hệ đến dòng tiền</h3>
<p>Gọi <span class="math inline">\(c^r_k\)</span> là chi phí kỳ vọng (không chiết khấu) cho một người bệnh dùng phác đồ <span class="math inline">\(r\)</span> ở tháng thứ <span class="math inline">\(k\)</span> kể từ khi bắt đầu điều trị. M02 cho ta <span class="math inline">\(c^r_k\)</span> trực tiếp từ vết đoàn hệ: số người còn đang điều trị đầu tháng (đợt đầu hoặc đợt điều trị lại) nhân giá thuốc và theo dõi, cộng biến cố bất lợi ở tháng đầu, đánh giá cuối điều trị khi hoàn thành, và chăm sóc ở các trạng thái sau điều trị. Ba phác đồ là ba nhánh có sẵn của M02: dài hạn, ngắn 9 tháng và BPaLM. Gọi <span class="math inline">\(N^r_e\)</span> là số người bắt đầu phác đồ <span class="math inline">\(r\)</span> ở tháng lịch <span class="math inline">\(e\)</span>. Chi phí ở tháng lịch <span class="math inline">\(t\)</span> là</p>
<p><span class="math display">\[
B_t = \sum_{r} \sum_{e \le t} N^r_e \, c^r_{t-e+1},
\]</span></p>
<p>tức một phép tích chập của dòng người vào với hồ sơ chi phí. Tác động ngân sách là <span class="math inline">\(BI_t = B^{\text{mới}}_t - B^{\text{hiện tại}}_t\)</span>, rồi cộng theo năm. Thế giới hiện tại giữ cơ cấu năm 2024; trong thế giới mới, tỷ lệ áp dụng năm <span class="math inline">\(y\)</span> nhân tỷ lệ đủ điều kiện cho ra tỷ lệ người dùng BPaLM (không thấp hơn mức hiện tại), phần còn lại chia cho phác đồ dài hạn và phác đồ ngắn theo tỷ lệ hiện có.</p>
<p><strong>Người đã điều trị từ trước.</strong> Nếu dòng người chỉ bắt đầu từ tháng đầu của khung thời gian, năm đầu sẽ thiếu những người bắt đầu điều trị năm trước nhưng vẫn đang dùng thuốc (phác đồ 18 tháng kéo sang năm sau) hoặc đang được điều trị lại. Ngân sách “hiện tại” khi đó thấp hơn thực tế rõ rệt. Ta thêm 36 tháng người bắt đầu trước khung thời gian (giai đoạn chạy đà, run-in), cùng nhịp với tháng đầu và theo cơ cấu hiện tại, vào cả hai thế giới. Họ triệt tiêu trong tác động ngân sách, nhưng làm mức ngân sách đúng ngay từ năm đầu.</p>
<p>Ba điểm khác với CEA. Thứ nhất, tiền không chiết khấu, vì người giữ ngân sách cần số tiền thực chi từng năm. Thứ hai, không có QALY; lợi ích sức khỏe chỉ đi vào BIA qua chi phí, ví dụ ít biến cố bất lợi hơn thì ít tiền nằm viện hơn. Thứ ba, chi phí phát sinh sau khung thời gian bị cắt bỏ.</p>
</section>
<section id="đơn-vị-chi-trả" class="level3">
<h3 class="anchored" data-anchor-id="đơn-vị-chi-trả">Đơn vị chi trả</h3>
<p>Việt Nam chi cho lao qua hai dòng tiền chính. Từ 7/2022 quỹ BHYT chi trả thuốc lao hàng một <span class="citation" data-cites="scdi2024supports">(<a href="#ref-scdi2024supports" role="doc-biblioref">Center for Supporting Community Development Initiatives (SCDI) 2024</a>)</span>. Dịch vụ lao kháng thuốc được BHYT chi trả một phần, có đồng chi trả, và nằm viện có mức đồng chi trả theo luật 20% <span class="citation" data-cites="oh2026assessment">(<a href="#ref-oh2026assessment" role="doc-biblioref">Oh và c.s. 2026</a>)</span>. Thuốc lao kháng thuốc nằm trong ngân sách thuốc hàng hai của Chương trình Chống lao; báo cáo cho WHO ghi 87% ngân sách này đã xác định được nguồn tài trợ năm 2025 <span class="citation" data-cites="who2026tbfinance">(<a href="#ref-who2026tbfinance" role="doc-biblioref">World Health Organization 2026c</a>)</span>. Ở quy mô toàn bộ kinh phí lao, 62.9% năm 2023 đến từ nguồn bên ngoài, chủ yếu Quỹ Toàn cầu <span class="citation" data-cites="oh2026assessment">(<a href="#ref-oh2026assessment" role="doc-biblioref">Oh và c.s. 2026</a>)</span>. Bài này vì vậy giao thuốc cho Chương trình Chống lao, còn khám, xét nghiệm, nằm viện vì biến cố bất lợi và chăm sóc sau điều trị cho quỹ BHYT (bảng <code>params/payer.csv</code>), và bỏ qua phần đồng chi trả của người bệnh. Các nguồn chưa thống nhất: một phóng sự cho rằng điều trị nội trú lao kháng thuốc do Chương trình Chống lao chi trả <span class="citation" data-cites="vov2024bhyt">(<a href="#ref-vov2024bhyt" role="doc-biblioref">Đài Tiếng nói Việt Nam (VOV) 2024</a>)</span>. Hãy kiểm tra lại phân chia này với đơn vị chi trả trước khi dùng.</p>
</section>
</section>
<section id="thực-hành" class="level2">
<h2 class="anchored" data-anchor-id="thực-hành">Thực hành</h2>
<p>Nạp hàm của M02 và M10, các giá trị chung của khóa học và các bảng tham số. Kiểm tra: không có lỗi; <code>read_params()</code> báo lỗi nếu một tham số không minh họa thiếu nguồn.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vietnamese text in tables and figures needs a UTF-8 locale (Rscript may start in "C")</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">isTRUE</span>(<span class="fu">l10n_info</span>()[[<span class="st">"UTF-8"</span>]])) <span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_CTYPE"</span>, <span class="st">"en_US.UTF-8"</span>))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/helpers.R"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/vn_data.R"</span>)              <span class="co"># course-wide values: vn_context(), vn_prices(), ...</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../m02-cohort-markov/code/model.R"</span>)   <span class="co"># M02 model: evaluate_regimen(), run_cea(), ...</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"code/model.R"</span>)                        <span class="co"># M10 functions</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>p02 <span class="ot">&lt;-</span> <span class="fu">m02_params</span>(<span class="st">"../m02-cohort-markov/params/mdrtb.csv"</span>)   <span class="co"># M02 parameters + shared prices</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>pb <span class="ot">&lt;-</span> <span class="fu">read_params</span>(<span class="st">"params/bia.csv"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>payer <span class="ot">&lt;-</span> <span class="fu">read_payer</span>(<span class="st">"params/payer.csv"</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>ctx <span class="ot">&lt;-</span> <span class="fu">vn_context</span>()</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>ptab_bia <span class="ot">&lt;-</span> <span class="fu">attr</span>(pb, <span class="st">"table"</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>p_bia <span class="ot">&lt;-</span> <span class="fu">bia_params</span>(p02, pb)                  <span class="co"># M02 parameters + the BIA's price conventions</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>extra_months <span class="ot">&lt;-</span> <span class="dv">36</span>                            <span class="co"># Exercise 2: months followed after the horizon</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>bn <span class="ot">&lt;-</span> <span class="cf">function</span>(x) x <span class="sc">/</span> <span class="fl">1e9</span>                     <span class="co"># VND -&gt; billion VND (tỷ VNĐ)</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">sum</span>(<span class="fu">current_counts</span>(pb)) <span class="sc">&gt;</span> <span class="dv">0</span>, <span class="fu">all</span>(<span class="fu">current_mix</span>(pb) <span class="sc">&gt;=</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Đặt hai câu hỏi cạnh nhau. Bảng cho thấy chi phí mỗi người bệnh có chiết khấu (dùng cho CEA) và không chiết khấu (dùng cho BIA) của ba phác đồ. Kiểm tra: chi phí không chiết khấu luôn lớn hơn hoặc bằng chi phí có chiết khấu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One model, two questions. CEA: discounted, lifetime, per patient.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># BIA: undiscounted cash, a few years, the whole eligible population.</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>cea <span class="ot">&lt;-</span> <span class="fu">run_cea</span>(p_bia)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>per_patient <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">cost_disc_million =</span> cea<span class="sc">$</span>cost <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">cost_undisc_million =</span> cea<span class="sc">$</span>cost_undisc <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">qaly =</span> cea<span class="sc">$</span>qaly,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">row.names =</span> REGIMEN_LABELS[REGIMENS]</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(per_patient, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     cost_disc_million cost_undisc_million  qaly
Phác đồ dài hạn                  29.32               29.91 12.49
Phác đồ ngắn 9 tháng             21.69               21.95 12.91
BPaLM                            15.02               15.13 13.39</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(per_patient<span class="sc">$</span>cost_undisc_million <span class="sc">&gt;=</span> per_patient<span class="sc">$</span>cost_disc_million))   <span class="co"># discounting only shrinks costs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Lấy hồ sơ nguồn lực theo tháng từ vết đoàn hệ của M02, rồi nhân với giá. Tách nguồn lực khỏi giá giúp đổi giá thuốc mà không phải chạy lại mô hình. Kiểm tra: cộng hết các tháng phải đúng bằng chi phí không chiết khấu của M02 cho cả ba phác đồ (<code>stopifnot</code>), và tiền thuốc mỗi người bệnh của mô hình phải cùng bậc với số chương trình báo cáo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Monthly resource use per patient from the M02 trace (first-line treatment and</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># retreatment), then prices</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">bia_resources</span>(p02)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>prof <span class="ot">&lt;-</span> <span class="fu">bia_profiles</span>(res, p02, pb)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Check: over the whole follow-up the monthly profile adds up to M02's undiscounted cost</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (g <span class="cf">in</span> REGIMENS) <span class="fu">stopifnot</span>(<span class="fu">abs</span>(<span class="fu">sum</span>(prof[[g]]) <span class="sc">-</span> cea[g, <span class="st">"cost_undisc"</span>]) <span class="sc">&lt;</span> <span class="fl">1e-3</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Cost per patient in each year after starting treatment (million VND)</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>year_fu <span class="ot">&lt;-</span> <span class="fu">ceiling</span>(<span class="fu">seq_len</span>(<span class="fu">nrow</span>(prof<span class="sc">$</span>long)) <span class="sc">/</span> <span class="dv">12</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>by_fu <span class="ot">&lt;-</span> <span class="fu">sapply</span>(prof, <span class="cf">function</span>(x) <span class="fu">tapply</span>(<span class="fu">rowSums</span>(x), year_fu, sum))[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, REGIMENS] <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(by_fu) <span class="ot">&lt;-</span> REGIMEN_LABELS[REGIMENS]</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(by_fu) <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"Năm thứ"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="st">"sau khi bắt đầu"</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(by_fu, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Phác đồ dài hạn Phác đồ ngắn 9 tháng BPaLM
Năm thứ 1 sau khi bắt đầu           22.31                20.86 14.76
Năm thứ 2 sau khi bắt đầu            6.35                 0.29  0.10
Năm thứ 3 sau khi bắt đầu            0.32                 0.19  0.06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Face validity: drug spending per patient in the model (2024 mix) versus what the</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># programme reported to WHO for 2024 (USD per patient starting treatment)</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>drug_usd <span class="ot">&lt;-</span> <span class="fu">sapply</span>(prof, <span class="cf">function</span>(x) <span class="fu">sum</span>(x<span class="sc">$</span>drug)) <span class="sc">/</span> ctx<span class="sc">$</span>fx_vnd_per_usd</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>drug_usd_mix <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">current_mix</span>(pb) <span class="sc">*</span> drug_usd)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(drug_usd, <span class="at">mix_2024 =</span> drug_usd_mix, <span class="at">who_reported_2024 =</span> pb<span class="sc">$</span>who_drug_cpp_2024_usd))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             long             short             bpalm          mix_2024 
              453               305               281               348 
who_reported_2024 
              458 </code></pre>
</div>
</div>
<p>Một người bệnh dùng phác đồ dài hạn tiêu 22.3 triệu VNĐ trong năm đầu và 6.4 triệu VNĐ trong năm thứ hai; với phác đồ ngắn và BPaLM, gần như toàn bộ chi phí (20.9 và 14.8 triệu VNĐ) rơi vào năm đầu. Với cơ cấu năm 2024, tiền thuốc mô hình cho mỗi người bệnh là khoảng US$348, bằng 76% con số US$458 mà chương trình báo cáo cho WHO <span class="citation" data-cites="who2026tbfinance">(<a href="#ref-who2026tbfinance" role="doc-biblioref">World Health Organization 2026c</a>)</span>. Mô hình dùng giá thuốc quốc tế (GDF; bảng của Treatment Action Group, lấy cận dưới cho phác đồ dài hạn), chưa gồm vận chuyển và thuốc cho người kháng thêm thuốc, nên thấp hơn là điều dễ hiểu. Đây là một phép kiểm tra hợp lý rẻ và đáng làm.</p>
<p>Lập lịch người bệnh bắt đầu điều trị mỗi tháng, tách theo phác đồ ở thế giới hiện tại (<code>_now</code>) và thế giới mới. Kiểm tra: ở mỗi thế giới, số người theo từng phác đồ cộng lại bằng tổng số người mỗi tháng, không có số âm, và BPaLM của thế giới mới không thấp hơn hiện tại.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Who enters the budget: patients starting treatment each month, by regimen</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>sched <span class="ot">&lt;-</span> <span class="fu">enrolment_schedule</span>(pb)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">nrow</span>(sched) <span class="sc">==</span> <span class="dv">12</span> <span class="sc">*</span> pb<span class="sc">$</span>horizon_years, <span class="fu">all</span>(sched[, <span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)] <span class="sc">&gt;=</span> <span class="dv">0</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(<span class="fu">abs</span>(sched<span class="sc">$</span>long <span class="sc">+</span> sched<span class="sc">$</span>short <span class="sc">+</span> sched<span class="sc">$</span>bpalm <span class="sc">-</span> sched<span class="sc">$</span>total) <span class="sc">&lt;</span> <span class="fl">1e-9</span>),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(<span class="fu">abs</span>(sched<span class="sc">$</span>long_now <span class="sc">+</span> sched<span class="sc">$</span>short_now <span class="sc">+</span> sched<span class="sc">$</span>bpalm_now <span class="sc">-</span> sched<span class="sc">$</span>total) <span class="sc">&lt;</span> <span class="fl">1e-9</span>),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(sched<span class="sc">$</span>bpalm <span class="sc">&gt;=</span> sched<span class="sc">$</span>bpalm_now <span class="sc">-</span> <span class="fl">1e-9</span>))     <span class="co"># scale-up never goes below today's BPaLM use</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>pop_year <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(<span class="fu">cbind</span>(total, long_now, short_now, bpalm_now, long, short, bpalm) <span class="sc">~</span> year,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> sched, <span class="at">FUN =</span> sum)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>pop_year<span class="sc">$</span>year <span class="ot">&lt;-</span> pb<span class="sc">$</span>start_year <span class="sc">+</span> pop_year<span class="sc">$</span>year <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(pop_year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  year total long_now short_now bpalm_now long short bpalm
1 2026  3050     1013      1286       751  830  1054  1167
2 2027  3050     1013      1286       751  659   836  1556
3 2028  3050     1013      1286       751  487   618  1944
4 2029  3050     1013      1286       751  373   473  2204
5 2030  3050     1013      1286       751  316   401  2333</code></pre>
</div>
</div>
<p>Chạy BIA: cộng dồn chi phí của mọi đoàn hệ tháng, gồm cả giai đoạn chạy đà, trong cả hai thế giới. Kiểm tra: ngân sách hiện tại năm đầu đã ở mức ổn định (bước kiểm tra ngay dưới đây).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>bia <span class="ot">&lt;-</span> <span class="fu">run_bia</span>(pb, prof)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">bia_by_year</span>(bia, pb<span class="sc">$</span>start_year)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>bia_5y <span class="ot">&lt;-</span> <span class="fu">sum</span>(tab<span class="sc">$</span>impact)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">year =</span> tab<span class="sc">$</span>year, <span class="at">patients =</span> <span class="fu">round</span>(tab<span class="sc">$</span>patients), <span class="at">on_bpalm =</span> <span class="fu">round</span>(tab<span class="sc">$</span>on_bpalm),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">current =</span> <span class="fu">fmt_num</span>(<span class="fu">bn</span>(tab<span class="sc">$</span>current), <span class="dv">1</span>), <span class="at">new =</span> <span class="fu">fmt_num</span>(<span class="fu">bn</span>(tab<span class="sc">$</span>new), <span class="dv">1</span>),</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">impact =</span> <span class="fu">fmt_num</span>(<span class="fu">bn</span>(tab<span class="sc">$</span>impact), <span class="dv">1</span>), <span class="at">cumulative =</span> <span class="fu">fmt_num</span>(<span class="fu">bn</span>(tab<span class="sc">$</span>cumulative), <span class="dv">1</span>)),</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Năm"</span>, <span class="st">"Người bệnh mới"</span>, <span class="st">"Trong đó dùng BPaLM"</span>, <span class="st">"Ngân sách hiện tại (tỷ VNĐ)"</span>,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Ngân sách khi mở rộng BPaLM (tỷ VNĐ)"</span>, <span class="st">"Tác động (tỷ VNĐ)"</span>, <span class="st">"Cộng dồn (tỷ VNĐ)"</span>),</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">align =</span> <span class="st">"rrrrrrr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 3%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 26%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Năm</th>
<th style="text-align: right;">Người bệnh mới</th>
<th style="text-align: right;">Trong đó dùng BPaLM</th>
<th style="text-align: right;">Ngân sách hiện tại (tỷ VNĐ)</th>
<th style="text-align: right;">Ngân sách khi mở rộng BPaLM (tỷ VNĐ)</th>
<th style="text-align: right;">Tác động (tỷ VNĐ)</th>
<th style="text-align: right;">Cộng dồn (tỷ VNĐ)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2026</td>
<td style="text-align: right;">3050</td>
<td style="text-align: right;">1167</td>
<td style="text-align: right;">68.3</td>
<td style="text-align: right;">66.5</td>
<td style="text-align: right;">-1.7</td>
<td style="text-align: right;">-1.7</td>
</tr>
<tr class="even">
<td style="text-align: right;">2027</td>
<td style="text-align: right;">3050</td>
<td style="text-align: right;">1556</td>
<td style="text-align: right;">68.6</td>
<td style="text-align: right;">63.3</td>
<td style="text-align: right;">-5.3</td>
<td style="text-align: right;">-7.0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2028</td>
<td style="text-align: right;">3050</td>
<td style="text-align: right;">1944</td>
<td style="text-align: right;">68.9</td>
<td style="text-align: right;">59.8</td>
<td style="text-align: right;">-9.1</td>
<td style="text-align: right;">-16.1</td>
</tr>
<tr class="even">
<td style="text-align: right;">2029</td>
<td style="text-align: right;">3050</td>
<td style="text-align: right;">2204</td>
<td style="text-align: right;">69.1</td>
<td style="text-align: right;">56.7</td>
<td style="text-align: right;">-12.4</td>
<td style="text-align: right;">-28.5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2030</td>
<td style="text-align: right;">3050</td>
<td style="text-align: right;">2333</td>
<td style="text-align: right;">69.2</td>
<td style="text-align: right;">54.7</td>
<td style="text-align: right;">-14.6</td>
<td style="text-align: right;">-43.1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Trong 5 năm, mở rộng BPaLM làm ngân sách thay đổi -43.1 tỷ VNĐ (số âm là tiết kiệm), trên nền ngân sách hiện tại khoảng 68 tỷ VNĐ mỗi năm. Năm đầu chỉ thay đổi -1.7 tỷ VNĐ, năm cuối -14.6 tỷ VNĐ, vì tỷ lệ áp dụng tăng dần và vì khoản tiết kiệm từ người lẽ ra dùng phác đồ dài hạn nằm ở năm thứ hai sau khi họ bắt đầu điều trị.</p>
<p>Năm phép kiểm tra độc lập, không phép nào lặp lại một định nghĩa: (a) một đoàn hệ bắt đầu muộn hai tháng thì tốn đúng như cũ nhưng dịch hai tháng; (b) một đoàn hệ theo dõi hết khung thời gian của M02 tốn đúng chi phí không chiết khấu của M02; (c) không mở rộng (BPaLM giữ mức hiện tại) thì tác động bằng 0 ở mọi tháng; (d) nếu ba phác đồ có cùng hồ sơ chi phí thì chuyển người bệnh giữa chúng không đổi ngân sách; (e) khi số người bệnh không đổi, ngân sách hiện tại năm đầu và năm hai chênh nhau dưới 1% (kiểm tra giai đoạn chạy đà).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Independent tests of the BIA machinery (none repeats a definition)</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (a) Convolution: a cohort that starts 2 months later costs the same, shifted by 2 months</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="dv">120</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>c_first <span class="ot">&lt;-</span> <span class="fu">cohort_costs</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="fu">rep</span>(<span class="dv">0</span>, h <span class="sc">-</span> <span class="dv">1</span>)), prof<span class="sc">$</span>long, h)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>c_third <span class="ot">&lt;-</span> <span class="fu">cohort_costs</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="fu">rep</span>(<span class="dv">0</span>, h <span class="sc">-</span> <span class="dv">3</span>)), prof<span class="sc">$</span>long, h)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(c_third[<span class="dv">3</span><span class="sc">:</span>h, ] <span class="sc">-</span> c_first[<span class="dv">1</span><span class="sc">:</span>(h <span class="sc">-</span> <span class="dv">2</span>), ]) <span class="sc">&lt;</span> <span class="fl">1e-9</span>), <span class="fu">sum</span>(c_third[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, ]) <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># (b) One cohort followed to the end of M02's horizon costs M02's undiscounted cost</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>n_fu <span class="ot">&lt;-</span> <span class="fu">nrow</span>(prof<span class="sc">$</span>long)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(<span class="fu">sum</span>(<span class="fu">cohort_costs</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="fu">rep</span>(<span class="dv">0</span>, n_fu <span class="sc">-</span> <span class="dv">1</span>)), prof<span class="sc">$</span>long, n_fu)) <span class="sc">-</span> cea[<span class="st">"long"</span>, <span class="st">"cost_undisc"</span>]) <span class="sc">&lt;</span> <span class="fl">1e-3</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># (c) No scale-up (uptake 0, so BPaLM stays at today's share): zero impact in every month</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>pb_none <span class="ot">&lt;-</span> pb</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (y <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>pb<span class="sc">$</span>horizon_years) pb_none[[<span class="fu">paste0</span>(<span class="st">"uptake_y"</span>, y)]] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">max</span>(<span class="fu">abs</span>(<span class="fu">run_bia</span>(pb_none, prof)<span class="sc">$</span>impact)) <span class="sc">&lt;</span> <span class="fl">1e-6</span>)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="co"># (d) If the three regimens had the same monthly cost profile, moving patients between</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="co">#     them could not change the budget: zero impact in every month</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>prof_same <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">long =</span> prof<span class="sc">$</span>short, <span class="at">short =</span> prof<span class="sc">$</span>short, <span class="at">bpalm =</span> prof<span class="sc">$</span>short)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">max</span>(<span class="fu">abs</span>(<span class="fu">run_bia</span>(pb, prof_same)<span class="sc">$</span>impact)) <span class="sc">&lt;</span> <span class="fl">1e-3</span>)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="co"># (e) Run-in: with a constant patient flow the current-world budget is flat from year 1</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>pb_flat <span class="ot">&lt;-</span> pb</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>pb_flat<span class="sc">$</span>growth_rate <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>tab_flat <span class="ot">&lt;-</span> <span class="fu">bia_by_year</span>(<span class="fu">run_bia</span>(pb_flat, prof), pb<span class="sc">$</span>start_year)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(tab_flat<span class="sc">$</span>current[<span class="dv">1</span>] <span class="sc">/</span> tab_flat<span class="sc">$</span>current[<span class="dv">2</span>] <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">&lt;</span> <span class="fl">0.01</span>)</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">flat_y1 =</span> <span class="fu">bn</span>(tab_flat<span class="sc">$</span>current[<span class="dv">1</span>]), <span class="at">flat_y2 =</span> <span class="fu">bn</span>(tab_flat<span class="sc">$</span>current[<span class="dv">2</span>])), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>flat_y1 flat_y2 
   68.3    68.6 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Without the run-in, year 1 would miss everyone who started before the horizon</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>pb_norun <span class="ot">&lt;-</span> pb_flat</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>pb_norun<span class="sc">$</span>runin_months <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>tab_norun <span class="ot">&lt;-</span> <span class="fu">bia_by_year</span>(<span class="fu">run_bia</span>(pb_norun, prof), pb<span class="sc">$</span>start_year)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>share_without_runin <span class="ot">&lt;-</span> tab_norun<span class="sc">$</span>current[<span class="dv">1</span>] <span class="sc">/</span> tab_flat<span class="sc">$</span>current[<span class="dv">1</span>]</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">budget_without_runin_y1 =</span> <span class="fu">bn</span>(tab_norun<span class="sc">$</span>current[<span class="dv">1</span>]), <span class="at">share =</span> share_without_runin), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>budget_without_runin_y1                   share 
                  47.55                    0.70 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(share_without_runin <span class="sc">&lt;</span> <span class="fl">0.9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Với số người không đổi, ngân sách hiện tại năm đầu là 68.3 tỷ VNĐ và năm hai 68.6 tỷ VNĐ, nên giai đoạn chạy đà 36 tháng đủ dài. Nếu bỏ giai đoạn này, ngân sách năm đầu chỉ bằng 70% mức ổn định.</p>
<p>Tách tác động theo cấu phần chi phí và theo đơn vị chi trả. Kiểm tra: cộng theo cấu phần hay theo đơn vị chi trả đều ra cùng tổng (<code>stopifnot</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Where the money moves: impact by cost component and by budget holder</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>comp_5y <span class="ot">&lt;-</span> <span class="fu">colSums</span>(bia<span class="sc">$</span>impact)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">bn</span>(comp_5y), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   drug monitor      ae     eot    post 
   -5.4   -13.5   -24.9     0.7     0.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>payer_year <span class="ot">&lt;-</span> <span class="fu">bia_by_payer</span>(bia, payer)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>level_y1 <span class="ot">&lt;-</span> <span class="fu">bia_by_payer</span>(bia, payer, <span class="st">"current"</span>)[<span class="dv">1</span>, ]      <span class="co"># current budget in year 1, by payer</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(payer_year) <span class="ot">&lt;-</span> tab<span class="sc">$</span>year</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">bn</span>(payer_year), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       ntp    shi
2026  0.39  -2.10
2027 -0.26  -5.05
2028 -1.00  -8.11
2029 -1.89 -10.52
2030 -2.61 -11.99</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(<span class="fu">sum</span>(payer_year) <span class="sc">-</span> bia_5y) <span class="sc">&lt;</span> <span class="fl">1e-3</span>, <span class="fu">abs</span>(<span class="fu">sum</span>(comp_5y) <span class="sc">-</span> bia_5y) <span class="sc">&lt;</span> <span class="fl">1e-3</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The text says the biggest savings come from adverse events and monitoring, not drugs</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="sc">-</span>comp_5y[[<span class="st">"ae"</span>]] <span class="sc">&gt;</span> <span class="sc">-</span>comp_5y[[<span class="st">"drug"</span>]], <span class="sc">-</span>comp_5y[[<span class="st">"monitor"</span>]] <span class="sc">&gt;</span> <span class="sc">-</span>comp_5y[[<span class="st">"drug"</span>]])</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ... and that a month of BPaLM drugs costs more than a month of the short regimen's drugs</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(p_bia<span class="sc">$</span>c_drug_bpalm <span class="sc">&gt;</span> p_bia<span class="sc">$</span>c_drug_short)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>ntp_y1 <span class="ot">&lt;-</span> payer_year[<span class="dv">1</span>, <span class="st">"ntp"</span>]</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>shi_y1 <span class="ot">&lt;-</span> payer_year[<span class="dv">1</span>, <span class="st">"shi"</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Hai khoản tiết kiệm lớn nhất là biến cố bất lợi (24.9 tỷ VNĐ, chiếm 58% tổng tiết kiệm) và theo dõi (13.5 tỷ VNĐ). Thuốc thay đổi ngân sách -5.4 tỷ VNĐ: BPaLM đắt hơn mỗi tháng (1.18 so với 0.86 triệu VNĐ của phác đồ ngắn), nhưng người bệnh dùng ít tháng hơn. Năm 2026, Chương trình Chống lao phải chi thêm 0.39 tỷ VNĐ tiền thuốc trong khi quỹ BHYT tiết kiệm 2.10 tỷ VNĐ. Cùng một chính sách, hai đơn vị chi trả thấy hai kết quả trái chiều: tháng thuốc BPaLM đắt hơn trả ngay, còn khoản tiết kiệm từ phác đồ dài hạn đến sau. So với ngân sách thuốc hiện tại của chương trình (25.7 tỷ VNĐ năm đầu), khoản chênh bằng 1.5%; con số nhỏ, nhưng với một ngân sách phụ thuộc tài trợ, nó vẫn cần được lên kế hoạch.</p>
<p>Khoản tiết kiệm từ biến cố bất lợi dựa trên hai giả định. Thứ nhất, tỷ lệ biến cố bất lợi nặng thấp hơn với BPaLM trong thử nghiệm TB-PRACTECAL (23% so với 48%) <span class="citation" data-cites="nyangwa2024short">(<a href="#ref-nyangwa2024short" role="doc-biblioref">Nyang’wa và c.s. 2024</a>)</span>, nhân với chi phí một đợt nằm viện vì lao kháng thuốc tại Bệnh viện Phổi Trung ương <span class="citation" data-cites="ngo2026direct">(<a href="#ref-ngo2026direct" role="doc-biblioref">Ngo và c.s. 2026</a>)</span>; chi phí này không riêng cho biến cố bất lợi và 38% là tiền thuốc. Thứ hai, M02 dùng <strong>trung vị</strong> chi phí một đợt, trong khi ngân sách cần chi phí <strong>trung bình</strong>. Cả hai được đưa vào phân tích độ nhạy và kịch bản bên dưới.</p>
<p>Vẽ tác động theo năm và cấu phần. Kiểm tra: điểm tròn (tác động ròng) bằng tổng chiều cao các cột của năm đó.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> bia<span class="sc">$</span>schedule<span class="sc">$</span>year</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>comp_df <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k <span class="cf">in</span> COMPONENTS) {</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  comp_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(comp_df, <span class="fu">data.frame</span>(</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="fu">factor</span>(tab<span class="sc">$</span>year),</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">component =</span> <span class="fu">factor</span>(COMPONENT_LABELS[[k]], <span class="at">levels =</span> COMPONENT_LABELS),</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">bn_vnd =</span> <span class="fu">as.vector</span>(<span class="fu">tapply</span>(bia<span class="sc">$</span>impact[, k], y, sum)) <span class="sc">/</span> <span class="fl">1e9</span>))</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>fig_comp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(comp_df, <span class="fu">aes</span>(year, bn_vnd, <span class="at">fill =</span> component)) <span class="sc">+</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">colour =</span> <span class="st">"grey30"</span>) <span class="sc">+</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(<span class="at">year =</span> <span class="fu">factor</span>(tab<span class="sc">$</span>year), <span class="at">bn_vnd =</span> <span class="fu">bn</span>(tab<span class="sc">$</span>impact)),</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(year, bn_vnd), <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">fill =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> pal_course[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>], <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Tỷ VNĐ (giá 2025, không chiết khấu)"</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Tác động ngân sách của việc mở rộng BPaLM theo năm và cấu phần"</span>,</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Cột: thay đổi từng cấu phần; điểm tròn: tác động ròng"</span>) <span class="sc">+</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_legend</span>(<span class="at">nrow =</span> <span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_comp, <span class="st">"l01-bia-components.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l01-bia-components.png" class="img-fluid figure-img"></p>
<figcaption>Tác động ngân sách theo năm và cấu phần chi phí</figcaption>
</figure>
</div>
<p>Phân tích độ nhạy một chiều (OWSA) cho tổng tác động 5 năm: đổi từng tham số về giá trị thấp và cao, giữ nguyên các tham số khác. Giá thuốc và chi phí theo dõi đổi qua hệ số nhân (giá trị minh họa) quanh giá chung của khóa học; tỷ lệ biến cố bất lợi dùng khoảng 95% của phân phối beta với 151 người mỗi nhánh, đúng cỡ quần thể an toàn của thử nghiệm <span class="citation" data-cites="nyangwa2024short">(<a href="#ref-nyangwa2024short" role="doc-biblioref">Nyang’wa và c.s. 2024</a>)</span>. Kiểm tra: ở giá trị cơ sở, hàm <code>total_with()</code> cho lại đúng tổng tác động (<code>stopifnot</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-way sensitivity of the 5-year budget impact: each input at its low and high value</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>total_with <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">pb_k =</span> pb, <span class="at">p02_k =</span> p02) <span class="fu">bia_total</span>(pb_k, p02_k, res)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(<span class="fu">total_with</span>() <span class="sc">-</span> bia_5y) <span class="sc">&lt;</span> <span class="fl">1e-3</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>lab <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">growth_rate =</span> <span class="st">"Tốc độ thay đổi số người bệnh mỗi năm"</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">share_eligible =</span> <span class="st">"Tỷ lệ đủ điều kiện nhận BPaLM"</span>,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">hosp_mean_ratio =</span> <span class="st">"Chi phí nằm viện: trung bình / trung vị"</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">mult_drug_bpalm =</span> <span class="st">"Giá thuốc BPaLM (hệ số nhân)"</span>,</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">mult_drug_short =</span> <span class="st">"Giá thuốc phác đồ ngắn (hệ số nhân)"</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">mult_drug_long =</span> <span class="st">"Giá thuốc phác đồ dài hạn (hệ số nhân)"</span>,</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">mult_monitor =</span> <span class="st">"Chi phí theo dõi (hệ số nhân)"</span>,</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">ae_bpalm =</span> <span class="st">"Tỷ lệ biến cố bất lợi nặng, BPaLM"</span>,</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">ae_soc =</span> <span class="st">"Tỷ lệ biến cố bất lợi nặng, dài hạn và ngắn"</span>,</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">uptake =</span> <span class="fu">paste0</span>(<span class="st">"Tỷ lệ dùng BPaLM khi mở rộng (cả "</span>, pb<span class="sc">$</span>horizon_years, <span class="st">" năm)"</span>))</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>rng <span class="ot">&lt;-</span> <span class="cf">function</span>(tab_k, nm) <span class="fu">unlist</span>(tab_k[tab_k<span class="sc">$</span>name <span class="sc">==</span> nm, <span class="fu">c</span>(<span class="st">"low"</span>, <span class="st">"high"</span>)])</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>owsa <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>add_row <span class="ot">&lt;-</span> <span class="cf">function</span>(owsa, nm, out) <span class="fu">rbind</span>(owsa, <span class="fu">data.frame</span>(<span class="at">input =</span> lab[[nm]], <span class="at">low =</span> out[<span class="dv">1</span>], <span class="at">high =</span> out[<span class="dv">2</span>]))</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a><span class="co"># (1) inputs of the BIA table</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (nm <span class="cf">in</span> <span class="fu">c</span>(<span class="st">"growth_rate"</span>, <span class="st">"share_eligible"</span>, <span class="st">"hosp_mean_ratio"</span>, <span class="st">"mult_drug_bpalm"</span>,</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>             <span class="st">"mult_drug_short"</span>, <span class="st">"mult_drug_long"</span>, <span class="st">"mult_monitor"</span>)) {</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>  out <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (v <span class="cf">in</span> <span class="fu">rng</span>(ptab_bia, nm)) { pb_k <span class="ot">&lt;-</span> pb; pb_k[[nm]] <span class="ot">&lt;-</span> v; out <span class="ot">&lt;-</span> <span class="fu">c</span>(out, <span class="fu">total_with</span>(<span class="at">pb_k =</span> pb_k)) }</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>  owsa <span class="ot">&lt;-</span> <span class="fu">add_row</span>(owsa, nm, out)</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a><span class="co"># (2) uptake: all five years at their low values together, then at their high values</span></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>up_names <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"uptake_y"</span>, <span class="dv">1</span><span class="sc">:</span>pb<span class="sc">$</span>horizon_years)</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>out <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (side <span class="cf">in</span> <span class="fu">c</span>(<span class="st">"low"</span>, <span class="st">"high"</span>)) {</span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>  pb_k <span class="ot">&lt;-</span> pb</span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (nm <span class="cf">in</span> up_names) pb_k[[nm]] <span class="ot">&lt;-</span> ptab_bia[ptab_bia<span class="sc">$</span>name <span class="sc">==</span> nm, side]</span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>  out <span class="ot">&lt;-</span> <span class="fu">c</span>(out, <span class="fu">total_with</span>(<span class="at">pb_k =</span> pb_k))</span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>owsa <span class="ot">&lt;-</span> <span class="fu">add_row</span>(owsa, <span class="st">"uptake"</span>, out)</span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a><span class="co"># (3) adverse-event rates: 95% interval of a beta distribution with ae_n_arm patients</span></span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (nm <span class="cf">in</span> <span class="fu">c</span>(<span class="st">"ae_bpalm"</span>, <span class="st">"ae_soc"</span>)) {</span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a>  r <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), pb<span class="sc">$</span>ae_n_arm <span class="sc">*</span> p02[[nm]], pb<span class="sc">$</span>ae_n_arm <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p02[[nm]]))</span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a>  out <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (v <span class="cf">in</span> r) { p_k <span class="ot">&lt;-</span> p02; p_k[[nm]] <span class="ot">&lt;-</span> v; out <span class="ot">&lt;-</span> <span class="fu">c</span>(out, <span class="fu">total_with</span>(<span class="at">p02_k =</span> p_k)) }</span>
<span id="cb23-38"><a href="#cb23-38" aria-hidden="true" tabindex="-1"></a>  owsa <span class="ot">&lt;-</span> <span class="fu">add_row</span>(owsa, nm, out)</span>
<span id="cb23-39"><a href="#cb23-39" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb23-40"><a href="#cb23-40" aria-hidden="true" tabindex="-1"></a>owsa<span class="sc">$</span>swing <span class="ot">&lt;-</span> <span class="fu">abs</span>(owsa<span class="sc">$</span>high <span class="sc">-</span> owsa<span class="sc">$</span>low)</span>
<span id="cb23-41"><a href="#cb23-41" aria-hidden="true" tabindex="-1"></a>owsa <span class="ot">&lt;-</span> owsa[<span class="fu">order</span>(owsa<span class="sc">$</span>swing), ]</span>
<span id="cb23-42"><a href="#cb23-42" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(<span class="at">input =</span> owsa<span class="sc">$</span>input, <span class="at">low =</span> <span class="fu">fmt_num</span>(<span class="fu">bn</span>(owsa<span class="sc">$</span>low), <span class="dv">1</span>),</span>
<span id="cb23-43"><a href="#cb23-43" aria-hidden="true" tabindex="-1"></a>                        <span class="at">high =</span> <span class="fu">fmt_num</span>(<span class="fu">bn</span>(owsa<span class="sc">$</span>high), <span class="dv">1</span>), <span class="at">swing =</span> <span class="fu">fmt_num</span>(<span class="fu">bn</span>(owsa<span class="sc">$</span>swing), <span class="dv">1</span>)),</span>
<span id="cb23-44"><a href="#cb23-44" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Tham số"</span>, <span class="st">"Ở giá trị thấp"</span>, <span class="st">"Ở giá trị cao"</span>, <span class="st">"Biên độ"</span>),</span>
<span id="cb23-45"><a href="#cb23-45" aria-hidden="true" tabindex="-1"></a>             <span class="at">align =</span> <span class="st">"lrrr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 54%">
<col style="width: 18%">
<col style="width: 17%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tham số</th>
<th style="text-align: right;">Ở giá trị thấp</th>
<th style="text-align: right;">Ở giá trị cao</th>
<th style="text-align: right;">Biên độ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Chi phí theo dõi (hệ số nhân)</td>
<td style="text-align: right;">-36.4</td>
<td style="text-align: right;">-44.5</td>
<td style="text-align: right;">8.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tỷ lệ biến cố bất lợi nặng, BPaLM</td>
<td style="text-align: right;">-49.4</td>
<td style="text-align: right;">-36.2</td>
<td style="text-align: right;">13.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Giá thuốc phác đồ ngắn (hệ số nhân)</td>
<td style="text-align: right;">-35.4</td>
<td style="text-align: right;">-48.9</td>
<td style="text-align: right;">13.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tốc độ thay đổi số người bệnh mỗi năm</td>
<td style="text-align: right;">-38.6</td>
<td style="text-align: right;">-53.7</td>
<td style="text-align: right;">15.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tỷ lệ biến cố bất lợi nặng, dài hạn và ngắn</td>
<td style="text-align: right;">-35.3</td>
<td style="text-align: right;">-51.1</td>
<td style="text-align: right;">15.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tỷ lệ đủ điều kiện nhận BPaLM</td>
<td style="text-align: right;">-29.9</td>
<td style="text-align: right;">-52.0</td>
<td style="text-align: right;">22.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Giá thuốc phác đồ dài hạn (hệ số nhân)</td>
<td style="text-align: right;">-41.0</td>
<td style="text-align: right;">-64.1</td>
<td style="text-align: right;">23.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Giá thuốc BPaLM (hệ số nhân)</td>
<td style="text-align: right;">-50.1</td>
<td style="text-align: right;">-25.7</td>
<td style="text-align: right;">24.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chi phí nằm viện: trung bình / trung vị</td>
<td style="text-align: right;">-43.1</td>
<td style="text-align: right;">-67.8</td>
<td style="text-align: right;">24.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tỷ lệ dùng BPaLM khi mở rộng (cả 5 năm)</td>
<td style="text-align: right;">-19.9</td>
<td style="text-align: right;">-58.7</td>
<td style="text-align: right;">38.8</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>top_input <span class="ot">&lt;-</span> owsa<span class="sc">$</span>input[<span class="fu">nrow</span>(owsa)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>tor <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">data.frame</span>(<span class="at">input =</span> owsa<span class="sc">$</span>input, <span class="at">side =</span> <span class="st">"Giá trị thấp"</span>, <span class="at">bn_vnd =</span> <span class="fu">bn</span>(owsa<span class="sc">$</span>low)),</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>             <span class="fu">data.frame</span>(<span class="at">input =</span> owsa<span class="sc">$</span>input, <span class="at">side =</span> <span class="st">"Giá trị cao"</span>, <span class="at">bn_vnd =</span> <span class="fu">bn</span>(owsa<span class="sc">$</span>high)))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>tor<span class="sc">$</span>input <span class="ot">&lt;-</span> <span class="fu">factor</span>(tor<span class="sc">$</span>input, <span class="at">levels =</span> owsa<span class="sc">$</span>input)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>tor<span class="sc">$</span>side <span class="ot">&lt;-</span> <span class="fu">factor</span>(tor<span class="sc">$</span>side, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Giá trị thấp"</span>, <span class="st">"Giá trị cao"</span>))</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>fig_tor <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(tor, <span class="fu">aes</span>(<span class="at">y =</span> input)) <span class="sc">+</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="at">data =</span> owsa, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">bn</span>(low), <span class="at">xend =</span> <span class="fu">bn</span>(high), <span class="at">y =</span> <span class="fu">factor</span>(input, <span class="at">levels =</span> input),</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                                <span class="at">yend =</span> <span class="fu">factor</span>(input, <span class="at">levels =</span> input)),</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">colour =</span> <span class="st">"grey70"</span>, <span class="at">linewidth =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> bn_vnd, <span class="at">colour =</span> side), <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">bn</span>(bia_5y), <span class="at">linetype =</span> <span class="st">"22"</span>) <span class="sc">+</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">colour =</span> <span class="st">"grey30"</span>) <span class="sc">+</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> pal_course[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)], <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="fu">paste0</span>(<span class="st">"Tác động ngân sách "</span>, pb<span class="sc">$</span>horizon_years, <span class="st">" năm (tỷ VNĐ)"</span>), <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Tham số nào làm tác động ngân sách thay đổi nhiều nhất?"</span>,</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Đường đứt: phân tích cơ sở"</span>) <span class="sc">+</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_tor, <span class="st">"l01-tornado.png"</span>, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="fl">5.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l01-tornado.png" class="img-fluid figure-img"></p>
<figcaption>Phân tích độ nhạy một chiều của tổng tác động ngân sách</figcaption>
</figure>
</div>
<p>Tham số chi phối nhiều nhất là “Tỷ lệ dùng BPaLM khi mở rộng (cả 5 năm)”. Trong mọi trường hợp đã thử, mở rộng BPaLM vẫn tiết kiệm ngân sách.</p>
<p>Kịch bản cơ cấu điều trị hiện tại: cùng 3,050 người bệnh, nhưng hôm nay họ dùng phác đồ khác nhau. Kiểm tra: BPaLM thay phác đồ dài hạn thì tiết kiệm nhiều hơn, thay phác đồ ngắn thì ít hơn (<code>stopifnot</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scenario: the current treatment mix. What BPaLM replaces decides how much it saves.</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Each scenario keeps the 2024 total and changes who is on which regimen today.</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>n0 <span class="ot">&lt;-</span> <span class="fu">current_counts</span>(pb)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>set_counts <span class="ot">&lt;-</span> <span class="cf">function</span>(pb_k, n) {</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  pb_k<span class="sc">$</span>who_tx_18m_2024 <span class="ot">&lt;-</span> n[[<span class="st">"long"</span>]]; pb_k<span class="sc">$</span>who_tx_9m_2024 <span class="ot">&lt;-</span> n[[<span class="st">"short"</span>]]; pb_k<span class="sc">$</span>who_tx_6m_2024 <span class="ot">&lt;-</span> n[[<span class="st">"bpalm"</span>]]</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  pb_k</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>other0 <span class="ot">&lt;-</span> n0[<span class="fu">c</span>(<span class="st">"long"</span>, <span class="st">"short"</span>)] <span class="sc">/</span> <span class="fu">sum</span>(n0[<span class="fu">c</span>(<span class="st">"long"</span>, <span class="st">"short"</span>)])</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>mixes <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"WHO 2024 (phân tích cơ sở)"</span> <span class="ot">=</span> n0,</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Chưa ai dùng BPaLM (trước 2024)"</span> <span class="ot">=</span> <span class="fu">c</span>(n0[<span class="fu">c</span>(<span class="st">"long"</span>, <span class="st">"short"</span>)] <span class="sc">+</span> n0[[<span class="st">"bpalm"</span>]] <span class="sc">*</span> other0, <span class="at">bpalm =</span> <span class="dv">0</span>),</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Mọi người không dùng BPaLM đều dùng phác đồ dài hạn"</span> <span class="ot">=</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="at">long =</span> <span class="fu">sum</span>(n0[<span class="fu">c</span>(<span class="st">"long"</span>, <span class="st">"short"</span>)]), <span class="at">short =</span> <span class="dv">0</span>, <span class="at">bpalm =</span> n0[[<span class="st">"bpalm"</span>]]),</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Mọi người không dùng BPaLM đều dùng phác đồ ngắn"</span> <span class="ot">=</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="at">long =</span> <span class="dv">0</span>, <span class="at">short =</span> <span class="fu">sum</span>(n0[<span class="fu">c</span>(<span class="st">"long"</span>, <span class="st">"short"</span>)]), <span class="at">bpalm =</span> n0[[<span class="st">"bpalm"</span>]])</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>mix_tab <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (nm <span class="cf">in</span> <span class="fu">names</span>(mixes)) {</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>  pb_k <span class="ot">&lt;-</span> <span class="fu">set_counts</span>(pb, mixes[[nm]][REGIMENS])</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>  tab_k <span class="ot">&lt;-</span> <span class="fu">bia_by_year</span>(<span class="fu">run_bia</span>(pb_k, prof), pb<span class="sc">$</span>start_year)</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>  mix_tab <span class="ot">&lt;-</span> <span class="fu">rbind</span>(mix_tab, <span class="fu">data.frame</span>(<span class="at">scenario =</span> nm, <span class="at">level_y1 =</span> tab_k<span class="sc">$</span>current[<span class="dv">1</span>],</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>                                       <span class="at">impact_y1 =</span> tab_k<span class="sc">$</span>impact[<span class="dv">1</span>], <span class="at">impact_5y =</span> <span class="fu">sum</span>(tab_k<span class="sc">$</span>impact)))</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(<span class="at">scenario =</span> mix_tab<span class="sc">$</span>scenario, <span class="at">level =</span> <span class="fu">fmt_num</span>(<span class="fu">bn</span>(mix_tab<span class="sc">$</span>level_y1), <span class="dv">1</span>),</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>                        <span class="at">y1 =</span> <span class="fu">fmt_num</span>(<span class="fu">bn</span>(mix_tab<span class="sc">$</span>impact_y1), <span class="dv">1</span>), <span class="at">y5 =</span> <span class="fu">fmt_num</span>(<span class="fu">bn</span>(mix_tab<span class="sc">$</span>impact_5y), <span class="dv">1</span>)),</span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Cơ cấu điều trị hiện tại"</span>, <span class="st">"Ngân sách hiện tại năm đầu (tỷ VNĐ)"</span>,</span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"Tác động năm đầu (tỷ VNĐ)"</span>, <span class="st">"Tác động 5 năm (tỷ VNĐ)"</span>), <span class="at">align =</span> <span class="st">"lrrr"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 37%">
<col style="width: 26%">
<col style="width: 18%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Cơ cấu điều trị hiện tại</th>
<th style="text-align: right;">Ngân sách hiện tại năm đầu (tỷ VNĐ)</th>
<th style="text-align: right;">Tác động năm đầu (tỷ VNĐ)</th>
<th style="text-align: right;">Tác động 5 năm (tỷ VNĐ)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">WHO 2024 (phân tích cơ sở)</td>
<td style="text-align: right;">68.3</td>
<td style="text-align: right;">-1.7</td>
<td style="text-align: right;">-43.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chưa ai dùng BPaLM (trước 2024)</td>
<td style="text-align: right;">75.7</td>
<td style="text-align: right;">-4.8</td>
<td style="text-align: right;">-75.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mọi người không dùng BPaLM đều dùng phác đồ dài hạn</td>
<td style="text-align: right;">78.1</td>
<td style="text-align: right;">-1.6</td>
<td style="text-align: right;">-58.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mọi người không dùng BPaLM đều dùng phác đồ ngắn</td>
<td style="text-align: right;">60.5</td>
<td style="text-align: right;">-1.8</td>
<td style="text-align: right;">-31.4</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>saving <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">setNames</span>(mix_tab<span class="sc">$</span>impact_5y, <span class="fu">c</span>(<span class="st">"base"</span>, <span class="st">"no_bpalm"</span>, <span class="st">"all_long"</span>, <span class="st">"all_short"</span>))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Claims in the text: BPaLM saves more when it replaces the long regimen, less when it</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># replaces the short one, and more if nobody were on BPaLM yet</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(saving[[<span class="st">"all_long"</span>]] <span class="sc">&gt;</span> saving[[<span class="st">"base"</span>]], saving[[<span class="st">"base"</span>]] <span class="sc">&gt;</span> saving[[<span class="st">"all_short"</span>]],</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>          saving[[<span class="st">"no_bpalm"</span>]] <span class="sc">&gt;</span> saving[[<span class="st">"base"</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nếu mọi người không dùng BPaLM đều đang dùng phác đồ dài hạn, mở rộng tiết kiệm 58.0 tỷ VNĐ; nếu họ đều dùng phác đồ ngắn, chỉ còn 31.4 tỷ VNĐ. Nếu chưa ai dùng BPaLM như trước năm 2024, khoản tiết kiệm sẽ là 75.1 tỷ VNĐ thay vì 43.1: một BIA dựa trên cơ cấu cũ sẽ phóng đại lợi ích của việc mở rộng.</p>
<p>Cuối cùng, tìm <strong>giá trung hòa ngân sách</strong>: giá thuốc BPaLM mỗi tháng mà tại đó tác động 5 năm bằng 0. Kiểm tra: tác động tại giá tìm được gần bằng 0 (<code>stopifnot</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Budget-neutral price: the monthly BPaLM drug price at which the 5-year impact is zero</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>price_neutral <span class="ot">&lt;-</span> <span class="fu">budget_neutral_price</span>(pb, p02, res)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="sc">!</span><span class="fu">is.na</span>(price_neutral), price_neutral <span class="sc">&gt;</span> p_bia<span class="sc">$</span>c_drug_bpalm,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>          <span class="fu">abs</span>(<span class="fu">total_with</span>(<span class="at">p02_k =</span> <span class="fu">replace</span>(p02, <span class="st">"c_drug_bpalm"</span>, price_neutral),</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">pb_k =</span> <span class="fu">replace</span>(pb, <span class="st">"mult_drug_bpalm"</span>, <span class="dv">1</span>))) <span class="sc">&lt;</span> <span class="fl">1e3</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">base_price =</span> p_bia<span class="sc">$</span>c_drug_bpalm, <span class="at">neutral_price =</span> price_neutral,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">ratio =</span> price_neutral <span class="sc">/</span> p_bia<span class="sc">$</span>c_drug_bpalm), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   base_price neutral_price         ratio 
   1181913.33    2645481.26          2.24 </code></pre>
</div>
</div>
<p>Mở rộng BPaLM vẫn không làm tăng ngân sách 5 năm cho đến khi giá thuốc lên khoảng 2.65 triệu VNĐ mỗi tháng, gấp 2.2 lần giá GDF hiện dùng <span class="citation" data-cites="itpc2025gdf">(<a href="#ref-itpc2025gdf" role="doc-biblioref">ITPC-EECA 2025</a>)</span>. Con số này hữu ích khi đàm phán giá hoặc khi tài trợ thuốc giảm và Việt Nam phải tự mua.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Mẹo thực hành">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mẹo thực hành
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Tách <strong>nguồn lực</strong> (số tháng điều trị, số biến cố) khỏi <strong>giá</strong>. Khi đơn vị chi trả hỏi “nếu giá thuốc là X thì sao?”, bạn chỉ cần nhân lại, không cần chạy lại mô hình.</li>
<li>Luôn trình bày bảng theo từng năm, cả hai thế giới, tác động và cộng dồn; người giữ ngân sách đọc theo năm tài khóa, không đọc theo người bệnh.</li>
<li>Hỏi sớm “ngân sách của ai?” và “hiện nay người bệnh đang dùng phác đồ nào?”. Số liệu báo cáo WHO của chương trình (số người theo phác đồ, chi phí thuốc mỗi người) là nguồn công khai dễ lấy nhất.</li>
<li>Đối chiếu tổng chi phí của thế giới hiện tại với số chi thực tế của chương trình. Đây là kiểm tra hợp lý rẻ nhất, và nó bắt được lỗi thiếu người đã điều trị từ trước.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Lỗi thường gặp">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lỗi thường gặp
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Bắt đầu dòng người từ số 0.</strong> Ngân sách năm đầu thiếu người đã điều trị từ trước, nên mức ngân sách sai (tác động thì không đổi). Thêm giai đoạn chạy đà.</li>
<li><strong>Nhân chi phí trọn đời mỗi người với số người mỗi năm.</strong> Cách này bỏ qua việc chi phí kéo dài sang năm sau và tính cả chi phí ngoài khung thời gian. Dùng dòng tiền theo tháng và cộng dồn như trên.</li>
<li><strong>Chiết khấu trong BIA.</strong> Người giữ ngân sách cần tiền thực chi; nếu cần, trình bày thêm số đã chiết khấu như một phân tích phụ.</li>
<li><strong>Giả định áp dụng 100% ngay năm đầu, hoặc dùng cơ cấu điều trị cũ.</strong> Cả hai làm kết quả trông tốt hơn thực tế (bài tập 1 và kịch bản cơ cấu hiện tại).</li>
<li><strong>Dùng mô hình BIA khác mô hình CEA.</strong> Hai mô hình với giả định lâm sàng khác nhau sẽ cho hai câu chuyện không khớp; ISPOR khuyên giữ chúng nhất quán <span class="citation" data-cites="mauskopf2007principles">(<a href="#ref-mauskopf2007principles" role="doc-biblioref">Mauskopf và c.s. 2007</a>)</span>.</li>
</ul>
</div>
</div>
</section>
<section id="bài-tập" class="level2">
<h2 class="anchored" data-anchor-id="bài-tập">Bài tập</h2>
<ol type="1">
<li><strong>(Dễ)</strong> Giả sử mọi người bệnh đủ điều kiện chuyển sang BPaLM ngay từ tháng đầu. Tác động 5 năm và tác động năm đầu thay đổi thế nào?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 1: every eligible patient is on BPaLM from the first month</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>pb_all <span class="ot">&lt;-</span> pb</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (nm <span class="cf">in</span> up_names) pb_all[[nm]] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>bia_all <span class="ot">&lt;-</span> <span class="fu">bia_by_year</span>(<span class="fu">run_bia</span>(pb_all, prof), pb<span class="sc">$</span>start_year)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">base_5y =</span> <span class="fu">bn</span>(bia_5y), <span class="at">full_uptake_5y =</span> <span class="fu">bn</span>(<span class="fu">sum</span>(bia_all<span class="sc">$</span>impact)),</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">base_y1 =</span> <span class="fu">bn</span>(tab<span class="sc">$</span>impact[<span class="dv">1</span>]), <span class="at">full_uptake_y1 =</span> <span class="fu">bn</span>(bia_all<span class="sc">$</span>impact[<span class="dv">1</span>])), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       base_5y full_uptake_5y        base_y1 full_uptake_y1 
         -43.1          -78.4           -1.7           -7.6 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The text says faster uptake saves more</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">sum</span>(bia_all<span class="sc">$</span>impact) <span class="sc">&lt;</span> bia_5y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Tác động 5 năm đổi từ -43.1 thành -78.4 tỷ VNĐ, và tác động năm đầu từ -1.7 thành -7.6 tỷ VNĐ. Áp dụng nhanh hơn thì tiết kiệm nhiều hơn, nhưng đây là kịch bản lạc quan: thực tế cần đào tạo, xét nghiệm kháng thuốc mới và cung ứng thuốc ở mọi tỉnh, không chỉ các bệnh viện tuyến cuối.</p>
</div>
</div>
</div>
<ol start="2" type="1">
<li><strong>(Vừa)</strong> Theo dõi tiếp 3 năm sau khi khung thời gian kết thúc, không nhận người bệnh mới. Bao nhiêu tác động nằm ngoài khung thời gian, và vì sao?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 2: costs that fall after the horizon. Follow the five annual cohorts for</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 3 more years with no new patients, and compare with the 5-year window.</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># (The run-in patients are left out: they are identical in both worlds and cancel.)</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>H <span class="ot">&lt;-</span> <span class="fu">nrow</span>(sched)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>pad <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">c</span>(x, <span class="fu">rep</span>(<span class="dv">0</span>, extra_months))</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>n_all <span class="ot">&lt;-</span> H <span class="sc">+</span> extra_months</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>cur_full <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>new_full <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (g <span class="cf">in</span> REGIMENS) {</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  cur_full <span class="ot">&lt;-</span> cur_full <span class="sc">+</span> <span class="fu">cohort_costs</span>(<span class="fu">pad</span>(sched[[<span class="fu">paste0</span>(g, <span class="st">"_now"</span>)]]), prof[[g]], n_all)</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  new_full <span class="ot">&lt;-</span> new_full <span class="sc">+</span> <span class="fu">cohort_costs</span>(<span class="fu">pad</span>(sched[[g]]), prof[[g]], n_all)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>impact_full <span class="ot">&lt;-</span> <span class="fu">sum</span>(new_full <span class="sc">-</span> cur_full)</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>impact_after <span class="ot">&lt;-</span> <span class="fu">sum</span>((new_full <span class="sc">-</span> cur_full)[(H <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">:</span>n_all, ])</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(<span class="fu">sum</span>((new_full <span class="sc">-</span> cur_full)[<span class="dv">1</span><span class="sc">:</span>H, ]) <span class="sc">-</span> bia_5y) <span class="sc">&lt;</span> <span class="fl">1e-3</span>)</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">within_5y =</span> <span class="fu">bn</span>(bia_5y), <span class="at">after_horizon =</span> <span class="fu">bn</span>(impact_after), <span class="at">total =</span> <span class="fu">bn</span>(impact_full)), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    within_5y after_horizon         total 
        -43.1         -11.2         -54.4 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The text says more savings fall after the horizon (the long regimen's second year)</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(impact_after <span class="sc">&lt;</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Trong 3 năm sau khung thời gian có thêm -11.2 tỷ VNĐ tác động (số âm là tiết kiệm). Người bắt đầu phác đồ dài hạn trong năm cuối vẫn còn tiêu tiền thuốc và theo dõi ở năm sau, và người thất bại hay bỏ điều trị còn được điều trị lại nhiều năm sau, nên thế giới hiện tại “đắt” thêm sau khung thời gian. BIA cắt khoản này đi, nên một chương trình tiết kiệm dài hạn trông kém hấp dẫn hơn trong BIA ngắn hạn. Nên báo cáo con số này như một phân tích phụ.</p>
</div>
</div>
</div>
<ol start="3" type="1">
<li><strong>(Khó)</strong> Tìm giá thuốc BPaLM mỗi tháng làm tác động <strong>năm đầu</strong> bằng 0 và so với giá trung hòa 5 năm. Giá nào chặt hơn, và nó nói gì với đơn vị chi trả?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 3: budget-neutral price in year 1 only versus over 5 years</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>price_neutral_y1 <span class="ot">&lt;-</span> <span class="fu">budget_neutral_price</span>(pb, p02, res, <span class="at">year =</span> <span class="dv">1</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">neutral_5y =</span> price_neutral, <span class="at">neutral_y1 =</span> price_neutral_y1), <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>neutral_5y neutral_y1 
   2645481    2082798 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="sc">!</span><span class="fu">is.na</span>(price_neutral_y1), price_neutral_y1 <span class="sc">&lt;</span> price_neutral)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Giá trung hòa năm đầu là khoảng 2.08 triệu VNĐ/tháng, thấp hơn giá trung hòa 5 năm (khoảng 2.65 triệu VNĐ/tháng). Năm đầu, BPaLM tốn tiền ngay còn khoản tiết kiệm của phác đồ dài hạn chưa đến, nên điều kiện “không tăng ngân sách năm đầu” khắt khe hơn. Một đơn vị chi trả có ngân sách năm cứng nhắc, như ngân sách thuốc của Chương trình Chống lao, cần nhìn cả hai giá.</p>
</div>
</div>
</div>
</section>
<section id="tài-liệu-tham-khảo" class="level2">
<h2 class="anchored" data-anchor-id="tài-liệu-tham-khảo">Tài liệu tham khảo</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-bilinski2017when" class="csl-entry" role="listitem">
Bilinski, Alyssa, Peter Neumann, Joshua Cohen, Teja Thorat, Katherine McDaniel, và Joshua A. Salomon. 2017. <span>“When cost-effective interventions are unaffordable: integrating cost-effectiveness and budget impact in priority setting for global health programs”</span>. <em>PLoS Medicine</em> 14 (10): e1002397. <a href="https://doi.org/10.1371/journal.pmed.1002397">https://doi.org/10.1371/journal.pmed.1002397</a>.
</div>
<div id="ref-scdi2024supports" class="csl-entry" role="listitem">
Center for Supporting Community Development Initiatives (SCDI). 2024. <span>“The current supports for tuberculosis patients”</span>. 11 Tháng Chạp 2024. <a href="https://www.scdi.org.vn/en/news/the-current-supports-for-tuberculosis-patients.html">https://www.scdi.org.vn/en/news/the-current-supports-for-tuberculosis-patients.html</a>.
</div>
<div id="ref-gso2026population2025" class="csl-entry" role="listitem">
Cục Thống kê (Bộ Tài chính). 2026. <span>“Thông cáo báo chí về tình hình dân số, lao động, việc làm quý <span>IV</span> và năm 2025”</span>. 5 Tháng Giêng 2026. <a href="https://www.nso.gov.vn/?p=59530">https://www.nso.gov.vn/?p=59530</a>.
</div>
<div id="ref-vov2024bhyt" class="csl-entry" role="listitem">
Đài Tiếng nói Việt Nam (VOV). 2024. <span>“Bảo hiểm y tế – <span>‘Chiếc phao cứu sinh’</span> cho người bệnh lao điều trị bệnh dài ngày”</span>. 12 Tháng Chạp 2024. <a href="https://vov.vn/xa-hoi/bao-hiem-y-te-chiec-phao-cuu-sinh-cho-nguoi-benh-lao-dieu-tri-benh-dai-ngay-post1139840.vov">https://vov.vn/xa-hoi/bao-hiem-y-te-chiec-phao-cuu-sinh-cho-nguoi-benh-lao-dieu-tri-benh-dai-ngay-post1139840.vov</a>.
</div>
<div id="ref-itpc2025gdf" class="csl-entry" role="listitem">
ITPC-EECA. 2025. <span>“<span>GDF</span> Announces Bedaquiline Price Reduction”</span>. 16 Tháng Chín 2025. <a href="https://itpc-eeca.org/en/2025/09/16/gdf-announces-bedaquiline-price-reduction/">https://itpc-eeca.org/en/2025/09/16/gdf-announces-bedaquiline-price-reduction/</a>.
</div>
<div id="ref-mauskopf2007principles" class="csl-entry" role="listitem">
Mauskopf, Josephine A., Sean D. Sullivan, Lieven Annemans, Jaime Caro, C. Daniel Mullins, Mark Nuijten, Ewa Orlewska, John Watkins, và Paul Trueman. 2007. <span>“Principles of good practice for budget impact analysis: report of the <span>ISPOR</span> Task Force on good research practices–budget impact analysis”</span>. <em>Value in Health</em> 10 (5): 336–47. <a href="https://doi.org/10.1111/j.1524-4733.2007.00187.x">https://doi.org/10.1111/j.1524-4733.2007.00187.x</a>.
</div>
<div id="ref-ngo2026direct" class="csl-entry" role="listitem">
Ngo, Do Minh, An Thi Binh Nguyen, Hanh Duc Nguyen, và Van Hau Hoang. 2026. <span>“Direct medical costs for drug-resistant tuberculosis inpatients at the national lung hospital, <span>Vietnam</span>: a one-year study”</span>. <em>Journal of Public Health Research</em> 15 (3): 22799036261467454. <a href="https://doi.org/10.1177/22799036261467454">https://doi.org/10.1177/22799036261467454</a>.
</div>
<div id="ref-nguyen2026from" class="csl-entry" role="listitem">
Nguyen, Thi Mai Phuong, Van Luong Dinh, Binh Hoa Nguyen, Thi Thanh Thuy Hoang, Viet Nhung Nguyen, Steven Callens, và Tom Decroo. 2026. <span>“From trials to programmatic scale-up: treatment outcomes of rifampicin-resistant tuberculosis during transition to short oral regimens in <span>Vietnam</span> (2021–2022)”</span>. <em>International Journal of Infectious Diseases</em> 163: 108222. <a href="https://doi.org/10.1016/j.ijid.2025.108222">https://doi.org/10.1016/j.ijid.2025.108222</a>.
</div>
<div id="ref-nyangwa2024short" class="csl-entry" role="listitem">
Nyang’wa, Bern-Thomas, Catherine Berry, Emil Kazounis, Ilaria Motta, Nargiza Parpieva, Zinaida Tigay, Ronelle Moodliar, và c.s. 2024. <span>“Short oral regimens for pulmonary rifampicin-resistant tuberculosis (<span>TB-PRACTECAL</span>): an open-label, randomised, controlled, phase <span>2B</span>–3, multi-arm, multicentre, non-inferiority trial”</span>. <em>The Lancet Respiratory Medicine</em> 12 (2): 117–28. <a href="https://doi.org/10.1016/S2213-2600(23)00389-2">https://doi.org/10.1016/S2213-2600(23)00389-2</a>.
</div>
<div id="ref-oh2026assessment" class="csl-entry" role="listitem">
Oh, Kyung Hyun, Jeungeun Seo, Yerin Yu, Fukushi Morishita, Alia Cynthia Luz, Huong Thi Giang Tran, Rajendra Prasad Hubraj Yadav, Martin P. Grobusch, và Hongjo Choi. 2026. <span>“Assessment of financial protection mechanisms for tuberculosis services in seven priority countries of the <span>Western Pacific Region</span>: a cross-sectional mixed-methods study”</span>. <em>Tropical Medicine and Health</em> 54 (1). <a href="https://doi.org/10.1186/s41182-026-00979-7">https://doi.org/10.1186/s41182-026-00979-7</a>.
</div>
<div id="ref-sullivan2014budget" class="csl-entry" role="listitem">
Sullivan, Sean D., Josephine A. Mauskopf, Federico Augustovski, J. Jaime Caro, Karen M. Lee, Mark Minchin, Ewa Orlewska, Pete Penna, Jose-Manuel Rodriguez Barrios, và Wen-Yi Shau. 2014. <span>“Budget impact analysis-principles of good practice: report of the <span>ISPOR</span> 2012 Budget Impact Analysis Good Practice <span>II</span> Task Force”</span>. <em>Value in Health</em> 17 (1): 5–14. <a href="https://doi.org/10.1016/j.jval.2013.08.2291">https://doi.org/10.1016/j.jval.2013.08.2291</a>.
</div>
<div id="ref-who2026tbnotif" class="csl-entry" role="listitem">
World Health Organization. 2026a. <span>“Global tuberculosis programme: case notifications by country and year (variables dr_6m_tx, dr_9m_tx, dr_18mplus_tx, conf_rr_nfqr_tx, unconf_rr_nfqr_tx, conf_rr_fqr_tx)”</span>. 2026. <a href="https://extranet.who.int/tme/generateCSV.asp?ds=notifications">https://extranet.who.int/tme/generateCSV.asp?ds=notifications</a>.
</div>
<div id="ref-who2026rrestimates" class="csl-entry" role="listitem">
———. 2026b. <span>“Global tuberculosis programme: <span>MDR/RR-TB</span> burden estimates by country and year (variable e_inc_rr_num)”</span>. 2026. <a href="https://extranet.who.int/tme/generateCSV.asp?ds=mdr_rr_estimates">https://extranet.who.int/tme/generateCSV.asp?ds=mdr_rr_estimates</a>.
</div>
<div id="ref-who2026tbfinance" class="csl-entry" role="listitem">
———. 2026c. <span>“Global tuberculosis programme: <span>TB</span> budgets and expenditure and utilisation of services by country and year (variables budget_patsup, cf_patsup, exp_cpp_mdr, budget_sld, cf_sld, cf_tot_gf)”</span>. 2026. <a href="https://extranet.who.int/tme/generateCSV.asp?ds=budget">https://extranet.who.int/tme/generateCSV.asp?ds=budget</a>.
</div>
</div>
<div class="video-script">
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kịch bản video (~14 phút)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Slide</th>
<th>Lời giảng chính</th>
<th>Hình/Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Bảng dự trù cuối năm</td>
<td>3,050 người bắt đầu điều trị năm 2024; 25% đã dùng phác đồ 6 tháng; ai trả tiền?</td>
<td>callout mở đầu</td>
</tr>
<tr class="even">
<td>2</td>
<td>Từ “đáng tiền” đến “trả nổi”</td>
<td>CEA trọn đời mỗi người; BIA tiền thực chi từng năm cho cả quần thể</td>
<td>chunk <code>l01-cea-vs-bia</code></td>
</tr>
<tr class="odd">
<td>3</td>
<td>Các thành phần</td>
<td>đơn vị chi trả, quần thể, cơ cấu hiện tại (WHO 2024), áp dụng, khung thời gian, chi phí</td>
<td>bảng thành phần</td>
</tr>
<tr class="even">
<td>4</td>
<td>Dòng tiền từ vết đoàn hệ</td>
<td>nguồn lực × giá; ba nhánh M02; điều trị lại; đối chiếu với số chương trình báo cáo</td>
<td>chunk <code>l01-profile</code></td>
</tr>
<tr class="odd">
<td>5</td>
<td>Quần thể mở và giai đoạn chạy đà</td>
<td>người mới vào mỗi tháng; người đã điều trị từ trước; tích chập <span class="math inline">\(B_t\)</span></td>
<td>công thức, chunk <code>l01-population</code></td>
</tr>
<tr class="even">
<td>6</td>
<td>Bảng BIA</td>
<td>hai thế giới, tác động, cộng dồn; năm đầu ít tiết kiệm</td>
<td>chunk <code>l01-bia</code>, <code>l01-checks</code></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Tiền đi đâu</td>
<td>biến cố bất lợi và theo dõi, không phải thuốc</td>
<td><code>figs/l01-bia-components.png</code></td>
</tr>
<tr class="even">
<td>8</td>
<td>Ngân sách của ai</td>
<td>thuốc: Chương trình Chống lao (tiền tài trợ); khám, xét nghiệm, nằm viện: BHYT</td>
<td>chunk <code>l01-components</code></td>
</tr>
<tr class="odd">
<td>9</td>
<td>Độ nhạy và cơ cấu hiện tại</td>
<td>tỷ lệ áp dụng, chi phí nằm viện, giá thuốc; thay phác đồ nào</td>
<td><code>figs/l01-tornado.png</code>, chunk <code>l01-mix</code></td>
</tr>
<tr class="even">
<td>10</td>
<td>Giá trung hòa ngân sách</td>
<td>công cụ đàm phán giá; điều kiện năm đầu chặt hơn</td>
<td>chunk <code>l01-price</code>, bài tập 3</td>
</tr>
<tr class="odd">
<td>11</td>
<td>Chuyển tiếp</td>
<td>ngân sách xong; ai được lợi? → Bài 2</td>
<td>—</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../kb/m10-policy-bia-equity/index.html" class="pagination-link" aria-label="M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" class="pagination-link" aria-label="Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)">
        <span class="nav-page-text"><span class="chapter-title">Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>