<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA – Mô hình Kinh tế Y tế với R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../kb/m11-software-engineering/index.html" rel="next">
<link href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9e7f0c659d5fa2cace8548cb57964278.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c18d72663580ed8ca19ce2a2f99af51b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="mermaid-theme" content="neutral">
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=JetBrains+Mono:wght@400;600&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m10-policy-bia-equity/index.html">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</a></li><li class="breadcrumb-item"><a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Mô hình Kinh tế Y tế với R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lời mở đầu</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m00-r-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M00 · R cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l02-vectors-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l03-functions-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hàm, cấu trúc điều khiển, vòng lặp và vectơ hóa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l04-data-frames.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Data frame — nhập, làm sạch, tóm tắt và chuyển dạng dữ liệu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l05-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Biểu đồ với ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l06-randomness-monte-carlo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 6: Ngẫu nhiên, mô phỏng Monte Carlo và sai số Monte Carlo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m01-ee-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M01 · Nền tảng đánh giá kinh tế và cây quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l01-evaluation-types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại đánh giá kinh tế, quan điểm, khung thời gian và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l02-health-outcomes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Năm sống, QALY và DALY</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l03-decision-rules.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l04-thresholds.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l05-decision-tree.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Xây cây quyết định từ đầu trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m02-cohort-markov/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l01-state-transition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao cần mô hình chuyển trạng thái</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l03-cohort-trace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l04-time-dependence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Phụ thuộc thời gian: lão hóa, trạng thái đường hầm và mảng 3 chiều</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l05-results-verification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị gắn với lần chuyển, đường biên hiệu quả và xác minh mô hình</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m03-uncertainty-voi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l01-deterministic-sa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại bất định và phân tích độ nhạy tất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l02-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Chọn phân phối cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l03-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích độ nhạy xác suất (PSA) trong R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l05-voi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m04-microsimulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M04 · Mô phỏng vi mô (microsimulation)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l01-why-microsimulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l02-microsim-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l03-vectorisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vectơ hóa theo cá thể và đo hiệu năng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l04-parallel-rcpp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tính toán song song và Rcpp cho vòng lặp nóng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l05-mc-error-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bao nhiêu cá thể là đủ? Sai số Monte Carlo, PSA và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m05-dynamic-transmission/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M05 · Mô hình lây truyền động</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l01-static-vs-dynamic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Mô hình tĩnh và mô hình lây truyền động</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l02-sir-seir-desolve.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình SIR và SEIR trong R với deSolve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l03-vaccination-herd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Tiêm chủng, hiệu quả trực tiếp và gián tiếp</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l04-dengue-host-vector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Mô hình vật chủ–véc tơ cho sốt xuất huyết Dengue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l05-dynamic-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế với mô hình lây truyền động</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m06-amr-economics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M06 · Kinh tế học kháng kháng sinh (AMR)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l01-amr-burden.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l02-attributable-los.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l03-ward-transmission.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Mô hình lây truyền CRE trong khoa hồi sức</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l04-two-strain-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m07-survival-psm/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M07 · Phân tích sống còn cho mô hình quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l01-survival-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ôn tập phân tích sống còn cho người làm mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l02-parametric-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình sống còn tham số với flexsurv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l03-extrapolation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Ngoại suy sống còn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l04-reconstruct-ipd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tái tạo dữ liệu cá thể từ đường KM đã công bố và dùng HR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l05-partitioned-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Mô hình sống còn phân vùng trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m08-calibration/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M08 · Hiệu chuẩn mô hình (calibration)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l01-why-calibrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l02-search-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l03-bayes-sir.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hiệu chuẩn Bayes và thuật toán SIR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l04-psa-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đưa kết quả hiệu chuẩn vào PSA, thẩm định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m09-inputs-vietnam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l01-costing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ước tính chi phí cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l05-decision-context.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bối cảnh ra quyết định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m10-policy-bia-equity/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m11-software-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l01-code-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Cấu trúc mã cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l02-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Xác minh và kiểm thử mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l03-version-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quản lý phiên bản với Git và tái lập môi trường với renv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l04-r-package.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đóng gói mô hình thành gói R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l05-shiny-living.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Ứng dụng Shiny và mô hình “sống”</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bảng thuật ngữ Anh–Việt</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Trong bài</h2>
   
  <ul class="collapse">
  <li><a href="#mục-tiêu-học-tập" id="toc-mục-tiêu-học-tập" class="nav-link active" data-scroll-target="#mục-tiêu-học-tập">Mục tiêu học tập</a></li>
  <li><a href="#ý-chính" id="toc-ý-chính" class="nav-link" data-scroll-target="#ý-chính">Ý chính</a></li>
  <li><a href="#nội-dung" id="toc-nội-dung" class="nav-link" data-scroll-target="#nội-dung">Nội dung</a></li>
  <li><a href="#thực-hành" id="toc-thực-hành" class="nav-link" data-scroll-target="#thực-hành">Thực hành</a></li>
  <li><a href="#bài-tập" id="toc-bài-tập" class="nav-link" data-scroll-target="#bài-tập">Bài tập</a></li>
  <li><a href="#tài-liệu-tham-khảo" id="toc-tài-liệu-tham-khảo" class="nav-link" data-scroll-target="#tài-liệu-tham-khảo">Tài liệu tham khảo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m10-policy-bia-equity/index.html">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</a></li><li class="breadcrumb-item"><a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></h1>
<p class="subtitle lead">Biến các bảng kết quả thành một bản tóm tắt chính sách một trang, nói về bất định bằng cả con số và lời</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled" title="Vì sao bạn nên quan tâm?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vì sao bạn nên quan tâm?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Năm 2023, 62.9% kinh phí phòng, chẩn đoán và điều trị lao của Việt Nam đến từ nguồn bên ngoài, chủ yếu Quỹ Toàn cầu <span class="citation" data-cites="oh2026assessment">(<a href="../m00-r-foundations/index.html#ref-oh2026assessment" role="doc-biblioref">Oh và c.s. 2026</a>)</span>. Khi nguồn tài trợ thu hẹp, quyết định như mở rộng BPaLM, với giá thuốc khoảng 7.1 triệu VNĐ một đợt <span class="citation" data-cites="itpc2025gdf">(<a href="../m00-r-foundations/index.html#ref-itpc2025gdf" role="doc-biblioref">ITPC-EECA 2025</a>)</span>, sẽ phải được cân nhắc trong ngân sách trong nước. Người giữ ngân sách thường chỉ có vài phút và một trang giấy cho mỗi vấn đề. Nếu trang đó chép sai một con số, hoặc nói “chắc chắn tiết kiệm” khi mô hình chưa tính hết bất định, quyết định có thể sai. Bài này dạy cách gói ba bài trước vào một trang mà mọi con số đều sinh từ code, và nói rõ mình chắc đến đâu.</p>
</div>
</div>
<section id="mục-tiêu-học-tập" class="level2">
<h2 class="anchored" data-anchor-id="mục-tiêu-học-tập">Mục tiêu học tập</h2>
<p>Sau bài này, bạn có thể:</p>
<ol type="1">
<li>Sắp kết quả của phân tích chi phí-hiệu quả (CEA), tác động ngân sách (BIA), chi phí-hiệu quả theo phân phối (DCEA) và chi phí-hiệu quả mở rộng (ECEA) thành câu trả lời cho những câu hỏi mà người ra quyết định thực sự đặt ra.</li>
<li>Viết một bản tóm tắt chính sách (policy brief) một trang trong đó mọi con số được sinh từ code.</li>
<li>Diễn đạt bất định bằng con số đi kèm lời, nói rõ xác suất đó bao gồm những nguồn bất định nào, và phân biệt khoảng bất định của tham số với giả định cấu trúc.</li>
<li>Mô tả các bước của một quy trình đánh giá công nghệ y tế (HTA), vai trò của thảo luận có cân nhắc (deliberation), và những gì đã biết chắc về HTA ở Việt Nam.</li>
</ol>
</section>
<section id="ý-chính" class="level2">
<h2 class="anchored" data-anchor-id="ý-chính">Ý chính</h2>
<ul>
<li>Bắt đầu bằng câu trả lời, không bằng phương pháp. Một bảng kết quả chính, một hình, mọi ô đều tính từ code.</li>
<li>Người ra quyết định thường hỏi năm câu: có đáng tiền không, ngân sách đổi bao nhiêu, ai chi và khi nào, ai được lợi, gia đình người bệnh có được bảo vệ không.</li>
<li><strong>Giá trị ngưỡng</strong> (giá trung hòa ngân sách, ε*) thường có ích hơn một ước tính điểm: chúng cho biết điều gì phải xảy ra để kết luận đổi.</li>
<li>Luôn nói con số kèm lời: người đọc hiểu các cụm từ như “có khả năng” rất khác nhau, kể cả khi đã có hướng dẫn <span class="citation" data-cites="budescu2009improving">(<a href="../m00-r-foundations/index.html#ref-budescu2009improving" role="doc-biblioref">Budescu, Broomell, và Por 2009</a>)</span>.</li>
<li>Tách hai loại bất định: bất định trực tiếp về con số (khoảng, xác suất) và bất định gián tiếp về chất lượng bằng chứng và giả định <span class="citation" data-cites="vanderbles2019communicating">(<a href="../m00-r-foundations/index.html#ref-vanderbles2019communicating" role="doc-biblioref">Bles và c.s. 2019</a>)</span>.</li>
<li>Khoảng từ mô phỏng là <strong>khoảng bất định</strong>, không phải khoảng tin cậy.</li>
<li>Một xác suất chỉ có nghĩa trong phạm vi những gì được rút mẫu. “Gần như chắc chắn tiết kiệm” khi chỉ biến thiên giá và tỷ lệ áp dụng không phải là chắc chắn thật; hãy ghi rõ phạm vi, và đưa giả định cấu trúc vào kịch bản.</li>
<li>Đánh giá công nghệ y tế (HTA) là quy trình đa ngành, nhiều bên cùng tham gia; con số từ mô hình chỉ là một đầu vào cho thảo luận có cân nhắc với các bên liên quan <span class="citation" data-cites="oortwijn2022designing">(<a href="../m00-r-foundations/index.html#ref-oortwijn2022designing" role="doc-biblioref">Oortwijn và c.s. 2022</a>)</span>.</li>
</ul>
</section>
<section id="nội-dung" class="level2">
<h2 class="anchored" data-anchor-id="nội-dung">Nội dung</h2>
<section id="người-ra-quyết-định-hỏi-gì" class="level3">
<h3 class="anchored" data-anchor-id="người-ra-quyết-định-hỏi-gì">Người ra quyết định hỏi gì</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Câu hỏi</th>
<th>Phương pháp</th>
<th>Bài</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Có đáng tiền không?</td>
<td>CEA: tỷ số chi phí-hiệu quả gia tăng (ICER), lợi ích ròng quy ra tiền (NMB), lấn át, đường biên hiệu quả</td>
<td>M02 Bài 5</td>
</tr>
<tr class="even">
<td>Ngân sách đổi bao nhiêu, năm nào?</td>
<td>BIA</td>
<td>Bài 1</td>
</tr>
<tr class="odd">
<td>Ai chi thêm, ai tiết kiệm?</td>
<td>BIA theo đơn vị chi trả</td>
<td>Bài 1</td>
</tr>
<tr class="even">
<td>Ai được lợi, có đánh đổi công bằng không?</td>
<td>DCEA, mặt phẳng tác động công bằng</td>
<td>Bài 2</td>
</tr>
<tr class="odd">
<td>Gia đình người bệnh có được bảo vệ không?</td>
<td>ECEA, chi phí thảm họa</td>
<td>Bài 3</td>
</tr>
<tr class="even">
<td>Chắc chắn đến đâu, điều gì làm đổi kết luận?</td>
<td>PSA, phân tích kịch bản, giá trị ngưỡng</td>
<td>M03, Bài 1, Bài 4</td>
</tr>
</tbody>
</table>
<p>Mỗi câu có một con số chính. Bản tóm tắt không cần thêm gì ngoài các con số đó, mức chắc chắn của chúng, và những giả định quyết định kết luận.</p>
</section>
<section id="bản-tóm-tắt-chính-sách-một-trang" class="level3">
<h3 class="anchored" data-anchor-id="bản-tóm-tắt-chính-sách-một-trang">Bản tóm tắt chính sách một trang</h3>
<p>Một cấu trúc dùng được cho hầu hết các bản tóm tắt:</p>
<ol type="1">
<li><strong>Tiêu đề là kết luận</strong>, không phải chủ đề: “Mở rộng BPaLM tiết kiệm ngân sách”, không phải “Đánh giá kinh tế BPaLM”.</li>
<li><strong>Ba thông điệp chính</strong>, mỗi thông điệp một câu, có con số.</li>
<li><strong>Một bảng kết quả chính</strong> trả lời các câu hỏi ở trên, có cột mức chắc chắn.</li>
<li><strong>Một hình</strong>, thường là ngân sách theo năm có khoảng bất định.</li>
<li><strong>Điều gì sẽ làm đổi kết luận</strong>: các giá trị ngưỡng và giả định cấu trúc quan trọng nhất.</li>
<li><strong>Công bằng và bảo vệ tài chính</strong>: ai được lợi, ai vẫn chưa được bảo vệ.</li>
<li><strong>Giới hạn và dữ liệu cần có</strong> để quyết định chắc hơn.</li>
<li><strong>Phương pháp và nguồn</strong> trong một đoạn ngắn; chi tiết để ở phụ lục báo cáo theo bảng kiểm CHEERS 2022 <span class="citation" data-cites="husereau2022consolidated">(<a href="../m00-r-foundations/index.html#ref-husereau2022consolidated" role="doc-biblioref">Husereau và c.s. 2022</a>)</span>.</li>
</ol>
<p>Với BIA, nhóm công tác ISPOR khuyên báo cáo đầu vào và phép tính đủ chi tiết để người khác làm lại được, và trình bày kết quả theo dạng mà người ra quyết định cần <span class="citation" data-cites="sullivan2014budget">(<a href="../m00-r-foundations/index.html#ref-sullivan2014budget" role="doc-biblioref">Sullivan và c.s. 2014</a>)</span>. Khi bản tóm tắt được viết bằng Quarto như bài này, mọi con số được tính lại mỗi lần biên dịch, nên không có số nào bị chép sai.</p>
</section>
<section id="nói-về-bất-định" class="level3">
<h3 class="anchored" data-anchor-id="nói-về-bất-định">Nói về bất định</h3>
<p>Có ba lớp bất định cần nói riêng. <strong>Tham số</strong>: giá thuốc, tỷ lệ biến cố bất lợi, tỷ lệ đủ điều kiện, tỷ lệ áp dụng, số người bệnh; trình bày bằng khoảng bất định 95% và xác suất từ phân tích độ nhạy xác suất (probabilistic sensitivity analysis, PSA; M03). <strong>Cấu trúc</strong>: các giả định như cách áp RR cho tử vong trong điều trị (M02 Bài 5), có điều trị lại hay không, dùng trung vị hay trung bình cho chi phí nằm viện, hay cơ cấu phác đồ hiện tại; trình bày bằng kịch bản, không gộp vào khoảng. <strong>Chất lượng bằng chứng</strong>: ví dụ hiệu quả của hỗ trợ tiền mặt lấy từ nghiên cứu lao nhạy thuốc, hay hai nghiên cứu trái ngược nhau về chi phí người bệnh (Bài 3); nói thẳng bằng lời. Mỗi xác suất phải đi kèm phạm vi.</p>
<p>Với xác suất, nói con số trước, lời sau, và có thể thêm tần suất tự nhiên (“bao nhiêu trong 10 lần mô phỏng”). Budescu và cộng sự cho thấy người đọc báo cáo IPCC gán cho các cụm từ xác suất những giá trị lệch đáng kể so với hướng dẫn, kể cả khi có hướng dẫn trong tay, và đề xuất một cách trình bày khác hiệu quả hơn <span class="citation" data-cites="budescu2009improving">(<a href="../m00-r-foundations/index.html#ref-budescu2009improving" role="doc-biblioref">Budescu, Broomell, và Por 2009</a>)</span>. Van der Bles và cộng sự tổng hợp các cách diễn đạt bất định trực tiếp và gián tiếp; có một số bằng chứng rằng nói rõ bất định không nhất thiết tác động xấu đến người nghe, dù tác động khác nhau theo người nghe và cách trình bày <span class="citation" data-cites="vanderbles2019communicating">(<a href="../m00-r-foundations/index.html#ref-vanderbles2019communicating" role="doc-biblioref">Bles và c.s. 2019</a>)</span>. Hàm <code>prob_words()</code> dùng các mốc của thang khả năng (likelihood scale) trong báo cáo IPCC mà Budescu và cộng sự đã thử nghiệm, gộp thành bảy cụm không chồng lấn. Vì người đọc hiểu các cụm từ này rất khác nhau, khóa học luôn in con số kèm theo lời.</p>
</section>
<section id="quy-trình-hta" class="level3">
<h3 class="anchored" data-anchor-id="quy-trình-hta">Quy trình HTA</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>flowchart LR</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  A["Chọn chủ đề&lt;br/&gt;ưu tiên"] --&gt; B["Xác định phạm vi&lt;br/&gt;quần thể, so sánh, quan điểm"]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  B --&gt; C["Đánh giá (assessment)&lt;br/&gt;hiệu quả, an toàn, CEA, BIA,&lt;br/&gt;công bằng, khả thi"]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  C --&gt; D["Thẩm định (appraisal)&lt;br/&gt;thảo luận có cân nhắc"]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  D --&gt; E["Quyết định&lt;br/&gt;và khuyến nghị"]</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  E --&gt; F["Triển khai,&lt;br/&gt;theo dõi"]</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  F -.-&gt;|bằng chứng mới| A</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  A["Chọn chủ đề&lt;br/&gt;ưu tiên"] --&gt; B["Xác định phạm vi&lt;br/&gt;quần thể, so sánh, quan điểm"]
  B --&gt; C["Đánh giá (assessment)&lt;br/&gt;hiệu quả, an toàn, CEA, BIA,&lt;br/&gt;công bằng, khả thi"]
  C --&gt; D["Thẩm định (appraisal)&lt;br/&gt;thảo luận có cân nhắc"]
  D --&gt; E["Quyết định&lt;br/&gt;và khuyến nghị"]
  E --&gt; F["Triển khai,&lt;br/&gt;theo dõi"]
  F -.-&gt;|bằng chứng mới| A
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Định nghĩa do INAHTA và HTAi cùng xây dựng mô tả HTA là một quy trình đa ngành, dùng phương pháp minh bạch để xác định giá trị của một công nghệ y tế ở các thời điểm khác nhau trong vòng đời của nó <span class="citation" data-cites="orourke2020new">(<a href="../m00-r-foundations/index.html#ref-orourke2020new" role="doc-biblioref">O’Rourke, Oortwijn, và Schuller 2020</a>)</span>. Mô hình kinh tế của khóa học nằm ở bước đánh giá. Bước thẩm định là nơi các con số gặp những cân nhắc khác: công bằng, tính khả thi, tiếng nói của người bệnh. Nhóm công tác HTAi/ISPOR đưa ra hướng dẫn và bảng kiểm để thiết kế quá trình thảo luận có cân nhắc qua các giai đoạn của HTA <span class="citation" data-cites="oortwijn2022designing">(<a href="../m00-r-foundations/index.html#ref-oortwijn2022designing" role="doc-biblioref">Oortwijn và c.s. 2022</a>)</span>. Khung tham chiếu iDSI gợi ý các nguyên tắc phương pháp cho đánh giá kinh tế ở nước thu nhập thấp và trung bình, như một công cụ hỗ trợ tư duy chứ không phải khuôn cứng <span class="citation" data-cites="wilkinson2016international">(<a href="../m00-r-foundations/index.html#ref-wilkinson2016international" role="doc-biblioref">Wilkinson và c.s. 2016</a>)</span>.</p>
<p><strong>Việt Nam.</strong> Theo một nghiên cứu định tính dựa trên phỏng vấn năm 2017–2018, Việt Nam đưa HTA vào quá trình ra quyết định về danh mục quyền lợi bảo hiểm y tế từ năm 2014; các rào cản gồm thiếu nhân lực, hạ tầng dữ liệu hạn chế, chưa có hướng dẫn phương pháp, sự chú ý vào tiết kiệm ngân sách trước mắt và sự phản đối của công chúng <span class="citation" data-cites="lee2021health">(<a href="../m00-r-foundations/index.html#ref-lee2021health" role="doc-biblioref">Lee và c.s. 2021</a>)</span>. Với lao, câu hỏi ngân sách càng gấp vì phần lớn kinh phí còn đến từ tài trợ, và các nước đang thu hẹp điều kiện nhận Quỹ Toàn cầu phải chuyển dần các khoản này sang quỹ BHYT và ngân sách trong nước <span class="citation" data-cites="oh2026assessment">(<a href="../m00-r-foundations/index.html#ref-oh2026assessment" role="doc-biblioref">Oh và c.s. 2026</a>)</span>. Một ví dụ về bằng chứng dẫn đến chính sách là khảo sát chi phí người bệnh lao năm 2016 (Bài 3) <span class="citation" data-cites="hoa2019national">(<a href="../m00-r-foundations/index.html#ref-hoa2019national" role="doc-biblioref">Hoa và Nhung 2019</a>)</span>. Chi tiết về các văn bản và cơ quan HTA hiện hành chưa được kiểm chứng trong khóa học; xem M09 Bài 5 về bối cảnh ra quyết định.</p>
</section>
</section>
<section id="thực-hành" class="level2">
<h2 class="anchored" data-anchor-id="thực-hành">Thực hành</h2>
<p>Nạp hàm, tham số và các giá trị chung. Kiểm tra: không có lỗi.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vietnamese text in tables and figures needs a UTF-8 locale (Rscript may start in "C")</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">isTRUE</span>(<span class="fu">l10n_info</span>()[[<span class="st">"UTF-8"</span>]])) <span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_CTYPE"</span>, <span class="st">"en_US.UTF-8"</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/helpers.R"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/vn_data.R"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../m02-cohort-markov/code/model.R"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"code/model.R"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>p02 <span class="ot">&lt;-</span> <span class="fu">m02_params</span>(<span class="st">"../m02-cohort-markov/params/mdrtb.csv"</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>pb <span class="ot">&lt;-</span> <span class="fu">read_params</span>(<span class="st">"params/bia.csv"</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>pe <span class="ot">&lt;-</span> <span class="fu">read_params</span>(<span class="st">"params/equity.csv"</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>payer <span class="ot">&lt;-</span> <span class="fu">read_payer</span>(<span class="st">"params/payer.csv"</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>ctx <span class="ot">&lt;-</span> <span class="fu">vn_context</span>()</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>ptab_bia <span class="ot">&lt;-</span> <span class="fu">attr</span>(pb, <span class="st">"table"</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>n_patients <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">current_counts</span>(pb))</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>mix <span class="ot">&lt;-</span> <span class="fu">current_mix</span>(pb)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> ctx<span class="sc">$</span>wtp_low</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise settings (analysis choices, not data)</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>saving_target <span class="ot">&lt;-</span> <span class="fl">30e9</span>    <span class="co"># Exercise 1: a 5-year saving target (VND)</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>se_target <span class="ot">&lt;-</span> <span class="fl">0.005</span>       <span class="co"># Exercise 3: target Monte Carlo standard error of a probability</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>bn <span class="ot">&lt;-</span> <span class="cf">function</span>(x) x <span class="sc">/</span> <span class="fl">1e9</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Tính lại các con số chính của M02 và Bài 1–3 bằng chính các hàm đã dùng. Không chép số từ bài trước: nếu một tham số đổi, bản tóm tắt tự cập nhật. Kiểm tra: các điều kiện mà lời văn dựa vào (BPaLM chiếm ưu thế so với cả phác đồ ngắn lẫn phác đồ dài hạn, tức rẻ hơn và thêm năm sống điều chỉnh theo chất lượng, QALY; tiết kiệm trong 5 năm; tỷ lệ hộ gặp chi phí thảm họa giảm) đều đúng (<code>stopifnot</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recompute the headline numbers of Lessons 1-3 from the same functions (no copy-paste)</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>cea <span class="ot">&lt;-</span> <span class="fu">run_cea</span>(p02)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>cmp_short <span class="ot">&lt;-</span> <span class="fu">compare_regimens</span>(cea, <span class="at">new =</span> <span class="st">"bpalm"</span>, <span class="at">ref =</span> <span class="st">"short"</span>)   <span class="co"># course threshold from kb/_shared</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>cmp_long <span class="ot">&lt;-</span> <span class="fu">compare_regimens</span>(cea, <span class="at">new =</span> <span class="st">"bpalm"</span>, <span class="at">ref =</span> <span class="st">"long"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">bia_resources</span>(p02)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>prof <span class="ot">&lt;-</span> <span class="fu">bia_profiles</span>(res, p02, pb)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>bia <span class="ot">&lt;-</span> <span class="fu">run_bia</span>(pb, prof)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>bia_tab <span class="ot">&lt;-</span> <span class="fu">bia_by_year</span>(bia, pb<span class="sc">$</span>start_year)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>payer_y1 <span class="ot">&lt;-</span> <span class="fu">bia_by_payer</span>(bia, payer)[<span class="dv">1</span>, ]</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>pp <span class="ot">&lt;-</span> <span class="fu">patient_outcomes</span>(p02, pe, mix)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>h0 <span class="ot">&lt;-</span> <span class="fu">quintile_vector</span>(pe, <span class="st">"qale_q"</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>dist <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">c</span>(<span class="at">bpalm =</span> <span class="st">"bpalm"</span>, <span class="at">target =</span> <span class="st">"bpalm_target"</span>, <span class="at">all =</span> <span class="st">"bpalm_all"</span>),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>               <span class="cf">function</span>(s) <span class="fu">dcea_summary</span>(<span class="fu">dcea_distribution</span>(pp, pe, n_patients, s, k), h0, ctx<span class="sc">$</span>population, <span class="dv">0</span>))</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">income_grid</span>(<span class="fu">log</span>(<span class="fu">median_income_vnd</span>(pe)), <span class="fu">fit_income_sigma</span>(<span class="fu">quintile_vector</span>(pe, <span class="st">"inc_share_q"</span>)))</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>ecea_b <span class="ot">&lt;-</span> <span class="fu">ecea_table</span>(pp, pe, n_patients, <span class="st">"bpalm"</span>, grid, <span class="at">ref =</span> <span class="st">"now"</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>w_case <span class="ot">&lt;-</span> <span class="fu">quintile_vector</span>(pe, <span class="st">"share_case_q"</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Threshold value for the brief: BPaLM drug price at which the 5-year impact is zero (Lesson 1)</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>price_neutral <span class="ot">&lt;-</span> <span class="fu">budget_neutral_price</span>(pb, p02, res)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>key <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">d_cost =</span> cmp_short<span class="sc">$</span>d_cost, <span class="at">d_qaly =</span> cmp_short<span class="sc">$</span>d_qaly, <span class="at">status_short =</span> cmp_short<span class="sc">$</span>status,</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">status_long =</span> cmp_long<span class="sc">$</span>status,</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">bia_5y =</span> <span class="fu">sum</span>(bia_tab<span class="sc">$</span>impact), <span class="at">bia_y1 =</span> bia_tab<span class="sc">$</span>impact[<span class="dv">1</span>],</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">ntp_y1 =</span> payer_y1[[<span class="st">"ntp"</span>]], <span class="at">shi_y1 =</span> payer_y1[[<span class="st">"shi"</span>]],</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">deaths_averted =</span> <span class="fu">sum</span>(ecea_b<span class="sc">$</span>deaths_averted), <span class="at">nhb =</span> dist<span class="sc">$</span>bpalm<span class="sc">$</span>total_nhb,</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">che_now =</span> <span class="fu">sum</span>(w_case <span class="sc">*</span> ecea_b<span class="sc">$</span>che_ref), <span class="at">che_bpalm =</span> <span class="fu">sum</span>(w_case <span class="sc">*</span> ecea_b<span class="sc">$</span>che_new),</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">price_neutral =</span> price_neutral, <span class="at">poor_share =</span> <span class="fu">sum</span>(w_case[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>])</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(key)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 14
 $ d_cost        : num -6677215
 $ d_qaly        : num 0.479
 $ status_short  : chr "dominant"
 $ status_long   : chr "dominant"
 $ bia_5y        : num -4.31e+10
 $ bia_y1        : num -1.71e+09
 $ ntp_y1        : num 3.89e+08
 $ shi_y1        : num -2.1e+09
 $ deaths_averted: num 90.8
 $ nhb           : num 1896
 $ che_now       : num 0.912
 $ che_bpalm     : num 0.865
 $ price_neutral : num 2645481
 $ poor_share    : num 0.54</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Claims that the text below relies on</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(key<span class="sc">$</span>status_short <span class="sc">==</span> <span class="st">"dominant"</span>, key<span class="sc">$</span>status_long <span class="sc">==</span> <span class="st">"dominant"</span>, key<span class="sc">$</span>bia_5y <span class="sc">&lt;</span> <span class="dv">0</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>          key<span class="sc">$</span>che_bpalm <span class="sc">&lt;</span> key<span class="sc">$</span>che_now, <span class="sc">!</span><span class="fu">is.na</span>(key<span class="sc">$</span>price_neutral), key<span class="sc">$</span>deaths_averted <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The brief says the poorest households stay above the threshold even with BPaLM</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(ecea_b[<span class="st">"Q1"</span>, <span class="st">"che_new"</span>] <span class="sc">&gt;</span> <span class="fl">0.99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Giả định cấu trúc không có phân phối, nên ta chạy lại BIA dưới từng giả định thay vì gộp vào một khoảng: cơ cấu điều trị hiện tại, số người được phát hiện, chi phí nằm viện theo trung bình, hai cách áp RR cho tử vong của BPaLM và việc bỏ vòng điều trị lại trong M02. Kiểm tra: dòng “phân tích cơ sở” khớp với kết quả ở trên.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Structural assumptions get scenarios, not intervals: the same BIA under other choices.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Each scenario changes the M02 or BIA parameters and recomputes resource use and prices.</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>scenario_impact <span class="ot">&lt;-</span> <span class="cf">function</span>(p02_k, pb_k) {</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  res_k <span class="ot">&lt;-</span> <span class="fu">bia_resources</span>(p02_k)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  tab_k <span class="ot">&lt;-</span> <span class="fu">bia_by_year</span>(<span class="fu">run_bia</span>(pb_k, <span class="fu">bia_profiles</span>(res_k, p02_k, pb_k)), pb_k<span class="sc">$</span>start_year)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">y1 =</span> tab_k<span class="sc">$</span>impact[<span class="dv">1</span>], <span class="at">total =</span> <span class="fu">sum</span>(tab_k<span class="sc">$</span>impact), <span class="at">level_y1 =</span> tab_k<span class="sc">$</span>current[<span class="dv">1</span>])</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>n0 <span class="ot">&lt;-</span> <span class="fu">current_counts</span>(pb)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>set_counts <span class="ot">&lt;-</span> <span class="cf">function</span>(pb_k, n) {</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  pb_k<span class="sc">$</span>who_tx_18m_2024 <span class="ot">&lt;-</span> n[[<span class="st">"long"</span>]]; pb_k<span class="sc">$</span>who_tx_9m_2024 <span class="ot">&lt;-</span> n[[<span class="st">"short"</span>]]; pb_k<span class="sc">$</span>who_tx_6m_2024 <span class="ot">&lt;-</span> n[[<span class="st">"bpalm"</span>]]</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  pb_k</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>other0 <span class="ot">&lt;-</span> n0[<span class="fu">c</span>(<span class="st">"long"</span>, <span class="st">"short"</span>)] <span class="sc">/</span> <span class="fu">sum</span>(n0[<span class="fu">c</span>(<span class="st">"long"</span>, <span class="st">"short"</span>)])</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>no_retx <span class="ot">&lt;-</span> p02</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>no_retx<span class="sc">$</span>retx_rate_failed <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>no_retx<span class="sc">$</span>retx_rate_ltfu <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>scen <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Phân tích cơ sở"</span> <span class="ot">=</span> <span class="fu">scenario_impact</span>(p02, pb),</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Chưa ai dùng BPaLM (cơ cấu trước 2024)"</span> <span class="ot">=</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scenario_impact</span>(p02, <span class="fu">set_counts</span>(pb, <span class="fu">c</span>(n0[<span class="fu">c</span>(<span class="st">"long"</span>, <span class="st">"short"</span>)] <span class="sc">+</span> n0[[<span class="st">"bpalm"</span>]] <span class="sc">*</span> other0, <span class="at">bpalm =</span> <span class="dv">0</span>))),</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Mọi người không dùng BPaLM đều dùng phác đồ ngắn"</span> <span class="ot">=</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scenario_impact</span>(p02, <span class="fu">set_counts</span>(pb, <span class="fu">c</span>(<span class="at">long =</span> <span class="dv">0</span>, <span class="at">short =</span> <span class="fu">sum</span>(n0[<span class="fu">c</span>(<span class="st">"long"</span>, <span class="st">"short"</span>)]), <span class="at">bpalm =</span> n0[[<span class="st">"bpalm"</span>]]))),</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Phát hiện và điều trị đủ số ca WHO ước tính"</span> <span class="ot">=</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scenario_impact</span>(p02, <span class="fu">set_counts</span>(pb, n0 <span class="sc">*</span> p02<span class="sc">$</span>who_rr_incidence <span class="sc">/</span> <span class="fu">sum</span>(n0))),</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Chi phí nằm viện = trung bình thay vì trung vị"</span> <span class="ot">=</span></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scenario_impact</span>(p02, <span class="fu">replace</span>(pb, <span class="st">"hosp_mean_ratio"</span>, ptab_bia<span class="sc">$</span>high[ptab_bia<span class="sc">$</span>name <span class="sc">==</span> <span class="st">"hosp_mean_ratio"</span>])),</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>  <span class="st">"RR cũng áp cho tử vong khi điều trị BPaLM (mã 1)"</span> <span class="ot">=</span> <span class="fu">scenario_impact</span>(<span class="fu">replace</span>(p02, <span class="st">"bpalm_death_rule"</span>, <span class="dv">1</span>), pb),</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Tỷ lệ tử vong tích lũy của BPaLM bằng phác đồ ngắn (mã 2)"</span> <span class="ot">=</span> <span class="fu">scenario_impact</span>(<span class="fu">replace</span>(p02, <span class="st">"bpalm_death_rule"</span>, <span class="dv">2</span>), pb),</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Không ai được điều trị lại"</span> <span class="ot">=</span> <span class="fu">scenario_impact</span>(no_retx, pb)</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>scen_tab <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, scen)</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(<span class="at">scenario =</span> <span class="fu">rownames</span>(scen_tab), <span class="at">y1 =</span> <span class="fu">fmt_num</span>(<span class="fu">bn</span>(scen_tab[, <span class="st">"y1"</span>]), <span class="dv">1</span>),</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>                        <span class="at">total =</span> <span class="fu">fmt_num</span>(<span class="fu">bn</span>(scen_tab[, <span class="st">"total"</span>]), <span class="dv">1</span>)),</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Kịch bản"</span>, <span class="st">"Tác động năm đầu (tỷ VNĐ)"</span>, <span class="st">"Tác động 5 năm (tỷ VNĐ)"</span>),</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>             <span class="at">align =</span> <span class="st">"lrr"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 53%">
<col style="width: 24%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Kịch bản</th>
<th style="text-align: right;">Tác động năm đầu (tỷ VNĐ)</th>
<th style="text-align: right;">Tác động 5 năm (tỷ VNĐ)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Phân tích cơ sở</td>
<td style="text-align: right;">-1.7</td>
<td style="text-align: right;">-43.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chưa ai dùng BPaLM (cơ cấu trước 2024)</td>
<td style="text-align: right;">-4.8</td>
<td style="text-align: right;">-75.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mọi người không dùng BPaLM đều dùng phác đồ ngắn</td>
<td style="text-align: right;">-1.8</td>
<td style="text-align: right;">-31.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Phát hiện và điều trị đủ số ca WHO ước tính</td>
<td style="text-align: right;">-5.3</td>
<td style="text-align: right;">-132.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chi phí nằm viện = trung bình thay vì trung vị</td>
<td style="text-align: right;">-3.6</td>
<td style="text-align: right;">-67.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">RR cũng áp cho tử vong khi điều trị BPaLM (mã 1)</td>
<td style="text-align: right;">-1.7</td>
<td style="text-align: right;">-42.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tỷ lệ tử vong tích lũy của BPaLM bằng phác đồ ngắn (mã 2)</td>
<td style="text-align: right;">-1.7</td>
<td style="text-align: right;">-43.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Không ai được điều trị lại</td>
<td style="text-align: right;">-1.7</td>
<td style="text-align: right;">-41.7</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Does the sign of the 5-year impact change in any scenario? (used in the text)</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>saving_in_all <span class="ot">&lt;-</span> <span class="fu">all</span>(scen_tab[, <span class="st">"total"</span>] <span class="sc">&lt;</span> <span class="dv">0</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(scen_tab[<span class="dv">1</span>, <span class="st">"total"</span>] <span class="sc">-</span> key<span class="sc">$</span>bia_5y) <span class="sc">&lt;</span> <span class="fl">1e-3</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Claims in the brief (rows 2-4): saving is larger with no BPaLM yet and with wider case finding,</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># smaller if the others are on the short regimen; wider case finding also raises the budget level</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(scen_tab[<span class="dv">2</span>, <span class="st">"total"</span>] <span class="sc">&lt;</span> scen_tab[<span class="dv">1</span>, <span class="st">"total"</span>], scen_tab[<span class="dv">4</span>, <span class="st">"total"</span>] <span class="sc">&lt;</span> scen_tab[<span class="dv">1</span>, <span class="st">"total"</span>],</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>          scen_tab[<span class="dv">3</span>, <span class="st">"total"</span>] <span class="sc">&gt;</span> scen_tab[<span class="dv">1</span>, <span class="st">"total"</span>], scen_tab[<span class="dv">4</span>, <span class="st">"level_y1"</span>] <span class="sc">&gt;</span> scen_tab[<span class="dv">1</span>, <span class="st">"level_y1"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Chạy BIA xác suất: rút 1,000 bộ giá trị cho giá thuốc ba phác đồ và chi phí theo dõi (qua hệ số nhân), tỷ lệ biến cố bất lợi nặng của hai nhóm thuốc, tỷ lệ đủ điều kiện, tốc độ tăng người bệnh và tỷ lệ áp dụng. Phân phối lấy từ cột <code>dist</code> của bảng tham số (đều, hoặc log-chuẩn tách đôi với khoảng thấp-cao làm phân vị 2.5% và 97.5%), riêng tỷ lệ biến cố bất lợi dùng phân phối beta. <strong>Không</strong> rút mẫu: kết cục lâm sàng, thời gian điều trị và quy tắc tử vong của BPaLM (M02 giữ cố định), cơ cấu phác đồ năm 2024 (số liệu báo cáo), và chi phí nằm viện (trung vị hay trung bình là lựa chọn cấu trúc). Kiểm tra: các phân vị của hàm rút mẫu khớp khoảng thấp-cao đã cho, và mọi lần chạy cho kết quả hữu hạn.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probabilistic BIA: prices (as multipliers), adverse-event rates, eligibility, growth and</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># uptake are drawn together. Distributions come from the `dist` column of the parameter</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># table (uniform, split lognormal) or are beta (adverse events). Left out on purpose:</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># resource use from M02 (clinical outcomes, durations, the BPaLM death rule) is held fixed</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># (M03 shows how to propagate it); the 2024 regimen mix is data; and the hospital-cost</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># convention (median or mean) is a structural choice, so they appear as scenarios above.</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>n_sim <span class="ot">&lt;-</span> pb<span class="sc">$</span>n_psa</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>H <span class="ot">&lt;-</span> pb<span class="sc">$</span>horizon_years</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>param_row <span class="ot">&lt;-</span> <span class="cf">function</span>(tab_k, nm) tab_k[tab_k<span class="sc">$</span>name <span class="sc">==</span> nm, ]</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Independent check of the draw function: its 2.5%, 50%, 97.5% quantiles are low, value, high</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>q_chk <span class="ot">&lt;-</span> <span class="fu">quantile</span>(<span class="fu">draw_split_lognormal</span>(<span class="fl">1e5</span>, <span class="dv">1</span>, <span class="fl">0.8</span>, <span class="fl">1.5</span>), <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>))</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(q_chk <span class="sc">/</span> <span class="fu">c</span>(<span class="fl">0.8</span>, <span class="dv">1</span>, <span class="fl">1.5</span>) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">&lt;</span> <span class="fl">0.02</span>))</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>pb_draw <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"mult_drug_bpalm"</span>, <span class="st">"mult_drug_short"</span>, <span class="st">"mult_drug_long"</span>, <span class="st">"mult_monitor"</span>,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>             <span class="st">"share_eligible"</span>, <span class="st">"growth_rate"</span>)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>draws <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">sapply</span>(pb_draw, <span class="cf">function</span>(nm) <span class="fu">draw_param</span>(n_sim, <span class="fu">param_row</span>(ptab_bia, nm))))</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>draws<span class="sc">$</span>ae_bpalm <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(n_sim, pb<span class="sc">$</span>ae_n_arm <span class="sc">*</span> p02<span class="sc">$</span>ae_bpalm, pb<span class="sc">$</span>ae_n_arm <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p02<span class="sc">$</span>ae_bpalm))</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>draws<span class="sc">$</span>ae_soc <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(n_sim, pb<span class="sc">$</span>ae_n_arm <span class="sc">*</span> p02<span class="sc">$</span>ae_soc, pb<span class="sc">$</span>ae_n_arm <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p02<span class="sc">$</span>ae_soc))</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>draws<span class="sc">$</span>uptake_u <span class="ot">&lt;-</span> <span class="fu">runif</span>(n_sim)   <span class="co"># one position between low and high uptake, shared by all years</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>impact_year <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, n_sim, H, <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="cn">NULL</span>, bia_tab<span class="sc">$</span>year))</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_len</span>(n_sim)) {</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  p_i <span class="ot">&lt;-</span> p02</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>  p_i<span class="sc">$</span>ae_bpalm <span class="ot">&lt;-</span> draws<span class="sc">$</span>ae_bpalm[i]</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>  p_i<span class="sc">$</span>ae_soc <span class="ot">&lt;-</span> draws<span class="sc">$</span>ae_soc[i]</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>  pb_i <span class="ot">&lt;-</span> pb</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (nm <span class="cf">in</span> pb_draw) pb_i[[nm]] <span class="ot">&lt;-</span> draws[i, nm]</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (y <span class="cf">in</span> <span class="fu">seq_len</span>(H)) {</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>    r <span class="ot">&lt;-</span> <span class="fu">param_row</span>(ptab_bia, <span class="fu">paste0</span>(<span class="st">"uptake_y"</span>, y))</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>    pb_i[[<span class="fu">paste0</span>(<span class="st">"uptake_y"</span>, y)]] <span class="ot">&lt;-</span> r<span class="sc">$</span>low <span class="sc">+</span> draws<span class="sc">$</span>uptake_u[i] <span class="sc">*</span> (r<span class="sc">$</span>high <span class="sc">-</span> r<span class="sc">$</span>low)</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>  impact_year[i, ] <span class="ot">&lt;-</span> <span class="fu">bia_by_year</span>(<span class="fu">run_bia</span>(pb_i, <span class="fu">bia_profiles</span>(res, p_i, pb_i)), pb<span class="sc">$</span>start_year)<span class="sc">$</span>impact</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>total_sim <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(impact_year)</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">is.finite</span>(total_sim)))</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>p_saving <span class="ot">&lt;-</span> <span class="fu">mean</span>(total_sim <span class="sc">&lt;</span> <span class="dv">0</span>)</span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>p_saving_y1 <span class="ot">&lt;-</span> <span class="fu">mean</span>(impact_year[, <span class="dv">1</span>] <span class="sc">&lt;</span> <span class="dv">0</span>)</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a>ci_5y <span class="ot">&lt;-</span> <span class="fu">quantile</span>(total_sim, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>))</span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">bn</span>(ci_5y), <span class="at">p_saving =</span> p_saving, <span class="at">p_saving_y1 =</span> p_saving_y1), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       2.5%         50%       97.5%    p_saving p_saving_y1 
    -76.819     -37.187     -12.802       1.000       0.957 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">prob_words</span>(p_saving), <span class="fu">prob_words</span>(p_saving_y1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "gần như chắc chắn" "rất có khả năng"  </code></pre>
</div>
</div>
<p>Tác động 5 năm có trung vị -37 tỷ VNĐ, khoảng bất định 95% từ -77 đến -13 tỷ VNĐ. Xác suất tiết kiệm trong 5 năm là 100.0% (“gần như chắc chắn”), còn xác suất tiết kiệm ngay năm đầu là 95.7% (“rất có khả năng”): khoảng 4 trong 100 lần mô phỏng, năm đầu tốn thêm tiền. Xác suất 100% từ 1,000 lần rút nghĩa là không lần nào cho kết quả ngược lại, không phải chắc chắn tuyệt đối. Hai xác suất này chỉ nói về các đầu vào đã rút mẫu ở trên; chúng không bao gồm bất định lâm sàng của M02 hay các kịch bản cấu trúc, nên đừng đọc chúng như xác suất cho toàn bộ mô hình.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>band <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">year =</span> bia_tab<span class="sc">$</span>year,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">lo =</span> <span class="fu">apply</span>(impact_year, <span class="dv">2</span>, quantile, <span class="fl">0.025</span>) <span class="sc">/</span> <span class="fl">1e9</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">mid =</span> <span class="fu">apply</span>(impact_year, <span class="dv">2</span>, quantile, <span class="fl">0.5</span>) <span class="sc">/</span> <span class="fl">1e9</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">hi =</span> <span class="fu">apply</span>(impact_year, <span class="dv">2</span>, quantile, <span class="fl">0.975</span>) <span class="sc">/</span> <span class="fl">1e9</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">base =</span> <span class="fu">bn</span>(bia_tab<span class="sc">$</span>impact))</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>fig_psa <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(band, <span class="fu">aes</span>(year)) <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), <span class="at">fill =</span> pal_course[<span class="dv">5</span>], <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> mid), <span class="at">colour =</span> pal_course[<span class="dv">1</span>], <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> base), <span class="at">colour =</span> pal_course[<span class="dv">2</span>], <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">colour =</span> <span class="st">"grey30"</span>) <span class="sc">+</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Tác động ngân sách (tỷ VNĐ)"</span>,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Tác động ngân sách hằng năm và khoảng bất định 95%"</span>,</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">"Đường: trung vị của "</span>, <span class="fu">fmt_num</span>(n_sim), <span class="st">" lần rút mẫu; điểm: phân tích cơ sở"</span>)) <span class="sc">+</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_psa, <span class="st">"l04-bia-uncertainty.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l04-bia-uncertainty.png" class="img-fluid figure-img"></p>
<figcaption>Tác động ngân sách hằng năm và khoảng bất định 95%</figcaption>
</figure>
</div>
<p>Thang lời (IPCC, gộp bảy cụm), luôn đi kèm con số và tần suất tự nhiên. Kiểm tra: mỗi xác suất ứng với đúng một cụm từ.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Words and numbers together: the same probability, phrased for a reader</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>probs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.005</span>, <span class="fl">0.05</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.8</span>, <span class="fl">0.95</span>, <span class="fl">0.995</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">data.frame</span>(<span class="at">p =</span> <span class="fu">fmt_pct</span>(probs, <span class="dv">1</span>), <span class="at">words =</span> <span class="fu">prob_words</span>(probs),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">freq =</span> <span class="fu">paste0</span>(<span class="fu">fmt_num</span>(probs <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>), <span class="st">" trên 100"</span>)),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Xác suất"</span>, <span class="st">"Cách nói (luôn kèm con số)"</span>, <span class="st">"Tần suất tự nhiên"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Xác suất</th>
<th style="text-align: left;">Cách nói (luôn kèm con số)</th>
<th style="text-align: left;">Tần suất tự nhiên</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0.5%</td>
<td style="text-align: left;">gần như không thể</td>
<td style="text-align: left;">0.5 trên 100</td>
</tr>
<tr class="even">
<td style="text-align: left;">5.0%</td>
<td style="text-align: left;">rất ít khả năng</td>
<td style="text-align: left;">5.0 trên 100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">25.0%</td>
<td style="text-align: left;">ít khả năng</td>
<td style="text-align: left;">25.0 trên 100</td>
</tr>
<tr class="even">
<td style="text-align: left;">50.0%</td>
<td style="text-align: left;">khả năng ngang nhau</td>
<td style="text-align: left;">50.0 trên 100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">80.0%</td>
<td style="text-align: left;">có khả năng</td>
<td style="text-align: left;">80.0 trên 100</td>
</tr>
<tr class="even">
<td style="text-align: left;">95.0%</td>
<td style="text-align: left;">rất có khả năng</td>
<td style="text-align: left;">95.0 trên 100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">99.5%</td>
<td style="text-align: left;">gần như chắc chắn</td>
<td style="text-align: left;">99.5 trên 100</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Lập bảng kết quả chính cho bản tóm tắt. Cột “mức chắc chắn” nói rõ xác suất tiết kiệm bao gồm những nguồn bất định nào. Kiểm tra: không ô nào gõ tay; mọi số đi qua <code>fmt_num()</code>, <code>fmt_pct()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The key-results table for a one-page brief: every cell is computed, none typed</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>psa_scope <span class="ot">&lt;-</span> <span class="st">"chỉ tính bất định về giá thuốc và theo dõi, biến cố bất lợi, tỷ lệ đủ điều kiện, số người và tỷ lệ áp dụng"</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>y1_answer <span class="ot">&lt;-</span> <span class="cf">function</span>(ntp, shi) {</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  part <span class="ot">&lt;-</span> <span class="cf">function</span>(label, x) <span class="fu">paste0</span>(label, <span class="cf">if</span> (x <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="st">" chi thêm "</span> <span class="cf">else</span> <span class="st">" tiết kiệm "</span>, <span class="fu">fmt_num</span>(<span class="fu">abs</span>(<span class="fu">bn</span>(x)), <span class="dv">1</span>), <span class="st">" tỷ VNĐ"</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">paste0</span>(<span class="fu">part</span>(<span class="st">"Chương trình Chống lao"</span>, ntp), <span class="st">"; "</span>, <span class="fu">part</span>(<span class="st">"quỹ BHYT"</span>, shi))</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>brief <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">question =</span> <span class="fu">c</span>(<span class="st">"Có đáng tiền không?"</span>, <span class="fu">paste</span>(<span class="st">"Ngân sách"</span>, H, <span class="st">"năm thay đổi bao nhiêu?"</span>),</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Năm đầu ai phải chi thêm?"</span>, <span class="st">"Ai được lợi?"</span>, <span class="st">"Gánh nặng tài chính cho hộ gia đình?"</span>),</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">answer =</span> <span class="fu">c</span>(</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(<span class="st">"BPaLM rẻ hơn phác đồ ngắn 9 tháng "</span>, <span class="fu">fmt_num</span>(<span class="sc">-</span>key<span class="sc">$</span>d_cost <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">1</span>), <span class="st">" triệu VNĐ và thêm "</span>,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>           <span class="fu">fmt_num</span>(key<span class="sc">$</span>d_qaly, <span class="dv">2</span>), <span class="st">" QALY mỗi người bệnh; rẻ hơn và tốt hơn cả phác đồ dài hạn"</span>),</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(<span class="st">"Tiết kiệm "</span>, <span class="fu">fmt_num</span>(<span class="sc">-</span><span class="fu">bn</span>(key<span class="sc">$</span>bia_5y), <span class="dv">0</span>), <span class="st">" tỷ VNĐ (khoảng bất định 95%: "</span>,</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>           <span class="fu">fmt_num</span>(<span class="sc">-</span><span class="fu">bn</span>(ci_5y[[<span class="dv">3</span>]]), <span class="dv">0</span>), <span class="st">"–"</span>, <span class="fu">fmt_num</span>(<span class="sc">-</span><span class="fu">bn</span>(ci_5y[[<span class="dv">1</span>]]), <span class="dv">0</span>), <span class="st">")"</span>),</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">y1_answer</span>(key<span class="sc">$</span>ntp_y1, key<span class="sc">$</span>shi_y1),</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(<span class="fu">fmt_num</span>(key<span class="sc">$</span>deaths_averted, <span class="dv">0</span>), <span class="st">" ca tử vong tránh được trong "</span>, pe<span class="sc">$</span>death_window_months <span class="sc">/</span> <span class="dv">12</span>,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>           <span class="st">" năm mỗi đoàn hệ năm nếu mọi người dùng BPaLM; "</span>,</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>           <span class="fu">fmt_pct</span>(key<span class="sc">$</span>poor_share, <span class="dv">0</span>), <span class="st">" người bệnh thuộc hai nhóm ngũ phân vị nghèo nhất"</span>),</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">paste0</span>(<span class="st">"Hộ gặp chi phí thảm họa giảm từ "</span>, <span class="fu">fmt_pct</span>(key<span class="sc">$</span>che_now, <span class="dv">0</span>), <span class="st">" xuống "</span>,</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>           <span class="fu">fmt_pct</span>(key<span class="sc">$</span>che_bpalm, <span class="dv">0</span>))</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">certainty =</span> <span class="fu">c</span>(<span class="st">"Phụ thuộc giá thuốc và cách áp RR cho tử vong (M02)"</span>,</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>                <span class="fu">paste0</span>(<span class="fu">prob_words</span>(p_saving), <span class="st">": xác suất tiết kiệm "</span>, <span class="fu">fmt_pct</span>(p_saving, <span class="dv">1</span>), <span class="st">", "</span>, psa_scope),</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Phụ thuộc phân chia chi trả (số liệu tài chính WHO, Oh 2026; còn mâu thuẫn về nằm viện)"</span>,</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Phân bố theo nhóm là giá trị minh họa"</span>,</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Chi phí người bệnh từ khảo sát năm 2016; nhạy với giả định về phần chi phí cố định"</span>)</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(brief, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Câu hỏi của người ra quyết định"</span>, <span class="st">"Câu trả lời"</span>, <span class="st">"Mức chắc chắn"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 40%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Câu hỏi của người ra quyết định</th>
<th style="text-align: left;">Câu trả lời</th>
<th style="text-align: left;">Mức chắc chắn</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Có đáng tiền không?</td>
<td style="text-align: left;">BPaLM rẻ hơn phác đồ ngắn 9 tháng 6.7 triệu VNĐ và thêm 0.48 QALY mỗi người bệnh; rẻ hơn và tốt hơn cả phác đồ dài hạn</td>
<td style="text-align: left;">Phụ thuộc giá thuốc và cách áp RR cho tử vong (M02)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ngân sách 5 năm thay đổi bao nhiêu?</td>
<td style="text-align: left;">Tiết kiệm 43 tỷ VNĐ (khoảng bất định 95%: 13–77)</td>
<td style="text-align: left;">gần như chắc chắn: xác suất tiết kiệm 100.0%, chỉ tính bất định về giá thuốc và theo dõi, biến cố bất lợi, tỷ lệ đủ điều kiện, số người và tỷ lệ áp dụng</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Năm đầu ai phải chi thêm?</td>
<td style="text-align: left;">Chương trình Chống lao chi thêm 0.4 tỷ VNĐ; quỹ BHYT tiết kiệm 2.1 tỷ VNĐ</td>
<td style="text-align: left;">Phụ thuộc phân chia chi trả (số liệu tài chính WHO, Oh 2026; còn mâu thuẫn về nằm viện)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ai được lợi?</td>
<td style="text-align: left;">91 ca tử vong tránh được trong 5 năm mỗi đoàn hệ năm nếu mọi người dùng BPaLM; 54% người bệnh thuộc hai nhóm ngũ phân vị nghèo nhất</td>
<td style="text-align: left;">Phân bố theo nhóm là giá trị minh họa</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gánh nặng tài chính cho hộ gia đình?</td>
<td style="text-align: left;">Hộ gặp chi phí thảm họa giảm từ 91% xuống 86%</td>
<td style="text-align: left;">Chi phí người bệnh từ khảo sát năm 2016; nhạy với giả định về phần chi phí cố định</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Bản tóm tắt dưới đây được viết bằng các con số tính ở trên; đổi một tham số rồi biên dịch lại, mọi con số sẽ đổi theo.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Bản tóm tắt mẫu (một số đầu vào là giá trị minh họa, chưa dùng cho quyết định)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Bản tóm tắt mẫu (một số đầu vào là giá trị minh họa, chưa dùng cho quyết định)
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Mở rộng BPaLM cho lao kháng thuốc: tiết kiệm ngân sách và cứu thêm người bệnh, nhưng ngân sách thuốc của Chương trình Chống lao tăng nhẹ năm đầu</strong></p>
<ul>
<li>Mỗi người bệnh chuyển từ phác đồ ngắn 9 tháng sang BPaLM tiết kiệm 6.7 triệu VNĐ và được thêm 0.48 QALY; so với phác đồ dài hạn, BPaLM cũng rẻ hơn và tốt hơn.</li>
<li>Mở rộng trong 5 năm tiết kiệm khoảng 43 tỷ VNĐ (khoảng bất định 95%: 13–77 tỷ VNĐ). Xác suất tiết kiệm là 100.0% khi chỉ tính bất định về giá thuốc và theo dõi, tỷ lệ biến cố bất lợi, tỷ lệ đủ điều kiện, số người bệnh và tỷ lệ áp dụng. Dấu của kết luận không đổi trong cả 8 kịch bản cấu trúc: khoản tiết kiệm nằm giữa 31 và 133 tỷ VNĐ.</li>
<li>Năm 2026, Chương trình Chống lao chi thêm 0.4 tỷ VNĐ; quỹ BHYT tiết kiệm 2.1 tỷ VNĐ.</li>
</ul>
<p><em>Công bằng.</em> 54% người bệnh thuộc hai nhóm ngũ phân vị nghèo nhất; nếu mọi người bệnh dùng BPaLM, mỗi đoàn hệ năm tránh được khoảng 91 ca tử vong trong 5 năm so với cơ cấu hiện tại. Tỷ lệ hộ gặp chi phí thảm họa giảm từ 91% xuống 86%, nhưng hộ nghèo nhất vẫn vượt ngưỡng: cần thêm bảo trợ xã hội.</p>
<p><em>Điều gì làm đổi kết luận.</em> Ngân sách 5 năm chỉ tăng nếu giá BPaLM vượt khoảng 2.65 triệu VNĐ mỗi tháng. Khoản tiết kiệm phụ thuộc nhiều vào việc BPaLM thay phác đồ nào: 75 tỷ VNĐ nếu tính từ cơ cấu trước 2024, 31 tỷ VNĐ nếu mọi người còn lại đang dùng phác đồ ngắn. Phát hiện đủ số ca WHO ước tính sẽ nâng khoản tiết kiệm lên 133 tỷ VNĐ, đồng thời nâng ngân sách hiện tại năm đầu từ 68 lên 210 tỷ VNĐ.</p>
<p><em>Giới hạn.</em> Tỷ lệ áp dụng, tỷ lệ đủ điều kiện, mức hỗ trợ tiền mặt và phân bố theo nhóm thu nhập là giá trị minh họa; phân chia chi trả dựa trên số liệu tài chính tổng quát và còn mâu thuẫn về chi phí nằm viện; xác suất tiết kiệm không gồm bất định lâm sàng của M02.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Mẹo thực hành">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mẹo thực hành
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Viết tiêu đề và ba thông điệp chính trước khi làm hình. Nếu không viết được, phân tích chưa xong.</li>
<li>Đưa bản nháp cho một người không làm mô hình đọc lướt, rồi hỏi họ nhớ con số nào. Đó là con số bạn thực sự truyền đạt được.</li>
<li>Đặt các giả định cấu trúc quan trọng trong bản tóm tắt, không chôn chúng trong phụ lục.</li>
<li>Giữ bản tóm tắt trong cùng tệp Quarto với phân tích; khi tham số đổi, chỉ cần biên dịch lại. Tiêu đề cũng nên sinh từ kết quả, như bản mẫu trên.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Lỗi thường gặp">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lỗi thường gặp
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Chỉ nói lời, không nói số</strong> (“rất có khả năng tiết kiệm”). Người nghe hiểu cụm từ này rất khác nhau; luôn kèm xác suất.</li>
<li><strong>Gọi khoảng mô phỏng là “khoảng tin cậy”.</strong> Đây là khoảng bất định của dự báo, không phải khoảng tin cậy của một ước lượng thống kê.</li>
<li><strong>Gộp giả định cấu trúc vào khoảng bất định, hoặc nêu một xác suất mà không nói nó bao gồm gì.</strong> Cách áp RR cho tử vong không có phân phối; hãy trình bày nó như một kịch bản riêng, và ghi phạm vi rút mẫu bên cạnh mọi xác suất.</li>
<li><strong>Một bảng dài vài trang.</strong> Người ra quyết định chỉ đọc vài dòng đầu. Phần còn lại để ở phụ lục.</li>
</ul>
</div>
</div>
</section>
<section id="bài-tập" class="level2">
<h2 class="anchored" data-anchor-id="bài-tập">Bài tập</h2>
<ol type="1">
<li><strong>(Dễ)</strong> Tính xác suất khoản tiết kiệm 5 năm vượt một mốc cho trước (biến <code>saving_target</code> trong code) và viết một câu cho bản tóm tắt, có cả con số và lời.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 1: probability that 5-year savings exceed a target, in words and numbers</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>p_target <span class="ot">&lt;-</span> <span class="fu">mean</span>(total_sim <span class="sc">&lt;</span> <span class="sc">-</span>saving_target)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">p =</span> <span class="fu">round</span>(p_target, <span class="dv">3</span>), <span class="at">words =</span> <span class="fu">prob_words</span>(p_target))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            p         words 
      "0.675" "có khả năng" </code></pre>
</div>
</div>
<p>Một câu gợi ý: “Khả năng tiết kiệm hơn 30 tỷ VNĐ trong 5 năm là 68% (có khả năng), khi chỉ tính bất định của các đầu vào đã rút mẫu”. Mức tiết kiệm trung vị là 37 tỷ VNĐ, gần mốc này, nên xác suất nhạy với giả định về phân phối.</p>
</div>
</div>
</div>
<ol start="2" type="1">
<li><strong>(Vừa)</strong> Đầu vào nào giải thích nhiều nhất bất định của tác động 5 năm? Dùng hệ số tương quan hạng Spearman giữa từng đầu vào và kết quả.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 2: which input drives the uncertainty? Rank correlation with the 5-year total</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>input_labels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">mult_drug_bpalm =</span> <span class="st">"giá thuốc BPaLM"</span>, <span class="at">mult_drug_short =</span> <span class="st">"giá thuốc phác đồ ngắn"</span>,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">mult_drug_long =</span> <span class="st">"giá thuốc phác đồ dài hạn"</span>, <span class="at">mult_monitor =</span> <span class="st">"chi phí theo dõi"</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">share_eligible =</span> <span class="st">"tỷ lệ đủ điều kiện"</span>, <span class="at">growth_rate =</span> <span class="st">"tốc độ thay đổi số người bệnh"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ae_bpalm =</span> <span class="st">"tỷ lệ biến cố bất lợi nặng của BPaLM"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ae_soc =</span> <span class="st">"tỷ lệ biến cố bất lợi nặng của phác đồ dài hạn/ngắn"</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">uptake_u =</span> <span class="st">"tỷ lệ áp dụng"</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">names</span>(draws) <span class="sc">%in%</span> <span class="fu">names</span>(input_labels)))</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>rho <span class="ot">&lt;-</span> <span class="fu">sapply</span>(draws, <span class="cf">function</span>(x) <span class="fu">cor</span>(x, total_sim, <span class="at">method =</span> <span class="st">"spearman"</span>))</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">sort</span>(rho), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       uptake_u  share_eligible  mult_drug_long     growth_rate          ae_soc 
          -0.69           -0.31           -0.27           -0.19           -0.18 
mult_drug_short    mult_monitor        ae_bpalm mult_drug_bpalm 
          -0.16           -0.09            0.17            0.35 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>top_inputs <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">sort</span>(<span class="fu">abs</span>(rho), <span class="at">decreasing =</span> <span class="cn">TRUE</span>))[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Đầu vào có tương quan hạng lớn nhất về trị tuyệt đối là tỷ lệ áp dụng (ρ = -0.69), rồi giá thuốc BPaLM (ρ = 0.35). Hai đầu vào này tác động ngược chiều. Tương quan dương nghĩa là đầu vào cao làm tác động ngân sách bớt âm (tiết kiệm ít đi); tương quan âm thì ngược lại. Thông điệp cho người ra quyết định: các đầu vào đứng đầu đáng được xác minh trước tiên. Tương quan hạng chỉ là chỉ báo nhanh; M03 dùng các phương pháp chặt hơn.</p>
</div>
</div>
</div>
<ol start="3" type="1">
<li><strong>(Khó)</strong> Sai số chuẩn Monte Carlo của xác suất tiết kiệm năm đầu là bao nhiêu với 1,000 lần rút? Cần bao nhiêu lần rút để sai số chuẩn xuống bằng mức mục tiêu (biến <code>se_target</code> trong code)?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 3: Monte Carlo standard error of P(saving in year 1), and the number of</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># draws needed to bring it down to se_target</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>se_y1 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(p_saving_y1 <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_saving_y1) <span class="sc">/</span> n_sim)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>n_needed <span class="ot">&lt;-</span> <span class="fu">ceiling</span>(p_saving_y1 <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p_saving_y1) <span class="sc">/</span> se_target<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">p_saving_y1 =</span> p_saving_y1, <span class="at">se =</span> <span class="fu">round</span>(se_y1, <span class="dv">4</span>), <span class="at">n_needed =</span> n_needed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>p_saving_y1          se    n_needed 
     0.9570      0.0064   1647.0000 </code></pre>
</div>
</div>
<p>Sai số chuẩn là <span class="math inline">\(\sqrt{p(1-p)/n}\)</span> = 0.0064 với <span class="math inline">\(p\)</span> = 95.7%. Muốn giảm còn 0.005 cần khoảng 1,647 lần rút. Xác suất gần 0.5 cần nhiều lần rút hơn xác suất gần 0 hoặc 1 (xem M00 Bài 6 về sai số Monte Carlo).</p>
</div>
</div>
</div>
</section>
<section id="tài-liệu-tham-khảo" class="level2">
<h2 class="anchored" data-anchor-id="tài-liệu-tham-khảo">Tài liệu tham khảo</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-vanderbles2019communicating" class="csl-entry" role="listitem">
Bles, Anne Marthe van der, Sander van der Linden, Alexandra L. J. Freeman, James Mitchell, Ana B. Galvao, Lisa Zaval, và David J. Spiegelhalter. 2019. <span>“Communicating uncertainty about facts, numbers and science”</span>. <em>Royal Society Open Science</em> 6 (5): 181870. <a href="https://doi.org/10.1098/rsos.181870">https://doi.org/10.1098/rsos.181870</a>.
</div>
<div id="ref-budescu2009improving" class="csl-entry" role="listitem">
Budescu, David V., Stephen Broomell, và Han-Hui Por. 2009. <span>“Improving communication of uncertainty in the reports of the <span>Intergovernmental Panel on Climate Change</span>”</span>. <em>Psychological Science</em> 20 (3): 299–308. <a href="https://doi.org/10.1111/j.1467-9280.2009.02284.x">https://doi.org/10.1111/j.1467-9280.2009.02284.x</a>.
</div>
<div id="ref-hoa2019national" class="csl-entry" role="listitem">
Hoa, N. B., và N. V. Nhung. 2019. <span>“National tuberculosis patients cost survey: research findings lead to change in policy and practice, <span>Viet Nam</span>”</span>. <em>Public Health Action</em> 9 (2): 50–52. <a href="https://doi.org/10.5588/pha.18.0082">https://doi.org/10.5588/pha.18.0082</a>.
</div>
<div id="ref-husereau2022consolidated" class="csl-entry" role="listitem">
Husereau, Don, Michael Drummond, Federico Augustovski, Esther de Bekker-Grob, Andrew H Briggs, Chris Carswell, Lisa Caulley, và c.s. 2022. <span>“Consolidated Health Economic Evaluation Reporting Standards 2022 (CHEERS 2022) statement: updated reporting guidance for health economic evaluations”</span>. <em>BMJ (Clinical research ed.)</em> 376: e067975. <a href="https://doi.org/10.1136/bmj-2021-067975">https://doi.org/10.1136/bmj-2021-067975</a>.
</div>
<div id="ref-itpc2025gdf" class="csl-entry" role="listitem">
ITPC-EECA. 2025. <span>“<span>GDF</span> Announces Bedaquiline Price Reduction”</span>. 16 Tháng Chín 2025. <a href="https://itpc-eeca.org/en/2025/09/16/gdf-announces-bedaquiline-price-reduction/">https://itpc-eeca.org/en/2025/09/16/gdf-announces-bedaquiline-price-reduction/</a>.
</div>
<div id="ref-lee2021health" class="csl-entry" role="listitem">
Lee, Hwa-Young, Thuy Thi-Thu Nguyen, Saeun Park, Van Minh Hoang, và Woong-Han Kim. 2021. <span>“Health technology assessment development in <span>Vietnam</span>: a qualitative study of current progress, barriers, facilitators, and future strategies”</span>. <em>International Journal of Environmental Research and Public Health</em> 18 (16): 8846. <a href="https://doi.org/10.3390/ijerph18168846">https://doi.org/10.3390/ijerph18168846</a>.
</div>
<div id="ref-orourke2020new" class="csl-entry" role="listitem">
O’Rourke, Brian, Wija Oortwijn, và Tara Schuller. 2020. <span>“The new definition of health technology assessment: a milestone in international collaboration”</span>. <em>International Journal of Technology Assessment in Health Care</em> 36 (3): 187–90. <a href="https://doi.org/10.1017/S0266462320000215">https://doi.org/10.1017/S0266462320000215</a>.
</div>
<div id="ref-oh2026assessment" class="csl-entry" role="listitem">
Oh, Kyung Hyun, Jeungeun Seo, Yerin Yu, Fukushi Morishita, Alia Cynthia Luz, Huong Thi Giang Tran, Rajendra Prasad Hubraj Yadav, Martin P. Grobusch, và Hongjo Choi. 2026. <span>“Assessment of financial protection mechanisms for tuberculosis services in seven priority countries of the <span>Western Pacific Region</span>: a cross-sectional mixed-methods study”</span>. <em>Tropical Medicine and Health</em> 54 (1). <a href="https://doi.org/10.1186/s41182-026-00979-7">https://doi.org/10.1186/s41182-026-00979-7</a>.
</div>
<div id="ref-oortwijn2022designing" class="csl-entry" role="listitem">
Oortwijn, Wija, Don Husereau, Julia Abelson, Edwine Barasa, Diana Dana Bayani, Vania Canuto Santos, Anthony Culyer, và c.s. 2022. <span>“Designing and implementing deliberative processes for health technology assessment: a good practices report of a joint <span>HTAi/ISPOR</span> Task Force”</span>. <em>Value in Health</em> 25 (6): 869–86. <a href="https://doi.org/10.1016/j.jval.2022.03.018">https://doi.org/10.1016/j.jval.2022.03.018</a>.
</div>
<div id="ref-sullivan2014budget" class="csl-entry" role="listitem">
Sullivan, Sean D., Josephine A. Mauskopf, Federico Augustovski, J. Jaime Caro, Karen M. Lee, Mark Minchin, Ewa Orlewska, Pete Penna, Jose-Manuel Rodriguez Barrios, và Wen-Yi Shau. 2014. <span>“Budget impact analysis-principles of good practice: report of the <span>ISPOR</span> 2012 Budget Impact Analysis Good Practice <span>II</span> Task Force”</span>. <em>Value in Health</em> 17 (1): 5–14. <a href="https://doi.org/10.1016/j.jval.2013.08.2291">https://doi.org/10.1016/j.jval.2013.08.2291</a>.
</div>
<div id="ref-wilkinson2016international" class="csl-entry" role="listitem">
Wilkinson, Thomas, Mark J. Sculpher, Karl Claxton, Paul Revill, Andrew Briggs, John A. Cairns, Yot Teerawattananon, và c.s. 2016. <span>“The International Decision Support Initiative Reference Case for Economic Evaluation: an aid to thought”</span>. <em>Value in Health</em> 19 (8): 921–28. <a href="https://doi.org/10.1016/j.jval.2016.04.015">https://doi.org/10.1016/j.jval.2016.04.015</a>.
</div>
</div>
<div class="video-script">
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kịch bản video (~13 phút)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Slide</th>
<th>Lời giảng chính</th>
<th>Hình/Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Một trang, vài phút</td>
<td>kinh phí lao phần lớn từ tài trợ; quyết định chuyển về ngân sách trong nước</td>
<td>callout mở đầu</td>
</tr>
<tr class="even">
<td>2</td>
<td>Năm câu hỏi</td>
<td>đáng tiền, ngân sách, ai chi, ai lợi, hộ gia đình</td>
<td>bảng câu hỏi</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Tính lại, không chép</td>
<td>mọi con số từ hàm của Bài 1–3</td>
<td>chunk <code>l04-key-results</code></td>
</tr>
<tr class="even">
<td>4</td>
<td>Cấu trúc một trang</td>
<td>tiêu đề là kết luận; ba thông điệp; một bảng; một hình</td>
<td>danh sách cấu trúc</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Kịch bản và BIA xác suất</td>
<td>cấu trúc → kịch bản; tham số → khoảng bất định 95%; xác suất kèm phạm vi</td>
<td>chunk <code>l04-scenarios</code>, <code>figs/l04-bia-uncertainty.png</code></td>
</tr>
<tr class="even">
<td>6</td>
<td>Con số và lời</td>
<td>người đọc hiểu cụm từ rất khác nhau; luôn kèm số</td>
<td>chunk <code>l04-words</code></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Ba lớp bất định</td>
<td>tham số, cấu trúc, chất lượng bằng chứng</td>
<td>—</td>
</tr>
<tr class="even">
<td>8</td>
<td>Bản tóm tắt mẫu</td>
<td>đọc to trong một phút</td>
<td>callout tóm tắt</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Quy trình HTA</td>
<td>đánh giá → thẩm định có cân nhắc → quyết định</td>
<td>sơ đồ Mermaid</td>
</tr>
<tr class="even">
<td>10</td>
<td>Việt Nam</td>
<td>HTA cho danh mục BHYT; chuyển đổi khỏi tài trợ</td>
<td>trích dẫn</td>
</tr>
<tr class="odd">
<td>11</td>
<td>Kết module</td>
<td>từ mô hình đến quyết định; M11: biến mô hình thành công cụ</td>
<td>—</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" class="pagination-link" aria-label="Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../kb/m11-software-engineering/index.html" class="pagination-link" aria-label="M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế">
        <span class="nav-page-text">M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>