<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI – Mô hình Kinh tế Y tế với R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../kb/m04-microsimulation/index.html" rel="next">
<link href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9e7f0c659d5fa2cace8548cb57964278.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c18d72663580ed8ca19ce2a2f99af51b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="mermaid-theme" content="neutral">
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=JetBrains+Mono:wght@400;600&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m03-uncertainty-voi/index.html">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</a></li><li class="breadcrumb-item"><a href="../../kb/m03-uncertainty-voi/l05-voi.html"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Mô hình Kinh tế Y tế với R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lời mở đầu</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m00-r-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M00 · R cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l02-vectors-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l03-functions-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hàm, cấu trúc điều khiển, vòng lặp và vectơ hóa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l04-data-frames.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Data frame — nhập, làm sạch, tóm tắt và chuyển dạng dữ liệu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l05-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Biểu đồ với ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l06-randomness-monte-carlo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 6: Ngẫu nhiên, mô phỏng Monte Carlo và sai số Monte Carlo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m01-ee-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M01 · Nền tảng đánh giá kinh tế và cây quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l01-evaluation-types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại đánh giá kinh tế, quan điểm, khung thời gian và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l02-health-outcomes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Năm sống, QALY và DALY</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l03-decision-rules.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l04-thresholds.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l05-decision-tree.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Xây cây quyết định từ đầu trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m02-cohort-markov/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l01-state-transition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao cần mô hình chuyển trạng thái</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l03-cohort-trace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l04-time-dependence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Phụ thuộc thời gian: lão hóa, trạng thái đường hầm và mảng 3 chiều</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l05-results-verification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị gắn với lần chuyển, đường biên hiệu quả và xác minh mô hình</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m03-uncertainty-voi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l01-deterministic-sa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại bất định và phân tích độ nhạy tất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l02-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Chọn phân phối cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l03-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích độ nhạy xác suất (PSA) trong R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l05-voi.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m04-microsimulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M04 · Mô phỏng vi mô (microsimulation)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l01-why-microsimulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l02-microsim-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l03-vectorisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vectơ hóa theo cá thể và đo hiệu năng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l04-parallel-rcpp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tính toán song song và Rcpp cho vòng lặp nóng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l05-mc-error-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bao nhiêu cá thể là đủ? Sai số Monte Carlo, PSA và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m05-dynamic-transmission/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M05 · Mô hình lây truyền động</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l01-static-vs-dynamic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Mô hình tĩnh và mô hình lây truyền động</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l02-sir-seir-desolve.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình SIR và SEIR trong R với deSolve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l03-vaccination-herd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Tiêm chủng, hiệu quả trực tiếp và gián tiếp</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l04-dengue-host-vector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Mô hình vật chủ–véc tơ cho sốt xuất huyết Dengue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l05-dynamic-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế với mô hình lây truyền động</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m06-amr-economics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M06 · Kinh tế học kháng kháng sinh (AMR)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l01-amr-burden.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l02-attributable-los.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l03-ward-transmission.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Mô hình lây truyền CRE trong khoa hồi sức</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l04-two-strain-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m07-survival-psm/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M07 · Phân tích sống còn cho mô hình quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l01-survival-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ôn tập phân tích sống còn cho người làm mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l02-parametric-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình sống còn tham số với flexsurv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l03-extrapolation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Ngoại suy sống còn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l04-reconstruct-ipd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tái tạo dữ liệu cá thể từ đường KM đã công bố và dùng HR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l05-partitioned-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Mô hình sống còn phân vùng trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m08-calibration/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M08 · Hiệu chuẩn mô hình (calibration)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l01-why-calibrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l02-search-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l03-bayes-sir.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hiệu chuẩn Bayes và thuật toán SIR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l04-psa-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đưa kết quả hiệu chuẩn vào PSA, thẩm định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m09-inputs-vietnam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l01-costing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ước tính chi phí cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l05-decision-context.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bối cảnh ra quyết định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m10-policy-bia-equity/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m11-software-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l01-code-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Cấu trúc mã cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l02-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Xác minh và kiểm thử mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l03-version-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quản lý phiên bản với Git và tái lập môi trường với renv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l04-r-package.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đóng gói mô hình thành gói R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l05-shiny-living.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Ứng dụng Shiny và mô hình “sống”</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bảng thuật ngữ Anh–Việt</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../references.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tài liệu tham khảo</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Trong bài</h2>
   
  <ul class="collapse">
  <li><a href="#mục-tiêu-học-tập" id="toc-mục-tiêu-học-tập" class="nav-link active" data-scroll-target="#mục-tiêu-học-tập">Mục tiêu học tập</a></li>
  <li><a href="#ý-chính" id="toc-ý-chính" class="nav-link" data-scroll-target="#ý-chính">Ý chính</a></li>
  <li><a href="#nội-dung" id="toc-nội-dung" class="nav-link" data-scroll-target="#nội-dung">Nội dung</a></li>
  <li><a href="#thực-hành" id="toc-thực-hành" class="nav-link" data-scroll-target="#thực-hành">Thực hành</a></li>
  <li><a href="#bài-tập" id="toc-bài-tập" class="nav-link" data-scroll-target="#bài-tập">Bài tập</a></li>
  <li><a href="#tài-liệu-tham-khảo" id="toc-tài-liệu-tham-khảo" class="nav-link" data-scroll-target="#tài-liệu-tham-khảo">Tài liệu tham khảo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m03-uncertainty-voi/index.html">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</a></li><li class="breadcrumb-item"><a href="../../kb/m03-uncertainty-voi/l05-voi.html"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></h1>
<p class="subtitle lead">Có đáng thu thập thêm bằng chứng trước khi mở rộng BPaLM không, và nên nghiên cứu tham số nào?</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled" title="Vì sao bạn nên quan tâm?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vì sao bạn nên quan tâm?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Năm 2024 Việt Nam phát hiện gần 4,000 người mắc lao kháng thuốc <span class="citation" data-cites="daibieunhandan2025chamdut">(<a href="#ref-daibieunhandan2025chamdut" role="doc-biblioref">Báo Đại biểu Nhân dân 2025</a>)</span>. Trước khi mở rộng BPaLM ra cả nước, có nên bỏ tiền cho một nghiên cứu trong nước, chẳng hạn một đoàn hệ đo tỷ lệ thành công và tử vong của từng phác đồ, không? Với giá GDF, giá trị kỳ vọng của thông tin hoàn hảo là 0 VNĐ mỗi người bệnh: không nghiên cứu nào, dù hoàn hảo, đổi được quyết định chọn BPaLM. Nhưng nếu BPaLM phải mua ở giá sát ngưỡng (kịch bản B, giả định), thông tin hoàn hảo cho 10 năm đáng khoảng 106 tỷ VNĐ, bằng tiền thuốc của 14,929 đợt BPaLM giá GDF. Bài này dạy tính các con số đó, và đọc chúng đúng.</p>
</div>
</div>
<section id="mục-tiêu-học-tập" class="level2">
<h2 class="anchored" data-anchor-id="mục-tiêu-học-tập">Mục tiêu học tập</h2>
<p>Sau bài này, bạn có thể:</p>
<ol type="1">
<li>Giải thích giá trị kỳ vọng của thông tin hoàn hảo (expected value of perfect information, EVPI) và tính nó từ kết quả PSA cho hai hoặc ba chiến lược.</li>
<li>Tính EVPI quần thể (population EVPI) cho Việt Nam, nêu rõ giả định về số người bệnh và thời gian quyết định còn hiệu lực.</li>
<li>Ước lượng giá trị kỳ vọng của thông tin hoàn hảo cho một nhóm tham số (EVPPI) bằng mô hình cộng tính tổng quát (generalised additive model, GAM), kèm khoảng bootstrap, và kiểm tra ước lượng đó.</li>
<li>Giải thích giá trị kỳ vọng của thông tin mẫu (EVSI) và lợi ích ròng kỳ vọng của việc lấy mẫu (ENBS) bổ sung gì cho EVPPI.</li>
</ol>
</section>
<section id="ý-chính" class="level2">
<h2 class="anchored" data-anchor-id="ý-chính">Ý chính</h2>
<ul>
<li>Bất định chỉ có giá trị đối với quyết định khi nó có thể khiến ta chọn sai. Phân tích giá trị thông tin (value of information, VOI) đo giá trị đó bằng đơn vị của NMB <span class="citation" data-cites="claxton1999irrelevance fenwick2020value">(<a href="#ref-claxton1999irrelevance" role="doc-biblioref">Claxton 1999</a>; <a href="#ref-fenwick2020value" role="doc-biblioref">Fenwick và c.s. 2020</a>)</span>.</li>
<li><span class="math inline">\(\text{EVPI} = E_\theta[\max_s \text{NMB}_s(\theta)] - \max_s E_\theta[\text{NMB}_s(\theta)]\)</span>. Nó bằng tổn thất kỳ vọng của lựa chọn tối ưu (Bài 4). Một phương án không bao giờ thắng không đóng góp gì vào EVPI.</li>
<li>EVPI quần thể nhân EVPI với số người chịu ảnh hưởng trong thời gian quyết định còn hiệu lực, có chiết khấu. Nếu nó nhỏ hơn chi phí của mọi nghiên cứu khả thi, hãy quyết định ngay.</li>
<li>EVPPI của một nhóm tham số <span class="math inline">\(\phi\)</span> cho biết nên ưu tiên nghiên cứu gì. Hồi quy NMB gia tăng theo <span class="math inline">\(\phi\)</span> trên chính mẫu PSA cho ước lượng nhanh, không cần vòng lặp lồng nhau <span class="citation" data-cites="strong2014estimating">(<a href="#ref-strong2014estimating" role="doc-biblioref">Strong, Oakley, và Brennan 2014</a>)</span>.</li>
<li>Khi biết cấu trúc mô hình, hồi quy theo một <strong>chỉ số dẫn xuất</strong> (ví dụ RR thay cho hai tỷ lệ của thử nghiệm) là chính xác và nhanh.</li>
<li>EVPI và EVPPI là kỳ vọng của một hàm max, nên nhiễu và chệch khi mẫu nhỏ: dùng mẫu PSA lớn, tính khoảng bootstrap, và chỉ xếp hạng khi khoảng không chồng lấn.</li>
<li><span class="math inline">\(\text{EVPPI}(\phi) \leq \text{EVPI}\)</span>, EVPPI của các nhóm không cộng lại thành EVPI, và một “tham số giả” phải có EVPPI gần 0.</li>
<li>VOI chỉ tin cậy như phân phối đầu vào và cấu trúc mô hình; ở đây nó dùng để học phương pháp, không để xếp hạng ưu tiên nghiên cứu thật.</li>
</ul>
</section>
<section id="nội-dung" class="level2">
<h2 class="anchored" data-anchor-id="nội-dung">Nội dung</h2>
<section id="giá-trị-của-việc-biết-chắc-evpi" class="level3">
<h3 class="anchored" data-anchor-id="giá-trị-của-việc-biết-chắc-evpi">Giá trị của việc biết chắc: EVPI</h3>
<p>Hôm nay ta phải chọn một chiến lược với thông tin hiện có, nên nhận <span class="math inline">\(\max_s E_\theta[\text{NMB}_s(\theta)]\)</span>. Nếu biết chắc giá trị thật của mọi tham số <span class="math inline">\(\theta\)</span>, ta sẽ chọn đúng chiến lược tốt nhất cho giá trị đó và nhận <span class="math inline">\(\max_s \text{NMB}_s(\theta)\)</span>. Vì chưa biết <span class="math inline">\(\theta\)</span>, giá trị kỳ vọng của việc biết chắc là trung bình của đại lượng này trên phân phối của <span class="math inline">\(\theta\)</span>. Hiệu số giữa hai đại lượng là EVPI:</p>
<p><span class="math display">\[
\text{EVPI} = \frac{1}{N}\sum_{i=1}^{N} \max_s \text{NMB}_{s,i} - \max_s \frac{1}{N}\sum_{i=1}^{N} \text{NMB}_{s,i} .
\]</span></p>
<p>Với hai chiến lược và NMB gia tăng <span class="math inline">\(\text{INB}_i\)</span>, công thức gọn lại thành <span class="math inline">\(E[\max(0, \text{INB})] - \max(0, E[\text{INB}])\)</span> (<code>evpi_inb()</code>); với ba chiến lược, dùng <code>evpi_nmb()</code> trên ma trận NMB. EVPI bằng 0 khi một chiến lược thắng ở mọi lần chạy, và lớn nhất khi quyết định sát ngưỡng và đám mây PSA rộng <span class="citation" data-cites="wilson2015practical">(<a href="#ref-wilson2015practical" role="doc-biblioref">Wilson 2015</a>)</span>.</p>
</section>
<section id="evpi-quần-thể" class="level3">
<h3 class="anchored" data-anchor-id="evpi-quần-thể">EVPI quần thể</h3>
<p>Một nghiên cứu mới giúp mọi người bệnh được điều trị trong suốt thời gian quyết định còn hiệu lực, không chỉ một người. Với <span class="math inline">\(n\)</span> người mỗi năm, thời gian <span class="math inline">\(T\)</span> năm và tỷ lệ chiết khấu <span class="math inline">\(r\)</span>:</p>
<p><span class="math display">\[
\text{EVPI}_{\text{quần thể}} = \text{EVPI} \times \sum_{t=0}^{T-1} \frac{n}{(1+r)^t} .
\]</span></p>
<p>Bài này dùng ba mức <span class="math inline">\(n\)</span>: khoảng 2,407 người được điều trị mỗi năm trong 2021–2022 <span class="citation" data-cites="nguyen2026from">(<a href="#ref-nguyen2026from" role="doc-biblioref">Nguyen và c.s. 2026</a>)</span>, gần 4,000 ca lao kháng thuốc được phát hiện năm 2024 <span class="citation" data-cites="daibieunhandan2025chamdut">(<a href="#ref-daibieunhandan2025chamdut" role="doc-biblioref">Báo Đại biểu Nhân dân 2025</a>)</span>, và 9,400 ca mắc mới ước tính của WHO <span class="citation" data-cites="who2026rrestimates">(<a href="#ref-who2026rrestimates" role="doc-biblioref">World Health Organization 2026</a>)</span>, nếu phát hiện được hết. <span class="math inline">\(T\)</span> = 10 năm là giá trị minh họa (khoảng 5–15 năm). Quyết định chỉ ảnh hưởng người đủ điều kiện dùng BPaLM, nên mọi con số dưới đây là <em>cận trên</em> theo số người.</p>
</section>
<section id="evppi-bằng-hồi-quy" class="level3">
<h3 class="anchored" data-anchor-id="evppi-bằng-hồi-quy">EVPPI bằng hồi quy</h3>
<p>Với một nhóm tham số <span class="math inline">\(\phi\)</span> (phần còn lại là <span class="math inline">\(\psi\)</span>),</p>
<p><span class="math display">\[
\text{EVPPI}(\phi) = E_\phi\!\left[\max_s E_{\psi \mid \phi}\,\text{NMB}_s(\phi, \psi)\right] - \max_s E\,[\text{NMB}_s] .
\]</span></p>
<p>Cách tính trực tiếp cần hai vòng lặp lồng nhau, tức hàng trăm nghìn lần chạy mô hình. Strong và cộng sự nhận ra rằng kỳ vọng bên trong, <span class="math inline">\(E[\text{INB} \mid \phi]\)</span>, chính là hàm hồi quy của INB theo <span class="math inline">\(\phi\)</span>. Vì vậy chỉ cần khớp một mô hình hồi quy trơn của INB theo <span class="math inline">\(\phi\)</span> trên mẫu PSA đã có, rồi thay INB bằng giá trị khớp <span class="math inline">\(\hat g(\phi_i)\)</span> <span class="citation" data-cites="strong2014estimating">(<a href="#ref-strong2014estimating" role="doc-biblioref">Strong, Oakley, và Brennan 2014</a>)</span>:</p>
<p><span class="math display">\[
\widehat{\text{EVPPI}}(\phi) = \frac{1}{N}\sum_i \max\{0, \hat g(\phi_i)\} - \max\Big\{0, \frac{1}{N}\sum_i \hat g(\phi_i)\Big\}.
\]</span></p>
<p>Công thức này cho hai chiến lược; với ba chiến lược, cần khớp một hồi quy cho mỗi NMB gia tăng. Ở đây phác đồ dài hạn không bao giờ thắng (Bài 4), nên EVPI ba chiến lược bằng EVPI hai chiến lược và dùng INB của BPaLM so với phác đồ ngắn là đủ; đoạn mã kiểm tra điều đó. GAM trong <code>mgcv</code> là lựa chọn mặc định, làm trơn bằng REML <span class="citation" data-cites="wood2011fast">(<a href="#ref-wood2011fast" role="doc-biblioref">Wood 2011</a>)</span>: <code>s(x)</code> cho một tham số, <code>te()</code> (tích tensor, giữ tương tác) cho hai hoặc ba tham số; nhóm lớn hơn nên dùng quá trình Gauss hoặc các phương pháp trong báo cáo của ISPOR <span class="citation" data-cites="rothery2020value">(<a href="#ref-rothery2020value" role="doc-biblioref">Rothery và c.s. 2020</a>)</span>. Khi biết cấu trúc, hồi quy theo một <em>chỉ số dẫn xuất</em>: M02 chỉ dùng hai tỷ lệ của thử nghiệm qua tỷ số RR, và bốn tham số biến cố bất lợi tác động lên INB qua một tổ hợp duy nhất, nên một spline một chiều là chính xác. Luôn chạy hai phép thử âm tính: EVPPI không vượt EVPI, và một tham số giả có EVPPI gần 0.</p>
</section>
<section id="evsi-giá-trị-của-một-nghiên-cứu-cụ-thể" class="level3">
<h3 class="anchored" data-anchor-id="evsi-giá-trị-của-một-nghiên-cứu-cụ-thể">EVSI: giá trị của một nghiên cứu cụ thể</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>flowchart TB</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  A["EVPI&lt;br/&gt;biết chắc mọi tham số"] --&gt; B["EVPPI(φ)&lt;br/&gt;biết chắc nhóm φ"]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  B --&gt; C["EVSI(φ, n)&lt;br/&gt;một nghiên cứu cỡ mẫu n đo φ"]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  C --&gt; D["ENBS = EVSI quần thể − chi phí nghiên cứu&lt;br/&gt;chọn thiết kế và cỡ mẫu có ENBS lớn nhất"]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TB
  A["EVPI&lt;br/&gt;biết chắc mọi tham số"] --&gt; B["EVPPI(φ)&lt;br/&gt;biết chắc nhóm φ"]
  B --&gt; C["EVSI(φ, n)&lt;br/&gt;một nghiên cứu cỡ mẫu n đo φ"]
  C --&gt; D["ENBS = EVSI quần thể − chi phí nghiên cứu&lt;br/&gt;chọn thiết kế và cỡ mẫu có ENBS lớn nhất"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Không nghiên cứu nào cho thông tin hoàn hảo. EVSI hỏi: một nghiên cứu cụ thể, ví dụ một đoàn hệ theo dõi <span class="math inline">\(n\)</span> người bệnh dùng phác đồ ngắn tại các tỉnh, đáng giá bao nhiêu? EVSI tăng theo <span class="math inline">\(n\)</span> và tiệm cận EVPPI của các tham số mà nghiên cứu đo <span class="citation" data-cites="ades2004expected">(<a href="#ref-ades2004expected" role="doc-biblioref">Ades, Lu, và Claxton 2004</a>)</span>. Trừ chi phí nghiên cứu (tăng theo <span class="math inline">\(n\)</span>) khỏi EVSI quần thể được ENBS; thiết kế tốt nhất có ENBS lớn nhất. Tính EVSI cần mô hình hóa dữ liệu của nghiên cứu tương lai; bốn phương pháp xấp xỉ được so sánh trong hướng dẫn của Kunst và cộng sự <span class="citation" data-cites="kunst2020computing">(<a href="#ref-kunst2020computing" role="doc-biblioref">Kunst và c.s. 2020</a>)</span>, và gói R <code>voi</code> cài đặt nhiều phương pháp trong số đó <span class="citation" data-cites="jackson2024voi">(<a href="#ref-jackson2024voi" role="doc-biblioref">Jackson và Heath 2024</a>)</span>.</p>
</section>
</section>
<section id="thực-hành" class="level2">
<h2 class="anchored" data-anchor-id="thực-hành">Thực hành</h2>
<p>Chạy PSA cho kịch bản B với 1,000 lần (mẫu nhỏ, như Bài 3–4), rồi chạy cả hai kịch bản với 5,000 lần bằng <code>run_psa_vec()</code> (mẫu lớn dùng cho VOI). Kiểm tra: bản vectơ hóa trùng vòng lặp <code>run_cea()</code> ở năm lần chạy đầu (<code>stopifnot</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vietnamese text in figures needs a UTF-8 locale (Rscript may start in the "C" locale)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">isTRUE</span>(<span class="fu">l10n_info</span>()[[<span class="st">"UTF-8"</span>]])) <span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_CTYPE"</span>, <span class="st">"en_US.UTF-8"</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/helpers.R"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/vn_data.R"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"code/model.R"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(mgcv))</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>inp <span class="ot">&lt;-</span> <span class="fu">load_m03_inputs</span>()</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> inp<span class="sc">$</span>p</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>spec <span class="ot">&lt;-</span> inp<span class="sc">$</span>spec</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> inp<span class="sc">$</span>u</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>ctx <span class="ot">&lt;-</span> inp<span class="sc">$</span>ctx</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>ctab <span class="ot">&lt;-</span> <span class="fu">attr</span>(ctx, <span class="st">"table"</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>utab <span class="ot">&lt;-</span> <span class="fu">attr</span>(u, <span class="st">"table"</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">fit_dist</span>(spec)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>price_hi <span class="ot">&lt;-</span> <span class="fu">price_scenario</span>(p, u<span class="sc">$</span>price_round)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Small sample (Lessons 3-4): n_psa runs, scenario B (negotiated price near the threshold)</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>draws_1k <span class="ot">&lt;-</span> <span class="fu">draw_psa</span>(fit, <span class="at">n =</span> u<span class="sc">$</span>n_psa, <span class="at">seed =</span> u<span class="sc">$</span>seed)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>psa_b_1k <span class="ot">&lt;-</span> <span class="fu">run_psa_vec</span>(p, draws_1k, <span class="at">fixed =</span> <span class="fu">list</span>(<span class="at">c_drug_bpalm =</span> price_hi))</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>inb_b_1k <span class="ot">&lt;-</span> <span class="fu">psa_incremental</span>(psa_b_1k, p<span class="sc">$</span>wtp)<span class="sc">$</span>d_nmb</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Large sample for value of information: n_psa_voi runs with the vectorised model (Lesson 3).</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="co"># EVPI and EVPPI are expectations of a maximum, so they need more runs than a mean does.</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>draws <span class="ot">&lt;-</span> <span class="fu">draw_psa</span>(fit, <span class="at">n =</span> u<span class="sc">$</span>n_psa_voi, <span class="at">seed =</span> u<span class="sc">$</span>seed)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>psa_a <span class="ot">&lt;-</span> <span class="fu">run_psa_vec</span>(p, draws)                                          <span class="co"># A: GDF price</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>psa_b <span class="ot">&lt;-</span> <span class="fu">run_psa_vec</span>(p, draws, <span class="at">fixed =</span> <span class="fu">list</span>(<span class="at">c_drug_bpalm =</span> price_hi))   <span class="co"># B: negotiated price</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>inb_a <span class="ot">&lt;-</span> <span class="fu">psa_incremental</span>(psa_a, p<span class="sc">$</span>wtp)<span class="sc">$</span>d_nmb                            <span class="co"># BPaLM minus short</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>inb_b <span class="ot">&lt;-</span> <span class="fu">psa_incremental</span>(psa_b, p<span class="sc">$</span>wtp)<span class="sc">$</span>d_nmb</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="co"># the vectorised runs agree with the loop of M02 run_cea() for the first 5 draws</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>chk_loop <span class="ot">&lt;-</span> <span class="fu">run_psa</span>(p, draws[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, ], <span class="at">fixed =</span> <span class="fu">list</span>(<span class="at">c_drug_bpalm =</span> price_hi), <span class="at">cores =</span> <span class="dv">1</span>)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">max</span>(<span class="fu">abs</span>(<span class="fu">as.matrix</span>(psa_b[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, ]) <span class="sc">/</span> <span class="fu">as.matrix</span>(chk_loop) <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">&lt;</span> <span class="fl">1e-8</span>)</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">n_small =</span> <span class="fu">length</span>(inb_b_1k), <span class="at">n_large =</span> <span class="fu">length</span>(inb_b))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>n_small n_large 
   1000    5000 </code></pre>
</div>
</div>
<p>Tính EVPI hai và ba chiến lược cho hai kịch bản, rồi EVPI theo ngưỡng. Kiểm tra: EVPI không âm; EVPI ba chiến lược không nhỏ hơn EVPI hai chiến lược, và bằng nhau khi phác đồ dài hạn không bao giờ thắng (<code>stopifnot</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Two-strategy EVPI (BPaLM vs short) and three-strategy EVPI (all regimens)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>evpi <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">A =</span> <span class="fu">evpi_inb</span>(inb_a), <span class="at">B =</span> <span class="fu">evpi_inb</span>(inb_b))</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>evpi3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">A =</span> <span class="fu">evpi_nmb</span>(<span class="fu">nmb_matrix</span>(psa_a, p<span class="sc">$</span>wtp)), <span class="at">B =</span> <span class="fu">evpi_nmb</span>(<span class="fu">nmb_matrix</span>(psa_b, p<span class="sc">$</span>wtp)))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>evpi_1k <span class="ot">&lt;-</span> <span class="fu">evpi_inb</span>(inb_b_1k)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Does the long regimen ever have the highest NMB? If never, it cannot add any value of information.</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>long_wins <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">A =</span> <span class="fu">mean</span>(<span class="fu">max.col</span>(<span class="fu">nmb_matrix</span>(psa_a, p<span class="sc">$</span>wtp)) <span class="sc">==</span> <span class="dv">1</span>), <span class="at">B =</span> <span class="fu">mean</span>(<span class="fu">max.col</span>(<span class="fu">nmb_matrix</span>(psa_b, p<span class="sc">$</span>wtp)) <span class="sc">==</span> <span class="dv">1</span>))</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">colnames</span>(<span class="fu">nmb_matrix</span>(psa_a, p<span class="sc">$</span>wtp))[<span class="dv">1</span>] <span class="sc">==</span> <span class="st">"long"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">rbind</span>(<span class="at">evpi_2_strategies =</span> evpi, <span class="at">evpi_3_strategies =</span> evpi3, <span class="at">long_optimal_share =</span> long_wins) <span class="sc">/</span> <span class="fu">c</span>(<span class="fl">1e6</span>, <span class="fl">1e6</span>, <span class="dv">1</span>), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   A     B
evpi_2_strategies  0 3.012
evpi_3_strategies  0 3.012
long_optimal_share 0 0.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">B_with_1000_runs =</span> evpi_1k <span class="sc">/</span> <span class="fl">1e6</span>), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>B_with_1000_runs 
            3.06 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(evpi <span class="sc">&gt;=</span> <span class="dv">0</span>), evpi[[<span class="st">"B"</span>]] <span class="sc">&gt;</span> evpi[[<span class="st">"A"</span>]], <span class="fu">all</span>(evpi3 <span class="sc">&gt;=</span> evpi <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">all</span>(long_wins <span class="sc">==</span> <span class="dv">0</span>)) <span class="fu">stopifnot</span>(<span class="fu">max</span>(<span class="fu">abs</span>(evpi3 <span class="sc">-</span> evpi)) <span class="sc">&lt;</span> <span class="dv">1</span>)          <span class="co"># exactly equal then</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># EVPI across thresholds for both scenarios (0 to 3 x GDP per capita)</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>wtp_grid <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">unique</span>(<span class="fu">c</span>(<span class="fu">seq</span>(<span class="dv">0</span>, ctab<span class="sc">$</span>high[ctab<span class="sc">$</span>name <span class="sc">==</span> <span class="st">"wtp"</span>], <span class="at">by =</span> <span class="fl">2.5e6</span>), p<span class="sc">$</span>wtp)))</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>evpi_curve <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (w <span class="cf">in</span> wtp_grid) {</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  evpi_curve <span class="ot">&lt;-</span> <span class="fu">rbind</span>(evpi_curve, <span class="fu">data.frame</span>(</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">wtp =</span> w,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">A =</span> <span class="fu">evpi_nmb</span>(<span class="fu">nmb_matrix</span>(psa_a, w)),</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">B =</span> <span class="fu">evpi_nmb</span>(<span class="fu">nmb_matrix</span>(psa_b, w))))</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>lab_a <span class="ot">&lt;-</span> <span class="st">"A. Giá GDF (phân tích cơ sở)"</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>lab_b <span class="ot">&lt;-</span> <span class="st">"B. Giá đàm phán sát ngưỡng (minh họa)"</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>evpi_long <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">data.frame</span>(<span class="at">scenario =</span> lab_a, <span class="at">wtp =</span> evpi_curve<span class="sc">$</span>wtp, <span class="at">evpi =</span> evpi_curve<span class="sc">$</span>A),</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">data.frame</span>(<span class="at">scenario =</span> lab_b, <span class="at">wtp =</span> evpi_curve<span class="sc">$</span>wtp, <span class="at">evpi =</span> evpi_curve<span class="sc">$</span>B))</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>fig_evpi <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(evpi_long, <span class="fu">aes</span>(wtp <span class="sc">/</span> <span class="fl">1e6</span>, evpi <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">colour =</span> scenario)) <span class="sc">+</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> p<span class="sc">$</span>wtp <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">linetype =</span> <span class="st">"22"</span>, <span class="at">colour =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> pal_course[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)], <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Ngưỡng chi phí-hiệu quả (triệu VNĐ/QALY)"</span>, <span class="at">y =</span> <span class="st">"EVPI (triệu VNĐ mỗi người bệnh)"</span>,</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"EVPI theo ngưỡng, ba phác đồ"</span>, <span class="at">subtitle =</span> <span class="st">"Đường đứt: ngưỡng 1 × GDP/người"</span>) <span class="sc">+</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">colour =</span> <span class="fu">guide_legend</span>(<span class="at">nrow =</span> <span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_evpi, <span class="st">"l05-evpi.png"</span>, <span class="at">width =</span> <span class="dv">7</span>, <span class="at">height =</span> <span class="fl">4.5</span>)</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>wtp_evpi_max <span class="ot">&lt;-</span> evpi_curve<span class="sc">$</span>wtp[<span class="fu">which.max</span>(evpi_curve<span class="sc">$</span>B)]</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>max_evpi_a <span class="ot">&lt;-</span> <span class="fu">max</span>(evpi_curve<span class="sc">$</span>A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l05-evpi.png" class="img-fluid figure-img"></p>
<figcaption>EVPI theo ngưỡng</figcaption>
</figure>
</div>
<p>Trong kịch bản A, EVPI là 0 VNĐ ở 1 × GDP/người và bằng 0 ở mọi ngưỡng trên hình. Trong kịch bản B, EVPI là 3.01 triệu VNĐ mỗi người bệnh, và đường EVPI đạt đỉnh quanh 125.0 triệu VNĐ/QALY, nơi quyết định sát nhất. Phác đồ dài hạn không thắng ở lần chạy nào, nên EVPI ba chiến lược bằng đúng EVPI hai chiến lược. Với 1,000 lần chạy, EVPI của B là 3.06 triệu VNĐ: EVPI ít nhạy với cỡ mẫu. EVPPI nhạy với cỡ mẫu hơn, như dưới đây.</p>
<p>Nhân với số người bệnh chịu ảnh hưởng. Kiểm tra: với một năm, số người có chiết khấu bằng đúng số người mỗi năm; EVPI quần thể tăng theo thời gian và theo số người (<code>stopifnot</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># People affected each year (low, base, high of params/uncertainty.csv), assumed constant,</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># over the lifetime of the decision (low, base, high), discounted at the shared rate</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>nrow_u <span class="ot">&lt;-</span> <span class="cf">function</span>(k) utab[utab<span class="sc">$</span>name <span class="sc">==</span> k, ]</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>people <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">low =</span> <span class="fu">nrow_u</span>(<span class="st">"n_year_affected"</span>)<span class="sc">$</span>low, <span class="at">base =</span> u<span class="sc">$</span>n_year_affected, <span class="at">high =</span> <span class="fu">nrow_u</span>(<span class="st">"n_year_affected"</span>)<span class="sc">$</span>high)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>yrs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">low =</span> <span class="fu">nrow_u</span>(<span class="st">"voi_years"</span>)<span class="sc">$</span>low, <span class="at">base =</span> u<span class="sc">$</span>voi_years, <span class="at">high =</span> <span class="fu">nrow_u</span>(<span class="st">"voi_years"</span>)<span class="sc">$</span>high)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>pop_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">years =</span> yrs)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k <span class="cf">in</span> <span class="fu">names</span>(people)) {</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  pop_tab[[<span class="fu">paste0</span>(<span class="st">"people_"</span>, k)]] <span class="ot">&lt;-</span> <span class="fu">vapply</span>(yrs, <span class="cf">function</span>(y) evpi[[<span class="st">"B"</span>]] <span class="sc">*</span> <span class="fu">pop_factor</span>(people[[k]], y, p<span class="sc">$</span>disc_rate), <span class="dv">0</span>) <span class="sc">/</span> <span class="fl">1e9</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(pop_tab, <span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="at">row.names =</span> <span class="cn">FALSE</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Thời gian quyết định còn hiệu lực (năm)"</span>,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">paste0</span>(<span class="st">"EVPI quần thể B, "</span>, <span class="fu">fmt_num</span>(people), <span class="st">" người/năm (tỷ VNĐ)"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 24%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Thời gian quyết định còn hiệu lực (năm)</th>
<th style="text-align: right;">EVPI quần thể B, 2,407 người/năm (tỷ VNĐ)</th>
<th style="text-align: right;">EVPI quần thể B, 4,000 người/năm (tỷ VNĐ)</th>
<th style="text-align: right;">EVPI quần thể B, 9,400 người/năm (tỷ VNĐ)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">34.2</td>
<td style="text-align: right;">56.8</td>
<td style="text-align: right;">133.6</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">63.7</td>
<td style="text-align: right;">105.9</td>
<td style="text-align: right;">248.8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: right;">89.2</td>
<td style="text-align: right;">148.2</td>
<td style="text-align: right;">348.2</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>pf_base <span class="ot">&lt;-</span> <span class="fu">pop_factor</span>(people[[<span class="st">"base"</span>]], u<span class="sc">$</span>voi_years, p<span class="sc">$</span>disc_rate)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>pop_evpi_b <span class="ot">&lt;-</span> evpi[[<span class="st">"B"</span>]] <span class="sc">*</span> pf_base</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>pop_evpi_a <span class="ot">&lt;-</span> evpi[[<span class="st">"A"</span>]] <span class="sc">*</span> pf_base</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>course_gdf <span class="ot">&lt;-</span> p<span class="sc">$</span>c_drug_bpalm <span class="sc">*</span> p<span class="sc">$</span>dur_bpalm                      <span class="co"># one BPaLM course at the GDF price</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(<span class="fu">pop_factor</span>(people[[<span class="st">"base"</span>]], <span class="dv">1</span>, p<span class="sc">$</span>disc_rate) <span class="sc">-</span> people[[<span class="st">"base"</span>]]) <span class="sc">&lt;</span> <span class="fl">1e-9</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(<span class="fu">diff</span>(pop_tab<span class="sc">$</span>people_base) <span class="sc">&gt;</span> <span class="dv">0</span>), <span class="fu">all</span>(pop_tab<span class="sc">$</span>people_high <span class="sc">&gt;</span> pop_tab<span class="sc">$</span>people_low))</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">people_discounted =</span> pf_base, <span class="at">pop_evpi_b_billion =</span> pop_evpi_b <span class="sc">/</span> <span class="fl">1e9</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">pop_evpi_a_billion =</span> pop_evpi_a <span class="sc">/</span> <span class="fl">1e9</span>, <span class="at">bpalm_courses_equivalent =</span> pop_evpi_b <span class="sc">/</span> course_gdf), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       people_discounted       pop_evpi_b_billion       pop_evpi_a_billion 
                 35144.4                    105.9                      0.0 
bpalm_courses_equivalent 
                 14928.9 </code></pre>
</div>
</div>
<p>Với 4,000 người mỗi năm trong 10 năm, EVPI quần thể của kịch bản B là 105.9 tỷ VNĐ, bằng tiền thuốc của khoảng 14,929 đợt BPaLM giá GDF: mức trần cho tổng giá trị của mọi nghiên cứu nhằm giảm bất định của quyết định này. Bảng cho thấy con số này thay đổi 10 lần giữa giả định thấp nhất và cao nhất về số người và thời gian; hai giả định đó cần được nêu rõ cạnh con số. Trong kịch bản A con số đó là 0.0 tỷ VNĐ, nên với giá GDF, không nghiên cứu nào đáng làm <em>chỉ để</em> quyết định có dùng BPaLM thay phác đồ ngắn hay không. Nghiên cứu vẫn có thể cần vì lý do khác, như theo dõi an toàn hoặc kháng bedaquiline.</p>
<p>Ước lượng EVPPI cho từng nhóm tham số bằng GAM. Hai nhóm dùng chỉ số dẫn xuất; đoạn mã kiểm tra trước, trên 20 lần rút, rằng INB đổi đúng bằng chỉ số biến cố bất lợi, và không đổi khi hai tỷ lệ của thử nghiệm đổi mà RR giữ nguyên. Kiểm tra: không nhóm nào vượt EVPI (cho phép 2% sai số ước lượng), và tham số giả có EVPPI dưới 1% EVPI (<code>stopifnot</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Groups of parameters that one study could measure. In scenario B the BPaLM price is fixed,</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># so it is not a group. Two groups use a DERIVED INDEX (one variable, exact):</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  - trial effect: M02 uses the two trial proportions only through their ratio (RR);</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co">#  - adverse events: the four parameters act on INB through</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co">#    (ae_soc - ae_bpalm) x (lambda x d_ae x dur_ae / 12 + hospital cost in VND).</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>groups <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Hiệu quả BPaLM trong thử nghiệm (RR)"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"unf_bpalm_trial"</span>, <span class="st">"unf_soc_trial"</span>),</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Thành công của phác đồ ngắn (VN)"</span> <span class="ot">=</span> <span class="st">"short_success"</span>,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Kết cục chương trình (VN)"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"vn_failure"</span>, <span class="st">"vn_death"</span>, <span class="st">"vn_ltfu"</span>),</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Biến cố bất lợi"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"ae_bpalm"</span>, <span class="st">"ae_soc"</span>, <span class="st">"d_ae"</span>, <span class="st">"c_hosp_usd"</span>),</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Diễn tiến lao không điều trị"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"cf_untreated"</span>, <span class="st">"dur_untreated"</span>),</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Sau bỏ điều trị và điều trị lại"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"ltfu_mort_rate"</span>, <span class="st">"retx_rate_ltfu"</span>, <span class="st">"retx_rate_failed"</span>),</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"SMR sau điều trị"</span> <span class="ot">=</span> <span class="st">"smr_post"</span>,</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Thỏa dụng"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"u_tb"</span>, <span class="st">"u_post"</span>),</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Giá thuốc phác đồ ngắn, dài hạn và theo dõi"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"c_drug_short"</span>, <span class="st">"c_drug_long"</span>, <span class="st">"c_monitor"</span>),</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Chi phí khác (thất bại, cuối điều trị)"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"c_failed"</span>, <span class="st">"c_eot"</span>),</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"aOR phác đồ dài hạn (qua điều trị lại)"</span> <span class="ot">=</span> <span class="st">"aor_long_vs_bdqstr"</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>g_rr <span class="ot">&lt;-</span> <span class="st">"Hiệu quả BPaLM trong thử nghiệm (RR)"</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>g_ae <span class="ot">&lt;-</span> <span class="st">"Biến cố bất lợi"</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">setequal</span>(<span class="fu">unlist</span>(groups), <span class="fu">setdiff</span>(fit<span class="sc">$</span>name, <span class="fu">c</span>(<span class="st">"vn_success"</span>, <span class="st">"vn_not_eval"</span>, <span class="st">"c_drug_bpalm"</span>))))</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>index_ae <span class="ot">&lt;-</span> <span class="cf">function</span>(d) {</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>  (d<span class="sc">$</span>ae_soc <span class="sc">-</span> d<span class="sc">$</span>ae_bpalm) <span class="sc">*</span> (d<span class="sc">$</span>d_ae <span class="sc">*</span> p<span class="sc">$</span>dur_ae <span class="sc">/</span> <span class="dv">12</span> <span class="sc">*</span> p<span class="sc">$</span>wtp <span class="sc">+</span> d<span class="sc">$</span>c_hosp_usd <span class="sc">*</span> p<span class="sc">$</span>fx_vnd_usd <span class="sc">*</span> p<span class="sc">$</span>hosp_inflator)</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>index_rr <span class="ot">&lt;-</span> <span class="cf">function</span>(d) d<span class="sc">$</span>unf_bpalm_trial <span class="sc">/</span> d<span class="sc">$</span>unf_soc_trial</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Check both identities on 20 draws: change only the group's parameters (price fixed at B)</span></span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>p_b <span class="ot">&lt;-</span> p; p_b<span class="sc">$</span>c_drug_bpalm <span class="ot">&lt;-</span> price_hi</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>lhs <span class="ot">&lt;-</span> rhs <span class="ot">&lt;-</span> same_rr <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">20</span>)</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>base_ae <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(p[groups[[g_ae]]])</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>) {</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>  q <span class="ot">&lt;-</span> p_b</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (k <span class="cf">in</span> groups[[g_ae]]) q[[k]] <span class="ot">&lt;-</span> draws[[k]][i]</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>  lhs[i] <span class="ot">&lt;-</span> <span class="fu">d_nmb</span>(q) <span class="sc">-</span> <span class="fu">d_nmb</span>(p_b)</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>  rhs[i] <span class="ot">&lt;-</span> <span class="fu">index_ae</span>(draws[i, groups[[g_ae]]]) <span class="sc">-</span> <span class="fu">index_ae</span>(base_ae)</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a>  <span class="co"># same RR, different proportions: same INB</span></span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>  q1 <span class="ot">&lt;-</span> p_b; q1<span class="sc">$</span>unf_bpalm_trial <span class="ot">&lt;-</span> draws<span class="sc">$</span>unf_bpalm_trial[i]; q1<span class="sc">$</span>unf_soc_trial <span class="ot">&lt;-</span> draws<span class="sc">$</span>unf_soc_trial[i]</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>  q2 <span class="ot">&lt;-</span> q1; q2<span class="sc">$</span>unf_bpalm_trial <span class="ot">&lt;-</span> <span class="fl">0.5</span> <span class="sc">*</span> q1<span class="sc">$</span>unf_bpalm_trial; q2<span class="sc">$</span>unf_soc_trial <span class="ot">&lt;-</span> <span class="fl">0.5</span> <span class="sc">*</span> q1<span class="sc">$</span>unf_soc_trial</span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>  same_rr[i] <span class="ot">&lt;-</span> <span class="fu">d_nmb</span>(q1) <span class="sc">-</span> <span class="fu">d_nmb</span>(q2)</span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">max</span>(<span class="fu">abs</span>(lhs <span class="sc">-</span> rhs)) <span class="sc">&lt;</span> <span class="fl">1e-3</span>, <span class="fu">max</span>(<span class="fu">abs</span>(same_rr)) <span class="sc">&lt;</span> <span class="fl">1e-3</span>)     <span class="co"># 0.001 VND</span></span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a>group_X <span class="ot">&lt;-</span> <span class="cf">function</span>(g, d) {</span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (g <span class="sc">==</span> g_ae) <span class="fu">return</span>(<span class="fu">data.frame</span>(<span class="at">index_ae =</span> <span class="fu">index_ae</span>(d)))</span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (g <span class="sc">==</span> g_rr) <span class="fu">return</span>(<span class="fu">data.frame</span>(<span class="at">rr =</span> <span class="fu">index_rr</span>(d)))</span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a>  d[groups[[g]]]</span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a>method_of <span class="ot">&lt;-</span> <span class="cf">function</span>(g) {</span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (g <span class="sc">%in%</span> <span class="fu">c</span>(g_ae, g_rr)) <span class="st">"chỉ số dẫn xuất, s()"</span> <span class="cf">else</span> <span class="cf">if</span> (<span class="fu">length</span>(groups[[g]]) <span class="sc">==</span> <span class="dv">1</span>) <span class="st">"s()"</span> <span class="cf">else</span> <span class="st">"te()"</span></span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a><span class="co"># A dummy 'parameter' that the model never uses: its EVPPI should be about zero</span></span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(u<span class="sc">$</span>seed)</span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a>draws<span class="sc">$</span>dummy <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="fu">nrow</span>(draws))</span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a>draws_1k<span class="sc">$</span>dummy <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="fu">nrow</span>(draws_1k))</span>
<span id="cb12-53"><a href="#cb12-53" aria-hidden="true" tabindex="-1"></a>g_dummy <span class="ot">&lt;-</span> <span class="st">"Tham số giả (kiểm tra)"</span></span>
<span id="cb12-54"><a href="#cb12-54" aria-hidden="true" tabindex="-1"></a>groups[[g_dummy]] <span class="ot">&lt;-</span> <span class="st">"dummy"</span></span>
<span id="cb12-55"><a href="#cb12-55" aria-hidden="true" tabindex="-1"></a>evppi_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">group =</span> <span class="fu">names</span>(groups), <span class="at">n_par =</span> <span class="fu">lengths</span>(groups),</span>
<span id="cb12-56"><a href="#cb12-56" aria-hidden="true" tabindex="-1"></a>                        <span class="at">method =</span> <span class="fu">vapply</span>(<span class="fu">names</span>(groups), method_of, <span class="st">""</span>), <span class="at">evppi =</span> <span class="cn">NA</span>, <span class="at">r2 =</span> <span class="cn">NA</span>, <span class="at">sd_fitted =</span> <span class="cn">NA</span>,</span>
<span id="cb12-57"><a href="#cb12-57" aria-hidden="true" tabindex="-1"></a>                        <span class="at">evppi_1k =</span> <span class="cn">NA</span>)</span>
<span id="cb12-58"><a href="#cb12-58" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(groups)) {</span>
<span id="cb12-59"><a href="#cb12-59" aria-hidden="true" tabindex="-1"></a>  g <span class="ot">&lt;-</span> <span class="fu">names</span>(groups)[i]</span>
<span id="cb12-60"><a href="#cb12-60" aria-hidden="true" tabindex="-1"></a>  res <span class="ot">&lt;-</span> <span class="fu">evppi_gam</span>(inb_b, <span class="fu">group_X</span>(g, draws))</span>
<span id="cb12-61"><a href="#cb12-61" aria-hidden="true" tabindex="-1"></a>  evppi_tab<span class="sc">$</span>evppi[i] <span class="ot">&lt;-</span> res[[<span class="st">"evppi"</span>]]</span>
<span id="cb12-62"><a href="#cb12-62" aria-hidden="true" tabindex="-1"></a>  evppi_tab<span class="sc">$</span>r2[i] <span class="ot">&lt;-</span> res[[<span class="st">"r2"</span>]]</span>
<span id="cb12-63"><a href="#cb12-63" aria-hidden="true" tabindex="-1"></a>  evppi_tab<span class="sc">$</span>sd_fitted[i] <span class="ot">&lt;-</span> res[[<span class="st">"sd_fitted"</span>]]</span>
<span id="cb12-64"><a href="#cb12-64" aria-hidden="true" tabindex="-1"></a>  evppi_tab<span class="sc">$</span>evppi_1k[i] <span class="ot">&lt;-</span> <span class="fu">evppi_gam</span>(inb_b_1k, <span class="fu">group_X</span>(g, draws_1k))[[<span class="st">"evppi"</span>]]</span>
<span id="cb12-65"><a href="#cb12-65" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-66"><a href="#cb12-66" aria-hidden="true" tabindex="-1"></a>evppi_tab<span class="sc">$</span>share_of_evpi <span class="ot">&lt;-</span> evppi_tab<span class="sc">$</span>evppi <span class="sc">/</span> evpi[[<span class="st">"B"</span>]]</span>
<span id="cb12-67"><a href="#cb12-67" aria-hidden="true" tabindex="-1"></a>evppi_tab<span class="sc">$</span>pop_billion <span class="ot">&lt;-</span> evppi_tab<span class="sc">$</span>evppi <span class="sc">*</span> pf_base <span class="sc">/</span> <span class="fl">1e9</span></span>
<span id="cb12-68"><a href="#cb12-68" aria-hidden="true" tabindex="-1"></a>evppi_tab <span class="ot">&lt;-</span> evppi_tab[<span class="fu">order</span>(evppi_tab<span class="sc">$</span>evppi, <span class="at">decreasing =</span> <span class="cn">TRUE</span>), ]</span>
<span id="cb12-69"><a href="#cb12-69" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(evppi_tab) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb12-70"><a href="#cb12-70" aria-hidden="true" tabindex="-1"></a><span class="co"># Checks: no group is worth more than all parameters together; the dummy is worth ~0</span></span>
<span id="cb12-71"><a href="#cb12-71" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(evppi_tab<span class="sc">$</span>evppi <span class="sc">&lt;=</span> evpi[[<span class="st">"B"</span>]] <span class="sc">*</span> <span class="fl">1.02</span>),</span>
<span id="cb12-72"><a href="#cb12-72" aria-hidden="true" tabindex="-1"></a>          evppi_tab<span class="sc">$</span>evppi[evppi_tab<span class="sc">$</span>group <span class="sc">==</span> g_dummy] <span class="sc">&lt;</span> <span class="fl">0.01</span> <span class="sc">*</span> evpi[[<span class="st">"B"</span>]])</span>
<span id="cb12-73"><a href="#cb12-73" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">setNames</span>(evppi_tab<span class="sc">$</span>evppi <span class="sc">/</span> <span class="fl">1e6</span>, evppi_tab<span class="sc">$</span>group), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Thành công của phác đồ ngắn (VN) 
                                       1.43 
                           SMR sau điều trị 
                                       1.41 
       Hiệu quả BPaLM trong thử nghiệm (RR) 
                                       1.13 
               Diễn tiến lao không điều trị 
                                       1.04 
            Sau bỏ điều trị và điều trị lại 
                                       0.76 
                            Biến cố bất lợi 
                                       0.32 
                  Kết cục chương trình (VN) 
                                       0.28 
                                  Thỏa dụng 
                                       0.27 
Giá thuốc phác đồ ngắn, dài hạn và theo dõi 
                                       0.15 
     aOR phác đồ dài hạn (qua điều trị lại) 
                                       0.02 
     Chi phí khác (thất bại, cuối điều trị) 
                                       0.01 
                     Tham số giả (kiểm tra) 
                                       0.00 </code></pre>
</div>
</div>
<p>Hồi quy thông thường có kém hơn chỉ số dẫn xuất không? Bảng sau so hai cách cho hai nhóm, ở mẫu nhỏ và mẫu lớn.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How good are the regressions for groups of several parameters? For the adverse-event group,</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># compare an additive model of separate smooths s(x1) + ... + s(x4) with the exact derived index,</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># at the small and the large sample. The same for the trial pair: te() on the two</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># proportions versus s() on their ratio.</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>chk_groups <span class="ot">&lt;-</span> <span class="fu">c</span>(g_ae, g_rr)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>est_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">group =</span> chk_groups, <span class="at">naive_method =</span> <span class="fu">c</span>(<span class="st">"4 × s() cộng tính"</span>, <span class="st">"te() hai tỷ lệ"</span>),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">naive_1k =</span> <span class="cn">NA</span>, <span class="at">index_1k =</span> <span class="cn">NA</span>, <span class="at">naive_large =</span> <span class="cn">NA</span>, <span class="at">index_large =</span> <span class="cn">NA</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(chk_groups)) {</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  g <span class="ot">&lt;-</span> chk_groups[i]</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  add <span class="ot">&lt;-</span> g <span class="sc">==</span> g_ae</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  est_tab<span class="sc">$</span>naive_1k[i] <span class="ot">&lt;-</span> <span class="fu">evppi_gam</span>(inb_b_1k, draws_1k[groups[[g]]], <span class="at">additive =</span> add)[[<span class="st">"evppi"</span>]] <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  est_tab<span class="sc">$</span>naive_large[i] <span class="ot">&lt;-</span> <span class="fu">evppi_gam</span>(inb_b, draws[groups[[g]]], <span class="at">additive =</span> add)[[<span class="st">"evppi"</span>]] <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  est_tab<span class="sc">$</span>index_1k[i] <span class="ot">&lt;-</span> evppi_tab<span class="sc">$</span>evppi_1k[evppi_tab<span class="sc">$</span>group <span class="sc">==</span> g] <span class="sc">/</span> <span class="fl">1e6</span>      <span class="co"># computed above</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  est_tab<span class="sc">$</span>index_large[i] <span class="ot">&lt;-</span> evppi_tab<span class="sc">$</span>evppi[evppi_tab<span class="sc">$</span>group <span class="sc">==</span> g] <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(est_tab, <span class="at">digits =</span> <span class="dv">2</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Nhóm"</span>, <span class="st">"Cách hồi quy thông thường"</span>, <span class="st">"Thông thường, N nhỏ"</span>, <span class="st">"Chỉ số dẫn xuất, N nhỏ"</span>,</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"Thông thường, N lớn"</span>, <span class="st">"Chỉ số dẫn xuất, N lớn"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 24%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nhóm</th>
<th style="text-align: left;">Cách hồi quy thông thường</th>
<th style="text-align: right;">Thông thường, N nhỏ</th>
<th style="text-align: right;">Chỉ số dẫn xuất, N nhỏ</th>
<th style="text-align: right;">Thông thường, N lớn</th>
<th style="text-align: right;">Chỉ số dẫn xuất, N lớn</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Biến cố bất lợi</td>
<td style="text-align: left;">4 × s() cộng tính</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">0.32</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hiệu quả BPaLM trong thử nghiệm (RR)</td>
<td style="text-align: left;">te() hai tỷ lệ</td>
<td style="text-align: right;">1.13</td>
<td style="text-align: right;">1.12</td>
<td style="text-align: right;">1.13</td>
<td style="text-align: right;">1.13</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gap of the usual regression relative to the index estimate at the large N, by sample size</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>over_1k <span class="ot">&lt;-</span> est_tab<span class="sc">$</span>naive_1k <span class="sc">/</span> est_tab<span class="sc">$</span>index_large <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>over_large <span class="ot">&lt;-</span> est_tab<span class="sc">$</span>naive_large <span class="sc">/</span> est_tab<span class="sc">$</span>index_large <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(over_1k) <span class="ot">&lt;-</span> <span class="fu">names</span>(over_large) <span class="ot">&lt;-</span> est_tab<span class="sc">$</span>group</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">rbind</span>(<span class="at">small_n =</span> over_1k, <span class="at">large_n =</span> over_large), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Biến cố bất lợi Hiệu quả BPaLM trong thử nghiệm (RR)
small_n           -0.26                                 0.01
large_n            0.02                                 0.00</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># At the small N: how far apart are the two methods, and how far are both from the large-N estimate?</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>gap_methods_1k <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">abs</span>(est_tab<span class="sc">$</span>naive_1k <span class="sc">/</span> est_tab<span class="sc">$</span>index_1k <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>gap_n_1k <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">abs</span>(<span class="fu">c</span>(est_tab<span class="sc">$</span>naive_1k, est_tab<span class="sc">$</span>index_1k) <span class="sc">/</span> <span class="fu">rep</span>(est_tab<span class="sc">$</span>index_large, <span class="dv">2</span>) <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">gap_methods_small_n =</span> gap_methods_1k, <span class="at">gap_to_large_n =</span> gap_n_1k), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>gap_methods_small_n      gap_to_large_n 
               0.05                0.30 </code></pre>
</div>
</div>
<p>Ở 5,000 lần chạy, hai cách lệch nhau tối đa 2%. Ở 1,000 lần, hai cách lệch nhau tối đa 5%, nhưng đều lệch so với ước lượng của mẫu lớn tới 30%: ở đây sai lệch chủ yếu do mẫu nhỏ, không do cách hồi quy. Chỉ số dẫn xuất vẫn đáng dùng: nó đúng theo cấu trúc, nhanh hơn, và không cần chọn số hàm cơ sở.</p>
<p>Khoảng bootstrap cho các nhóm có thể đứng đầu, rồi xếp bậc. Hai nhóm cùng bậc khi khoảng của chúng chồng lấn lên giới hạn dưới của nhóm cao hơn, nghĩa là mẫu này chưa cho phép xếp hạng giữa chúng. Kiểm tra: ước lượng điểm nằm trong khoảng của chính nó (<code>stopifnot</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bootstrap the PSA rows for the groups that could be ranked first: those with an EVPPI of</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># at least half the largest one (the dummy excluded). n_boot resamples each.</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>cand <span class="ot">&lt;-</span> evppi_tab<span class="sc">$</span>group[evppi_tab<span class="sc">$</span>evppi <span class="sc">&gt;=</span> <span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">max</span>(evppi_tab<span class="sc">$</span>evppi) <span class="sc">&amp;</span> evppi_tab<span class="sc">$</span>group <span class="sc">!=</span> g_dummy]</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>evppi_tab<span class="sc">$</span>lo <span class="ot">&lt;-</span> <span class="cn">NA_real_</span>; evppi_tab<span class="sc">$</span>hi <span class="ot">&lt;-</span> <span class="cn">NA_real_</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (j <span class="cf">in</span> <span class="fu">seq_along</span>(cand)) {</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  b <span class="ot">&lt;-</span> <span class="fu">evppi_boot</span>(inb_b, <span class="fu">group_X</span>(cand[j], draws), <span class="at">n_boot =</span> u<span class="sc">$</span>n_boot, <span class="at">seed =</span> u<span class="sc">$</span>seed <span class="sc">+</span> <span class="dv">10</span> <span class="sc">*</span> j)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  evppi_tab<span class="sc">$</span>lo[evppi_tab<span class="sc">$</span>group <span class="sc">==</span> cand[j]] <span class="ot">&lt;-</span> <span class="fu">quantile</span>(b, <span class="fl">0.025</span>, <span class="at">names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  evppi_tab<span class="sc">$</span>hi[evppi_tab<span class="sc">$</span>group <span class="sc">==</span> cand[j]] <span class="ot">&lt;-</span> <span class="fu">quantile</span>(b, <span class="fl">0.975</span>, <span class="at">names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>shown <span class="ot">&lt;-</span> <span class="fu">transform</span>(evppi_tab, <span class="at">evppi =</span> evppi <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>                   <span class="at">ci =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(lo), <span class="st">""</span>, <span class="fu">paste0</span>(<span class="fu">fmt_num</span>(lo <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">2</span>), <span class="st">"–"</span>, <span class="fu">fmt_num</span>(hi <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">2</span>))))</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(shown[, <span class="fu">c</span>(<span class="st">"group"</span>, <span class="st">"n_par"</span>, <span class="st">"method"</span>, <span class="st">"evppi"</span>, <span class="st">"ci"</span>, <span class="st">"r2"</span>, <span class="st">"share_of_evpi"</span>, <span class="st">"pop_billion"</span>)],</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">digits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">1</span>), <span class="at">row.names =</span> <span class="cn">FALSE</span>,</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Nhóm tham số"</span>, <span class="st">"Số tham số"</span>, <span class="st">"Cách ước lượng"</span>, <span class="st">"EVPPI (triệu VNĐ/người)"</span>,</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"Khoảng bootstrap 95%"</span>, <span class="st">"R² của GAM"</span>, <span class="st">"Tỷ lệ so với EVPI"</span>, <span class="st">"EVPPI quần thể (tỷ VNĐ)"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 6%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nhóm tham số</th>
<th style="text-align: right;">Số tham số</th>
<th style="text-align: left;">Cách ước lượng</th>
<th style="text-align: right;">EVPPI (triệu VNĐ/người)</th>
<th style="text-align: left;">Khoảng bootstrap 95%</th>
<th style="text-align: right;">R² của GAM</th>
<th style="text-align: right;">Tỷ lệ so với EVPI</th>
<th style="text-align: right;">EVPPI quần thể (tỷ VNĐ)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Thành công của phác đồ ngắn (VN)</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">s()</td>
<td style="text-align: right;">1.43</td>
<td style="text-align: left;">1.32–1.55</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">50.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">SMR sau điều trị</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">s()</td>
<td style="text-align: right;">1.41</td>
<td style="text-align: left;">1.28–1.54</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">49.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hiệu quả BPaLM trong thử nghiệm (RR)</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">chỉ số dẫn xuất, s()</td>
<td style="text-align: right;">1.13</td>
<td style="text-align: left;">1.00–1.25</td>
<td style="text-align: right;">0.17</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">39.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diễn tiến lao không điều trị</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">te()</td>
<td style="text-align: right;">1.04</td>
<td style="text-align: left;">0.92–1.19</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">36.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sau bỏ điều trị và điều trị lại</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">te()</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: left;">0.63–0.90</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">26.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Biến cố bất lợi</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">chỉ số dẫn xuất, s()</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: left;"></td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">11.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kết cục chương trình (VN)</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">te()</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: left;"></td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">9.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Thỏa dụng</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">te()</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: left;"></td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">9.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Giá thuốc phác đồ ngắn, dài hạn và theo dõi</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">te()</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: left;"></td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">5.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">aOR phác đồ dài hạn (qua điều trị lại)</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">s()</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: left;"></td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chi phí khác (thất bại, cuối điều trị)</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">te()</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: left;"></td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tham số giả (kiểm tra)</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">s()</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: left;"></td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.0</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rank tiers. Groups are taken in order of EVPPI; a group joins the tier of the best group not</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># yet placed if its upper bound reaches that group's lower bound (intervals overlap). Groups in</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># the same tier cannot be ranked against each other with this sample.</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>cand_tab <span class="ot">&lt;-</span> evppi_tab[<span class="sc">!</span><span class="fu">is.na</span>(evppi_tab<span class="sc">$</span>hi), ]</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>tier <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA_integer_</span>, <span class="fu">nrow</span>(cand_tab))</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_len</span>(<span class="fu">nrow</span>(cand_tab))) {</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.na</span>(tier[i])) <span class="cf">next</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  k <span class="ot">&lt;-</span> k <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> i<span class="sc">:</span><span class="fu">nrow</span>(cand_tab)) {</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">is.na</span>(tier[j]) <span class="sc">&amp;&amp;</span> cand_tab<span class="sc">$</span>hi[j] <span class="sc">&gt;=</span> cand_tab<span class="sc">$</span>lo[i]) tier[j] <span class="ot">&lt;-</span> k</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>cand_tab<span class="sc">$</span>tier <span class="ot">&lt;-</span> tier</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>top_group <span class="ot">&lt;-</span> evppi_tab<span class="sc">$</span>group[<span class="dv">1</span>]</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="sc">!</span><span class="fu">anyNA</span>(tier), cand_tab<span class="sc">$</span>group[<span class="dv">1</span>] <span class="sc">==</span> top_group,</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(cand_tab<span class="sc">$</span>lo <span class="sc">&lt;=</span> cand_tab<span class="sc">$</span>evppi), <span class="fu">all</span>(cand_tab<span class="sc">$</span>hi <span class="sc">&gt;=</span> cand_tab<span class="sc">$</span>evppi))</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Which kinds of range stand behind each candidate group?</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>range_kinds <span class="ot">&lt;-</span> <span class="cf">function</span>(g) <span class="fu">unique</span>(RANGE_TYPE_LABELS[spec<span class="sc">$</span>range_type[<span class="fu">match</span>(groups[[g]], spec<span class="sc">$</span>name)]])</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>cand_tab<span class="sc">$</span>basis <span class="ot">&lt;-</span> <span class="fu">vapply</span>(cand_tab<span class="sc">$</span>group, <span class="cf">function</span>(g) <span class="fu">paste</span>(<span class="fu">range_kinds</span>(g), <span class="at">collapse =</span> <span class="st">"; "</span>), <span class="st">""</span>)</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>cand_tab<span class="sc">$</span>on_ci95 <span class="ot">&lt;-</span> <span class="fu">vapply</span>(cand_tab<span class="sc">$</span>group, <span class="cf">function</span>(g) <span class="fu">any</span>(spec<span class="sc">$</span>range_type[<span class="fu">match</span>(groups[[g]], spec<span class="sc">$</span>name)] <span class="sc">==</span> <span class="st">"ci95"</span>), <span class="cn">TRUE</span>)</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(cand_tab[, <span class="fu">c</span>(<span class="st">"group"</span>, <span class="st">"tier"</span>, <span class="st">"basis"</span>)], <span class="at">row.names =</span> <span class="cn">FALSE</span>,</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Nhóm"</span>, <span class="st">"Bậc xếp hạng"</span>, <span class="st">"Loại khoảng bất định của các tham số trong nhóm"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 32%">
<col style="width: 11%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Nhóm</th>
<th style="text-align: right;">Bậc xếp hạng</th>
<th style="text-align: left;">Loại khoảng bất định của các tham số trong nhóm</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Thành công của phác đồ ngắn (VN)</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">phân vị 2.5-97.5% (cỡ mẫu giả định)</td>
</tr>
<tr class="even">
<td style="text-align: left;">SMR sau điều trị</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">KTC 95% mượn từ nghiên cứu khác</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hiệu quả BPaLM trong thử nghiệm (RR)</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">phân vị 2.5-97.5% (từ số đếm)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diễn tiến lao không điều trị</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">khoảng giữa các nghiên cứu; khoảng minh họa</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sau bỏ điều trị và điều trị lại</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">KTC 95% công bố; phân vị 2.5-97.5% (từ số đếm); khoảng minh họa</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ranking with the small sample, for comparison</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>rank_small <span class="ot">&lt;-</span> evppi_tab<span class="sc">$</span>group[<span class="fu">order</span>(evppi_tab<span class="sc">$</span>evppi_1k, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)][<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>rank_large <span class="ot">&lt;-</span> evppi_tab<span class="sc">$</span>group[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">n_candidates =</span> <span class="fu">nrow</span>(cand_tab), <span class="at">n_tiers =</span> <span class="fu">max</span>(tier), <span class="at">candidates_on_published_ci =</span> <span class="fu">sum</span>(cand_tab<span class="sc">$</span>on_ci95))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              n_candidates                    n_tiers 
                         5                          3 
candidates_on_published_ci 
                         1 </code></pre>
</div>
</div>
<p>Nhóm đứng đầu là “Thành công của phác đồ ngắn (VN)”, 1.43 triệu VNĐ mỗi người bệnh, tức 48% EVPI. Khoảng bootstrap chia 5 nhóm đứng đầu thành 3 bậc; bậc 1 gồm “Thành công của phác đồ ngắn (VN)”, “SMR sau điều trị”; trong cùng một bậc thì chưa xếp hạng được. Tham số giả có EVPPI 0.000 triệu VNĐ, đúng như mong đợi; tỷ số chênh của phác đồ dài hạn, chỉ tác động qua đợt điều trị lại, có EVPPI 0.02 triệu VNĐ. Thỏa dụng, dù rất quan trọng cho QALY, có EVPPI nhỏ vì đã được đo chính xác trên một mẫu lớn (Bài 2). Với 1,000 lần chạy, ba nhóm đầu là “Thành công của phác đồ ngắn (VN)”, “SMR sau điều trị”, “Hiệu quả BPaLM trong thử nghiệm (RR)”; với 5,000 lần là “Thành công của phác đồ ngắn (VN)”, “SMR sau điều trị”, “Hiệu quả BPaLM trong thử nghiệm (RR)”. Thứ tự giống nhau ở hai cỡ mẫu.</p>
<p>Vẽ EVPPI theo nhóm. Kiểm tra: mọi thanh nằm bên trái đường EVPI.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>ev_df <span class="ot">&lt;-</span> evppi_tab</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>ev_df<span class="sc">$</span>group <span class="ot">&lt;-</span> <span class="fu">factor</span>(ev_df<span class="sc">$</span>group, <span class="at">levels =</span> <span class="fu">rev</span>(ev_df<span class="sc">$</span>group))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>fig_evppi <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ev_df, <span class="fu">aes</span>(evppi <span class="sc">/</span> <span class="fl">1e6</span>, group)) <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> pal_course[<span class="dv">1</span>], <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">data =</span> ev_df[<span class="sc">!</span><span class="fu">is.na</span>(ev_df<span class="sc">$</span>lo), ], <span class="fu">aes</span>(<span class="at">xmin =</span> lo <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">xmax =</span> hi <span class="sc">/</span> <span class="fl">1e6</span>),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.3</span>, <span class="at">colour =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> evpi[[<span class="st">"B"</span>]] <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">linetype =</span> <span class="st">"22"</span>, <span class="at">colour =</span> pal_course[<span class="dv">2</span>]) <span class="sc">+</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"EVPPI (triệu VNĐ mỗi người bệnh)"</span>, <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Giá trị của thông tin hoàn hảo theo nhóm tham số"</span>,</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Kịch bản B (minh họa), ngưỡng 1 × GDP/người; đường đứt: EVPI; vạch đen: khoảng bootstrap 95%"</span>) <span class="sc">+</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_evppi, <span class="st">"l05-evppi.png"</span>, <span class="at">width =</span> <span class="fl">7.5</span>, <span class="at">height =</span> <span class="fl">4.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l05-evppi.png" class="img-fluid figure-img"></p>
<figcaption>EVPPI theo nhóm tham số, kịch bản B</figcaption>
</figure>
</div>
<p>Trước khi diễn giải thứ tự này, thử ba điều mà PSA không chứa, ở kịch bản B: một giả định cấu trúc của M02 (luật 2: tử vong tích lũy khi dùng BPaLM như phác đồ ngắn), sai lệch số liệu (tử vong bị báo cáo thiếu) và việc không có điều trị lại cho người thất bại hoặc bỏ điều trị (lost to follow-up). Kiểm tra: INB cơ sở của B gần 0; so độ lớn của các dịch chuyển với EVPI và với độ lệch chuẩn do sai số lấy mẫu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># What the PSA does not contain, at scenario B: (1) a structural choice of M02, how the trial RR</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># treats deaths on treatment (rule 2: same cumulative deaths as the short regimen); (2) data bias,</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># under-reported deaths on treatment; (3) no retreatment. Compare the shift in INB with the EVPI</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># and with the spread of E[INB] caused by sampling error in the Vietnamese programme data.</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>shift <span class="ot">&lt;-</span> <span class="cf">function</span>(q) <span class="fu">d_nmb</span>(q) <span class="sc">-</span> <span class="fu">d_nmb</span>(p_b)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>q <span class="ot">&lt;-</span> p_b; q<span class="sc">$</span>bpalm_death_rule <span class="ot">&lt;-</span> <span class="dv">2</span>; shift_rule2 <span class="ot">&lt;-</span> <span class="fu">shift</span>(q)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>q <span class="ot">&lt;-</span> p_b; q<span class="sc">$</span>vn_death <span class="ot">&lt;-</span> p<span class="sc">$</span>vn_death <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> p<span class="sc">$</span>death_unreported); shift_under <span class="ot">&lt;-</span> <span class="fu">shift</span>(q)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>q <span class="ot">&lt;-</span> p_b; q<span class="sc">$</span>retx_rate_failed <span class="ot">&lt;-</span> <span class="dv">0</span>; q<span class="sc">$</span>retx_rate_ltfu <span class="ot">&lt;-</span> <span class="dv">0</span>; shift_noretx <span class="ot">&lt;-</span> <span class="fu">shift</span>(q)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>sd_sampling_vn <span class="ot">&lt;-</span> evppi_tab<span class="sc">$</span>sd_fitted[evppi_tab<span class="sc">$</span>group <span class="sc">==</span> <span class="st">"Kết cục chương trình (VN)"</span>]</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">base_inb_b_million =</span> <span class="fu">d_nmb</span>(p_b) <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">shift_death_rule2 =</span> shift_rule2 <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">shift_underreport =</span> shift_under <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">shift_no_retreatment =</span> shift_noretx <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">sd_from_sampling_vn =</span> sd_sampling_vn <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">evpi_b =</span> evpi[[<span class="st">"B"</span>]] <span class="sc">/</span> <span class="fl">1e6</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  base_inb_b_million    shift_death_rule2    shift_underreport 
               -0.18               -33.01                10.94 
shift_no_retreatment  sd_from_sampling_vn               evpi_b 
               16.85                 1.20                 3.01 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Thứ tự này chưa phải ưu tiên nghiên cứu thật">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Thứ tự này chưa phải ưu tiên nghiên cứu thật
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>Khoảng bất định là giả định.</strong> Chỉ 1 trong 5 nhóm đứng đầu có tham số dựa trên KTC 95% công bố. Cơ sở của khoảng bất định từng nhóm: “Thành công của phác đồ ngắn (VN)” (phân vị 2.5-97.5% (cỡ mẫu giả định)); “SMR sau điều trị” (KTC 95% mượn từ nghiên cứu khác); “Hiệu quả BPaLM trong thử nghiệm (RR)” (phân vị 2.5-97.5% (từ số đếm)); “Diễn tiến lao không điều trị” (khoảng giữa các nghiên cứu; khoảng minh họa); “Sau bỏ điều trị và điều trị lại” (KTC 95% công bố; phân vị 2.5-97.5% (từ số đếm); khoảng minh họa). Nhóm đứng đầu dựa trên một cỡ nhóm suy ngược thô (Bài 2): con số thật nhiều khả năng có trong toàn văn bài báo mà tóm tắt không nêu. Đọc toàn văn có thể là “nghiên cứu” rẻ nhất. Khoảng càng rộng thì EVPPI càng lớn.</li>
<li><strong>Cấu trúc mô hình.</strong> Luật 2 đổi INB của B -33.0 triệu VNĐ, bằng 11.0 lần EVPI (3.01 triệu VNĐ); tắt điều trị lại đổi 16.8 triệu. Một giả định cấu trúc có thể đổi giá trị kỳ vọng của quyết định nhiều hơn toàn bộ bất định tham số, mà EVPPI không thấy được trừ khi giả định đó được tham số hóa <span class="citation" data-cites="bojke2009characterizing">(<a href="#ref-bojke2009characterizing" role="doc-biblioref">Bojke và c.s. 2009</a>)</span>.</li>
<li><strong>Sai lệch số liệu nằm ngoài PSA.</strong> Tử vong bị báo cáo thiếu đổi INB của B 10.9 triệu VNĐ, trong khi độ lệch chuẩn của <span class="math inline">\(E[\text{INB}]\)</span> do sai số lấy mẫu của kết cục chương trình chỉ 1.2 triệu VNĐ; EVPPI của nhóm đó (0.28 triệu VNĐ) đánh giá thấp giá trị của việc sửa sai lệch.</li>
</ol>
<p>Dùng bài này để học cách làm. Muốn ưu tiên nghiên cứu thật, hãy thay khoảng giả định bằng số liệu thật, tham số hóa các giả định cấu trúc và đưa sai lệch vào mô hình.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Mẹo thực hành">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mẹo thực hành
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Tính EVPI trước. Nếu EVPI quần thể nhỏ hơn chi phí của một nghiên cứu nhỏ, dừng lại; không cần EVPPI.</li>
<li>Nhóm tham số theo <strong>nghiên cứu có thể làm</strong>, không theo vị trí trong code: một đoàn hệ theo dõi đo cùng lúc tử vong sau bỏ điều trị và tỷ lệ quay lại điều trị.</li>
<li>In R² của mỗi GAM cạnh EVPPI. R² gần 0 kèm EVPPI lớn là dấu hiệu khớp quá mức.</li>
<li>Luôn thêm một tham số giả vào bảng EVPPI như một phép thử âm tính.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Lỗi thường gặp">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lỗi thường gặp
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Cộng EVPPI của các nhóm để được EVPI:</strong> EVPPI không cộng được; bài tập 2 cho thấy điều đó.</li>
<li><strong>Báo cáo EVPI mỗi người mà không có EVPI quần thể:</strong> người tài trợ nghiên cứu cần so với chi phí nghiên cứu, tức là cần con số quần thể (cận trên theo số người).</li>
<li><strong>Tính VOI cho tham số không có trong PSA:</strong> giá đàm phán được cố định, nên EVPPI của nó không xác định; bất định cấu trúc và sai lệch số liệu cũng không có trong EVPPI trừ khi được tham số hóa.</li>
<li><strong>Coi EVPPI là giá trị của một nghiên cứu cụ thể:</strong> EVPPI là mức trần; nghiên cứu thật có cỡ mẫu hữu hạn và đáng giá ít hơn (EVSI).</li>
</ul>
</div>
</div>
</section>
<section id="bài-tập" class="level2">
<h2 class="anchored" data-anchor-id="bài-tập">Bài tập</h2>
<ol type="1">
<li><strong>(Dễ)</strong> Vì sao EVPI của kịch bản A bằng 0? Kiểm tra bằng hai con số.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 1: why is the EVPI of scenario A zero?</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">p_bpalm_optimal =</span> <span class="fu">mean</span>(inb_a <span class="sc">&gt;</span> <span class="dv">0</span>), <span class="at">min_inb_million =</span> <span class="fu">min</span>(inb_a) <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">evpi_a_vnd =</span> evpi[[<span class="st">"A"</span>]]), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>p_bpalm_optimal min_inb_million      evpi_a_vnd 
          1.000          39.279           0.000 </code></pre>
</div>
</div>
<p>BPaLM là lựa chọn tối ưu ở 100% số lần chạy, và INB nhỏ nhất vẫn dương (39.3 triệu VNĐ). Khi một chiến lược thắng ở mọi lần chạy, <span class="math inline">\(E[\max(0, \text{INB})] = E[\text{INB}]\)</span>, nên EVPI bằng 0: biết thêm không đổi được lựa chọn.</p>
</div>
</div>
</div>
<ol start="2" type="1">
<li><strong>(Vừa)</strong> Tính EVPPI riêng cho tỷ lệ kết cục bất lợi của nhánh BPaLM và của nhánh chăm sóc chuẩn, rồi so với EVPPI của cả nhóm (RR). Tổng có bằng EVPPI của nhóm không?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 2: EVPPI is not additive. The two trial proportions one at a time versus together</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>e_bpalm <span class="ot">&lt;-</span> <span class="fu">evppi_gam</span>(inb_b, draws[<span class="st">"unf_bpalm_trial"</span>])[[<span class="st">"evppi"</span>]]</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>e_soc <span class="ot">&lt;-</span> <span class="fu">evppi_gam</span>(inb_b, draws[<span class="st">"unf_soc_trial"</span>])[[<span class="st">"evppi"</span>]]</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>e_grp <span class="ot">&lt;-</span> evppi_tab<span class="sc">$</span>evppi[evppi_tab<span class="sc">$</span>group <span class="sc">==</span> g_rr]</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">unf_bpalm_trial =</span> e_bpalm, <span class="at">unf_soc_trial =</span> e_soc, <span class="at">sum =</span> e_bpalm <span class="sc">+</span> e_soc, <span class="at">group =</span> e_grp) <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>unf_bpalm_trial   unf_soc_trial             sum           group 
          0.999           0.413           1.412           1.125 </code></pre>
</div>
</div>
<p>Tổng hai EVPPI riêng là 1.41 triệu VNĐ, khác EVPPI của nhóm (1.13 triệu VNĐ). Biết chắc một tỷ lệ đã cho biết phần lớn RR trong nhiều lần chạy, nên phần đóng góp thêm của tỷ lệ thứ hai nhỏ hơn giá trị riêng của nó. Vì vậy hãy tính EVPPI cho đúng nhóm tham số mà một nghiên cứu sẽ đo; một thử nghiệm mới đo cả hai nhánh cùng lúc.</p>
</div>
</div>
</div>
<ol start="3" type="1">
<li><strong>(Khó)</strong> Ước lượng EVPPI cũng có sai số Monte Carlo. Dùng bootstrap trên các hàng PSA để tính khoảng 95% cho EVPPI của hiệu quả thử nghiệm (RR) ở mẫu nhỏ và mẫu lớn. Khoảng rộng ra bao nhiêu lần? So với căn bậc hai của tỷ số hai cỡ mẫu.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 3: how much wider is the bootstrap interval of the trial-effect EVPPI (s() on the RR)</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># with the small sample?</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>b_small <span class="ot">&lt;-</span> <span class="fu">evppi_boot</span>(inb_b_1k, <span class="fu">group_X</span>(g_rr, draws_1k), <span class="at">n_boot =</span> u<span class="sc">$</span>n_boot, <span class="at">seed =</span> u<span class="sc">$</span>seed <span class="sc">+</span> <span class="dv">3</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>b_large <span class="ot">&lt;-</span> <span class="fu">evppi_boot</span>(inb_b, <span class="fu">group_X</span>(g_rr, draws), <span class="at">n_boot =</span> u<span class="sc">$</span>n_boot, <span class="at">seed =</span> u<span class="sc">$</span>seed <span class="sc">+</span> <span class="dv">4</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>ci_small <span class="ot">&lt;-</span> <span class="fu">quantile</span>(b_small, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">names =</span> <span class="cn">FALSE</span>) <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>ci_large <span class="ot">&lt;-</span> <span class="fu">quantile</span>(b_large, <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">names =</span> <span class="cn">FALSE</span>) <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">rbind</span>(<span class="at">small_n =</span> <span class="fu">c</span>(ci_small, <span class="at">width =</span> <span class="fu">diff</span>(ci_small)), <span class="at">large_n =</span> <span class="fu">c</span>(ci_large, <span class="at">width =</span> <span class="fu">diff</span>(ci_large))), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  width
small_n 0.85 1.39  0.53
large_n 1.02 1.27  0.25</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">ratio_of_widths =</span> <span class="fu">diff</span>(ci_small) <span class="sc">/</span> <span class="fu">diff</span>(ci_large), <span class="at">sqrt_ratio_of_n =</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(inb_b) <span class="sc">/</span> <span class="fu">length</span>(inb_b_1k))), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ratio_of_widths sqrt_ratio_of_n 
           2.14            2.24 </code></pre>
</div>
</div>
<p>Khoảng bootstrap 95% là 0.85–1.39 triệu VNĐ với 1,000 lần chạy, và 1.02–1.27 với 5,000 lần. Khoảng hẹp đi 2.1 lần, gần <span class="math inline">\(\sqrt{N_{\text{lớn}}/N_{\text{nhỏ}}}\)</span> = 2.2. Khi hai nhóm có EVPPI chênh nhau ít hơn độ rộng này, đừng xếp hạng chúng; hãy tăng số lần chạy PSA.</p>
</div>
</div>
</div>
</section>
<section id="tài-liệu-tham-khảo" class="level2">
<h2 class="anchored" data-anchor-id="tài-liệu-tham-khảo">Tài liệu tham khảo</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-ades2004expected" class="csl-entry" role="listitem">
Ades, A. E., G. Lu, và K. Claxton. 2004. <span>“Expected value of sample information calculations in medical decision modeling”</span>. <em>Medical Decision Making</em> 24 (2): 207–27. <a href="https://doi.org/10.1177/0272989X04263162">https://doi.org/10.1177/0272989X04263162</a>.
</div>
<div id="ref-daibieunhandan2025chamdut" class="csl-entry" role="listitem">
Báo Đại biểu Nhân dân. 2025. <span>“Thứ trưởng <span>Bộ Y tế</span> Trần Văn Thuấn nhấn mạnh: <span>‘Chấm dứt bệnh lao là mục tiêu cao cả’</span>”</span>. 24 Tháng Ba 2025. <a href="https://daibieunhandan.vn/thu-truong-bo-y-te-tran-van-thuan-nhan-manh-cham-dut-benh-lao-la-muc-tieu-cao-ca-10362721.html">https://daibieunhandan.vn/thu-truong-bo-y-te-tran-van-thuan-nhan-manh-cham-dut-benh-lao-la-muc-tieu-cao-ca-10362721.html</a>.
</div>
<div id="ref-bojke2009characterizing" class="csl-entry" role="listitem">
Bojke, Laura, Karl Claxton, Mark Sculpher, và Stephen Palmer. 2009. <span>“Characterizing structural uncertainty in decision analytic models: a review and application of methods”</span>. <em>Value in Health</em> 12 (5): 739–49. <a href="https://doi.org/10.1111/j.1524-4733.2008.00502.x">https://doi.org/10.1111/j.1524-4733.2008.00502.x</a>.
</div>
<div id="ref-claxton1999irrelevance" class="csl-entry" role="listitem">
Claxton, K. 1999. <span>“The irrelevance of inference: a decision-making approach to the stochastic evaluation of health care technologies”</span>. <em>Journal of Health Economics</em> 18 (3): 341–64. <a href="https://doi.org/10.1016/s0167-6296(98)00039-3">https://doi.org/10.1016/s0167-6296(98)00039-3</a>.
</div>
<div id="ref-fenwick2020value" class="csl-entry" role="listitem">
Fenwick, Elisabeth, Lotte Steuten, Saskia Knies, Salah Ghabri, Anirban Basu, James F. Murray, Hendrik Erik Koffijberg, Mark Strong, Gillian D. Sanders Schmidler, và Claire Rothery. 2020. <span>“Value of information analysis for research decisions – an introduction: report 1 of the <span>ISPOR</span> Value of Information Analysis Emerging Good Practices Task Force”</span>. <em>Value in Health</em> 23 (2): 139–50. <a href="https://doi.org/10.1016/j.jval.2020.01.001">https://doi.org/10.1016/j.jval.2020.01.001</a>.
</div>
<div id="ref-jackson2024voi" class="csl-entry" role="listitem">
Jackson, Christopher, và Anna Heath. 2024. <span>“voi: Expected Value of Information. <span>R</span> package version 1.0.3”</span>. <a href="https://doi.org/10.32614/CRAN.package.voi">https://doi.org/10.32614/CRAN.package.voi</a>.
</div>
<div id="ref-kunst2020computing" class="csl-entry" role="listitem">
Kunst, Natalia, Edward C. F. Wilson, David Glynn, Fernando Alarid-Escudero, Gianluca Baio, Alan Brennan, Michael Fairley, và c.s. 2020. <span>“Computing the expected value of sample information efficiently: practical guidance and recommendations for four model-based methods”</span>. <em>Value in Health</em> 23 (6): 734–42. <a href="https://doi.org/10.1016/j.jval.2020.02.010">https://doi.org/10.1016/j.jval.2020.02.010</a>.
</div>
<div id="ref-nguyen2026from" class="csl-entry" role="listitem">
Nguyen, Thi Mai Phuong, Van Luong Dinh, Binh Hoa Nguyen, Thi Thanh Thuy Hoang, Viet Nhung Nguyen, Steven Callens, và Tom Decroo. 2026. <span>“From trials to programmatic scale-up: treatment outcomes of rifampicin-resistant tuberculosis during transition to short oral regimens in <span>Vietnam</span> (2021–2022)”</span>. <em>International Journal of Infectious Diseases</em> 163: 108222. <a href="https://doi.org/10.1016/j.ijid.2025.108222">https://doi.org/10.1016/j.ijid.2025.108222</a>.
</div>
<div id="ref-rothery2020value" class="csl-entry" role="listitem">
Rothery, Claire, Mark Strong, Hendrik Erik Koffijberg, Anirban Basu, Salah Ghabri, Saskia Knies, James F. Murray, Gillian D. Sanders Schmidler, Lotte Steuten, và Elisabeth Fenwick. 2020. <span>“Value of information analytical methods: report 2 of the <span>ISPOR</span> Value of Information Analysis Emerging Good Practices Task Force”</span>. <em>Value in Health</em> 23 (3): 277–86. <a href="https://doi.org/10.1016/j.jval.2020.01.004">https://doi.org/10.1016/j.jval.2020.01.004</a>.
</div>
<div id="ref-strong2014estimating" class="csl-entry" role="listitem">
Strong, Mark, Jeremy E. Oakley, và Alan Brennan. 2014. <span>“Estimating multiparameter partial expected value of perfect information from a probabilistic sensitivity analysis sample: a nonparametric regression approach”</span>. <em>Medical Decision Making</em> 34 (3): 311–26. <a href="https://doi.org/10.1177/0272989X13505910">https://doi.org/10.1177/0272989X13505910</a>.
</div>
<div id="ref-wilson2015practical" class="csl-entry" role="listitem">
Wilson, Edward C. F. 2015. <span>“A practical guide to value of information analysis”</span>. <em>PharmacoEconomics</em> 33 (2): 105–21. <a href="https://doi.org/10.1007/s40273-014-0219-x">https://doi.org/10.1007/s40273-014-0219-x</a>.
</div>
<div id="ref-wood2011fast" class="csl-entry" role="listitem">
Wood, Simon N. 2011. <span>“Fast stable restricted maximum likelihood and marginal likelihood estimation of semiparametric generalized linear models”</span>. <em>Journal of the Royal Statistical Society Series B: Statistical Methodology</em> 73 (1): 3–36. <a href="https://doi.org/10.1111/j.1467-9868.2010.00749.x">https://doi.org/10.1111/j.1467-9868.2010.00749.x</a>.
</div>
<div id="ref-who2026rrestimates" class="csl-entry" role="listitem">
World Health Organization. 2026. <span>“Global tuberculosis programme: <span>MDR/RR-TB</span> burden estimates by country and year (variable e_inc_rr_num)”</span>. 2026. <a href="https://extranet.who.int/tme/generateCSV.asp?ds=mdr_rr_estimates">https://extranet.who.int/tme/generateCSV.asp?ds=mdr_rr_estimates</a>.
</div>
</div>
<div class="video-script">
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kịch bản video (~15 phút)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Slide</th>
<th>Lời giảng chính</th>
<th>Hình/Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Câu hỏi thứ hai</td>
<td>mở rộng BPaLM ngay, hay chờ một nghiên cứu trong nước?</td>
<td>callout đầu bài</td>
</tr>
<tr class="even">
<td>2</td>
<td>EVPI</td>
<td>chọn đúng ở từng lần chạy trừ chọn theo kỳ vọng; bằng tổn thất kỳ vọng</td>
<td>công thức</td>
</tr>
<tr class="odd">
<td>3</td>
<td>EVPI hai kịch bản</td>
<td>A: 0 VNĐ; B có giá trị, đỉnh ở ngưỡng hòa vốn; phương án không bao giờ thắng không thêm gì</td>
<td><code>figs/l05-evpi.png</code></td>
</tr>
<tr class="even">
<td>4</td>
<td>EVPI quần thể</td>
<td>người bệnh mỗi năm × thời gian, có chiết khấu; ba mức số người; cận trên</td>
<td>chunk <code>l05-pop</code></td>
</tr>
<tr class="odd">
<td>5</td>
<td>EVPPI là gì</td>
<td>biết chắc một nhóm tham số; ưu tiên nghiên cứu</td>
<td>công thức</td>
</tr>
<tr class="even">
<td>6</td>
<td>EVPPI bằng hồi quy</td>
<td>E[INB | φ] là hàm hồi quy; GAM <code>s()</code>, <code>te()</code>, chỉ số dẫn xuất (RR, biến cố bất lợi)</td>
<td>chunk <code>l05-evppi</code></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Hai cách hồi quy</td>
<td>chỉ số dẫn xuất so với hồi quy thông thường; mẫu nhỏ và lớn</td>
<td>chunk <code>l05-ae-check</code></td>
</tr>
<tr class="even">
<td>8</td>
<td>Khoảng bootstrap và bậc</td>
<td>chỉ xếp hạng khi khoảng không chồng lấn</td>
<td>chunk <code>l05-boot</code>, <code>figs/l05-evppi.png</code></td>
</tr>
<tr class="odd">
<td>9</td>
<td>Hai phép thử</td>
<td>EVPPI ≤ EVPI; tham số giả ≈ 0</td>
<td>chunk <code>l05-evppi</code></td>
</tr>
<tr class="even">
<td>10</td>
<td>Không cộng được</td>
<td>hai tỷ lệ của thử nghiệm so với RR</td>
<td>bài tập 2</td>
</tr>
<tr class="odd">
<td>11</td>
<td>Vì sao chưa phải ưu tiên thật</td>
<td>cỡ nhóm suy ngược; luật áp RR cho tử vong; báo cáo thiếu</td>
<td>khung cảnh báo</td>
</tr>
<tr class="even">
<td>12</td>
<td>EVSI và ENBS</td>
<td>nghiên cứu cụ thể, cỡ mẫu n; trừ chi phí</td>
<td>sơ đồ Mermaid</td>
</tr>
<tr class="odd">
<td>13</td>
<td>Tổng kết M03</td>
<td>OWSA → PSA → CEAC → VOI; tiếp theo M04</td>
<td>—</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" class="pagination-link" aria-label="Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../kb/m04-microsimulation/index.html" class="pagination-link" aria-label="M04 · Mô phỏng vi mô (microsimulation)">
        <span class="nav-page-text">M04 · Mô phỏng vi mô (microsimulation)</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>