---
title: "Chiếc lốp vá"
date: 2023-06-20
categories: ["Book Review", "Random thoughts"]
tags: ["Book Review", "love", "mind wandering"]
lang-post: VI
---

> *“Chúng ta đi qua đời này bằng những chiếc lốp vá, đời ai chẳng vài lần dính đinh. **Muốn yêu thương chân thành, chớ bỏ qua từng điều nhỏ bé…”*

Hôm nay mình quyết định lạc vào xứ sở mộng mơ của tác giả Minh Đào. Anh là sáng lập của Trạm Đọc, dự án Đại Học Tự Học. Mình đã theo dõi anh trên [Facebook](https://www.facebook.com/mdaongoc) từ khá lâu nên đợt sách mới ra có mua nhưng chưa đọc, giờ mới đến lúc.

## Khi người ấy nói lời yêu, có rất nhiều điều bạn nên nghĩ – Minh Đào

Có một loại tình cảm lớn hơn cả tình yêu, đó là tình thương. Người yêu bạn vẫn có thể khiến bạn đau, nhưng người thương bạn vì bạn mà chịu đau. Yêu mang tính sở hữu. Thương mang tính quan sát. Bạn ngắm hoa mà không bẻ hoa. Hoa vẫn thơm, dù bạn không được ngửi mùi. Có hai loại niềm vui: vui vì mình vui, và vui khi thấy người khác được vui. Hạnh phúc lớn nhất của người tặng quà là thấy người nhận quà hạnh phúc. Thất bại lớn khi yêu là không thể làm người mình yêu hạnh phúc. Tình yêu sinh ra những con người ích kỉ nhất: “Phải có em, dù một lần trong đời”, nhưng cũng tạo ra những con người bao dung nhất: “Mong em hạnh phúc”.

Đôi khi cách tốt nhất để giữ một thứ là từ bỏ nó. Nhớ nghĩa là quên bớt đi, 80% những nội dung không liên quan bị gạt ra lề và chỉ 20% thật sự ấn tượng được đọng lại trong đầu bạn. Và cách cuộc tình kết thúc thế nào sẽ quyết định nó được nhớ lại ra sao. Sẽ toàn là kỉ niệm vui, nếu chia tay trong thanh thản hay sẽ toàn là nỗi buồn, nếu chia tay trong thù hận. Trong tình yêu, không có sự thật. Hãy nói thật theo cách của mình, và mở lòng cho những sự thật khác. Có lẽ thứ tử tế nhất mà những người yêu nhau có thể làm cho nhau là tự thổi còi dừng cuộc chơi khi họ không còn muốn chơi. “Muộn rồi, mình về thôi nhỉ?” – dù bạn đã muốn đứng dậy từ cả tiếng trước rồi.

Những kẻ không tin người thì giữ hạnh phúc độc quyền vào tay mình để không một ai có thể làm họ đau. Những kẻ tin người thì dám “góp gạo thổi cơm” với người khác, dù hiểu rằng tình cảm luôn là một canh bạc. Đã là canh bạc, thì cách duy nhất để khôn ngoan là đừng chơi.

Vì biết rằng mọi chuyện rồi sẽ rất khó khăn, ai rồi cũng sẽ phải già đi, sống là rất cô đơn, bởi ta thương nhau nên ở cạnh nhau. Có lẽ đó là lí do đáng giá duy nhất mà người cần đến người.

Nhưng, lỡ như có điều gì không may xảy đến, đừng tự trách bản thân mình.

Đời người ngắn ngủi, đừng sống mãi trong hồi ức.

Rating: 8.0
