---
title: "Valuable Lessons From 2020"
date: 2021-01-01
categories: ["Book Review", "Featured", "Random thoughts"]
tags: ["Book Review", "COVID-19", "Productivity"]
lang-post: EN/VI
---


::: {.lang-vi}
The previous year was marked by a plethora of changes, both externally and within my own environment. It was a one-of-a-kind chapter lived in the midst of chaos, with the overwhelming presence of COVID-19, from which I gleaned a plethora of observations and insights.

A heightened awareness has sparked a stronger attachment to the work I do. Meaningful experiences shared with my family, my colleagues, cherished companions, and mentors over the last year have left an indelible mark of immeasurable value.

Throughout the year 2020, my dedication to the habit of reading grew stronger. Using Goodreads as a tracking tool, I jot down reviews after each book and set a goal of 30 reads.

Surprisingly, as I reflect today, I have exceeded this goal by more than 200% (reading 65 books), occasionally ranking among Vietnam’s top #10 reviewers on Goodreads!

In retrospect, this habit appears to have illuminated many positive aspects of life. While books cannot replace real-life experiences, they can help to enrich them.

Here are the five most remarkable lessons I learned from my reading over the last year. To honor their authenticity, I have kept the titles in their original language (i.e., English). Those interested can find the Vietnamese translations conveniently under the original titles.

## “The Unfair Advantage” by Ash Ali and Hasan Kubba

In times of self-doubt and inferiority, this book drew me out of my shell and revealed the idea that everyone has some “unfair” advantage that sets them apart. This individuality varies, encompassing characteristics such as height, appearance, intelligence, kindness, or profound selflessness. The message is clear: don’t focus solely on your weaknesses, and don’t compare them to the strengths of others. Determine and cultivate your unique “unfair” advantage, and strive for continuous growth!

## “The Art of Loving” and “To Have or to Be” by Erich Fromm

My relationships have frequently reached a standstill. I scoured books and the wisdom of other travelers for answers. The interdependence of “having” and “being” was the most important lesson I discovered. If you want to have good friendships, you must first learn to be a good friend. A profound realization dawned on me: love is like a delicate glass sphere, exquisite yet fragile. It never fully recovers its original wholeness after being shattered and reassembled.

## “Justice: What’s the Right Thing to Do?” by Michael J. Sandel

Mr. Sandel’s work helped to illuminate my path, which was frequently befuddled by questions of justice and fairness. Justice is more than just right and wrong; it can take many forms, including “horizontal equity” and “vertical justice.” To evaluate the legitimacy of justice, one must avoid simplistic categorizations and instead employ multiple perspectives, evaluative tools, experiential insights, and investigate the reasoning behind judgments. To understand an elephant, one must fully engage with it, refraining from passing judgment solely on the basis of touching its trunk or ears!

## Tara Westover, “Educated”

This book was recommended to me by Bill Gates. Tara’s extraordinary journey from her Idaho hometown to a PhD at Cambridge was not without sacrifices. Along with formal education, she learned the art of learning by embracing help from others and, most importantly, accepting the inevitability of trade-offs.

## “Social: Why Our Brains Are Wired to Connect” by Matthew D. Lieberman and “Altruism” by Ricard Matthieu

While food, shelter, and sustenance help with mere survival, human interaction, or society, helps with true living. Isolation is a dangerous situation for anyone. Living in a close-knit community promotes safety, protection, and shared experiences. Emotions are contagious; personal contentment is essential for fostering a joyful community. Kindness, forgiveness, meditation, and controlling one’s anger are the foundations for achieving mental tranquillity.

I am now ready for 2021. Let’s get the ball rolling !!

---

# Những điều hay nhất đã học được trong năm 2020.

Năm vừa rồi là một năm với quá nhiều biến động, cả môi trường bên ngoài lẫn bên trong con người mình. Đó là năm hiếm hoi mình được sống trong thời kỳ hỗn loạn, với COVID-19, nhờ đó cũng quan sát và học thêm được rất nhiều điều.

Sự vững vàng hơn trong nhận thức giúp mình càng yêu hơn những công việc mình làm. Những trải nghiệm đầy ý nghĩa trong năm qua cùng với gia đình, Y học Cộng đồng, với bạn bè, với những anh, chị, thầy, cô mình yêu quý là vô giá và không thể nào quên.

Suốt năm 2020, mình cũng kiên trì hơn với thói quen đọc sách. Mình sử dụng Goodreads làm công cụ theo dõi, viết bình luận sau mỗi quyển, và đặt mục tiêu 30 quyển. Thế mà hôm nay ngồi lục cục mở xem lại, mình đã đọc được hơn 200% mục tiêu rồi (65 quyển), có lúc còn vào top #10 reviewers của Việt Nam! 😊

Ngẫm nghĩ lại, hình như chính thói quen này giúp mình nhận ra rất nhiều điều hay ho trong cuộc sống. Đọc sách không thay thế được trải nghiệm thực tế, nhưng sách giúp nâng cao trải nghiệm của bản thân.
Sẵn đây, mình lưu lại năm điều hay nhất mình đã đọc được trong năm qua. Mình để tên sách gốc để tôn trọng nguyên bản, và ai quan tâm cũng dễ tìm bản tiếng Việt theo tên gốc.

## Ash Ali, Hasan Kubba, “The Unfair Advantage”.

Cũng có nhiều thời điểm mình cảm thấy tự ti và thua kém. Quyển sách đã kéo mình ra khỏi kén, giúp mình nhận ra luôn có một số lợi thế bất công khiến mình trở nên nổi bật so với người khác. Lợi thế ấy khác nhau ở mỗi người, có thể là chiều cao vượt trội, hình thể đẹp đẽ, trí thông minh, lòng tốt bụng hay vị tha tột cùng. Đừng chỉ tập trung vào điểm yếu của bản thân. Đừng so sánh điểm yếu của mình với điểm mạnh của người khác. Hãy tìm ra lợi thế “bất công” của mình, tập trung vào đó để ngày càng tốt hơn và tốt hơn nhé!

## Erich Fromm, “The Art of Loving” và “To Have or to Be”

Nhiều lúc, mối quan hệ của mình rơi vào bế tắc. Mình đã tìm đến những quyển sách và những chia sẻ của những anh, chị đi trước. “To have” và “To be” nên đi kèm với nhau, muốn có một người bạn tốt, bản thân mình hãy trở thành một người bạn tốt trước đã. Mình nhận ra một điều rất chí mạng: Tình cảm giống như là những quả bóng thuỷ tinh đẹp đẽ nhưng mỏng manh dễ vỡ, một khi đã làm rơi, dù có nhặt lên và ghép lại cũng sẽ không bao giờ toàn vẹn được như lúc đầu.

## Michael J. Sandel, “Justice: What’s the Right Thing to Do?”

Nhiều lúc mình vẫn mông lung với câu hỏi: “Công lý là gì? Thế nào mới là công bằng?”. Thầy Sandel đã giúp mình phần nào giải quyết câu hỏi này. Công lý không đơn giản chỉ là phán xét đúng, sai. Công bằng cũng được phân chia ra nhiều loại, “công bằng ngang”, “công bằng dọc”. Muốn đánh giá công lý có thật hay không không đơn giản chỉ ở cảm giác đúng sai, bản thân mình phải có thật nhiều góc nhìn, nhiều công cụ đánh giá và nhiều trải nghiệm thực tế cũng như tìm hiểu những lý do ẩn khuất đằng sau. Xem voi thì phải xem đầy đủ, đừng chỉ sờ vòi sờ tai rồi phán xét nhé!

## Tara Westower, “Educated”

Mình đọc quyển này vì Bill Gates gợi ý thôi (he he 😃) Trong suốt hành trình gian khổ từ vùng quê Idaho của Tara đến khi tốt nghiệp tiến sĩ tại Cambridge, luôn luôn có một cái giá mà Tara phải đánh đổi. Cô đã học cách học, cách chấp nhận sự giúp đỡ của mọi người và cuối cùng nhưng không kém phần quan trọng, biết chấp nhận đánh đổi.

## Matthew D. Lieberman, “Social: Why Our Brains Are Wired to Connect” và Ricard Matthieu, “Altruism”

Đồ ăn, thức uống, nơi ở giúp con người tồn tại. Nhưng tương tác giữa người và người, hay rộng hơn là xã hội, mới giúp người ta thực sự được sống. Khó có ai forever alone cho được! Sống trong một cộng đồng thân mật tạo cho ta cảm giác an toàn, được che chở, được sẻ chia. Cảm xúc là một thứ lây lan mạnh mẽ. Để xây dựng một cộng đồng hạnh phúc, bản thân chúng ta phải hạnh phúc trước. Lòng tốt, sự vị tha, thực hành thiền định, không sân si… tất cả những điều này là căn bản để có được một tâm hồn an yên.

Tôi sẵn sàng rồi, 2021 ei!
:::

::: {.lang-en}
*(English version coming soon.)*
:::

