---
title: "The Circle of Influence"
date: 2023-08-12
categories: ["Book Review", "Featured", "Random thoughts", "Self-dev"]
lang-post: EN/VI
---


::: {.lang-vi}
During my childhood, my bookcase had a collection of stories about renowned scientists, through which I learned about the fascinating beginnings of countless amazing innovations, many of which occurred by coincidence. Notable examples include Flemming’s unintentional discovery of the antibiotic Penicillin, Rontgen’s X-rays, Nobel’s dynamite, and, farther back, Archimedes’ bathtub eureka moment and Newton’s chance encounter with a falling apple.

I frequently ask myself, *“Why did fortune favor them?”*

My query evolved as I grew older: *“Why did the apple choose to fall on Newton’s head rather than any ordinary person’s?”* This latter question is far easier to answer than the former, because the apple’s fall is a constant event.

This prompted another thought: *“What if the Penicillium notatum culture dish had ended up in the hands of a housekeeper? What if, after a long day at work, a laborer came home to relax in a full bathtub that accidently overflowed to the outside?”* Would they have discovered penicillin or discovered Archimedes’ idea of buoyancy?”

Definitely not.

Scientists are not the only ones who benefit from good fortune. It blesses people all throughout the world, albeit at various times. The crucial aspect is whether people recognize or are appropriately prepared for these periods of fortune. Scientists, like the rest of us, are not always endowed with brilliance or natural exceptionality, and they are often unclear about the timing of serendipitous events. However, when the opportunity presents itself, they are ready to grasp it, having meticulously prepared themselves for months, years, or even decades.

Furthermore, the extended period of preparation increases their chances of luck. Consider a figurative “downpour of opportunity” sweeping across a broad landscape where everyone lives. Those that investigate a bigger area undoubtedly boost their chances of finding it.

Indeed, *a significant fraction of these seemingly unintentional accomplishments are the result of deliberate preparation*.

---

Hồi còn nhỏ, tủ sách nhà mình có một bộ sưu tập chuyện kể về các nhà khoa học. Mình phát hiện ra cơ số các phát minh hay ho đều bắt đầu một cách tình cờ. Có thể kể ra như Flemming với kháng sinh Penicillin, Rontgen với tia X, Nobel với thuốc nổ, hay xa hơn là Archimedes với cái bồn tắm và Newton với quả táo rơi vào đầu.
Đã không ít lần mình tự hỏi, “Sao họ may mắn thế?”.

Lớn hơn một chút, câu hỏi của mình khác đi: “Tại sao quả táo không rơi vào đầu người bình thường bao giờ, mà lại chọn Newton?”. Câu hỏi này dễ trả lời hơn nhiều so với câu đầu tiên, là nó có rơi, rơi hoài mà.

Nó dẫn mình đến một câu hỏi khác: “Nếu chiếc đĩa nuôi cấy nấm Penicillium notatum rơi vào tay một cô dọn phòng thì sẽ thế nào? Nếu chú thợ nề về nhà ngâm mình vào bồn nước sau một ngày mỏi mệt và thấy nước tràn ra ngoài thì sao? Họ có phát minh ra penicillin hay lực đẩy Archimedes không?”.

Chắc là không.

Vận may không chỉ đến với nhà khoa học. Nó đến với mọi người, vào những thời điểm khác nhau, nhưng quan trọng người ta không nhận ra hoặc chưa sẵn sàng đón nhận. Những nhà khoa học đôi khi không tài giỏi hay xuất chúng vượt trội, họ cũng không biết may mắn sẽ đến khi nào như hầu hết mọi người. Nhưng khi nó đến, họ đã sẵn sàng. Họ đã chuẩn bị cho một cơ hội trong tích tắc bằng hàng tháng, hàng năm, hàng chục năm trời tích luỹ.

Cũng qua quá trình dài tích luỹ đó, họ cũng tăng khả năng may mắn xảy đến với mình. Hãy tưởng tượng, có một “cơn mưa cơ hội” trải đều trên một khu vực rộng lớn nơi tất cả mọi người cùng chung sống. Người nào khai phá được một vùng đất lớn hơn chắc hẳn sẽ có cơ may nhận được nhiều hơn.

À, thế là hầu như những thành tựu tình cờ đều đã được sắp đặt trước cả.
:::

::: {.lang-en}
*(English version coming soon.)*
:::

