---
title: "5 nguyên tắc resume"
date: 2021-08-30
categories: ["Self-dev"]
tags: ["Career", "Productivity", "Self-development"]
lang-post: VI
---

Có lẽ các bạn đã quá quen thuộc với cụm từ nộp CV ứng tuyển (Curriculum Vitae). Tuy nhiên, đối với sinh viên mới ra trường, nhà tuyển dụng thường chỉ yêu cầu nộp resume.

## RESUME LÀ GÌ?

Resume là bản tóm tắt ngắn gọn các học vấn và kĩ năng mà bạn có. Độ dài lý tưởng từ 1 đến 2 trang. Ngược lại, một CV thường dài hơn rất nhiều, dành cho người có 5 năm kinh nghiệm trở lên.

Dựa trên phân tích dữ liệu từ 125.484 bản resume, Austin Belcak đã đưa ra 5 nguyên tắc vàng:

### MẸO SỐ 1: THÊM PROFILE LINKEDIN VÀO RESUME

Những ứng viên có thêm profile LinkedIn có tỷ lệ được gọi phỏng vấn cao rõ rệt. Chưa đến một nửa số ứng viên (48%) làm được điều này.

### MẸO SỐ 2: LƯU Ý NHỮNG KỸ NĂNG QUAN TRỌNG, ĐẶC BIỆT KỸ NĂNG MỀM

Chỉ có 51% từ khoá & kỹ năng quan trọng được nhắc đến. Các ứng viên thường bỏ sót kỹ năng mềm: làm việc nhóm, quản lý thời gian, quản lý cảm xúc.

### MẸO SỐ 3: BẠN CÓ THÀNH TỰU? HÃY ĐO LƯỜNG NÓ!

Chỉ khoảng 26% resumes có đo lường rõ ràng những thành tựu đạt được. Thay vì "thành viên năng nổ", hãy ghi "tổ chức 3 buổi giao lưu cho hơn 1,000 em nhỏ".

### MẸO SỐ 4: ĐỪNG CỐ NHÉT QUÁ NHIỀU CHỮ

Độ dài lý tưởng là 475-600 từ. 77% resumes vượt quá con số này.

### MẸO SỐ 5: HÃY CẨN THẬN VỚI LỖI CHÍNH TẢ

Chỉ cần một từ lóng hay một lỗi chính tả là đủ để huỷ hoại cả resume. Có đến 51% resumes mắc lỗi này.

**GOOD THING TAKES TIME AND EFFORT! GOODLUCK!**
