---
title: "Ứng dụng COVID-19 siêu ứng dụng"
date: 2021-10-26
tags: ["Application", "COVID-19", "health declaration"]
lang-post: VI
draft: true
---

*Bài viết đã được đăng tải trên báo [Khoa học và Phát triển](https://khoahocphattrien.vn), ngày 26/10/2021.*

Trên cơ sở tìm kiếm tổng quan hệ thống tất cả các ứng dụng liên quan đến COVID hiện đang được sử dụng tại Việt Nam, chúng tôi cho rằng nên tập trung xây dựng một ứng dụng duy nhất là PC-Covid.

## Nhiều ứng dụng, nhiều lúng túng

Nhóm nghiên cứu đã thống kê trên 30 ứng dụng trên điện thoại thông minh có liên quan đến COVID-19. Có quá nhiều ứng dụng chống dịch nhưng không có bất kỳ một ứng dụng nào có thể thực hiện đầy đủ tất cả các tính năng.

## Phát triển một "siêu ứng dụng"

Bộ Y tế đã cho ra mắt ứng dụng PC-Covid. Tuy nhiên, ứng dụng vẫn có khá nhiều lỗi. Chúng tôi cho rằng việc tập trung xây dựng một ứng dụng duy nhất cần phải dựa vào những ưu, nhược điểm phổ biến để cải thiện các hạn chế.

**Tác giả: Nhóm nghiên cứu chống dịch COVID toàn cầu** - TS. Trần Thị Thùy Linh, Hoàng Ngọc Lan Hương, Võ Cao Danh, Nguyễn Thanh An, Huỳnh Lê Anh Khoa, BS. Nguyễn Khởi Quân, BS. Nguyễn Hải Nam, Đoàn Lê Nguyệt Cát, PGS.TS.BS Nguyễn Tiến Huy.
