---
title: "Hệ thống phát hiện Covid-19 bị hở"
date: 2023-06-27
tags: ["COVID-19", "health policy", "management", "Productivity"]
lang-post: VI
draft: true
---

*Bài viết đã được đăng tải trên báo [Kinh tế và Dự báo](https://kinhtevadubao.vn) (Bộ Kế hoạch và Đầu tư), ngày 07/10/2021.*

Việt Nam thiếu sót các biện pháp nhằm phát hiện người nhiễm COVID-19 nếu xuất hiện F0 không rõ nguồn gốc trong cộng đồng. Nhóm nghiên cứu kiến nghị 7 giải pháp cấp bách để chặn nguồn lây từ F0.

Việt Nam là một trong những quốc gia chọn phương pháp chống dịch theo chiến lược Zero COVID Control. Như chúng tôi đã phân tích trên Tạp chí khoa học [Frontiers in Public Health](https://pubmed.ncbi.nlm.nih.gov/34368034/), Việt Nam là một trong những quốc gia chống dịch tốt nhất cho tới thời điểm sóng dịch lần này.

Chúng tôi kiến nghị Ban Chỉ đạo Phòng chống dịch Quốc Gia, Bộ Y Tế, Sở Y tế thực thi như sau:

- **Thứ nhất,** ra văn bản chính thức "Xét nghiệm RT-PCR SARS-CoV-2 miễn phí" cho tất cả những người nghi nhiễm COVID-19.
- **Thứ hai,** tuyên truyền mạnh hơn nữa cho người dân hiểu rõ và yêu cầu khai báo y tế khi có triệu chứng.
- **Thứ ba,** có chính sách khen thưởng cụ thể cho người dân tự giác khai báo.
- **Thứ tư,** nghiêm cấm và phạt tất cả những ai có triệu chứng nhưng không tự giác khai báo y tế.
- **Thứ năm,** chuyển mục tiêu "xét nghiệm đại trà" sang "xét nghiệm diện rộng có mục tiêu".
- **Thứ sáu,** duy trì việc truy vết hiệu quả.
- **Thứ bảy,** lập các tổ giám sát và đánh giá các biện pháp chống dịch.

**Tác giả**: Nhóm nghiên cứu chống dịch COVID-19 Toàn cầu - Nguyễn Tiến Huy (PGS, TS, BS, Đại Học Nagasaki), Trương Văn Đạt, Nguyễn Hải Nam, Nguyễn Khởi Quân, Nguyễn Thanh An, Lê Văn Trường, Hà Xuân Nam, Nguyễn Tiến Đồng, Lê Ngọc Bảo Trân, Nguyễn Thanh Hoàng Mai, Koki Shimizu.
