---
title: "A beautiful intro to research"
date: 2023-07-23
categories: ["Self-dev"]
tags: ["Epidemiology", "intro to research", "medical research", "RCT", "Statistics"]
lang-post: EN
---

Hi peeps! Today I found a beautiful outline for an introduction to medical research, from Dr F. Perry Wilson at Yale University. This is a perfect compass for any medical students who want to get started with research.

## **Lesson Guide** - Credit Dr F. Perry Wilson, Offered by Yale

### **The Basics**

1. How Research Works
2. The Medical Manuscript
3. The Replication Crisis
4. The Question is - what is the Question?

### **Medical Statistics Made Ridiculously Simple**

5. Types of Data
6. Averages by Other Names
7. Sampling the Secret Sauce of Statistics
8. Statistics as an Onion
9. Relative vs. Absolute Risk
10. The Power and the Problem with the P-Value
11. Choosing a Statistical Test
12. Interpretation of "Negative" Studies
13. The Randomized Control Trial
14. The Cohort Study
15. The Case-Control Study
16. Study of Diagnostic Tests
17. Meta-Analysis
18. Survival Data
19. Cost-Effectiveness Study

### **How Wrong Conclusions are Reached**

20. Causality
21. Confounding
22. Effect Modification and Mediation
23. Generalizability
24. Multiple Comparisons
25. Surrogate Endpoints
26. Fraud

### **Bias**

27. Selection Bias
28. Information Bias
29. Time-based bias
30. Statistical Brain Teasers

### **Fixing the Problems with Medical Studies**

31. Adjustment
32. Matching
33. Propensity Scoring
34. Putting It All Together

Hope it helps, and have fun!
