---
title: "Truy tìm F0 xét nghiệm chọn lọc"
date: 2023-06-27
tags: ["contact tracing", "COVID-19", "health policy", "management"]
lang-post: VI
draft: true
---

*Bài viết đã được đăng tải trên báo [Kinh tế và Dự báo](https://kinhtevadubao.vn/truy-tim-f0-nen-theo-phuong-phap-xet-nghiem-chon-loc-19348.html) (Bộ Kế hoạch và Đầu tư), ngày 07/10/2021.*

## Hai chiến lược xét nghiệm

Nhiều địa phương đã triển khai xét nghiệm đại trà nhắm vào diện rộng. Biện pháp này không được khuyến khích bởi WHO vì không thể duy trì dài lâu. WHO có hướng dẫn xét nghiệm chọn lọc kèm truy vết cho người dân có triệu chứng gần như là bắt buộc.

## Ước đoán hiệu quả của 2 phương pháp

Với xét nghiệm đại trà (ít nhất 11 ngày) sẽ phát hiện ra 28.000 người sau khi xác nhận bằng PCR. Kinh phí khoảng 145 tỉ VND.

Với xét nghiệm chọn lọc vào người có triệu chứng kèm truy vết: có thể phát hiện 23.520 người trong vòng 3 ngày. Kinh phí khoảng 21,19 tỉ VND.

Phương pháp xét nghiệm chọn lọc kèm truy vết đưa ra kết quả cao hơn nhiều, tính về mặt thời gian (23.520 người/3 ngày so với 28.000 người/11 ngày) và kinh phí (21,19 tỉ so với 145 tỉ VND).

**Tác giả: Nhóm nghiên cứu chống dịch COVID-19 Toàn cầu** - Nguyễn Tiến Huy, Trương Văn Đạt, Nguyễn Hải Nam, Nguyễn Khởi Quân, và cộng sự.
