---
title: "Love and the Secret Garden"
date: 2024-11-30
categories: ["Random thoughts", "Self-dev"]
lang-post: EN
---

## The Secret Garden

"In his book, 'Fortress Besieged,' Qian Zhongshu writes: 'Honestly, no matter who you marry, after the wedding, you'll discover the person you married and the person you loved seem like two different people.'

These words are rather endearing. Marriage, just like any close relationship, is like an onion; as you peel away the layers, you discover who the person truly is, both in the eyes of others and in your own. You uncover the secrets hidden within... and you end up in tears of bittersweet.

Even if you love each other for a hundred years, the person you love will still have a secret garden, a place you've never set foot in. You won't know when it snows there, when the flowers bloom, you won't even know if it has all four seasons. But you will definitely know that on the day they smile faintly and say, 'I'm fine!' and turn away to enter that garden, you want to chase after them. But no matter how hard you try, all you see is their back, a back that tells you there's no need to follow.

The next day, they're full of life again, and you'll know they've returned from that garden.

Some people feel that in a close relationship, there should be no secrets, not even the smallest ones. Naive. So they frantically chase after their partner, demanding: 'Why is there this garden?' When their partner doesn't know how to answer, they get angry and destroy the whole garden. They set it on fire, flames fill the sky, and they feel satisfied that their partner completely belongs to them. But love, by then, is probably gone.

You've burned down the whole lively garden ravaged a land to ruins, how can you expect love to still take root?

## Then how can I still love someone while keeping secrets

Actually, love is the most difficult thing in the world to understand. When love is still there, you don't need to ask. But your feelings will answer. If you feel love, then there is love. If you feel it's not there, then it's not there. Your body understands your love better than your brain. Because the brain is too smart, when it senses the risk of being hurt, it automatically creates an illusion to deceive you for a while.

It's very difficult for someone to truly enter my hearts. That's why, in this world, all you need is wine and meat to indulge all night; just cigarette smoke and a song to listen to all night; tears and a good movie to watch all night. How long is a night? No one knows. Some people experience a century, others just close their eyes, and when they wake up, it's sunlight on the headboard.

I don't share about my secret garden because I am afraid that if someone enters that, what if they find it desolate and scary, filled with too many worries and sorrows, unworthy, shameful, repulsive, damaged, tainted, corrupted, ugly, pathetic, disgusting, repugnant? So, I want to lick my own wounds in my own garden, but I don't want you to worry and fear for me. I pretend to be strong and solid, when deep inside I might be full of insecurities and damages, just like any human being.

And it's even harder for someone to be in my garden, but not impossible. Yet, it requires effort from both sides to make it work. From me, a lot of self-acceptance, courage, and honesty to share. From you, a limitless amount of wisdom, compassion, forgiveness, and kindness. But if one day, I can't bear it anymore, I will definitely need a hug from you. And if you can find that person on Earth, keep them close and fight hard for them, because you will never meet that same person twice.

Therefore, one promise that I must keep is that I won't lie to you. And if I really have to do so, I am so sorry.

## Reflecting on yourself - it's hard to understand someone, because all you can see in them is you

Self-reflection through love is incredibly clear. You'll realize that you understand yourself better when you honestly love someone. People are good at hiding their emotions from others, but they can't hide their own purity when they love. Truly loving someone becomes the foundation for loving a good love. When you have someone loving you from the heart, you will understand. When someone is sincere with you, you will see it. We see that love in others through the sincere love we once gave.

It's hard to understand someone, because looking at them is just like you looking into a mirror - all you can see in them, is a reflection of you.

Therefore, while it may seem easy to deceive others, the truth is, the hardest person to fool is yourself. And that's the deception that will ultimately cost you the most. Even though you and another person might reach a point where you can't find common ground, you will never lose in love. It's about developing yourself. By loving someone, you've gained a deeper understanding of your true self in love.

It's truly heartbreaking to witness an adult trapped in the remnants of their childhood – their behavior, speech, and even their selfishness, irresponsibility, and indifference echoing that of a child. And that's interesting because when they are a child, they think of other the same - same naivety and shortsightedness. All that they can see in a person reflects who they are as a child, and they can't see what they don't understand. How pity.

Therefore, a normal thought is that they can use these people for personal gains, cause the reflection of them are naivety and shortsightedness.

Interestingly, when such a child possesses valuable assets like wealth, social standing, or beauty, they - in turn - become vulnerable to exploitation. People will use them, drain them, and then discard them, leaving them with nothing but the bitter sting of betrayal. Again and again, until they learn, because their naivety won't be able to save them. Until they confront the realities of life and discover their own core values, they're destined to repeat this agonizing cycle, forever caught in a loop of naivety and heartbreak.

We often think about adding things to improve a situation, but sometimes, it's about subtracting – letting go of those who don't deserve you and only seek to use you for their own gain. If you are their friend, be there for them as they navigate their way out of this pattern; but set out a boundary for tolerating - a threshold of which you will no longer stay - and never try to change them.

Their destiny is not yours to write, and ultimately, karma will take its course.

The science of karma is now explained. May your paths be guided by wisdom and compassion 😊 ---
