<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bài 2: Điều chỉnh chi phí về một năm tham chiếu – Mô hình Kinh tế Y tế với R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" rel="next">
<link href="../../kb/m09-inputs-vietnam/l01-costing.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9e7f0c659d5fa2cace8548cb57964278.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c18d72663580ed8ca19ce2a2f99af51b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="mermaid-theme" content="neutral">
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=JetBrains+Mono:wght@400;600&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m09-inputs-vietnam/index.html">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</a></li><li class="breadcrumb-item"><a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Mô hình Kinh tế Y tế với R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lời mở đầu</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m00-r-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M00 · R cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l02-vectors-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l03-functions-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hàm, cấu trúc điều khiển, vòng lặp và vectơ hóa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l04-data-frames.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Data frame — nhập, làm sạch, tóm tắt và chuyển dạng dữ liệu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l05-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Biểu đồ với ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l06-randomness-monte-carlo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 6: Ngẫu nhiên, mô phỏng Monte Carlo và sai số Monte Carlo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m01-ee-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M01 · Nền tảng đánh giá kinh tế và cây quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l01-evaluation-types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại đánh giá kinh tế, quan điểm, khung thời gian và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l02-health-outcomes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Năm sống, QALY và DALY</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l03-decision-rules.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l04-thresholds.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l05-decision-tree.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Xây cây quyết định từ đầu trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m02-cohort-markov/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l01-state-transition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao cần mô hình chuyển trạng thái</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l03-cohort-trace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l04-time-dependence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Phụ thuộc thời gian: lão hóa, trạng thái đường hầm và mảng 3 chiều</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l05-results-verification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị gắn với lần chuyển, đường biên hiệu quả và xác minh mô hình</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m03-uncertainty-voi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l01-deterministic-sa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại bất định và phân tích độ nhạy tất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l02-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Chọn phân phối cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l03-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích độ nhạy xác suất (PSA) trong R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l05-voi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m04-microsimulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M04 · Mô phỏng vi mô (microsimulation)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l01-why-microsimulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l02-microsim-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l03-vectorisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vectơ hóa theo cá thể và đo hiệu năng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l04-parallel-rcpp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tính toán song song và Rcpp cho vòng lặp nóng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l05-mc-error-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bao nhiêu cá thể là đủ? Sai số Monte Carlo, PSA và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m05-dynamic-transmission/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M05 · Mô hình lây truyền động</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l01-static-vs-dynamic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Mô hình tĩnh và mô hình lây truyền động</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l02-sir-seir-desolve.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình SIR và SEIR trong R với deSolve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l03-vaccination-herd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Tiêm chủng, hiệu quả trực tiếp và gián tiếp</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l04-dengue-host-vector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Mô hình vật chủ–véc tơ cho sốt xuất huyết Dengue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l05-dynamic-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế với mô hình lây truyền động</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m06-amr-economics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M06 · Kinh tế học kháng kháng sinh (AMR)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l01-amr-burden.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l02-attributable-los.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l03-ward-transmission.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Mô hình lây truyền CRE trong khoa hồi sức</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l04-two-strain-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m07-survival-psm/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M07 · Phân tích sống còn cho mô hình quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l01-survival-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ôn tập phân tích sống còn cho người làm mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l02-parametric-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình sống còn tham số với flexsurv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l03-extrapolation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Ngoại suy sống còn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l04-reconstruct-ipd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tái tạo dữ liệu cá thể từ đường KM đã công bố và dùng HR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l05-partitioned-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Mô hình sống còn phân vùng trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m08-calibration/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M08 · Hiệu chuẩn mô hình (calibration)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l01-why-calibrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l02-search-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l03-bayes-sir.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hiệu chuẩn Bayes và thuật toán SIR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l04-psa-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đưa kết quả hiệu chuẩn vào PSA, thẩm định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m09-inputs-vietnam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l01-costing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ước tính chi phí cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l05-decision-context.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bối cảnh ra quyết định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m10-policy-bia-equity/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m11-software-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l01-code-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Cấu trúc mã cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l02-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Xác minh và kiểm thử mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l03-version-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quản lý phiên bản với Git và tái lập môi trường với renv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l04-r-package.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đóng gói mô hình thành gói R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l05-shiny-living.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Ứng dụng Shiny và mô hình “sống”</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bảng thuật ngữ Anh–Việt</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../references.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tài liệu tham khảo</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Trong bài</h2>
   
  <ul class="collapse">
  <li><a href="#mục-tiêu-học-tập" id="toc-mục-tiêu-học-tập" class="nav-link active" data-scroll-target="#mục-tiêu-học-tập">Mục tiêu học tập</a></li>
  <li><a href="#ý-chính" id="toc-ý-chính" class="nav-link" data-scroll-target="#ý-chính">Ý chính</a></li>
  <li><a href="#nội-dung" id="toc-nội-dung" class="nav-link" data-scroll-target="#nội-dung">Nội dung</a></li>
  <li><a href="#thực-hành" id="toc-thực-hành" class="nav-link" data-scroll-target="#thực-hành">Thực hành</a></li>
  <li><a href="#bài-tập" id="toc-bài-tập" class="nav-link" data-scroll-target="#bài-tập">Bài tập</a></li>
  <li><a href="#tài-liệu-tham-khảo" id="toc-tài-liệu-tham-khảo" class="nav-link" data-scroll-target="#tài-liệu-tham-khảo">Tài liệu tham khảo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m09-inputs-vietnam/index.html">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</a></li><li class="breadcrumb-item"><a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></h1>
<p class="subtitle lead">Dùng chỉ số giá, tỷ giá và sức mua tương đương để đưa mọi chi phí về VNĐ của cùng một năm, bằng hàm R kiểm tra được</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled" title="Vì sao bạn nên quan tâm?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vì sao bạn nên quan tâm?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Bạn mở hai bài báo để lấy chi phí cho mô hình: một đợt nằm viện vì lao kháng thuốc ở Bệnh viện Phổi Trung ương, trung bình US$1,407 (giá 2024), và một đợt ICU thở máy vì nhiễm khuẩn huyết ở TP.HCM, US$2,860 (giá 2019, trung vị). Đổi bằng tỷ giá của nghiên cứu rồi quy về giá 2025, đợt ICU là 79.0 triệu VNĐ, bằng 14.9 tháng lương tối thiểu vùng I. Từ 2019 đến 2025, mặt bằng giá tiêu dùng ở Việt Nam tăng 19.9%, nên bát phở 40,000 VNĐ hôm nay chỉ tương đương khoảng 33,400 VNĐ năm 2019. Cộng hai con số như trên mà không điều chỉnh là cộng hai đơn vị khác nhau. Bài này giúp bạn chọn chỉ số giá, tỷ giá và thứ tự quy đổi để mọi chi phí về VNĐ năm 2025.</p>
</div>
</div>
<section id="mục-tiêu-học-tập" class="level2">
<h2 class="anchored" data-anchor-id="mục-tiêu-học-tập">Mục tiêu học tập</h2>
<p>Sau bài này, bạn có thể:</p>
<ol type="1">
<li>Quy một chi phí từ mặt bằng giá của năm này sang năm khác bằng chỉ số giá tiêu dùng (CPI) hoặc chỉ số giảm phát GDP (GDP deflator).</li>
<li>Đổi tiền giữa VNĐ, USD và đô la quốc tế (international dollar, quy theo PPP), và biết khi nào dùng tỷ giá thị trường, khi nào dùng PPP.</li>
<li>So sánh hai cách điều chỉnh chính (điều chỉnh theo giá Việt Nam rồi đổi tiền, hoặc điều chỉnh theo giá Mỹ trong USD rồi đổi tiền) và chọn cách phù hợp.</li>
<li>Viết và kiểm tra một hàm R đưa mọi chi phí về một năm tham chiếu chi phí (cost year), dừng lại khi thiếu số liệu thay vì đoán.</li>
</ol>
</section>
<section id="ý-chính" class="level2">
<h2 class="anchored" data-anchor-id="ý-chính">Ý chính</h2>
<ul>
<li>Mỗi chi phí cần hai nhãn: <strong>đơn vị tiền</strong> và <strong>năm tham chiếu chi phí</strong> (cost year). Chuẩn hóa là đưa mọi chi phí về một cặp nhãn duy nhất, ở đây là VNĐ năm 2025.</li>
<li>CPI Việt Nam và tỷ giá chính thức của khóa học nằm ở một chỗ duy nhất, <code>_shared/data/vn_cpi_fx.csv</code>; hàm dùng chung <code>inflate_vnd()</code> làm phép quy đổi bằng CPI.</li>
<li>Công thức duy nhất cần nhớ: <span class="math inline">\(C_{\text{đích}} = C_{\text{gốc}} \times I_{\text{đích}} / I_{\text{gốc}}\)</span>, với <span class="math inline">\(I\)</span> là một chỉ số giá.</li>
<li>CPI đo giá giỏ hàng tiêu dùng; chỉ số giảm phát GDP đo giá mọi hàng hóa sản xuất trong nước. Cả hai là chỉ số chung, không riêng cho y tế; nhiều nước công bố thêm chỉ số giá nhóm chăm sóc y tế, đáng thử làm độ nhạy khi có. Chọn một chỉ số, ghi rõ, thử chỉ số kia.</li>
<li>Chi phí phát sinh tại Việt Nam: đổi sang VNĐ theo tỷ giá <strong>năm gốc</strong>, rồi quy về giá năm đích bằng chỉ số <strong>Việt Nam</strong>. Đổi USD theo tỷ giá năm nay mà bỏ qua chênh lệch giá giữa các năm là sai.</li>
<li>Thứ tự “đổi tiền rồi điều chỉnh giá” và “điều chỉnh giá rồi đổi tiền” cho kết quả khác nhau, vì tỷ giá không đi cùng chênh lệch lạm phát giữa hai nước <span class="citation" data-cites="turner2019adjusting">(<a href="#ref-turner2019adjusting" role="doc-biblioref">Turner và c.s. 2019</a>)</span>.</li>
<li>Đô la quốc tế (PPP) dùng để so sánh giữa các nước; USD theo tỷ giá thị trường dùng cho hàng hóa mua bằng ngoại tệ và ngân sách tài trợ.</li>
<li>Khi năm đích chưa có số liệu (chỉ số giá Mỹ hay tỷ giá năm gần nhất thường chưa công bố), hàm phải báo lỗi; số thay thế, nếu dùng, phải được gắn cờ và viết ra.</li>
</ul>
</section>
<section id="nội-dung" class="level2">
<h2 class="anchored" data-anchor-id="nội-dung">Nội dung</h2>
<section id="vì-sao-phải-điều-chỉnh" class="level3">
<h3 class="anchored" data-anchor-id="vì-sao-phải-điều-chỉnh">Vì sao phải điều chỉnh</h3>
<p>Bài 1 kết thúc với các số liệu chi phí Việt Nam ở hai năm tham chiếu chi phí, đều tính bằng USD theo tỷ giá do nhóm nghiên cứu chọn <span class="citation" data-cites="ngo2026direct hung2022direct">(<a href="#ref-ngo2026direct" role="doc-biblioref">Ngo và c.s. 2026</a>; <a href="#ref-hung2022direct" role="doc-biblioref">Hung và c.s. 2022</a>)</span>. Đặt chúng cạnh nhau trong một mô hình VNĐ năm 2025 mà không điều chỉnh là cộng hai thứ khác đơn vị. Bảng kiểm báo cáo CHEERS 2022 dành riêng một mục cho đơn vị tiền, năm tham chiếu chi phí và cách quy đổi <span class="citation" data-cites="husereau2022consolidated">(<a href="#ref-husereau2022consolidated" role="doc-biblioref">Husereau và c.s. 2022</a>)</span>, vì đây là chỗ người đọc không tự kiểm tra lại được.</p>
</section>
<section id="chỉ-số-giá" class="level3">
<h3 class="anchored" data-anchor-id="chỉ-số-giá">Chỉ số giá</h3>
<p>Một chỉ số giá <span class="math inline">\(I_t\)</span> cho biết mặt bằng giá năm <span class="math inline">\(t\)</span> so với năm gốc của chỉ số. Quy chi phí <span class="math inline">\(C\)</span> từ năm <span class="math inline">\(s\)</span> sang năm <span class="math inline">\(t\)</span>:</p>
<p><span class="math display">\[
C_t = C_s \times \frac{I_t}{I_s}.
\]</span></p>
<p>Năm gốc của chỉ số (ví dụ 2010 = 100) không quan trọng vì nó triệt tiêu trong tỷ số. Ngân hàng Thế giới công bố cả CPI lẫn chỉ số giảm phát GDP cho Việt Nam trong bộ chỉ số phát triển thế giới (WDI) <span class="citation" data-cites="worldbank2026wdicpi worldbank2026wdi">(<a href="#ref-worldbank2026wdicpi" role="doc-biblioref">World Bank 2026a</a>, <a href="#ref-worldbank2026wdi" role="doc-biblioref">2026c</a>)</span>. CPI phản ánh giá hàng tiêu dùng mà hộ gia đình mua; chỉ số giảm phát GDP bao trùm mọi hàng hóa và dịch vụ sản xuất trong nước. Nghiên cứu chi phí ICU tại TP.HCM dùng chỉ số giảm phát GDP để đưa chi phí 2017–2019 về giá 2019 <span class="citation" data-cites="hung2022direct">(<a href="#ref-hung2022direct" role="doc-biblioref">Hung và c.s. 2022</a>)</span>; một số nghiên cứu khác dùng CPI. Hai lựa chọn đều chấp nhận được nếu được ghi rõ.</p>
</section>
<section id="tỷ-giá-thị-trường-và-sức-mua-tương-đương" class="level3">
<h3 class="anchored" data-anchor-id="tỷ-giá-thị-trường-và-sức-mua-tương-đương">Tỷ giá thị trường và sức mua tương đương</h3>
<p>Tỷ giá thị trường (VNĐ/USD, bình quân năm) cho biết cần bao nhiêu VNĐ để mua một USD. Hệ số sức mua tương đương (PPP) cho biết cần bao nhiêu VNĐ để mua ở Việt Nam lượng hàng mà một đô la mua được ở Mỹ. Ở nước thu nhập trung bình như Việt Nam, hệ số PPP nhỏ hơn nhiều so với tỷ giá, nên cùng một khoản VNĐ đổi ra được nhiều đô la quốc tế hơn USD. Bài của Turner và cộng sự bàn cả hai cách quy đổi <span class="citation" data-cites="turner2019adjusting">(<a href="#ref-turner2019adjusting" role="doc-biblioref">Turner và c.s. 2019</a>)</span>. Quy ước của khóa học: PPP cho so sánh chi phí giữa các nước; tỷ giá thị trường cho hàng hóa mua bằng ngoại tệ (thuốc nhập khẩu, máy xét nghiệm) và khi người ra quyết định là nhà tài trợ quốc tế.</p>
</section>
<section id="hai-thứ-tự-hai-kết-quả" class="level3">
<h3 class="anchored" data-anchor-id="hai-thứ-tự-hai-kết-quả">Hai thứ tự, hai kết quả</h3>
<p>Với một chi phí báo cáo bằng USD của năm <span class="math inline">\(s\)</span>, cần đưa về năm <span class="math inline">\(t\)</span>, có hai cách chính <span class="citation" data-cites="turner2019adjusting">(<a href="#ref-turner2019adjusting" role="doc-biblioref">Turner và c.s. 2019</a>)</span>:</p>
<ol type="1">
<li><strong>Điều chỉnh theo giá Mỹ:</strong> giữ USD, nhân với <span class="math inline">\(I^{\text{Mỹ}}_t / I^{\text{Mỹ}}_s\)</span>, rồi (nếu cần) đổi sang VNĐ theo tỷ giá năm <span class="math inline">\(t\)</span>.</li>
<li><strong>Điều chỉnh theo giá Việt Nam:</strong> đổi sang VNĐ theo tỷ giá năm <span class="math inline">\(s\)</span>, nhân với <span class="math inline">\(I^{\text{VN}}_t / I^{\text{VN}}_s\)</span>, rồi (nếu cần) đổi lại USD theo tỷ giá năm <span class="math inline">\(t\)</span>.</li>
</ol>
<p>Nếu tỷ giá điều chỉnh đúng bằng chênh lệch lạm phát giữa hai nước, hai cách cho cùng kết quả. Thực tế không như vậy, nên kết quả khác nhau, có khi rất lớn; ví dụ giả định trong bài báo gốc là 100 USD chi tại Việt Nam năm 2006, đưa về giá 2016 cho US$116.84 theo cách 1 và US$172.09 theo cách 2 <span class="citation" data-cites="turner2019adjusting">(<a href="#ref-turner2019adjusting" role="doc-biblioref">Turner và c.s. 2019</a>)</span>. Cách thứ ba là tách chi phí thành phần hàng hóa trao đổi quốc tế (dùng cách 1) và phần nguồn lực trong nước như nhân lực (dùng cách 2).</p>
<p>Quy tắc thực hành cho mô hình Việt Nam:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>flowchart TD</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  A["Chi phí gốc: số tiền, đơn vị tiền, năm tham chiếu chi phí s"] --&gt; B{"Phát sinh ở Việt Nam?"}</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  B -- "Có" --&gt; C["Đổi sang VNĐ theo tỷ giá năm s&lt;br/&gt;(ưu tiên tỷ giá nghiên cứu gốc đã dùng)"]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  C --&gt; D["Nhân I_VN(t) / I_VN(s)"]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  B -- "Không: hàng nhập khẩu, giá quốc tế" --&gt; E["Giữ USD, nhân I_Mỹ(t) / I_Mỹ(s)"]</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  E --&gt; F["Đổi sang VNĐ theo tỷ giá năm t"]</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  D --&gt; G["VNĐ năm t: ghi vào params/*.csv&lt;br/&gt;cột unit = 'VNĐ (t)'"]</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  F --&gt; G</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
  A["Chi phí gốc: số tiền, đơn vị tiền, năm tham chiếu chi phí s"] --&gt; B{"Phát sinh ở Việt Nam?"}
  B -- "Có" --&gt; C["Đổi sang VNĐ theo tỷ giá năm s&lt;br/&gt;(ưu tiên tỷ giá nghiên cứu gốc đã dùng)"]
  C --&gt; D["Nhân I_VN(t) / I_VN(s)"]
  B -- "Không: hàng nhập khẩu, giá quốc tế" --&gt; E["Giữ USD, nhân I_Mỹ(t) / I_Mỹ(s)"]
  E --&gt; F["Đổi sang VNĐ theo tỷ giá năm t"]
  D --&gt; G["VNĐ năm t: ghi vào params/*.csv&lt;br/&gt;cột unit = 'VNĐ (t)'"]
  F --&gt; G
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Nếu nghiên cứu gốc đã đổi VNĐ sang USD bằng một tỷ giá riêng, hãy đổi ngược bằng <strong>chính tỷ giá đó</strong> để lấy lại số VNĐ ban đầu, thay vì dùng một tỷ giá khác.</p>
</section>
</section>
<section id="thực-hành" class="level2">
<h2 class="anchored" data-anchor-id="thực-hành">Thực hành</h2>
<p>Chunk đầu nạp CPI Việt Nam và tỷ giá từ tệp dùng chung <code>vn_cpi_fx()</code> <span class="citation" data-cites="worldbank2026wdicpi worldbank2026wdifx">(<a href="#ref-worldbank2026wdicpi" role="doc-biblioref">World Bank 2026a</a>, <a href="#ref-worldbank2026wdifx" role="doc-biblioref">2026b</a>)</span>, cùng các chuỗi chỉ dùng trong bài này (chỉ số giảm phát GDP, hệ số PPP, chỉ số giá Mỹ) từ <code>params/macro.csv</code> <span class="citation" data-cites="worldbank2026wdi">(<a href="#ref-worldbank2026wdi" role="doc-biblioref">World Bank 2026c</a>)</span>, rồi gom thành danh sách <code>m</code>. Năm đích là 2025, lấy từ <code>vn_context()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">isTRUE</span>(<span class="fu">l10n_info</span>()[[<span class="st">"UTF-8"</span>]])) <span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_CTYPE"</span>, <span class="st">"en_US.UTF-8"</span>))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/helpers.R"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/vn_data.R"</span>)   <span class="co"># course-wide CPI and VND/USD rate: the single source of truth</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"code/model.R"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>ctx <span class="ot">&lt;-</span> <span class="fu">vn_context</span>()</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>pr <span class="ot">&lt;-</span> <span class="fu">vn_prices</span>()</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>pc <span class="ot">&lt;-</span> <span class="fu">read_params</span>(<span class="st">"params/costing.csv"</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>cf <span class="ot">&lt;-</span> <span class="fu">vn_cpi_fx</span>()                   <span class="co"># shared CPI (2010 = 100), inflation and exchange rate, 2010-2025</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">macro_series</span>(<span class="fu">read_params</span>(<span class="st">"params/macro.csv"</span>), cf)   <span class="co"># + module deflator, PPP and US indices</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>target <span class="ot">&lt;-</span> ctx<span class="sc">$</span>cost_year</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In bảng tỷ lệ lạm phát theo hai chỉ số, tỷ giá (kèm cờ trạng thái) và hệ số PPP từng năm. Kiểm tra: lạm phát tính từ chỉ số CPI khớp lạm phát công bố trong tệp dùng chung, và hệ số PPP nhỏ hơn tỷ giá.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One table per year (the years of the module's deflator series): price indices, exchange rate, PPP</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>yrs <span class="ot">&lt;-</span> <span class="fu">names</span>(m<span class="sc">$</span>vn_defl)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>cpi_y <span class="ot">&lt;-</span> m<span class="sc">$</span>vn_cpi[yrs]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>macro_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="fu">as.integer</span>(yrs),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">cpi_infl =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">diff</span>(cpi_y) <span class="sc">/</span> <span class="fu">head</span>(cpi_y, <span class="sc">-</span><span class="dv">1</span>)),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">defl_infl =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="fu">diff</span>(m<span class="sc">$</span>vn_defl) <span class="sc">/</span> <span class="fu">head</span>(m<span class="sc">$</span>vn_defl, <span class="sc">-</span><span class="dv">1</span>)),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">fx =</span> <span class="fu">unname</span>(m<span class="sc">$</span>fx[yrs]),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">fx_status =</span> cf<span class="sc">$</span>fx_status[<span class="fu">match</span>(<span class="fu">as.integer</span>(yrs), cf<span class="sc">$</span>year)],</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">ppp =</span> <span class="fu">unname</span>(m<span class="sc">$</span>ppp[yrs])</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>macro_tab<span class="sc">$</span>ppp_over_fx <span class="ot">&lt;-</span> macro_tab<span class="sc">$</span>ppp <span class="sc">/</span> macro_tab<span class="sc">$</span>fx</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>macro_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     year   cpi_infl  defl_infl       fx                            fx_status
     2015         NA         NA 21697.57                            published
2016 2016 0.02668248 0.01819536 21935.00                            published
2017 2017 0.03520257 0.04362920 22370.09                            published
2018 2018 0.03539628 0.03626647 22602.05                            published
2019 2019 0.02795824 0.02423227 23050.24                            published
2020 2020 0.03220934 0.01467478 23208.37                            published
2021 2021 0.01834716 0.02880768 23159.78                            published
2022 2022 0.03156507 0.04442833 23271.21                            published
2023 2023 0.03252893 0.02164983 23787.32                            published
2024 2024 0.03621093 0.04208552 24164.89                            published
2025 2025 0.03309993 0.03331761 24970.00 not_published_filled_from_vn_context
          ppp ppp_over_fx
     7290.149   0.3359892
2016 7163.831   0.3265936
2017 7211.600   0.3223769
2018 7275.826   0.3219100
2019 7191.188   0.3119789
2020 7064.954   0.3044141
2021 7120.011   0.3074300
2022 6942.552   0.2983322
2023 6839.771   0.2875385
2024 6954.978   0.2878134
2025 6990.871   0.2799708</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checks: CPI inflation computed from the index equals the published inflation in the shared file;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># it stays in a plausible range; the PPP factor is below the market rate (middle-income country)</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>infl_pub <span class="ot">&lt;-</span> cf<span class="sc">$</span>inflation[<span class="fu">match</span>(macro_tab<span class="sc">$</span>year[<span class="sc">-</span><span class="dv">1</span>], cf<span class="sc">$</span>year)]</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(macro_tab<span class="sc">$</span>cpi_infl[<span class="sc">-</span><span class="dv">1</span>] <span class="sc">-</span> infl_pub) <span class="sc">&lt;</span> <span class="fl">1e-6</span>),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(macro_tab<span class="sc">$</span>cpi_infl[<span class="sc">-</span><span class="dv">1</span>] <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> macro_tab<span class="sc">$</span>cpi_infl[<span class="sc">-</span><span class="dv">1</span>] <span class="sc">&lt;</span> <span class="fl">0.15</span>),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(macro_tab<span class="sc">$</span>ppp_over_fx <span class="sc">&lt;</span> <span class="dv">1</span>))</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>fx_cy_status <span class="ot">&lt;-</span> cf<span class="sc">$</span>fx_status[cf<span class="sc">$</span>year <span class="sc">==</span> target]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Lạm phát CPI năm 2025 là 3.3%. Hai chỉ số không đi cùng nhau từng năm: năm 2020, CPI tăng 3.2% còn chỉ số giảm phát GDP chỉ tăng 1.5%. Ngân hàng Thế giới chưa công bố tỷ giá năm 2025; tệp dùng chung điền 24,970 VNĐ/USD, suy ra từ GDP bình quân đầu người tính bằng VNĐ và USD của Cục Thống kê <span class="citation" data-cites="gso2026gdp2025">(<a href="#ref-gso2026gdp2025" role="doc-biblioref">Cục Thống kê (Bộ Tài chính) 2026</a>)</span>, và gắn cờ not_published_filled_from_vn_context. Đó là cách xử lý minh bạch một năm chưa có số liệu: dùng số thay thế có nguồn, và để lại dấu vết.</p>
<p>Quy 1 triệu VNĐ năm 2019 về giá năm 2025 bằng cả hai chỉ số. Kiểm tra: đi rồi về phải ra đúng số ban đầu, và hàm <code>inflate()</code> của bài cho cùng kết quả với hàm dùng chung <code>inflate_vnd()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1,000,000 VND spent in 2019, expressed in 2025 prices with two indices</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>x_2019 <span class="ot">&lt;-</span> <span class="fl">1e6</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>infl_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"CPI"</span>, <span class="st">"GDP deflator"</span>),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">value_2025 =</span> <span class="fu">c</span>(<span class="fu">inflate</span>(x_2019, <span class="dv">2019</span>, target, m<span class="sc">$</span>vn_cpi), <span class="fu">inflate</span>(x_2019, <span class="dv">2019</span>, target, m<span class="sc">$</span>vn_defl))</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>infl_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         index value_2025
1          CPI    1198541
2 GDP deflator    1199441</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Round trip and identity checks; the module's inflate() gives the same answer as the shared inflate_vnd()</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(<span class="fu">inflate</span>(<span class="fu">inflate</span>(x_2019, <span class="dv">2019</span>, target, m<span class="sc">$</span>vn_cpi), target, <span class="dv">2019</span>, m<span class="sc">$</span>vn_cpi) <span class="sc">-</span> x_2019) <span class="sc">&lt;</span> <span class="fl">1e-6</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>          <span class="fu">inflate</span>(x_2019, <span class="dv">2019</span>, <span class="dv">2019</span>, m<span class="sc">$</span>vn_cpi) <span class="sc">==</span> x_2019,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>          <span class="fu">abs</span>(infl_tab<span class="sc">$</span>value_2025[<span class="dv">1</span>] <span class="sc">-</span> <span class="fu">inflate_vnd</span>(x_2019, <span class="at">from_year =</span> <span class="dv">2019</span>, <span class="at">to_year =</span> target)) <span class="sc">&lt;</span> <span class="fl">1e-6</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Everyday reading: a bowl of pho at today's price, expressed in 2019 prices</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>pho_2019 <span class="ot">&lt;-</span> <span class="fu">inflate_vnd</span>(pr<span class="sc">$</span>anchor_pho_bowl, <span class="at">from_year =</span> target, <span class="at">to_year =</span> <span class="dv">2019</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Where do the two indices disagree most? Relative gap between the two multipliers by base year</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>idx_gap <span class="ot">&lt;-</span> (m<span class="sc">$</span>vn_defl[[<span class="fu">as.character</span>(target)]] <span class="sc">/</span> m<span class="sc">$</span>vn_defl) <span class="sc">/</span> (m<span class="sc">$</span>vn_cpi[[<span class="fu">as.character</span>(target)]] <span class="sc">/</span> cpi_y) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>idx_gap_year <span class="ot">&lt;-</span> <span class="fu">names</span>(idx_gap)[<span class="fu">which.max</span>(<span class="fu">abs</span>(idx_gap))]</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>idx_gap_max <span class="ot">&lt;-</span> idx_gap[[idx_gap_year]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Trong giai đoạn này, hai chỉ số tình cờ cho hệ số gần như nhau (1,198,541 và 1,199,441 VNĐ). Với các năm gốc khác thì không hẳn: hình dưới cho thấy hai hệ số lệch nhau nhiều nhất ở năm gốc 2020, khi chỉ số giảm phát cho hệ số cao hơn CPI 1.8%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>fac <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">year =</span> <span class="fu">as.integer</span>(yrs), <span class="at">factor =</span> m<span class="sc">$</span>vn_cpi[[<span class="fu">as.character</span>(target)]] <span class="sc">/</span> cpi_y,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">index =</span> <span class="st">"CPI Việt Nam"</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">year =</span> <span class="fu">as.integer</span>(yrs), <span class="at">factor =</span> m<span class="sc">$</span>vn_defl[[<span class="fu">as.character</span>(target)]] <span class="sc">/</span> m<span class="sc">$</span>vn_defl,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">index =</span> <span class="st">"Chỉ số giảm phát GDP Việt Nam"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>fig_index <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(fac, <span class="fu">aes</span>(year, factor, <span class="at">colour =</span> index)) <span class="sc">+</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> pal_course[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)], <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">as.integer</span>(yrs)) <span class="sc">+</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Năm giá của chi phí gốc"</span>, <span class="at">y =</span> <span class="fu">paste</span>(<span class="st">"Hệ số nhân để quy về giá năm"</span>, target),</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Cùng một khoản chi, hai chỉ số giá cho hai hệ số quy đổi"</span>) <span class="sc">+</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_index, <span class="st">"l02-index.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-l02-index" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-l02-index-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="l02-cost-adjustment_files/figure-html/fig-l02-index-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-l02-index-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;48.1: Hệ số nhân để đưa chi phí của từng năm về giá của năm tham chiếu, theo hai chỉ số giá của Việt Nam.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Bây giờ đưa chi phí ICU của người bệnh nhiễm khuẩn huyết có thở máy (US$2,860, giá 2019) về VNĐ năm 2025 theo bốn cách. Hàm <code>cost_to_vnd()</code> nhận đơn vị tiền, năm gốc, năm đích, chỉ số và thứ tự điều chỉnh.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Septic shock ICU cost (US$ 2019, from bills) expressed in VND 2025, four ways.</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The US CPI and the exchange rate end in 2024, so the "US inflation" route cannot reach 2025</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># directly: row 3 is a labelled bridge (US inflation and exchange rate up to 2024, then Vietnamese CPI).</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>x_usd <span class="ot">&lt;-</span> pc<span class="sc">$</span>hung_sepsis_mv_usd</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>y0 <span class="ot">&lt;-</span> pc<span class="sc">$</span>hung_price_year</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>bridge_year <span class="ot">&lt;-</span> <span class="fu">min</span>(<span class="fu">max</span>(<span class="fu">as.integer</span>(<span class="fu">names</span>(m<span class="sc">$</span>us_cpi))), <span class="fu">max</span>(<span class="fu">as.integer</span>(<span class="fu">names</span>(m<span class="sc">$</span>fx))))</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>methods_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"Đổi sang VNĐ (tỷ giá nghiên cứu) rồi CPI Việt Nam"</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Đổi sang VNĐ (tỷ giá nghiên cứu) rồi chỉ số giảm phát GDP"</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>             <span class="fu">paste0</span>(<span class="st">"CPI Mỹ trong USD đến "</span>, bridge_year, <span class="st">", đổi theo tỷ giá "</span>, bridge_year,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>                    <span class="st">", rồi CPI Việt Nam sang "</span>, target, <span class="st">" (cầu nối)"</span>),</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>             <span class="fu">paste0</span>(<span class="st">"Đổi theo tỷ giá "</span>, bridge_year, <span class="st">", bỏ qua chênh lệch giá giữa các năm (sai)"</span>)),</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">vnd_2025 =</span> <span class="fu">c</span>(</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cost_to_vnd</span>(x_usd, <span class="st">"USD"</span>, y0, target, m, <span class="st">"cpi"</span>, <span class="st">"local"</span>, <span class="at">fx_source =</span> pc<span class="sc">$</span>hung_fx),</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cost_to_vnd</span>(x_usd, <span class="st">"USD"</span>, y0, target, m, <span class="st">"deflator"</span>, <span class="st">"local"</span>, <span class="at">fx_source =</span> pc<span class="sc">$</span>hung_fx),</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cost_to_vnd</span>(x_usd, <span class="st">"USD"</span>, y0, target, m, <span class="st">"cpi"</span>, <span class="st">"bridge"</span>, <span class="at">bridge_year =</span> bridge_year),</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>    x_usd <span class="sc">*</span> <span class="fu">series_value</span>(m<span class="sc">$</span>fx, bridge_year, <span class="st">"Exchange rate"</span>)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>methods_tab<span class="sc">$</span>vs_first <span class="ot">&lt;-</span> methods_tab<span class="sc">$</span>vnd_2025 <span class="sc">/</span> methods_tab<span class="sc">$</span>vnd_2025[<span class="dv">1</span>] <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>methods_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                                                 method
1                                     Đổi sang VNĐ (tỷ giá nghiên cứu) rồi CPI Việt Nam
2                             Đổi sang VNĐ (tỷ giá nghiên cứu) rồi chỉ số giảm phát GDP
3 CPI Mỹ trong USD đến 2024, đổi theo tỷ giá 2024, rồi CPI Việt Nam sang 2025 (cầu nối)
4                        Đổi theo tỷ giá 2024, bỏ qua chênh lệch giá giữa các năm (sai)
  vnd_2025      vs_first
1 79011437  0.0000000000
2 79070763  0.0007508532
3 87605985  0.1087759928
4 69111573 -0.1252965922</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(methods_tab<span class="sc">$</span>vnd_2025 <span class="sc">&gt;</span> <span class="dv">0</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The lesson's opening box uses the shared inflate_vnd(): it must agree with row 1 (study rate, then Vietnamese CPI)</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(methods_tab<span class="sc">$</span>vnd_2025[<span class="dv">1</span>] <span class="sc">-</span> <span class="fu">inflate_vnd</span>(x_usd <span class="sc">*</span> pc<span class="sc">$</span>hung_fx, <span class="at">from_year =</span> y0, <span class="at">to_year =</span> target)) <span class="sc">&lt;</span> <span class="dv">1</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The text says the GDP deflator barely changes the result (below 1%)</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(methods_tab<span class="sc">$</span>vs_first[<span class="dv">2</span>]) <span class="sc">&lt;</span> <span class="fl">0.01</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Like for like: in the last year where US CPI and exchange rate both exist, compare the pure routes</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>same_year <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"Tỷ giá nghiên cứu rồi CPI Việt Nam"</span>, <span class="st">"CPI Mỹ trong USD rồi tỷ giá năm đích"</span>),</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">vnd =</span> <span class="fu">c</span>(<span class="fu">cost_to_vnd</span>(x_usd, <span class="st">"USD"</span>, y0, bridge_year, m, <span class="st">"cpi"</span>, <span class="st">"local"</span>, <span class="at">fx_source =</span> pc<span class="sc">$</span>hung_fx),</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>          <span class="fu">cost_to_vnd</span>(x_usd, <span class="st">"USD"</span>, y0, bridge_year, m, <span class="st">"cpi"</span>, <span class="st">"usd"</span>))</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>gap_same_year <span class="ot">&lt;-</span> same_year<span class="sc">$</span>vnd[<span class="dv">2</span>] <span class="sc">/</span> same_year<span class="sc">$</span>vnd[<span class="dv">1</span>] <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>same_year</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                method      vnd
1   Tỷ giá nghiên cứu rồi CPI Việt Nam 76479956
2 CPI Mỹ trong USD rồi tỷ giá năm đích 84799139</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The bridge adds one common Vietnamese-CPI step to both routes, so its gap equals the same-year gap</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(methods_tab<span class="sc">$</span>vs_first[<span class="dv">3</span>] <span class="sc">-</span> gap_same_year) <span class="sc">&lt;</span> <span class="fl">1e-9</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The pure US route must refuse years the US index does not cover (no silent fallback)</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>us_err <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(<span class="fu">cost_to_vnd</span>(x_usd, <span class="st">"USD"</span>, y0, target, m, <span class="st">"cpi"</span>, <span class="st">"usd"</span>), <span class="at">error =</span> <span class="cf">function</span>(e) <span class="fu">conditionMessage</span>(e))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>us_err</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Price index has no value for year 2025"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">is.character</span>(us_err),</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">inherits</span>(<span class="fu">try</span>(<span class="fu">cost_to_vnd</span>(x_usd, <span class="st">"USD"</span>, y0, <span class="dv">2030</span>, m, <span class="st">"cpi"</span>, <span class="st">"usd"</span>), <span class="at">silent =</span> <span class="cn">TRUE</span>), <span class="st">"try-error"</span>),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>          <span class="fu">abs</span>(<span class="fu">cost_to_vnd</span>(x_usd, <span class="st">"USD"</span>, y0, bridge_year, m, <span class="st">"cpi"</span>, <span class="st">"usd"</span>) <span class="sc">-</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                <span class="fu">cost_to_vnd</span>(x_usd, <span class="st">"USD"</span>, y0, bridge_year, m, <span class="st">"cpi"</span>, <span class="st">"bridge"</span>, <span class="at">bridge_year =</span> bridge_year)) <span class="sc">&lt;</span> <span class="fl">1e-6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cách khuyến nghị (đổi bằng tỷ giá nghiên cứu, rồi CPI Việt Nam) cho 79.0 triệu VNĐ, tức 14.9 tháng lương tối thiểu vùng I cho một đợt nằm ICU. Cách “CPI Mỹ rồi đổi tiền” không với tới năm 2025: chỉ số giá Mỹ dừng ở 2024, nên hàm báo lỗi (Price index has no value for year 2025). Dòng 3 là một cầu nối được gắn nhãn rõ: giá Mỹ và tỷ giá đến 2024, rồi CPI Việt Nam sang 2025. Nó cao hơn cách khuyến nghị 10.9%, đúng bằng chênh lệch khi so ở năm 2024 (10.9%), nơi hai cách đều có đủ số liệu: bước CPI Việt Nam sang 2025 nhân cả hai như nhau. Chênh lệch đến từ khác biệt giữa giá Mỹ, giá Việt Nam và biến động tỷ giá từ 2019, không đến từ cầu nối. Đổi thẳng theo tỷ giá gần nhất mà bỏ qua chênh lệch giá giữa các năm cho kết quả thấp hơn 12.5%. Thay CPI bằng chỉ số giảm phát GDP gần như không đổi kết quả (0.08%), vì hai chỉ số tăng gần như song song từ 2019.</p>
<p>Lặp lại so sánh của Turner và cộng sự với số liệu mới: 100 USD chi tại Việt Nam năm 2015, quy về USD năm 2024.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The two main approaches for a US$100 cost from 2015, expressed in US$ of 2024</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>fx15 <span class="ot">&lt;-</span> <span class="fu">series_value</span>(m<span class="sc">$</span>fx, <span class="dv">2015</span>); fx24 <span class="ot">&lt;-</span> <span class="fu">series_value</span>(m<span class="sc">$</span>fx, <span class="dv">2024</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>turner_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">approach =</span> <span class="fu">c</span>(<span class="st">"Phương án 1: lạm phát Mỹ trong USD"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Phương án 2: đổi sang VNĐ, lạm phát Việt Nam, đổi lại USD"</span>),</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">usd_2024 =</span> <span class="fu">c</span>(<span class="fu">inflate</span>(<span class="dv">100</span>, <span class="dv">2015</span>, <span class="dv">2024</span>, m<span class="sc">$</span>us_cpi),</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>               <span class="fu">inflate</span>(<span class="dv">100</span> <span class="sc">*</span> fx15, <span class="dv">2015</span>, <span class="dv">2024</span>, m<span class="sc">$</span>vn_cpi) <span class="sc">/</span> fx24)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>turner_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                   approach usd_2024
1                        Phương án 1: lạm phát Mỹ trong USD 132.3487
2 Phương án 2: đổi sang VNĐ, lạm phát Việt Nam, đổi lại USD 117.8367</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>gap_1524 <span class="ot">&lt;-</span> turner_tab<span class="sc">$</span>usd_2024[<span class="dv">1</span>] <span class="sc">-</span> turner_tab<span class="sc">$</span>usd_2024[<span class="dv">2</span>]</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Turner et al. report the same comparison for 2006 -&gt; 2016: which approach is higher?</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>turner_orig <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">method1 =</span> pc<span class="sc">$</span>turner_m1_usd, <span class="at">method2 =</span> pc<span class="sc">$</span>turner_m2_usd)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>sign_orig <span class="ot">&lt;-</span> <span class="fu">sign</span>(turner_orig[[<span class="st">"method1"</span>]] <span class="sc">-</span> turner_orig[[<span class="st">"method2"</span>]])</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>sign_here <span class="ot">&lt;-</span> <span class="fu">sign</span>(turner_tab<span class="sc">$</span>usd_2024[<span class="dv">1</span>] <span class="sc">-</span> turner_tab<span class="sc">$</span>usd_2024[<span class="dv">2</span>])</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">original =</span> sign_orig, <span class="at">here =</span> sign_here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>original     here 
      -1        1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Method 2 beats method 1 when Vietnamese prices grew faster than US prices x the VND depreciation</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>fac1524 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">vn_prices =</span> <span class="fu">inflate</span>(<span class="dv">1</span>, <span class="dv">2015</span>, <span class="dv">2024</span>, m<span class="sc">$</span>vn_cpi), <span class="at">us_prices =</span> <span class="fu">inflate</span>(<span class="dv">1</span>, <span class="dv">2015</span>, <span class="dv">2024</span>, m<span class="sc">$</span>us_cpi),</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">vnd_depreciation =</span> fx24 <span class="sc">/</span> fx15)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>fac1524</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       vn_prices        us_prices vnd_depreciation 
        1.312364         1.323487         1.113714 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The text says the sign flipped and that method 1 is higher here: guard both statements</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(sign_orig <span class="sc">!=</span> sign_here, sign_here <span class="sc">==</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Hai cách lệch nhau 14.5 USD trên mỗi 100 USD, và chiều lệch ngược với ví dụ của Turner: ở giai đoạn 2006–2016 cách 2 cao hơn cách 1, còn ở 2015–2024 này cách 1 cao hơn. Cách 2 cao hơn khi giá Việt Nam tăng nhanh hơn tích của hệ số tăng giá Mỹ và hệ số mất giá của VNĐ. Từ 2015 đến 2024, giá Việt Nam tăng ×1.31, giá Mỹ ×1.32, VNĐ mất giá ×1.11. Vì thế dấu của chênh lệch phụ thuộc giai đoạn: không cách nào luôn cao hơn, và phải tính rồi mới biết. Cách 1 còn ngầm giả định giá nguồn lực Việt Nam tăng theo giá ở Mỹ, điều không đúng với nhân lực và dịch vụ trong nước.</p>
<p>Chi phí nằm viện vì lao kháng thuốc được nhóm nghiên cứu đổi sang USD bằng tỷ giá riêng 25,000 VNĐ/USD. Đổi ngược bằng tỷ giá đó và bằng tỷ giá bình quân của Ngân hàng Thế giới:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># DR-TB hospital stay (US$ 2024): the study's own exchange rate vs the World Bank average</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>ngo_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">rate_used =</span> <span class="fu">c</span>(<span class="st">"Tỷ giá của nghiên cứu"</span>, <span class="st">"Tỷ giá bình quân Ngân hàng Thế giới"</span>),</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">fx =</span> <span class="fu">c</span>(pc<span class="sc">$</span>ngo_fx, <span class="fu">series_value</span>(m<span class="sc">$</span>fx, pc<span class="sc">$</span>ngo_price_year)),</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">vnd_2025 =</span> <span class="fu">c</span>(<span class="fu">cost_to_vnd</span>(pc<span class="sc">$</span>ngo_median_usd, <span class="st">"USD"</span>, pc<span class="sc">$</span>ngo_price_year, target, m, <span class="at">fx_source =</span> pc<span class="sc">$</span>ngo_fx),</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>               <span class="fu">cost_to_vnd</span>(pc<span class="sc">$</span>ngo_median_usd, <span class="st">"USD"</span>, pc<span class="sc">$</span>ngo_price_year, target, m))</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>ngo_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            rate_used       fx vnd_2025
1               Tỷ giá của nghiên cứu 25000.00 18266240
2 Tỷ giá bình quân Ngân hàng Thế giới 24164.89 17656064</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>ngo_diff <span class="ot">&lt;-</span> ngo_tab<span class="sc">$</span>vnd_2025[<span class="dv">1</span>] <span class="sc">/</span> ngo_tab<span class="sc">$</span>vnd_2025[<span class="dv">2</span>] <span class="sc">-</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dùng nhầm tỷ giá làm chi phí lệch 3.5%, chỉ vì một bước quy đổi. Hãy đổi ngược bằng tỷ giá mà nghiên cứu gốc đã dùng. Bài 1 làm đúng như vậy với khảo sát chi phí người bệnh lao: đổi bằng tỷ giá 23,256 VNĐ/USD của nghiên cứu, rồi <code>inflate_vnd()</code> từ năm 2021.</p>
<p>Cuối cùng, trình bày một chi phí VNĐ 2025 bằng USD và đô la quốc tế (international dollar), dùng tỷ giá và hệ số PPP của cùng một năm: năm gần nhất có cả hai. Kiểm tra cờ trạng thái của tỷ giá năm đó.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Report a VND 2025 cost in US$ and in international dollars (PPP), both for the same year so the</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># comparison is clean: the ratio below is just the exchange rate over the PPP factor of that year.</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The 2025 rate in the shared file is not a World Bank figure: check its status flag and say so.</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>x_vnd <span class="ot">&lt;-</span> methods_tab<span class="sc">$</span>vnd_2025[<span class="dv">1</span>]</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>conv_year <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">as.integer</span>(<span class="fu">intersect</span>(<span class="fu">names</span>(m<span class="sc">$</span>fx), <span class="fu">names</span>(m<span class="sc">$</span>ppp))))</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">year =</span> conv_year, <span class="at">fx_status =</span> cf<span class="sc">$</span>fx_status[cf<span class="sc">$</span>year <span class="sc">==</span> conv_year])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                  year                              fx_status 
                                "2025" "not_published_filled_from_vn_context" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>out_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">unit =</span> <span class="fu">c</span>(<span class="fu">paste0</span>(<span class="st">"VNĐ (giá "</span>, target, <span class="st">")"</span>), <span class="fu">paste0</span>(<span class="st">"US$ (tỷ giá "</span>, conv_year, <span class="st">")"</span>),</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>           <span class="fu">paste0</span>(<span class="st">"Đô la quốc tế (PPP "</span>, conv_year, <span class="st">")"</span>)),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">c</span>(x_vnd, <span class="fu">vnd_to_usd</span>(x_vnd, conv_year, m), <span class="fu">vnd_to_intl</span>(x_vnd, conv_year, m))</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>out_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      unit        value
1           VNĐ (giá 2025) 79011437.322
2        US$ (tỷ giá 2025)     3164.255
3 Đô la quốc tế (PPP 2025)    11302.088</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>intl_over_usd <span class="ot">&lt;-</span> out_tab<span class="sc">$</span>value[<span class="dv">3</span>] <span class="sc">/</span> out_tab<span class="sc">$</span>value[<span class="dv">2</span>]</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(intl_over_usd <span class="sc">-</span> <span class="fu">series_value</span>(m<span class="sc">$</span>fx, conv_year) <span class="sc">/</span> <span class="fu">series_value</span>(m<span class="sc">$</span>ppp, conv_year)) <span class="sc">&lt;</span> <span class="fl">1e-9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cả hai quy đổi dùng năm 2025; tỷ giá năm này là số điền từ Cục Thống kê (cờ not_published_filled_from_vn_context), nên báo cáo phải ghi rõ. Cùng một khoản chi, con số tính bằng đô la quốc tế lớn gấp 3.57 lần con số tính bằng USD: đó chính là tỷ giá chia cho hệ số PPP của năm đó. Khi đọc một nghiên cứu báo cáo “I$” hay “US$”, hãy kiểm tra đó là loại đô la nào trước khi so sánh.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Mẹo thực hành">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mẹo thực hành
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Lấy CPI và tỷ giá Việt Nam từ tệp dùng chung (<code>vn_cpi_fx()</code>, <code>inflate_vnd()</code>), không chép vào module. Chuỗi riêng của bài (chỉ số giảm phát, PPP, giá Mỹ) lưu trong bảng tham số, một dòng một năm, có mã chỉ số và ngày truy xuất.</li>
<li>Viết hàm quy đổi sao cho thiếu số liệu thì <strong>dừng lại</strong>, như <code>series_value()</code>. Lỗi lộ ra sớm rẻ hơn một kết quả sai lặng lẽ.</li>
<li>Năm đích là một giá trị duy nhất của cả khóa học (<code>vn_context()$cost_year</code>). Đổi năm đích chỉ cần sửa một ô trong <code>_shared</code>.</li>
<li>Với thuốc nhập khẩu có giá quốc tế bằng USD, cân nhắc giữ USD và đổi theo tỷ giá năm đích (cách tách hàng hóa trao đổi quốc tế).</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Lỗi thường gặp">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lỗi thường gặp
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Đổi USD năm cũ theo tỷ giá năm nay rồi coi như giá năm nay.</strong> Cách này bỏ qua lạm phát trong nước; ví dụ trong bài thấp hơn 12.5%.</li>
<li><strong>Dùng tỷ giá khác với nghiên cứu gốc khi đổi ngược.</strong> Lấy lại số VNĐ ban đầu bằng đúng tỷ giá họ đã dùng.</li>
<li><strong>Lẫn đô la quốc tế với USD.</strong> Ở Việt Nam, cùng một khoản chi tính ra đô la quốc tế lớn gấp 3.6 lần tính ra USD.</li>
<li><strong>Để hàm tự lùi về năm gần nhất có số liệu.</strong> Kết quả mang nhãn năm đích nhưng nằm ở giá năm cũ. Hàm phải dừng lại; cầu nối hay số điền thay, nếu dùng, phải được gắn nhãn (CHEERS 2022 yêu cầu báo cáo rõ chỉ số và năm).</li>
</ul>
</div>
</div>
</section>
<section id="bài-tập" class="level2">
<h2 class="anchored" data-anchor-id="bài-tập">Bài tập</h2>
<ol type="1">
<li><strong>(Dễ)</strong> Đưa chi phí nằm viện vì lao kháng thuốc (trung vị) về VNĐ năm 2025 bằng chỉ số giảm phát GDP thay cho CPI. Kết quả khác bao nhiêu?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 1: the DR-TB stay in VND 2025 with the GDP deflator instead of the CPI</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>ex1 <span class="ot">&lt;-</span> <span class="fu">cost_to_vnd</span>(pc<span class="sc">$</span>ngo_median_usd, <span class="st">"USD"</span>, pc<span class="sc">$</span>ngo_price_year, target, m, <span class="st">"deflator"</span>, <span class="at">fx_source =</span> pc<span class="sc">$</span>ngo_fx)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>ex1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18270089</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>ex1_rel <span class="ot">&lt;-</span> ex1 <span class="sc">/</span> ngo_tab<span class="sc">$</span>vnd_2025[<span class="dv">1</span>] <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>ex1_rel</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0002107038</code></pre>
</div>
</div>
<p>Chênh lệch là 0.02%: chỉ đi qua một năm (2024 sang 2025), và trong năm đó CPI tăng 3.31%, chỉ số giảm phát tăng 3.33%.</p>
</div>
</div>
</div>
<ol start="2" type="1">
<li><strong>(Vừa)</strong> Một bài báo báo cáo chi phí 500 đô la quốc tế (giá 2019). Đổi sang VNĐ năm 2025.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 2: a cost reported as 500 international dollars (2019) -&gt; VND 2025</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">inflate</span>(<span class="dv">500</span> <span class="sc">*</span> <span class="fu">series_value</span>(m<span class="sc">$</span>ppp, <span class="dv">2019</span>), <span class="dv">2019</span>, target, m<span class="sc">$</span>vn_cpi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4309468</code></pre>
</div>
</div>
<p>Nhân với hệ số PPP của năm 2019 để ra VNĐ 2019, rồi quy về giá 2025 bằng CPI Việt Nam. Không dùng tỷ giá thị trường ở bước đầu.</p>
</div>
</div>
</div>
<ol start="3" type="1">
<li><strong>(Khó)</strong> Lặp lại so sánh hai cách điều chỉnh cho giai đoạn 2019–2024. Khoảng cách giữa hai cách lớn hơn hay nhỏ hơn giai đoạn 2015–2024? Giải thích bằng diễn biến lạm phát và tỷ giá.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 3: Turner-style comparison for 2019 -&gt; 2024</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>ex3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">us_inflation =</span> <span class="fu">inflate</span>(<span class="dv">100</span>, <span class="dv">2019</span>, <span class="dv">2024</span>, m<span class="sc">$</span>us_cpi),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">vn_inflation =</span> <span class="fu">inflate</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">series_value</span>(m<span class="sc">$</span>fx, <span class="dv">2019</span>), <span class="dv">2019</span>, <span class="dv">2024</span>, m<span class="sc">$</span>vn_cpi) <span class="sc">/</span> fx24)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>ex3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>us_inflation vn_inflation 
    122.6989     110.6627 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>gap_1924 <span class="ot">&lt;-</span> ex3[[<span class="st">"us_inflation"</span>]] <span class="sc">-</span> ex3[[<span class="st">"vn_inflation"</span>]]</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>span_1924 <span class="ot">&lt;-</span> <span class="dv">2024</span> <span class="sc">-</span> <span class="dv">2019</span>; span_1524 <span class="ot">&lt;-</span> <span class="dv">2024</span> <span class="sc">-</span> <span class="dv">2015</span>   <span class="co"># length of the two periods in years</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>fac1924 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">vn_prices =</span> <span class="fu">inflate</span>(<span class="dv">1</span>, <span class="dv">2019</span>, <span class="dv">2024</span>, m<span class="sc">$</span>vn_cpi), <span class="at">us_prices =</span> <span class="fu">inflate</span>(<span class="dv">1</span>, <span class="dv">2019</span>, <span class="dv">2024</span>, m<span class="sc">$</span>us_cpi),</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">vnd_depreciation =</span> fx24 <span class="sc">/</span> <span class="fu">series_value</span>(m<span class="sc">$</span>fx, <span class="dv">2019</span>))</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>fac1924</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       vn_prices        us_prices vnd_depreciation 
        1.160141         1.226989         1.048357 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Method 1 is higher exactly when US prices x VND depreciation exceed Vietnamese prices</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>((gap_1924 <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">==</span> (fac1924[[<span class="st">"us_prices"</span>]] <span class="sc">*</span> fac1924[[<span class="st">"vnd_depreciation"</span>]] <span class="sc">&gt;</span> fac1924[[<span class="st">"vn_prices"</span>]]))</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The text: the 2019-2024 gap is smaller than 2015-2024, but by less than the shorter period would suggest</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(gap_1924 <span class="sc">&gt;</span> <span class="dv">0</span>, gap_1924 <span class="sc">&lt;</span> gap_1524, gap_1924 <span class="sc">/</span> gap_1524 <span class="sc">&gt;</span> span_1924 <span class="sc">/</span> span_1524)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Khoảng cách giai đoạn 2019–2024 là 12.0 USD trên mỗi 100 USD, so với 14.5 USD cho 2015–2024: nhỏ hơn, nhưng chỉ nhỏ hơn 17% trong khi giai đoạn ngắn hơn 44% (5 so với 9 năm). Nghĩa là phần lớn chênh lệch giữa hai cách tích lũy từ 2019 trở đi. Giai đoạn này giá Mỹ tăng ×1.23, giá Việt Nam ×1.16, VNĐ mất giá ×1.05; tích của hệ số giá Mỹ và hệ số mất giá vượt hệ số giá Việt Nam, nên cách 1 vẫn cao hơn.</p>
</div>
</div>
</div>
</section>
<section id="tài-liệu-tham-khảo" class="level2">
<h2 class="anchored" data-anchor-id="tài-liệu-tham-khảo">Tài liệu tham khảo</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-gso2026gdp2025" class="csl-entry" role="listitem">
Cục Thống kê (Bộ Tài chính). 2026. <span>“Họp báo công bố tình hình kinh tế – xã hội quý <span>IV</span> và năm 2025”</span>. 5 Tháng Giêng 2026. <a href="https://www.nso.gov.vn/?p=59699">https://www.nso.gov.vn/?p=59699</a>.
</div>
<div id="ref-hung2022direct" class="csl-entry" role="listitem">
Hung, Trinh Manh, Nguyen Van Hao, Lam Minh Yen, Angela McBride, Vu Quoc Dat, H. Rogier van Doorn, Huynh Thi Loan, và c.s. 2022. <span>“Direct medical costs of tetanus, dengue, and sepsis patients in an intensive care unit in <span>Vietnam</span>”</span>. <em>Frontiers in Public Health</em> 10: 893200. <a href="https://doi.org/10.3389/fpubh.2022.893200">https://doi.org/10.3389/fpubh.2022.893200</a>.
</div>
<div id="ref-husereau2022consolidated" class="csl-entry" role="listitem">
Husereau, Don, Michael Drummond, Federico Augustovski, Esther de Bekker-Grob, Andrew H Briggs, Chris Carswell, Lisa Caulley, và c.s. 2022. <span>“Consolidated Health Economic Evaluation Reporting Standards 2022 (CHEERS 2022) statement: updated reporting guidance for health economic evaluations”</span>. <em>BMJ (Clinical research ed.)</em> 376: e067975. <a href="https://doi.org/10.1136/bmj-2021-067975">https://doi.org/10.1136/bmj-2021-067975</a>.
</div>
<div id="ref-ngo2026direct" class="csl-entry" role="listitem">
Ngo, Do Minh, An Thi Binh Nguyen, Hanh Duc Nguyen, và Hau Van Hoang. 2026. <span>“Direct medical costs for drug-resistant tuberculosis inpatients at the national lung hospital, <span>Vietnam</span>: a one-year study”</span>. <em>Journal of Public Health Research</em> 15 (3): 22799036261467454. <a href="https://doi.org/10.1177/22799036261467454">https://doi.org/10.1177/22799036261467454</a>.
</div>
<div id="ref-turner2019adjusting" class="csl-entry" role="listitem">
Turner, Hugo C., Jeremy A. Lauer, Bach Xuan Tran, Yot Teerawattananon, và Mark Jit. 2019. <span>“Adjusting for inflation and currency changes within health economic studies”</span>. <em>Value in Health</em> 22 (9): 1026–32. <a href="https://doi.org/10.1016/j.jval.2019.03.021">https://doi.org/10.1016/j.jval.2019.03.021</a>.
</div>
<div id="ref-worldbank2026wdicpi" class="csl-entry" role="listitem">
World Bank. 2026a. <span>“Consumer price index (2010 = 100), <span>Viet Nam</span> (indicator <span>FP.CPI.TOTL</span>), World Development Indicators”</span>. 2026. <a href="https://api.worldbank.org/v2/country/VNM/indicator/FP.CPI.TOTL?format=json&amp;date=2010:2025&amp;per_page=100">https://api.worldbank.org/v2/country/VNM/indicator/FP.CPI.TOTL?format=json&amp;date=2010:2025&amp;per_page=100</a>.
</div>
<div id="ref-worldbank2026wdifx" class="csl-entry" role="listitem">
———. 2026b. <span>“Official exchange rate (<span>LCU</span> per <span>US$</span>, period average), <span>Viet Nam</span> (indicator <span>PA.NUS.FCRF</span>), World Development Indicators”</span>. 2026. <a href="https://api.worldbank.org/v2/country/VNM/indicator/PA.NUS.FCRF?format=json&amp;date=2010:2025&amp;per_page=100">https://api.worldbank.org/v2/country/VNM/indicator/PA.NUS.FCRF?format=json&amp;date=2010:2025&amp;per_page=100</a>.
</div>
<div id="ref-worldbank2026wdi" class="csl-entry" role="listitem">
———. 2026c. <span>“World Development Indicators: <span>GDP</span> deflator (<span>NY.GDP.DEFL.ZS</span>), <span>PPP</span> conversion factor (<span>PA.NUS.PPP</span>) for <span>Viet Nam</span>; consumer price index (<span>FP.CPI.TOTL</span>) and <span>GDP</span> deflator for the <span>United States</span>”</span>. <a href="https://api.worldbank.org/v2/country/VNM/indicator/NY.GDP.DEFL.ZS?format=json&amp;date=2015:2025">https://api.worldbank.org/v2/country/VNM/indicator/NY.GDP.DEFL.ZS?format=json&amp;date=2015:2025</a>.
</div>
</div>
<div class="video-script">
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kịch bản video (~12 phút)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Slide</th>
<th>Lời giảng chính</th>
<th>Hình/Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Các con số, hai năm tham chiếu chi phí</td>
<td>không cộng được chi phí khác đơn vị; phở 40,000 VNĐ nay ≈ 33,400 VNĐ năm 2019; CHEERS mục 15</td>
<td>callout đầu bài</td>
</tr>
<tr class="even">
<td>2</td>
<td>Chỉ số giá</td>
<td><span class="math inline">\(C_t = C_s I_t / I_s\)</span>; năm gốc của chỉ số không quan trọng</td>
<td>công thức</td>
</tr>
<tr class="odd">
<td>3</td>
<td>CPI hay chỉ số giảm phát GDP</td>
<td>2020: 3.2% so với 1.5%; chọn một, thử cái kia</td>
<td><code>figs/l02-index.png</code></td>
</tr>
<tr class="even">
<td>4</td>
<td>Tỷ giá và PPP</td>
<td>tệp dùng chung <code>vn_cpi_fx()</code>; tỷ giá 2025 là số điền có cờ; PPP để so sánh giữa nước</td>
<td>chunk <code>l02-series</code></td>
</tr>
<tr class="odd">
<td>5</td>
<td>Hai thứ tự điều chỉnh</td>
<td>điều chỉnh theo giá Việt Nam rồi đổi tiền, hay ngược lại</td>
<td>sơ đồ quyết định</td>
</tr>
<tr class="even">
<td>6</td>
<td>Ví dụ ICU nhiễm khuẩn huyết</td>
<td>bốn cách; CPI Mỹ dừng ở 2024 nên cần cầu nối; hàm báo lỗi thay vì đoán</td>
<td>chunk <code>l02-methods</code></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Bài học từ Turner 2019</td>
<td>100 USD năm 2015: 132.3 vs 117.8; dấu chênh lệch đổi theo giai đoạn</td>
<td>chunk <code>l02-turner</code></td>
</tr>
<tr class="even">
<td>8</td>
<td>Tỷ giá của nghiên cứu gốc</td>
<td>đổi ngược bằng đúng tỷ giá họ dùng</td>
<td>chunk <code>l02-ngo</code></td>
</tr>
<tr class="odd">
<td>9</td>
<td>Thiếu số liệu năm đích</td>
<td>hàm báo lỗi; chọn và ghi lại</td>
<td>chunk <code>l02-ppp</code></td>
</tr>
<tr class="even">
<td>10</td>
<td>Chuyển tiếp</td>
<td>chi phí đã xong; sang kết cục: thỏa dụng, trọng số bệnh tật, bảng sống → Bài 3</td>
<td>—</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../kb/m09-inputs-vietnam/l01-costing.html" class="pagination-link" aria-label="Bài 1: Ước tính chi phí cho mô hình">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Bài 1: Ước tính chi phí cho mô hình</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="pagination-link" aria-label="Bài 3: Đầu vào về kết cục sức khỏe">
        <span class="nav-page-text"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>