<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bài 3: Đầu vào về kết cục sức khỏe – Mô hình Kinh tế Y tế với R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" rel="next">
<link href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9e7f0c659d5fa2cace8548cb57964278.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c18d72663580ed8ca19ce2a2f99af51b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=JetBrains+Mono:wght@400;600&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m09-inputs-vietnam/index.html">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</a></li><li class="breadcrumb-item"><a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Mô hình Kinh tế Y tế với R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lời mở đầu</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m00-r-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M00 · R cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l02-vectors-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l03-functions-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hàm, cấu trúc điều khiển, vòng lặp và vectơ hóa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l04-data-frames.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Data frame — nhập, làm sạch, tóm tắt và chuyển dạng dữ liệu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l05-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Biểu đồ với ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l06-randomness-monte-carlo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 6: Ngẫu nhiên, mô phỏng Monte Carlo và sai số Monte Carlo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m01-ee-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M01 · Nền tảng đánh giá kinh tế và cây quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l01-evaluation-types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại đánh giá kinh tế, quan điểm, khung thời gian và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l02-health-outcomes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Năm sống, QALY và DALY</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l03-decision-rules.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l04-thresholds.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l05-decision-tree.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Xây cây quyết định từ đầu trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m02-cohort-markov/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l01-state-transition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao cần mô hình chuyển trạng thái</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l03-cohort-trace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l04-time-dependence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Phụ thuộc thời gian: lão hóa, trạng thái đường hầm và mảng 3 chiều</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l05-results-verification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị gắn với lần chuyển, đường biên hiệu quả và xác minh mô hình</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m03-uncertainty-voi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l01-deterministic-sa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại bất định và phân tích độ nhạy tất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l02-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Chọn phân phối cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l03-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích độ nhạy xác suất (PSA) trong R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l05-voi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m04-microsimulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M04 · Mô phỏng vi mô (microsimulation)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l01-why-microsimulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l02-microsim-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l03-vectorisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vectơ hóa theo cá thể và đo hiệu năng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l04-parallel-rcpp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tính toán song song và Rcpp cho vòng lặp nóng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l05-mc-error-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bao nhiêu cá thể là đủ? Sai số Monte Carlo, PSA và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m05-dynamic-transmission/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M05 · Mô hình lây truyền động</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l01-static-vs-dynamic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Mô hình tĩnh và mô hình lây truyền động</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l02-sir-seir-desolve.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình SIR và SEIR trong R với deSolve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l03-vaccination-herd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Tiêm chủng, hiệu quả trực tiếp và gián tiếp</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l04-dengue-host-vector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Mô hình vật chủ–véc tơ cho sốt xuất huyết Dengue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l05-dynamic-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế với mô hình lây truyền động</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m06-amr-economics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M06 · Kinh tế học kháng kháng sinh (AMR)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l01-amr-burden.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l02-attributable-los.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l03-ward-transmission.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Mô hình lây truyền CRE trong khoa hồi sức</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l04-two-strain-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m07-survival-psm/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M07 · Phân tích sống còn cho mô hình quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l01-survival-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ôn tập phân tích sống còn cho người làm mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l02-parametric-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình sống còn tham số với flexsurv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l03-extrapolation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Ngoại suy sống còn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l04-reconstruct-ipd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tái tạo dữ liệu cá thể từ đường KM đã công bố và dùng HR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l05-partitioned-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Mô hình sống còn phân vùng trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m08-calibration/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M08 · Hiệu chuẩn mô hình (calibration)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l01-why-calibrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l02-search-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l03-bayes-sir.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hiệu chuẩn Bayes và thuật toán SIR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l04-psa-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đưa kết quả hiệu chuẩn vào PSA, thẩm định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m09-inputs-vietnam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l01-costing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ước tính chi phí cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l05-decision-context.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bối cảnh ra quyết định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m10-policy-bia-equity/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m11-software-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l01-code-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Cấu trúc mã cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l02-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Xác minh và kiểm thử mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l03-version-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quản lý phiên bản với Git và tái lập môi trường với renv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l04-r-package.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đóng gói mô hình thành gói R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l05-shiny-living.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Ứng dụng Shiny và mô hình “sống”</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bảng thuật ngữ Anh–Việt</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../references.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tài liệu tham khảo</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Trong bài</h2>
   
  <ul class="collapse">
  <li><a href="#mục-tiêu-học-tập" id="toc-mục-tiêu-học-tập" class="nav-link active" data-scroll-target="#mục-tiêu-học-tập">Mục tiêu học tập</a></li>
  <li><a href="#ý-chính" id="toc-ý-chính" class="nav-link" data-scroll-target="#ý-chính">Ý chính</a></li>
  <li><a href="#nội-dung" id="toc-nội-dung" class="nav-link" data-scroll-target="#nội-dung">Nội dung</a></li>
  <li><a href="#thực-hành" id="toc-thực-hành" class="nav-link" data-scroll-target="#thực-hành">Thực hành</a></li>
  <li><a href="#bài-tập" id="toc-bài-tập" class="nav-link" data-scroll-target="#bài-tập">Bài tập</a></li>
  <li><a href="#tài-liệu-tham-khảo" id="toc-tài-liệu-tham-khảo" class="nav-link" data-scroll-target="#tài-liệu-tham-khảo">Tài liệu tham khảo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m09-inputs-vietnam/index.html">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</a></li><li class="breadcrumb-item"><a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></h1>
<p class="subtitle lead">Tính giá trị thỏa dụng bằng bộ giá trị EQ-5D-5L Việt Nam, chọn mốc nền theo tuổi, dùng trọng số bệnh tật GBD, và lấy tử vong nền từ bảng sống dùng chung của khóa học</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled" title="Vì sao bạn nên quan tâm?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vì sao bạn nên quan tâm?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Một người đàn ông 51 tuổi, đúng tuổi trung vị của người bệnh lao trong khảo sát EQ-5D-5L ở Hà Nội, Hải Phòng, Đà Nẵng và TP.HCM, đến khám vì ho kéo dài. Nếu ông chết vì lao, theo bảng sống Việt Nam mà cả khóa học dùng chung, ông mất khoảng 24.5 năm sống. Nếu ông sống sót, lúc bắt đầu điều trị thỏa dụng trung bình của người bệnh là 0.83, trong khi người cùng tuổi là 0.92; qua 6 tháng điều trị, khoảng cách ấy tương đương chừng 10 ngày sống khỏe mạnh. Hai con số này góp phần quyết định phần “hiệu quả” của mọi ICER về lao, nên cách chọn mốc nền, bảng sống và thang đo (QALY hay DALY) làm đổi kết quả. Bài này giúp bạn chọn cho đúng.</p>
</div>
</div>
<section id="mục-tiêu-học-tập" class="level2">
<h2 class="anchored" data-anchor-id="mục-tiêu-học-tập">Mục tiêu học tập</h2>
<p>Sau bài này, bạn có thể:</p>
<ol type="1">
<li>Chuyển hồ sơ EQ-5D-5L thành giá trị thỏa dụng (utility) bằng bộ giá trị (value set) Việt Nam, và kiểm tra hàm của mình với các giá trị đã công bố.</li>
<li>Chọn giá trị thỏa dụng từ y văn và chọn mốc sức khỏe nền (baseline) theo tuổi, cùng bộ giá trị.</li>
<li>Dùng trọng số bệnh tật (disability weight) GBD để tính YLD, và dùng bảng sống để tính YLL.</li>
<li>Kiểm tra một bảng sống công bố, lấy tỷ suất chết nền từ <code>vn_mx()</code> và đổi sang xác suất theo chu kỳ.</li>
<li>Nêu rõ lựa chọn bảng sống (nguồn, năm, giới; quốc gia hay tham chiếu) và nhận ra khi hai nguồn chính thức mâu thuẫn.</li>
</ol>
</section>
<section id="ý-chính" class="level2">
<h2 class="anchored" data-anchor-id="ý-chính">Ý chính</h2>
<ul>
<li>QALY cần <strong>giá trị thỏa dụng</strong> (1 = sức khỏe hoàn hảo, 0 = tử vong, có thể âm). DALY cần <strong>trọng số bệnh tật</strong> (0 = khỏe, 1 = tương đương tử vong). Hai thang đo không đổi lẫn cho nhau được.</li>
<li>Việt Nam có bộ giá trị EQ-5D-5L riêng, dạng cộng: thỏa dụng = 1 trừ tổng mức giảm của năm khía cạnh. Hàm tự viết phải tái tạo được các giá trị tác giả công bố.</li>
<li>Chỉ so hoặc chia hai thỏa dụng khi cùng công cụ đo, cùng bộ giá trị và quần thể giống nhau (nguyên tắc của khóa học; ISPOR có bảng kiểm <span class="citation" data-cites="brazier2019identification">(<a href="#ref-brazier2019identification" role="doc-biblioref">Brazier và c.s. 2019</a>)</span>). Lấy 1 làm mốc nền phóng đại lợi ích; dùng chuẩn dân số <strong>cùng nhóm tuổi</strong> khi có <span class="citation" data-cites="ara2010populating">(<a href="#ref-ara2010populating" role="doc-biblioref">Ara và Brazier 2010</a>)</span>.</li>
<li>Tử vong nền (background mortality) lấy từ bảng sống dùng chung (<code>vn_lifetable()</code>, <code>vn_mx()</code>): WHO 2023 cho Việt Nam. Không chép bảng sống vào module.</li>
<li>Luôn kiểm tra bảng trước khi dùng: các cột phải khớp nhau, và <span class="math inline">\(L_x \le n\,l_x\)</span>. Bảng WHO qua được kiểm tra; bảng 2009 của Tổng cục Thống kê thì không (bài tập 3).</li>
<li>WHO và Cục Thống kê (trước đây là Tổng cục Thống kê) bất đồng về tuổi thọ theo giới: khoảng 2.2 năm ở nam. Đó là một phát hiện cần nêu, không phải chi tiết để bỏ qua.</li>
</ul>
</section>
<section id="nội-dung" class="level2">
<h2 class="anchored" data-anchor-id="nội-dung">Nội dung</h2>
<section id="giá-trị-thỏa-dụng-và-bộ-giá-trị-eq-5d-5l" class="level3">
<h3 class="anchored" data-anchor-id="giá-trị-thỏa-dụng-và-bộ-giá-trị-eq-5d-5l">Giá trị thỏa dụng và bộ giá trị EQ-5D-5L</h3>
<p>EQ-5D-5L hỏi về năm khía cạnh (đi lại, tự chăm sóc, sinh hoạt thường ngày, đau/khó chịu, lo lắng/u sầu), mỗi khía cạnh năm mức từ “không có vấn đề” đến “không thể/rất nặng” <span class="citation" data-cites="herdman2011development">(<a href="#ref-herdman2011development" role="doc-biblioref">Herdman và c.s. 2011</a>)</span>. Mỗi người trả lời cho ra một hồ sơ năm chữ số, ví dụ 12345. Hồ sơ chưa phải thỏa dụng: cần một <strong>bộ giá trị</strong>, ước lượng từ ưu tiên của dân số chung bằng các kỹ thuật như đánh đổi thời gian (time trade-off) và thí nghiệm lựa chọn rời rạc (discrete choice experiment).</p>
<p>Bộ giá trị EQ-5D-5L Việt Nam được xây từ 1,200 người trưởng thành đại diện cho cả nước, theo quy trình chuẩn của nhóm EuroQol và một mô hình hybrid kết hợp hai kỹ thuật trên <span class="citation" data-cites="mai2020eq5d5l">(<a href="#ref-mai2020eq5d5l" role="doc-biblioref">Mai và c.s. 2020</a>)</span>. Giá trị thấp nhất (trạng thái 55555) là -0.5115. Mô hình có dạng cộng:</p>
<p><span class="math display">\[
u = 1 - \sum_{d=1}^{5} \delta_d(\ell_d), \qquad \delta_d(\ell) = \sum_{j=2}^{\ell} \Delta_{d,j},
\]</span></p>
<p>trong đó <span class="math inline">\(\Delta_{d,j}\)</span> là mức giảm khi đi từ mức <span class="math inline">\(j-1\)</span> lên mức <span class="math inline">\(j\)</span> ở khía cạnh <span class="math inline">\(d\)</span> (hệ số gia tăng như bảng gốc công bố), và <span class="math inline">\(\delta_d(\ell)\)</span> là mức giảm cộng dồn ở mức <span class="math inline">\(\ell\)</span>. Trước khi có bộ giá trị trong nước, các nghiên cứu Việt Nam từng mượn bộ giá trị của Hàn Quốc, Thái Lan hoặc Trung Quốc <span class="citation" data-cites="mai2020eq5d5l">(<a href="#ref-mai2020eq5d5l" role="doc-biblioref">Mai và c.s. 2020</a>)</span>; nay dùng bộ khác cần được lý giải và thử độ nhạy.</p>
</section>
<section id="thỏa-dụng-từ-y-văn-và-mốc-nền-theo-tuổi" class="level3">
<h3 class="anchored" data-anchor-id="thỏa-dụng-từ-y-văn-và-mốc-nền-theo-tuổi">Thỏa dụng từ y văn và mốc nền theo tuổi</h3>
<p>Mô hình hiếm khi có số liệu EQ-5D tự thu thập cho mọi trạng thái; hướng dẫn ISPOR giúp tìm, tổng hợp và đánh giá thỏa dụng từ y văn <span class="citation" data-cites="brazier2019identification">(<a href="#ref-brazier2019identification" role="doc-biblioref">Brazier và c.s. 2019</a>)</span>. Ở người bệnh lao, khảo sát dọc 585 người tại bốn thành phố, dùng bộ giá trị Việt Nam, cho thỏa dụng trung bình 0.83 lúc bắt đầu điều trị và 0.90 sau điều trị <span class="citation" data-cites="vo2025life">(<a href="#ref-vo2025life" role="doc-biblioref">Vo và c.s. 2025</a>)</span>. Bài báo công bố cả phân bố năm mức của từng khía cạnh, nên ta mô phỏng được câu trả lời từ số liệu thật.</p>
<p><strong>Mốc nền.</strong> Tổn thất QALY của một đợt bệnh bằng chênh lệch giữa thỏa dụng “nếu không mắc bệnh” và thỏa dụng khi mắc; lấy 1 làm mốc là bỏ qua việc người cùng tuổi vốn không hoàn toàn khỏe <span class="citation" data-cites="ara2010populating">(<a href="#ref-ara2010populating" role="doc-biblioref">Ara và Brazier 2010</a>)</span>. Số liệu chuẩn quốc gia, tính bằng bộ giá trị Việt Nam, cho 0.94 ở mọi tuổi và giảm dần theo tuổi: 0.92 ở nhóm 45–54, 0.91 ở 55–64 và 0.89 từ 65 tuổi <span class="citation" data-cites="mai2022reference">(<a href="#ref-mai2022reference" role="doc-biblioref">Mai và c.s. 2022</a>)</span>. Khảo sát Hà Nội cho 0.91 nhưng tính bằng bộ giá trị Thái Lan <span class="citation" data-cites="nguyen2017quality">(<a href="#ref-nguyen2017quality" role="doc-biblioref">Nguyen và c.s. 2017</a>)</span>; khảo sát người bệnh lao lấy đúng số này làm mốc so sánh, nên chia 0.83 cho nó là chia hai số của hai bộ giá trị. Điều chỉnh nhân (multiplicative) giữ <em>tỷ số</em> giữa thỏa dụng khi bệnh và mốc của cùng quần thể rồi áp lên mốc của quần thể mô hình; tỷ số chỉ có nghĩa khi hai số cùng bộ giá trị.</p>
</section>
<section id="trọng-số-bệnh-tật-và-daly" class="level3">
<h3 class="anchored" data-anchor-id="trọng-số-bệnh-tật-và-daly">Trọng số bệnh tật và DALY</h3>
<p>DALY là tổng số năm sống mất do tử vong sớm (YLL) và số năm sống với bệnh tật (YLD) <span class="citation" data-cites="murray1994quantifying">(<a href="#ref-murray1994quantifying" role="doc-biblioref">Murray 1994</a>)</span>:</p>
<p><span class="math display">\[
\text{DALY} = \underbrace{e(a)}_{\text{YLL}} + \underbrace{\text{DW} \times L}_{\text{YLD}},
\]</span></p>
<p>với <span class="math inline">\(e(a)\)</span> là kỳ vọng sống còn lại ở tuổi tử vong <span class="math inline">\(a\)</span>, DW là trọng số bệnh tật và <span class="math inline">\(L\)</span> là thời gian sống với bệnh. Khi chiết khấu với tỷ lệ <span class="math inline">\(r\)</span> liên tục, một khoảng thời gian <span class="math inline">\(T\)</span> được thay bằng <span class="math inline">\((1 - e^{-\rho T})/\rho\)</span> với <span class="math inline">\(\rho = \ln(1+r)\)</span>.</p>
<p>Trọng số bệnh tật được ước lượng trong các nghiên cứu Gánh nặng bệnh tật toàn cầu (GBD) <span class="citation" data-cites="salomon2015disability gbd2020global">(<a href="#ref-salomon2015disability" role="doc-biblioref">Salomon và c.s. 2015</a>; <a href="#ref-gbd2020global" role="doc-biblioref">GBD 2019 Diseases and Injuries Collaborators 2020</a>)</span>. Với lao không nhiễm HIV, trọng số GBD 2013 và 2019 là 0.333 (khoảng bất định 0.224–0.454); với lao đồng nhiễm HIV là 0.408 <span class="citation" data-cites="tomeny2024rethinking">(<a href="#ref-tomeny2024rethinking" role="doc-biblioref">Tomeny và c.s. 2024</a>)</span>. Chưa có trọng số riêng cho MDR/RR-TB, nên dùng 0.333 cho một đợt lao kháng thuốc là giả định cần thử độ nhạy. QALY và DALY có thể cho kết luận khác nhau ở một số bài toán <span class="citation" data-cites="augustovski2018measuring">(<a href="#ref-augustovski2018measuring" role="doc-biblioref">Augustovski và c.s. 2018</a>)</span>.</p>
<p><strong>Bảng sống cho YLL.</strong> Bảng quốc gia cho kỳ vọng sống còn lại thực tế trong nước. Bảng sống tham chiếu (reference life table) là một bảng chung cho mọi nước, nên cùng một ca tử vong ở cùng tuổi mất cùng số năm ở mọi nơi; hướng dẫn tính DALY cho COVID-19 nêu cả hai và cho rằng bảng khát vọng thích hợp hơn khi cần so sánh quốc tế <span class="citation" data-cites="wyper2021burden">(<a href="#ref-wyper2021burden" role="doc-biblioref">Wyper và c.s. 2021</a>)</span>. Lựa chọn này đổi YLL đáng kể: ở Nepal, YLL thấp hơn 27% ở nam và 21% ở nữ khi dùng bảng quốc gia thay bảng sống tham chiếu GBD 2021 <span class="citation" data-cites="tonnelier2026years">(<a href="#ref-tonnelier2026years" role="doc-biblioref">Tonnelier và c.s. 2026</a>)</span>. Phần thực hành chỉ dùng bảng quốc gia.</p>
</section>
<section id="bảng-sống-dùng-chung-của-khóa-học" class="level3">
<h3 class="anchored" data-anchor-id="bảng-sống-dùng-chung-của-khóa-học">Bảng sống dùng chung của khóa học</h3>
<p>Bảng sống rút gọn đi từ tỷ suất chết theo nhóm tuổi <span class="math inline">\(_nM_x\)</span> đến kỳ vọng sống <span class="math inline">\(e_x\)</span>:</p>
<p><span class="math display">\[
{}_nq_x = \frac{n\,{}_nM_x}{1 + (n - {}_na_x)\,{}_nM_x}, \quad
l_{x+n} = l_x (1 - {}_nq_x), \quad
{}_nL_x = n\, l_{x+n} + {}_na_x\, {}_nd_x, \quad
e_x = \frac{\sum_{y \ge x} {}_nL_y}{l_x},
\]</span></p>
<p>với <span class="math inline">\(_na_x\)</span> là số năm sống trung bình trong khoảng của người chết trong khoảng đó. Nhóm tuổi cuối mở, nên <span class="math inline">\(L = l/M\)</span>.</p>
<p>Khóa học dùng <strong>một</strong> bảng sống cho mọi module: bảng của Tổ chức Y tế Thế giới cho Việt Nam năm 2023, theo hai giới và từng giới, lưu ở <code>_shared/data/vn_lifetable.csv</code> <span class="citation" data-cites="who2026lifetables">(<a href="#ref-who2026lifetables" role="doc-biblioref">World Health Organization 2026</a>)</span>. Hàm <code>vn_lifetable()</code> đọc bảng; <code>vn_mx()</code> trả tỷ suất chết năm ở một tuổi bất kỳ. Khi WHO công bố bảng mới, chỉ cần dựng lại tệp đó, mọi mô hình cập nhật theo. Trong mô hình chu kỳ tháng, tỷ suất năm <span class="math inline">\(M\)</span> đổi thành xác suất tháng bằng <span class="math inline">\(p = 1 - e^{-M/12}\)</span>, như M02 Bài 2.</p>
<p><strong>Hai nguồn chính thức bất đồng.</strong> Tuổi thọ khi sinh hai giới của WHO (2023) và của Cục Thống kê (2025) <span class="citation" data-cites="gso2026population2025">(<a href="#ref-gso2026population2025" role="doc-biblioref">Cục Thống kê (Bộ Tài chính) 2026</a>)</span> gần nhau, nhưng theo giới thì không: Cục Thống kê cho nam cao hơn 2.2 năm và nữ thấp hơn 1.2 năm. Hai cơ quan dùng số liệu, phương pháp và năm khác nhau; ta chưa biết bên nào đúng hơn. Với mô hình lao, nơi phần lớn người bệnh là nam, chênh lệch này đi thẳng vào YLL, nên hãy nêu nó trong báo cáo và thử độ nhạy.</p>
</section>
</section>
<section id="thực-hành" class="level2">
<h2 class="anchored" data-anchor-id="thực-hành">Thực hành</h2>
<p>Nạp bảng tham số kết cục, các giá trị dùng chung và bảng sống cũ dùng cho bài tập.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">isTRUE</span>(<span class="fu">l10n_info</span>()[[<span class="st">"UTF-8"</span>]])) <span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_CTYPE"</span>, <span class="st">"en_US.UTF-8"</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/helpers.R"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/vn_data.R"</span>)   <span class="co"># shared life table (vn_lifetable, vn_mx) and discount rate</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"code/model.R"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>ctx <span class="ot">&lt;-</span> <span class="fu">vn_context</span>()</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>po <span class="ot">&lt;-</span> <span class="fu">read_params</span>(<span class="st">"params/outcomes.csv"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>pg <span class="ot">&lt;-</span> <span class="fu">read_params</span>(<span class="st">"params/lifetable_gso2009.csv"</span>)   <span class="co"># old GSO table, used only in Exercise 3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dựng ma trận mức giảm cộng dồn từ các hệ số gia tăng, rồi tính lại bảy trạng thái tác giả đã công bố. Kiểm tra: chênh lệch dưới 0.0005 (các hệ số công bố đã làm tròn bốn chữ số) và mức giảm không giảm khi mức độ tăng.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cumulative decrements per dimension and level (level 1 = no problems = 0)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> <span class="fu">eq5d_decrements</span>(po)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(D, <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   1      2      3      4      5
mo 0 0.0692 0.0785 0.2064 0.3761
sc 0 0.0428 0.0460 0.1472 0.2313
ua 0 0.0464 0.0587 0.1735 0.2989
pd 0 0.0839 0.1521 0.2700 0.3665
ad 0 0.0638 0.1127 0.1715 0.2390</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reproduce the values the authors published for a few health states</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>chk_states <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"12111"</span>, <span class="st">"11211"</span>, <span class="st">"11112"</span>, <span class="st">"21111"</span>, <span class="st">"11121"</span>, <span class="st">"12345"</span>, <span class="st">"55555"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>chk <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">state =</span> chk_states,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">published =</span> <span class="fu">unlist</span>(po[<span class="fu">paste0</span>(<span class="st">"eq_chk_"</span>, chk_states)]),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">computed =</span> <span class="fu">eq5d_value</span>(chk_states, D))</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>chk<span class="sc">$</span>diff <span class="ot">&lt;-</span> chk<span class="sc">$</span>computed <span class="sc">-</span> chk<span class="sc">$</span>published</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>chk</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             state published computed   diff
eq_chk_12111 12111    0.9573   0.9572 -1e-04
eq_chk_11211 11211    0.9536   0.9536  0e+00
eq_chk_11112 11112    0.9362   0.9362  0e+00
eq_chk_21111 21111    0.9308   0.9308  0e+00
eq_chk_11121 11121    0.9161   0.9161  0e+00
eq_chk_12345 12345    0.3897   0.3895 -2e-04
eq_chk_55555 55555   -0.5115  -0.5118 -3e-04</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Published increments are rounded to 4 decimals, so expect differences below 0.0005</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(chk<span class="sc">$</span>diff) <span class="sc">&lt;</span> <span class="fl">5e-4</span>), <span class="fu">all</span>(<span class="fu">apply</span>(D, <span class="dv">1</span>, diff) <span class="sc">&gt;=</span> <span class="dv">0</span>))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Why not draw the 20 increments independently from normal(value, SE)? The published SEs are</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># large next to some increments, so a draw can make a worse level score higher (negative increment).</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>tabo <span class="ot">&lt;-</span> <span class="fu">attr</span>(po, <span class="st">"table"</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>inc <span class="ot">&lt;-</span> tabo[<span class="fu">grepl</span>(<span class="st">"^eq_(mo|sc|ua|pd|ad)_[2-5]$"</span>, tabo<span class="sc">$</span>name), ]</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>p_neg <span class="ot">&lt;-</span> <span class="fu">setNames</span>(<span class="fu">pnorm</span>(<span class="dv">0</span>, inc<span class="sc">$</span>value, inc<span class="sc">$</span>dist_p2), inc<span class="sc">$</span>name)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>p_any_neg <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">prod</span>(<span class="dv">1</span> <span class="sc">-</span> p_neg)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">sort</span>(p_neg, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>eq_sc_3 eq_mo_3 eq_ua_3 
  0.355   0.143   0.064 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>p_any_neg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4825094</code></pre>
</div>
</div>
<p>Chênh lệch lớn nhất là 0.0003, đúng cỡ sai số làm tròn. Nếu hàm của bạn lệch hàng phần trăm, gần như chắc chắn bạn đã cộng nhầm hệ số gia tăng thành hệ số cộng dồn hoặc ngược lại.</p>
<p><strong>Lưu ý về PSA.</strong> Không nên rút 20 hệ số này độc lập từ phân phối chuẩn quanh giá trị công bố: sai số chuẩn lớn so với một số hệ số (ví dụ <code>eq_sc_3</code>: xác suất rút ra giá trị âm là 35%) và bài báo không công bố ma trận hiệp phương sai. Rút độc lập cho 48% bộ giá trị có ít nhất một hệ số âm. Vì thế bảng tham số giữ các hệ số cố định; độ bất định nên đặt ở thỏa dụng trung bình của từng trạng thái bệnh.</p>
<p>Mô phỏng câu trả lời EQ-5D-5L cho 585 người bệnh: mức của từng khía cạnh rút từ phân bố năm mức mà khảo sát người bệnh lao công bố lúc bắt đầu điều trị <span class="citation" data-cites="vo2025life">(<a href="#ref-vo2025life" role="doc-biblioref">Vo và c.s. 2025</a>)</span>. Kiểm tra: tỷ lệ có vấn đề trong mẫu mô phỏng gần với khảo sát.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulated EQ-5D-5L answers for a cohort the size of the Vietnamese TB survey. Each dimension's</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># level is drawn from the level shares the survey published at the start of treatment.</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">909</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>shares <span class="ot">&lt;-</span> <span class="fu">eq5d_level_shares</span>(po, po<span class="sc">$</span>n_vo)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(shares, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1     2     3     4     5
mo 0.696 0.226 0.026 0.048 0.005
sc 0.904 0.070 0.009 0.012 0.005
ua 0.662 0.219 0.038 0.044 0.038
pd 0.462 0.388 0.074 0.072 0.005
ad 0.650 0.217 0.058 0.072 0.003</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>lv <span class="ot">&lt;-</span> <span class="fu">simulate_eq5d</span>(po<span class="sc">$</span>n_vo, shares)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>u_sim <span class="ot">&lt;-</span> <span class="fu">eq5d_value</span>(lv, D)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>sim_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">length</span>(u_sim), <span class="at">mean_utility =</span> <span class="fu">mean</span>(u_sim),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">share_full_health =</span> <span class="fu">mean</span>(u_sim <span class="sc">==</span> <span class="dv">1</span>), <span class="at">share_negative =</span> <span class="fu">mean</span>(u_sim <span class="sc">&lt;</span> <span class="dv">0</span>),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">published_mean =</span> po<span class="sc">$</span>u_tb_start</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>sim_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    n mean_utility share_full_health share_negative published_mean
1 585    0.8411056         0.1435897              0           0.83</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check: simulated shares with any problem are close to the survey (Monte Carlo noise only)</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">rbind</span>(<span class="at">survey =</span> <span class="dv">1</span> <span class="sc">-</span> shares[, <span class="dv">1</span>], <span class="at">simulated =</span> <span class="fu">colMeans</span>(lv <span class="sc">&gt;</span> <span class="dv">1</span>)), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             mo    sc    ua    pd    ad
survey    0.304 0.096 0.338 0.538 0.350
simulated 0.313 0.068 0.364 0.509 0.333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(u_sim <span class="sc">&lt;=</span> <span class="dv">1</span>), <span class="fu">all</span>(<span class="fu">abs</span>(<span class="fu">colMeans</span>(lv <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> shares[, <span class="dv">1</span>])) <span class="sc">&lt;</span> <span class="fl">0.06</span>))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Independence check: the survey found 11111 in 28.9% at baseline; independent draws give the product</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>p_11111_indep <span class="ot">&lt;-</span> <span class="fu">prod</span>(shares[, <span class="dv">1</span>])</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">survey =</span> po<span class="sc">$</span>share_11111_tb, <span class="at">independent =</span> p_11111_indep, <span class="at">simulated =</span> sim_tab<span class="sc">$</span>share_full_health)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     survey independent   simulated 
  0.2890000   0.1247754   0.1435897 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(p_11111_indep <span class="sc">&lt;</span> po<span class="sc">$</span>share_11111_tb)   <span class="co"># independence understates "no problems at all"</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>sim_gap <span class="ot">&lt;-</span> sim_tab<span class="sc">$</span>mean_utility <span class="sc">-</span> po<span class="sc">$</span>u_tb_start</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Thỏa dụng trung bình của mẫu mô phỏng là 0.841, cao hơn giá trị công bố 0.83 là 0.011. Mô phỏng giả định năm khía cạnh độc lập, và giả định đó sai rõ: khảo sát thấy 28.9% người trả lời 11111, còn rút độc lập chỉ cho 12.5% (mô phỏng: 14.4%). Ở người bệnh thật, đau, mệt và lo lắng đi cùng nhau, nên người “không có vấn đề gì” nhiều hơn và người có vấn đề thì có nhiều vấn đề cùng lúc. Khi cần hồ sơ đầy đủ, hãy xin số liệu cá nhân thay vì mô phỏng từ phân bố biên.</p>
<p>Vẽ phân bố thỏa dụng của mẫu mô phỏng. Kiểm tra bằng mắt: vạch đỏ (mô phỏng) gần vạch xanh lá (khảo sát), và có một cột ở 1 (trạng thái 11111).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>fig_u <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">u =</span> u_sim), <span class="fu">aes</span>(u)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.025</span>, <span class="at">fill =</span> pal_course[<span class="dv">1</span>], <span class="at">colour =</span> <span class="st">"white"</span>, <span class="at">boundary =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(u_sim), <span class="at">colour =</span> pal_course[<span class="dv">2</span>], <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> po<span class="sc">$</span>u_tb_start, <span class="at">colour =</span> pal_course[<span class="dv">3</span>], <span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Giá trị thỏa dụng (bộ giá trị EQ-5D-5L Việt Nam)"</span>, <span class="at">y =</span> <span class="st">"Số người"</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">"Thỏa dụng của "</span>, <span class="fu">fmt_num</span>(po<span class="sc">$</span>n_vo), <span class="st">" hồ sơ EQ-5D-5L mô phỏng"</span>),</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Vạch đỏ: trung bình mô phỏng; vạch xanh lá đứt: trung bình khảo sát"</span>) <span class="sc">+</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_u, <span class="st">"l03-utility-sim.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-l03-utility" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-l03-utility-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="l03-outcome-inputs_files/figure-html/fig-l03-utility-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-l03-utility-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;49.1: Phân bố thỏa dụng của các hồ sơ EQ-5D-5L mô phỏng từ phân bố mức của người bệnh lao, tính bằng bộ giá trị Việt Nam.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Tính tổn thất QALY của một đợt bệnh dài 0.5 năm (khoảng 24 tuần điều trị BPaLM <span class="citation" data-cites="nyangwa2022week">(<a href="#ref-nyangwa2022week" role="doc-biblioref">Nyang’wa và c.s. 2022</a>)</span>) với bốn mốc nền. Cột <code>loss_flat</code> áp thỏa dụng lúc bắt đầu lên cả đợt; cột <code>loss_path</code> dùng trung bình của đường đi tuyến tính đến thỏa dụng sau điều trị. Kiểm tra: <code>loss_path</code> nhỏ hơn <code>loss_flat</code>, và mốc càng cao tổn thất càng lớn.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># QALY loss of one treated TB episode depends on which "healthy" baseline you subtract from.</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The survey's median age is 51, so the age-matched national norm (45-54) is the natural baseline.</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>baselines <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Sức khỏe hoàn hảo"</span> <span class="ot">=</span> <span class="dv">1</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Chuẩn quốc gia, mọi tuổi (Mai 2022)"</span> <span class="ot">=</span> po<span class="sc">$</span>u_norm_mai,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Chuẩn quốc gia, 45–54 tuổi (Mai 2022)"</span> <span class="ot">=</span> po<span class="sc">$</span>u_norm_45_54,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Dân số Hà Nội, bộ giá trị Thái Lan (Nguyen 2017)"</span> <span class="ot">=</span> po<span class="sc">$</span>u_norm_hanoi)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># During treatment utility moves from the start value to the post-treatment value:</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="co"># a straight line gives the episode average. The flat version uses the start value throughout.</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>u_episode <span class="ot">&lt;-</span> (po<span class="sc">$</span>u_tb_start <span class="sc">+</span> po<span class="sc">$</span>u_tb_post) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>b_vals <span class="ot">&lt;-</span> <span class="fu">unname</span>(baselines)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>qaly_loss <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">baseline =</span> <span class="fu">names</span>(baselines), <span class="at">u_baseline =</span> b_vals,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>                        <span class="at">loss_flat =</span> (b_vals <span class="sc">-</span> po<span class="sc">$</span>u_tb_start) <span class="sc">*</span> po<span class="sc">$</span>dur_episode,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>                        <span class="at">loss_path =</span> (b_vals <span class="sc">-</span> u_episode) <span class="sc">*</span> po<span class="sc">$</span>dur_episode)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>qaly_loss</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                          baseline u_baseline loss_flat
1                                Sức khỏe hoàn hảo       1.00     0.085
2              Chuẩn quốc gia, mọi tuổi (Mai 2022)       0.94     0.055
3            Chuẩn quốc gia, 45–54 tuổi (Mai 2022)       0.92     0.045
4 Dân số Hà Nội, bộ giá trị Thái Lan (Nguyen 2017)       0.91     0.040
  loss_path
1    0.0675
2    0.0375
3    0.0275
4    0.0225</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(qaly_loss<span class="sc">$</span>loss_path <span class="sc">&lt;</span> qaly_loss<span class="sc">$</span>loss_flat), <span class="fu">all</span>(<span class="fu">diff</span>(qaly_loss<span class="sc">$</span>loss_path) <span class="sc">&lt;=</span> <span class="dv">0</span>))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>loss_days_age <span class="ot">&lt;-</span> qaly_loss<span class="sc">$</span>loss_path[<span class="dv">3</span>] <span class="sc">*</span> <span class="dv">365</span>   <span class="co"># in days of full health</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiplicative transfer keeps the ratio of two utilities that share ONE value set.</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Same value set (Vietnamese), age-matched baseline, moved to people aged 65+:</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>u_rel_same <span class="ot">&lt;-</span> <span class="fu">utility_relative</span>(po<span class="sc">$</span>u_tb_start, po<span class="sc">$</span>u_norm_45_54, po<span class="sc">$</span>u_norm_65plus)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Mismatch: dividing the Vietnamese-value-set utility by a Thai-value-set baseline</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>u_rel_mixed <span class="ot">&lt;-</span> <span class="fu">utility_relative</span>(po<span class="sc">$</span>u_tb_start, po<span class="sc">$</span>u_norm_hanoi, po<span class="sc">$</span>u_norm_65plus)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">same_value_set =</span> u_rel_same, <span class="at">mixed_value_sets =</span> u_rel_mixed, <span class="at">error =</span> u_rel_mixed <span class="sc">-</span> u_rel_same)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  same_value_set mixed_value_sets            error 
     0.802934783      0.811758242      0.008823459 </code></pre>
</div>
</div>
<p>Lấy 1 làm mốc cho tổn thất 0.0675 QALY, gấp 2.5 lần khi lấy mốc cùng tuổi 0.92 (0.0275 QALY, khoảng 10 ngày sống khỏe mạnh); ngay cả mốc quốc gia mọi tuổi cũng làm tổn thất lớn thêm 36%. Về điều chỉnh nhân, chuyển thỏa dụng của người bệnh sang người từ 65 tuổi (mốc 0.89): cùng bộ giá trị cho 0.803; chia nhầm cho mốc Thái Lan cho 0.812, lệch 0.009.</p>
<p>Bây giờ đến bảng sống dùng chung. Nạp ba bảng (hai giới, nam, nữ) và kiểm tra trước khi dùng: số năm sống trung bình của người chết trong mỗi nhóm, suy ra từ chính cặp <span class="math inline">\(M_x\)</span>, <span class="math inline">\(q_x\)</span> của WHO, phải nằm giữa 0 và độ rộng nhóm; dựng lại bảng từ <span class="math inline">\(M_x\)</span> phải trả lại đúng <span class="math inline">\(q_x\)</span>. Kiểm tra: cả hai điều kiện đúng, và tuổi thọ dựng lại lệch WHO dưới nửa năm.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The course life table: WHO Global Health Observatory, Viet Nam 2023, abridged, by sex.</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>lt_who <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">both =</span> <span class="fu">vn_lifetable</span>(<span class="st">"both"</span>), <span class="at">male =</span> <span class="fu">vn_lifetable</span>(<span class="st">"male"</span>), <span class="at">female =</span> <span class="fu">vn_lifetable</span>(<span class="st">"female"</span>))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(lt_who<span class="sc">$</span>both[, <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"age_width"</span>, <span class="st">"mx"</span>, <span class="st">"qx"</span>, <span class="st">"ex"</span>)], <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  age age_width          mx          qx       ex
1   0         1 0.012584942 0.012443996 74.31004
2   1         4 0.001383372 0.005515178 74.24515
3   5         5 0.000198837 0.000993689 70.64802
4  10         5 0.000332251 0.001659876 65.71581</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check a published table before using it. Step 1: the average years lived by those who die in</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># each group, implied by WHO's own (mx, qx) pair. It must lie between 0 and the group width.</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>ax_who <span class="ot">&lt;-</span> <span class="fu">lapply</span>(lt_who, <span class="cf">function</span>(t) <span class="fu">implied_ax</span>(t<span class="sc">$</span>age, t<span class="sc">$</span>mx, t<span class="sc">$</span>qx))</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(ax_who<span class="sc">$</span>both[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>], <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.10 1.60 2.49 2.50 2.50</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">vapply</span>(ax_who, <span class="cf">function</span>(a) <span class="fu">all</span>(a[<span class="sc">-</span><span class="dv">19</span>] <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> a[<span class="sc">-</span><span class="dv">19</span>] <span class="sc">&lt;</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="fu">rep</span>(<span class="dv">5</span>, <span class="dv">16</span>))), <span class="fu">logical</span>(<span class="dv">1</span>))))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: rebuild the table from mx with those a(x). qx must come back exactly; e(x) may differ</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># only through the open 85+ group, where our L = l / M is a simplification.</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>rebuilt <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">names</span>(lt_who), <span class="cf">function</span>(s) {</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  t <span class="ot">&lt;-</span> lt_who[[s]]</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">life_table</span>(t<span class="sc">$</span>age, t<span class="sc">$</span>mx, <span class="at">ax =</span> ax_who[[s]])</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(rebuilt) <span class="ot">&lt;-</span> <span class="fu">names</span>(lt_who)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">vapply</span>(<span class="fu">names</span>(lt_who), <span class="cf">function</span>(s)</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">max</span>(<span class="fu">abs</span>(rebuilt[[s]]<span class="sc">$</span>qx[<span class="sc">-</span><span class="dv">19</span>] <span class="sc">/</span> lt_who[[s]]<span class="sc">$</span>qx[<span class="sc">-</span><span class="dv">19</span>] <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">&lt;</span> <span class="fl">1e-8</span>, <span class="fu">logical</span>(<span class="dv">1</span>))))</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>e0_check <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">sex =</span> <span class="fu">c</span>(<span class="st">"Hai giới"</span>, <span class="st">"Nam"</span>, <span class="st">"Nữ"</span>),</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>                       <span class="at">who_published =</span> <span class="fu">vapply</span>(lt_who, <span class="cf">function</span>(t) t<span class="sc">$</span>ex[<span class="dv">1</span>], <span class="fu">numeric</span>(<span class="dv">1</span>)),</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>                       <span class="at">rebuilt =</span> <span class="fu">vapply</span>(rebuilt, <span class="cf">function</span>(t) t<span class="sc">$</span>ex[<span class="dv">1</span>], <span class="fu">numeric</span>(<span class="dv">1</span>)),</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>                       <span class="at">gso_2025 =</span> <span class="fu">c</span>(ctx<span class="sc">$</span>life_expectancy_birth, ctx<span class="sc">$</span>life_expectancy_birth_male,</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>                                    ctx<span class="sc">$</span>life_expectancy_birth_female))</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>e0_check<span class="sc">$</span>rebuilt_minus_who <span class="ot">&lt;-</span> e0_check<span class="sc">$</span>rebuilt <span class="sc">-</span> e0_check<span class="sc">$</span>who_published</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>e0_check<span class="sc">$</span>gso_minus_who <span class="ot">&lt;-</span> e0_check<span class="sc">$</span>gso_2025 <span class="sc">-</span> e0_check<span class="sc">$</span>who_published</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>e0_check</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            sex who_published  rebuilt gso_2025 rebuilt_minus_who gso_minus_who
both   Hai giới      74.31004 74.36232     74.7        0.05227175     0.3899564
male        Nam      70.13150 70.14528     72.3        0.01378379     2.1685005
female       Nữ      78.46587 78.55881     77.3        0.09294126    -1.1658703</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(e0_check<span class="sc">$</span>rebuilt_minus_who) <span class="sc">&lt;</span> <span class="fl">0.5</span>))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The text: the two agencies agree for both sexes (within 1 year) but GSO is higher for men, lower for women</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(e0_check<span class="sc">$</span>gso_minus_who[<span class="dv">1</span>]) <span class="sc">&lt;</span> <span class="dv">1</span>, e0_check<span class="sc">$</span>gso_minus_who[<span class="dv">2</span>] <span class="sc">&gt;</span> <span class="dv">0</span>, e0_check<span class="sc">$</span>gso_minus_who[<span class="dv">3</span>] <span class="sc">&lt;</span> <span class="dv">0</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Beyond age 5, WHO's a(x) is close to n/2: largest deviation in years</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>ax_dev <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">vapply</span>(ax_who, <span class="cf">function</span>(a) <span class="fu">max</span>(<span class="fu">abs</span>(a[<span class="dv">3</span><span class="sc">:</span><span class="dv">18</span>] <span class="sc">-</span> <span class="fl">2.5</span>)), <span class="fu">numeric</span>(<span class="dv">1</span>)))</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="co"># The open group explains the small gap: WHO's e(85+) against 1 / M(85+)</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>open_gap <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">who_e85 =</span> lt_who<span class="sc">$</span>both<span class="sc">$</span>ex[<span class="dv">19</span>], <span class="at">one_over_m85 =</span> <span class="dv">1</span> <span class="sc">/</span> lt_who<span class="sc">$</span>both<span class="sc">$</span>mx[<span class="dv">19</span>])</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>open_gap</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     who_e85 one_over_m85 
    4.446465     4.627411 </code></pre>
</div>
</div>
<p>Bảng WHO qua được kiểm tra: <span class="math inline">\(a_0\)</span> = 0.10, <span class="math inline">\(a_{1\text{–}4}\)</span> = 1.60, các nhóm còn lại xấp xỉ <span class="math inline">\(n/2\)</span> (lệch tối đa 0.010 năm), và <span class="math inline">\(q_x\)</span> dựng lại trùng khớp. Tuổi thọ khi sinh dựng lại lệch 0.05 năm, chỉ do nhóm mở 85+: WHO cho <span class="math inline">\(e_{85}\)</span> = 4.45 năm, còn <span class="math inline">\(1/M_{85+}\)</span> = 4.63. Cột cuối của bảng là điều cần ghi vào báo cáo: so với Cục Thống kê, WHO thấp hơn 2.2 năm ở nam và cao hơn 1.2 năm ở nữ.</p>
<p>Vẽ tỷ suất chết theo tuổi và giới (thang log). Kiểm tra bằng mắt (code đã kiểm tra điều đầu): đường nam nằm trên đường nữ ở mọi tuổi trưởng thành, và trên thang log cả hai tăng gần như theo đường thẳng sau 40 tuổi.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>lt_long <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">age =</span> lt_who<span class="sc">$</span>male<span class="sc">$</span>age, <span class="at">mx =</span> lt_who<span class="sc">$</span>male<span class="sc">$</span>mx, <span class="at">sex =</span> <span class="st">"Nam"</span>),</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">age =</span> lt_who<span class="sc">$</span>female<span class="sc">$</span>age, <span class="at">mx =</span> lt_who<span class="sc">$</span>female<span class="sc">$</span>mx, <span class="at">sex =</span> <span class="st">"Nữ"</span>))</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>fig_lt <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(lt_long, <span class="fu">aes</span>(age, mx, <span class="at">colour =</span> sex)) <span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_step</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> po<span class="sc">$</span>age_tb, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> pal_course[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)], <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tuổi (đầu nhóm tuổi)"</span>, <span class="at">y =</span> <span class="st">"Tỷ suất chết mỗi năm (thang log)"</span>,</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Bảng sống Việt Nam 2023 (WHO): tỷ suất chết theo tuổi và giới"</span>,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Nét đứt: tuổi trung vị của người bệnh lao trong khảo sát EQ-5D-5L"</span>) <span class="sc">+</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_lt, <span class="st">"l03-lifetable.png"</span>)</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a><span class="co"># What the text asks the reader to see: male death rates above female ones at every adult age</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>adult <span class="ot">&lt;-</span> lt_who<span class="sc">$</span>male<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">15</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(lt_who<span class="sc">$</span>male<span class="sc">$</span>mx[adult] <span class="sc">&gt;</span> lt_who<span class="sc">$</span>female<span class="sc">$</span>mx[adult]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-l03-lifetable" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-l03-lifetable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="l03-outcome-inputs_files/figure-html/fig-l03-lifetable-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-l03-lifetable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;49.2: Tỷ suất chết theo tuổi và giới, bảng sống WHO cho Việt Nam năm 2023 (thang log), lấy từ tệp dùng chung của khóa học.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Lấy ra các đầu vào mô hình ở tuổi 51: tỷ suất chết nền từ <code>vn_mx()</code>, xác suất chết mỗi tháng, và kỳ vọng sống còn lại; gộp hai giới theo tỷ lệ nữ của người bệnh lao (23.6%), không theo dân số chung. Kiểm tra: xác suất tháng dương và nhỏ, nam cao hơn nữ.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># From the shared table to model inputs at the median age of the TB survey. Death RATES come from</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co"># vn_mx() (a step function over the age groups); a monthly cycle needs p = 1 - exp(-m / 12).</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>age0 <span class="ot">&lt;-</span> po<span class="sc">$</span>age_tb</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>w_f <span class="ot">&lt;-</span> po<span class="sc">$</span>share_female_tb</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>mx_m <span class="ot">&lt;-</span> <span class="fu">vn_mx</span>(age0, <span class="st">"male"</span>); mx_f <span class="ot">&lt;-</span> <span class="fu">vn_mx</span>(age0, <span class="st">"female"</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>use_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">sex =</span> <span class="fu">c</span>(<span class="st">"Nam"</span>, <span class="st">"Nữ"</span>, <span class="st">"Gộp theo tỷ lệ giới của người bệnh lao"</span>, <span class="st">"Hai giới (dân số chung)"</span>),</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">mx_year =</span> <span class="fu">c</span>(mx_m, mx_f, (<span class="dv">1</span> <span class="sc">-</span> w_f) <span class="sc">*</span> mx_m <span class="sc">+</span> w_f <span class="sc">*</span> mx_f, <span class="fu">vn_mx</span>(age0, <span class="st">"both"</span>)),</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">ex =</span> <span class="fu">c</span>(<span class="fu">ex_at</span>(age0, lt_who<span class="sc">$</span>male), <span class="fu">ex_at</span>(age0, lt_who<span class="sc">$</span>female),</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>         (<span class="dv">1</span> <span class="sc">-</span> w_f) <span class="sc">*</span> <span class="fu">ex_at</span>(age0, lt_who<span class="sc">$</span>male) <span class="sc">+</span> w_f <span class="sc">*</span> <span class="fu">ex_at</span>(age0, lt_who<span class="sc">$</span>female),</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>         <span class="fu">ex_at</span>(age0, lt_who<span class="sc">$</span>both))</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>use_tab<span class="sc">$</span>p_month <span class="ot">&lt;-</span> <span class="fu">rate_to_prob</span>(use_tab<span class="sc">$</span>mx_year, <span class="at">t =</span> <span class="dv">1</span> <span class="sc">/</span> <span class="dv">12</span>)</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>use_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                     sex     mx_year       ex      p_month
1                                    Nam 0.008568435 24.46664 0.0007137814
2                                     Nữ 0.003205295 30.12195 0.0002670722
3 Gộp theo tỷ lệ giới của người bệnh lao 0.007302734 25.80129 0.0006083760
4                Hai giới (dân số chung) 0.005822342 27.45405 0.0004850775</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(use_tab<span class="sc">$</span>p_month <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> use_tab<span class="sc">$</span>p_month <span class="sc">&lt;</span> <span class="fl">0.01</span>), use_tab<span class="sc">$</span>mx_year[<span class="dv">1</span>] <span class="sc">&gt;</span> use_tab<span class="sc">$</span>mx_year[<span class="dv">2</span>])</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>male_over_female <span class="ot">&lt;-</span> mx_m <span class="sc">/</span> mx_f</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ở tuổi 51, tỷ suất chết nền của nam gấp 2.7 lần nữ. Gộp theo giới người bệnh lao, xác suất chết nền mỗi tháng là 0.00061 và kỳ vọng sống còn lại là 25.8 năm.</p>
<p>Cuối cùng, tính DALY cho một ca tử vong vì lao ở tuổi 51 và cho một đợt bệnh được điều trị, rồi so hai lựa chọn bảng sống cho YLL.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># DALYs for one TB death at the survey's median age and one treated episode</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>ex_mix <span class="ot">&lt;-</span> use_tab<span class="sc">$</span>ex[<span class="dv">3</span>]</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>daly_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">component =</span> <span class="fu">c</span>(<span class="st">"YLL (một ca tử vong)"</span>, <span class="st">"YLD (một đợt bệnh, lao không HIV)"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>                <span class="st">"YLD (một đợt bệnh, lao đồng nhiễm HIV)"</span>),</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">undiscounted =</span> <span class="fu">c</span>(<span class="fu">disc_duration</span>(ex_mix, <span class="dv">0</span>), <span class="fu">yld</span>(po<span class="sc">$</span>dw_tb, po<span class="sc">$</span>dur_episode),</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">yld</span>(po<span class="sc">$</span>dw_tbhiv, po<span class="sc">$</span>dur_episode)),</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">discounted =</span> <span class="fu">c</span>(<span class="fu">disc_duration</span>(ex_mix, ctx<span class="sc">$</span>disc_rate), <span class="fu">yld</span>(po<span class="sc">$</span>dw_tb, po<span class="sc">$</span>dur_episode, ctx<span class="sc">$</span>disc_rate),</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">yld</span>(po<span class="sc">$</span>dw_tbhiv, po<span class="sc">$</span>dur_episode, ctx<span class="sc">$</span>disc_rate))</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>daly_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                               component undiscounted discounted
1                   YLL (một ca tử vong)     25.80129 18.0512620
2      YLD (một đợt bệnh, lao không HIV)      0.16650  0.1652757
3 YLD (một đợt bệnh, lao đồng nhiễm HIV)      0.20400  0.2024999</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(daly_tab<span class="sc">$</span>discounted <span class="sc">&lt;=</span> daly_tab<span class="sc">$</span>undiscounted))</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The choice of life table for YLL: sex mix of TB patients vs the general population</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>yll_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">table =</span> <span class="fu">c</span>(<span class="st">"WHO 2023, gộp theo giới người bệnh lao (mặc định)"</span>, <span class="st">"WHO 2023, hai giới chung"</span>),</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">yll =</span> <span class="fu">c</span>(ex_mix, use_tab<span class="sc">$</span>ex[<span class="dv">4</span>]))</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>yll_tab<span class="sc">$</span>vs_default <span class="ot">&lt;-</span> yll_tab<span class="sc">$</span>yll <span class="sc">/</span> yll_tab<span class="sc">$</span>yll[<span class="dv">1</span>] <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>yll_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                              table      yll vs_default
1 WHO 2023, gộp theo giới người bệnh lao (mặc định) 25.80129 0.00000000
2                          WHO 2023, hai giới chung 27.45405 0.06405717</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Health loss of the same episode with a disability weight vs a utility (age-matched baseline)</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>dw_loss <span class="ot">&lt;-</span> po<span class="sc">$</span>dw_tb <span class="sc">*</span> po<span class="sc">$</span>dur_episode</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">yld =</span> dw_loss, <span class="at">qaly_loss_age =</span> qaly_loss<span class="sc">$</span>loss_path[<span class="dv">3</span>], <span class="at">ratio =</span> dw_loss <span class="sc">/</span> qaly_loss<span class="sc">$</span>loss_path[<span class="dv">3</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          yld qaly_loss_age         ratio 
     0.166500      0.027500      6.054545 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(dw_loss <span class="sc">&gt;</span> qaly_loss<span class="sc">$</span>loss_path[<span class="dv">3</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Một ca tử vong mất 25.8 năm sống, còn 18.1 năm khi chiết khấu 3%. Dùng bảng hai giới của dân số chung thay vì gộp theo giới người bệnh lao làm YLL tăng 6.4%, chưa kể chênh lệch giữa bảng quốc gia và bảng sống tham chiếu. Một đợt bệnh chỉ đóng góp 0.167 YLD. Với cùng đợt bệnh, tổn thất tính bằng trọng số bệnh tật (0.167) lớn gấp 6.1 lần tổn thất QALY tính bằng thỏa dụng đo ở người bệnh Việt Nam với mốc cùng tuổi (0.0275). Hai thang đo không đổi lẫn được: trọng số GBD gắn với một trạng thái bệnh theo mô tả của GBD, còn 0.83 được đo ở người đang bắt đầu điều trị.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Mẹo thực hành">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mẹo thực hành
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Viết hàm tính thỏa dụng một lần, kiểm tra với các trạng thái tác giả công bố, rồi dùng lại.</li>
<li>Khi lấy thỏa dụng từ y văn, ghi vào cột <code>note</code>: công cụ, bộ giá trị, quần thể, tuổi, thời điểm đo.</li>
<li>Gộp bảng sống hai giới theo cơ cấu giới của <em>người bệnh</em>, không phải của dân số chung.</li>
<li>Gọi <code>vn_mx()</code> cho tử vong nền; muốn thử bảng khác (Cục Thống kê, UN WPP), viết một hàm thay thế cùng đầu vào, đầu ra để chạy phân tích độ nhạy.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Lỗi thường gặp">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lỗi thường gặp
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Nhầm hệ số gia tăng với hệ số cộng dồn.</strong> Bảng gốc của bộ giá trị Việt Nam cho mức giảm giữa hai mức liền kề; phải cộng dồn trước khi trừ.</li>
<li><strong>Dùng 1 − DW như một giá trị thỏa dụng.</strong> Trọng số bệnh tật đo tổn thất sức khỏe theo cách khác; ví dụ lao cho thấy hai cách lệch nhau nhiều lần.</li>
<li><strong>Lấy 1 hoặc chuẩn mọi tuổi làm mốc nền.</strong> Người 51 tuổi không có thỏa dụng của người 25 tuổi; dùng chuẩn cùng nhóm tuổi và cùng bộ giá trị.</li>
<li><strong>Chép bảng sống vào module, hoặc tin tuyệt đối vào bảng công bố.</strong> Dùng bảng dùng chung, và kiểm tra <span class="math inline">\(L_x \le n\,l_x\)</span> cùng việc các cột khớp nhau với mọi bảng mới.</li>
</ul>
</div>
</div>
</section>
<section id="bài-tập" class="level2">
<h2 class="anchored" data-anchor-id="bài-tập">Bài tập</h2>
<ol type="1">
<li><strong>(Dễ)</strong> Tính thỏa dụng của các hồ sơ 21232, 11122 và 33333.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 1: utility of three profiles</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>ex1_v <span class="ot">&lt;-</span> <span class="fu">eq5d_value</span>(<span class="fu">c</span>(<span class="st">"21232"</span>, <span class="st">"11122"</span>, <span class="st">"33333"</span>), D)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>ex1_v</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6685 0.8523 0.5520</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The text: all-moderate (33333) scores lowest of the three; 21232 loses most through its level-3 pain item</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(ex1_v[<span class="dv">3</span>] <span class="sc">&lt;</span> <span class="fu">min</span>(ex1_v[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]), D[<span class="st">"pd"</span>, <span class="st">"3"</span>] <span class="sc">&gt;</span> D[<span class="st">"mo"</span>, <span class="st">"2"</span>] <span class="sc">+</span> D[<span class="st">"ad"</span>, <span class="st">"2"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Trạng thái 33333 (mọi khía cạnh ở mức vừa) có thỏa dụng thấp nhất trong ba hồ sơ, 0.55, so với 0.67 của 21232 và 0.85 của 11122, vì mức giảm cộng dồn ở cả năm khía cạnh. Ở bộ giá trị Việt Nam, một mức vừa của đau/khó chịu (trừ 0.15) đã lớn hơn cộng hai mức nhẹ của đi lại và lo lắng (0.13), nên hồ sơ 21232 vẫn mất 0.33.</p>
</div>
</div>
</div>
<ol start="2" type="1">
<li><strong>(Vừa)</strong> Tính YLL chưa chiết khấu và có chiết khấu cho nam tử vong ở tuổi 30 và 70 (bảng WHO 2023). Chiết khấu ảnh hưởng nhiều hơn ở tuổi nào? Vì sao?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 2: undiscounted and discounted YLL for deaths at 30 and 70 (men, WHO 2023)</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>ex2 <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">70</span>), <span class="cf">function</span>(a) {</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  e <span class="ot">&lt;-</span> <span class="fu">ex_at</span>(a, lt_who<span class="sc">$</span>male)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">age =</span> a, <span class="at">yll =</span> e, <span class="at">yll_disc =</span> <span class="fu">disc_duration</span>(e, ctx<span class="sc">$</span>disc_rate))</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>ex2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             [,1]      [,2]
age      30.00000 70.000000
yll      42.95273 10.930891
yll_disc 24.32659  9.340753</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>ex2_cut <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> ex2[<span class="st">"yll_disc"</span>, ] <span class="sc">/</span> ex2[<span class="st">"yll"</span>, ]</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(ex2_cut[<span class="dv">1</span>] <span class="sc">&gt;</span> ex2_cut[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Chiết khấu cắt 43% YLL ở tuổi 30 nhưng chỉ 15% ở tuổi 70, vì những năm sống bị mất ở người trẻ nằm xa trong tương lai. Lựa chọn tỷ lệ chiết khấu quan trọng với bệnh gây tử vong ở người trẻ.</p>
</div>
</div>
</div>
<ol start="3" type="1">
<li><strong>(Khó)</strong> Kiểm tra bảng sống toàn quốc 2009 của Tổng cục Thống kê (Biểu 7, trang 147) <span class="citation" data-cites="gso2011census">(<a href="#ref-gso2011census" role="doc-biblioref">Tổng cục Thống kê 2011</a>)</span>, có trong <code>params/lifetable_gso2009.csv</code>. (a) Đếm số nhóm tuổi có <span class="math inline">\(L_x &gt; n\,l_x\)</span>. (b) Tính tuổi thọ khi sinh bằng <span class="math inline">\(T_0/l_0\)</span> từ cột <span class="math inline">\(L_x\)</span> công bố, và dựng lại chỉ từ cột <span class="math inline">\(l_x\)</span> (với <span class="math inline">\(a = n/2\)</span>). Bảng này có dùng được cho mô hình không?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 3: audit an old published table (GSO 2009 census life table, Biểu 7).</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Those who die in a 5-year group live at most 5 years in it, so Lx can never exceed n x lx.</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>gso <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">c</span>(<span class="at">m =</span> <span class="st">"m"</span>, <span class="at">f =</span> <span class="st">"f"</span>), <span class="cf">function</span>(s) {</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  d <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">age =</span> <span class="fu">lifetable_col</span>(pg, <span class="st">"lx"</span>, s)<span class="sc">$</span>age, <span class="at">lx =</span> <span class="fu">lifetable_col</span>(pg, <span class="st">"lx"</span>, s)<span class="sc">$</span>lx,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Lx =</span> <span class="fu">lifetable_col</span>(pg, <span class="st">"Lx"</span>, s)<span class="sc">$</span>Lx)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  d<span class="sc">$</span>n <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">diff</span>(d<span class="sc">$</span>age), <span class="cn">NA</span>)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  d</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>k_g <span class="ot">&lt;-</span> <span class="fu">nrow</span>(gso<span class="sc">$</span>m)</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>n_impossible <span class="ot">&lt;-</span> <span class="fu">vapply</span>(gso, <span class="cf">function</span>(g) <span class="fu">sum</span>(g<span class="sc">$</span>Lx[<span class="sc">-</span>k_g] <span class="sc">&gt;</span> g<span class="sc">$</span>n[<span class="sc">-</span>k_g] <span class="sc">*</span> g<span class="sc">$</span>lx[<span class="sc">-</span>k_g]), <span class="fu">numeric</span>(<span class="dv">1</span>))</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>n_impossible</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> m  f 
15 15 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Life expectancy at birth three ways: published; Tx / lx from the published Lx; rebuilt from lx</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>e0_gso <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sex =</span> <span class="fu">c</span>(<span class="st">"Nam"</span>, <span class="st">"Nữ"</span>),</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">published =</span> <span class="fu">c</span>(pg<span class="sc">$</span>e0_gso_m, pg<span class="sc">$</span>e0_gso_f),</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">from_published_Lx =</span> <span class="fu">vapply</span>(gso, <span class="cf">function</span>(g) <span class="fu">sum</span>(g<span class="sc">$</span>Lx) <span class="sc">/</span> g<span class="sc">$</span>lx[<span class="dv">1</span>], <span class="fu">numeric</span>(<span class="dv">1</span>)),</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">from_lx =</span> <span class="fu">vapply</span>(gso, <span class="cf">function</span>(g) <span class="fu">ex0_from_lx</span>(g<span class="sc">$</span>age, g<span class="sc">$</span>lx, g<span class="sc">$</span>Lx[k_g]), <span class="fu">numeric</span>(<span class="dv">1</span>))</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>e0_gso<span class="sc">$</span>gap <span class="ot">&lt;-</span> e0_gso<span class="sc">$</span>from_lx <span class="sc">-</span> e0_gso<span class="sc">$</span>published</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>e0_gso</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sex published from_published_Lx  from_lx       gap
m Nam      70.2          70.22743 68.01308 -2.186917
f  Nữ      75.6          75.60089 73.68385 -1.916149</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(e0_gso<span class="sc">$</span>from_published_Lx <span class="sc">-</span> e0_gso<span class="sc">$</span>published) <span class="sc">&lt;</span> <span class="fl">0.06</span>), <span class="fu">all</span>(e0_gso<span class="sc">$</span>gap <span class="sc">&lt;</span> <span class="dv">0</span>),</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>          n_impossible[[<span class="st">"m"</span>]] <span class="sc">&gt;</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cột <span class="math inline">\(L_x\)</span> vượt <span class="math inline">\(n\,l_x\)</span> ở 15 nhóm tuổi của nam và 15 của nữ, điều không thể xảy ra. Tuổi thọ công bố khớp với <span class="math inline">\(T_0/l_0\)</span> tính từ chính cột <span class="math inline">\(L_x\)</span> đó, nên lỗi đi thẳng vào số công bố; dựng lại từ <span class="math inline">\(l_x\)</span> cho thấp hơn 2.2 năm ở nam và 1.9 năm ở nữ. Bảng cũ (2009) và có lỗi nội bộ chưa rõ nguyên nhân; chỉ dùng để luyện kỹ năng kiểm tra. Mô hình dùng bảng dùng chung.</p>
</div>
</div>
</div>
</section>
<section id="tài-liệu-tham-khảo" class="level2">
<h2 class="anchored" data-anchor-id="tài-liệu-tham-khảo">Tài liệu tham khảo</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-ara2010populating" class="csl-entry" role="listitem">
Ara, Roberta, và John E. Brazier. 2010. <span>“Populating an economic model with health state utility values: moving toward better practice”</span>. <em>Value in Health</em> 13 (5): 509–18. <a href="https://doi.org/10.1111/j.1524-4733.2010.00700.x">https://doi.org/10.1111/j.1524-4733.2010.00700.x</a>.
</div>
<div id="ref-augustovski2018measuring" class="csl-entry" role="listitem">
Augustovski, Federico, Lisandro D. Colantonio, Julieta Galante, Ariel Bardach, Joaquín E. Caporale, Víctor Zárate, Ling Hsiang Chuang, Andres Pichon-Riviere, và Paul Kind. 2018. <span>“Measuring the benefits of healthcare: <span>DALYs</span> and <span>QALYs</span> – does the choice of measure matter? <span>A</span> case study of two preventive interventions”</span>. <em>International Journal of Health Policy and Management</em> 7 (2): 120–36. <a href="https://doi.org/10.15171/ijhpm.2017.47">https://doi.org/10.15171/ijhpm.2017.47</a>.
</div>
<div id="ref-brazier2019identification" class="csl-entry" role="listitem">
Brazier, John, Roberta Ara, Ismail Azzabi, Jan Busschbach, Hélène Chevrou-Séverac, Bruce Crawford, Luciane Cruz, và c.s. 2019. <span>“Identification, review, and use of health state utilities in cost-effectiveness models: an <span>ISPOR</span> Good Practices for Outcomes Research Task Force report”</span>. <em>Value in Health</em> 22 (3): 267–75. <a href="https://doi.org/10.1016/j.jval.2019.01.004">https://doi.org/10.1016/j.jval.2019.01.004</a>.
</div>
<div id="ref-gso2026population2025" class="csl-entry" role="listitem">
Cục Thống kê (Bộ Tài chính). 2026. <span>“Thông cáo báo chí về tình hình dân số, lao động, việc làm quý <span>IV</span> và năm 2025”</span>. 5 Tháng Giêng 2026. <a href="https://www.nso.gov.vn/?p=59530">https://www.nso.gov.vn/?p=59530</a>.
</div>
<div id="ref-gbd2020global" class="csl-entry" role="listitem">
GBD 2019 Diseases and Injuries Collaborators. 2020. <span>“Global burden of 369 diseases and injuries in 204 countries and territories, 1990–2019: a systematic analysis for the <span>Global Burden of Disease Study</span> 2019”</span>. <em>The Lancet</em> 396 (10258): 1204–22. <a href="https://doi.org/10.1016/S0140-6736(20)30925-9">https://doi.org/10.1016/S0140-6736(20)30925-9</a>.
</div>
<div id="ref-herdman2011development" class="csl-entry" role="listitem">
Herdman, M., C. Gudex, A. Lloyd, M. F. Janssen, P. Kind, D. Parkin, G. Bonsel, và X. Badia. 2011. <span>“Development and preliminary testing of the new five-level version of <span>EQ-5D</span> (<span>EQ-5D-5L</span>)”</span>. <em>Quality of Life Research</em> 20 (10): 1727–36. <a href="https://doi.org/10.1007/s11136-011-9903-x">https://doi.org/10.1007/s11136-011-9903-x</a>.
</div>
<div id="ref-mai2022reference" class="csl-entry" role="listitem">
Mai, Vu Quynh, Kim Bao Giang, Hoang Van Minh, Lars Lindholm, Sun Sun, và Klas Göran Sahlen. 2022. <span>“Reference data among general population and known-groups validity among hypertensive population of the <span>EQ-5D-5L</span> in <span>Vietnam</span>”</span>. <em>Quality of Life Research</em> 31 (2): 539–50. <a href="https://doi.org/10.1007/s11136-021-02959-2">https://doi.org/10.1007/s11136-021-02959-2</a>.
</div>
<div id="ref-mai2020eq5d5l" class="csl-entry" role="listitem">
Mai, Vu Quynh, Sun Sun, Hoang Van Minh, Nan Luo, Kim Bao Giang, Lars Lindholm, và Klas Goran Sahlen. 2020. <span>“An <span>EQ-5D-5L</span> value set for <span>Vietnam</span>”</span>. <em>Quality of Life Research</em> 29 (7): 1923–33. <a href="https://doi.org/10.1007/s11136-020-02469-7">https://doi.org/10.1007/s11136-020-02469-7</a>.
</div>
<div id="ref-murray1994quantifying" class="csl-entry" role="listitem">
Murray, C. J. 1994. <span>“<a href="https://www.ncbi.nlm.nih.gov/pubmed/8062401">Quantifying the burden of disease: the technical basis for disability-adjusted life years</a>”</span>. <em>Bulletin of the World Health Organization</em> 72 (3): 429–45.
</div>
<div id="ref-nguyen2017quality" class="csl-entry" role="listitem">
Nguyen, Long Hoang, Bach Xuan Tran, Quynh Ngoc Hoang Le, Tung Thanh Tran, và Carl A. Latkin. 2017. <span>“Quality of life profile of general <span>Vietnamese</span> population using <span>EQ-5D-5L</span>”</span>. <em>Health and Quality of Life Outcomes</em> 15 (1): 199. <a href="https://doi.org/10.1186/s12955-017-0771-0">https://doi.org/10.1186/s12955-017-0771-0</a>.
</div>
<div id="ref-nyangwa2022week" class="csl-entry" role="listitem">
Nyang’wa, Bern-Thomas, Catherine Berry, Emil Kazounis, Ilaria Motta, Nargiza Parpieva, Zinaida Tigay, Varvara Solodovnikova, và c.s. 2022. <span>“A 24-week, all-oral regimen for rifampin-resistant tuberculosis”</span>. <em>New England Journal of Medicine</em> 387 (25): 2331–43. <a href="https://doi.org/10.1056/NEJMoa2117166">https://doi.org/10.1056/NEJMoa2117166</a>.
</div>
<div id="ref-salomon2015disability" class="csl-entry" role="listitem">
Salomon, Joshua A., Juanita A. Haagsma, Adrian Davis, Charline Maertens de Noordhout, Suzanne Polinder, Arie H. Havelaar, Alessandro Cassini, và c.s. 2015. <span>“Disability weights for the <span>Global Burden of Disease</span> 2013 study”</span>. <em>The Lancet Global Health</em> 3 (11): e712–23. <a href="https://doi.org/10.1016/S2214-109X(15)00069-8">https://doi.org/10.1016/S2214-109X(15)00069-8</a>.
</div>
<div id="ref-tomeny2024rethinking" class="csl-entry" role="listitem">
Tomeny, Ewan M., Thomas Hampton, Phuong Bich Tran, Laura Rosu, Mphatso D. Phiri, Kathryn A. Haigh, Jasper Nidoi, Tom Wingfield, và Eve Worrall. 2024. <span>“Rethinking tuberculosis morbidity quantification: a systematic review and critical appraisal of <span>TB</span> disability weights in cost-effectiveness analyses”</span>. <em>PharmacoEconomics</em> 42 (11): 1209–36. <a href="https://doi.org/10.1007/s40273-024-01410-x">https://doi.org/10.1007/s40273-024-01410-x</a>.
</div>
<div id="ref-tonnelier2026years" class="csl-entry" role="listitem">
Tonnelier, Margo, Damien Delforge, Manisha Panta Bhandari, Brecht Devleesschauwer, Juanita A. Haagsma, Grant M. A. Wyper, Emilie Castin, Niko Speybroeck, và Periklis Charalampous. 2026. <span>“Years of life lost due to the 2015 <span>Gorkha</span> earthquake in <span>Nepal</span>”</span>. <em>BMC Public Health</em> 26 (1). <a href="https://doi.org/10.1186/s12889-026-27054-4">https://doi.org/10.1186/s12889-026-27054-4</a>.
</div>
<div id="ref-gso2011census" class="csl-entry" role="listitem">
Tổng cục Thống kê. 2011. <span>“Tổng điều tra dân số và nhà ở <span>Việt Nam</span> năm 2009. Mức sinh và mức chết ở <span>Việt Nam</span>: thực trạng, xu hướng và những khác biệt”</span>. Hà Nội: Tổng cục Thống kê, Bộ Kế hoạch và Đầu tư. <a href="https://vietnam.un.org/en/download/815/4126">https://vietnam.un.org/en/download/815/4126</a>.
</div>
<div id="ref-vo2025life" class="csl-entry" role="listitem">
Vo, Luan Nguyen Quang, Rachel Forse, Andrew James Codlin, Huy Ba Huynh, Anja Maria Christine Wiemers, Jacob Creswell, Tushar Garg, và c.s. 2025. <span>“A life that’s worth living – measuring health-related quality of life among people treated for tuberculosis in <span>Viet Nam</span>: a longitudinal <span>EQ-5D-5L</span> survey”</span>. <em>Health and Quality of Life Outcomes</em> 23 (1): 43. <a href="https://doi.org/10.1186/s12955-025-02369-9">https://doi.org/10.1186/s12955-025-02369-9</a>.
</div>
<div id="ref-who2026lifetables" class="csl-entry" role="listitem">
World Health Organization. 2026. <span>“Global Health Observatory: life tables by country, <span>Viet Nam</span>, 2023 (indicators <span>LIFE_0000000029</span> nMx, <span>LIFE_0000000030</span> nqx, <span>LIFE_0000000035</span> ex)”</span>. 2026. <a href="https://ghoapi.azureedge.net/api/LIFE_0000000029">https://ghoapi.azureedge.net/api/LIFE_0000000029</a>.
</div>
<div id="ref-wyper2021burden" class="csl-entry" role="listitem">
Wyper, Grant M. A., Ricardo M. A. Assunção, Edoardo Colzani, Ian Grant, Juanita A. Haagsma, Giske Lagerweij, Elena Von der Lippe, và c.s. 2021. <span>“Burden of disease methods: a guide to calculate <span>COVID-19</span> disability-adjusted life years”</span>. <em>International Journal of Public Health</em> 66: 619011. <a href="https://doi.org/10.3389/ijph.2021.619011">https://doi.org/10.3389/ijph.2021.619011</a>.
</div>
</div>
<div class="video-script">
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kịch bản video (~14 phút)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Slide</th>
<th>Lời giảng chính</th>
<th>Hình/Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>QALY cần gì, DALY cần gì</td>
<td>thỏa dụng vs trọng số bệnh tật; nam 51 tuổi mất 24.5 năm sống</td>
<td>callout đầu bài</td>
</tr>
<tr class="even">
<td>2</td>
<td>EQ-5D-5L</td>
<td>năm khía cạnh, năm mức, 3,125 trạng thái</td>
<td>ví dụ hồ sơ 12345</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Bộ giá trị Việt Nam</td>
<td>1,200 người; mô hình cộng; thấp nhất -0.5115</td>
<td>chunk <code>l03-valueset</code></td>
</tr>
<tr class="even">
<td>4</td>
<td>Thỏa dụng người bệnh lao</td>
<td>0.83 → 0.90; 11111: 29% thật, 12% nếu độc lập</td>
<td><code>figs/l03-utility-sim.png</code></td>
</tr>
<tr class="odd">
<td>5</td>
<td>Mốc nền theo tuổi</td>
<td>1, 0.94, 0.92; tổn thất đổi gấp 2.5 lần</td>
<td>chunk <code>l03-baseline</code></td>
</tr>
<tr class="even">
<td>6</td>
<td>Trọng số bệnh tật GBD</td>
<td>lao 0.333, lao/HIV 0.408; YLD = DW × thời gian</td>
<td>chunk <code>l03-daly</code></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Bảng sống dùng chung</td>
<td>WHO 2023; <code>vn_lifetable()</code>, <code>vn_mx()</code>; một nguồn cho cả khóa</td>
<td>chunk <code>l03-lifetable</code></td>
</tr>
<tr class="even">
<td>8</td>
<td>Kiểm tra bảng sống</td>
<td><span class="math inline">\(a_x\)</span> suy ra hợp lý; dựng lại trả đúng <span class="math inline">\(q_x\)</span>; nhóm mở 85+</td>
<td><code>figs/l03-lifetable.png</code></td>
</tr>
<tr class="odd">
<td>9</td>
<td>Hai nguồn bất đồng</td>
<td>WHO vs Cục Thống kê: nam lệch 2.2 năm</td>
<td>bảng <code>e0_check</code></td>
</tr>
<tr class="even">
<td>10</td>
<td>Tử vong nền và YLL</td>
<td>xác suất tháng 0.00061; YLL 25.8 năm; bảng quốc gia hay tham chiếu</td>
<td>chunk <code>l03-model-use</code></td>
</tr>
<tr class="odd">
<td>11</td>
<td>Chuyển tiếp</td>
<td>thỏa dụng và tử vong nền đã có; xác suất chuyển từ nhiều nghiên cứu → Bài 4</td>
<td>—</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" class="pagination-link" aria-label="Bài 2: Điều chỉnh chi phí về một năm tham chiếu">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" class="pagination-link" aria-label="Bài 4: Tổng hợp bằng chứng cho tham số">
        <span class="nav-page-text"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>