<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bài 4: Tổng hợp bằng chứng cho tham số – Mô hình Kinh tế Y tế với R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../kb/m09-inputs-vietnam/l05-decision-context.html" rel="next">
<link href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9e7f0c659d5fa2cace8548cb57964278.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c18d72663580ed8ca19ce2a2f99af51b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=JetBrains+Mono:wght@400;600&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m09-inputs-vietnam/index.html">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</a></li><li class="breadcrumb-item"><a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Mô hình Kinh tế Y tế với R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lời mở đầu</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m00-r-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M00 · R cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l02-vectors-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l03-functions-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hàm, cấu trúc điều khiển, vòng lặp và vectơ hóa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l04-data-frames.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Data frame — nhập, làm sạch, tóm tắt và chuyển dạng dữ liệu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l05-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Biểu đồ với ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l06-randomness-monte-carlo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 6: Ngẫu nhiên, mô phỏng Monte Carlo và sai số Monte Carlo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m01-ee-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M01 · Nền tảng đánh giá kinh tế và cây quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l01-evaluation-types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại đánh giá kinh tế, quan điểm, khung thời gian và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l02-health-outcomes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Năm sống, QALY và DALY</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l03-decision-rules.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l04-thresholds.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l05-decision-tree.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Xây cây quyết định từ đầu trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m02-cohort-markov/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l01-state-transition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao cần mô hình chuyển trạng thái</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l03-cohort-trace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l04-time-dependence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Phụ thuộc thời gian: lão hóa, trạng thái đường hầm và mảng 3 chiều</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l05-results-verification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị gắn với lần chuyển, đường biên hiệu quả và xác minh mô hình</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m03-uncertainty-voi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l01-deterministic-sa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại bất định và phân tích độ nhạy tất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l02-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Chọn phân phối cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l03-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích độ nhạy xác suất (PSA) trong R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l05-voi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m04-microsimulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M04 · Mô phỏng vi mô (microsimulation)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l01-why-microsimulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l02-microsim-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l03-vectorisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vectơ hóa theo cá thể và đo hiệu năng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l04-parallel-rcpp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tính toán song song và Rcpp cho vòng lặp nóng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l05-mc-error-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bao nhiêu cá thể là đủ? Sai số Monte Carlo, PSA và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m05-dynamic-transmission/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M05 · Mô hình lây truyền động</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l01-static-vs-dynamic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Mô hình tĩnh và mô hình lây truyền động</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l02-sir-seir-desolve.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình SIR và SEIR trong R với deSolve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l03-vaccination-herd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Tiêm chủng, hiệu quả trực tiếp và gián tiếp</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l04-dengue-host-vector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Mô hình vật chủ–véc tơ cho sốt xuất huyết Dengue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l05-dynamic-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế với mô hình lây truyền động</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m06-amr-economics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M06 · Kinh tế học kháng kháng sinh (AMR)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l01-amr-burden.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l02-attributable-los.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l03-ward-transmission.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Mô hình lây truyền CRE trong khoa hồi sức</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l04-two-strain-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m07-survival-psm/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M07 · Phân tích sống còn cho mô hình quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l01-survival-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ôn tập phân tích sống còn cho người làm mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l02-parametric-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình sống còn tham số với flexsurv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l03-extrapolation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Ngoại suy sống còn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l04-reconstruct-ipd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tái tạo dữ liệu cá thể từ đường KM đã công bố và dùng HR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l05-partitioned-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Mô hình sống còn phân vùng trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m08-calibration/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M08 · Hiệu chuẩn mô hình (calibration)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l01-why-calibrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l02-search-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l03-bayes-sir.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hiệu chuẩn Bayes và thuật toán SIR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l04-psa-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đưa kết quả hiệu chuẩn vào PSA, thẩm định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m09-inputs-vietnam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l01-costing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ước tính chi phí cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l05-decision-context.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bối cảnh ra quyết định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m10-policy-bia-equity/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m11-software-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l01-code-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Cấu trúc mã cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l02-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Xác minh và kiểm thử mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l03-version-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quản lý phiên bản với Git và tái lập môi trường với renv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l04-r-package.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đóng gói mô hình thành gói R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l05-shiny-living.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Ứng dụng Shiny và mô hình “sống”</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bảng thuật ngữ Anh–Việt</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Trong bài</h2>
   
  <ul class="collapse">
  <li><a href="#mục-tiêu-học-tập" id="toc-mục-tiêu-học-tập" class="nav-link active" data-scroll-target="#mục-tiêu-học-tập">Mục tiêu học tập</a></li>
  <li><a href="#ý-chính" id="toc-ý-chính" class="nav-link" data-scroll-target="#ý-chính">Ý chính</a></li>
  <li><a href="#nội-dung" id="toc-nội-dung" class="nav-link" data-scroll-target="#nội-dung">Nội dung</a></li>
  <li><a href="#thực-hành" id="toc-thực-hành" class="nav-link" data-scroll-target="#thực-hành">Thực hành</a></li>
  <li><a href="#bài-tập" id="toc-bài-tập" class="nav-link" data-scroll-target="#bài-tập">Bài tập</a></li>
  <li><a href="#tài-liệu-tham-khảo" id="toc-tài-liệu-tham-khảo" class="nav-link" data-scroll-target="#tài-liệu-tham-khảo">Tài liệu tham khảo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m09-inputs-vietnam/index.html">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</a></li><li class="breadcrumb-item"><a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></h1>
<p class="subtitle lead">Gộp tỷ lệ và tỷ suất bằng mô hình hiệu ứng ngẫu nhiên viết từ đầu, và chuyển HR, RR, OR của thử nghiệm thành xác suất cho mô hình</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled" title="Vì sao bạn nên quan tâm?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vì sao bạn nên quan tâm?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Giám đốc một bệnh viện phổi tỉnh hỏi bạn: phác đồ BPaLM tốt hơn phác đồ đang dùng bao nhiêu, khi hai nguồn số liệu không khớp nhau? Năm 2021–2022, chương trình chống lao quốc gia điều trị 4,814 người lao kháng rifampicin: 71.2% thành công, 13.3% bỏ điều trị và 7.8% tử vong; còn thử nghiệm TB-PRACTECAL báo cáo BPaLM giảm kết cục bất lợi từ 48% xuống 11%, nhưng ở một quần thể khác và so với một nhóm chứng khác. Mỗi điểm phần trăm thành công tương ứng khoảng 48 người trong một lứa người bệnh như vậy, và mỗi người phải điều trị lại tốn ít nhất 12,185,360 VNĐ tiền thuốc phác đồ dài hạn, bằng 2.3 tháng lương tối thiểu vùng I. Bài này giúp bạn biến số liệu nhiều tỉnh và kết quả thử nghiệm thành xác suất đúng cho mô hình Việt Nam.</p>
</div>
</div>
<section id="mục-tiêu-học-tập" class="level2">
<h2 class="anchored" data-anchor-id="mục-tiêu-học-tập">Mục tiêu học tập</h2>
<p>Sau bài này, bạn có thể:</p>
<ol type="1">
<li>Gộp tỷ lệ (trên thang logit) và tỷ suất (trên thang log) từ nhiều nghiên cứu bằng mô hình hiệu ứng ngẫu nhiên (random-effects) DerSimonian–Laird viết bằng base R.</li>
<li>Đọc và báo cáo mức không đồng nhất giữa các nghiên cứu (<span class="math inline">\(\tau^2\)</span>, <span class="math inline">\(I^2\)</span>) và khoảng dự báo (prediction interval), và chọn con số phù hợp cho mô hình.</li>
<li>Áp nguy cơ tương đối (RR), tỷ số chênh (OR) và tỷ số nguy cơ tức thời (HR) lên nguy cơ nền (baseline risk) của Việt Nam để ra xác suất cho mô hình.</li>
<li>Nhận ra các phép chuyển đổi sai thường gặp và kiểm tra chúng bằng code.</li>
</ol>
</section>
<section id="ý-chính" class="level2">
<h2 class="anchored" data-anchor-id="ý-chính">Ý chính</h2>
<ul>
<li>Một tham số tốt dùng mọi bằng chứng phù hợp, không phải nghiên cứu tình cờ tìm thấy đầu tiên.</li>
<li>Gộp trên thang biến đổi (logit cho tỷ lệ, log cho tỷ suất), rồi biến đổi ngược. Không lấy trung bình cộng các tỷ lệ.</li>
<li>Mô hình hiệu ứng ngẫu nhiên giả định mỗi nghiên cứu có giá trị thật riêng; <span class="math inline">\(\tau^2\)</span> đo độ phân tán của các giá trị thật đó, <span class="math inline">\(I^2\)</span> là tỷ lệ biến thiên do phân tán thật.</li>
<li>Khoảng tin cậy nói về <em>giá trị trung bình</em>; khoảng dự báo nói về <em>một bối cảnh mới</em>. Một tỉnh chưa có trong dữ liệu gần với khoảng dự báo hơn.</li>
<li>Mô hình cần xác suất trong bối cảnh Việt Nam: lấy <strong>hiệu quả tương đối</strong> từ thử nghiệm, áp lên <strong>nguy cơ nền</strong> của Việt Nam.</li>
<li>RR nhân thẳng vào xác suất; OR phải đi qua odds; HR áp lên xác suất cộng dồn dưới dạng lũy thừa. Hiệu số nguy cơ (RD) giả định hiệu quả cộng không đổi, điều hiếm khi đúng giữa hai nguy cơ nền rất khác nhau, và có thể cho xác suất ngoài khoảng 0–1.</li>
<li>Nguy cơ nền phải ứng với đúng nhóm so sánh của thử nghiệm, và OR đã điều chỉnh từ nghiên cứu quan sát không phải hiệu quả nhân quả: dùng nó như bài tập số học, không như đầu vào mô hình.</li>
<li>Nhân OR với xác suất nền chỉ gần đúng khi sự kiện hiếm; ở nguy cơ nền vài chục phần trăm, sai số đáng kể.</li>
</ul>
</section>
<section id="nội-dung" class="level2">
<h2 class="anchored" data-anchor-id="nội-dung">Nội dung</h2>
<section id="vì-sao-phải-gộp-và-gộp-trên-thang-nào" class="level3">
<h3 class="anchored" data-anchor-id="vì-sao-phải-gộp-và-gộp-trên-thang-nào">Vì sao phải gộp, và gộp trên thang nào</h3>
<p>Tham số như “tỷ lệ điều trị thành công” hay “tỷ suất tái phát” thường có ở nhiều nghiên cứu với kết quả khác nhau. Chỉ chọn một nghiên cứu là tùy tiện; lấy trung bình cộng bỏ qua cỡ mẫu. Phân tích gộp (meta-analysis) lấy trung bình có trọng số theo độ chính xác.</p>
<p>Tỷ lệ bị chặn trong khoảng 0–1 và phương sai phụ thuộc vào chính tỷ lệ, nên ta gộp trên thang logit <span class="math inline">\(y_i = \ln[p_i/(1-p_i)]\)</span> với phương sai xấp xỉ <span class="math inline">\(v_i = 1/e_i + 1/(n_i - e_i)\)</span>, rồi biến đổi ngược. Biến đổi arcsine kép Freeman–Tukey được một số tác giả ưa dùng <span class="citation" data-cites="barendregt2013meta">(<a href="../m00-r-foundations/index.html#ref-barendregt2013meta" role="doc-biblioref">Barendregt và c.s. 2013</a>)</span>, nhưng phép biến đổi ngược của nó có thể cho kết quả sai lệch nghiêm trọng <span class="citation" data-cites="schwarzer2019seriously">(<a href="../m00-r-foundations/index.html#ref-schwarzer2019seriously" role="doc-biblioref">Schwarzer và c.s. 2019</a>)</span>; thang logit đơn giản và dễ kiểm tra hơn. Tỷ suất (số sự kiện chia người-năm) được gộp trên thang log với <span class="math inline">\(v_i \approx 1/e_i\)</span>.</p>
</section>
<section id="mô-hình-hiệu-ứng-ngẫu-nhiên-dersimonianlaird" class="level3">
<h3 class="anchored" data-anchor-id="mô-hình-hiệu-ứng-ngẫu-nhiên-dersimonianlaird">Mô hình hiệu ứng ngẫu nhiên DerSimonian–Laird</h3>
<p>Mô hình hiệu ứng cố định (fixed effect) giả định mọi nghiên cứu ước lượng cùng một giá trị. Ở bài toán chương trình (nhiều tỉnh, nhiều bệnh viện), giả định này hiếm khi đúng. Mô hình hiệu ứng ngẫu nhiên (random effects) cho phép giá trị thật <span class="math inline">\(\theta_i\)</span> khác nhau quanh trung bình <span class="math inline">\(\mu\)</span> với phương sai <span class="math inline">\(\tau^2\)</span> <span class="citation" data-cites="dersimonian1986meta">(<a href="../m00-r-foundations/index.html#ref-dersimonian1986meta" role="doc-biblioref">DerSimonian và Laird 1986</a>)</span>:</p>
<p><span class="math display">\[
y_i = \theta_i + \varepsilon_i,\quad \varepsilon_i \sim N(0, v_i),\qquad \theta_i \sim N(\mu, \tau^2).
\]</span></p>
<p>Ước lượng theo các bước, mỗi bước là một dòng R:</p>
<p><span class="math display">\[
w_i = \frac{1}{v_i},\quad Q = \sum w_i (y_i - \hat\mu_{\text{FE}})^2,\quad
\hat\tau^2 = \max\!\left(0, \frac{Q - (k-1)}{\sum w_i - \sum w_i^2/\sum w_i}\right),
\]</span></p>
<p><span class="math display">\[
w_i^* = \frac{1}{v_i + \hat\tau^2},\quad \hat\mu = \frac{\sum w_i^* y_i}{\sum w_i^*},\quad \text{SE}(\hat\mu) = \sqrt{1/\textstyle\sum w_i^*}.
\]</span></p>
<p><span class="math inline">\(I^2 = (Q - (k-1))/Q\)</span> là tỷ lệ biến thiên quan sát được do khác biệt thật giữa các nghiên cứu chứ không do may rủi chọn mẫu <span class="citation" data-cites="higgins2002quantifying">(<a href="../m00-r-foundations/index.html#ref-higgins2002quantifying" role="doc-biblioref">Higgins và Thompson 2002</a>)</span>. Khoảng dự báo 95% cho giá trị thật ở một bối cảnh mới là <span class="math inline">\(\hat\mu \pm t_{k-2}\sqrt{\hat\tau^2 + \text{SE}^2}\)</span> <span class="citation" data-cites="riley2011interpretation">(<a href="../m00-r-foundations/index.html#ref-riley2011interpretation" role="doc-biblioref">Riley, Higgins, và Deeks 2011</a>)</span>.</p>
<p><strong>Con số nào vào mô hình?</strong> Phân tích cơ sở dùng <span class="math inline">\(\hat\mu\)</span> (biến đổi ngược). Khi mô hình đại diện cho chính tập bối cảnh đã có dữ liệu, độ bất định của tham số là khoảng tin cậy. Khi mô hình đại diện cho một bối cảnh mới, khoảng dự báo thích hợp hơn. M03 đưa các khoảng này vào phân tích độ nhạy xác suất.</p>
<p><strong>Khi có ít nghiên cứu.</strong> Khoảng tin cậy chuẩn của DerSimonian–Laird dùng phân phối chuẩn và coi <span class="math inline">\(\hat\tau^2\)</span> như đã biết, nên với ít nghiên cứu nó thường quá hẹp. Phương pháp Hartung–Knapp–Sidik–Jonkman (HKSJ) ước lượng phương sai từ độ phân tán của chính các nghiên cứu quanh <span class="math inline">\(\hat\mu\)</span> và dùng phân phối <span class="math inline">\(t\)</span> với <span class="math inline">\(k-1\)</span> bậc tự do; mô phỏng cho thấy HKSJ cho tỷ lệ sai loại I sát mức danh nghĩa hơn DL, nhất là khi số nghiên cứu ít <span class="citation" data-cites="inthout2014hartung">(<a href="../m00-r-foundations/index.html#ref-inthout2014hartung" role="doc-biblioref">IntHout, Ioannidis, và Borm 2014</a>)</span>. Hàm <code>meta_dl()</code> trả cả hai khoảng.</p>
</section>
<section id="chuyển-hiệu-quả-tương-đối-thành-xác-suất" class="level3">
<h3 class="anchored" data-anchor-id="chuyển-hiệu-quả-tương-đối-thành-xác-suất">Chuyển hiệu quả tương đối thành xác suất</h3>
<p>Thử nghiệm thường báo cáo hiệu quả <em>tương đối</em>; mô hình cần xác suất <em>tuyệt đối</em> trong bối cảnh của mình. Cách làm chuẩn: lấy nguy cơ nền <span class="math inline">\(p_0\)</span> từ số liệu Việt Nam và áp hiệu quả tương đối của thử nghiệm <span class="citation" data-cites="gidwani2020estimating">(<a href="../m00-r-foundations/index.html#ref-gidwani2020estimating" role="doc-biblioref">Gidwani và Russell 2020</a>)</span>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Thước đo</th>
<th>Định nghĩa</th>
<th>Áp lên nguy cơ nền <span class="math inline">\(p_0\)</span> (cùng khoảng thời gian)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nguy cơ tương đối (RR)</td>
<td><span class="math inline">\(p_1/p_0\)</span></td>
<td><span class="math inline">\(p_1 = \text{RR}\cdot p_0\)</span> (kiểm tra <span class="math inline">\(p_1 \le 1\)</span>)</td>
</tr>
<tr class="even">
<td>Tỷ số chênh (OR)</td>
<td><span class="math inline">\(\dfrac{p_1/(1-p_1)}{p_0/(1-p_0)}\)</span></td>
<td><span class="math inline">\(p_1 = \dfrac{\text{OR}\, p_0/(1-p_0)}{1 + \text{OR}\, p_0/(1-p_0)}\)</span></td>
</tr>
<tr class="odd">
<td>Tỷ số nguy cơ tức thời (HR)</td>
<td><span class="math inline">\(h_1(t)/h_0(t)\)</span>, giả định không đổi</td>
<td><span class="math inline">\(p_1 = 1 - (1 - p_0)^{\text{HR}}\)</span></td>
</tr>
<tr class="even">
<td>Hiệu số nguy cơ (risk difference, RD)</td>
<td><span class="math inline">\(p_1 - p_0\)</span></td>
<td><span class="math inline">\(p_1 = p_0 + \text{RD}\)</span> (giả định hiệu quả cộng không đổi; có thể ra xác suất âm)</td>
</tr>
</tbody>
</table>
<p>Công thức đổi OR sang RR của Zhang và Yu, <span class="math inline">\(\text{RR} = \text{OR}/(1 - p_0 + p_0\,\text{OR})\)</span> <span class="citation" data-cites="zhang1998whats">(<a href="../m00-r-foundations/index.html#ref-zhang1998whats" role="doc-biblioref">Zhang và Yu 1998</a>)</span>, cho cùng kết quả với dòng OR trong bảng: cả hai chỉ là đi qua odds với nguy cơ nền <span class="math inline">\(p_0\)</span>. Với HR, công thức trong bảng đến từ <span class="math inline">\(S_1(t) = S_0(t)^{\text{HR}}\)</span> khi nguy cơ tỷ lệ; tương đương, nhân tỷ suất nền với HR rồi đổi sang xác suất <span class="citation" data-cites="fleurence2007rates">(<a href="../m00-r-foundations/index.html#ref-fleurence2007rates" role="doc-biblioref">Fleurence và Hollenbeak 2007</a>)</span>.</p>
<p>Hai chi tiết thường bị bỏ qua. Thứ nhất, <strong>quần thể phân tích</strong>: TB-PRACTECAL báo cáo kết cục bất lợi 11% với BPaLM và 48% với chăm sóc chuẩn trong quần thể mITT (phân tích theo ý định điều trị có điều chỉnh), nhưng 4% và 12% trong quần thể per-protocol (theo đúng phác đồ) <span class="citation" data-cites="nyangwa2022week">(<a href="../m00-r-foundations/index.html#ref-nyangwa2022week" role="doc-biblioref">Nyang’wa và c.s. 2022</a>)</span>. Hai quần thể cho hai hiệu quả tương đối khác hẳn nhau. Thứ hai, <strong>định nghĩa kết cục và khung thời gian</strong>: kết cục 72 tuần của thử nghiệm không trùng với kết cục cuối điều trị của chương trình <span class="citation" data-cites="nguyen2026from">(<a href="../m00-r-foundations/index.html#ref-nguyen2026from" role="doc-biblioref">Nguyen và c.s. 2026</a>)</span>. Ghi rõ cả hai lựa chọn trong bảng tham số.</p>
</section>
</section>
<section id="thực-hành" class="level2">
<h2 class="anchored" data-anchor-id="thực-hành">Thực hành</h2>
<p>Nạp bảng tham số. Phần gộp dùng <strong>dữ liệu mô phỏng</strong> (tám tỉnh giả định); phần chuyển đổi dùng số liệu thật đã kiểm chứng.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">isTRUE</span>(<span class="fu">l10n_info</span>()[[<span class="st">"UTF-8"</span>]])) <span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_CTYPE"</span>, <span class="st">"en_US.UTF-8"</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/helpers.R"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/vn_data.R"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"code/model.R"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>ps <span class="ot">&lt;-</span> <span class="fu">read_params</span>(<span class="st">"params/synthesis.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mô phỏng tám đoàn hệ: cỡ mẫu ngẫu nhiên, giá trị thật mỗi tỉnh lệch quanh 72% trên thang logit với độ lệch chuẩn 0.35, số ca thành công rút từ phân phối nhị thức. Kiểm tra: số ca không vượt cỡ mẫu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SIMULATED data: treatment success in 8 provincial cohorts (not real studies)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> ps<span class="sc">$</span>sim_k</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>studies <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">study =</span> <span class="fu">paste</span>(<span class="st">"Tỉnh"</span>, LETTERS[<span class="fu">seq_len</span>(k)]),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">n =</span> <span class="fu">round</span>(stats<span class="sc">::</span><span class="fu">runif</span>(k, ps<span class="sc">$</span>sim_n_min, ps<span class="sc">$</span>sim_n_max)))</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>true_logit <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">rnorm</span>(k, <span class="fu">logit</span>(ps<span class="sc">$</span>sim_p), ps<span class="sc">$</span>sim_tau)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>studies<span class="sc">$</span>events <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">rbinom</span>(k, studies<span class="sc">$</span>n, <span class="fu">expit</span>(true_logit))</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>studies<span class="sc">$</span>p_obs <span class="ot">&lt;-</span> studies<span class="sc">$</span>events <span class="sc">/</span> studies<span class="sc">$</span>n</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>studies</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   study   n events     p_obs
1 Tỉnh A 377    286 0.7586207
2 Tỉnh B 259    178 0.6872587
3 Tỉnh C 277    196 0.7075812
4 Tỉnh D 269    183 0.6802974
5 Tỉnh E 399    273 0.6842105
6 Tỉnh F 272    209 0.7683824
7 Tỉnh G 453    318 0.7019868
8 Tỉnh H  99     54 0.5454545</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(studies<span class="sc">$</span>events <span class="sc">&lt;=</span> studies<span class="sc">$</span>n), <span class="fu">nrow</span>(studies) <span class="sc">==</span> k)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Gộp bằng hàm <code>pool_proportions()</code>, so sánh với hiệu ứng cố định, cộng dồn thô và trung bình cộng. Kiểm tra: trọng số cộng bằng 1, sai số chuẩn của mô hình hiệu ứng ngẫu nhiên không nhỏ hơn của hiệu ứng cố định, khoảng dự báo chứa khoảng tin cậy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>pp <span class="ot">&lt;-</span> <span class="fu">pool_proportions</span>(studies<span class="sc">$</span>events, studies<span class="sc">$</span>n)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>pool_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"Hiệu ứng cố định"</span>, <span class="st">"Hiệu ứng ngẫu nhiên (DerSimonian-Laird, KTC chuẩn)"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Hiệu ứng ngẫu nhiên (cùng ước lượng, KTC Hartung-Knapp)"</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Cộng dồn thô (tổng ca / tổng mẫu)"</span>, <span class="st">"Trung bình cộng các tỷ lệ"</span>),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimate =</span> <span class="fu">c</span>(<span class="fu">expit</span>(pp<span class="sc">$</span>mu_fe), pp<span class="sc">$</span>p, pp<span class="sc">$</span>p, <span class="fu">sum</span>(studies<span class="sc">$</span>events) <span class="sc">/</span> <span class="fu">sum</span>(studies<span class="sc">$</span>n), <span class="fu">mean</span>(studies<span class="sc">$</span>p_obs)),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">lo =</span> <span class="fu">c</span>(<span class="fu">expit</span>(pp<span class="sc">$</span>mu_fe <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> pp<span class="sc">$</span>se_fe), pp<span class="sc">$</span>p_ci[<span class="dv">1</span>], pp<span class="sc">$</span>p_ci_hksj[<span class="dv">1</span>], <span class="cn">NA</span>, <span class="cn">NA</span>),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">hi =</span> <span class="fu">c</span>(<span class="fu">expit</span>(pp<span class="sc">$</span>mu_fe <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> pp<span class="sc">$</span>se_fe), pp<span class="sc">$</span>p_ci[<span class="dv">2</span>], pp<span class="sc">$</span>p_ci_hksj[<span class="dv">2</span>], <span class="cn">NA</span>, <span class="cn">NA</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>pool_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                   method  estimate        lo
1                                        Hiệu ứng cố định 0.7038664 0.6851699
2      Hiệu ứng ngẫu nhiên (DerSimonian-Laird, KTC chuẩn) 0.6996440 0.6635182
3 Hiệu ứng ngẫu nhiên (cùng ước lượng, KTC Hartung-Knapp) 0.6996440 0.6483308
4                       Cộng dồn thô (tổng ca / tổng mẫu) 0.7056133        NA
5                               Trung bình cộng các tỷ lệ 0.6917240        NA
         hi
1 0.7219032
2 0.7334493
3 0.7463986
4        NA
5        NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">tau2 =</span> pp<span class="sc">$</span>tau2, <span class="at">Q =</span> pp<span class="sc">$</span>Q, <span class="at">df =</span> pp<span class="sc">$</span>df, <span class="at">I2 =</span> pp<span class="sc">$</span>I2, <span class="at">pi_lo =</span> pp<span class="sc">$</span>p_pi[<span class="dv">1</span>], <span class="at">pi_hi =</span> pp<span class="sc">$</span>p_pi[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       tau2           Q          df          I2       pi_lo       pi_hi 
 0.04005862 24.05816368  7.00000000  0.70903847  0.57774666  0.79861749 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checks: weights sum to 1; the random-effects CI is at least as wide as the fixed-effect CI;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the prediction interval contains the CI; the HKSJ CI is wider than the normal CI here (few studies)</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(<span class="fu">sum</span>(pp<span class="sc">$</span>weights) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">&lt;</span> <span class="fl">1e-12</span>, pp<span class="sc">$</span>se <span class="sc">&gt;=</span> pp<span class="sc">$</span>se_fe,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>          pp<span class="sc">$</span>p_pi[<span class="dv">1</span>] <span class="sc">&lt;=</span> pp<span class="sc">$</span>p_ci[<span class="dv">1</span>], pp<span class="sc">$</span>p_pi[<span class="dv">2</span>] <span class="sc">&gt;=</span> pp<span class="sc">$</span>p_ci[<span class="dv">2</span>],</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>          pp<span class="sc">$</span>p_ci_hksj[<span class="dv">1</span>] <span class="sc">&lt;</span> pp<span class="sc">$</span>p_ci[<span class="dv">1</span>], pp<span class="sc">$</span>p_ci_hksj[<span class="dv">2</span>] <span class="sc">&gt;</span> pp<span class="sc">$</span>p_ci[<span class="dv">2</span>])</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># The text calls the heterogeneity high (I2 above 50%) and the prediction interval much wider than the CI</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(pp<span class="sc">$</span>I2 <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="fu">diff</span>(pp<span class="sc">$</span>p_pi) <span class="sc">&gt;</span> <span class="fl">1.5</span> <span class="sc">*</span> <span class="fu">diff</span>(pp<span class="sc">$</span>p_ci))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Tỷ lệ gộp là 70.0% (KTC 95%: 66.4%–73.3%). Mức không đồng nhất cao: <span class="math inline">\(I^2\)</span> = 70.9%, <span class="math inline">\(\hat\tau^2\)</span> = 0.040. Vì vậy khoảng dự báo cho một tỉnh mới rộng hơn hẳn, từ 57.8% đến 79.9%. Nếu mô hình dành cho một tỉnh chưa có trong dữ liệu, độ bất định thật gần với khoảng này. Với 8 nghiên cứu, KTC theo HKSJ (64.8%–74.6%) rộng hơn KTC chuẩn.</p>
<p>Vẽ biểu đồ rừng (forest plot): từng tỉnh với khoảng tin cậy, kích thước điểm theo trọng số, cùng ước lượng gộp và khoảng dự báo. Kiểm tra bằng mắt: tỉnh có mẫu lớn có điểm to và khoảng hẹp, và khoảng dự báo rộng hơn khoảng tin cậy gộp.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>forest_dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">label =</span> studies<span class="sc">$</span>study, <span class="at">p =</span> pp<span class="sc">$</span>study<span class="sc">$</span>p, <span class="at">lo =</span> pp<span class="sc">$</span>study<span class="sc">$</span>lo, <span class="at">hi =</span> pp<span class="sc">$</span>study<span class="sc">$</span>hi,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">weight =</span> pp<span class="sc">$</span>study<span class="sc">$</span>weight, <span class="at">type =</span> <span class="st">"Nghiên cứu"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>forest_dat <span class="ot">&lt;-</span> <span class="fu">rbind</span>(forest_dat,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">label =</span> <span class="st">"Gộp (KTC 95%)"</span>, <span class="at">p =</span> pp<span class="sc">$</span>p, <span class="at">lo =</span> pp<span class="sc">$</span>p_ci[<span class="dv">1</span>], <span class="at">hi =</span> pp<span class="sc">$</span>p_ci[<span class="dv">2</span>],</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">weight =</span> <span class="cn">NA</span>, <span class="at">type =</span> <span class="st">"Gộp"</span>),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">label =</span> <span class="st">"Khoảng dự báo 95%"</span>, <span class="at">p =</span> pp<span class="sc">$</span>p, <span class="at">lo =</span> pp<span class="sc">$</span>p_pi[<span class="dv">1</span>], <span class="at">hi =</span> pp<span class="sc">$</span>p_pi[<span class="dv">2</span>],</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">weight =</span> <span class="cn">NA</span>, <span class="at">type =</span> <span class="st">"Dự báo"</span>))</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>forest_dat<span class="sc">$</span>label <span class="ot">&lt;-</span> <span class="fu">factor</span>(forest_dat<span class="sc">$</span>label, <span class="at">levels =</span> <span class="fu">rev</span>(forest_dat<span class="sc">$</span>label))</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>is_study <span class="ot">&lt;-</span> forest_dat<span class="sc">$</span>type <span class="sc">==</span> <span class="st">"Nghiên cứu"</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>fig_forest <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(forest_dat, <span class="fu">aes</span>(p, label, <span class="at">colour =</span> type)) <span class="sc">+</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> lo, <span class="at">xmax =</span> hi), <span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">orientation =</span> <span class="st">"y"</span>) <span class="sc">+</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> forest_dat[is_study, ], <span class="fu">aes</span>(<span class="at">size =</span> weight), <span class="at">shape =</span> <span class="dv">15</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> forest_dat[<span class="sc">!</span>is_study, ], <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> pp<span class="sc">$</span>p, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"grey50"</span>) <span class="sc">+</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Nghiên cứu"</span> <span class="ot">=</span> pal_course[<span class="dv">1</span>], <span class="st">"Gộp"</span> <span class="ot">=</span> pal_course[<span class="dv">2</span>],</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">"Dự báo"</span> <span class="ot">=</span> pal_course[<span class="dv">3</span>]), <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="fl">1.5</span>, <span class="dv">5</span>)) <span class="sc">+</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tỷ lệ điều trị thành công"</span>, <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Gộp tỷ lệ bằng mô hình hiệu ứng ngẫu nhiên (dữ liệu mô phỏng)"</span>) <span class="sc">+</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_forest, <span class="st">"l04-forest.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-l04-forest" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-l04-forest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="l04-evidence-synthesis_files/figure-html/fig-l04-forest-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-l04-forest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;50.1: Biểu đồ rừng: tỷ lệ điều trị thành công ở tám tỉnh (dữ liệu mô phỏng), ước lượng gộp và khoảng dự báo.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Gộp tỷ suất tái phát từ tám đoàn hệ mô phỏng trên thang log, rồi đổi sang xác suất mỗi tháng cho mô hình.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SIMULATED relapse data: events and person-years in 8 cohorts, pooled on the log scale</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>rate_dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">study =</span> <span class="fu">paste</span>(<span class="st">"Đoàn hệ"</span>, <span class="fu">seq_len</span>(k)),</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">py =</span> <span class="fu">round</span>(stats<span class="sc">::</span><span class="fu">runif</span>(k, ps<span class="sc">$</span>sim_py_min, ps<span class="sc">$</span>sim_py_max)))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>rate_true <span class="ot">&lt;-</span> <span class="fu">exp</span>(stats<span class="sc">::</span><span class="fu">rnorm</span>(k, <span class="fu">log</span>(ps<span class="sc">$</span>sim_rate), ps<span class="sc">$</span>sim_tau_rate))</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>rate_dat<span class="sc">$</span>events <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">rpois</span>(k, rate_true <span class="sc">*</span> rate_dat<span class="sc">$</span>py)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>rate_dat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      study   py events
1 Đoàn hệ 1 1979     22
2 Đoàn hệ 2 2301     25
3 Đoàn hệ 3  657      6
4 Đoàn hệ 4 3023     70
5 Đoàn hệ 5  964     12
6 Đoàn hệ 6  787      8
7 Đoàn hệ 7 2225     19
8 Đoàn hệ 8 1626     10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>pr <span class="ot">&lt;-</span> <span class="fu">pool_rates</span>(rate_dat<span class="sc">$</span>events, rate_dat<span class="sc">$</span>py)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>rate_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">rate_per_1000py =</span> <span class="dv">1000</span> <span class="sc">*</span> <span class="fu">c</span>(pr<span class="sc">$</span>rate, pr<span class="sc">$</span>rate_ci, pr<span class="sc">$</span>rate_pi),</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">what =</span> <span class="fu">c</span>(<span class="st">"gộp"</span>, <span class="st">"KTC thấp"</span>, <span class="st">"KTC cao"</span>, <span class="st">"dự báo thấp"</span>, <span class="st">"dự báo cao"</span>))</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>rate_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  rate_per_1000py        what
1       11.074015         gộp
2        7.705273    KTC thấp
3       15.915567     KTC cao
4        3.362842 dự báo thấp
5       36.467308  dự báo cao</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Into a monthly model: rate per year / 12, then p = 1 - exp(-r t)</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>p_month_relapse <span class="ot">&lt;-</span> <span class="fu">rate_to_prob</span>(pr<span class="sc">$</span>rate <span class="sc">/</span> <span class="dv">12</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>p_month_relapse</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0009224089</code></pre>
</div>
</div>
<p>Tỷ suất gộp là 11.1 trên 1,000 người-năm, khoảng dự báo 3.4–36.5. Xác suất tái phát mỗi tháng là 0.00092.</p>
<p>Bây giờ chuyển hiệu quả của TB-PRACTECAL sang Việt Nam, với hai điều cần làm đúng. Một là <strong>quy ước kết cục</strong>: bài coi “không thành công” là 1 trừ thành công, nên người không được đánh giá (4.2%) tính vào nhóm không thành công, cho mọi nguy cơ nền; bài báo nguồn có thể định nghĩa khác, cần kiểm tra khi dùng thật. Hai là <strong>nguy cơ nền phải ứng với đúng nhóm so sánh</strong>: nhóm đối chứng của TB-PRACTECAL là phác đồ chuẩn 9–20 tháng, tức phác đồ dài hạn, trong khi nguy cơ nền của chương trình quốc gia 2021–2022 <span class="citation" data-cites="nguyen2026from">(<a href="../m00-r-foundations/index.html#ref-nguyen2026from" role="doc-biblioref">Nguyen và c.s. 2026</a>)</span> gộp mọi phác đồ. Ta chưa có nguy cơ nền riêng của phác đồ dài hạn, nên thêm một xấp xỉ từ OR đã điều chỉnh của chính nghiên cứu (mục kế tiếp). Kiểm tra: RR và OR cho xác suất trong khoảng 0–1; so xác suất chuyển với nguy cơ ở nhóm BPaLM của thử nghiệm.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># TB-PRACTECAL effect measures applied to a Vietnamese baseline.</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Convention for every baseline in this lesson: unfavourable = 1 - success, so patients who</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># were not evaluated (about 4%) count as unfavourable. The trial comparator is a 9-20 month</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># regimen, i.e. a LONG regimen, so the matching baseline is the Vietnamese long-regimen risk.</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># We do not have it directly; two stand-ins are shown and compared.</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>p0_all <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> ps<span class="sc">$</span>vn_success                        <span class="co"># all regimens mixed (short, injectable, long)</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>p0_bdq <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> ps<span class="sc">$</span>vn_success_bdqstr                 <span class="co"># bedaquiline short regimen (reference group)</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>p0_long <span class="ot">&lt;-</span> <span class="fu">apply_or</span>(p0_bdq, ps<span class="sc">$</span>aor_long)           <span class="co"># long regimen, from the adjusted OR (approximation, see l04-or)</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>baselines <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Mọi phác đồ (hỗn hợp)"</span> <span class="ot">=</span> p0_all, <span class="st">"Phác đồ dài hạn (xấp xỉ từ aOR)"</span> <span class="ot">=</span> p0_long)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>eff <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">population =</span> <span class="fu">c</span>(<span class="st">"mITT"</span>, <span class="st">"per-protocol"</span>),</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_bpalm =</span> <span class="fu">c</span>(ps<span class="sc">$</span>unf_bpalm_mitt, ps<span class="sc">$</span>unf_bpalm_pp),</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_soc =</span> <span class="fu">c</span>(ps<span class="sc">$</span>unf_soc_mitt, ps<span class="sc">$</span>unf_soc_pp),</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">rd_reported =</span> <span class="fu">c</span>(ps<span class="sc">$</span>rd_mitt, ps<span class="sc">$</span>rd_pp)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>eff<span class="sc">$</span>rd_from_rounded <span class="ot">&lt;-</span> eff<span class="sc">$</span>p_bpalm <span class="sc">-</span> eff<span class="sc">$</span>p_soc</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>eff<span class="sc">$</span>rr <span class="ot">&lt;-</span> eff<span class="sc">$</span>p_bpalm <span class="sc">/</span> eff<span class="sc">$</span>p_soc</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>eff<span class="sc">$</span>or <span class="ot">&lt;-</span> (eff<span class="sc">$</span>p_bpalm <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> eff<span class="sc">$</span>p_bpalm)) <span class="sc">/</span> (eff<span class="sc">$</span>p_soc <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> eff<span class="sc">$</span>p_soc))</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>eff</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    population p_bpalm p_soc rd_reported rd_from_rounded        rr        or
1         mITT    0.11  0.48       -0.37           -0.37 0.2291667 0.1338951
2 per-protocol    0.04  0.12       -0.09           -0.08 0.3333333 0.3055556</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Transport each measure to each baseline, then compare with the risk seen in the trial's BPaLM arm</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>transport <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(<span class="fu">seq_along</span>(baselines), <span class="cf">function</span>(b) {</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  p0 <span class="ot">&lt;-</span> baselines[[b]]</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">baseline =</span> <span class="fu">names</span>(baselines)[b], <span class="at">p0 =</span> p0, <span class="at">population =</span> eff<span class="sc">$</span>population,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">rd =</span> p0 <span class="sc">+</span> eff<span class="sc">$</span>rd_reported, <span class="at">rr =</span> <span class="fu">apply_rr</span>(p0, eff<span class="sc">$</span>rr), <span class="at">or =</span> <span class="fu">apply_or</span>(p0, eff<span class="sc">$</span>or),</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">p_trial_bpalm =</span> eff<span class="sc">$</span>p_bpalm)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>}))</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>transport</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         baseline        p0   population          rd         rr
1           Mọi phác đồ (hỗn hợp) 0.2880000         mITT -0.08200000 0.06600000
2           Mọi phác đồ (hỗn hợp) 0.2880000 per-protocol  0.19800000 0.09600000
3 Phác đồ dài hạn (xấp xỉ từ aOR) 0.3276154         mITT -0.04238458 0.07507853
4 Phác đồ dài hạn (xấp xỉ từ aOR) 0.3276154 per-protocol  0.23761542 0.10920514
          or p_trial_bpalm
1 0.05137725          0.11
2 0.11000000          0.04
3 0.06124407          0.11
4 0.12958718          0.04</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sanity: RR and OR stay inside [0, 1]; a transported risk below the trial's own BPaLM-arm</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># risk is a warning sign that a constant relative effect does not hold at this baseline</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(transport<span class="sc">$</span>rr <span class="sc">&gt;=</span> <span class="dv">0</span> <span class="sc">&amp;</span> transport<span class="sc">$</span>rr <span class="sc">&lt;=</span> <span class="dv">1</span>), <span class="fu">all</span>(transport<span class="sc">$</span>or <span class="sc">&gt;=</span> <span class="dv">0</span> <span class="sc">&amp;</span> transport<span class="sc">$</span>or <span class="sc">&lt;=</span> <span class="dv">1</span>))</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>below_trial <span class="ot">&lt;-</span> <span class="fu">with</span>(transport, rr <span class="sc">&lt;</span> p_trial_bpalm)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>below_trial</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  TRUE FALSE  TRUE FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The text: with the mITT effect, RD gives a negative probability at both baselines, and the RR result</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># falls below the risk seen in the trial's own BPaLM arm (rows 1 and 3 are the mITT rows)</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>mitt <span class="ot">&lt;-</span> transport<span class="sc">$</span>population <span class="sc">==</span> <span class="st">"mITT"</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(transport<span class="sc">$</span>rd[mitt] <span class="sc">&lt;</span> <span class="dv">0</span>), <span class="fu">all</span>(below_trial[mitt]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Với nguy cơ nền mọi phác đồ 28.8%, RR của mITT cho xác suất không thành công với BPaLM là 6.6%, OR cho 5.1%, còn hiệu số nguy cơ cho xác suất âm (-8.2%): nó giả định hiệu quả cộng không đổi (-37 điểm phần trăm) dù nguy cơ nền thấp hơn nhiều so với 48% của nhóm đối chứng. Nguy cơ nền phác đồ dài hạn (32.8%) cải thiện một phần, không sửa được lỗi này (mITT vẫn cho -4.2%). RR ở mITT (6.6% với nền mọi phác đồ, 7.5% với phác đồ dài hạn) còn thấp hơn nguy cơ quan sát ở nhóm BPaLM của thử nghiệm (11%). Điều đó chỉ đúng nếu người bệnh Việt Nam nhẹ hơn ở mọi yếu tố ngoài phác đồ, và các nguyên nhân không do phác đồ (bỏ điều trị, tử vong vì bệnh khác) cũng co theo cùng tỷ lệ; hai giả định cần nêu rõ và thử. Ví dụ minh họa cơ chế, không phải ước tính hiệu quả BPaLM tại Việt Nam. Ở per-protocol, RR cho 9.6%; hiệu số nguy cơ công bố là -9 điểm phần trăm, trong khi tính từ phần trăm làm tròn ra -8, nên cần lưu số ca và cỡ mẫu (không có trong tóm tắt). Chọn quần thể nào là quyết định cần nêu và thử độ nhạy.</p>
<p>Nghiên cứu Việt Nam báo cáo tỷ số chênh điều chỉnh (aOR) của kết cục bất lợi giữa phác đồ dài hạn và phác đồ ngắn có bedaquiline là 1.56 (KTC 95%: 1.32–1.84) <span class="citation" data-cites="nguyen2026from">(<a href="../m00-r-foundations/index.html#ref-nguyen2026from" role="doc-biblioref">Nguyen và c.s. 2026</a>)</span>. Hãy dùng nó như bài tập số học trên thang odds, không như đầu vào mô hình. (a) Đây là nghiên cứu quan sát: phác đồ được chọn theo tình trạng người bệnh (ví dụ người kháng fluoroquinolone thường không đủ điều kiện dùng phác đồ ngắn), nên aOR chịu nhiễu theo chỉ định (confounding by indication), không phải hiệu quả nhân quả. (b) aOR là OR có điều kiện theo các biến trong mô hình và không co gọn được (non-collapsible): áp nó lên nguy cơ nền thô của nhóm ngắn chỉ cho xấp xỉ, không cho nguy cơ biên của nhóm dài. (c) Khoảng của kết quả chỉ phản ánh bất định của OR, vì nguy cơ nền được coi là đã biết. Khi cần chuyển hiệu quả, dùng hiệu quả tương đối từ thử nghiệm ngẫu nhiên hoặc nguy cơ biên chuẩn hóa (standardised) từ chính mô hình hồi quy. Với bài tập, lấy nguy cơ nền là tỷ lệ không thành công của phác đồ ngắn (23.8%) và đổi OR thành xác suất cho phác đồ dài hạn.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vietnamese adjusted OR (long vs bedaquiline short regimen) -&gt; probability for the long regimen.</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># This is an arithmetic exercise on the odds scale: the OR is observational and conditional (see text).</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>or_vals <span class="ot">&lt;-</span> <span class="fu">param_range</span>(ps, <span class="st">"aor_long"</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>or_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">or =</span> or_vals,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">rr_zhang_yu =</span> <span class="fu">or_to_rr</span>(or_vals, p0_bdq),</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_long_correct =</span> <span class="fu">apply_or</span>(p0_bdq, or_vals),</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_long_naive =</span> p0_bdq <span class="sc">*</span> or_vals</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>or_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      or rr_zhang_yu p_long_correct p_long_naive
est 1.56    1.376535      0.3276154      0.37128
lo  1.32    1.226583      0.2919269      0.31416
hi  1.84    1.533436      0.3649577      0.43792</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sanity: an OR above 1 must raise the risk, and multiplying the OR by the baseline overshoots it</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(or_tab<span class="sc">$</span>p_long_correct <span class="sc">&gt;</span> p0_bdq), <span class="fu">all</span>(or_tab<span class="sc">$</span>p_long_naive <span class="sc">&gt;</span> or_tab<span class="sc">$</span>p_long_correct))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Xác suất không thành công với phác đồ dài hạn (xấp xỉ) là 32.8%. Nhân thẳng OR với nguy cơ nền cho 37.1%, cao hơn 4.4 điểm phần trăm. RR tương ứng theo công thức Zhang–Yu là 1.38, không phải 1.56. Tóm tắt bài báo không cho tỷ lệ không thành công thô của phác đồ dài hạn; khi có, hãy so với 32.8% để thấy xấp xỉ này lệch bao nhiêu.</p>
<p>Vẽ xác suất đúng (qua odds) và xác suất sai (nhân thẳng) theo nguy cơ nền. Kiểm tra bằng mắt: hai đường gần nhau ở nguy cơ nền thấp và tách ra khi nguy cơ nền tăng.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">p0 =</span> <span class="fu">seq</span>(<span class="fl">0.01</span>, <span class="fl">0.6</span>, <span class="at">by =</span> <span class="fl">0.01</span>))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>conv <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">p0 =</span> grid<span class="sc">$</span>p0, <span class="at">p1 =</span> <span class="fu">apply_or</span>(grid<span class="sc">$</span>p0, ps<span class="sc">$</span>aor_long), <span class="at">method =</span> <span class="st">"Đúng: đổi qua odds"</span>),</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">p0 =</span> grid<span class="sc">$</span>p0, <span class="at">p1 =</span> grid<span class="sc">$</span>p0 <span class="sc">*</span> ps<span class="sc">$</span>aor_long, <span class="at">method =</span> <span class="st">"Sai: nhân OR với xác suất nền"</span>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>fig_or <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(conv, <span class="fu">aes</span>(p0, p1, <span class="at">colour =</span> method)) <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dotted"</span>, <span class="at">colour =</span> <span class="st">"grey50"</span>) <span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> pal_course[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)], <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Nguy cơ nền p0"</span>, <span class="at">y =</span> <span class="st">"Xác suất ở nhóm so sánh p1"</span>,</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Áp cùng một tỷ số chênh: sai lệch tăng khi nguy cơ nền cao"</span>) <span class="sc">+</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_or, <span class="st">"l04-or-conversion.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-l04-or" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-l04-or-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="l04-evidence-synthesis_files/figure-html/fig-l04-or-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-l04-or-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;50.2: Cùng một tỷ số chênh (của phác đồ dài hạn so với phác đồ ngắn), áp đúng qua odds và áp sai bằng cách nhân với nguy cơ nền.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Cuối cùng, một HR thật: trong đoàn hệ quốc gia ở Nam Phi, phác đồ có bedaquiline đi kèm nguy cơ tử vong thấp hơn so với phác đồ chuẩn có thuốc tiêm, 0.35 (KTC 95%: 0.28–0.46) <span class="citation" data-cites="schnippel2018effect">(<a href="../m00-r-foundations/index.html#ref-schnippel2018effect" role="doc-biblioref">Schnippel và c.s. 2018</a>)</span>. Đây là nghiên cứu quan sát, ở nơi tỷ lệ đồng nhiễm HIV cao, nên ta dùng nó để học cách áp HR, không như hiệu quả của BPaLM tại Việt Nam. Áp HR lên tỷ lệ tử vong trong điều trị của chương trình quốc gia, coi như xác suất cộng dồn trong 18 tháng, rồi đổi sang xác suất mỗi tháng. Cửa sổ thời gian là một giả định: tỷ lệ tử vong gộp mọi phác đồ, kể cả phác đồ ngắn 9–11 tháng. Kiểm tra: HR = 1 không làm thay đổi gì, và xác suất tháng cộng dồn lại đúng bằng xác suất cả đợt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Hazard ratio on a cumulative probability over the longer regimen, then a monthly probability.</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The HR is a real but observational estimate (bedaquiline-containing vs standard regimens, South</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Africa). The window is an assumption: the national death share (all regimens, same denominator</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># as above) is treated as a cumulative probability over the longer-regimen duration.</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>p0_death <span class="ot">&lt;-</span> ps<span class="sc">$</span>vn_death</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>hr <span class="ot">&lt;-</span> ps<span class="sc">$</span>hr_bdq_death</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>hr_ci <span class="ot">&lt;-</span> <span class="fu">param_range</span>(ps, <span class="st">"hr_bdq_death"</span>)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>hr_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">quantity =</span> <span class="fu">c</span>(<span class="st">"Nguy cơ nền trong cả đợt điều trị"</span>, <span class="st">"Áp HR đúng: 1 - (1 - p0)^HR"</span>,</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Sai: p0 x HR"</span>),</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_course =</span> <span class="fu">c</span>(p0_death, <span class="fu">apply_hr</span>(p0_death, hr), p0_death <span class="sc">*</span> hr)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>hr_tab<span class="sc">$</span>p_month <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> hr_tab<span class="sc">$</span>p_course)<span class="sc">^</span>(<span class="dv">1</span> <span class="sc">/</span> ps<span class="sc">$</span>dur_long)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>hr_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                           quantity   p_course     p_month
1 Nguy cơ nền trong cả đợt điều trị 0.07800000 0.004501507
2       Áp HR đúng: 1 - (1 - p0)^HR 0.02802337 0.001577838
3                      Sai: p0 x HR 0.02730000 0.001536572</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checks: HR = 1 changes nothing; monthly probabilities compound back to the course probability</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(<span class="fu">apply_hr</span>(p0_death, <span class="dv">1</span>) <span class="sc">-</span> p0_death) <span class="sc">&lt;</span> <span class="fl">1e-15</span>,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(<span class="fu">abs</span>(<span class="dv">1</span> <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> hr_tab<span class="sc">$</span>p_month)<span class="sc">^</span>ps<span class="sc">$</span>dur_long <span class="sc">-</span> hr_tab<span class="sc">$</span>p_course) <span class="sc">&lt;</span> <span class="fl">1e-12</span>))</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Deaths averted per 100 patients at the HR and at its 95% CI limits</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>averted_100 <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="sc">*</span> (p0_death <span class="sc">-</span> <span class="fu">apply_hr</span>(p0_death, hr_ci))</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>averted_100</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     est       lo       hi 
4.997663 5.551776 4.133253 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>naive_gap_pp <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="sc">*</span> <span class="fu">abs</span>(hr_tab<span class="sc">$</span>p_course[<span class="dv">3</span>] <span class="sc">-</span> hr_tab<span class="sc">$</span>p_course[<span class="dv">2</span>])</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Baselines for Exercise 3: low, the national death share, high; and for Exercise 2</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>ex3_p0 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.02</span>, ps<span class="sc">$</span>vn_death, <span class="fl">0.30</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>ex2_p0 <span class="ot">&lt;-</span> <span class="fl">0.10</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Với HR này, cứ 100 người bệnh thì tránh được khoảng 5.0 ca tử vong (4.1–5.6 theo hai đầu KTC). Ở nguy cơ nền thấp như 7.8%, nhân thẳng <span class="math inline">\(p_0 \times \text{HR}\)</span> chỉ lệch 0.07 điểm phần trăm so với công thức đúng. Bài tập 3 cho thấy sai lệch tăng theo nguy cơ nền.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Mẹo thực hành">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mẹo thực hành
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Lưu dữ liệu từng nghiên cứu (số ca, cỡ mẫu hoặc người-năm, năm, bối cảnh) trong một bảng riêng; kết quả gộp phải chạy lại được từ bảng đó.</li>
<li>Luôn vẽ biểu đồ rừng (forest plot) trước khi tin con số gộp: một nghiên cứu lệch hẳn có thể là khác định nghĩa kết cục, không phải khác hiệu quả.</li>
<li>Báo cáo cả khoảng dự báo. Với số liệu chương trình nhiều tỉnh, đây thường là con số trung thực nhất về bất định.</li>
<li>Viết hàm áp hiệu quả tương đối có kiểm tra (<code>apply_rr()</code> cảnh báo khi vượt 1) và gọi nó ở mọi nơi, thay vì nhân tay rải rác trong mô hình.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Lỗi thường gặp">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lỗi thường gặp
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Lấy trung bình cộng các tỷ lệ.</strong> Nghiên cứu 50 người và nghiên cứu 500 người không thể có trọng số bằng nhau.</li>
<li><strong>Nhân OR với xác suất nền.</strong> Chỉ gần đúng khi sự kiện hiếm; ở nguy cơ nền 23.8%, sai 4.4 điểm phần trăm.</li>
<li><strong>Chuyển hiệu số nguy cơ sang nguy cơ nền khác.</strong> Có thể ra xác suất âm như ví dụ trên.</li>
<li><strong>Áp RR hoặc OR của một khung thời gian lên nguy cơ nền của khung khác</strong> (ví dụ RR của 72 tuần lên xác suất một tháng). RR và OR phụ thuộc khung thời gian; HR là thước đo duy nhất giữ nguyên qua các khung nếu nguy cơ tỷ lệ không đổi. Khi đổi khung thời gian, đi qua tỷ suất (M02 Bài 2).</li>
<li><strong>Dùng nguy cơ nền của quần thể khác nhóm so sánh, hoặc dùng aOR quan sát như hiệu quả nhân quả.</strong> Kiểm tra nhóm so sánh của thử nghiệm và so xác suất chuyển với nguy cơ trong chính thử nghiệm.</li>
</ul>
</div>
</div>
</section>
<section id="bài-tập" class="level2">
<h2 class="anchored" data-anchor-id="bài-tập">Bài tập</h2>
<ol type="1">
<li><strong>(Dễ)</strong> Phân tích “bỏ một”: gộp lại sau khi lần lượt bỏ từng tỉnh. Tỉnh nào ảnh hưởng nhiều nhất tới kết quả?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 1: leave-one-out sensitivity of the pooled proportion</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>loo <span class="ot">&lt;-</span> <span class="fu">vapply</span>(<span class="fu">seq_len</span>(k), <span class="cf">function</span>(i) <span class="fu">pool_proportions</span>(studies<span class="sc">$</span>events[<span class="sc">-</span>i], studies<span class="sc">$</span>n[<span class="sc">-</span>i])<span class="sc">$</span>p, <span class="fu">numeric</span>(<span class="dv">1</span>))</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">left_out =</span> studies<span class="sc">$</span>study, <span class="at">p_obs =</span> <span class="fu">round</span>(studies<span class="sc">$</span>p_obs, <span class="dv">3</span>), <span class="at">pooled =</span> <span class="fu">round</span>(loo, <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  left_out p_obs pooled
1   Tỉnh A 0.759  0.690
2   Tỉnh B 0.687  0.701
3   Tỉnh C 0.708  0.698
4   Tỉnh D 0.680  0.702
5   Tỉnh E 0.684  0.701
6   Tỉnh F 0.768  0.690
7   Tỉnh G 0.702  0.698
8   Tỉnh H 0.545  0.713</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>loo_up <span class="ot">&lt;-</span> <span class="fu">which.max</span>(loo)   <span class="co"># the province whose removal raises the pooled estimate most</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">province =</span> studies<span class="sc">$</span>study[loo_up], <span class="at">p_obs =</span> studies<span class="sc">$</span>p_obs[loo_up], <span class="at">rank_low =</span> <span class="fu">rank</span>(studies<span class="sc">$</span>p_obs)[loo_up])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           province               p_obs            rank_low 
           "Tỉnh H" "0.545454545454545"                 "1" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The text calls this province the most influential: its removal moves the pooled value more than any other</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">which.max</span>(<span class="fu">abs</span>(loo <span class="sc">-</span> pp<span class="sc">$</span>p)) <span class="sc">==</span> loo_up)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Bỏ Tỉnh H (tỷ lệ quan sát 54.5%, thấp nhất trong 8 tỉnh) làm ước lượng gộp tăng nhiều nhất, lên 71.3%. Nếu kết quả gộp phụ thuộc vào một nghiên cứu, hãy kiểm tra định nghĩa kết cục và chất lượng của nghiên cứu đó trước khi quyết định.</p>
</div>
</div>
</div>
<ol start="2" type="1">
<li><strong>(Vừa)</strong> Áp tỷ số chênh 1.56 lên nguy cơ nền 10%. So sánh với cách nhân thẳng.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 2: the Vietnamese OR applied at a lower baseline risk (10%)</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>ex2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">correct =</span> <span class="fu">apply_or</span>(ex2_p0, ps<span class="sc">$</span>aor_long), <span class="at">naive =</span> ex2_p0 <span class="sc">*</span> ps<span class="sc">$</span>aor_long)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>ex2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  correct     naive 
0.1477273 0.1560000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Closer together than at the lesson's baseline (OR approximates RR when events are rare)</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(ex2[[<span class="st">"naive"</span>]] <span class="sc">-</span> ex2[[<span class="st">"correct"</span>]] <span class="sc">&lt;</span> or_tab<span class="sc">$</span>p_long_naive[<span class="dv">1</span>] <span class="sc">-</span> or_tab<span class="sc">$</span>p_long_correct[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ở nguy cơ nền thấp, hai cách gần nhau hơn so với nguy cơ nền trong bài, đúng như dự đoán: OR xấp xỉ RR khi sự kiện hiếm.</p>
</div>
</div>
</div>
<ol start="3" type="1">
<li><strong>(Khó)</strong> Với HR = 0.35, tính số tử vong tránh được trên mỗi người ở ba nguy cơ nền 2%, 7.8% và 30%. Kết luận gì về việc chuyển hiệu quả từ thử nghiệm sang các nhóm người bệnh có nguy cơ khác nhau?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 3: is the effect of the HR larger in absolute terms at a high or a low baseline?</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Also: how wrong is the shortcut p0 x HR at each baseline?</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>ex3 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">p0 =</span> ex3_p0, <span class="at">p1 =</span> <span class="fu">apply_hr</span>(ex3_p0, hr))</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>ex3<span class="sc">$</span>averted <span class="ot">&lt;-</span> ex3<span class="sc">$</span>p0 <span class="sc">-</span> ex3<span class="sc">$</span>p1</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>ex3<span class="sc">$</span>naive_p1 <span class="ot">&lt;-</span> ex3<span class="sc">$</span>p0 <span class="sc">*</span> hr</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>ex3<span class="sc">$</span>naive_error <span class="ot">&lt;-</span> ex3<span class="sc">$</span>naive_p1 <span class="sc">-</span> ex3<span class="sc">$</span>p1</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>ex3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     p0          p1    averted naive_p1   naive_error
1 0.020 0.007046007 0.01295399   0.0070 -4.600723e-05
2 0.078 0.028023371 0.04997663   0.0273 -7.233713e-04
3 0.300 0.117358559 0.18264144   0.1050 -1.235856e-02</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">diff</span>(ex3<span class="sc">$</span>averted) <span class="sc">&gt;</span> <span class="dv">0</span>), <span class="fu">all</span>(<span class="fu">diff</span>(ex3<span class="sc">$</span>naive_error) <span class="sc">&lt;</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cùng một HR, số tử vong tránh được tăng mạnh theo nguy cơ nền, và lối tắt <span class="math inline">\(p_0 \times \text{HR}\)</span> sai nhiều hơn (về độ lớn) khi nguy cơ nền cao (cột <code>naive_error</code>). Lợi ích tuyệt đối, và do đó tỷ số chi phí-hiệu quả gia tăng (ICER), phụ thuộc vào nguy cơ nền của quần thể mô hình, nên nguy cơ nền phải lấy từ số liệu Việt Nam và được phân tích độ nhạy riêng.</p>
</div>
</div>
</div>
</section>
<section id="tài-liệu-tham-khảo" class="level2">
<h2 class="anchored" data-anchor-id="tài-liệu-tham-khảo">Tài liệu tham khảo</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-barendregt2013meta" class="csl-entry" role="listitem">
Barendregt, Jan J., Suhail A. Doi, Yong Yi Lee, Rosana E. Norman, và Theo Vos. 2013. <span>“Meta-analysis of prevalence”</span>. <em>Journal of Epidemiology and Community Health</em> 67 (11): 974–78. <a href="https://doi.org/10.1136/jech-2013-203104">https://doi.org/10.1136/jech-2013-203104</a>.
</div>
<div id="ref-dersimonian1986meta" class="csl-entry" role="listitem">
DerSimonian, R., và N. Laird. 1986. <span>“Meta-analysis in clinical trials”</span>. <em>Controlled Clinical Trials</em> 7 (3): 177–88. <a href="https://doi.org/10.1016/0197-2456(86)90046-2">https://doi.org/10.1016/0197-2456(86)90046-2</a>.
</div>
<div id="ref-fleurence2007rates" class="csl-entry" role="listitem">
Fleurence, Rachael L., và Christopher S. Hollenbeak. 2007. <span>“Rates and probabilities in economic modelling: transformation, translation and appropriate application”</span>. <em>PharmacoEconomics</em> 25 (1): 3–6. <a href="https://doi.org/10.2165/00019053-200725010-00002">https://doi.org/10.2165/00019053-200725010-00002</a>.
</div>
<div id="ref-gidwani2020estimating" class="csl-entry" role="listitem">
Gidwani, Risha, và Louise B. Russell. 2020. <span>“Estimating transition probabilities from published evidence: a tutorial for decision modelers”</span>. <em>PharmacoEconomics</em> 38 (11): 1153–64. <a href="https://doi.org/10.1007/s40273-020-00937-z">https://doi.org/10.1007/s40273-020-00937-z</a>.
</div>
<div id="ref-higgins2002quantifying" class="csl-entry" role="listitem">
Higgins, Julian P. T., và Simon G. Thompson. 2002. <span>“Quantifying heterogeneity in a meta-analysis”</span>. <em>Statistics in Medicine</em> 21 (11): 1539–58. <a href="https://doi.org/10.1002/sim.1186">https://doi.org/10.1002/sim.1186</a>.
</div>
<div id="ref-inthout2014hartung" class="csl-entry" role="listitem">
IntHout, Joanna, John P. A. Ioannidis, và George F. Borm. 2014. <span>“The <span>Hartung-Knapp-Sidik-Jonkman</span> method for random effects meta-analysis is straightforward and considerably outperforms the standard <span>DerSimonian-Laird</span> method”</span>. <em>BMC Medical Research Methodology</em> 14: 25. <a href="https://doi.org/10.1186/1471-2288-14-25">https://doi.org/10.1186/1471-2288-14-25</a>.
</div>
<div id="ref-nguyen2026from" class="csl-entry" role="listitem">
Nguyen, Thi Mai Phuong, Van Luong Dinh, Binh Hoa Nguyen, Thi Thanh Thuy Hoang, Viet Nhung Nguyen, Steven Callens, và Tom Decroo. 2026. <span>“From trials to programmatic scale-up: treatment outcomes of rifampicin-resistant tuberculosis during transition to short oral regimens in <span>Vietnam</span> (2021–2022)”</span>. <em>International Journal of Infectious Diseases</em> 163: 108222. <a href="https://doi.org/10.1016/j.ijid.2025.108222">https://doi.org/10.1016/j.ijid.2025.108222</a>.
</div>
<div id="ref-nyangwa2022week" class="csl-entry" role="listitem">
Nyang’wa, Bern-Thomas, Catherine Berry, Emil Kazounis, Ilaria Motta, Nargiza Parpieva, Zinaida Tigay, Varvara Solodovnikova, và c.s. 2022. <span>“A 24-week, all-oral regimen for rifampin-resistant tuberculosis”</span>. <em>New England Journal of Medicine</em> 387 (25): 2331–43. <a href="https://doi.org/10.1056/NEJMoa2117166">https://doi.org/10.1056/NEJMoa2117166</a>.
</div>
<div id="ref-riley2011interpretation" class="csl-entry" role="listitem">
Riley, Richard D., Julian P. T. Higgins, và Jonathan J. Deeks. 2011. <span>“Interpretation of random effects meta-analyses”</span>. <em>BMJ</em> 342: d549. <a href="https://doi.org/10.1136/bmj.d549">https://doi.org/10.1136/bmj.d549</a>.
</div>
<div id="ref-schnippel2018effect" class="csl-entry" role="listitem">
Schnippel, Kathryn, Norbert Ndjeka, Gary Maartens, Graeme Meintjes, Iqbal Master, Nazir Ismail, Jennifer Hughes, và c.s. 2018. <span>“Effect of bedaquiline on mortality in <span>South African</span> patients with drug-resistant tuberculosis: a retrospective cohort study”</span>. <em>The Lancet Respiratory Medicine</em> 6 (9): 699–706. <a href="https://doi.org/10.1016/S2213-2600(18)30235-2">https://doi.org/10.1016/S2213-2600(18)30235-2</a>.
</div>
<div id="ref-schwarzer2019seriously" class="csl-entry" role="listitem">
Schwarzer, Guido, Hiam Chemaitelly, Laith J. Abu-Raddad, và Gerta Rücker. 2019. <span>“Seriously misleading results using inverse of <span>Freeman-Tukey</span> double arcsine transformation in meta-analysis of single proportions”</span>. <em>Research Synthesis Methods</em> 10 (3): 476–83. <a href="https://doi.org/10.1002/jrsm.1348">https://doi.org/10.1002/jrsm.1348</a>.
</div>
<div id="ref-zhang1998whats" class="csl-entry" role="listitem">
Zhang, J., và K. F. Yu. 1998. <span>“What’s the relative risk? <span>A</span> method of correcting the odds ratio in cohort studies of common outcomes”</span>. <em>JAMA</em> 280 (19): 1690–91. <a href="https://doi.org/10.1001/jama.280.19.1690">https://doi.org/10.1001/jama.280.19.1690</a>.
</div>
</div>
<div class="video-script">
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kịch bản video (~14 phút)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Slide</th>
<th>Lời giảng chính</th>
<th>Hình/Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Một tham số, nhiều nghiên cứu</td>
<td>lấy một nghiên cứu là tùy tiện; gộp có trọng số</td>
<td>—</td>
</tr>
<tr class="even">
<td>2</td>
<td>Thang biến đổi</td>
<td>logit cho tỷ lệ, log cho tỷ suất; tránh biến đổi ngược Freeman–Tukey</td>
<td>công thức</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Cố định hay ngẫu nhiên</td>
<td>mỗi tỉnh một giá trị thật; <span class="math inline">\(\tau^2\)</span></td>
<td>sơ đồ công thức</td>
</tr>
<tr class="even">
<td>4</td>
<td>DerSimonian–Laird trong base R</td>
<td>năm dòng code; kiểm tra trọng số</td>
<td>chunk <code>l04-pool</code></td>
</tr>
<tr class="odd">
<td>5</td>
<td><span class="math inline">\(I^2\)</span>, khoảng dự báo, HKSJ</td>
<td><span class="math inline">\(I^2\)</span> = 70.9%; khoảng dự báo 57.8%–79.9%; ít nghiên cứu thì dùng HKSJ</td>
<td><code>figs/l04-forest.png</code></td>
</tr>
<tr class="even">
<td>6</td>
<td>Tỷ suất</td>
<td>gộp trên thang log; đổi sang xác suất tháng</td>
<td>chunk <code>l04-rates</code></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Hiệu quả tương đối + nguy cơ nền Việt Nam</td>
<td>bảng RR, OR, HR, RD</td>
<td>bảng công thức</td>
</tr>
<tr class="even">
<td>8</td>
<td>TB-PRACTECAL sang Việt Nam</td>
<td>đúng nhóm so sánh; mITT vs per-protocol; RD cho xác suất âm; kiểm tra với nhóm BPaLM của thử nghiệm</td>
<td>chunk <code>l04-transport</code></td>
</tr>
<tr class="odd">
<td>9</td>
<td>OR không phải RR</td>
<td>32.8% vs 37.1%; aOR quan sát, có điều kiện, không co gọn</td>
<td><code>figs/l04-or-conversion.png</code></td>
</tr>
<tr class="even">
<td>10</td>
<td>HR và khung thời gian</td>
<td><span class="math inline">\(1-(1-p_0)^{HR}\)</span>; đổi sang xác suất tháng</td>
<td>chunk <code>l04-hr</code></td>
</tr>
<tr class="odd">
<td>11</td>
<td>Chuyển tiếp</td>
<td>đầu vào đã đủ; ra quyết định và báo cáo → Bài 5</td>
<td>—</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="pagination-link" aria-label="Bài 3: Đầu vào về kết cục sức khỏe">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../kb/m09-inputs-vietnam/l05-decision-context.html" class="pagination-link" aria-label="Bài 5: Bối cảnh ra quyết định và báo cáo">
        <span class="nav-page-text"><span class="chapter-title">Bài 5: Bối cảnh ra quyết định và báo cáo</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>