<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bài 1: Vì sao phải hiệu chuẩn mô hình – Mô hình Kinh tế Y tế với R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../kb/m08-calibration/l02-search-methods.html" rel="next">
<link href="../../kb/m08-calibration/index.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9e7f0c659d5fa2cace8548cb57964278.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c18d72663580ed8ca19ce2a2f99af51b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="mermaid-theme" content="neutral">
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=JetBrains+Mono:wght@400;600&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m08-calibration/index.html">M08 · Hiệu chuẩn mô hình (calibration)</a></li><li class="breadcrumb-item"><a href="../../kb/m08-calibration/l01-why-calibrate.html"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Mô hình Kinh tế Y tế với R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lời mở đầu</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m00-r-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M00 · R cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l02-vectors-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l03-functions-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hàm, cấu trúc điều khiển, vòng lặp và vectơ hóa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l04-data-frames.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Data frame — nhập, làm sạch, tóm tắt và chuyển dạng dữ liệu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l05-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Biểu đồ với ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l06-randomness-monte-carlo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 6: Ngẫu nhiên, mô phỏng Monte Carlo và sai số Monte Carlo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m01-ee-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M01 · Nền tảng đánh giá kinh tế và cây quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l01-evaluation-types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại đánh giá kinh tế, quan điểm, khung thời gian và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l02-health-outcomes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Năm sống, QALY và DALY</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l03-decision-rules.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l04-thresholds.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l05-decision-tree.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Xây cây quyết định từ đầu trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m02-cohort-markov/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l01-state-transition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao cần mô hình chuyển trạng thái</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l03-cohort-trace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l04-time-dependence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Phụ thuộc thời gian: lão hóa, trạng thái đường hầm và mảng 3 chiều</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l05-results-verification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị gắn với lần chuyển, đường biên hiệu quả và xác minh mô hình</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m03-uncertainty-voi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l01-deterministic-sa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại bất định và phân tích độ nhạy tất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l02-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Chọn phân phối cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l03-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích độ nhạy xác suất (PSA) trong R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l05-voi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m04-microsimulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M04 · Mô phỏng vi mô (microsimulation)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l01-why-microsimulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l02-microsim-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l03-vectorisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vectơ hóa theo cá thể và đo hiệu năng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l04-parallel-rcpp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tính toán song song và Rcpp cho vòng lặp nóng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l05-mc-error-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bao nhiêu cá thể là đủ? Sai số Monte Carlo, PSA và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m05-dynamic-transmission/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M05 · Mô hình lây truyền động</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l01-static-vs-dynamic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Mô hình tĩnh và mô hình lây truyền động</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l02-sir-seir-desolve.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình SIR và SEIR trong R với deSolve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l03-vaccination-herd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Tiêm chủng, hiệu quả trực tiếp và gián tiếp</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l04-dengue-host-vector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Mô hình vật chủ–véc tơ cho sốt xuất huyết Dengue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l05-dynamic-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế với mô hình lây truyền động</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m06-amr-economics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M06 · Kinh tế học kháng kháng sinh (AMR)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l01-amr-burden.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l02-attributable-los.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l03-ward-transmission.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Mô hình lây truyền CRE trong khoa hồi sức</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l04-two-strain-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m07-survival-psm/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M07 · Phân tích sống còn cho mô hình quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l01-survival-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ôn tập phân tích sống còn cho người làm mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l02-parametric-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình sống còn tham số với flexsurv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l03-extrapolation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Ngoại suy sống còn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l04-reconstruct-ipd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tái tạo dữ liệu cá thể từ đường KM đã công bố và dùng HR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l05-partitioned-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Mô hình sống còn phân vùng trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m08-calibration/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M08 · Hiệu chuẩn mô hình (calibration)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l01-why-calibrate.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l02-search-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l03-bayes-sir.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hiệu chuẩn Bayes và thuật toán SIR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l04-psa-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đưa kết quả hiệu chuẩn vào PSA, thẩm định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m09-inputs-vietnam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l01-costing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ước tính chi phí cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l05-decision-context.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bối cảnh ra quyết định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m10-policy-bia-equity/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m11-software-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l01-code-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Cấu trúc mã cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l02-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Xác minh và kiểm thử mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l03-version-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quản lý phiên bản với Git và tái lập môi trường với renv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l04-r-package.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đóng gói mô hình thành gói R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l05-shiny-living.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Ứng dụng Shiny và mô hình “sống”</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bảng thuật ngữ Anh–Việt</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Trong bài</h2>
   
  <ul class="collapse">
  <li><a href="#mục-tiêu-học-tập" id="toc-mục-tiêu-học-tập" class="nav-link active" data-scroll-target="#mục-tiêu-học-tập">Mục tiêu học tập</a></li>
  <li><a href="#ý-chính" id="toc-ý-chính" class="nav-link" data-scroll-target="#ý-chính">Ý chính</a></li>
  <li><a href="#nội-dung" id="toc-nội-dung" class="nav-link" data-scroll-target="#nội-dung">Nội dung</a></li>
  <li><a href="#thực-hành" id="toc-thực-hành" class="nav-link" data-scroll-target="#thực-hành">Thực hành</a></li>
  <li><a href="#bài-tập" id="toc-bài-tập" class="nav-link" data-scroll-target="#bài-tập">Bài tập</a></li>
  <li><a href="#tài-liệu-tham-khảo" id="toc-tài-liệu-tham-khảo" class="nav-link" data-scroll-target="#tài-liệu-tham-khảo">Tài liệu tham khảo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m08-calibration/index.html">M08 · Hiệu chuẩn mô hình (calibration)</a></li><li class="breadcrumb-item"><a href="../../kb/m08-calibration/l01-why-calibrate.html"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></h1>
<p class="subtitle lead">Chọn mục tiêu hiệu chuẩn, đo mức độ phù hợp và nhận ra khi tham số không nhận dạng được</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled" title="Vì sao bạn nên quan tâm?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vì sao bạn nên quan tâm?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ở mỗi huyện, tổ chống lao ghi từng ca bệnh vào sổ rồi báo cáo lên Chương trình Chống lao Quốc gia. Cộng cả nước, năm 2024 có 106,392 ca mới và tái phát được báo cáo, trong khi WHO ước tính khoảng 184,000 người mắc lao trong năm đó: chênh lệch cỡ 78,000 người không có tên trong sổ <span class="citation" data-cites="who2026ghotb">(<a href="../m00-r-foundations/index.html#ref-who2026ghotb" role="doc-biblioref">World Health Organization 2026b</a>)</span>. Họ vẫn có thể lây cho người khác. Mỗi ca mà hệ thống thường quy tìm ra tốn khoảng 6.7 triệu VNĐ riêng cho khâu chẩn đoán (tính cả những người phải xét nghiệm mới tìm được một ca), bằng 1.3 tháng lương tối thiểu vùng I <span class="citation" data-cites="schwalb2025potential chinhphu2025nd293">(<a href="../m00-r-foundations/index.html#ref-schwalb2025potential" role="doc-biblioref">Schwalb và c.s. 2025</a>; <a href="../m00-r-foundations/index.html#ref-chinhphu2025nd293" role="doc-biblioref">Chính phủ 2025</a>)</span>. Không ai đếm trực tiếp được nhóm người bị bỏ sót, cũng không ai đo được bệnh lây nhanh đến đâu. Bài này giúp bạn quyết định phải đưa số liệu nào vào mô hình (số ca báo cáo, điều tra hiện mắc) để ước lượng được các con số đó.</p>
</div>
</div>
<section id="mục-tiêu-học-tập" class="level2">
<h2 class="anchored" data-anchor-id="mục-tiêu-học-tập">Mục tiêu học tập</h2>
<p>Sau bài này, bạn có thể:</p>
<ol type="1">
<li>Giải thích khi nào một tham số phải được hiệu chuẩn thay vì lấy thẳng từ y văn.</li>
<li>Định nghĩa mục tiêu hiệu chuẩn (calibration target) sao cho đầu ra mô hình đo đúng cùng một đại lượng, và đặt mục tiêu mô phỏng cạnh số liệu thật của Việt Nam.</li>
<li>Viết hàm hợp lý (likelihood) và tổng bình phương sai số có trọng số (weighted SSE) cho nhiều mục tiêu, và giải thích vì sao hai thước đo này gần như tương đương.</li>
<li>Kiểm chứng mô hình trước khi hiệu chuẩn: bước thời gian, bảo toàn dân số, so sánh với một bộ giải độc lập.</li>
<li>Phát hiện tính không nhận dạng được (non-identifiability) bằng mặt log của hàm hợp lý (log-likelihood) và nêu cách khắc phục.</li>
</ol>
</section>
<section id="ý-chính" class="level2">
<h2 class="anchored" data-anchor-id="ý-chính">Ý chính</h2>
<ul>
<li>Hiệu chuẩn mô hình (calibration) ước lượng các tham số không đo được bằng cách buộc đầu ra mô hình khớp số liệu quan sát: biết đầu ra, tìm đầu vào.</li>
<li>Bảy quyết định của một lần hiệu chuẩn: tham số, mục tiêu, thước đo mức độ phù hợp, cách tìm kiếm, tiêu chí chấp nhận, điểm dừng, cách đưa kết quả vào phân tích kinh tế <span class="citation" data-cites="vanni2011calibrating">(<a href="../m00-r-foundations/index.html#ref-vanni2011calibrating" role="doc-biblioref">Vanni và c.s. 2011</a>)</span>.</li>
<li>Mục tiêu phải đo cùng đại lượng với đầu ra mô hình (quần thể, định nghĩa ca bệnh, năm); sai định nghĩa thì “khớp” vẫn cho tham số sai. Điều tra năm 2017–2018 đo người từ 15 tuổi, nên phải quy về mọi lứa tuổi trước khi so.</li>
<li>Hàm hợp lý mô tả cách dữ liệu được sinh ra: ở đây điều tra theo nhị thức với cỡ mẫu hiệu dụng (effective sample size), số ca báo cáo theo phân phối chuẩn (dữ liệu thật thường cần Poisson hay nhị thức âm). Khi sai số chuẩn, tổng bình phương sai số có trọng số bằng −2 lần log của hàm hợp lý cộng hằng số.</li>
<li>Kiểm chứng mô hình trước khi hiệu chuẩn: bước thời gian đủ nhỏ, dân số được bảo toàn, khớp một bộ giải độc lập. Hiệu chuẩn không sửa được mô hình sai.</li>
<li>Số ca báo cáo ≈ tỷ suất phát hiện × thời gian chưa phát hiện, nên riêng nó không phân biệt “lây nhiều, phát hiện kém” với “lây ít, phát hiện tốt”; điều tra hiện mắc giải quyết điều đó. Không nhận dạng được là giới hạn của dữ liệu, không phải lỗi code.</li>
</ul>
</section>
<section id="nội-dung" class="level2">
<h2 class="anchored" data-anchor-id="nội-dung">Nội dung</h2>
<section id="khi-nào-cần-hiệu-chuẩn" class="level3">
<h3 class="anchored" data-anchor-id="khi-nào-cần-hiệu-chuẩn">Khi nào cần hiệu chuẩn</h3>
<p>Ở M02, hầu hết tham số lấy được từ y văn. Mô hình lây truyền thì khác: hệ số lây truyền (β), tỷ suất phát hiện ca bệnh hay xu hướng lây truyền theo thời gian không nghiên cứu nào đo trực tiếp được. Ta chỉ thấy hệ quả của chúng, như số ca được báo cáo hay tỷ lệ hiện mắc trong một cuộc điều tra. Hiệu chuẩn tìm các giá trị tham số làm mô hình tái tạo được những con số đó <span class="citation" data-cites="stout2009calibration">(<a href="../m00-r-foundations/index.html#ref-stout2009calibration" role="doc-biblioref">Stout và c.s. 2009</a>)</span>.</p>
<p>Xác minh mô hình (verification, M02 Bài 5) hỏi code có đúng thiết kế không; thẩm định mô hình (validation, Bài 4) hỏi mô hình có phản ánh đúng thực tế không; hiệu chuẩn là bước ước lượng nằm giữa. Ba mô hình lao gần đây cho Việt Nam đều được hiệu chuẩn theo số liệu trong nước trước khi dùng để đánh giá can thiệp <span class="citation" data-cites="horton2022population bui2025impact schwalb2025potential">(<a href="../m00-r-foundations/index.html#ref-horton2022population" role="doc-biblioref">Horton và c.s. 2022</a>; <a href="../m00-r-foundations/index.html#ref-bui2025impact" role="doc-biblioref">Bui và c.s. 2025</a>; <a href="../m00-r-foundations/index.html#ref-schwalb2025potential" role="doc-biblioref">Schwalb và c.s. 2025</a>)</span>.</p>
</section>
<section id="ví-dụ-xuyên-suốt-diễn-tiến-tự-nhiên-của-bệnh-lao" class="level3">
<h3 class="anchored" data-anchor-id="ví-dụ-xuyên-suốt-diễn-tiến-tự-nhiên-của-bệnh-lao">Ví dụ xuyên suốt: diễn tiến tự nhiên của bệnh lao</h3>
<p>Mô hình có sáu ngăn, tính theo tỷ lệ dân số. Người chết được thay bằng trẻ sinh vào ngăn S, nên dân số không đổi.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>flowchart LR</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  S["S: chưa nhiễm"] -- "λ(t)" --&gt; E["E: tiềm ẩn sớm"]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  E -- "tiến triển nhanh" --&gt; I["I: lao hoạt động,&lt;br/&gt;chưa phát hiện"]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  E -- "ổn định" --&gt; L["L: tiềm ẩn muộn"]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  L -- "tái hoạt động" --&gt; I</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  L -- "tái nhiễm" --&gt; E</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  I -- "δ: phát hiện" --&gt; T["T: đang điều trị"]</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  I -- "tự khỏi" --&gt; R["R: đã khỏi"]</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  I -- "tử vong do lao" --&gt; D(("tử vong"))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  T -- "hoàn thành" --&gt; R</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  T -- "tử vong do lao" --&gt; D</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  R -- "tái phát" --&gt; I</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  R -- "tái nhiễm" --&gt; E</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  S["S: chưa nhiễm"] -- "λ(t)" --&gt; E["E: tiềm ẩn sớm"]
  E -- "tiến triển nhanh" --&gt; I["I: lao hoạt động,&lt;br/&gt;chưa phát hiện"]
  E -- "ổn định" --&gt; L["L: tiềm ẩn muộn"]
  L -- "tái hoạt động" --&gt; I
  L -- "tái nhiễm" --&gt; E
  I -- "δ: phát hiện" --&gt; T["T: đang điều trị"]
  I -- "tự khỏi" --&gt; R["R: đã khỏi"]
  I -- "tử vong do lao" --&gt; D(("tử vong"))
  T -- "hoàn thành" --&gt; R
  T -- "tử vong do lao" --&gt; D
  R -- "tái phát" --&gt; I
  R -- "tái nhiễm" --&gt; E
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Lực lây nhiễm (force of infection) là <span class="math inline">\(\lambda(t) = \beta(t)\, I(t)\)</span>, với hệ số lây truyền giảm dần từ năm 2000:</p>
<p><span class="math display">\[
\beta(t) = \beta \, e^{-k_\beta \,(t - 2000)} .
\]</span></p>
<p>Mô hình là một hệ phương trình vi phân thường. Ở M05 ta giải hệ này bằng <code>deSolve</code> cho một bộ tham số; hiệu chuẩn cần chạy hàng chục nghìn bộ, nên <code>run_tb_model()</code> tự cài bộ tích phân Runge–Kutta bậc 4 (RK4) bằng base R, mỗi bộ tham số một hàng của ma trận trạng thái. Với bước <span class="math inline">\(h\)</span>, RK4 tính bốn độ dốc <span class="math inline">\(k_1, \dots, k_4\)</span> rồi cập nhật <span class="math inline">\(y_{t+h} = y_t + \tfrac{h}{6}(k_1 + 2k_2 + 2k_3 + k_4)\)</span>. Bước 0.50 năm cho các năm được báo cáo, sau 200 năm chạy khởi động (burn-in) với bước 1 năm để mô hình gần trạng thái cân bằng. Cách cho mỗi người rời ngăn ở cuối mỗi bước (kiểu chu kỳ của M02) kéo dài mọi thời gian cư trú thêm khoảng nửa bước, nên các thời gian 3 năm hay 6 tháng trong bảng tham số không còn đúng nghĩa; đó là lý do cần hiệu chỉnh nửa chu kỳ hoặc một bộ tích phân tốt hơn.</p>
<p>Tử vong nền không gõ tay mà lấy từ bảng sống WHO 2023 của Việt Nam, dùng chung cho cả khóa học <span class="citation" data-cites="who2026lifetables">(<a href="../m00-r-foundations/index.html#ref-who2026lifetables" role="doc-biblioref">World Health Organization 2026a</a>)</span>: <span class="math inline">\(\mu = 1/e_0\)</span>, với tuổi thọ lúc sinh <span class="math inline">\(e_0\)</span> = 74.3 năm, tức 13.5 ca tử vong trên 1,000 người mỗi năm. Trong một quần thể có cỡ không đổi, lựa chọn này làm thời gian sống trung bình trong mô hình bằng đúng <span class="math inline">\(e_0\)</span>.</p>
<p>Tham số diễn tiến tự nhiên lấy từ y văn khi có thể. Lao phổi AFB dương, HIV âm, không điều trị có tỷ lệ tử vong 10 năm trung bình có trọng số 70% (khoảng 53%–86%); lao AFB âm cấy dương khoảng 20%; bệnh kéo dài khoảng 3 năm ở cả hai loại <span class="citation" data-cites="tiemersma2011natural">(<a href="../m00-r-foundations/index.html#ref-tiemersma2011natural" role="doc-biblioref">Tiemersma và c.s. 2011</a>)</span>. Mô hình chỉ có một ngăn lao hoạt động, nên dùng trung bình có trọng số theo tỷ lệ AFB dương. Tỷ lệ này lấy từ điều tra quốc gia 2017–2018: lao AFB dương chiếm 79 trong 322 ca trên 100,000 người lớn, tức khoảng 25% <span class="citation" data-cites="nguyen2020second">(<a href="../m00-r-foundations/index.html#ref-nguyen2020second" role="doc-biblioref">Nguyen và c.s. 2020</a>)</span>, cho tỷ lệ tử vong trung bình 32%. Có 14% người nhiễm lần đầu ở tuổi trưởng thành phát bệnh trong 5 năm đầu <span class="citation" data-cites="vynnycky1997natural">(<a href="../m00-r-foundations/index.html#ref-vynnycky1997natural" role="doc-biblioref">Vynnycky và Fine 1997</a>)</span>; ta dùng con số này gần đúng làm tỷ lệ tiến triển nhanh khỏi giai đoạn tiềm ẩn sớm, dài 2 năm (giá trị minh họa; có nghiên cứu cho rằng giai đoạn này ngắn hơn nhiều so với các mô hình cũ giả định <span class="citation" data-cites="ragonnet2017optimally">(<a href="../m00-r-foundations/index.html#ref-ragonnet2017optimally" role="doc-biblioref">Ragonnet và c.s. 2017</a>)</span>). Mức bảo vệ 79% chống bệnh sau tái nhiễm lấy từ <span class="citation" data-cites="andrews2012risk">Andrews và c.s. (<a href="../m00-r-foundations/index.html#ref-andrews2012risk" role="doc-biblioref">2012</a>)</span>, cao hơn nhiều so với ước lượng của <span class="citation" data-cites="vynnycky1997natural">Vynnycky và Fine (<a href="../m00-r-foundations/index.html#ref-vynnycky1997natural" role="doc-biblioref">1997</a>)</span>, nên là một lựa chọn có ảnh hưởng. Tỷ suất tái hoạt động và tái phát là giá trị minh họa; các mô hình đã công bố dùng giá trị rất khác nhau cho chúng <span class="citation" data-cites="menzies2018progression">(<a href="../m00-r-foundations/index.html#ref-menzies2018progression" role="doc-biblioref">Menzies và c.s. 2018</a>)</span>.</p>
<p>Ba tham số được hiệu chuẩn, mỗi tham số trong một khoảng cho phép (khoảng tiên nghiệm là giá trị minh họa): hệ số lây truyền <span class="math inline">\(\beta\)</span> (từ 4 đến 30 mỗi năm), tỷ suất phát hiện và bắt đầu điều trị <span class="math inline">\(\delta\)</span>, và tốc độ giảm lây truyền <span class="math inline">\(k_\beta\)</span>.</p>
</section>
<section id="mục-tiêu-hiệu-chuẩn-mô-phỏng-và-thật" class="level3">
<h3 class="anchored" data-anchor-id="mục-tiêu-hiệu-chuẩn-mô-phỏng-và-thật">Mục tiêu hiệu chuẩn: mô phỏng và thật</h3>
<p>Bài này dùng <strong>mục tiêu mô phỏng</strong>, sinh từ chính mô hình tại một bộ “giá trị thật” cộng sai số lấy mẫu. Vì biết đáp án, ta kiểm tra được mỗi phương pháp có tìm lại giá trị thật không (phép thử phục hồi tham số, parameter recovery test). Giá trị thật được chọn gần bộ khớp nhất với số liệu Việt Nam, nên thế giới mô phỏng trông giống Việt Nam năm 2017. Có ba loại mục tiêu:</p>
<ul>
<li>Số ca được báo cáo mỗi năm từ 2010 đến 2024, với sai số báo cáo có hệ số biến thiên 5% (giá trị minh họa).</li>
<li>Một cuộc điều tra tỷ lệ hiện mắc năm 2017, dùng để hiệu chuẩn.</li>
<li>Một cuộc điều tra năm 2007, <strong>giữ lại</strong> để thẩm định ở Bài 4.</li>
</ul>
<p>Đặt cạnh chúng là <strong>mục tiêu thật</strong>: số ca lao mới và tái phát mà Việt Nam báo cáo cho WHO, chia cho dân số của Ngân hàng Thế giới <span class="citation" data-cites="who2026ghotb worldbank2026wdipop">(<a href="../m00-r-foundations/index.html#ref-who2026ghotb" role="doc-biblioref">World Health Organization 2026b</a>; <a href="../m00-r-foundations/index.html#ref-worldbank2026wdipop" role="doc-biblioref">World Bank 2026b</a>)</span>, và điều tra quốc gia lần 2. Năm 2021 bị loại vì số ca giảm mạnh do gián đoạn dịch vụ trong đại dịch COVID-19, điều mà mô hình này không mô tả <span class="citation" data-cites="bui2025impact">(<a href="../m00-r-foundations/index.html#ref-bui2025impact" role="doc-biblioref">Bui và c.s. 2025</a>)</span>. Điều tra chỉ đo người từ 15 tuổi, nên được nhân với tỷ lệ người lớn trong dân số (75.6% năm 2017 <span class="citation" data-cites="worldbank2026wdipop0014">(<a href="../m00-r-foundations/index.html#ref-worldbank2026wdipop0014" role="doc-biblioref">World Bank 2026a</a>)</span>), giả định trẻ em gần như không có lao phổi có bằng chứng vi khuẩn. Ước tính tỷ lệ mới mắc và tử vong của WHO không dùng làm mục tiêu: chúng là kết quả của một mô hình khác, nên chỉ dùng để đối chiếu.</p>
<p>Độ chính xác của điều tra lấy từ thiết kế của điều tra tỷ lệ hiện mắc lao quốc gia lần 2: 61,763 người tham gia, tỷ lệ hiện mắc ở người từ 15 tuổi 322 (KTC 95%: 260–399) trên 100,000 <span class="citation" data-cites="nguyen2020second">(<a href="../m00-r-foundations/index.html#ref-nguyen2020second" role="doc-biblioref">Nguyen và c.s. 2020</a>)</span>. Khoảng tin cậy rộng hơn khoảng của mẫu ngẫu nhiên đơn vì điều tra lấy mẫu cụm, rồi bù trừ dữ liệu thiếu và gia quyền. Hệ số thiết kế hiệu dụng (effective design effect) suy ra từ khoảng tin cậy đã công bố:</p>
<p><span class="math display">\[
\text{deff} = \left(\frac{\text{SE}_{\text{từ KTC}}}{\text{SE}_{\text{mẫu ngẫu nhiên đơn}}}\right)^2, \qquad n_{\text{hiệu dụng}} = \frac{n}{\text{deff}} ,
\]</span></p>
<p>ở đây deff ≈ 2.38. Con số này gộp ba nguồn: cụm, gia quyền và bù trừ dữ liệu thiếu. Riêng ước lượng thô (chưa bù trừ, chưa gia quyền), khoảng tin cậy trong bài báo cho hệ số 2.15, gần với giá trị lập kế hoạch cỡ mẫu của chính điều tra là 1.92 <span class="citation" data-cites="nguyen2020second">(<a href="../m00-r-foundations/index.html#ref-nguyen2020second" role="doc-biblioref">Nguyen và c.s. 2020</a>)</span>; vậy phần lớn hệ số hiệu dụng đến từ thiết kế cụm. Hàm hợp lý của điều tra dùng <span class="math inline">\(n_{\text{hiệu dụng}}\)</span>, không dùng <span class="math inline">\(n\)</span>.</p>
</section>
<section id="đo-mức-độ-phù-hợp" class="level3">
<h3 class="anchored" data-anchor-id="đo-mức-độ-phù-hợp">Đo mức độ phù hợp</h3>
<p>Gọi <span class="math inline">\(m_j(\theta)\)</span> là đầu ra mô hình cho mục tiêu <span class="math inline">\(j\)</span> khi tham số là <span class="math inline">\(\theta\)</span>. Với số ca báo cáo <span class="math inline">\(y_j\)</span> có độ lệch chuẩn <span class="math inline">\(\sigma_j\)</span>, và điều tra có <span class="math inline">\(x\)</span> ca trong <span class="math inline">\(n_{\text{hiệu dụng}}\)</span> người:</p>
<p><span class="math display">\[
\ell(\theta) = \sum_{j} \log \phi\!\left(y_j;\, m_j(\theta), \sigma_j\right) + \log \text{Binom}\!\left(x;\, n_{\text{hiệu dụng}}, \pi(\theta)\right),
\]</span></p>
<p>với <span class="math inline">\(\pi(\theta)\)</span> là tỷ lệ hiện mắc theo mô hình. Cộng các log-likelihood nghĩa là giả định sai số của các mục tiêu độc lập với nhau. Thước đo thứ hai là tổng bình phương sai số có trọng số:</p>
<p><span class="math display">\[
\text{WSSE}(\theta) = \sum_j \left(\frac{y_j - m_j(\theta)}{\sigma_j}\right)^2 .
\]</span></p>
<p>Khi sai số tuân theo phân phối chuẩn, <span class="math inline">\(-2\ell(\theta) = \text{WSSE}(\theta) + \text{hằng số}\)</span> (phần điều tra nhị thức chỉ xấp xỉ): chọn trọng số là chọn mức tin cậy cho từng mục tiêu. Trọng số tùy ý có thể chọn ra bộ “tốt nhất” khác và dẫn đến kết luận kinh tế khác <span class="citation" data-cites="enns2015identifying">(<a href="../m00-r-foundations/index.html#ref-enns2015identifying" role="doc-biblioref">Enns và c.s. 2015</a>)</span>.</p>
</section>
<section id="tính-nhận-dạng-được" class="level3">
<h3 class="anchored" data-anchor-id="tính-nhận-dạng-được">Tính nhận dạng được</h3>
<p>Gần trạng thái cân bằng, số ca báo cáo mỗi năm xấp xỉ <span class="math inline">\(\delta \times I\)</span>. Tích này giữ nguyên khi <span class="math inline">\(\delta\)</span> tăng và <span class="math inline">\(I\)</span> giảm, với <span class="math inline">\(\beta\)</span> điều chỉnh theo. Kết quả là một “sống núi” (ridge): một dải dài các bộ tham số khớp số ca báo cáo như nhau. Điều tra đo <span class="math inline">\(I\)</span> trực tiếp nên cắt ngang sống núi đó.</p>
<p>Để vẽ trên mặt phẳng, bài dùng hàm hợp lý profile (profile likelihood): với mỗi cặp <span class="math inline">\((\beta, \delta)\)</span>, lấy <span class="math inline">\(k_\beta\)</span> khớp nhất. Vùng có log-likelihood thấp hơn cực đại không quá <span class="math inline">\(\chi^2_{2;\,0.95}/2 \approx\)</span> 3.0 là vùng tin cậy 95% xấp xỉ. Các bộ khớp như nhau có thể cho dự báo và quyết định khác nhau <span class="citation" data-cites="alarid2018nonidentifiability">(<a href="../m00-r-foundations/index.html#ref-alarid2018nonidentifiability" role="doc-biblioref">Alarid-Escudero và c.s. 2018</a>)</span>. Cách khắc phục: thêm mục tiêu đo một tổ hợp tham số khác, dùng tiên nghiệm có thông tin (Bài 3), hoặc giảm số tham số hiệu chuẩn; luôn báo cáo vấn đề.</p>
</section>
</section>
<section id="thực-hành" class="level2">
<h2 class="anchored" data-anchor-id="thực-hành">Thực hành</h2>
<p>Nạp hàm dùng chung, số liệu Việt Nam dùng chung (<code>vn_data.R</code>) và hàm của module. <code>tb_params()</code> đọc bảng tham số rồi tính thêm các giá trị lấy từ dữ liệu chung, như tử vong nền từ bảng sống.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vietnamese text in figures needs a UTF-8 locale (Rscript may start in the "C" locale)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">isTRUE</span>(<span class="fu">l10n_info</span>()[[<span class="st">"UTF-8"</span>]])) <span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_CTYPE"</span>, <span class="st">"en_US.UTF-8"</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/helpers.R"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/vn_data.R"</span>)                    <span class="co"># course-wide Vietnamese data (life table, prices)</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"code/model.R"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">tb_params</span>()                                    <span class="co"># fixed parameters + values derived from shared data</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>pc <span class="ot">&lt;-</span> <span class="fu">read_params</span>(<span class="st">"params/calibration.csv"</span>)         <span class="co"># calibrated parameters: truth + prior bounds</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>bounds <span class="ot">&lt;-</span> <span class="fu">prior_bounds</span>(pc)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>th_true <span class="ot">&lt;-</span> <span class="fu">theta_true</span>(pc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Bảng tham số hiệu chuẩn chứa giá trị thật (cột <code>value</code>) và khoảng cho phép. Kiểm tra: số giá trị minh họa trong bảng tham số cố định, và ba giá trị suy ra từ dữ liệu chung.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Three parameters cannot be observed directly: they will be calibrated</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>calib_tab <span class="ot">&lt;-</span> <span class="fu">attr</span>(pc, <span class="st">"table"</span>)[, <span class="fu">c</span>(<span class="st">"name"</span>, <span class="st">"value"</span>, <span class="st">"low"</span>, <span class="st">"high"</span>, <span class="st">"unit"</span>)]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>calib_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    name value low high    unit
1   beta  6.70 4.0 30.0 mỗi năm
2  delta  0.45 0.1  2.0 mỗi năm
3 k_beta  0.02 0.0  0.1 mỗi năm</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fixed parameters: how many come from a verified source, how many are illustrative?</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>fixed_tab <span class="ot">&lt;-</span> <span class="fu">attr</span>(p, <span class="st">"table"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">illustrative =</span> fixed_tab<span class="sc">$</span>illustrative)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>illustrative
FALSE  TRUE 
   27    22 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Values computed from the shared course data, e.g. background mortality from the WHO life table</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>derived_tab <span class="ot">&lt;-</span> <span class="fu">attr</span>(p, <span class="st">"derived"</span>)[, <span class="fu">c</span>(<span class="st">"name"</span>, <span class="st">"value"</span>, <span class="st">"unit"</span>)]</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>derived_tab<span class="sc">$</span>value <span class="ot">&lt;-</span> <span class="fu">signif</span>(derived_tab<span class="sc">$</span>value, <span class="dv">4</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>derived_tab[derived_tab<span class="sc">$</span>name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"mu_bg"</span>, <span class="st">"age_tb"</span>, <span class="st">"yll_death"</span>), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       name    value    unit
1     mu_bg  0.01346 mỗi năm
2    age_tb 48.27000    tuổi
3 yll_death 29.84000     năm</code></pre>
</div>
</div>
<p>22 trong 49 tham số cố định là giá trị minh họa hoặc lựa chọn mô hình hóa. Chạy mô hình một lần ở giá trị thật. Kiểm tra: dân số được bảo toàn, không ngăn nào âm, số ca báo cáo đúng bằng <span class="math inline">\(\delta \times\)</span> thời gian chưa phát hiện, và mô hình đứng yên ở trạng thái cân bằng khi không có xu hướng giảm (<span class="math inline">\(k_\beta = 0\)</span>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One run at the "true" values: annual outputs per 100,000 population</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>sim_true <span class="ot">&lt;-</span> <span class="fu">run_tb_model</span>(th_true, p)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>show_years <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"2000"</span>, <span class="st">"2007"</span>, <span class="st">"2017"</span>, <span class="st">"2024"</span>, <span class="st">"2035"</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>out_true <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="at">prevalence =</span> sim_true<span class="sc">$</span>prev[<span class="dv">1</span>, show_years],</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">notifications =</span> sim_true<span class="sc">$</span>notif[<span class="dv">1</span>, show_years],</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">incidence =</span> sim_true<span class="sc">$</span>inc[<span class="dv">1</span>, show_years],</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tb_deaths =</span> sim_true<span class="sc">$</span>deaths[<span class="dv">1</span>, show_years])</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(out_true, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               2000  2007  2017  2024  2035
prevalence    308.8 289.3 239.8 210.5 174.9
notifications 138.9 130.2 107.9  94.7  78.7
incidence     245.8 225.9 186.4 164.0 136.5
tb_deaths      37.6  35.2  29.2  25.7  21.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sanity checks: the population is conserved and no compartment is negative</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(<span class="fu">sum</span>(sim_true<span class="sc">$</span>state_end) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">&lt;</span> <span class="fl">1e-10</span>, <span class="fu">all</span>(sim_true<span class="sc">$</span>state_end <span class="sc">&gt;=</span> <span class="dv">0</span>))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Notifications are detection rate x time spent undetected: an exact identity in this model</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">max</span>(<span class="fu">abs</span>(sim_true<span class="sc">$</span>notif <span class="sc">-</span> th_true[[<span class="st">"delta"</span>]] <span class="sc">*</span> sim_true<span class="sc">$</span>prev)) <span class="sc">&lt;</span> <span class="fl">1e-8</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># With no decline in transmission (k_beta = 0) the model must stay at its equilibrium</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>th_flat <span class="ot">&lt;-</span> th_true</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>th_flat[<span class="st">"k_beta"</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>sim_flat <span class="ot">&lt;-</span> <span class="fu">run_tb_model</span>(th_flat, p)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>drift <span class="ot">&lt;-</span> sim_flat<span class="sc">$</span>prev[<span class="dv">1</span>, <span class="st">"2035"</span>] <span class="sc">/</span> sim_flat<span class="sc">$</span>prev[<span class="dv">1</span>, <span class="st">"2000"</span>] <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(drift, <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2035 
-2e-04 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(drift) <span class="sc">&lt;</span> <span class="fl">0.005</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Khi tắt xu hướng giảm, tỷ lệ hiện mắc chỉ trôi 0.02% trong 35 năm, nên trạng thái đầu kỳ đã gần cân bằng.</p>
<p>Trước khi hiệu chuẩn, kiểm chứng mô hình bốn cách: giảm bước thời gian 4 lần, so với <code>deSolve</code> (một bộ tham số, dung sai chặt), kiểm tra tổng các đạo hàm bằng 0, và kéo dài gấp đôi thời gian chạy khởi động. Kiểm tra: mọi chênh lệch phải nhỏ.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verification 1: make the step 4 times shorter. Results must hardly move.</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>p_fine <span class="ot">&lt;-</span> p</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>p_fine<span class="sc">$</span>dt <span class="ot">&lt;-</span> p<span class="sc">$</span>dt <span class="sc">/</span> <span class="dv">4</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>p_fine<span class="sc">$</span>dt_burnin <span class="ot">&lt;-</span> p<span class="sc">$</span>dt_burnin <span class="sc">/</span> <span class="dv">4</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">101</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>X_check <span class="ot">&lt;-</span> <span class="fu">rbind</span>(th_true, <span class="fu">lhs_sample</span>(<span class="dv">40</span>, bounds<span class="sc">$</span>lower, bounds<span class="sc">$</span>upper))   <span class="co"># true values + 40 prior draws</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>outs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"prev"</span>, <span class="st">"notif"</span>, <span class="st">"inc"</span>, <span class="st">"deaths"</span>, <span class="st">"py_T"</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>sim_a <span class="ot">&lt;-</span> <span class="fu">run_tb_model</span>(X_check, p)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>sim_b <span class="ot">&lt;-</span> <span class="fu">run_tb_model</span>(X_check, p_fine)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>rel_diff <span class="ot">&lt;-</span> <span class="cf">function</span>(a, b) <span class="fu">abs</span>(a <span class="sc">-</span> b) <span class="sc">/</span> <span class="fu">pmax</span>(<span class="fu">abs</span>(b), <span class="dv">1</span>)    <span class="co"># relative to the finer run, floor 1 per 100,000</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>step_check <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">at_true_values =</span> <span class="fu">sapply</span>(outs, <span class="cf">function</span>(o) <span class="fu">max</span>(<span class="fu">rel_diff</span>(sim_a[[o]][<span class="dv">1</span>, ], sim_b[[o]][<span class="dv">1</span>, ]))),</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">over_prior =</span> <span class="fu">sapply</span>(outs, <span class="cf">function</span>(o) <span class="fu">max</span>(<span class="fu">rel_diff</span>(sim_a[[o]], sim_b[[o]]))))</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>step_check</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       prev        notif          inc       deaths         py_T
at_true_values 1.660076e-06 1.660076e-06 8.511431e-07 1.469368e-06 1.403162e-06
over_prior     2.197082e-05 2.197082e-05 1.135860e-05 1.759377e-05 9.273808e-06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(step_check[<span class="st">"at_true_values"</span>, ] <span class="sc">&lt;</span> <span class="fl">1e-4</span>), <span class="fu">all</span>(step_check[<span class="st">"over_prior"</span>, ] <span class="sc">&lt;</span> <span class="fl">0.01</span>))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Verification 2: the same equations integrated by deSolve (one parameter set, tight tolerances)</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(deSolve)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>r_check <span class="ot">&lt;-</span> <span class="fu">prepare_rates</span>(p)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>rhs <span class="ot">&lt;-</span> <span class="cf">function</span>(t, y, parms) {</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  beta_t <span class="ot">&lt;-</span> th_true[[<span class="st">"beta"</span>]] <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span>th_true[[<span class="st">"k_beta"</span>]] <span class="sc">*</span> <span class="fu">max</span>(<span class="dv">0</span>, t <span class="sc">-</span> p<span class="sc">$</span>year_trend))</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="fu">as.vector</span>(<span class="fu">tb_deriv</span>(<span class="fu">matrix</span>(y, <span class="at">nrow =</span> <span class="dv">1</span>), beta_t, th_true[[<span class="st">"delta"</span>]], r_check)))</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>y_init <span class="ot">&lt;-</span> <span class="fu">c</span>(p<span class="sc">$</span>init_S, p<span class="sc">$</span>init_E, p<span class="sc">$</span>init_L, p<span class="sc">$</span>init_I, p<span class="sc">$</span>init_T,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>            <span class="dv">1</span> <span class="sc">-</span> p<span class="sc">$</span>init_S <span class="sc">-</span> p<span class="sc">$</span>init_E <span class="sc">-</span> p<span class="sc">$</span>init_L <span class="sc">-</span> p<span class="sc">$</span>init_I <span class="sc">-</span> p<span class="sc">$</span>init_T, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>burn <span class="ot">&lt;-</span> deSolve<span class="sc">::</span><span class="fu">ode</span>(y_init, <span class="fu">c</span>(p<span class="sc">$</span>year_start <span class="sc">-</span> p<span class="sc">$</span>burnin_years, p<span class="sc">$</span>year_start), rhs, <span class="cn">NULL</span>,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>                     <span class="at">method =</span> <span class="st">"lsoda"</span>, <span class="at">rtol =</span> <span class="fl">1e-10</span>, <span class="at">atol =</span> <span class="fl">1e-12</span>)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>y_2000 <span class="ot">&lt;-</span> burn[<span class="dv">2</span>, <span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>y_2000[<span class="dv">7</span><span class="sc">:</span><span class="dv">11</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>trace <span class="ot">&lt;-</span> deSolve<span class="sc">::</span><span class="fu">ode</span>(y_2000, p<span class="sc">$</span>year_start<span class="sc">:</span>(p<span class="sc">$</span>year_end <span class="sc">+</span> <span class="dv">1</span>), rhs, <span class="cn">NULL</span>,</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>                      <span class="at">method =</span> <span class="st">"lsoda"</span>, <span class="at">rtol =</span> <span class="fl">1e-10</span>, <span class="at">atol =</span> <span class="fl">1e-12</span>)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>notif_desolve <span class="ot">&lt;-</span> <span class="fu">diff</span>(trace[, <span class="dv">1</span> <span class="sc">+</span> <span class="dv">7</span>]) <span class="sc">*</span> <span class="fl">1e5</span>                <span class="co"># column 1 is time; totals start at column 8</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>desolve_diff <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="fu">rel_diff</span>(sim_true<span class="sc">$</span>notif[<span class="dv">1</span>, ], notif_desolve))</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a><span class="fu">signif</span>(desolve_diff, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.7e-06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(desolve_diff <span class="sc">&lt;</span> <span class="fl">1e-4</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Verification 3: every flow leaves one compartment and enters another (or is a death replaced</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># by a birth), so the six derivatives of a random state sum to zero</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">102</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>y_rand <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">t</span>(<span class="fu">apply</span>(<span class="fu">matrix</span>(<span class="fu">runif</span>(<span class="dv">60</span>), <span class="dv">10</span>), <span class="dv">1</span>, <span class="cf">function</span>(v) v <span class="sc">/</span> <span class="fu">sum</span>(v))), <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="dv">5</span>))</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>d_rand <span class="ot">&lt;-</span> <span class="fu">tb_deriv</span>(y_rand, <span class="at">beta_t =</span> th_true[[<span class="st">"beta"</span>]], <span class="at">delta_t =</span> th_true[[<span class="st">"delta"</span>]], <span class="at">r =</span> r_check)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">max</span>(<span class="fu">abs</span>(<span class="fu">rowSums</span>(d_rand[, <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>]))) <span class="sc">&lt;</span> <span class="fl">1e-12</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Verification 4: does the starting state still matter? Double the burn-in.</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>p_long <span class="ot">&lt;-</span> p</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>p_long<span class="sc">$</span>burnin_years <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> p<span class="sc">$</span>burnin_years</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>burnin_effect <span class="ot">&lt;-</span> <span class="fu">run_tb_model</span>(th_true, p_long)<span class="sc">$</span>prev[<span class="dv">1</span>, <span class="st">"2017"</span>] <span class="sc">/</span> sim_true<span class="sc">$</span>prev[<span class="dv">1</span>, <span class="st">"2017"</span>] <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(burnin_effect, <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2017 
-4e-04 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(burnin_effect) <span class="sc">&lt;</span> <span class="fl">0.005</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Giảm bước 4 lần đổi kết quả tối đa 0.0002% ở giá trị thật và 0.00% trên 40 điểm rút từ tiên nghiệm; <code>deSolve</code> khác tối đa 0.0002%; gấp đôi thời gian chạy khởi động đổi tỷ lệ hiện mắc năm 2017 chỉ 0.04%. Bước thời gian không còn là nguồn sai số đáng kể ở vùng tham số hợp lý. Ở rìa tiên nghiệm, nơi bệnh gần như tự tắt, thời gian chạy khởi động vẫn ảnh hưởng, nhưng vùng đó có hợp lý rất thấp.</p>
<p>Sinh mục tiêu mô phỏng với seed cố định, nên mọi bài nhận cùng một bộ mục tiêu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SIMULATED targets: model output at the true values + sampling error (seed fixed)</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>targets <span class="ot">&lt;-</span> <span class="fu">make_targets</span>(p, pc, <span class="at">seed =</span> <span class="dv">2025</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Design effect of the real 2017-2018 survey, backed out of its published 95% CI</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>real <span class="ot">&lt;-</span> fixed_tab[fixed_tab<span class="sc">$</span>name <span class="sc">==</span> <span class="st">"vn_prev2017"</span>, ]</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>deff <span class="ot">&lt;-</span> <span class="fu">survey_deff</span>(p<span class="sc">$</span>survey_n, real<span class="sc">$</span>value, real<span class="sc">$</span>low, real<span class="sc">$</span>high)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>n_eff <span class="ot">&lt;-</span> targets<span class="sc">$</span>n_eff[targets<span class="sc">$</span>type <span class="sc">==</span> <span class="st">"prev"</span>][<span class="dv">1</span>]</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">design_effect =</span> <span class="fu">round</span>(deff, <span class="dv">2</span>), <span class="at">n_survey =</span> p<span class="sc">$</span>survey_n, <span class="at">n_effective =</span> n_eff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>design_effect      n_survey   n_effective 
         2.38      61763.00      25933.00 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>tg_show <span class="ot">&lt;-</span> targets[, <span class="fu">c</span>(<span class="st">"type"</span>, <span class="st">"year"</span>, <span class="st">"value"</span>, <span class="st">"sd"</span>, <span class="st">"use"</span>)]</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>tg_show<span class="sc">$</span>value <span class="ot">&lt;-</span> <span class="fu">round</span>(tg_show<span class="sc">$</span>value, <span class="dv">1</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>tg_show<span class="sc">$</span>sd <span class="ot">&lt;-</span> <span class="fu">round</span>(tg_show<span class="sc">$</span>sd, <span class="dv">1</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>tg_show</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    type year value   sd         use
1  notif 2010 127.4  6.4 calibration
2  notif 2011 121.4  6.1 calibration
3  notif 2012 123.5  6.2 calibration
4  notif 2013 124.1  6.2 calibration
5  notif 2014 116.5  5.8 calibration
6  notif 2015 111.3  5.6 calibration
7  notif 2016 112.2  5.6 calibration
8  notif 2017 107.5  5.4 calibration
9  notif 2018 104.0  5.2 calibration
10 notif 2019 107.5  5.4 calibration
11 notif 2020  99.9  5.0 calibration
12 notif 2021  91.3  4.6 calibration
13 notif 2022  96.1  4.8 calibration
14 notif 2023 100.1  5.0 calibration
15 notif 2024  99.8  5.0 calibration
16  prev 2017 273.8 32.4 calibration
17  prev 2007 312.3 34.7  validation</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>expected <span class="ot">&lt;-</span> <span class="fu">n_targets_expected</span>(p)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">nrow</span>(targets) <span class="sc">==</span> expected[[<span class="st">"total"</span>]], <span class="fu">sum</span>(targets<span class="sc">$</span>use <span class="sc">==</span> <span class="st">"calibration"</span>) <span class="sc">==</span> expected[[<span class="st">"calibration"</span>]],</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>          n_eff <span class="sc">&lt;</span> p<span class="sc">$</span>survey_n <span class="sc">/</span> <span class="dv">2</span>)       <span class="co"># the text says the effective sample size is below half of the participants</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Có 16 mục tiêu hiệu chuẩn và 1 mục tiêu giữ lại. Cỡ mẫu hiệu dụng của mỗi điều tra là 25,933 người, chưa bằng nửa số người tham gia. Tiếp theo, dựng bộ mục tiêu thật theo đúng định dạng đó và đặt hai bộ cạnh nhau. Kiểm tra: ở năm 2017, mô hình tại giá trị thật lệch số liệu Việt Nam không quá 15% ở cả ba chỉ số.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># REAL Vietnamese data next to the simulated targets: WHO notifications (new and relapse)</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># per 100,000, and the 2017-2018 survey turned into an all-age prevalence. Same format as</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># `targets`, so every function of the module works with either set.</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>targets_vn <span class="ot">&lt;-</span> <span class="fu">make_targets_vn</span>(p)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>who <span class="ot">&lt;-</span> <span class="fu">vn_tb_data</span>()</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>side <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">type =</span> targets<span class="sc">$</span>type, <span class="at">year =</span> targets<span class="sc">$</span>year, <span class="at">use =</span> targets<span class="sc">$</span>use,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">simulated =</span> <span class="fu">round</span>(targets<span class="sc">$</span>value, <span class="dv">1</span>),</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">real_vn =</span> <span class="fu">round</span>(targets_vn<span class="sc">$</span>value[<span class="fu">match</span>(<span class="fu">paste</span>(targets<span class="sc">$</span>type, targets<span class="sc">$</span>year),</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>                                                         <span class="fu">paste</span>(targets_vn<span class="sc">$</span>type, targets_vn<span class="sc">$</span>year))], <span class="dv">1</span>))</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>side</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    type year         use simulated real_vn
1  notif 2010 calibration     127.4   111.4
2  notif 2011 calibration     121.4   111.7
3  notif 2012 calibration     123.5   114.1
4  notif 2013 calibration     124.1   110.8
5  notif 2014 calibration     116.5   109.5
6  notif 2015 calibration     111.3   108.6
7  notif 2016 calibration     112.2   108.6
8  notif 2017 calibration     107.5   107.9
9  notif 2018 calibration     104.0   103.6
10 notif 2019 calibration     107.5   105.5
11 notif 2020 calibration      99.9   101.8
12 notif 2021 calibration      91.3      NA
13 notif 2022 calibration      96.1   102.8
14 notif 2023 calibration     100.1   104.2
15 notif 2024 calibration      99.8   105.4
16  prev 2017 calibration     273.8   242.9
17  prev 2007  validation     312.3      NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Context the targets do not contain: WHO incidence and TB mortality estimates, and the</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># model at its "true" values</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>yrs_ctx <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"2010"</span>, <span class="st">"2017"</span>, <span class="st">"2024"</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>ctx_tab <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="at">who_incidence =</span> who<span class="sc">$</span>inc_100k[<span class="fu">match</span>(yrs_ctx, who<span class="sc">$</span>year)],</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">model_incidence =</span> sim_true<span class="sc">$</span>inc[<span class="dv">1</span>, yrs_ctx],</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">who_tb_deaths =</span> who<span class="sc">$</span>mort_hivneg_100k[<span class="fu">match</span>(yrs_ctx, who<span class="sc">$</span>year)],</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">model_tb_deaths =</span> sim_true<span class="sc">$</span>deaths[<span class="dv">1</span>, yrs_ctx])</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(ctx_tab, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2010  2017  2024
who_incidence   231.0 188.0 182.0
model_incidence 213.6 186.4 164.0
who_tb_deaths    24.0  12.0  10.0
model_tb_deaths  33.5  29.2  25.7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Statements in the text: the simulated world is close to Viet Nam in 2017 (within 15%) ...</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>ratio_2017 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">notif =</span> sim_true<span class="sc">$</span>notif[<span class="dv">1</span>, <span class="st">"2017"</span>][[<span class="dv">1</span>]] <span class="sc">/</span> who<span class="sc">$</span>notif_100k[who<span class="sc">$</span>year <span class="sc">==</span> <span class="dv">2017</span>],</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">prev =</span> sim_true<span class="sc">$</span>prev[<span class="dv">1</span>, <span class="st">"2017"</span>][[<span class="dv">1</span>]] <span class="sc">/</span> targets_vn<span class="sc">$</span>value[targets_vn<span class="sc">$</span>type <span class="sc">==</span> <span class="st">"prev"</span>],</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">inc =</span> sim_true<span class="sc">$</span>inc[<span class="dv">1</span>, <span class="st">"2017"</span>][[<span class="dv">1</span>]] <span class="sc">/</span> who<span class="sc">$</span>inc_100k[who<span class="sc">$</span>year <span class="sc">==</span> <span class="dv">2017</span>])</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(ratio_2017, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>notif  prev   inc 
 1.00  0.99  0.99 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(ratio_2017 <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">&lt;</span> <span class="fl">0.15</span>))</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ... it declines faster than the real notifications, and it has far more TB deaths than WHO estimates</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>notif_change <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">simulated =</span> sim_true<span class="sc">$</span>notif[<span class="dv">1</span>, <span class="st">"2024"</span>][[<span class="dv">1</span>]] <span class="sc">/</span> sim_true<span class="sc">$</span>notif[<span class="dv">1</span>, <span class="st">"2010"</span>][[<span class="dv">1</span>]] <span class="sc">-</span> <span class="dv">1</span>,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">real =</span> who<span class="sc">$</span>notif_100k[who<span class="sc">$</span>year <span class="sc">==</span> <span class="dv">2024</span>] <span class="sc">/</span> who<span class="sc">$</span>notif_100k[who<span class="sc">$</span>year <span class="sc">==</span> <span class="dv">2010</span>] <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(notif_change, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>simulated      real 
   -0.233    -0.055 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>deaths_ratio_2024 <span class="ot">&lt;-</span> sim_true<span class="sc">$</span>deaths[<span class="dv">1</span>, <span class="st">"2024"</span>][[<span class="dv">1</span>]] <span class="sc">/</span> who<span class="sc">$</span>mort_hivneg_100k[who<span class="sc">$</span>year <span class="sc">==</span> <span class="dv">2024</span>]</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(deaths_ratio_2024, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(notif_change[[<span class="st">"simulated"</span>]] <span class="sc">&lt;</span> notif_change[[<span class="st">"real"</span>]], deaths_ratio_2024 <span class="sc">&gt;</span> <span class="fl">1.5</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Missing people with TB in 2024: WHO estimated incident cases minus notified cases</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>gap_2024 <span class="ot">&lt;-</span> who<span class="sc">$</span>inc_num[who<span class="sc">$</span>year <span class="sc">==</span> <span class="dv">2024</span>] <span class="sc">-</span> who<span class="sc">$</span>notif_newrel[who<span class="sc">$</span>year <span class="sc">==</span> <span class="dv">2024</span>]</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">notified_2024 =</span> who<span class="sc">$</span>notif_newrel[who<span class="sc">$</span>year <span class="sc">==</span> <span class="dv">2024</span>], <span class="at">estimated_2024 =</span> who<span class="sc">$</span>inc_num[who<span class="sc">$</span>year <span class="sc">==</span> <span class="dv">2024</span>],</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">missed_2024 =</span> gap_2024)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> notified_2024 estimated_2024    missed_2024 
        106392         184000          77608 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(gap_2024 <span class="sc">&gt;</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Năm 2017, thế giới mô phỏng gần Việt Nam: tỷ số mô hình/thật là 1.00 cho số ca báo cáo, 0.99 cho tỷ lệ hiện mắc và 0.99 cho tỷ lệ mới mắc. Hai khác biệt cần biết. Từ 2010 đến 2024, số ca báo cáo mô phỏng giảm 23%, còn số ca báo cáo thật chỉ giảm 5%. Và mô hình cho số tử vong do lao gấp 2.6 lần ước tính của WHO năm 2024: tỷ lệ tử vong lấy từ diễn tiến tự nhiên trước thời kỳ có thuốc <span class="citation" data-cites="tiemersma2011natural">(<a href="../m00-r-foundations/index.html#ref-tiemersma2011natural" role="doc-biblioref">Tiemersma và c.s. 2011</a>)</span> có thể không còn đúng với người bệnh ngày nay, hoặc WHO ước tính thấp. Mô hình không giải quyết được mâu thuẫn này; ta ghi lại nó để thẩm định ở Bài 2 và Bài 4.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>real_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">year =</span> targets<span class="sc">$</span>year, <span class="at">value =</span> targets<span class="sc">$</span>value, <span class="at">lo =</span> targets<span class="sc">$</span>value <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> targets<span class="sc">$</span>sd,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">hi =</span> targets<span class="sc">$</span>value <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> targets<span class="sc">$</span>sd, <span class="at">what =</span> <span class="fu">ifelse</span>(targets<span class="sc">$</span>type <span class="sc">==</span> <span class="st">"notif"</span>,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Số ca báo cáo /100,000"</span>, <span class="st">"Tỷ lệ hiện mắc /100,000"</span>), <span class="at">source =</span> <span class="st">"Mục tiêu mô phỏng"</span>),</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">year =</span> targets_vn<span class="sc">$</span>year, <span class="at">value =</span> targets_vn<span class="sc">$</span>value, <span class="at">lo =</span> targets_vn<span class="sc">$</span>value <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> targets_vn<span class="sc">$</span>sd,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">hi =</span> targets_vn<span class="sc">$</span>value <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> targets_vn<span class="sc">$</span>sd, <span class="at">what =</span> <span class="fu">ifelse</span>(targets_vn<span class="sc">$</span>type <span class="sc">==</span> <span class="st">"notif"</span>,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Số ca báo cáo /100,000"</span>, <span class="st">"Tỷ lệ hiện mắc /100,000"</span>), <span class="at">source =</span> <span class="st">"Việt Nam (WHO, điều tra 2017-2018)"</span>),</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">year =</span> who<span class="sc">$</span>year[who<span class="sc">$</span>year <span class="sc">&gt;=</span> <span class="dv">2010</span>], <span class="at">value =</span> who<span class="sc">$</span>inc_100k[who<span class="sc">$</span>year <span class="sc">&gt;=</span> <span class="dv">2010</span>],</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">lo =</span> who<span class="sc">$</span>inc_100k_lo[who<span class="sc">$</span>year <span class="sc">&gt;=</span> <span class="dv">2010</span>], <span class="at">hi =</span> who<span class="sc">$</span>inc_100k_hi[who<span class="sc">$</span>year <span class="sc">&gt;=</span> <span class="dv">2010</span>],</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">what =</span> <span class="st">"Mới mắc /100,000 (chỉ để đối chiếu)"</span>, <span class="at">source =</span> <span class="st">"Việt Nam (WHO, điều tra 2017-2018)"</span>))</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>yrs_all <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">colnames</span>(sim_true<span class="sc">$</span>notif))</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>model_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">year =</span> yrs_all, <span class="at">value =</span> sim_true<span class="sc">$</span>notif[<span class="dv">1</span>, ], <span class="at">what =</span> <span class="st">"Số ca báo cáo /100,000"</span>),</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">year =</span> yrs_all, <span class="at">value =</span> sim_true<span class="sc">$</span>prev[<span class="dv">1</span>, ], <span class="at">what =</span> <span class="st">"Tỷ lệ hiện mắc /100,000"</span>),</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">year =</span> yrs_all, <span class="at">value =</span> sim_true<span class="sc">$</span>inc[<span class="dv">1</span>, ], <span class="at">what =</span> <span class="st">"Mới mắc /100,000 (chỉ để đối chiếu)"</span>))</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>model_df <span class="ot">&lt;-</span> model_df[model_df<span class="sc">$</span>year <span class="sc">&gt;=</span> <span class="dv">2005</span> <span class="sc">&amp;</span> model_df<span class="sc">$</span>year <span class="sc">&lt;=</span> <span class="dv">2024</span>, ]</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>fig_real <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(real_df, <span class="fu">aes</span>(year, value, <span class="at">colour =</span> source)) <span class="sc">+</span></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> model_df, <span class="fu">aes</span>(year, value), <span class="at">inherit.aes =</span> <span class="cn">FALSE</span>, <span class="at">colour =</span> <span class="st">"grey55"</span>, <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), <span class="at">size =</span> <span class="fl">0.25</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.6</span>)) <span class="sc">+</span></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>what, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> pal_course[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)], <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_limits</span>(<span class="at">y =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Năm"</span>, <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Mục tiêu mô phỏng và số liệu thật của Việt Nam (đường xám: mô hình tại giá trị thật)"</span>) <span class="sc">+</span></span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb39-26"><a href="#cb39-26" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_real, <span class="st">"l01-real-vn.png"</span>, <span class="at">width =</span> <span class="fl">9.5</span>, <span class="at">height =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l01-real-vn.png" class="img-fluid figure-img"></p>
<figcaption>Mục tiêu mô phỏng (xanh) và số liệu thật của Việt Nam (cam). Thanh dọc: khoảng 95% của mục tiêu; với tỷ lệ mới mắc là khoảng bất định của WHO. Đường xám: mô hình tại giá trị thật.</figcaption>
</figure>
</div>
<p>Đo mức độ phù hợp ở giá trị thật và ở một bộ sai (tỷ suất phát hiện gấp đôi). Kiểm tra: bộ sai có log-likelihood thấp hơn.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Goodness of fit of the true values: log-likelihood and weighted SSE</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>gof_true <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">loglik_notif =</span> <span class="fu">loglik_targets</span>(sim_true, targets, <span class="at">types =</span> <span class="st">"notif"</span>),</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">loglik_prev  =</span> <span class="fu">loglik_targets</span>(sim_true, targets, <span class="at">types =</span> <span class="st">"prev"</span>),</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">loglik_total =</span> <span class="fu">loglik_targets</span>(sim_true, targets),</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">wsse_total   =</span> <span class="fu">wsse_targets</span>(sim_true, targets)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(gof_true, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>loglik_notif  loglik_prev loglik_total   wsse_total 
      -43.65        -3.65       -47.30         9.96 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A clearly wrong parameter set (detection rate doubled) fits much worse</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>th_wrong <span class="ot">&lt;-</span> th_true</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>th_wrong[<span class="st">"delta"</span>] <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> th_true[<span class="st">"delta"</span>]</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>sim_wrong <span class="ot">&lt;-</span> <span class="fu">run_tb_model</span>(th_wrong, p)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>gof_wrong <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">loglik_total =</span> <span class="fu">loglik_targets</span>(sim_wrong, targets),</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">wsse_total =</span> <span class="fu">wsse_targets</span>(sim_wrong, targets))</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(gof_wrong, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>loglik_total   wsse_total 
     -369.29       618.26 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(gof_wrong[<span class="st">"loglik_total"</span>] <span class="sc">&lt;</span> gof_true[<span class="st">"loglik_total"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ở giá trị thật, log-likelihood tổng là -47.30 và WSSE là 9.96. Bộ sai cho log-likelihood -369.29. Lưu ý: giá trị thật không nhất thiết khớp tốt nhất, vì mục tiêu có nhiễu (Bài 2).</p>
<p>Chạy mô hình cho cả một lưới ba chiều bằng một lần gọi hàm, rồi tính hàm hợp lý profile cho ba tập mục tiêu. Kiểm tra: vùng tin cậy khi dùng cả hai loại mục tiêu nhỏ hơn khi chỉ dùng số ca báo cáo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Log-likelihood over a 3-D grid of the calibrated parameters (about 43,000 runs, vectorised)</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">beta =</span> <span class="fu">seq</span>(bounds<span class="sc">$</span>lower[<span class="st">"beta"</span>], bounds<span class="sc">$</span>upper[<span class="st">"beta"</span>], <span class="at">by =</span> <span class="fl">0.5</span>),</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">delta =</span> <span class="fu">seq</span>(bounds<span class="sc">$</span>lower[<span class="st">"delta"</span>], bounds<span class="sc">$</span>upper[<span class="st">"delta"</span>], <span class="at">by =</span> <span class="fl">0.05</span>),</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">k_beta =</span> <span class="fu">seq</span>(bounds<span class="sc">$</span>lower[<span class="st">"k_beta"</span>], bounds<span class="sc">$</span>upper[<span class="st">"k_beta"</span>], <span class="at">by =</span> <span class="fl">0.005</span>))</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>sim_grid <span class="ot">&lt;-</span> <span class="fu">run_tb_model</span>(<span class="fu">as.matrix</span>(grid), p)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(sim_grid<span class="sc">$</span>notif)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 43407    36</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Profile log-likelihood: for each (beta, delta) pair keep the best-fitting k_beta</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>pair_key <span class="ot">&lt;-</span> <span class="fu">paste</span>(grid<span class="sc">$</span>beta, grid<span class="sc">$</span>delta)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>pairs_bd <span class="ot">&lt;-</span> <span class="fu">unique</span>(grid[, <span class="fu">c</span>(<span class="st">"beta"</span>, <span class="st">"delta"</span>)])</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>profile_ll <span class="ot">&lt;-</span> <span class="cf">function</span>(ll) {</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  best <span class="ot">&lt;-</span> <span class="fu">tapply</span>(ll, pair_key, max)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  prof <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(best[<span class="fu">paste</span>(pairs_bd<span class="sc">$</span>beta, pairs_bd<span class="sc">$</span>delta)])</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  prof <span class="sc">-</span> <span class="fu">max</span>(prof)                                 <span class="co"># 0 at the best pair</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>target_sets <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">"Chỉ dùng số ca báo cáo"</span> <span class="ot">=</span> <span class="st">"notif"</span>, <span class="st">"Chỉ dùng điều tra hiện mắc"</span> <span class="ot">=</span> <span class="st">"prev"</span>,</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Cả hai loại mục tiêu"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"notif"</span>, <span class="st">"prev"</span>))</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>surf <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (nm <span class="cf">in</span> <span class="fu">names</span>(target_sets)) {</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>  ll <span class="ot">&lt;-</span> <span class="fu">loglik_targets</span>(sim_grid, targets, <span class="at">types =</span> target_sets[[nm]])</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>  surf <span class="ot">&lt;-</span> <span class="fu">rbind</span>(surf, <span class="fu">data.frame</span>(pairs_bd, <span class="at">d_ll =</span> <span class="fu">profile_ll</span>(ll), <span class="at">targets =</span> nm))</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>surf<span class="sc">$</span>targets <span class="ot">&lt;-</span> <span class="fu">factor</span>(surf<span class="sc">$</span>targets, <span class="at">levels =</span> <span class="fu">names</span>(target_sets))</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>surf<span class="sc">$</span>d_ll_clip <span class="ot">&lt;-</span> <span class="fu">pmax</span>(surf<span class="sc">$</span>d_ll, <span class="sc">-</span><span class="dv">30</span>)</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Share of (beta, delta) pairs inside the approximate 95% region (profile &gt; -3.0)</span></span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>cut_95 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">qchisq</span>(<span class="fl">0.95</span>, <span class="dv">2</span>) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>region_share <span class="ot">&lt;-</span> <span class="fu">tapply</span>(surf<span class="sc">$</span>d_ll <span class="sc">&gt;</span> cut_95, surf<span class="sc">$</span>targets, mean)</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(region_share, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Chỉ dùng số ca báo cáo Chỉ dùng điều tra hiện mắc 
                     0.075                      0.467 
      Cả hai loại mục tiêu 
                     0.004 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(region_share[[<span class="st">"Cả hai loại mục tiêu"</span>]] <span class="sc">&lt;</span> region_share[[<span class="st">"Chỉ dùng số ca báo cáo"</span>]])</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="co"># How far the notification-only region reaches along delta, as a share of delta's prior range</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>in_region_n <span class="ot">&lt;-</span> surf<span class="sc">$</span>d_ll <span class="sc">&gt;</span> cut_95 <span class="sc">&amp;</span> surf<span class="sc">$</span>targets <span class="sc">==</span> <span class="st">"Chỉ dùng số ca báo cáo"</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>delta_region <span class="ot">&lt;-</span> <span class="fu">range</span>(surf<span class="sc">$</span>delta[in_region_n])</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>delta_span_notif <span class="ot">&lt;-</span> <span class="fu">diff</span>(delta_region) <span class="sc">/</span> (bounds<span class="sc">$</span>upper[[<span class="st">"delta"</span>]] <span class="sc">-</span> bounds<span class="sc">$</span>lower[[<span class="st">"delta"</span>]])</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(delta_region, <span class="at">share_of_prior_range =</span> delta_span_notif), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                          share_of_prior_range 
                 0.1                  2.0                  1.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(delta_span_notif <span class="sc">&gt;</span> <span class="fl">0.7</span>)   <span class="co"># the text says the region is a long ridge in delta</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Hình sau vẽ ba bản đồ profile cạnh nhau để so vùng tin cậy giữa ba tập mục tiêu; vùng trong đường trắng càng nhỏ thì mục tiêu càng nhiều thông tin.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>fig_surface <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(surf, <span class="fu">aes</span>(beta, delta)) <span class="sc">+</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="fu">aes</span>(<span class="at">fill =</span> d_ll_clip)) <span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_contour</span>(<span class="fu">aes</span>(<span class="at">z =</span> d_ll), <span class="at">breaks =</span> cut_95, <span class="at">colour =</span> <span class="st">"white"</span>, <span class="at">linewidth =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"point"</span>, <span class="at">x =</span> th_true[[<span class="st">"beta"</span>]], <span class="at">y =</span> th_true[[<span class="st">"delta"</span>]], <span class="at">shape =</span> <span class="dv">4</span>, <span class="at">size =</span> <span class="dv">3</span>,</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">stroke =</span> <span class="fl">1.2</span>, <span class="at">colour =</span> pal_course[<span class="dv">2</span>]) <span class="sc">+</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>targets) <span class="sc">+</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"grey95"</span>, <span class="at">high =</span> pal_course[<span class="dv">1</span>], <span class="at">name =</span> <span class="st">"Log-likelihood</span><span class="sc">\n</span><span class="st">(so với cực đại)"</span>) <span class="sc">+</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"beta (hệ số lây truyền, /năm)"</span>, <span class="at">y =</span> <span class="st">"delta (tỷ suất phát hiện, /năm)"</span>,</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Hàm hợp lý profile: số ca báo cáo tạo một sống núi dài, điều tra hiện mắc cắt ngang nó"</span>) <span class="sc">+</span></span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>)</span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_surface, <span class="st">"l01-gof-surface.png"</span>, <span class="at">width =</span> <span class="dv">9</span>, <span class="at">height =</span> <span class="fl">3.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l01-gof-surface.png" class="img-fluid figure-img"></p>
<figcaption>Hàm hợp lý profile theo <span class="math inline">\((\beta, \delta)\)</span> với ba tập mục tiêu. Đường trắng: vùng tin cậy 95% xấp xỉ. Dấu x: giá trị thật.</figcaption>
</figure>
</div>
<p>Lưới có 43,407 bộ tham số. Chỉ với số ca báo cáo, vùng tin cậy chiếm 7.5% lưới <span class="math inline">\((\beta, \delta)\)</span> nhưng trải từ <span class="math inline">\(\delta\)</span> = 0.10 đến 2.00, tức 100% khoảng tiên nghiệm của <span class="math inline">\(\delta\)</span>. Thêm điều tra hiện mắc thu nhỏ vùng này còn 0.4%. Lấy một bộ trên sống núi nhưng có <span class="math inline">\(\delta\)</span> lớn:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Two parameter sets that fit the notifications equally well but disagree on prevalence</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>ll_notif_grid <span class="ot">&lt;-</span> <span class="fu">loglik_targets</span>(sim_grid, targets, <span class="at">types =</span> <span class="st">"notif"</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>on_ridge <span class="ot">&lt;-</span> <span class="fu">which</span>(ll_notif_grid <span class="sc">&gt;</span> <span class="fu">max</span>(ll_notif_grid) <span class="sc">-</span> <span class="dv">1</span> <span class="sc">&amp;</span> grid<span class="sc">$</span>delta <span class="sc">&gt;</span> <span class="fl">1.2</span>)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>alt <span class="ot">&lt;-</span> <span class="fu">unlist</span>(grid[on_ridge[<span class="fu">which.max</span>(ll_notif_grid[on_ridge])], CALIB_NAMES])</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>sim_alt <span class="ot">&lt;-</span> <span class="fu">run_tb_model</span>(alt, p)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>ridge_tab <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">true_values =</span> <span class="fu">c</span>(th_true, <span class="at">notif_2017 =</span> sim_true<span class="sc">$</span>notif[<span class="dv">1</span>, <span class="st">"2017"</span>][[<span class="dv">1</span>]],</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">prev_2017 =</span> sim_true<span class="sc">$</span>prev[<span class="dv">1</span>, <span class="st">"2017"</span>][[<span class="dv">1</span>]],</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ll_notif =</span> <span class="fu">loglik_targets</span>(sim_true, targets, <span class="st">"notif"</span>),</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ll_total =</span> <span class="fu">loglik_targets</span>(sim_true, targets)),</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">ridge_set =</span> <span class="fu">c</span>(alt, <span class="at">notif_2017 =</span> sim_alt<span class="sc">$</span>notif[<span class="dv">1</span>, <span class="st">"2017"</span>][[<span class="dv">1</span>]],</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">prev_2017 =</span> sim_alt<span class="sc">$</span>prev[<span class="dv">1</span>, <span class="st">"2017"</span>][[<span class="dv">1</span>]],</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>                <span class="at">ll_notif =</span> <span class="fu">loglik_targets</span>(sim_alt, targets, <span class="st">"notif"</span>),</span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>                <span class="at">ll_total =</span> <span class="fu">loglik_targets</span>(sim_alt, targets))</span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(ridge_tab, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            beta delta k_beta notif_2017 prev_2017 ll_notif ll_total
true_values  6.7  0.45   0.02    107.910   239.799  -43.648  -47.296
ridge_set   14.5  2.00   0.03    108.367    54.184  -43.068 -104.249</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>prev_ratio <span class="ot">&lt;-</span> sim_true<span class="sc">$</span>prev[<span class="dv">1</span>, <span class="st">"2017"</span>][[<span class="dv">1</span>]] <span class="sc">/</span> sim_alt<span class="sc">$</span>prev[<span class="dv">1</span>, <span class="st">"2017"</span>][[<span class="dv">1</span>]]</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The text says the ridge set fits the notifications as well as the true values (within 2 log-likelihood units)</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(prev_ratio <span class="sc">&gt;</span> <span class="fl">1.5</span>, <span class="fu">abs</span>(ridge_tab[<span class="st">"ridge_set"</span>, <span class="st">"ll_notif"</span>] <span class="sc">-</span> ridge_tab[<span class="st">"true_values"</span>, <span class="st">"ll_notif"</span>]) <span class="sc">&lt;</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Bộ này khớp số ca báo cáo tương đương giá trị thật (log-likelihood -43.1 so với -43.6), nhưng tỷ lệ hiện mắc năm 2017 thấp hơn 4.4 lần. Hình dưới đặt hai quỹ đạo cạnh các mục tiêu để thấy chỉ điều tra mới phân biệt được chúng.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>yrs <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">colnames</span>(sim_true<span class="sc">$</span>notif))</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>traj <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">year =</span> yrs, <span class="at">value =</span> sim_true<span class="sc">$</span>notif[<span class="dv">1</span>, ], <span class="at">set =</span> <span class="st">"Giá trị thật"</span>, <span class="at">what =</span> <span class="st">"Số ca báo cáo /100,000"</span>),</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">year =</span> yrs, <span class="at">value =</span> sim_alt<span class="sc">$</span>notif[<span class="dv">1</span>, ], <span class="at">set =</span> <span class="st">"Bộ trên sống núi"</span>, <span class="at">what =</span> <span class="st">"Số ca báo cáo /100,000"</span>),</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">year =</span> yrs, <span class="at">value =</span> sim_true<span class="sc">$</span>prev[<span class="dv">1</span>, ], <span class="at">set =</span> <span class="st">"Giá trị thật"</span>, <span class="at">what =</span> <span class="st">"Tỷ lệ hiện mắc /100,000"</span>),</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">year =</span> yrs, <span class="at">value =</span> sim_alt<span class="sc">$</span>prev[<span class="dv">1</span>, ], <span class="at">set =</span> <span class="st">"Bộ trên sống núi"</span>, <span class="at">what =</span> <span class="st">"Tỷ lệ hiện mắc /100,000"</span>)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>obs <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">year =</span> targets<span class="sc">$</span>year, <span class="at">value =</span> targets<span class="sc">$</span>value, <span class="at">sd =</span> targets<span class="sc">$</span>sd,</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">what =</span> <span class="fu">ifelse</span>(targets<span class="sc">$</span>type <span class="sc">==</span> <span class="st">"notif"</span>, <span class="st">"Số ca báo cáo /100,000"</span>, <span class="st">"Tỷ lệ hiện mắc /100,000"</span>),</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">use =</span> <span class="fu">ifelse</span>(targets<span class="sc">$</span>use <span class="sc">==</span> <span class="st">"calibration"</span>, <span class="st">"Dùng để hiệu chuẩn"</span>, <span class="st">"Giữ lại để thẩm định"</span>))</span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>fig_ridge <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(traj[traj<span class="sc">$</span>year <span class="sc">&lt;=</span> <span class="dv">2024</span>, ], <span class="fu">aes</span>(year, value)) <span class="sc">+</span></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">colour =</span> set), <span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="at">data =</span> obs, <span class="fu">aes</span>(<span class="at">ymin =</span> value <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> sd, <span class="at">ymax =</span> value <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> sd, <span class="at">shape =</span> use),</span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>                  <span class="at">size =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>what, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> pal_course[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)], <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb56-17"><a href="#cb56-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_shape_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">1</span>), <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb56-18"><a href="#cb56-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_limits</span>(<span class="at">y =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb56-19"><a href="#cb56-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Năm"</span>, <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb56-20"><a href="#cb56-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Mục tiêu MÔ PHỎNG và hai bộ tham số khớp số ca báo cáo như nhau"</span>) <span class="sc">+</span></span>
<span id="cb56-21"><a href="#cb56-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb56-22"><a href="#cb56-22" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_ridge, <span class="st">"l01-ridge.png"</span>, <span class="at">width =</span> <span class="dv">9</span>, <span class="at">height =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l01-ridge.png" class="img-fluid figure-img"></p>
<figcaption>Hai bộ tham số khớp số ca báo cáo như nhau nhưng khác hẳn về tỷ lệ hiện mắc. Thanh dọc: khoảng 95% của mục tiêu mô phỏng.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Mẹo thực hành">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mẹo thực hành
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Trước khi dùng số liệu thật, chạy phép thử phục hồi tham số như bài này. Một phép thử đầy đủ lặp lại trên nhiều bộ dữ liệu mô phỏng và kiểm tra tỷ lệ khoảng tin cậy chứa giá trị thật; bài này chỉ chạy một bộ nên không chứng minh được độ bao phủ.</li>
<li>Lưu mỗi mục tiêu thành một hàng, kèm năm, định nghĩa, sai số và vai trò, như bảng <code>targets</code> và <code>targets_vn</code>; nó sẽ thành phụ lục báo cáo.</li>
<li>Viết mô hình để chạy nhiều bộ tham số cùng lúc (mỗi bộ một hàng) và luôn dùng log-likelihood: tích của nhiều xác suất nhỏ sẽ tràn về 0.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Lỗi thường gặp">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lỗi thường gặp
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Coi điều tra phức hợp như mẫu ngẫu nhiên đơn.</strong> Mục tiêu trở nên “chắc chắn” quá mức và lấn át các mục tiêu khác. Dùng cỡ mẫu hiệu dụng.</li>
<li><strong>Đầu ra và mục tiêu không cùng định nghĩa.</strong> Điều tra thật đo lao phổi có bằng chứng vi khuẩn ở người từ 15 tuổi; ngăn I ở đây gồm mọi lứa tuổi và mọi thể lao chưa phát hiện. Phép quy đổi trong bài chỉ là gần đúng.</li>
<li><strong>Dùng ước tính của mô hình khác làm mục tiêu.</strong> Tỷ lệ mới mắc của WHO đã là đầu ra của một mô hình; đưa nó vào hàm hợp lý là đếm hai lần các giả định.</li>
<li><strong>Trọng số tùy tiện.</strong> Không chia sai số cho độ lệch chuẩn thì mục tiêu có số lớn nhất quyết định kết quả.</li>
<li><strong>Hiệu chuẩn một mô hình chưa kiểm chứng.</strong> Bước thời gian quá dài làm lệch mọi tồn kho và thời gian cư trú; hiệu chuẩn sẽ “bù” sai lệch đó vào các tham số.</li>
</ul>
</div>
</div>
</section>
<section id="bài-tập" class="level2">
<h2 class="anchored" data-anchor-id="bài-tập">Bài tập</h2>
<p><strong>Bài 1 (dễ).</strong> Nhân hệ số lây truyền với 0.5. Mục tiêu nào bị ảnh hưởng nhiều hơn: số ca báo cáo hay điều tra?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 1: reduce the transmission rate. Which target suffers most?</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>th_ex <span class="ot">&lt;-</span> th_true</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>th_ex[<span class="st">"beta"</span>] <span class="ot">&lt;-</span> th_true[[<span class="st">"beta"</span>]] <span class="sc">*</span> ex1_beta_factor</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>sim_ex <span class="ot">&lt;-</span> <span class="fu">run_tb_model</span>(th_ex, p)</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">ll_notif =</span> <span class="fu">loglik_targets</span>(sim_ex, targets, <span class="st">"notif"</span>),</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">ll_prev =</span> <span class="fu">loglik_targets</span>(sim_ex, targets, <span class="st">"prev"</span>),</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">prev_2017 =</span> sim_ex<span class="sc">$</span>prev[<span class="dv">1</span>, <span class="st">"2017"</span>][[<span class="dv">1</span>]]), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> ll_notif   ll_prev prev_2017 
  -1550.5     -46.9      70.2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">loglik_targets</span>(sim_true, targets, <span class="st">"notif"</span>) <span class="sc">-</span> <span class="fu">loglik_targets</span>(sim_ex, targets, <span class="st">"notif"</span>) <span class="sc">&gt;</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">loglik_targets</span>(sim_true, targets, <span class="st">"prev"</span>) <span class="sc">-</span> <span class="fu">loglik_targets</span>(sim_ex, targets, <span class="st">"prev"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Log-likelihood của số ca báo cáo giảm mạnh hơn nhiều so với của điều tra, vì 15 mục tiêu số ca có sai số nhỏ, còn một điều tra chỉ có 25,933 người hiệu dụng. Tỷ lệ hiện mắc năm 2017 theo mô hình chỉ còn 70 trên 100,000.</p>
</div>
</div>
</div>
<p><strong>Bài 2 (trung bình).</strong> Rút 500 bộ tham số ngẫu nhiên trong khoảng tiên nghiệm. Kiểm tra rằng −2 × log-likelihood và WSSE xếp hạng các bộ gần như giống hệt nhau (tương quan hạng Spearman), rồi lặp lại chỉ với 5% bộ tốt nhất.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 2: -2 x log-likelihood and weighted SSE rank parameter sets almost identically</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11</span>)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>X_ex <span class="ot">&lt;-</span> <span class="fu">random_sample</span>(ex2_n_draws, bounds<span class="sc">$</span>lower, bounds<span class="sc">$</span>upper)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>sim_ex2 <span class="ot">&lt;-</span> <span class="fu">run_tb_model</span>(X_ex, p)</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>ll_ex2 <span class="ot">&lt;-</span> <span class="fu">loglik_targets</span>(sim_ex2, targets)</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>wsse_ex2 <span class="ot">&lt;-</span> <span class="fu">wsse_targets</span>(sim_ex2, targets)</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>rank_cor <span class="ot">&lt;-</span> <span class="fu">cor</span>(<span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> ll_ex2, wsse_ex2, <span class="at">method =</span> <span class="st">"spearman"</span>)</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a><span class="co"># The same, among the best-fitting draws only (the part that matters for calibration)</span></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>top <span class="ot">&lt;-</span> ll_ex2 <span class="sc">&gt;=</span> <span class="fu">quantile</span>(ll_ex2, <span class="dv">1</span> <span class="sc">-</span> ex2_top_share)</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>rank_cor_top <span class="ot">&lt;-</span> <span class="fu">cor</span>(<span class="sc">-</span><span class="dv">2</span> <span class="sc">*</span> ll_ex2[top], wsse_ex2[top], <span class="at">method =</span> <span class="st">"spearman"</span>)</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">all_draws =</span> rank_cor, <span class="at">best_draws =</span> rank_cor_top), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> all_draws best_draws 
     0.999      0.655 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(rank_cor <span class="sc">&gt;</span> <span class="fl">0.9</span>, rank_cor_top <span class="sc">&lt;</span> rank_cor)   <span class="co"># the text says agreement is weaker among the best draws</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Tương quan hạng là 0.999 trên toàn bộ các bộ, nhưng chỉ còn 0.655 trong nhóm tốt nhất. Hai thước đo chỉ khác nhau ở phần điều tra (nhị thức so với xấp xỉ chuẩn), và sự khác biệt đó nổi lên khi các bộ đã khớp gần nhau. Kiểm tra phần còn lại ở Bài 2: hai thước đo cho cùng một điểm tối ưu.</p>
</div>
</div>
</div>
<p><strong>Bài 3 (khó hơn).</strong> Giả sử sai số báo cáo lớn hơn nhiều: hệ số biến thiên 20% thay vì 5%. Vùng tin cậy khi dùng cả hai loại mục tiêu thay đổi thế nào? Giải thích.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 3: notifications with a much larger reporting error</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>targets_noisy <span class="ot">&lt;-</span> targets</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>is_notif <span class="ot">&lt;-</span> targets_noisy<span class="sc">$</span>type <span class="sc">==</span> <span class="st">"notif"</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>targets_noisy<span class="sc">$</span>sd[is_notif] <span class="ot">&lt;-</span> ex3_cv_noisy <span class="sc">*</span> targets_noisy<span class="sc">$</span>value[is_notif]</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>share_cv5 <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">profile_ll</span>(<span class="fu">loglik_targets</span>(sim_grid, targets)) <span class="sc">&gt;</span> cut_95)</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>share_cv20 <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">profile_ll</span>(<span class="fu">loglik_targets</span>(sim_grid, targets_noisy)) <span class="sc">&gt;</span> cut_95)</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">share_cv5 =</span> share_cv5, <span class="at">share_cv20 =</span> share_cv20), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> share_cv5 share_cv20 
     0.004      0.029 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(share_cv20 <span class="sc">&gt;</span> share_cv5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Vùng tin cậy rộng ra từ 0.4% lên 2.9% lưới. Số ca báo cáo kém chính xác thì chứa ít thông tin hơn về <span class="math inline">\(\beta\)</span> và <span class="math inline">\(k_\beta\)</span>; điều tra vẫn giữ <span class="math inline">\(\delta\)</span> khỏi trôi dọc sống núi, nhưng mọi tham số đều kém chắc chắn hơn.</p>
</div>
</div>
</div>
</section>
<section id="tài-liệu-tham-khảo" class="level2">
<h2 class="anchored" data-anchor-id="tài-liệu-tham-khảo">Tài liệu tham khảo</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-alarid2018nonidentifiability" class="csl-entry" role="listitem">
Alarid-Escudero, Fernando, Richard F. MacLehose, Yadira Peralta, Karen M. Kuntz, và Eva A. Enns. 2018. <span>“Nonidentifiability in model calibration and implications for medical decision making”</span>. <em>Medical Decision Making</em> 38 (7): 810–21. <a href="https://doi.org/10.1177/0272989X18792283">https://doi.org/10.1177/0272989X18792283</a>.
</div>
<div id="ref-andrews2012risk" class="csl-entry" role="listitem">
Andrews, Jason R., Farzad Noubary, Rochelle P. Walensky, Rodrigo Cerda, Elena Losina, và C. Robert Horsburgh. 2012. <span>“Risk of progression to active tuberculosis following reinfection with <span>Mycobacterium tuberculosis</span>”</span>. <em>Clinical Infectious Diseases</em> 54 (6): 784–91. <a href="https://doi.org/10.1093/cid/cir951">https://doi.org/10.1093/cid/cir951</a>.
</div>
<div id="ref-bui2025impact" class="csl-entry" role="listitem">
Bui, Viet Long, Romain Ragonnet, Angus E. Hughes, David S. Shipman, Emma S. McBryde, Binh Hoa Nguyen, Hoang Nam Do, Thai Son Ha, Greg J. Fox, và James M. Trauer. 2025. <span>“Impact of case detection and <span>COVID-19</span>-related disruptions on tuberculosis in <span>Vietnam</span>: a modeling analysis”</span>. <em>The Journal of Infectious Diseases</em> 232 (4): e682–90. <a href="https://doi.org/10.1093/infdis/jiaf406">https://doi.org/10.1093/infdis/jiaf406</a>.
</div>
<div id="ref-chinhphu2025nd293" class="csl-entry" role="listitem">
Chính phủ. 2025. <span>“Nghị định 293/2025/<span>NĐ-CP</span> quy định mức lương tối thiểu đối với người lao động làm việc theo hợp đồng lao động (hiệu lực từ 1/1/2026)”</span>. 2025. <a href="https://hatinh.gov.vn/vi/bai-viet/tang-luong-toi-thieu-vung-tu-112026">https://hatinh.gov.vn/vi/bai-viet/tang-luong-toi-thieu-vung-tu-112026</a>.
</div>
<div id="ref-enns2015identifying" class="csl-entry" role="listitem">
Enns, Eva A., Lauren E. Cipriano, Cyrena T. Simons, và Chung Yin Kong. 2015. <span>“Identifying best-fitting inputs in health-economic model calibration: a <span>Pareto</span> frontier approach”</span>. <em>Medical Decision Making</em> 35 (2): 170–82. <a href="https://doi.org/10.1177/0272989X14528382">https://doi.org/10.1177/0272989X14528382</a>.
</div>
<div id="ref-horton2022population" class="csl-entry" role="listitem">
Horton, Katherine C., Richard G. White, Nguyen Binh Hoa, Hai Viet Nguyen, Roel Bakker, Tom Sumner, Elizabeth L. Corbett, và Rein M. G. J. Houben. 2022. <span>“Population benefits of addressing programmatic and social determinants of gender disparities in tuberculosis in <span>Viet Nam</span>: a modelling study”</span>. <em>PLOS Global Public Health</em> 2 (7): e0000784. <a href="https://doi.org/10.1371/journal.pgph.0000784">https://doi.org/10.1371/journal.pgph.0000784</a>.
</div>
<div id="ref-menzies2018progression" class="csl-entry" role="listitem">
Menzies, Nicolas A., Emory Wolf, David Connors, Meghan Bellerose, Alyssa N. Sbarra, Ted Cohen, Andrew N. Hill, và c.s. 2018. <span>“Progression from latent infection to active disease in dynamic tuberculosis transmission models: a systematic review of the validity of modelling assumptions”</span>. <em>The Lancet Infectious Diseases</em> 18 (8): e228–38. <a href="https://doi.org/10.1016/S1473-3099(18)30134-8">https://doi.org/10.1016/S1473-3099(18)30134-8</a>.
</div>
<div id="ref-nguyen2020second" class="csl-entry" role="listitem">
Nguyen, Hai Viet, Edine W. Tiemersma, Hoa Binh Nguyen, Frank G. J. Cobelens, Alyssa Finlay, Philippe Glaziou, Cu Huy Dao, và c.s. 2020. <span>“The second national tuberculosis prevalence survey in <span>Vietnam</span>”</span>. <em>PLoS ONE</em> 15 (4): e0232142. <a href="https://doi.org/10.1371/journal.pone.0232142">https://doi.org/10.1371/journal.pone.0232142</a>.
</div>
<div id="ref-ragonnet2017optimally" class="csl-entry" role="listitem">
Ragonnet, Romain, James M. Trauer, Nick Scott, Michael T. Meehan, Justin T. Denholm, và Emma S. McBryde. 2017. <span>“Optimally capturing latency dynamics in models of tuberculosis transmission”</span>. <em>Epidemics</em> 21: 39–47. <a href="https://doi.org/10.1016/j.epidem.2017.06.002">https://doi.org/10.1016/j.epidem.2017.06.002</a>.
</div>
<div id="ref-schwalb2025potential" class="csl-entry" role="listitem">
Schwalb, Alvaro, Katherine C. Horton, Jon C. Emery, Martin J. Harker, Lara Goscé, Lara D. Veeken, Frances L. Garden, và c.s. 2025. <span>“Potential impact, costs, and benefits of population-wide screening interventions for tuberculosis in <span>Viet Nam</span>: a mathematical modelling study”</span>. <em>PLOS Global Public Health</em> 5 (9): e0005050. <a href="https://doi.org/10.1371/journal.pgph.0005050">https://doi.org/10.1371/journal.pgph.0005050</a>.
</div>
<div id="ref-stout2009calibration" class="csl-entry" role="listitem">
Stout, Natasha K., Amy B. Knudsen, Chung Yin Kong, Pamela M. McMahon, và G. Scott Gazelle. 2009. <span>“Calibration methods used in cancer simulation models and suggested reporting guidelines”</span>. <em>PharmacoEconomics</em> 27 (7): 533–45. <a href="https://doi.org/10.2165/11314830-000000000-00000">https://doi.org/10.2165/11314830-000000000-00000</a>.
</div>
<div id="ref-tiemersma2011natural" class="csl-entry" role="listitem">
Tiemersma, Edine W., Marieke J. van der Werf, Martien W. Borgdorff, Brian G. Williams, và Nico J. D. Nagelkerke. 2011. <span>“Natural history of tuberculosis: duration and fatality of untreated pulmonary tuberculosis in <span>HIV</span> negative patients: a systematic review”</span>. <em>PLoS ONE</em> 6 (4): e17601. <a href="https://doi.org/10.1371/journal.pone.0017601">https://doi.org/10.1371/journal.pone.0017601</a>.
</div>
<div id="ref-vanni2011calibrating" class="csl-entry" role="listitem">
Vanni, Tazio, Jonathan Karnon, Jason Madan, Richard G. White, W. John Edmunds, Anna M. Foss, và Rosa Legood. 2011. <span>“Calibrating models in economic evaluation: a seven-step approach”</span>. <em>PharmacoEconomics</em> 29 (1): 35–49. <a href="https://doi.org/10.2165/11584600-000000000-00000">https://doi.org/10.2165/11584600-000000000-00000</a>.
</div>
<div id="ref-vynnycky1997natural" class="csl-entry" role="listitem">
Vynnycky, E., và P. E. Fine. 1997. <span>“The natural history of tuberculosis: the implications of age-dependent risks of disease and the role of reinfection”</span>. <em>Epidemiology and Infection</em> 119 (2): 183–201. <a href="https://doi.org/10.1017/s0950268897007917">https://doi.org/10.1017/s0950268897007917</a>.
</div>
<div id="ref-worldbank2026wdipop0014" class="csl-entry" role="listitem">
World Bank. 2026a. <span>“Population ages 0–14 (% of total population), <span>Viet Nam</span> (indicator <span>SP.POP.0014.TO.ZS</span>), World Development Indicators”</span>. 2026. <a href="https://api.worldbank.org/v2/country/VNM/indicator/SP.POP.0014.TO.ZS?format=json&amp;date=2015:2024&amp;per_page=50">https://api.worldbank.org/v2/country/VNM/indicator/SP.POP.0014.TO.ZS?format=json&amp;date=2015:2024&amp;per_page=50</a>.
</div>
<div id="ref-worldbank2026wdipop" class="csl-entry" role="listitem">
———. 2026b. <span>“Population, total, <span>Viet Nam</span> (indicator <span>SP.POP.TOTL</span>), World Development Indicators”</span>. 2026. <a href="https://api.worldbank.org/v2/country/VNM/indicator/SP.POP.TOTL?format=json&amp;date=2000:2025&amp;per_page=100">https://api.worldbank.org/v2/country/VNM/indicator/SP.POP.TOTL?format=json&amp;date=2000:2025&amp;per_page=100</a>.
</div>
<div id="ref-who2026lifetables" class="csl-entry" role="listitem">
World Health Organization. 2026a. <span>“Global Health Observatory: life tables by country, <span>Viet Nam</span>, 2023 (indicators <span>LIFE_0000000029</span> nMx, <span>LIFE_0000000030</span> nqx, <span>LIFE_0000000035</span> ex)”</span>. 2026. <a href="https://ghoapi.azureedge.net/api/LIFE_0000000029">https://ghoapi.azureedge.net/api/LIFE_0000000029</a>.
</div>
<div id="ref-who2026ghotb" class="csl-entry" role="listitem">
———. 2026b. <span>“Global Health Observatory: tuberculosis indicators for <span>Viet Nam</span>, 2000–2024 (<span>TB_c_newinc</span>, <span>MDG_0000000020</span>, <span>TB_e_inc_num</span>, <span>MDG_0000000017</span>, <span>TB_Notification_agesex_num</span>)”</span>. 2026. <a href="https://ghoapi.azureedge.net/api/TB_c_newinc">https://ghoapi.azureedge.net/api/TB_c_newinc</a>.
</div>
</div>
<div class="video-script">
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kịch bản video (~13 phút)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Slide</th>
<th>Lời giảng chính</th>
<th>Hình/Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Người bệnh không có tên trong sổ</td>
<td>106,392 ca báo cáo so với 184,000 ca ước tính năm 2024; β, δ không đo được</td>
<td>callout đầu bài</td>
</tr>
<tr class="even">
<td>2</td>
<td>Hiệu chuẩn, xác minh, thẩm định</td>
<td>ước lượng / code đúng / phản ánh thực tế</td>
<td>bảng so sánh</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Bảy quyết định</td>
<td>tham số, mục tiêu, GOF, tìm kiếm, chấp nhận, dừng, tích hợp</td>
<td>Vanni 2011</td>
</tr>
<tr class="even">
<td>4</td>
<td>Mô hình lao 6 ngăn</td>
<td>λ(t) = β(t)·I; hệ ODE; RK4 vector hóa; tử vong nền từ bảng sống</td>
<td>chunk <code>l01-run</code></td>
</tr>
<tr class="odd">
<td>5</td>
<td>Kiểm chứng trước khi hiệu chuẩn</td>
<td>bước thời gian, deSolve, bảo toàn; chênh lệch tối đa 0.0022%</td>
<td>chunk <code>l01-verify</code></td>
</tr>
<tr class="even">
<td>6</td>
<td>Mục tiêu mô phỏng và thật</td>
<td>biết đáp án → phép thử phục hồi; số liệu WHO và điều tra 2017–2018 bên cạnh</td>
<td><code>figs/l01-real-vn.png</code></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Điều tra phức hợp</td>
<td>deff ≈ 2.38 (cụm + gia quyền + bù trừ); n hiệu dụng 25,933; quy về mọi lứa tuổi</td>
<td>công thức deff</td>
</tr>
<tr class="even">
<td>8</td>
<td>Hàm hợp lý và WSSE</td>
<td>nhị thức + chuẩn; −2ℓ = WSSE + hằng số</td>
<td>chunk <code>l01-gof</code></td>
</tr>
<tr class="odd">
<td>9</td>
<td>Sống núi</td>
<td>số ca ≈ δ × I; điều tra cắt ngang</td>
<td><code>figs/l01-gof-surface.png</code></td>
</tr>
<tr class="even">
<td>10</td>
<td>Hai bộ tham số, một số ca</td>
<td>hiện mắc chênh 4.4 lần</td>
<td><code>figs/l01-ridge.png</code></td>
</tr>
<tr class="odd">
<td>11</td>
<td>Lỗi thường gặp</td>
<td>điều tra phức hợp; sai định nghĩa; dùng ước tính WHO làm mục tiêu; trọng số tùy ý</td>
<td>callout</td>
</tr>
<tr class="even">
<td>12</td>
<td>Chuyển tiếp</td>
<td>tìm bộ tốt nhất thế nào khi không vẽ được lưới? → Bài 2</td>
<td>—</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../kb/m08-calibration/index.html" class="pagination-link" aria-label="M08 · Hiệu chuẩn mô hình (calibration)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">M08 · Hiệu chuẩn mô hình (calibration)</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../kb/m08-calibration/l02-search-methods.html" class="pagination-link" aria-label="Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead">
        <span class="nav-page-text"><span class="chapter-title">Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>