---
title: "Ethics Right vs Wrong"
date: 2021-09-10
categories: ["Random thoughts"]
tags: ["mind wandering", "Random thoughts"]
lang-post: EN/VI
---


::: {.lang-vi}
> *Assume you’re in command of a train hurtling down the tracks with no brakes. A group of five workers toil unknowingly ahead. You frantically sound the horn, but their obliviousness persists. Panic sets in when you notice a single person on a side road. A difficult decision must be made: should you steer the train, causing the death of one in order to save the other five? Is such an act morally acceptable? (**The trolley problem**).*

The solution to this moral quandary lies *within *each individual, shaped by their personal perspectives as well as the larger societal context. Every ethical philosophy has its own point of view.

Do you put the greater good ahead of the few, or do you advocate for the protection of the vulnerable?

Do ethical principles remain immutable, or can they flex in response to changing circumstances?

Is one inclined to seek legal and governmental protection, or does one prefer a laissez-faire approach in which interactions are governed by voluntary agreements?

The abundance of ethical paradigms blurs identity lines.

Consider Robin Hood: a hero who steals from the wealthy to help the poor.

Should a terminally ill person be encouraged to donate an organ in order to potentially save many lives? Can a society that allows people to buy military service exemptions be considered just?

Myriad ethical quandaries defy clear-cut, black-and-white solutions in the realm of ethical reflection. What matters, in my opinion, is encouraging openness to differing points of view and respecting the tapestry of differences. Rather than attempting to convert others, we must recognize that divergence, like us, has its place.

This article is based on insights gained while taking Prof Michael Sandel’s “Justice” course.

---

# **Về đạo đức và kết luận đúng – sai **

> Bạn đang cầm lái một đoàn tàu hỏng phanh, phía trước đường ray là một nhóm năm công nhân đang làm việc, bạn bấm còi inh ỏi nhưng họ không để ý. Đang hốt hoảng không biết làm sao thì bạn thấy một đường ray phụ, trên đó chỉ có một người thôi. Liệu bạn có bẻ lái, (cố ý) sát hại một người để cứu năm người? Liệu đó có phải là việc làm phù hợp đạo đức? (The trooley dilemma).

Câu trả lời nằm ở mỗi cá nhân và hệ quy chiếu mà họ theo đuổi, cũng như bối cảnh chung của xã hội.

Mỗi trường phái đạo đức lại có một quan điểm riêng.

Bạn là người tôn trọng lợi ích đa số hơn thiểu số, hay bạn bảo vệ người yếu thế?

Bạn tự đặt ra cho mình những quy chuẩn đạo đức mà tuyệt đối không được phá bỏ, hay là người linh hoạt tuỳ theo hoàn cảnh?

Bạn thích sự bảo vệ của luật pháp và chính quyền, hay thích mọi việc tự do – chỉ thương lượng người với người là ổn thoả?

Có rất nhiều trường phái mà dường như chính mình cũng không biết mình là ai.

Liệu Robin Hood cướp của người giàu chia cho người nghèo có phải một việc làm phải đạo? Liệu có nên thuyết phục một người đang phút lâm chung hiến tạng để cứu nhiều người khác? Liệu một xã hội cho phép mọi người trả tiền để được miễn/giảm nghĩa vụ quân sự có phải là một xã hội bất công?

Còn rất nhiều vấn đề đạo đức nan giải mà chúng ta khó có thể đưa ra câu trả lời là trắng hay là đen.

Điều quan trọng trong cuộc tranh luận này theo mình là sự cởi mở với quan điểm trái chiều cũng như tôn trọng sự khác biệt. Cũng đừng cố gắng thay đổi quan điểm của đối phương làm gì. Không được đâu.

Bài viết dựa vào kinh nghiệm và kiến thức mình nhặt được từ khoá học Justice của Michael Sandels.
:::

::: {.lang-en}
*(English version coming soon.)*
:::

