---
title: "Most effective COVID-19 vaccines"
date: 2021-08-26
tags: ["COVID-19", "vaccine", "volunteer"]
lang-post: EN/VI
---


::: {.lang-vi}
In the United States, the initial two COVID-19 vaccines available hail from Pfizer/BioNTech and Moderna, both with ~95% efficacy. Johnson & Johnson's third vaccine exhibited 66% effectiveness. However, comparing these numbers directly doesn't provide the correct lens.

Check out this video from my team at Y Hoc Cong Dong: amidst high demand and vaccine scarcity, **the optimal choice is to administer the available vaccine as soon as feasible**. Link: [click here](https://www.facebook.com/yhoccongdong/posts/pfbid0318C2nkDaZHv313KhHz3xVJ1xSLKWBPKSxJjbCCiGNMp8yNH5o8iiybQ7ksH1C8Xul).

---

Tại Hoa Kỳ, hai loại vắc xin COVID-19 đầu tiên là Pfizer/BioNTech và Moderna có hiệu lực khoảng 95%. Loại thứ ba của Johnson & Johnson chỉ có 66%.

Tuy nhiên, đó không phải là cách đúng đắn để so sánh hiệu quả của vắc xin. Trong thời điểm cao điểm dịch, **vắc xin tốt nhất chính là vắc xin được tiêm sớm nhất**.
:::

::: {.lang-en}
*(English version coming soon.)*
:::

