---
title: "COVID-19 vaccine pregnancy"
date: 2022-02-15
tags: ["COVID-19", "maternal health", "pregnancy", "vaccine"]
lang-post: EN/VI
---

Original article: Goldshtein I, Steinberg DM, Kuint J, et al. [Association of BNT162b2 COVID-19 Vaccination During Pregnancy With Neonatal and Early Infant Outcomes.](https://jamanetwork.com/journals/jamapediatrics/fullarticle/2788938) *JAMA Pediatr.* 2022;176(5):470-477.

This is without a doubt one of the most common concerns among pregnant women. On February 10th, a comprehensive research published in JAMA found no association between getting the Pfizer COVID-19 vaccine during pregnancy and unfavorable outcomes for the infant. These findings are based on a population analysis of 24,288 singleton births in Israel.

Among 24,288 singleton births, 16,697 cases had mothers who received the COVID-19 immunization during pregnancy. There were no evident changes in risk between the two groups in terms of observed adverse events.

A significant drawback: the authors assessed relationships using data from vaccine exposure in the second and third trimesters, as first trimester data were not robust. However, the first trimester is universally recognized as a key period of rapid growth and development.

---

**Mẹ tiêm vaccine COVID-19 khi đang mang thai liệu có liên hệ với bất lợi nào cho con?**

Một nghiên cứu lớn được công bố trên JAMA cho thấy không có bất kỳ mối liên hệ nào giữa việc tiêm vắc xin Pfizer trong giai đoạn thai kỳ với biến cố bất lợi cho con. Kết quả này được rút ra từ nghiên cứu quần thể trên 24.288 ca sinh đơn tại Israel.

Trong 24.288 ca sinh đơn, có 16.697 trường hợp có mẹ đã tiêm vắc xin COVID-19. Không có bất kỳ khác biệt nào về nguy cơ giữa hai nhóm. Tử vong sơ sinh nhìn chung thấp.

Một nhược điểm lớn nằm ở việc khảo sát các dị tật sau sinh: dữ liệu ở tam cá nguyệt thứ nhất không đủ mạnh. Đây có thể là một hướng khảo sát tiềm năng cho những nghiên cứu về sau.
