---
title: "Giãn cách xã hội điện tử giấc ngủ"
date: 2023-06-27
tags: ["COVID-19", "quality of life", "social distancing"]
lang-post: VI
---

*Bài viết đã được đăng tải trên báo [Sức khoẻ và Đời sống](https://suckhoedoisong.vn/gian-cach-xa-hoi-do-covid-19-tang-su-dung-man-hinh-dien-tu-se-lam-giam-chat-luong-giac-ngu-169197321.htm) (Bộ Y tế), ngày 15/07/2021.*

Nghiên cứu gần đây của các nhà khoa học Ý cho thấy, sự gia tăng thời gian sử dụng màn hình điện tử trong khi giãn cách xã hội do COVID-19 có thể giảm chất lượng giấc ngủ.

## Mối liên hệ giữa giấc ngủ và sức khỏe

Giấc ngủ có tác động rất nhiều đến sức khoẻ. Ngủ đủ giấc giúp mọi người cảm thấy khỏe mạnh. Ngủ không đủ giấc hoặc chất lượng giấc ngủ kém có thể dẫn đến nhiều vấn đề sức khỏe thể chất, như tăng huyết áp, đái tháo đường type 2, bệnh tim, đột quỵ, bệnh thận và béo phì.

## Sử dụng thiết bị điện tử tăng mạnh trong thời gian giãn cách xã hội

Một nghiên cứu được thực hiện bằng cách sử dụng dữ liệu từ Ý, đã kiểm tra mức độ tiếp xúc màn hình điện tử tăng lên trong thời gian cách ly xã hội do COVID-19 ảnh hưởng đến chất lượng giấc ngủ như thế nào. Nghiên cứu này khảo sát 2.123 người tham gia.

Kết quả cho thấy, có sự suy giảm chất lượng giấc ngủ đối với những người tăng thời gian tiếp xúc với màn hình trong 2 giờ trước khi đi ngủ. Ngược lại, chất lượng giấc ngủ được cải thiện ở những người giảm thời gian sử dụng thiết bị.

## Rối loạn giấc ngủ do lạm dụng thiết bị điện tử

Việc sử dụng màn hình điện tử trước khi đi ngủ có thể tác động tiêu cực đến chất lượng giấc ngủ. Nguyên nhân là do màn hình phát ra ánh sáng xanh có thể gia tăng sự tỉnh táo; các hoạt động hấp dẫn như nhắn tin hoặc chơi game giúp tăng kích thích não bộ.

Chu kỳ ngủ và thức hàng ngày được kiểm soát bởi nhân trên chéo (SCN). Ánh sáng phát ra từ các thiết bị điện tử là tín hiệu làm SCN bị nhầm lẫn, từ đó làm rối loạn điều hoà giấc ngủ.
