---
title: "Gỡ rối COVID-19 quản lý thông tin"
date: 2023-06-27
tags: ["COVID-19", "management", "Productivity"]
lang-post: VI
---


::: {.lang-vi}
*Bài viết đã được đăng tải trên báo [Người Đô Thị](https://nguoidothi.net.vn/go-roi-covid-19-ngay-tu-khau-quan-ly-thong-tin-mot-cach-day-du-co-he-thong-31749.html), ngày 15/10/2021.*

Một công việc đều trở nên khó khăn khi nó nằm ngoài tầm kiểm soát. Để quá trình chống dịch được dễ dàng, thống nhất và hiệu quả, việc phải có một hệ thống quản lý dữ liệu dễ theo dõi, dễ tìm kiếm và dễ hiểu là một điều cấp bách.

Chúng tôi đề xuất Bộ Y tế và các cơ quan phòng, chống dịch hợp tác thiết kế một website hoàn chỉnh, thống nhất với một bảng thông tin (Dashboard) rõ ràng, dễ theo dõi, dễ hiểu và dễ truy xuất. Mục lục có thể tham khảo từ CDC Hoa Kỳ, Anh, Australia.

Một hệ quản lý dữ liệu tốt, được số hoá giúp giảm tải cho khâu quản lý, truy xuất và thực hiện đi rất nhiều.

Biết đồng sức, biết đồng lòng, việc gì khó, cũng làm xong.

**BS. Nguyễn Khởi Quân** (VinUniversity), **Nguyễn Thị Hiền Hậu** (ĐH Duy Tân), **PGS-TS-BS. Nguyễn Tiến Huy** (ĐH Nagasaki)
:::

::: {.lang-en}
*(English version coming soon.)*
:::

