---
title: "COVID-19 vĩ độ Hà Nội"
date: 2023-06-27
tags: ["COVID-19", "global health", "public health", "weather"]
lang-post: VI
---

*Bài viết đã được đăng tải trên báo Soha và [CafeBiz](https://cafebiz.vn), ngày 21/09/2020.*

Từ giữa làn sóng Covid-19 đầu tiên, các nhà nghiên cứu đã lo lắng một đợt bùng phát mới và nặng hơn sẽ diễn ra ở các nước xứ lạnh vào mùa đông năm 2019.

## Có sự lây lan theo mùa

Thực tế các virus đường hô hấp nói chung có sự lây lan theo mùa. Các nghiên cứu dựa trên chủng SARS-CoV đầu tiên cho thấy thời tiết có thể có ảnh hưởng quan trọng đối với sự lây lan của coronavirus. Ở Hồng Kông, khi thời tiết dưới 24,6 độ C, số ca mới tăng hơn 18 lần.

## Thời tiết khô hơn, virus sẽ khỏe hơn

Một kết quả được đăng tải trên Annual Reviews chỉ ra độ ẩm lý tưởng cho đường hô hấp khỏe mạnh là từ 40%-60%. Để so sánh, độ ẩm không khí trung bình tại Việt Nam thường xuyên vượt ngưỡng 80%.

## Nắng và tia UV

Một nghiên cứu ở Tây Ban Nha theo dõi trong quá trình cách ly xã hội chỉ ra: thời gian chiếu sáng trong ngày càng dài thì càng có nhiều ca nhiễm COVID-19. Phát hiện này đối lập với những hiểu biết với virus cúm thông thường.

## Vị trí địa lý

Hầu như tất cả những thành phố xuất hiện đại dịch đều nằm trong khoảng từ 30-50 độ vĩ Bắc (với khí hậu ôn đới, nhiệt độ trung bình chỉ từ 5-11 độ C).

## Những tranh luận không ngừng nghỉ

Các nhà nghiên cứu từ Đại học Oxford đã thực hiện tổng phân tích và đưa ra kết luận rằng những con số được đưa ra qua các nghiên cứu có quá nhiều giới hạn và thật sự không đáng tin cậy để đưa ra bất kỳ kết luận nào.
