<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bài 2: Tỷ suất, xác suất và độ dài chu kỳ – Mô hình Kinh tế Y tế với R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../kb/m02-cohort-markov/l03-cohort-trace.html" rel="next">
<link href="../../kb/m02-cohort-markov/l01-state-transition.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9e7f0c659d5fa2cace8548cb57964278.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c18d72663580ed8ca19ce2a2f99af51b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=JetBrains+Mono:wght@400;600&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m02-cohort-markov/index.html">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</a></li><li class="breadcrumb-item"><a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Mô hình Kinh tế Y tế với R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lời mở đầu</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m00-r-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M00 · R cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l02-vectors-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l03-functions-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hàm, cấu trúc điều khiển, vòng lặp và vectơ hóa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l04-data-frames.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Data frame — nhập, làm sạch, tóm tắt và chuyển dạng dữ liệu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l05-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Biểu đồ với ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l06-randomness-monte-carlo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 6: Ngẫu nhiên, mô phỏng Monte Carlo và sai số Monte Carlo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m01-ee-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M01 · Nền tảng đánh giá kinh tế và cây quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l01-evaluation-types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại đánh giá kinh tế, quan điểm, khung thời gian và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l02-health-outcomes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Năm sống, QALY và DALY</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l03-decision-rules.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l04-thresholds.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l05-decision-tree.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Xây cây quyết định từ đầu trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m02-cohort-markov/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l01-state-transition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao cần mô hình chuyển trạng thái</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l03-cohort-trace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l04-time-dependence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Phụ thuộc thời gian: lão hóa, trạng thái đường hầm và mảng 3 chiều</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l05-results-verification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị gắn với lần chuyển, đường biên hiệu quả và xác minh mô hình</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m03-uncertainty-voi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l01-deterministic-sa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại bất định và phân tích độ nhạy tất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l02-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Chọn phân phối cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l03-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích độ nhạy xác suất (PSA) trong R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l05-voi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m04-microsimulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M04 · Mô phỏng vi mô (microsimulation)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l01-why-microsimulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l02-microsim-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l03-vectorisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vectơ hóa theo cá thể và đo hiệu năng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l04-parallel-rcpp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tính toán song song và Rcpp cho vòng lặp nóng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l05-mc-error-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bao nhiêu cá thể là đủ? Sai số Monte Carlo, PSA và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m05-dynamic-transmission/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M05 · Mô hình lây truyền động</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l01-static-vs-dynamic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Mô hình tĩnh và mô hình lây truyền động</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l02-sir-seir-desolve.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình SIR và SEIR trong R với deSolve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l03-vaccination-herd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Tiêm chủng, hiệu quả trực tiếp và gián tiếp</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l04-dengue-host-vector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Mô hình vật chủ–véc tơ cho sốt xuất huyết Dengue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l05-dynamic-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế với mô hình lây truyền động</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m06-amr-economics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M06 · Kinh tế học kháng kháng sinh (AMR)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l01-amr-burden.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l02-attributable-los.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l03-ward-transmission.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Mô hình lây truyền CRE trong khoa hồi sức</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l04-two-strain-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m07-survival-psm/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M07 · Phân tích sống còn cho mô hình quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l01-survival-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ôn tập phân tích sống còn cho người làm mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l02-parametric-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình sống còn tham số với flexsurv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l03-extrapolation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Ngoại suy sống còn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l04-reconstruct-ipd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tái tạo dữ liệu cá thể từ đường KM đã công bố và dùng HR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l05-partitioned-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Mô hình sống còn phân vùng trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m08-calibration/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M08 · Hiệu chuẩn mô hình (calibration)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l01-why-calibrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l02-search-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l03-bayes-sir.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hiệu chuẩn Bayes và thuật toán SIR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l04-psa-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đưa kết quả hiệu chuẩn vào PSA, thẩm định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m09-inputs-vietnam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l01-costing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ước tính chi phí cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l05-decision-context.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bối cảnh ra quyết định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m10-policy-bia-equity/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m11-software-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l01-code-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Cấu trúc mã cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l02-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Xác minh và kiểm thử mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l03-version-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quản lý phiên bản với Git và tái lập môi trường với renv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l04-r-package.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đóng gói mô hình thành gói R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l05-shiny-living.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Ứng dụng Shiny và mô hình “sống”</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bảng thuật ngữ Anh–Việt</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Trong bài</h2>
   
  <ul class="collapse">
  <li><a href="#mục-tiêu-học-tập" id="toc-mục-tiêu-học-tập" class="nav-link active" data-scroll-target="#mục-tiêu-học-tập">Mục tiêu học tập</a></li>
  <li><a href="#ý-chính" id="toc-ý-chính" class="nav-link" data-scroll-target="#ý-chính">Ý chính</a></li>
  <li><a href="#nội-dung" id="toc-nội-dung" class="nav-link" data-scroll-target="#nội-dung">Nội dung</a></li>
  <li><a href="#thực-hành" id="toc-thực-hành" class="nav-link" data-scroll-target="#thực-hành">Thực hành</a></li>
  <li><a href="#bài-tập" id="toc-bài-tập" class="nav-link" data-scroll-target="#bài-tập">Bài tập</a></li>
  <li><a href="#tài-liệu-tham-khảo" id="toc-tài-liệu-tham-khảo" class="nav-link" data-scroll-target="#tài-liệu-tham-khảo">Tài liệu tham khảo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m02-cohort-markov/index.html">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</a></li><li class="breadcrumb-item"><a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></h1>
<p class="subtitle lead">Biến số liệu công bố thành xác suất chuyển hằng tháng một cách đúng đắn</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled" title="Vì sao bạn nên quan tâm?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vì sao bạn nên quan tâm?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Mở báo cáo của một Chương trình Chống lao tỉnh, bạn gặp bốn loại con số trộn lẫn: tỷ lệ thành công của phác đồ ngắn (76.2%), tỷ số chênh của phác đồ dài hạn (1.56), kết cục bất lợi của BPaLM trong thử nghiệm (12% so với 41%) và tỷ suất tử vong của người bỏ điều trị (lost to follow-up) (5.2/100 người-năm). Mỗi loại đi vào ma trận chuyển theo một đường riêng, và đi nhầm đường cũng giống đổi đô la theo giá bán của ngân hàng (26,377 VNĐ) thay vì tỷ giá chính thức (24,970 VNĐ) <span class="citation" data-cites="sbv2026interbank gso2026gdp2025">(<a href="../m00-r-foundations/index.html#ref-sbv2026interbank" role="doc-biblioref">State Bank of Vietnam 2026</a>; <a href="../m00-r-foundations/index.html#ref-gso2026gdp2025" role="doc-biblioref">Cục Thống kê (Bộ Tài chính) 2026a</a>)</span>: con số vẫn trông hợp lý nhưng lệch 5.6%. Chẳng hạn, nhân thẳng tỷ số chênh vào tỷ lệ bất lợi sẽ cho phác đồ dài hạn 37.1% bất lợi thay vì 32.8%. Bài này giúp bạn chọn đúng đường cho từng con số, trước khi chúng quyết định phác đồ nào được chọn.</p>
</div>
</div>
<section id="mục-tiêu-học-tập" class="level2">
<h2 class="anchored" data-anchor-id="mục-tiêu-học-tập">Mục tiêu học tập</h2>
<p>Sau bài này, bạn có thể:</p>
<ol type="1">
<li>Phân biệt tỷ suất (rate) và xác suất (probability), và chuyển đổi đúng giữa chúng.</li>
<li>Áp đúng tỷ số chênh (OR), nguy cơ tương đối (RR) và tỷ số nguy cơ tức thời (hazard ratio, HR) lên nguy cơ nền.</li>
<li>Tách các nguy cơ cạnh tranh (competing risks) thành xác suất chuyển trong một chu kỳ.</li>
<li>Lấy tử vong nền theo tuổi từ bảng sống (life table) và áp dụng tỷ số tử vong chuẩn hóa (SMR) đúng chỗ.</li>
<li>Chọn độ dài chu kỳ hợp lý cho một bài toán cụ thể.</li>
</ol>
</section>
<section id="ý-chính" class="level2">
<h2 class="anchored" data-anchor-id="ý-chính">Ý chính</h2>
<ul>
<li>Tỷ suất là số biến cố trên người-thời gian (từ 0 đến vô cùng). Xác suất là tỷ lệ một nhóm gặp biến cố trong một khoảng thời gian nêu rõ (từ 0 đến 1).</li>
<li>Với tỷ suất không đổi <span class="math inline">\(r\)</span>: <span class="math inline">\(p = 1 - e^{-rt}\)</span> và <span class="math inline">\(r = -\ln(1-p)/t\)</span>. Không bao giờ chia xác suất cho 12.</li>
<li>Khi một trạng thái có nhiều lối ra, cộng các tỷ suất rồi chia xác suất tổng theo tỷ lệ: <span class="math inline">\(p_k = \tfrac{r_k}{R}(1-e^{-Rt})\)</span>.</li>
<li>HR và SMR nhân vào <strong>tỷ suất</strong>; RR nhân vào <strong>xác suất</strong> đo trên cùng khoảng thời gian; OR nhân vào <strong>odds</strong>.</li>
<li>Tỷ lệ kết cục cuối điều trị đổi thành nguy cơ tức thời (hazard) hằng tháng, rồi kiểm tra ngược.</li>
<li>Ghép hiệu quả tương đối của thử nghiệm với nguy cơ nền địa phương thì phải nêu mọi chỗ hai nguồn không khớp.</li>
<li>Khi hai nguồn dữ liệu mâu thuẫn (tử vong sau bỏ điều trị), mâu thuẫn đó là một phát hiện, không phải chuyện giấu đi.</li>
</ul>
</section>
<section id="nội-dung" class="level2">
<h2 class="anchored" data-anchor-id="nội-dung">Nội dung</h2>
<section id="tỷ-suất-và-xác-suất" class="level3">
<h3 class="anchored" data-anchor-id="tỷ-suất-và-xác-suất">Tỷ suất và xác suất</h3>
<p>Tỷ suất đo tốc độ xảy ra biến cố: số biến cố chia cho tổng người-thời gian. Xác suất là tỷ lệ những người ban đầu gặp biến cố trong một khoảng thời gian xác định. Nếu tỷ suất không đổi trong khoảng đó:</p>
<p><span class="math display">\[
p(t) = 1 - e^{-rt}, \qquad r = -\frac{\ln(1-p)}{t}.
\]</span></p>
<p>Khi <span class="math inline">\(rt\)</span> nhỏ, hai đại lượng gần bằng nhau; khi <span class="math inline">\(rt\)</span> lớn, chúng tách xa <span class="citation" data-cites="miller1994determining fleurence2007rates">(<a href="../m00-r-foundations/index.html#ref-miller1994determining" role="doc-biblioref">Miller và Homan 1994</a>; <a href="../m00-r-foundations/index.html#ref-fleurence2007rates" role="doc-biblioref">Fleurence và Hollenbeak 2007</a>)</span>. Tỷ suất có đợt lao tiếp theo trong một đoàn hệ MDR/RR-TB ở Việt Nam là 10.3/1000 người-năm <span class="citation" data-cites="maclean2026longterm">(<a href="../m00-r-foundations/index.html#ref-maclean2026longterm" role="doc-biblioref">MacLean và c.s. 2026</a>)</span>: xác suất trong một tháng là 0.086%, trong 5 năm là 5.02%, thấp hơn con số 5.15% có được khi nhân tỷ suất với 5. Muốn đổi xác suất năm sang xác suất tháng, đi qua tỷ suất: <span class="math inline">\(p_{\text{tháng}} = 1 - (1 - p_{\text{năm}})^{1/12}\)</span> (hàm <code>prob_rescale()</code>).</p>
</section>
<section id="nguy-cơ-cạnh-tranh" class="level3">
<h3 class="anchored" data-anchor-id="nguy-cơ-cạnh-tranh">Nguy cơ cạnh tranh</h3>
<p>Người ở trạng thái Thất bại có thể tử vong, tự khỏi hoặc bắt đầu điều trị lại; ai đã chết thì không thể khỏi. Với các tỷ suất <span class="math inline">\(r_1, \dots, r_m\)</span> có tổng <span class="math inline">\(R\)</span>:</p>
<p><span class="math display">\[
p_k = \frac{r_k}{R}\left(1 - e^{-Rt}\right), \qquad p_{\text{ở lại}} = e^{-Rt}.
\]</span></p>
<p>Đổi riêng từng tỷ suất thành xác suất rồi cộng lại sẽ đếm trùng <span class="citation" data-cites="gidwani2020estimating">(<a href="../m00-r-foundations/index.html#ref-gidwani2020estimating" role="doc-biblioref">Gidwani và Russell 2020</a>)</span>. Hàm <code>competing_probs()</code> cài công thức này và được dùng cho <strong>mọi</strong> hàng của ma trận chuyển. Ví dụ lao không điều trị: dữ liệu thời kỳ trước hóa trị liệu cho thấy lao phổi AFB dương kéo dài khoảng 3 năm đến khi tự khỏi hoặc tử vong, với tỷ lệ tử vong 10 năm khoảng 70% <span class="citation" data-cites="tiemersma2011natural">(<a href="../m00-r-foundations/index.html#ref-tiemersma2011natural" role="doc-biblioref">Tiemersma và c.s. 2011</a>)</span>. Coi tổng tỷ suất rời trạng thái là <span class="math inline">\(\lambda = 1/\text{thời gian mắc}\)</span>, ta có tỷ suất tử vong do lao <span class="math inline">\(\mu = CF \cdot \lambda =\)</span> 0.233/năm và tỷ suất tự khỏi <span class="math inline">\(\rho = (1-CF)\lambda =\)</span> 0.100/năm. Mô hình dùng hai tỷ suất này cho trạng thái Thất bại.</p>
</section>
<section id="kết-cục-của-ba-phác-đồ-tỷ-lệ-tỷ-số-chênh-nguy-cơ-tương-đối" class="level3">
<h3 class="anchored" data-anchor-id="kết-cục-của-ba-phác-đồ-tỷ-lệ-tỷ-số-chênh-nguy-cơ-tương-đối">Kết cục của ba phác đồ: tỷ lệ, tỷ số chênh, nguy cơ tương đối</h3>
<p>Ba phác đồ có ba loại bằng chứng <span class="citation" data-cites="nguyen2026from nyangwa2024short">(<a href="../m00-r-foundations/index.html#ref-nguyen2026from" role="doc-biblioref">Nguyen và c.s. 2026</a>; <a href="../m00-r-foundations/index.html#ref-nyangwa2024short" role="doc-biblioref">Nyang’wa và c.s. 2024</a>)</span>:</p>
<ul>
<li><strong>Phác đồ ngắn:</strong> tỷ lệ thành công 76.2%. Bài báo chỉ công bố tỷ lệ thành công theo phác đồ trong tóm tắt, nên phần bất lợi được chia theo cơ cấu của toàn đoàn hệ (thất bại, tử vong, bỏ điều trị, không đánh giá): một giả định.</li>
<li><strong>Phác đồ dài hạn:</strong> chỉ có tỷ số chênh đã điều chỉnh (aOR) 1.56 (KTC 95%: 1.32–1.84) so với phác đồ ngắn. OR nhân vào odds: <span class="math inline">\(\text{odds}_{\text{dài}} = \text{OR} \times p/(1-p)\)</span>, rồi <span class="math inline">\(p_{\text{dài}} = \text{odds}/(1+\text{odds})\)</span>. Dùng OR đã điều chỉnh như OR thô là một giả định.</li>
<li><strong>BPaLM:</strong> chưa có số liệu chương trình của Việt Nam. Ta lấy RR của kết cục bất lợi so với chăm sóc chuẩn trong TB-PRACTECAL, 0.117/0.409 = 0.29, rồi nhân vào tỷ lệ thất bại và bỏ điều trị <strong>gộp mọi phác đồ</strong> của Việt Nam. Lý do: nhóm chăm sóc chuẩn của thử nghiệm cũng là hỗn hợp phác đồ ngắn 9–11 tháng và phác đồ dài 18–20 tháng.</li>
</ul>
<p>Số liệu chương trình cho tỷ lệ cuối điều trị, không cho tỷ suất. Ta loại nhóm “không được đánh giá” khỏi mẫu số, rồi giả định nguy cơ không đổi trong <span class="math inline">\(D\)</span> tháng điều trị:</p>
<p><span class="math display">\[
H = -\frac{\ln(1-q)}{D}, \qquad h_k = H\,\frac{q_k}{q}, \qquad q = \sum_k q_k .
\]</span></p>
<p>Tỷ lệ tử vong quan sát đã chứa tử vong nền. <code>prepare_inputs()</code> trừ tỷ suất tử vong nền <strong>trung bình trong thời gian điều trị</strong>, nên tổng nguy cơ cả đợt, và do đó tỷ lệ hoàn thành, vẫn đúng khi đoàn hệ chuyển nhóm tuổi giữa chừng.</p>
<p>Ghép RR của thử nghiệm với nguy cơ nền địa phương là cách làm phổ biến, nhưng phải nói rõ bốn chỗ hai nguồn không khớp:</p>
<ol type="1">
<li><strong>Thời điểm đo.</strong> RR đo ở tuần 72 và tính cả tái phát; tỷ lệ chương trình đo ở cuối điều trị.</li>
<li><strong>Thành phần của kết cục bất lợi.</strong> Trong nhóm chăm sóc chuẩn, phần lớn kết cục bất lợi là ngừng điều trị sớm; theo đề cương (per-protocol), khác biệt chỉ còn 4% so với 7.2% <span class="citation" data-cites="nyangwa2024short">(<a href="../m00-r-foundations/index.html#ref-nyangwa2024short" role="doc-biblioref">Nyang’wa và c.s. 2024</a>)</span>. Ngừng điều trị trong thử nghiệm không hoàn toàn giống “thất bại” trong chương trình.</li>
<li><strong>Tử vong.</strong> Đến tuần 72 có 0% tử vong với BPaLM so với 3.6% với chăm sóc chuẩn, đa số liên quan điều trị; nhưng số ca rất nhỏ, và thử nghiệm loại người có men gan cao, QT kéo dài hoặc bệnh tim cấu trúc <span class="citation" data-cites="nyangwa2024short">(<a href="../m00-r-foundations/index.html#ref-nyangwa2024short" role="doc-biblioref">Nyang’wa và c.s. 2024</a>)</span>. Phân tích cơ sở vì vậy chỉ áp RR cho thất bại và bỏ điều trị, và cho BPaLM cùng nguy cơ tử vong do lao hằng tháng với phác đồ ngắn. Bài 5 so sánh với hai kịch bản: áp RR cho cả tử vong, và giữ nguyên tỷ lệ tử vong tích lũy của phác đồ ngắn.</li>
<li><strong>Tử vong bị báo cáo thiếu.</strong> Một đoàn hệ tiến cứu tại Việt Nam thấy 43% ca tử vong trong điều trị không được báo cáo cho Chương trình Chống lao <span class="citation" data-cites="maclean2026longterm">(<a href="../m00-r-foundations/index.html#ref-maclean2026longterm" role="doc-biblioref">MacLean và c.s. 2026</a>)</span> (kịch bản ở Bài 5).</li>
</ol>
</section>
<section id="sau-khi-ngừng-điều-trị-thất-bại-khác-bỏ-điều-trị" class="level3">
<h3 class="anchored" data-anchor-id="sau-khi-ngừng-điều-trị-thất-bại-khác-bỏ-điều-trị">Sau khi ngừng điều trị: Thất bại khác Bỏ điều trị</h3>
<p>Cách đơn giản nhất là cho cả người thất bại lẫn người bỏ điều trị theo diễn tiến của lao không điều trị (23.3 ca tử vong do lao/100 người-năm). Dữ liệu toàn quốc của Georgia mâu thuẫn với cách này: người bỏ điều trị lao kháng thuốc tử vong 5.2/100 người-năm do mọi nguyên nhân, và 63% đã âm hóa nuôi cấy trước khi bỏ <span class="citation" data-cites="adamashvili2022low">(<a href="../m00-r-foundations/index.html#ref-adamashvili2022low" role="doc-biblioref">Adamashvili và c.s. 2022</a>)</span>. Người bỏ điều trị thường đã uống thuốc nhiều tháng; họ không giống người mắc lao chưa từng điều trị. Mô hình vì thế dùng tử vong của Georgia cho trạng thái Bỏ điều trị, và giữ diễn tiến tự nhiên cho Thất bại. Cùng nghiên cứu cho biết 30% người bỏ điều trị đã quay lại điều trị trong thời gian theo dõi, tương ứng tỷ suất khoảng 0.079/năm. Với người thất bại, chưa có số công bố về thời gian chờ điều trị lại; mô hình dùng 4/năm, tức chờ trung bình 3 tháng (giá trị minh họa). Đây là số liệu nước khác và giai đoạn phác đồ có thuốc tiêm; Bài 5 thử lại với tử vong như lao không điều trị.</p>
</section>
<section id="bảng-sống-và-smr" class="level3">
<h3 class="anchored" data-anchor-id="bảng-sống-và-smr">Bảng sống và SMR</h3>
<p>Tử vong nền tăng mạnh theo tuổi. Mô hình dùng bảng sống Việt Nam năm 2023 của WHO, chung cho cả khóa học <span class="citation" data-cites="who2026lifetables">(<a href="../m00-r-foundations/index.html#ref-who2026lifetables" role="doc-biblioref">World Health Organization 2026</a>)</span>: một tỷ suất tử vong <span class="math inline">\(m_x\)</span> cho mỗi nhóm tuổi, không đổi trong nhóm. Tuổi thọ lúc sinh theo bảng này là 74.3 năm, gần con số 74.7 năm 2025 của Cục Thống kê <span class="citation" data-cites="gso2026population2025">(<a href="../m00-r-foundations/index.html#ref-gso2026population2025" role="doc-biblioref">Cục Thống kê (Bộ Tài chính) 2026b</a>)</span>.</p>
<p>Người đã điều trị lao có tử vong cao hơn người không mắc lao. Đoàn hệ Việt Nam cho SMR sau điều trị 3.0 so với <strong>người tiếp xúc trong hộ gia đình</strong>, không phải dân số chung <span class="citation" data-cites="maclean2026longterm">(<a href="../m00-r-foundations/index.html#ref-maclean2026longterm" role="doc-biblioref">MacLean và c.s. 2026</a>)</span>; áp nó lên bảng sống dân số chung là một giả định. Một tổng quan toàn cầu cho SMR gộp so với dân số chung 2.91 (KTC 95%: 2.21–3.84) <span class="citation" data-cites="romanowski2019longterm">(<a href="../m00-r-foundations/index.html#ref-romanowski2019longterm" role="doc-biblioref">Romanowski và c.s. 2019</a>)</span>. SMR nhân vào tỷ suất: <span class="math inline">\(p = 1 - \exp(-\text{SMR}\cdot m_x\, t)\)</span>.</p>
<p><strong>Một đường cho tử vong tăng thêm sau khi khỏi.</strong> SMR đo tử vong do mọi nguyên nhân, kể cả do lao tái phát. Vừa nhân SMR, vừa cho người đã khỏi tái phát rồi tử vong như lao không điều trị, là đếm tử vong do lao hai lần. Phân tích cơ sở chỉ dùng SMR (<code>relapse_years</code> = 0); Bài 5 so sánh với cách mô hình hóa tái phát tường minh, SMR bằng 1.</p>
</section>
<section id="chọn-độ-dài-chu-kỳ" class="level3">
<h3 class="anchored" data-anchor-id="chọn-độ-dài-chu-kỳ">Chọn độ dài chu kỳ</h3>
<p>Ba tiêu chí: các mốc thời gian quan trọng (6, 9 và 18 tháng) phải là bội số nguyên của chu kỳ; sai số do nhiều lần chuyển trạng thái trong một chu kỳ phải nhỏ; và mô hình vẫn chạy nhanh. Chu kỳ tháng thỏa cả ba.</p>
</section>
</section>
<section id="thực-hành" class="level2">
<h2 class="anchored" data-anchor-id="thực-hành">Thực hành</h2>
<p>Nạp hàm và tham số như mọi bài. Kiểm tra: không có lỗi.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vietnamese text in figures needs a UTF-8 locale (Rscript may start in the "C" locale)</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">isTRUE</span>(<span class="fu">l10n_info</span>()[[<span class="st">"UTF-8"</span>]])) <span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_CTYPE"</span>, <span class="st">"en_US.UTF-8"</span>))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/helpers.R"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/vn_data.R"</span>)    <span class="co"># course-wide values: threshold, life table, prices</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"code/model.R"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">m02_params</span>()                    <span class="co"># params/mdrtb.csv + shared values</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>inp <span class="ot">&lt;-</span> <span class="fu">prepare_inputs</span>(p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Đổi tỷ suất đợt lao tiếp theo thành xác suất tháng và 5 năm, rồi so sánh cách quy đổi đúng với cách chia cho 12. Kiểm tra: <code>stopifnot</code> xác nhận 12 chu kỳ tháng tái tạo đúng xác suất năm ban đầu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A rate (per person-year) becomes a monthly probability in two steps:</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># rescale the rate to the cycle (divide by 12), then p = 1 - exp(-r * t).</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>r_relapse_year <span class="ot">&lt;-</span> p<span class="sc">$</span>relapse_rate</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>p_relapse_month <span class="ot">&lt;-</span> <span class="fu">rate_to_prob</span>(r_relapse_year <span class="sc">/</span> <span class="dv">12</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>p_relapse_5y <span class="ot">&lt;-</span> <span class="fu">rate_to_prob</span>(r_relapse_year, <span class="at">t =</span> <span class="dv">5</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">rate_per_year =</span> r_relapse_year, <span class="at">prob_per_month =</span> p_relapse_month, <span class="at">prob_5_years =</span> p_relapse_5y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> rate_per_year prob_per_month   prob_5_years 
  0.0103000000   0.0008579651   0.0501963500 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rescaling a probability: go through the rate, never divide the probability</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>annual_p <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.20</span>, <span class="fl">0.50</span>, <span class="fl">0.80</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>rescale_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">annual_p =</span> annual_p,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">monthly_correct =</span> <span class="fu">prob_rescale</span>(annual_p, <span class="at">t_from =</span> <span class="dv">12</span>, <span class="at">t_to =</span> <span class="dv">1</span>),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">monthly_naive =</span> annual_p <span class="sc">/</span> <span class="dv">12</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Probability over 12 cycles implied by each monthly value</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>rescale_tab<span class="sc">$</span>annual_from_naive <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> rescale_tab<span class="sc">$</span>monthly_naive)<span class="sc">^</span><span class="dv">12</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(rescale_tab, <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  annual_p monthly_correct monthly_naive annual_from_naive
1     0.05          0.0043        0.0042            0.0489
2     0.20          0.0184        0.0167            0.1826
3     0.50          0.0561        0.0417            0.3999
4     0.80          0.1255        0.0667            0.5630</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(<span class="dv">1</span> <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> rescale_tab<span class="sc">$</span>monthly_correct)<span class="sc">^</span><span class="dv">12</span> <span class="sc">-</span> annual_p) <span class="sc">&lt;</span> <span class="fl">1e-12</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Với xác suất năm 80%, cách chia cho 12 chỉ tạo lại 56.3% sau 12 chu kỳ. Hình dưới vẽ sai lệch này trên cả dải xác suất. Kiểm tra: đường “đúng” là đường chéo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>grid_p <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.01</span>, <span class="fl">0.95</span>, <span class="at">by =</span> <span class="fl">0.01</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>rescale_curve <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">annual_p =</span> grid_p, <span class="at">implied =</span> grid_p, <span class="at">method =</span> <span class="st">"Đúng: qua tỷ suất"</span>),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">annual_p =</span> grid_p, <span class="at">implied =</span> <span class="dv">1</span> <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> grid_p <span class="sc">/</span> <span class="dv">12</span>)<span class="sc">^</span><span class="dv">12</span>, <span class="at">method =</span> <span class="st">"Sai: chia xác suất cho 12"</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>fig_rescale <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(rescale_curve, <span class="fu">aes</span>(annual_p, implied, <span class="at">colour =</span> method)) <span class="sc">+</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> pal_course[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)], <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Xác suất trong 1 năm (dữ liệu gốc)"</span>, <span class="at">y =</span> <span class="st">"Xác suất 1 năm do 12 chu kỳ tháng tạo ra"</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Chia xác suất cho 12 làm mất nguy cơ khi xác suất lớn"</span>) <span class="sc">+</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_rescale, <span class="st">"l02-rescale.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l02-rescale.png" class="img-fluid figure-img"></p>
<figcaption>Quy đổi xác suất năm sang tháng: đúng và sai</figcaption>
</figure>
</div>
<p>Tách tử vong và tự khỏi của lao không điều trị bằng công thức nguy cơ cạnh tranh, với chu kỳ 1 tháng và 1 năm, rồi so với cách đổi riêng từng nguy cơ. Kiểm tra: lặp ma trận một tháng của trạng thái Thất bại trong 100 năm (không có tử vong nền, không điều trị lại); tỷ lệ cuối cùng ở Tử vong phải bằng tỷ lệ tử vong đầu vào (<code>stopifnot</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Untreated TB: total exit rate = 1 / duration; death share = 10-year case fatality</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>exit_rate <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> p<span class="sc">$</span>dur_untreated</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>mu_tb <span class="ot">&lt;-</span> p<span class="sc">$</span>cf_untreated <span class="sc">*</span> exit_rate          <span class="co"># TB death rate, per year</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>rho <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> p<span class="sc">$</span>cf_untreated) <span class="sc">*</span> exit_rate      <span class="co"># self-cure rate, per year</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>comp_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">cycle =</span> <span class="fu">c</span>(<span class="st">"1 tháng"</span>, <span class="st">"12 tháng"</span>),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">t_years =</span> <span class="fu">c</span>(<span class="dv">1</span> <span class="sc">/</span> <span class="dv">12</span>, <span class="dv">1</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>comp_tab<span class="sc">$</span>p_death_competing <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>comp_tab<span class="sc">$</span>p_cure_competing <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>comp_tab<span class="sc">$</span>p_death_naive <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>comp_tab<span class="sc">$</span>p_cure_naive <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_len</span>(<span class="fu">nrow</span>(comp_tab))) {</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  pr <span class="ot">&lt;-</span> <span class="fu">competing_probs</span>(<span class="fu">c</span>(<span class="at">death =</span> mu_tb, <span class="at">cure =</span> rho), <span class="at">t =</span> comp_tab<span class="sc">$</span>t_years[i])</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  comp_tab<span class="sc">$</span>p_death_competing[i] <span class="ot">&lt;-</span> pr[[<span class="st">"death"</span>]]</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  comp_tab<span class="sc">$</span>p_cure_competing[i] <span class="ot">&lt;-</span> pr[[<span class="st">"cure"</span>]]</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  comp_tab<span class="sc">$</span>p_death_naive[i] <span class="ot">&lt;-</span> <span class="fu">rate_to_prob</span>(mu_tb, comp_tab<span class="sc">$</span>t_years[i])</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  comp_tab<span class="sc">$</span>p_cure_naive[i] <span class="ot">&lt;-</span> <span class="fu">rate_to_prob</span>(rho, comp_tab<span class="sc">$</span>t_years[i])</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>comp_tab<span class="sc">$</span>p_stay_competing <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> comp_tab<span class="sc">$</span>p_death_competing <span class="sc">-</span> comp_tab<span class="sc">$</span>p_cure_competing</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(comp_tab, <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     cycle t_years p_death_competing p_cure_competing p_death_naive
1  1 tháng  0.0833            0.0192          0.00822        0.0193
2 12 tháng  1.0000            0.1984          0.08504        0.2081
  p_cure_naive p_stay_competing
1       0.0083            0.973
2       0.0952            0.717</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check with a matrix, not with the formula: iterate the monthly Failed-state matrix</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (no background mortality; Cured treated as absorbing) for 100 years. The share that</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ends in Dead must equal the case fatality used as input.</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>s_f <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Failed"</span>, <span class="st">"Cured"</span>, <span class="st">"Dead"</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>P_f <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="at">dimnames =</span> <span class="fu">list</span>(s_f, s_f))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>pr <span class="ot">&lt;-</span> <span class="fu">competing_probs</span>(<span class="fu">c</span>(<span class="at">Cured =</span> rho <span class="sc">/</span> <span class="dv">12</span>, <span class="at">Dead =</span> mu_tb <span class="sc">/</span> <span class="dv">12</span>))</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>P_f[<span class="st">"Failed"</span>, <span class="fu">names</span>(pr)] <span class="ot">&lt;-</span> pr</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>P_f[<span class="st">"Failed"</span>, <span class="st">"Failed"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">sum</span>(pr)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>P_f[<span class="st">"Cured"</span>, <span class="st">"Cured"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>P_f[<span class="st">"Dead"</span>, <span class="st">"Dead"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>s_end <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">Failed =</span> <span class="dv">1</span>, <span class="at">Cured =</span> <span class="dv">0</span>, <span class="at">Dead =</span> <span class="dv">0</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (t <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1200</span>) s_end <span class="ot">&lt;-</span> s_end <span class="sc">%*%</span> P_f</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(s_end, <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Failed Cured Dead
[1,]      0   0.3  0.7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(s_end[<span class="dv">1</span>, <span class="st">"Dead"</span>] <span class="sc">-</span> p<span class="sc">$</span>cf_untreated) <span class="sc">&lt;</span> <span class="fl">1e-6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Với chu kỳ năm, cách đổi riêng cho tổng xác suất rời trạng thái 30.3%, cao hơn con số đúng 28.3%.</p>
<p>Đổi tỷ lệ thành công và tỷ số chênh thành tỷ lệ bất lợi của phác đồ dài hạn, qua odds. Kiểm tra: kết quả trùng hàm <code>success_from_or()</code> của mô hình (<code>stopifnot</code>), và cách nhân thẳng OR (cột <code>naive_unf_long</code>) cho số lớn hơn.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Short regimen: success 76.2%. Long regimen: only an adjusted odds ratio (aOR) of an</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># unfavourable outcome versus the short regimen is published. An OR acts on the ODDS:</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>unf_short <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> p<span class="sc">$</span>short_success</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>odds_short <span class="ot">&lt;-</span> unf_short <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> unf_short)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>odds_long <span class="ot">&lt;-</span> odds_short <span class="sc">*</span> p<span class="sc">$</span>aor_long_vs_bdqstr</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>unf_long <span class="ot">&lt;-</span> odds_long <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> odds_long)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">odds_short =</span> odds_short, <span class="at">odds_long =</span> odds_long, <span class="at">unf_short =</span> unf_short, <span class="at">unf_long =</span> unf_long,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">naive_unf_long =</span> p<span class="sc">$</span>aor_long_vs_bdqstr <span class="sc">*</span> unf_short), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    odds_short      odds_long      unf_short       unf_long naive_unf_long 
        0.3123         0.4872         0.2380         0.3276         0.3713 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>((<span class="dv">1</span> <span class="sc">-</span> unf_long) <span class="sc">-</span> <span class="fu">success_from_or</span>(p<span class="sc">$</span>short_success, p<span class="sc">$</span>aor_long_vs_bdqstr)) <span class="sc">&lt;</span> <span class="fl">1e-12</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Non-success is split like the national cohort, then "not evaluated" leaves the denominator</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">outcomes_from_success</span>(p<span class="sc">$</span>short_success, p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   failure      death       ltfu 
0.03070924 0.06653668 0.11345357 </code></pre>
</div>
</div>
<p>Đổi tỷ lệ kết cục cuối điều trị thành nguy cơ hằng tháng cho ba phác đồ. Kiểm tra: cột <code>q_reproduced</code> trùng cột <code>q_end_of_tx</code>, và nguy cơ tử vong do lao hằng tháng của BPaLM bằng của phác đồ ngắn trong phân tích cơ sở (có <code>stopifnot</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># From end-of-treatment proportions to constant monthly hazards (all three regimens)</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>hz_tab <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (g <span class="cf">in</span> REGIMENS) {</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  q_g <span class="ot">&lt;-</span> inp<span class="sc">$</span>q_unfav[[g]]</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  h_g <span class="ot">&lt;-</span> <span class="fu">derive_tx_hazards</span>(q_g, inp<span class="sc">$</span>duration[[g]])</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  H_g <span class="ot">&lt;-</span> <span class="fu">sum</span>(h_g)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  hz_tab <span class="ot">&lt;-</span> <span class="fu">rbind</span>(hz_tab, <span class="fu">data.frame</span>(</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">regimen =</span> g, <span class="at">outcome =</span> <span class="fu">names</span>(q_g), <span class="at">q_end_of_tx =</span> q_g, <span class="at">hazard_month =</span> h_g,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Check: the hazards reproduce the cumulative proportions over the treatment duration</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">q_reproduced =</span> h_g <span class="sc">/</span> H_g <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(<span class="sc">-</span>H_g <span class="sc">*</span> inp<span class="sc">$</span>duration[[g]]))</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(hz_tab, <span class="at">digits =</span> <span class="dv">3</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> regimen outcome q_end_of_tx hazard_month q_reproduced
    long failure      0.0429      0.00282       0.0429
    long   death      0.0928      0.00611       0.0928
    long    ltfu      0.1583      0.01041       0.1583
   short failure      0.0307      0.00383       0.0307
   short   death      0.0665      0.00830       0.0665
   short    ltfu      0.1135      0.01416       0.1135
   bpalm failure      0.0107      0.00188       0.0107
   bpalm   death      0.0473      0.00830       0.0473
   bpalm    ltfu      0.0397      0.00696       0.0397</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(hz_tab<span class="sc">$</span>q_reproduced <span class="sc">-</span> hz_tab<span class="sc">$</span>q_end_of_tx) <span class="sc">&lt;</span> <span class="fl">1e-12</span>))</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>q_short <span class="ot">&lt;-</span> inp<span class="sc">$</span>q_unfav<span class="sc">$</span>short</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>q_bpalm <span class="ot">&lt;-</span> inp<span class="sc">$</span>q_unfav<span class="sc">$</span>bpalm</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>h_short <span class="ot">&lt;-</span> <span class="fu">derive_tx_hazards</span>(q_short, p<span class="sc">$</span>dur_short)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>h_bpalm <span class="ot">&lt;-</span> <span class="fu">derive_tx_hazards</span>(q_bpalm, p<span class="sc">$</span>dur_bpalm)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Base case (bpalm_death_rule = 0): same monthly TB death hazard as the short regimen</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">short =</span> inp<span class="sc">$</span>h_tx<span class="sc">$</span>short[[<span class="st">"death"</span>]], <span class="at">bpalm =</span> inp<span class="sc">$</span>h_tx<span class="sc">$</span>bpalm[[<span class="st">"death"</span>]]), <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  short   bpalm 
0.00799 0.00799 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (p<span class="sc">$</span>bpalm_death_rule <span class="sc">==</span> <span class="dv">0</span>) <span class="fu">stopifnot</span>(<span class="fu">abs</span>(inp<span class="sc">$</span>h_tx<span class="sc">$</span>short[[<span class="st">"death"</span>]] <span class="sc">-</span> inp<span class="sc">$</span>h_tx<span class="sc">$</span>bpalm[[<span class="st">"death"</span>]]) <span class="sc">&lt;</span> <span class="fl">1e-12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Riêng tử vong, nguy cơ hằng tháng của hai phác đồ bằng nhau nhưng tỷ lệ tích lũy là 4.7% với BPaLM so với 6.7% với phác đồ ngắn: phần chênh chỉ đến từ 3 tháng chịu nguy cơ ít hơn. Nếu tử vong trong điều trị dồn vào vài tháng đầu, giả định nguy cơ không đổi sẽ thổi phồng lợi ích này.</p>
<p>Áp ba số đo hiệu quả cùng độ lớn lên cùng một xác suất nền (ví dụ dạy học, không phải tham số mô hình). Kiểm tra: ba kết quả khác nhau.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Applying a hazard ratio (HR), a risk ratio (RR) and an odds ratio (OR) of the same</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># size to the same baseline probability (teaching example, not model inputs)</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>p0 <span class="ot">&lt;-</span> <span class="fl">0.20</span>      <span class="co"># baseline probability over one year</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>ratio <span class="ot">&lt;-</span> <span class="fl">0.5</span>    <span class="co"># the effect measure</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>odds0 <span class="ot">&lt;-</span> p0 <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> p0)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>effect_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">measure =</span> <span class="fu">c</span>(<span class="st">"HR"</span>, <span class="st">"RR"</span>, <span class="st">"OR"</span>),</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">applied_to =</span> <span class="fu">c</span>(<span class="st">"rate"</span>, <span class="st">"probability (same horizon)"</span>, <span class="st">"odds"</span>),</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">p1 =</span> <span class="fu">c</span>(<span class="dv">1</span> <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> p0)<span class="sc">^</span>ratio,                          <span class="co"># = 1 - exp(-HR * r * t)</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>         <span class="fu">min</span>(<span class="dv">1</span>, ratio <span class="sc">*</span> p0),</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>         ratio <span class="sc">*</span> odds0 <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> ratio <span class="sc">*</span> odds0))</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>effect_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  measure                 applied_to        p1
1      HR                       rate 0.1055728
2      RR probability (same horizon) 0.1000000
3      OR                       odds 0.1111111</code></pre>
</div>
</div>
<p>Với xác suất nền 20% trong 1 năm và tỷ số 0.5: HR cho 10.6%, RR cho 10.0%, OR cho 11.1%. Ba số đo chỉ cho kết quả gần nhau khi xác suất nền nhỏ.</p>
<p>So sánh hai trạng thái sau khi ngừng điều trị: tỷ suất năm của từng lối ra, rồi số phận sau một năm khi các lối ra cạnh tranh nhau. Kiểm tra: mỗi hàng của bảng thứ hai cộng lại nhỏ hơn 1 (phần còn lại vẫn ở trạng thái cũ).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># After treatment stops: two states with different evidence (rates per year).</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Failed: pre-chemotherapy natural history (Tiemersma) + start of retreatment (illustrative).</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># LTFU: mortality observed after LTFU in Georgia, same self-cure rate, return to treatment.</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>mu_bg_year <span class="ot">&lt;-</span> <span class="fu">mx_lookup</span>(p<span class="sc">$</span>age_start, inp<span class="sc">$</span>lifetable)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>rates_year <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Failed =</span> <span class="fu">c</span>(<span class="at">death_tb =</span> p<span class="sc">$</span>cf_untreated <span class="sc">/</span> p<span class="sc">$</span>dur_untreated, <span class="at">self_cure =</span> (<span class="dv">1</span> <span class="sc">-</span> p<span class="sc">$</span>cf_untreated) <span class="sc">/</span> p<span class="sc">$</span>dur_untreated,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">retreatment =</span> p<span class="sc">$</span>retx_rate_failed),</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">LTFU =</span> <span class="fu">c</span>(<span class="at">death_tb =</span> <span class="fu">max</span>(p<span class="sc">$</span>ltfu_mort_rate <span class="sc">-</span> mu_bg_year, <span class="dv">0</span>), <span class="at">self_cure =</span> (<span class="dv">1</span> <span class="sc">-</span> p<span class="sc">$</span>cf_untreated) <span class="sc">/</span> p<span class="sc">$</span>dur_untreated,</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">retreatment =</span> p<span class="sc">$</span>retx_rate_ltfu)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(rates_year, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       death_tb self_cure retreatment
Failed    0.233       0.1       4.000
LTFU      0.048       0.1       0.079</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One-year fate (competing risks, background mortality at the starting age added to death)</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>fate_1y <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">apply</span>(rates_year, <span class="dv">1</span>, <span class="cf">function</span>(r) {</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">competing_probs</span>(<span class="fu">c</span>(<span class="at">death =</span> r[[<span class="st">"death_tb"</span>]] <span class="sc">+</span> mu_bg_year, <span class="at">cure =</span> r[[<span class="st">"self_cure"</span>]], <span class="at">retx =</span> r[[<span class="st">"retreatment"</span>]]))</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>}))</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(fate_1y, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       death  cure  retx
Failed 0.054 0.023 0.910
LTFU   0.046 0.089 0.071</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">rowSums</span>(fate_1y) <span class="sc">&lt;</span> <span class="dv">1</span>),</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>          fate_1y[<span class="st">"Failed"</span>, <span class="st">"retx"</span>] <span class="sc">&gt;</span> <span class="fl">0.5</span>,                                   <span class="co"># most failures are retreated</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>          fate_1y[<span class="st">"Failed"</span>, <span class="st">"death"</span>] <span class="sc">&lt;</span> <span class="fu">rate_to_prob</span>(rates_year[<span class="st">"Failed"</span>, <span class="st">"death_tb"</span>]))  <span class="co"># far below untreated TB</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Sau một năm, 91% người thất bại đã bắt đầu điều trị lại, còn ở nhóm bỏ điều trị chỉ có 7%; tỷ lệ tử vong trong năm là 5.4% và 4.6%. Người thất bại tử vong trong năm đầu ít hơn nhiều so với mức của lao không điều trị, không phải vì bệnh nhẹ, mà vì phần lớn đã được điều trị lại.</p>
<p>Lấy bảng sống Việt Nam từ <code>kb/_shared</code> và tính tuổi thọ còn lại ở tuổi bắt đầu trực tiếp từ bảng sống. Kiểm tra: <span class="math inline">\(m_x\)</span> tăng theo tuổi sau tuổi thơ (<code>stopifnot</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Viet Nam life table (WHO 2023, both sexes) from kb/_shared, via make_lifetable()</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>lt <span class="ot">&lt;-</span> inp<span class="sc">$</span>lifetable</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>lt<span class="sc">$</span>p_year <span class="ot">&lt;-</span> <span class="fu">rate_to_prob</span>(lt<span class="sc">$</span>mx)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>lt[lt<span class="sc">$</span>age_start <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">seq</span>(<span class="dv">40</span>, <span class="dv">85</span>, <span class="at">by =</span> <span class="dv">10</span>)), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   age_start          mx      p_year
1          0 0.012584942 0.012506083
10        40 0.002590167 0.002586815
12        50 0.005822342 0.005805425
14        60 0.013382636 0.013293487
16        70 0.034080811 0.033506602
18        80 0.094004627 0.089721450</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remaining life expectancy at the starting age, straight from the life table</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>ages <span class="ot">&lt;-</span> p<span class="sc">$</span>age_start <span class="sc">+</span> (<span class="fu">seq_len</span>(inp<span class="sc">$</span>n_cycles) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="dv">12</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>surv <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fu">exp</span>(<span class="sc">-</span><span class="fu">cumsum</span>(<span class="fu">mx_lookup</span>(ages, lt) <span class="sc">/</span> <span class="dv">12</span>)))</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>e_start <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">cycle_weights</span>(inp<span class="sc">$</span>n_cycles) <span class="sc">*</span> surv) <span class="sc">/</span> <span class="dv">12</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>e_start</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 32.69066</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">diff</span>(lt<span class="sc">$</span>mx[lt<span class="sc">$</span>age_start <span class="sc">&gt;=</span> <span class="dv">10</span>]) <span class="sc">&gt;</span> <span class="dv">0</span>))     <span class="co"># mortality rises with age after childhood</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>lt_plot <span class="ot">&lt;-</span> <span class="fu">rbind</span>(lt[, <span class="fu">c</span>(<span class="st">"age_start"</span>, <span class="st">"mx"</span>)], <span class="fu">data.frame</span>(<span class="at">age_start =</span> p<span class="sc">$</span>horizon_age, <span class="at">mx =</span> lt<span class="sc">$</span>mx[<span class="fu">nrow</span>(lt)]))</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>fig_lt <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(lt_plot, <span class="fu">aes</span>(age_start, mx)) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_step</span>(<span class="at">colour =</span> pal_course[<span class="dv">1</span>], <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tuổi"</span>, <span class="at">y =</span> <span class="st">"Tỷ suất tử vong năm (thang log)"</span>,</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Bảng sống Việt Nam (WHO 2023, hai giới), hằng số trong mỗi nhóm tuổi"</span>) <span class="sc">+</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_lt, <span class="st">"l02-lifetable.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l02-lifetable.png" class="img-fluid figure-img"></p>
<figcaption>Bảng sống Việt Nam (WHO 2023), hai giới</figcaption>
</figure>
</div>
<p>Một người 45 tuổi trong dân số chung còn sống trung bình 32.7 năm theo bảng sống này.</p>
<p>Áp dụng SMR đúng (vào tỷ suất) và sai (vào xác suất năm) ở tuổi bắt đầu và hai độ tuổi cao hơn. Kiểm tra: hai cách gần nhau ở tuổi trẻ, tách xa ở tuổi cao.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Post-TB excess mortality: multiply the RATE by the SMR, then convert</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>ages_smr <span class="ot">&lt;-</span> <span class="fu">c</span>(p<span class="sc">$</span>age_start, <span class="dv">70</span>, <span class="dv">95</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>mx_smr <span class="ot">&lt;-</span> <span class="fu">mx_lookup</span>(ages_smr, lt)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>smr_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> ages_smr,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_year_general =</span> <span class="fu">rate_to_prob</span>(mx_smr),</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_year_correct =</span> <span class="fu">rate_to_prob</span>(p<span class="sc">$</span>smr_post <span class="sc">*</span> mx_smr),</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_year_wrong =</span> p<span class="sc">$</span>smr_post <span class="sc">*</span> <span class="fu">rate_to_prob</span>(mx_smr)</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(smr_tab, <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  age p_year_general p_year_correct p_year_wrong
1  45         0.0038         0.0112       0.0113
2  70         0.0335         0.0972       0.1005
3  95         0.1943         0.4771       0.5830</code></pre>
</div>
</div>
<p>Ở tuổi 95, cách sai cho xác suất tử vong năm 58.3% thay vì 47.7%.</p>
<p>So sánh ba độ dài chu kỳ: số trạng thái đường hầm (tunnel state) cần cho mỗi phác đồ (Bài 4), và sai số của xác suất tử vong sau 1 năm khi bắt đầu ở Thất bại, so với bước ngày (gần như thời gian liên tục). Kiểm tra: số đường hầm phải là số nguyên.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># What each candidate cycle length implies for this model.</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Error from "more than one transition per cycle": one-year outcome of a person in</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Failed (states Failed, Cured, Dead; natural-history rates of the model at the starting</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># age; retreatment left out to keep the example small), using</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="co"># cycles of 1, 3 or 12 months, compared with daily steps (close to continuous time).</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>mu_bg <span class="ot">&lt;-</span> <span class="fu">mx_lookup</span>(p<span class="sc">$</span>age_start, lt) <span class="sc">/</span> <span class="dv">12</span>          <span class="co"># background death rate per month</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>post_block <span class="ot">&lt;-</span> <span class="cf">function</span>(cycle_months) {</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Failed"</span>, <span class="st">"Cured"</span>, <span class="st">"Dead"</span>)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  P <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="at">dimnames =</span> <span class="fu">list</span>(s, s))</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  pr <span class="ot">&lt;-</span> <span class="fu">competing_probs</span>(<span class="fu">c</span>(<span class="at">Cured =</span> inp<span class="sc">$</span>untreated[[<span class="st">"cure"</span>]], <span class="at">Dead =</span> mu_bg <span class="sc">+</span> inp<span class="sc">$</span>untreated[[<span class="st">"death"</span>]]),</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>                        <span class="at">t =</span> cycle_months)</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>  P[<span class="st">"Failed"</span>, <span class="fu">names</span>(pr)] <span class="ot">&lt;-</span> pr</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  P[<span class="st">"Failed"</span>, <span class="st">"Failed"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">sum</span>(pr)</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>  P[<span class="st">"Cured"</span>, <span class="st">"Dead"</span>] <span class="ot">&lt;-</span> <span class="fu">rate_to_prob</span>(p<span class="sc">$</span>smr_post <span class="sc">*</span> mu_bg, cycle_months)</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>  P[<span class="st">"Cured"</span>, <span class="st">"Cured"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> P[<span class="st">"Cured"</span>, <span class="st">"Dead"</span>]</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>  P[<span class="st">"Dead"</span>, <span class="st">"Dead"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>  P</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>one_year <span class="ot">&lt;-</span> <span class="cf">function</span>(cycle_months) {          <span class="co"># row "Failed" after 12 months</span></span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>  P <span class="ot">&lt;-</span> <span class="fu">post_block</span>(cycle_months)</span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">Failed =</span> <span class="dv">1</span>, <span class="at">Cured =</span> <span class="dv">0</span>, <span class="at">Dead =</span> <span class="dv">0</span>)</span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (k <span class="cf">in</span> <span class="fu">seq_len</span>(<span class="fu">round</span>(<span class="dv">12</span> <span class="sc">/</span> cycle_months))) s <span class="ot">&lt;-</span> s <span class="sc">%*%</span> P</span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>  s[<span class="dv">1</span>, ]</span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>ref_dead <span class="ot">&lt;-</span> <span class="fu">one_year</span>(<span class="dv">1</span> <span class="sc">/</span> <span class="dv">30</span>)[[<span class="st">"Dead"</span>]]</span>
<span id="cb36-26"><a href="#cb36-26" aria-hidden="true" tabindex="-1"></a>cycle_months <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">12</span>)</span>
<span id="cb36-27"><a href="#cb36-27" aria-hidden="true" tabindex="-1"></a>cl_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb36-28"><a href="#cb36-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">cycle_months =</span> cycle_months,</span>
<span id="cb36-29"><a href="#cb36-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">tunnels_bpalm =</span> p<span class="sc">$</span>dur_bpalm <span class="sc">/</span> cycle_months,</span>
<span id="cb36-30"><a href="#cb36-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">tunnels_long =</span> p<span class="sc">$</span>dur_long <span class="sc">/</span> cycle_months,</span>
<span id="cb36-31"><a href="#cb36-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_leave_failed =</span> <span class="fu">sapply</span>(cycle_months, <span class="cf">function</span>(k) <span class="dv">1</span> <span class="sc">-</span> <span class="fu">post_block</span>(k)[<span class="st">"Failed"</span>, <span class="st">"Failed"</span>]),</span>
<span id="cb36-32"><a href="#cb36-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">dead_1y =</span> <span class="fu">sapply</span>(cycle_months, <span class="cf">function</span>(k) <span class="fu">one_year</span>(k)[[<span class="st">"Dead"</span>]])</span>
<span id="cb36-33"><a href="#cb36-33" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-34"><a href="#cb36-34" aria-hidden="true" tabindex="-1"></a>cl_tab<span class="sc">$</span>error_dead_1y <span class="ot">&lt;-</span> cl_tab<span class="sc">$</span>dead_1y <span class="sc">-</span> ref_dead</span>
<span id="cb36-35"><a href="#cb36-35" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(cl_tab, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  cycle_months tunnels_bpalm tunnels_long p_leave_failed dead_1y error_dead_1y
1            1           6.0         18.0        0.02770 0.20174      -0.00004
2            3           2.0          6.0        0.08082 0.20165      -0.00012
3           12           0.5          1.5        0.28616 0.20127      -0.00050</code></pre>
</div>
</div>
<p>Chu kỳ 12 tháng không biểu diễn được phác đồ 6 tháng (0.5 đường hầm). Sai số do nhiều lần chuyển trong một chu kỳ lại nhỏ: 0.050% với chu kỳ năm, 0.004% với chu kỳ tháng. Ở mô hình này, điều loại chu kỳ năm là các mốc điều trị, không phải xác suất hai biến cố.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Mẹo thực hành">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mẹo thực hành
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Ghi đơn vị thời gian vào tên biến: <code>rate_year</code>, <code>p_month</code>. Phần lớn lỗi quy đổi là lỗi đơn vị.</li>
<li>Luôn kiểm tra ngược: đổi xác suất tháng thành xác suất năm phải ra lại số gốc.</li>
<li>Ghi rõ số liệu gốc là tỷ suất, xác suất tích lũy, tỷ lệ cuối kỳ hay tỷ số (OR, RR, HR): mỗi loại có cách chuyển riêng <span class="citation" data-cites="gidwani2020estimating">(<a href="../m00-r-foundations/index.html#ref-gidwani2020estimating" role="doc-biblioref">Gidwani và Russell 2020</a>)</span>.</li>
<li>Gom mọi phép biến đổi tham số vào một hàm (ở đây là <code>prepare_inputs()</code>), không rải rác trong code mô hình.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Lỗi thường gặp">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lỗi thường gặp
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Chia xác suất cho 12.</strong> Sai ít khi xác suất nhỏ, sai nhiều khi xác suất lớn. Dùng <code>prob_rescale()</code>.</li>
<li><strong>Nhân OR vào tỷ lệ.</strong> OR chỉ xấp xỉ RR khi biến cố hiếm; với tỷ lệ bất lợi khoảng 25% (cả nước, mọi phác đồ), cách này thổi phồng sai biệt.</li>
<li><strong>Nhân SMR hoặc HR vào xác suất.</strong> Chỉ nhân vào tỷ suất. Ngược lại, RR nhân vào xác suất nền đo trên cùng khoảng thời gian.</li>
<li><strong>Đếm tử vong hai lần.</strong> Tỷ lệ tử vong quan sát trong điều trị đã gồm tử vong nền; SMR sau điều trị đã gồm tử vong do lao tái phát.</li>
</ul>
</div>
</div>
</section>
<section id="bài-tập" class="level2">
<h2 class="anchored" data-anchor-id="bài-tập">Bài tập</h2>
<ol type="1">
<li><strong>(Dễ)</strong> Từ tỷ suất đợt lao tiếp theo, tính xác suất có ít nhất một đợt lao mới trong 2 năm và 10 năm.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 1: probability of at least one recurrence within 2 and 10 years</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">two_years =</span> <span class="fu">rate_to_prob</span>(p<span class="sc">$</span>relapse_rate, <span class="dv">2</span>), <span class="at">ten_years =</span> <span class="fu">rate_to_prob</span>(p<span class="sc">$</span>relapse_rate, <span class="dv">10</span>)), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>two_years ten_years 
   0.0204    0.0979 </code></pre>
</div>
</div>
<p>Xác suất là 2.0% sau 2 năm và 9.8% sau 10 năm, giả định tỷ suất không đổi.</p>
</div>
</div>
</div>
<ol start="2" type="1">
<li><strong>(Khó)</strong> Với nguy cơ không đổi, tỷ lệ hoàn thành BPaLM phải bằng 1 trừ tổng kết cục bất lợi. Kiểm tra điều này bằng vết đoàn hệ (Markov trace) của mô hình đường hầm (dòng Tx6 → Khỏi bệnh) khi thay bảng sống bằng một bảng toàn số 0. Nếu thay vào đó dùng thẳng tỷ lệ bất lợi 12% của thử nghiệm cho Việt Nam, bạn ngầm giả định điều gì?</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 2: share of the BPaLM cohort completing treatment, read from the tunnel</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="co"># trace (flow Tx6 -&gt; Cured) with background mortality switched off (a life table of</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="co"># zeros). Constant hazards predict exactly 1 - sum(q) for the end-of-treatment proportions q.</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>lt_zero <span class="ot">&lt;-</span> <span class="fu">make_lifetable</span>()</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>lt_zero<span class="sc">$</span>mx <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>ev_nobg <span class="ot">&lt;-</span> <span class="fu">evaluate_regimen</span>(p, <span class="st">"bpalm"</span>, <span class="at">lifetable =</span> lt_zero)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>completed <span class="ot">&lt;-</span> ev_nobg<span class="sc">$</span>totals[[<span class="st">"n_completed"</span>]]</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>q_nobg <span class="ot">&lt;-</span> ev_nobg<span class="sc">$</span>inp<span class="sc">$</span>q_unfav<span class="sc">$</span>bpalm</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">from_trace =</span> completed, <span class="at">target =</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">sum</span>(q_nobg)), <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>from_trace     target 
  0.902252   0.902252 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(completed <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">sum</span>(q_nobg))) <span class="sc">&lt;</span> <span class="fl">1e-10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Hai con số trùng nhau (90.2%), và phép so sánh dùng vết đoàn hệ chứ không dùng lại công thức đã sinh ra nguy cơ. Dùng thẳng số của thử nghiệm là giả định người bệnh Việt Nam có nguy cơ nền giống quần thể thử nghiệm (Belarus, Nam Phi, Uzbekistan). Cách dùng RR nhân với nguy cơ nền địa phương giả định ngược lại: hiệu quả <strong>tương đối</strong> chuyển được giữa hai bối cảnh.</p>
</div>
</div>
</div>
</section>
<section id="tài-liệu-tham-khảo" class="level2">
<h2 class="anchored" data-anchor-id="tài-liệu-tham-khảo">Tài liệu tham khảo</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-adamashvili2022low" class="csl-entry" role="listitem">
Adamashvili, N., D. Baliashvili, G. Kuchukhidze, A. D. Salindri, R. R. Kempker, H. M. Blumberg, N. Lomtadze, Z. Avaliani, và M. J. Magee. 2022. <span>“Low <span>BMI</span> increases all-cause mortality rates in patients with drug-resistant <span>TB</span>”</span>. <em>The International Journal of Tuberculosis and Lung Disease</em> 26 (4): 326–33. <a href="https://doi.org/10.5588/ijtld.21.0450">https://doi.org/10.5588/ijtld.21.0450</a>.
</div>
<div id="ref-gso2026gdp2025" class="csl-entry" role="listitem">
Cục Thống kê (Bộ Tài chính). 2026a. <span>“Họp báo công bố tình hình kinh tế – xã hội quý <span>IV</span> và năm 2025”</span>. 5 Tháng Giêng 2026. <a href="https://www.nso.gov.vn/?p=59699">https://www.nso.gov.vn/?p=59699</a>.
</div>
<div id="ref-gso2026population2025" class="csl-entry" role="listitem">
———. 2026b. <span>“Thông cáo báo chí về tình hình dân số, lao động, việc làm quý <span>IV</span> và năm 2025”</span>. 5 Tháng Giêng 2026. <a href="https://www.nso.gov.vn/?p=59530">https://www.nso.gov.vn/?p=59530</a>.
</div>
<div id="ref-fleurence2007rates" class="csl-entry" role="listitem">
Fleurence, Rachael L., và Christopher S. Hollenbeak. 2007. <span>“Rates and probabilities in economic modelling: transformation, translation and appropriate application”</span>. <em>PharmacoEconomics</em> 25 (1): 3–6. <a href="https://doi.org/10.2165/00019053-200725010-00002">https://doi.org/10.2165/00019053-200725010-00002</a>.
</div>
<div id="ref-gidwani2020estimating" class="csl-entry" role="listitem">
Gidwani, Risha, và Louise B. Russell. 2020. <span>“Estimating transition probabilities from published evidence: a tutorial for decision modelers”</span>. <em>PharmacoEconomics</em> 38 (11): 1153–64. <a href="https://doi.org/10.1007/s40273-020-00937-z">https://doi.org/10.1007/s40273-020-00937-z</a>.
</div>
<div id="ref-maclean2026longterm" class="csl-entry" role="listitem">
MacLean, Emily Lai-Ho, Yen Ngoc Pham, Cuong Duc Pham, Binh Cam Nguyen, Frances L. Garden, Tasnim Hasan, Thu-Anh Nguyen, và c.s. 2026. <span>“Long-term outcomes among people with multidrug-resistant tuberculosis in <span>Vietnam</span>: a prospective cohort study”</span>. <em>Clinical Infectious Diseases</em> 81 (6): e623–31. <a href="https://doi.org/10.1093/cid/ciaf363">https://doi.org/10.1093/cid/ciaf363</a>.
</div>
<div id="ref-miller1994determining" class="csl-entry" role="listitem">
Miller, D. K., và S. M. Homan. 1994. <span>“Determining transition probabilities: confusion and suggestions”</span>. <em>Medical Decision Making</em> 14 (1): 52–58. <a href="https://doi.org/10.1177/0272989X9401400107">https://doi.org/10.1177/0272989X9401400107</a>.
</div>
<div id="ref-nguyen2026from" class="csl-entry" role="listitem">
Nguyen, Thi Mai Phuong, Van Luong Dinh, Binh Hoa Nguyen, Thi Thanh Thuy Hoang, Viet Nhung Nguyen, Steven Callens, và Tom Decroo. 2026. <span>“From trials to programmatic scale-up: treatment outcomes of rifampicin-resistant tuberculosis during transition to short oral regimens in <span>Vietnam</span> (2021–2022)”</span>. <em>International Journal of Infectious Diseases</em> 163: 108222. <a href="https://doi.org/10.1016/j.ijid.2025.108222">https://doi.org/10.1016/j.ijid.2025.108222</a>.
</div>
<div id="ref-nyangwa2024short" class="csl-entry" role="listitem">
Nyang’wa, Bern-Thomas, Catherine Berry, Emil Kazounis, Ilaria Motta, Nargiza Parpieva, Zinaida Tigay, Ronelle Moodliar, và c.s. 2024. <span>“Short oral regimens for pulmonary rifampicin-resistant tuberculosis (<span>TB-PRACTECAL</span>): an open-label, randomised, controlled, phase <span>2B</span>–3, multi-arm, multicentre, non-inferiority trial”</span>. <em>The Lancet Respiratory Medicine</em> 12 (2): 117–28. <a href="https://doi.org/10.1016/S2213-2600(23)00389-2">https://doi.org/10.1016/S2213-2600(23)00389-2</a>.
</div>
<div id="ref-romanowski2019longterm" class="csl-entry" role="listitem">
Romanowski, Kamila, Brett Baumann, C. Andrew Basham, Faiz Ahmad Khan, Greg J. Fox, và James C. Johnston. 2019. <span>“Long-term all-cause mortality in people treated for tuberculosis: a systematic review and meta-analysis”</span>. <em>The Lancet Infectious Diseases</em> 19 (10): 1129–37. <a href="https://doi.org/10.1016/S1473-3099(19)30309-3">https://doi.org/10.1016/S1473-3099(19)30309-3</a>.
</div>
<div id="ref-sbv2026interbank" class="csl-entry" role="listitem">
State Bank of Vietnam. 2026. <span>“Developments in Money Market and Inter-bank Market (December 29–31, 2025)”</span>. 2026. <a href="https://sbv.gov.vn/documents/20117/10032242/Dien%20bien%20lai%20suat%2029.31.doc.doc/9d799358-8873-0888-6ac4-089ed5746d93">https://sbv.gov.vn/documents/20117/10032242/Dien%20bien%20lai%20suat%2029.31.doc.doc/9d799358-8873-0888-6ac4-089ed5746d93</a>.
</div>
<div id="ref-tiemersma2011natural" class="csl-entry" role="listitem">
Tiemersma, Edine W., Marieke J. van der Werf, Martien W. Borgdorff, Brian G. Williams, và Nico J. D. Nagelkerke. 2011. <span>“Natural history of tuberculosis: duration and fatality of untreated pulmonary tuberculosis in <span>HIV</span> negative patients: a systematic review”</span>. <em>PLoS ONE</em> 6 (4): e17601. <a href="https://doi.org/10.1371/journal.pone.0017601">https://doi.org/10.1371/journal.pone.0017601</a>.
</div>
<div id="ref-who2026lifetables" class="csl-entry" role="listitem">
World Health Organization. 2026. <span>“Global Health Observatory: life tables by country, <span>Viet Nam</span>, 2023 (indicators <span>LIFE_0000000029</span> nMx, <span>LIFE_0000000030</span> nqx, <span>LIFE_0000000035</span> ex)”</span>. 2026. <a href="https://ghoapi.azureedge.net/api/LIFE_0000000029">https://ghoapi.azureedge.net/api/LIFE_0000000029</a>.
</div>
</div>
<div class="video-script">
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kịch bản video (~14 phút)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Slide</th>
<th>Lời giảng chính</th>
<th>Hình/Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Bốn con số, bốn loại đại lượng</td>
<td>tỷ lệ 76.2%, OR 1.56, RR 0.29, tỷ suất 5.2/100 người-năm</td>
<td>callout</td>
</tr>
<tr class="even">
<td>2</td>
<td>Tỷ suất và xác suất</td>
<td><span class="math inline">\(p = 1-e^{-rt}\)</span>; không chia xác suất cho 12</td>
<td><code>figs/l02-rescale.png</code></td>
</tr>
<tr class="odd">
<td>3</td>
<td>Nguy cơ cạnh tranh</td>
<td>chết thì không thể khỏi; <span class="math inline">\(p_k = \tfrac{r_k}{R}(1-e^{-Rt})\)</span></td>
<td>chunk <code>l02-competing</code></td>
</tr>
<tr class="even">
<td>4</td>
<td>OR qua odds</td>
<td>32.8% chứ không phải 37.1%</td>
<td>chunk <code>l02-or-to-prob</code></td>
</tr>
<tr class="odd">
<td>5</td>
<td>Từ tỷ lệ cuối điều trị đến hazard</td>
<td><span class="math inline">\(H = -\ln(1-q)/D\)</span>; kiểm tra ngược; ba phác đồ</td>
<td>chunk <code>l02-tx-hazards</code></td>
</tr>
<tr class="even">
<td>6</td>
<td>Thử nghiệm và dữ liệu địa phương</td>
<td>RR × nguy cơ nền gộp; bốn chỗ không khớp; tử vong 0% so với 3.6%</td>
<td>chunk <code>l02-effect-measures</code></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Thất bại khác Bỏ điều trị</td>
<td>hai nguồn mâu thuẫn; điều trị lại</td>
<td>chunk <code>l02-ltfu-retx</code></td>
</tr>
<tr class="even">
<td>8</td>
<td>Bảng sống và SMR</td>
<td>bảng WHO 2023; SMR so với ai; một đường, không đếm hai lần</td>
<td><code>figs/l02-lifetable.png</code></td>
</tr>
<tr class="odd">
<td>9</td>
<td>Chọn độ dài chu kỳ</td>
<td>bội số nguyên; sai số nhỏ; tốc độ</td>
<td>chunk <code>l02-cycle-length</code></td>
</tr>
<tr class="even">
<td>10</td>
<td>Tóm tắt</td>
<td>có xác suất rồi, chạy vết đoàn hệ → Bài 3</td>
<td>—</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../kb/m02-cohort-markov/l01-state-transition.html" class="pagination-link" aria-label="Bài 1: Vì sao cần mô hình chuyển trạng thái">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Bài 1: Vì sao cần mô hình chuyển trạng thái</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../kb/m02-cohort-markov/l03-cohort-trace.html" class="pagination-link" aria-label="Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu">
        <span class="nav-page-text"><span class="chapter-title">Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>