<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bài 1: Quy trình làm việc tái lập với R – Mô hình Kinh tế Y tế với R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../kb/m00-r-foundations/l02-vectors-matrices.html" rel="next">
<link href="../../kb/m00-r-foundations/index.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9e7f0c659d5fa2cace8548cb57964278.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c18d72663580ed8ca19ce2a2f99af51b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="mermaid-theme" content="neutral">
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=JetBrains+Mono:wght@400;600&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m00-r-foundations/index.html">M00 · R cho mô hình kinh tế y tế</a></li><li class="breadcrumb-item"><a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Mô hình Kinh tế Y tế với R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lời mở đầu</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m00-r-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M00 · R cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l02-vectors-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l03-functions-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hàm, cấu trúc điều khiển, vòng lặp và vectơ hóa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l04-data-frames.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Data frame — nhập, làm sạch, tóm tắt và chuyển dạng dữ liệu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l05-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Biểu đồ với ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l06-randomness-monte-carlo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 6: Ngẫu nhiên, mô phỏng Monte Carlo và sai số Monte Carlo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m01-ee-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M01 · Nền tảng đánh giá kinh tế và cây quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l01-evaluation-types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại đánh giá kinh tế, quan điểm, khung thời gian và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l02-health-outcomes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Năm sống, QALY và DALY</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l03-decision-rules.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l04-thresholds.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l05-decision-tree.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Xây cây quyết định từ đầu trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m02-cohort-markov/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l01-state-transition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao cần mô hình chuyển trạng thái</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l03-cohort-trace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l04-time-dependence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Phụ thuộc thời gian: lão hóa, trạng thái đường hầm và mảng 3 chiều</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l05-results-verification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị gắn với lần chuyển, đường biên hiệu quả và xác minh mô hình</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m03-uncertainty-voi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l01-deterministic-sa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại bất định và phân tích độ nhạy tất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l02-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Chọn phân phối cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l03-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích độ nhạy xác suất (PSA) trong R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l05-voi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m04-microsimulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M04 · Mô phỏng vi mô (microsimulation)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l01-why-microsimulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l02-microsim-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l03-vectorisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vectơ hóa theo cá thể và đo hiệu năng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l04-parallel-rcpp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tính toán song song và Rcpp cho vòng lặp nóng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l05-mc-error-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bao nhiêu cá thể là đủ? Sai số Monte Carlo, PSA và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m05-dynamic-transmission/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M05 · Mô hình lây truyền động</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l01-static-vs-dynamic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Mô hình tĩnh và mô hình lây truyền động</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l02-sir-seir-desolve.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình SIR và SEIR trong R với deSolve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l03-vaccination-herd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Tiêm chủng, hiệu quả trực tiếp và gián tiếp</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l04-dengue-host-vector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Mô hình vật chủ–véc tơ cho sốt xuất huyết Dengue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l05-dynamic-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế với mô hình lây truyền động</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m06-amr-economics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M06 · Kinh tế học kháng kháng sinh (AMR)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l01-amr-burden.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l02-attributable-los.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l03-ward-transmission.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Mô hình lây truyền CRE trong khoa hồi sức</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l04-two-strain-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m07-survival-psm/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M07 · Phân tích sống còn cho mô hình quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l01-survival-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ôn tập phân tích sống còn cho người làm mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l02-parametric-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình sống còn tham số với flexsurv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l03-extrapolation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Ngoại suy sống còn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l04-reconstruct-ipd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tái tạo dữ liệu cá thể từ đường KM đã công bố và dùng HR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l05-partitioned-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Mô hình sống còn phân vùng trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m08-calibration/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M08 · Hiệu chuẩn mô hình (calibration)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l01-why-calibrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l02-search-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l03-bayes-sir.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hiệu chuẩn Bayes và thuật toán SIR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l04-psa-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đưa kết quả hiệu chuẩn vào PSA, thẩm định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m09-inputs-vietnam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l01-costing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ước tính chi phí cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l05-decision-context.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bối cảnh ra quyết định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m10-policy-bia-equity/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m11-software-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l01-code-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Cấu trúc mã cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l02-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Xác minh và kiểm thử mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l03-version-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quản lý phiên bản với Git và tái lập môi trường với renv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l04-r-package.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đóng gói mô hình thành gói R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l05-shiny-living.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Ứng dụng Shiny và mô hình “sống”</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bảng thuật ngữ Anh–Việt</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Trong bài</h2>
   
  <ul class="collapse">
  <li><a href="#mục-tiêu-học-tập" id="toc-mục-tiêu-học-tập" class="nav-link active" data-scroll-target="#mục-tiêu-học-tập">Mục tiêu học tập</a></li>
  <li><a href="#ý-chính" id="toc-ý-chính" class="nav-link" data-scroll-target="#ý-chính">Ý chính</a></li>
  <li><a href="#nội-dung" id="toc-nội-dung" class="nav-link" data-scroll-target="#nội-dung">Nội dung</a></li>
  <li><a href="#thực-hành" id="toc-thực-hành" class="nav-link" data-scroll-target="#thực-hành">Thực hành</a></li>
  <li><a href="#bài-tập" id="toc-bài-tập" class="nav-link" data-scroll-target="#bài-tập">Bài tập</a></li>
  <li><a href="#tài-liệu-tham-khảo" id="toc-tài-liệu-tham-khảo" class="nav-link" data-scroll-target="#tài-liệu-tham-khảo">Tài liệu tham khảo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m00-r-foundations/index.html">M00 · R cho mô hình kinh tế y tế</a></li><li class="breadcrumb-item"><a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></h1>
<p class="subtitle lead">Tổ chức một dự án mô hình sao cho mọi con số đều chạy lại được từ mã</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled" title="Vì sao bạn nên quan tâm?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vì sao bạn nên quan tâm?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cuối năm, Hội đồng thuốc và điều trị của một bệnh viện tỉnh họp để sửa phác đồ kháng sinh kinh nghiệm cho ICU, dựa trên bản tổng kết kháng sinh đồ do khoa vi sinh gửi lên. Một ngày colistin cho một người bệnh nhiễm CRE tốn khoảng 3,641,873 VNĐ theo giá trúng thầu quy về năm 2025 <span class="citation" data-cites="thainguyen2023thau">(<a href="index.html#ref-thainguyen2023thau" role="doc-biblioref">Bệnh viện Trung ương Thái Nguyên 2023</a>)</span>, gấp 23 lần một ngày meropenem generic <span class="citation" data-cites="cuchi2024thau">(<a href="index.html#ref-cuchi2024thau" role="doc-biblioref">Bệnh viện Đa khoa khu vực Củ Chi 2024</a>)</span> và bằng 15 ngày lương tối thiểu vùng I theo mức từ 1/1/2026 <span class="citation" data-cites="chinhphu2025nd293">(<a href="index.html#ref-chinhphu2025nd293" role="doc-biblioref">Chính phủ 2025</a>)</span>. Nếu tỷ lệ <em>K. pneumoniae</em> kháng carbapenem trong báo cáo bị gõ tay sai, hội đồng có thể đẩy cả khoa sang phác đồ đắt gấp nhiều lần, hoặc giữ một phác đồ đã mất tác dụng, mà không ai phát hiện. Bài này giúp bạn tổ chức dự án sao cho mọi con số trong báo cáo đều chạy lại được từ dữ liệu thô và truy được về nguồn, để hội đồng có thể tin và kiểm tra.</p>
</div>
</div>
<section id="mục-tiêu-học-tập" class="level2">
<h2 class="anchored" data-anchor-id="mục-tiêu-học-tập">Mục tiêu học tập</h2>
<p>Sau bài này, bạn có thể:</p>
<ol type="1">
<li>Chạy một script R từ thư mục gốc của dự án, bằng IDE hoặc bằng <code>Rscript</code>.</li>
<li>Sắp xếp một dự án mô hình thành các thư mục <code>code/</code>, <code>params/</code>, <code>data/</code>, <code>figs/</code> và giải thích vai trò của từng thư mục.</li>
<li>Lưu tham số trong bảng CSV có cột nguồn và cờ giá trị minh họa, đọc bằng <code>read_params()</code>, và truy một tham số về số liệu công bố gốc.</li>
<li>Chọn đúng công cụ: script <code>.R</code> cho phần tính toán, Quarto <code>.qmd</code> cho phần báo cáo.</li>
<li>Viết con số trong văn bản bằng mã R nội dòng thay vì gõ tay.</li>
</ol>
</section>
<section id="ý-chính" class="level2">
<h2 class="anchored" data-anchor-id="ý-chính">Ý chính</h2>
<ul>
<li><strong>Tính tái lập (reproducibility)</strong> nghĩa là người khác, hoặc chính bạn sáu tháng sau, chạy lại mã trên cùng dữ liệu và ra đúng các con số đã báo cáo.</li>
<li>Thư mục dự án là đơn vị làm việc. Mọi đường dẫn tính tương đối từ thư mục module (module dùng chung <code>_shared/</code> đặt ở thư mục cha, xem bên dưới); không dùng <code>setwd()</code> với đường dẫn tuyệt đối.</li>
<li>Tách ba lớp: <strong>đầu vào</strong> (<code>params/</code>, <code>data/</code>), <strong>mô hình</strong> (hàm trong <code>code/model.R</code>), <strong>phân tích</strong> (một script cho mỗi câu hỏi). Kết quả đi vào <code>figs/</code> và báo cáo.</li>
<li>Dữ liệu thô chỉ để đọc. Mọi bước làm sạch được viết thành mã.</li>
<li>Mỗi tham số là một dòng trong <strong>bảng tham số (parameter table)</strong>, kèm nguồn, hoặc gắn cờ <code>illustrative = TRUE</code> nếu là giá trị minh họa. Tham số suy ra từ số liệu công bố thì phép suy ra cũng phải nằm trong mã.</li>
<li>Giá trị dùng chung cho cả khóa học (giá dịch vụ, giá thuốc, lương, CPI, bảng sống) chỉ nằm ở <code>_shared/</code>; module không chép lại.</li>
<li>Mọi con số trong văn bản sinh ra từ <strong>mã R nội dòng (inline R code)</strong>. Số gõ tay sẽ lỗi thời ngay khi dữ liệu hoặc mã thay đổi.</li>
<li>Ghi lại môi trường chạy: phiên bản R và gói, cùng <code>set.seed()</code> cho mọi bước ngẫu nhiên.</li>
</ul>
</section>
<section id="nội-dung" class="level2">
<h2 class="anchored" data-anchor-id="nội-dung">Nội dung</h2>
<section id="vì-sao-tái-lập-là-yêu-cầu-bắt-buộc" class="level3">
<h3 class="anchored" data-anchor-id="vì-sao-tái-lập-là-yêu-cầu-bắt-buộc">Vì sao tái lập là yêu cầu bắt buộc</h3>
<p>Một mô hình kinh tế y tế là một lập luận định lượng dùng để hỗ trợ quyết định, ví dụ có nên đưa một xét nghiệm nhanh vào danh mục chi trả hay không. Hội đồng đánh giá công nghệ y tế, người phản biện và đồng nghiệp đều cần kiểm tra lập luận đó. Mô hình dựng trong bảng tính thường khó kiểm tra: công thức nằm rải rác trong các ô, khó so sánh phiên bản, và khó chạy lại hàng nghìn lần cho phân tích bất định. Đó là nhận xét thực tế của người viết. Các tác giả đánh giá công nghệ y tế cũng nêu rằng bảng tính hạn chế tính minh bạch, khả năng tái lập và việc định lượng bất định, còn các ngôn ngữ lập trình như R cho phép xây mô hình minh bạch, tái lập, dùng lại được và biểu diễn được bất định <span class="citation" data-cites="incerti2019r">(<a href="index.html#ref-incerti2019r" role="doc-biblioref">Incerti và c.s. 2019</a>)</span>.</p>
<p>Hai bài viết ngắn đáng đọc trước khi bắt đầu tóm tắt các thói quen tối thiểu: ghi lại cách tạo ra mọi kết quả, tránh thao tác tay, lưu dữ liệu gốc nguyên vẹn, đặt seed cho mọi bước ngẫu nhiên và quản lý phiên bản <span class="citation" data-cites="sandve2013ten wilson2017good">(<a href="index.html#ref-sandve2013ten" role="doc-biblioref">Sandve và c.s. 2013</a>; <a href="index.html#ref-wilson2017good" role="doc-biblioref">Wilson và c.s. 2017</a>)</span>. Khóa học này áp dụng các thói quen đó ngay từ bài đầu.</p>
</section>
<section id="r-và-trình-soạn-mã" class="level3">
<h3 class="anchored" data-anchor-id="r-và-trình-soạn-mã">R và trình soạn mã</h3>
<p>R là môi trường tính toán thống kê miễn phí, chạy trên Windows, macOS và Linux <span class="citation" data-cites="rcoreteam_r">(<a href="index.html#ref-rcoreteam_r" role="doc-biblioref">R Core Team không ngày</a>)</span>. Bạn viết mã trong một trình soạn mã tích hợp (IDE) như RStudio, Positron hoặc VS Code. Có hai cách chạy mã. Gõ từng lệnh vào <em>console</em> để thử nhanh. Lưu chuỗi lệnh vào một <strong>script</strong> <code>.R</code> rồi chạy từ đầu đến cuối để có kết quả chính thức. Kết quả chính thức chỉ do script tạo ra, không phải những gì bạn đã gõ vào console.</p>
<p>Gói (package) mở rộng R. Cài một lần bằng <code>install.packages("ggplot2")</code>, nạp ở mỗi phiên bằng <code>library(ggplot2)</code>. Khóa học dùng base R cho cơ chế mô hình vì từng bước đều nhìn thấy được, và dùng <code>ggplot2</code> để vẽ biểu đồ.</p>
</section>
<section id="cấu-trúc-một-dự-án-mô-hình" class="level3">
<h3 class="anchored" data-anchor-id="cấu-trúc-một-dự-án-mô-hình">Cấu trúc một dự án mô hình</h3>
<p>Mỗi module của khóa học là một dự án nhỏ với cùng một cấu trúc:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Thư mục/tệp</th>
<th>Chứa gì</th>
<th>Quy tắc</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>params/*.csv</code></td>
<td>Tham số: giá trị, khoảng, phân phối, nguồn</td>
<td>Không có số gõ cứng trong mã</td>
</tr>
<tr class="even">
<td><code>data/</code></td>
<td>Dữ liệu đầu vào</td>
<td>Chỉ đọc; tạo ra bằng mã hoặc nhận nguyên trạng</td>
</tr>
<tr class="odd">
<td><code>code/model.R</code></td>
<td>Định nghĩa hàm</td>
<td>Nạp vào không gây tác dụng phụ</td>
</tr>
<tr class="even">
<td><code>code/lNN-*.R</code></td>
<td>Một phân tích hoàn chỉnh</td>
<td>Chạy độc lập từ thư mục gốc</td>
</tr>
<tr class="odd">
<td><code>figs/</code></td>
<td>Hình do mã tạo ra</td>
<td>Không sửa tay</td>
</tr>
<tr class="even">
<td><code>lNN-*.qmd</code></td>
<td>Bài viết, kéo mã từ script</td>
<td>Mọi con số là mã R nội dòng</td>
</tr>
</tbody>
</table>
<p>Cách tách này giống khung mã hóa được đề xuất cho mô hình quyết định trong R. Khung đó chia công việc thành đầu vào, triển khai mô hình, hiệu chuẩn, thẩm định và phân tích <span class="citation" data-cites="alaridescudero2019need">(<a href="index.html#ref-alaridescudero2019need" role="doc-biblioref">Alarid-Escudero và c.s. 2019</a>)</span>. Lợi ích rất thực tế: muốn đổi một giá thuốc, bạn sửa một dòng CSV và chạy lại, không phải lục tìm trong mã.</p>
<p>Mọi module cùng dùng hai tệp đặt ở thư mục cha: <code>_shared/R/helpers.R</code> (hàm định dạng số, hàm kiểm tra, giao diện đồ họa) và <code>_shared/R/vn_data.R</code> (giá trị dùng chung của Việt Nam: giá dịch vụ BHYT, giá thuốc trúng thầu, lương tối thiểu, CPI, bảng sống). Nhờ vậy, khi Bộ Y tế đổi giá ngày giường, chỉ cần sửa một dòng trong <code>_shared/</code> và mọi module cập nhật ở lần chạy sau. “Dự án” của khóa học là thư mục gốc <code>kb/</code>, trong đó các module nằm cạnh <code>_shared/</code>. Khi tải về, hãy tải cả <code>_shared/</code> lẫn module bạn học; mỗi script chạy với thư mục module làm thư mục làm việc.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>flowchart LR</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  A["params/*.csv&lt;br/&gt;data/ (chỉ đọc)"] --&gt; B["code/model.R&lt;br/&gt;chỉ định nghĩa hàm"]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  B --&gt; C["code/lNN-*.R&lt;br/&gt;phân tích"]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  A --&gt; C</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  C --&gt; D["figs/*.png&lt;br/&gt;con số"]</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  D --&gt; E["lNN-*.qmd&lt;br/&gt;mã R nội dòng"]</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  E --&gt; F["HTML / DOCX"]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  A["params/*.csv&lt;br/&gt;data/ (chỉ đọc)"] --&gt; B["code/model.R&lt;br/&gt;chỉ định nghĩa hàm"]
  B --&gt; C["code/lNN-*.R&lt;br/&gt;phân tích"]
  A --&gt; C
  C --&gt; D["figs/*.png&lt;br/&gt;con số"]
  D --&gt; E["lNN-*.qmd&lt;br/&gt;mã R nội dòng"]
  E --&gt; F["HTML / DOCX"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
<section id="script-hay-quarto" class="level3">
<h3 class="anchored" data-anchor-id="script-hay-quarto">Script hay Quarto?</h3>
<p>Script <code>.R</code> là nơi tính toán: chạy từ trên xuống, không phụ thuộc thứ tự bạn bấm nút. Quarto <span class="citation" data-cites="posit_quarto">(<a href="index.html#ref-posit_quarto" role="doc-biblioref">Posit không ngày</a>)</span> trộn văn bản với mã và xuất ra HTML, Word hoặc PDF. Mỗi lần xuất, toàn bộ mã chạy lại từ đầu. Khóa học dùng cả hai mà không chép mã hai lần: script đánh dấu từng đoạn bằng <code>## ---- nhãn ----</code>, và bài học kéo đoạn đó vào bằng <code>knitr::read_chunk()</code>. Mã chỉ tồn tại ở một nơi, nên bài viết không bao giờ lệch khỏi mã.</p>
</section>
<section id="mọi-con-số-do-mã-tạo-ra" class="level3">
<h3 class="anchored" data-anchor-id="mọi-con-số-do-mã-tạo-ra">Mọi con số do mã tạo ra</h3>
<p>Đây là nguyên tắc 9 trong mười quy tắc của Sandve và cộng sự: mỗi câu nêu kết quả phải truy được về kết quả nền bên dưới <span class="citation" data-cites="sandve2013ten">(<a href="index.html#ref-sandve2013ten" role="doc-biblioref">Sandve và c.s. 2013</a>)</span>. Trong tệp <code>.qmd</code>, câu nêu tỷ lệ đề kháng không chứa con số gõ tay mà chứa <code>`r fmt_pct(res_2025)`</code> (biểu thức R đặt giữa hai dấu backtick, bắt đầu bằng chữ <code>r</code>). Khi xuất, Quarto chạy biểu thức này và chèn kết quả vào câu. Nếu dữ liệu, tham số hoặc seed thay đổi, con số tự cập nhật. Các hàm <code>fmt_num()</code>, <code>fmt_pct()</code>, <code>fmt_vnd()</code> và <code>fmt_ci()</code> trong <code>_shared/R/helpers.R</code> thống nhất cách viết số cho cả khóa học: dấu chấm thập phân, dấu phẩy phân cách hàng nghìn.</p>
</section>
<section id="ghi-lại-môi-trường-chạy" class="level3">
<h3 class="anchored" data-anchor-id="ghi-lại-môi-trường-chạy">Ghi lại môi trường chạy</h3>
<p>Kết quả có thể đổi khi phiên bản R hoặc phiên bản gói thay đổi. Tối thiểu, hãy in phiên bản R và các gói chính ở cuối báo cáo. Với dự án dài hạn, gói <code>renv</code> lưu đúng phiên bản của từng gói vào một tệp khóa để người khác cài lại y hệt <span class="citation" data-cites="ushey_renv">(<a href="index.html#ref-ushey_renv" role="doc-biblioref">Ushey và Wickham không ngày</a>)</span>. Mọi bước ngẫu nhiên đều bắt đầu bằng <code>set.seed()</code> (xem Bài 6).</p>
</section>
</section>
<section id="thực-hành" class="level2">
<h2 class="anchored" data-anchor-id="thực-hành">Thực hành</h2>
<p>Mọi script trong khóa học mở đầu như nhau: dừng ngay nếu chạy sai thư mục, bật mã hóa UTF-8 để hiển thị tiếng Việt, nạp các hàm dùng chung (<code>helpers.R</code>, <code>vn_data.R</code>) và hàm của module, rồi bật cảnh báo khi <code>$</code> tự khớp với tên viết tắt (xem Bài 2). Kiểm tra: không có thông báo lỗi nào.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fail early, before anything is sourced, if the script is not run from the module folder</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(<span class="st">"code/model.R"</span>) <span class="sc">||</span> <span class="sc">!</span><span class="fu">file.exists</span>(<span class="st">"../_shared/R/helpers.R"</span>)) {</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stop</span>(<span class="st">"Run this script from the module folder (the one that contains code/ and params/); "</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>       <span class="st">"the course root must also contain _shared/."</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Vietnamese text needs a UTF-8 locale (Rscript may start in the "C" locale)</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">isTRUE</span>(<span class="fu">l10n_info</span>()[[<span class="st">"UTF-8"</span>]])) <span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_CTYPE"</span>, <span class="st">"en_US.UTF-8"</span>))</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/helpers.R"</span>)   <span class="co"># shared helpers: formatting, checks, plot theme</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/vn_data.R"</span>)   <span class="co"># shared Vietnamese inputs: prices, wages, life table, CPI</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"code/model.R"</span>)             <span class="co"># this module's functions (definitions only)</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">warnPartialMatchDollar =</span> <span class="cn">TRUE</span>)   <span class="co"># warn when `$` silently matches a shortened name (Lesson 2)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Lỗi hay gặp nhất của người mới là chạy script từ sai thư mục; các dòng đầu của đoạn mã trên đã chặn lỗi đó. Đoạn mã sau liệt kê thư mục hiện hành và các thư mục của dự án, tạo <code>data/</code> và <code>figs/</code> nếu chưa có. Kiểm tra: tên thư mục hiện hành là <code>m00-r-foundations</code> và cả bốn thư mục đều tồn tại.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Where are we? code/ and params/ must exist; data/ and figs/ are created when missing</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">dir.exists</span>(<span class="st">"code"</span>), <span class="fu">dir.exists</span>(<span class="st">"params"</span>))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (f <span class="cf">in</span> <span class="fu">c</span>(<span class="st">"data"</span>, <span class="st">"figs"</span>)) <span class="fu">dir.create</span>(f, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">basename</span>(<span class="fu">getwd</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "m00-r-foundations"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>folders <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"code"</span>, <span class="st">"params"</span>, <span class="st">"data"</span>, <span class="st">"figs"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">folder =</span> folders, <span class="at">exists =</span> <span class="fu">dir.exists</span>(folders))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  folder exists
1   code   TRUE
2 params   TRUE
3   data   TRUE
4   figs   TRUE</code></pre>
</div>
</div>
<p>Tiếp theo, ta đọc bảng tham số của bộ dữ liệu mô phỏng. <code>read_params()</code> trả về một danh sách có tên, nên mỗi tham số được gọi bằng <code>p_sim$ten_tham_so</code>. Bảng trộn hai loại dòng: mốc đã công bố, có khóa tài liệu trong cột <code>source</code> (tỷ lệ đề kháng, tỷ lệ loài, xu hướng), và giá trị minh họa cho những gì không có số liệu công khai (lỗi nhập liệu, số lần cấy lại). Kiểm tra: bảng đếm theo nguồn cho thấy mỗi dòng có nguồn trỏ tới một khóa trong <code>refs.bib</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>p_sim <span class="ot">&lt;-</span> <span class="fu">read_params</span>(<span class="st">"params/amr_sim.csv"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>tab_sim <span class="ot">&lt;-</span> <span class="fu">attr</span>(p_sim, <span class="st">"table"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>tab_sim[tab_sim<span class="sc">$</span>name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"n_pat_a"</span>, <span class="st">"target_kpn_mem"</span>, <span class="st">"trend_kpn"</span>),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">c</span>(<span class="st">"name"</span>, <span class="st">"value"</span>, <span class="st">"source"</span>, <span class="st">"illustrative"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             name   value              source illustrative
3         n_pat_a 300.000                             TRUE
21 target_kpn_mem   0.370   larsson2025burden        FALSE
24      trend_kpn   0.146 vu2021antimicrobial        FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>n_params <span class="ot">&lt;-</span> <span class="fu">nrow</span>(tab_sim)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>n_sourced <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">as.logical</span>(tab_sim<span class="sc">$</span>illustrative))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>n_illustrative <span class="ot">&lt;-</span> n_params <span class="sc">-</span> n_sourced</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">n_params =</span> n_params, <span class="at">n_sourced =</span> n_sourced, <span class="at">n_illustrative =</span> n_illustrative)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      n_params      n_sourced n_illustrative 
            41             24             17 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">source =</span> <span class="fu">ifelse</span>(<span class="fu">as.logical</span>(tab_sim<span class="sc">$</span>illustrative), <span class="st">"(minh họa)"</span>, tab_sim<span class="sc">$</span>source))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>source
         (minh họa)   larsson2025burden vu2021antimicrobial 
                 17                   3                  21 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(n_sourced <span class="sc">+</span> n_illustrative <span class="sc">==</span> n_params, n_sourced <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>p_sim<span class="sc">$</span>target_kpn_mem   <span class="co"># access one value by name</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.37</code></pre>
</div>
</div>
<p>Bảng có 41 tham số: 24 có nguồn và 17 là giá trị minh họa.</p>
<p><code>read_params()</code> còn đóng vai trò hàng rào an toàn. Nếu một tham số được khai là số liệu thật (<code>illustrative = FALSE</code>) mà không có nguồn, hàm dừng lại và nêu tên tham số đó. Ta cố ý tạo một bảng lỗi để xem thông báo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A "real" parameter without a source is refused by read_params()</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>bad <span class="ot">&lt;-</span> tab_sim[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, ]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>bad<span class="sc">$</span>illustrative[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="cn">FALSE</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> <span class="fu">tempfile</span>(<span class="at">fileext =</span> <span class="st">".csv"</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(bad, tmp, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>msg <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>(<span class="fu">read_params</span>(tmp), <span class="at">error =</span> <span class="cf">function</span>(e) <span class="fu">conditionMessage</span>(e))</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>msg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Non-illustrative parameters need a source: n_years"</code></pre>
</div>
</div>
<p>Có nguồn chưa đủ: phải truy được con số về số liệu gốc. Xác suất mắc mới CRE mỗi ngày trong <code>params/icu_markov.csv</code> không có trong bài báo nào; nó được suy ra từ hai mốc công bố <span class="citation" data-cites="tran2019high">(<a href="index.html#ref-tran2019high" role="doc-biblioref">Tran và c.s. 2019</a>)</span>. Nếu mỗi ngày một tỷ lệ <span class="math inline">\(p\)</span> người chưa mang khuẩn bị lây, phần chưa mang khuẩn giảm theo cấp số nhân: <span class="math inline">\((1 - p)^T = (1 - \pi_T)/(1 - \pi_0)\)</span>, với <span class="math inline">\(\pi_0\)</span> và <span class="math inline">\(\pi_T\)</span> là tỷ lệ mang khuẩn vào ngày nhập viện và ngày thứ <span class="math inline">\(T\)</span>. Phép suy ra này là một xấp xỉ: điều tra gốc là cắt ngang, gộp cả sơ sinh, trẻ em và người lớn, và ta đọc đường cong theo ngày nằm viện như thể đó là đường theo dõi một đoàn hệ. Các mốc nằm trong <code>params/reference_data.csv</code>; hàm <code>icu_probs_from_anchors()</code> làm lại mọi phép suy ra, và ta so với CSV. Kiểm tra: hai cột khớp nhau đến sai số làm tròn.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Every number must trace back to its source. The daily probabilities of the ICU model</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (params/icu_markov.csv) were derived from published figures kept in params/reference_data.csv.</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Recompute them in code and compare with the CSV.</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>ref <span class="ot">&lt;-</span> <span class="fu">read_params</span>(<span class="st">"params/reference_data.csv"</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>q_csv <span class="ot">&lt;-</span> <span class="fu">read_params</span>(<span class="st">"params/icu_markov.csv"</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>derived <span class="ot">&lt;-</span> <span class="fu">icu_probs_from_anchors</span>(ref)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>in_csv <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">unlist</span>(q_csv[<span class="fu">setdiff</span>(<span class="fu">names</span>(derived), <span class="st">"p_i_alive_exit"</span>)]),</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">p_i_alive_exit =</span> q_csv<span class="sc">$</span>p_i_c <span class="sc">+</span> q_csv<span class="sc">$</span>p_i_x)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>trace_tab <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="at">csv =</span> in_csv, <span class="at">derived =</span> derived[<span class="fu">names</span>(in_csv)])</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(trace_tab, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  csv derived
p_u_c          0.1288 0.12879
p_u_x          0.0897 0.08966
p_u_d          0.0227 0.02270
p_c_u          0.0088 0.00880
p_c_i          0.0197 0.01972
p_c_x          0.0897 0.08966
p_c_d          0.0227 0.02270
p_i_d          0.0305 0.03048
p_i_alive_exit 0.0657 0.06567</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(trace_tab[, <span class="st">"csv"</span>] <span class="sc">-</span> trace_tab[, <span class="st">"derived"</span>]) <span class="sc">&lt;</span> <span class="fl">1e-4</span>))   <span class="co"># equal up to rounding</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Với <span class="math inline">\(\pi_0\)</span> = 13%, <span class="math inline">\(\pi_T\)</span> = 89% và <span class="math inline">\(T\)</span> = 15 ngày, xác suất mắc mới là 0.1288 mỗi ngày, đúng giá trị 0.1288 trong CSV. Người đọc báo cáo muốn kiểm tra con số này chỉ cần mở bài báo gốc và chạy lại một dòng mã.</p>
<p>Bây giờ ta tạo bộ dữ liệu của module. <code>simulate_isolates()</code> sinh từng chủng phân lập (isolate) theo các tham số trên, quanh các mốc đã công bố; <code>str()</code> cho thấy mỗi cột có kiểu gì. Kiểm tra: bảng chéo bệnh viện × năm không có ô trống, và ba điều kiện trong <code>stopifnot()</code> đều đúng.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>iso <span class="ot">&lt;-</span> <span class="fu">simulate_isolates</span>(p_sim, <span class="at">seed =</span> <span class="dv">2025</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(iso)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   4080 obs. of  12 variables:
 $ isolate_id: chr  "I00001" "I00002" "I00003" "I00004" ...
 $ patient_id: chr  "P00005" "P00073" "P00190" "P00218" ...
 $ hospital  : chr  "A" "A" "A" "A" ...
 $ ward      : chr  "non-ICU" "ICU" "non-ICU" "ICU" ...
 $ date      : Date, format: "2021-01-01" "2021-01-01" ...
 $ year      : int  2021 2021 2021 2021 2021 2021 2021 2021 2021 2021 ...
 $ organism  : chr  "A. baumannii" "E. coli" "E. coli" "E. coli" ...
 $ CRO       : chr  NA "R" "R" "R" ...
 $ CIP       : chr  "R" "R" "R" "R" ...
 $ GEN       : chr  "R" "R" "R" "R" ...
 $ SXT       : chr  "R" "R" "R" "R" ...
 $ MEM       : chr  "R" "S" "S" "R" ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(iso<span class="sc">$</span>hospital, iso<span class="sc">$</span>year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
    2021 2022 2023 2024 2025
  A  426  412  414  383  383
  B  260  264  250  222  252
  C  174  160  150  176  154</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sanity checks: unique IDs, every antibiotic column present, years as planned</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="sc">!</span><span class="fu">anyDuplicated</span>(iso<span class="sc">$</span>isolate_id),</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(<span class="fu">names</span>(ANTIBIOTICS) <span class="sc">%in%</span> <span class="fu">names</span>(iso)),</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(iso<span class="sc">$</span>year <span class="sc">%in%</span> (p_sim<span class="sc">$</span>year_start <span class="sc">+</span> <span class="dv">0</span><span class="sc">:</span>(p_sim<span class="sc">$</span>n_years <span class="sc">-</span> <span class="dv">1</span>))))</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>n_iso <span class="ot">&lt;-</span> <span class="fu">nrow</span>(iso)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>n_pat <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(iso<span class="sc">$</span>patient_id))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Bộ dữ liệu có 4,080 chủng từ 3,094 người bệnh. Số chủng nhiều hơn số người bệnh vì một số người được cấy nhiều lần.</p>
<p>Phòng xét nghiệm không gửi dữ liệu sạch. <code>make_messy()</code> biến dữ liệu sạch thành một tệp trích xuất từ phòng xét nghiệm (laboratory export) có lỗi nhập liệu điển hình, và ta ghi nó vào <code>data/</code>. Tệp này được tạo ra hoàn toàn bằng mã, nên xóa đi rồi chạy lại vẫn ra đúng tệp cũ. Kiểm tra: số dòng đọc lại phải khớp với số dòng đã ghi.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The "laboratory export": written by code, never edited by hand</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>raw <span class="ot">&lt;-</span> <span class="fu">make_messy</span>(iso, p_sim, <span class="at">seed =</span> <span class="dv">2026</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(<span class="st">"data"</span>, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(raw, <span class="st">"data/amr_isolates_raw.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>, <span class="at">na =</span> <span class="st">""</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>raw_back <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/amr_isolates_raw.csv"</span>, <span class="at">na.strings =</span> <span class="st">""</span>, <span class="at">encoding =</span> <span class="st">"UTF-8"</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">nrow</span>(raw_back) <span class="sc">==</span> <span class="fu">nrow</span>(raw), <span class="fu">ncol</span>(raw_back) <span class="sc">==</span> <span class="fu">ncol</span>(raw))</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(raw_back)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4100   11</code></pre>
</div>
</div>
<p>Tệp <code>data/amr_isolates_raw.csv</code> có 4,100 dòng, nhiều hơn dữ liệu sạch 20 dòng do các dòng bị nhập trùng.</p>
<p>Đoạn sau cho thấy vì sao không được gõ số bằng tay. Ta tính cùng một con số, tỷ lệ <em>A. baumannii</em> đề kháng meropenem, trên hai bộ dữ liệu sinh từ hai seed khác nhau. Tỷ lệ này tính trên mọi chủng, kể cả chủng lặp lại; Bài 4 sẽ loại chúng. Kiểm tra: hai kết quả khác nhau.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One result computed twice: with the seed used in the lesson and with another seed.</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (Computed on all isolates, repeats included; Lesson 4 removes the repeats.)</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>aba_mem_r <span class="ot">&lt;-</span> <span class="cf">function</span>(d) <span class="fu">mean</span>(d<span class="sc">$</span>MEM[d<span class="sc">$</span>organism <span class="sc">==</span> <span class="st">"A. baumannii"</span>] <span class="sc">==</span> <span class="st">"R"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>res_2025 <span class="ot">&lt;-</span> <span class="fu">aba_mem_r</span>(iso)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>res_2026 <span class="ot">&lt;-</span> <span class="fu">aba_mem_r</span>(<span class="fu">simulate_isolates</span>(p_sim, <span class="at">seed =</span> <span class="dv">2026</span>))</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">seed_2025 =</span> <span class="fu">fmt_pct</span>(res_2025), <span class="at">seed_2026 =</span> <span class="fu">fmt_pct</span>(res_2026))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>seed_2025 seed_2026 
  "72.4%"   "73.8%" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(res_2025 <span class="sc">!=</span> res_2026)   <span class="co"># the lesson says the two results differ</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Với seed của bài học, tỷ lệ là 72.4%; với seed khác, 73.8%. Nếu bạn gõ tay con số thứ nhất vào báo cáo rồi sau đó đổi seed hay sửa dữ liệu, báo cáo sẽ sai mà không ai biết. Câu văn bạn vừa đọc dùng mã R nội dòng, nên nó luôn đúng.</p>
<p>Cuối cùng, ghi lại môi trường đã tạo ra kết quả.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">R =</span> R.version.string,</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">ggplot2 =</span> <span class="fu">as.character</span>(utils<span class="sc">::</span><span class="fu">packageVersion</span>(<span class="st">"ggplot2"</span>)),</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">platform =</span> R.version<span class="sc">$</span>platform)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                             R                        ggplot2 
"R version 4.5.3 (2026-03-11)"                        "4.0.2" 
                      platform 
      "aarch64-apple-darwin20" </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Mẹo thực hành">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mẹo thực hành
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Trong RStudio hoặc Positron, tạo một <em>Project</em> cho mỗi dự án. Khi mở project, thư mục làm việc tự động là thư mục gốc, nên mọi đường dẫn tương đối đều đúng.</li>
<li>Thỉnh thoảng khởi động lại R (Session → Restart R) rồi chạy script từ đầu. Nếu script chỉ chạy được khi console còn “nhớ” một biến cũ, đó là lỗi cần sửa ngay.</li>
<li>Đặt tên tham số ngắn, không dấu, có quy ước (<code>p_</code> cho xác suất, <code>c_</code> cho chi phí); dùng cột <code>label_vi</code> để mô tả bằng tiếng Việt.</li>
<li>Chạy cả script bằng <code>Rscript code/ten-script.R</code> trong terminal. Đó là phép thử rằng script không phụ thuộc vào bất cứ thứ gì bạn đã làm bằng tay.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Lỗi thường gặp">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lỗi thường gặp
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Dùng <code>setwd("C:/Users/...")</code>.</strong> Đường dẫn tuyệt đối chỉ đúng trên máy bạn. Hãy dùng đường dẫn tương đối từ thư mục gốc của project.</li>
<li><strong>Sửa dữ liệu thô bằng Excel.</strong> Thao tác tay không để lại dấu vết. Mọi chỉnh sửa phải nằm trong mã; tệp gốc giữ nguyên.</li>
<li><strong>Gõ số vào văn bản.</strong> Dấu hiệu nhận biết: trong tệp <code>.qmd</code> có một con số kết quả không nằm trong mã R nội dòng.</li>
<li><strong>Nhầm thứ tự ưu tiên toán tử.</strong> <code>x %in% a + 0:4</code> được hiểu là <code>(x %in% a) + 0:4</code>. Khi viết kiểm tra, hãy thêm ngoặc: <code>x %in% (a + 0:4)</code>, rồi chạy thử kiểm tra trên một ví dụ đã biết đáp án để chắc rằng <code>stopifnot()</code> thực sự bắt được lỗi.</li>
</ul>
</div>
</div>
</section>
<section id="bài-tập" class="level2">
<h2 class="anchored" data-anchor-id="bài-tập">Bài tập</h2>
<p><strong>Bài tập 1 (dễ).</strong> Đếm số chủng theo loài vi khuẩn và bệnh viện. Ở mỗi bệnh viện, bao nhiêu phần trăm chủng lấy từ khoa hồi sức tích cực (ICU)?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>table()</code> đếm theo hai chiều. Trung bình của một vectơ logic chính là tỷ lệ phần tử <code>TRUE</code>, và <code>tapply()</code> tính trung bình đó cho từng bệnh viện.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 1: isolates per organism and hospital, and share of isolates from ICU</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(iso<span class="sc">$</span>organism, iso<span class="sc">$</span>hospital)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               
                   A    B    C
  A. baumannii   539  304  201
  E. coli       1047  655  410
  K. pneumoniae  432  289  203</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">tapply</span>(iso<span class="sc">$</span>ward <span class="sc">==</span> <span class="st">"ICU"</span>, iso<span class="sc">$</span>hospital, mean), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    A     B     C 
0.200 0.194 0.216 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p><strong>Bài tập 2 (vừa).</strong> Tăng gấp đôi quy mô bệnh viện C bằng cách sửa tham số trong R, không sửa CSV. Chạy lại mô phỏng với cùng seed và so sánh số chủng của bệnh viện C.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Sao chép danh sách tham số, đổi một phần tử, rồi chạy lại. Tệp CSV không thay đổi, nên phân tích cơ sở vẫn nguyên vẹn.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 2: double the size of hospital C, re-simulate, compare total isolates</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>p_big <span class="ot">&lt;-</span> p_sim</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>p_big<span class="sc">$</span>n_pat_c <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> p_sim<span class="sc">$</span>n_pat_c</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>iso_big <span class="ot">&lt;-</span> <span class="fu">simulate_isolates</span>(p_big, <span class="at">seed =</span> <span class="dv">2025</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">base =</span> <span class="fu">sum</span>(iso<span class="sc">$</span>hospital <span class="sc">==</span> <span class="st">"C"</span>), <span class="at">doubled =</span> <span class="fu">sum</span>(iso_big<span class="sc">$</span>hospital <span class="sc">==</span> <span class="st">"C"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   base doubled 
    814    1548 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p><strong>Bài tập 3 (khó hơn).</strong> Nạp tham số của mô hình ICU bằng <code>load_icu_params()</code>. Có bao nhiêu tham số được gắn một phân phối xác suất, bao nhiêu có nguồn và bao nhiêu là giá trị minh họa? Hai chi phí lấy từ bảng giá dùng chung nằm ở đâu, và vì sao không được chép chúng vào <code>params/icu_markov.csv</code>?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Bảng đầy đủ nằm trong thuộc tính <code>"table"</code> của kết quả.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 3: which ICU parameters are sourced and which illustrative, and which have a</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># probability distribution attached? load_icu_params() adds the two shared prices.</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>tab_icu <span class="ot">&lt;-</span> <span class="fu">attr</span>(<span class="fu">load_icu_params</span>(), <span class="st">"table"</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">dist =</span> tab_icu<span class="sc">$</span>dist, <span class="at">illustrative =</span> tab_icu<span class="sc">$</span>illustrative)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       illustrative
dist    FALSE TRUE
  beta      8    2
  fixed     0    5
  gamma     2    1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>tab_icu[tab_icu<span class="sc">$</span>name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"c_icu_day"</span>, <span class="st">"c_infection"</span>), <span class="fu">c</span>(<span class="st">"name"</span>, <span class="st">"value"</span>, <span class="st">"source"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   name   value                            source
c_icu_day     c_icu_day 1017300                     byt2024qd3220
c_infection c_infection 3801137 thainguyen2023thau; cuchi2024thau</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>n_icu_sourced <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">as.logical</span>(tab_icu<span class="sc">$</span>illustrative))</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>n_icu_illustrative <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">as.logical</span>(tab_icu<span class="sc">$</span>illustrative))</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The lesson text lists the illustrative ones: check the list is still right</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">setequal</span>(tab_icu<span class="sc">$</span>name[<span class="fu">as.logical</span>(tab_icu<span class="sc">$</span>illustrative)],</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">c</span>(<span class="st">"n_days"</span>, <span class="st">"outbreak_rr"</span>, <span class="st">"outbreak_start"</span>, <span class="st">"outbreak_end"</span>, <span class="st">"c_contact"</span>,</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"cost_gamma_shape"</span>, <span class="st">"p_i_c"</span>, <span class="st">"p_i_x"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mô hình ICU có 10 tham số có nguồn và 8 giá trị minh họa (số ngày theo dõi, ba tham số của đợt bùng phát, chi phí phòng ngừa tiếp xúc, độ rộng phân phối của chi phí, và hai xác suất chia lối ra của người đang nhiễm khuẩn). Giá ngày giường và giá thuốc nằm trong <code>_shared/params/vn_prices.csv</code>; <code>load_icu_params()</code> đọc chúng qua <code>vn_prices()</code>. Nếu chép vào CSV của module, khi bảng giá chung được cập nhật, module này sẽ âm thầm dùng giá cũ, và hai module có thể báo hai giá khác nhau cho cùng một ngày giường. Ngay cả khi mọi tham số có nguồn, mô hình vẫn đơn giản hóa thực tế (một ICU chung, không phân tầng bệnh nặng), nên kết quả là con số gần đúng để học, chưa đủ để ra quyết định cho một bệnh viện cụ thể.</p>
</div>
</div>
</div>
</section>
<section id="tài-liệu-tham-khảo" class="level2">
<h2 class="anchored" data-anchor-id="tài-liệu-tham-khảo">Tài liệu tham khảo</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-alaridescudero2019need" class="csl-entry" role="listitem">
Alarid-Escudero, Fernando, Eline M. Krijkamp, Petros Pechlivanoglou, Hawre Jalal, Szu-Yu Zoe Kao, Alan Yang, và Eva A. Enns. 2019. <span>“A need for change! <span>A</span> coding framework for improving transparency in decision modeling”</span>. <em>PharmacoEconomics</em> 37 (11): 1329–39. <a href="https://doi.org/10.1007/s40273-019-00837-x">https://doi.org/10.1007/s40273-019-00837-x</a>.
</div>
<div id="ref-cuchi2024thau" class="csl-entry" role="listitem">
Bệnh viện Đa khoa khu vực Củ Chi. 2024. <span>“Danh mục giá thầu thuốc bệnh viện 2024 (Lần 2)”</span>. 2024. <a href="https://bvdkkvcuchi.vn/wp-content/uploads/2024/12/DANH-MUC-THUOC-DANG-WEBSITE-BV-nam-2024-lan-2.pdf">https://bvdkkvcuchi.vn/wp-content/uploads/2024/12/DANH-MUC-THUOC-DANG-WEBSITE-BV-nam-2024-lan-2.pdf</a>.
</div>
<div id="ref-thainguyen2023thau" class="csl-entry" role="listitem">
Bệnh viện Trung ương Thái Nguyên. 2023. <span>“Danh mục thuốc trúng thầu tại Bệnh viện Trung ương Thái Nguyên (áp dụng từ ngày 17/10/2023 theo Quyết định số 1580/<span>QĐ-BVTWTN</span>)”</span>. 17 Tháng Mười 2023. <a href="https://bvdktuthainguyen.gov.vn/uploads/media/tai%20lieu/danh%20muc%20thuoc/thuoc%202022-2023/DM%20thu%E1%BB%91c%20tr%C3%BAng%20th%E1%BA%A7u%202023%20BVTW%20TN%20(1).xlsx">https://bvdktuthainguyen.gov.vn/uploads/media/tai%20lieu/danh%20muc%20thuoc/thuoc%202022-2023/DM%20thu%E1%BB%91c%20tr%C3%BAng%20th%E1%BA%A7u%202023%20BVTW%20TN%20(1).xlsx</a>.
</div>
<div id="ref-chinhphu2025nd293" class="csl-entry" role="listitem">
Chính phủ. 2025. <span>“Nghị định 293/2025/<span>NĐ-CP</span> quy định mức lương tối thiểu đối với người lao động làm việc theo hợp đồng lao động (hiệu lực từ 1/1/2026)”</span>. 2025. <a href="https://hatinh.gov.vn/vi/bai-viet/tang-luong-toi-thieu-vung-tu-112026">https://hatinh.gov.vn/vi/bai-viet/tang-luong-toi-thieu-vung-tu-112026</a>.
</div>
<div id="ref-incerti2019r" class="csl-entry" role="listitem">
Incerti, Devin, Howard Thom, Gianluca Baio, và Jeroen P. Jansen. 2019. <span>“R you still using <span>Excel</span>? <span>The</span> advantages of modern software tools for health technology assessment”</span>. <em>Value in Health</em> 22 (5): 575–79. <a href="https://doi.org/10.1016/j.jval.2019.01.003">https://doi.org/10.1016/j.jval.2019.01.003</a>.
</div>
<div id="ref-posit_quarto" class="csl-entry" role="listitem">
Posit. không ngày. <span>“Quarto: an open-source scientific and technical publishing system”</span>. Truy cập 8 Tháng Mười 2026. <a href="https://quarto.org/">https://quarto.org/</a>.
</div>
<div id="ref-rcoreteam_r" class="csl-entry" role="listitem">
R Core Team. không ngày. <span>“The <span>R</span> Project for Statistical Computing”</span>. R Foundation for Statistical Computing. Truy cập 8 Tháng Mười 2026. <a href="https://www.r-project.org/">https://www.r-project.org/</a>.
</div>
<div id="ref-sandve2013ten" class="csl-entry" role="listitem">
Sandve, Geir Kjetil, Anton Nekrutenko, James Taylor, và Eivind Hovig. 2013. <span>“Ten simple rules for reproducible computational research”</span>. <em>PLoS Computational Biology</em> 9 (10): e1003285. <a href="https://doi.org/10.1371/journal.pcbi.1003285">https://doi.org/10.1371/journal.pcbi.1003285</a>.
</div>
<div id="ref-tran2019high" class="csl-entry" role="listitem">
Tran, Dien M., Mattias Larsson, Linus Olson, Ngoc T. B. Hoang, Ngai K. Le, Dung T. K. Khu, và c.s. 2019. <span>“High prevalence of colonisation with carbapenem-resistant <span>Enterobacteriaceae</span> among patients admitted to <span>Vietnamese</span> hospitals: risk factors and burden of disease”</span>. <em>Journal of Infection</em> 79 (2): 115–22. <a href="https://doi.org/10.1016/j.jinf.2019.05.013">https://doi.org/10.1016/j.jinf.2019.05.013</a>.
</div>
<div id="ref-ushey_renv" class="csl-entry" role="listitem">
Ushey, Kevin, và Hadley Wickham. không ngày. <span>“renv: project environments for <span>R</span>”</span>. Truy cập 8 Tháng Mười 2026. <a href="https://rstudio.github.io/renv/">https://rstudio.github.io/renv/</a>.
</div>
<div id="ref-wilson2017good" class="csl-entry" role="listitem">
Wilson, Greg, Jennifer Bryan, Karen Cranston, Justin Kitzes, Lex Nederbragt, và Tracy K. Teal. 2017. <span>“Good enough practices in scientific computing”</span>. <em>PLoS Computational Biology</em> 13 (6): e1005510. <a href="https://doi.org/10.1371/journal.pcbi.1005510">https://doi.org/10.1371/journal.pcbi.1005510</a>.
</div>
</div>
<div class="video-script">
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kịch bản video (~12 phút)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Slide</th>
<th>Lời giảng chính</th>
<th>Hình/Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Vì sao tái lập</td>
<td>Mô hình là lập luận hỗ trợ quyết định; ai cũng phải chạy lại được; bảng tính khó kiểm tra</td>
<td>Trích Incerti 2019</td>
</tr>
<tr class="even">
<td>2</td>
<td>R và IDE</td>
<td>Console để thử, script để chạy thật; cài gói một lần, nạp mỗi phiên</td>
<td>Màn hình RStudio/Positron</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Cấu trúc dự án</td>
<td>Bốn thư mục; ba lớp đầu vào, mô hình, phân tích</td>
<td>Bảng thư mục, sơ đồ Mermaid</td>
</tr>
<tr class="even">
<td>4</td>
<td>Chạy đúng thư mục</td>
<td><code>stop()</code> nếu thiếu <code>code/model.R</code>; <code>_shared/</code> đặt cạnh module; Project trong IDE</td>
<td><code>l01-setup</code>, <code>l01-check-wd</code></td>
</tr>
<tr class="odd">
<td>5</td>
<td>Bảng tham số</td>
<td>Một dòng một tham số; nguồn hoặc cờ minh họa; <code>_shared/</code> cho giá trị chung</td>
<td><code>l01-params</code></td>
</tr>
<tr class="even">
<td>6</td>
<td>Hàng rào an toàn và truy nguồn</td>
<td><code>read_params()</code> từ chối số liệu “thật” không có nguồn; tính lại xác suất mắc mới CRE từ 13% và 89%</td>
<td><code>l01-guardrail</code>, <code>l01-trace-source</code></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Dữ liệu do mã tạo</td>
<td>Mô phỏng rồi tạo tệp trích xuất có lỗi; dữ liệu thô chỉ đọc</td>
<td><code>l01-simulate</code>, <code>l01-save-raw</code></td>
</tr>
<tr class="even">
<td>8</td>
<td>Script và Quarto</td>
<td>Một nơi chứa mã; <code>read_chunk()</code> kéo đoạn mã vào bài</td>
<td>Nhãn <code>## ---- l01-setup ----</code></td>
</tr>
<tr class="odd">
<td>9</td>
<td>Mọi con số do mã tạo ra</td>
<td>Hai seed, hai con số khác nhau; số gõ tay sẽ lỗi thời</td>
<td><code>l01-every-number</code></td>
</tr>
<tr class="even">
<td>10</td>
<td>Ghi lại môi trường</td>
<td>Phiên bản R và gói; renv; seed</td>
<td><code>l01-session</code></td>
</tr>
<tr class="odd">
<td>11</td>
<td>Lỗi thường gặp</td>
<td><code>setwd()</code> tuyệt đối; sửa dữ liệu bằng Excel; thứ tự toán tử</td>
<td>Callout cảnh báo</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../kb/m00-r-foundations/index.html" class="pagination-link" aria-label="M00 · R cho mô hình kinh tế y tế">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">M00 · R cho mô hình kinh tế y tế</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../kb/m00-r-foundations/l02-vectors-matrices.html" class="pagination-link" aria-label="Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận">
        <span class="nav-page-text"><span class="chapter-title">Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>