<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực – Mô hình Kinh tế Y tế với R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../kb/m06-amr-economics/l02-attributable-los.html" rel="next">
<link href="../../kb/m06-amr-economics/index.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9e7f0c659d5fa2cace8548cb57964278.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c18d72663580ed8ca19ce2a2f99af51b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="mermaid-theme" content="neutral">
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=JetBrains+Mono:wght@400;600&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m06-amr-economics/index.html">M06 · Kinh tế học kháng kháng sinh (AMR)</a></li><li class="breadcrumb-item"><a href="../../kb/m06-amr-economics/l01-amr-burden.html"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Mô hình Kinh tế Y tế với R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lời mở đầu</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m00-r-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M00 · R cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l02-vectors-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l03-functions-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hàm, cấu trúc điều khiển, vòng lặp và vectơ hóa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l04-data-frames.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Data frame — nhập, làm sạch, tóm tắt và chuyển dạng dữ liệu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l05-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Biểu đồ với ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l06-randomness-monte-carlo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 6: Ngẫu nhiên, mô phỏng Monte Carlo và sai số Monte Carlo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m01-ee-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M01 · Nền tảng đánh giá kinh tế và cây quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l01-evaluation-types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại đánh giá kinh tế, quan điểm, khung thời gian và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l02-health-outcomes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Năm sống, QALY và DALY</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l03-decision-rules.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l04-thresholds.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l05-decision-tree.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Xây cây quyết định từ đầu trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m02-cohort-markov/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l01-state-transition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao cần mô hình chuyển trạng thái</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l03-cohort-trace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l04-time-dependence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Phụ thuộc thời gian: lão hóa, trạng thái đường hầm và mảng 3 chiều</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l05-results-verification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị gắn với lần chuyển, đường biên hiệu quả và xác minh mô hình</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m03-uncertainty-voi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l01-deterministic-sa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại bất định và phân tích độ nhạy tất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l02-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Chọn phân phối cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l03-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích độ nhạy xác suất (PSA) trong R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l05-voi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m04-microsimulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M04 · Mô phỏng vi mô (microsimulation)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l01-why-microsimulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l02-microsim-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l03-vectorisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vectơ hóa theo cá thể và đo hiệu năng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l04-parallel-rcpp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tính toán song song và Rcpp cho vòng lặp nóng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l05-mc-error-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bao nhiêu cá thể là đủ? Sai số Monte Carlo, PSA và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m05-dynamic-transmission/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M05 · Mô hình lây truyền động</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l01-static-vs-dynamic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Mô hình tĩnh và mô hình lây truyền động</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l02-sir-seir-desolve.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình SIR và SEIR trong R với deSolve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l03-vaccination-herd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Tiêm chủng, hiệu quả trực tiếp và gián tiếp</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l04-dengue-host-vector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Mô hình vật chủ–véc tơ cho sốt xuất huyết Dengue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l05-dynamic-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế với mô hình lây truyền động</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m06-amr-economics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M06 · Kinh tế học kháng kháng sinh (AMR)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l01-amr-burden.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l02-attributable-los.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l03-ward-transmission.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Mô hình lây truyền CRE trong khoa hồi sức</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l04-two-strain-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m07-survival-psm/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M07 · Phân tích sống còn cho mô hình quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l01-survival-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ôn tập phân tích sống còn cho người làm mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l02-parametric-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình sống còn tham số với flexsurv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l03-extrapolation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Ngoại suy sống còn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l04-reconstruct-ipd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tái tạo dữ liệu cá thể từ đường KM đã công bố và dùng HR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l05-partitioned-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Mô hình sống còn phân vùng trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m08-calibration/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M08 · Hiệu chuẩn mô hình (calibration)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l01-why-calibrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l02-search-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l03-bayes-sir.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hiệu chuẩn Bayes và thuật toán SIR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l04-psa-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đưa kết quả hiệu chuẩn vào PSA, thẩm định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m09-inputs-vietnam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l01-costing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ước tính chi phí cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l05-decision-context.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bối cảnh ra quyết định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m10-policy-bia-equity/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m11-software-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l01-code-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Cấu trúc mã cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l02-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Xác minh và kiểm thử mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l03-version-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quản lý phiên bản với Git và tái lập môi trường với renv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l04-r-package.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đóng gói mô hình thành gói R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l05-shiny-living.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Ứng dụng Shiny và mô hình “sống”</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bảng thuật ngữ Anh–Việt</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../references.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tài liệu tham khảo</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Trong bài</h2>
   
  <ul class="collapse">
  <li><a href="#mục-tiêu-học-tập" id="toc-mục-tiêu-học-tập" class="nav-link active" data-scroll-target="#mục-tiêu-học-tập">Mục tiêu học tập</a></li>
  <li><a href="#ý-chính" id="toc-ý-chính" class="nav-link" data-scroll-target="#ý-chính">Ý chính</a></li>
  <li><a href="#nội-dung" id="toc-nội-dung" class="nav-link" data-scroll-target="#nội-dung">Nội dung</a></li>
  <li><a href="#thực-hành" id="toc-thực-hành" class="nav-link" data-scroll-target="#thực-hành">Thực hành</a></li>
  <li><a href="#bài-tập" id="toc-bài-tập" class="nav-link" data-scroll-target="#bài-tập">Bài tập</a></li>
  <li><a href="#tài-liệu-tham-khảo" id="toc-tài-liệu-tham-khảo" class="nav-link" data-scroll-target="#tài-liệu-tham-khảo">Tài liệu tham khảo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m06-amr-economics/index.html">M06 · Kinh tế học kháng kháng sinh (AMR)</a></li><li class="breadcrumb-item"><a href="../../kb/m06-amr-economics/l01-amr-burden.html"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></h1>
<p class="subtitle lead">Phân biệt gánh nặng liên quan với gánh nặng quy thuộc, rồi tính cả hai bằng R cho một bệnh viện</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled" title="Vì sao bạn nên quan tâm?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vì sao bạn nên quan tâm?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Một người bệnh 61 tuổi nằm ICU của một bệnh viện hạng đặc biệt, cấy máu mọc <em>Klebsiella pneumoniae</em> kháng carbapenem. Đây không còn là chuyện hiếm: trong một khảo sát toàn quốc công bố năm 2025 ở 324 bệnh viện, 37% chủng <em>K. pneumoniae</em> được báo cáo đã kháng carbapenem <span class="citation" data-cites="larsson2025burden">(<a href="#ref-larsson2025burden" role="doc-biblioref">Larsson và c.s. 2025</a>)</span>. Một ngày colistin phối hợp meropenem liều cao tốn khoảng 3.96 triệu VNĐ theo giá trúng thầu (giá 2025), bằng 75% lương tối thiểu một tháng ở vùng I, hay 99 bát phở; cả đợt 14 ngày là khoảng 55 triệu VNĐ. Nhưng khi ban giám đốc hỏi “CRE tốn của bệnh viện bao nhiêu”, phần nào trong số đó thật sự <em>do kháng thuốc</em>? Bài này giúp bạn chọn đúng kịch bản phản thực trước khi đưa một con số gánh nặng lên bàn họp.</p>
</div>
</div>
<section id="mục-tiêu-học-tập" class="level2">
<h2 class="anchored" data-anchor-id="mục-tiêu-học-tập">Mục tiêu học tập</h2>
<p>Sau bài này, bạn có thể:</p>
<ol type="1">
<li>Giải thích vì sao kháng kháng sinh (antimicrobial resistance, AMR) là một ngoại ứng tiêu cực, và điều đó làm lệch kết quả đánh giá kinh tế ra sao.</li>
<li>Phân biệt gánh nặng liên quan (associated burden) với gánh nặng quy thuộc (attributable burden), và chọn kịch bản phản thực (counterfactual) đúng với câu hỏi chính sách.</li>
<li>Tính số tử vong, ngày giường, chi phí và số năm sống mất đi do nhiễm khuẩn Enterobacterales kháng carbapenem (carbapenem-resistant Enterobacterales, CRE) ở một bệnh viện theo cả hai kịch bản phản thực bằng R.</li>
<li>Ước tính chi phí xã hội của một liệu trình carbapenem khi cộng thêm chi phí ngoại ứng.</li>
</ol>
</section>
<section id="ý-chính" class="level2">
<h2 class="anchored" data-anchor-id="ý-chính">Ý chính</h2>
<ul>
<li>Mỗi liệu trình kháng sinh giúp người bệnh hôm nay nhưng làm giảm hiệu quả của thuốc cho người bệnh ngày mai. Người kê đơn không trả phần chi phí này, nên đó là <strong>ngoại ứng</strong> (externality).</li>
<li>Mọi con số gánh nặng AMR trả lời câu hỏi <em>so với điều gì?</em> <strong>Gánh nặng liên quan</strong> so với <em>không nhiễm khuẩn</em>; <strong>gánh nặng quy thuộc</strong> so với <em>nhiễm khuẩn do chủng nhạy cảm</em>. Số liên quan luôn lớn hơn vì gồm cả phần do bản thân nhiễm khuẩn.</li>
<li>Chọn kịch bản phản thực theo can thiệp. Thuốc mới diệt được CRE biến nhiễm khuẩn kháng thành nhiễm khuẩn “như nhạy cảm”: dùng gánh nặng quy thuộc. Kiểm soát nhiễm khuẩn ngăn được ca nhiễm: dùng gánh nặng liên quan.</li>
<li>Chi phí do kháng thuốc đến từ ngày nằm viện tăng thêm <span class="citation" data-cites="stewardson2016health">(<a href="#ref-stewardson2016health" role="doc-biblioref">Stewardson và c.s. 2016</a>)</span> và kháng sinh dự trữ. Với giá ở Việt Nam, một ngày phác đồ có colistin đắt gấp 25 lần một ngày meropenem generic và gấp 3.9 lần giá một ngày giường ICU, nên <em>giá thuốc</em> chiếm phần lớn chi phí quy thuộc (97% mỗi ca trong mô hình của bài).</li>
<li>Đánh giá kinh tế bỏ qua ngoại ứng sẽ đánh giá thấp các can thiệp giúp giảm dùng kháng sinh.</li>
</ul>
</section>
<section id="nội-dung" class="level2">
<h2 class="anchored" data-anchor-id="nội-dung">Nội dung</h2>
<section id="kháng-thuốc-là-một-ngoại-ứng" class="level3">
<h3 class="anchored" data-anchor-id="kháng-thuốc-là-một-ngoại-ứng">Kháng thuốc là một ngoại ứng</h3>
<p>Hiệu quả của một nhóm kháng sinh là một nguồn tài nguyên chung. Mỗi lần dùng thuốc, chủng nhạy bị diệt và chủng đề kháng có thêm chỗ phát triển (áp lực chọn lọc, Bài 4). Người bệnh hưởng trọn lợi ích của liệu trình, còn chi phí kháng thuốc thì dàn trải cho người bệnh khác, ở thời điểm khác. Khi chi phí không nằm trong giá, xã hội dùng kháng sinh nhiều hơn mức tối ưu <span class="citation" data-cites="coast1996superbugs laxminarayan2013antibiotic">(<a href="#ref-coast1996superbugs" role="doc-biblioref">Coast, Smith, và Millar 1996</a>; <a href="#ref-laxminarayan2013antibiotic" role="doc-biblioref">Laxminarayan và c.s. 2013</a>)</span>.</p>
<p>Về hình thức, chi phí xã hội của một liệu trình là:</p>
<p><span class="math display">\[
C_{\text{xã hội}} = C_{\text{riêng}} + C_{\text{ngoại ứng}} = d \cdot c_{\text{thuốc}} + d \cdot n_{SU} \cdot c_{AMR},
\]</span></p>
<p>trong đó <span class="math inline">\(d\)</span> là số ngày điều trị, <span class="math inline">\(n_{SU}\)</span> là số đơn vị chuẩn (standard unit, SU) mỗi ngày, và <span class="math inline">\(c_{AMR}\)</span> là chi phí kháng thuốc gây ra trên mỗi SU. Đánh giá kinh tế thông thường chỉ tính <span class="math inline">\(C_{\text{riêng}}\)</span>. Shrestha và cộng sự ước tính <span class="math inline">\(c_{AMR}\)</span> theo nhóm thuốc; trong bối cảnh Thái Lan, giá trị này nằm trong khoảng US$0.1 đến US$0.7 mỗi SU, và trong bối cảnh Mỹ, ước tính riêng cho carbapenem là US$0.1 mỗi SU (các tác giả không nêu năm giá trong tóm tắt) <span class="citation" data-cites="shrestha2018enumerating">(<a href="#ref-shrestha2018enumerating" role="doc-biblioref">Shrestha và c.s. 2018</a>)</span>. Bỏ qua phần này làm can thiệp giảm dùng kháng sinh (xét nghiệm nhanh, quản lý sử dụng kháng sinh) trông kém hấp dẫn hơn thực tế.</p>
</section>
<section id="gánh-nặng-liên-quan-hay-quy-thuộc" class="level3">
<h3 class="anchored" data-anchor-id="gánh-nặng-liên-quan-hay-quy-thuộc">Gánh nặng: liên quan hay quy thuộc?</h3>
<p>Nghiên cứu gánh nặng AMR toàn cầu dùng hai kịch bản phản thực cho cùng một bộ dữ liệu <span class="citation" data-cites="amrcollaborators2022global">(<a href="#ref-amrcollaborators2022global" role="doc-biblioref">Antimicrobial Resistance Collaborators 2022</a>)</span>. Năm 2019 có 4.95 triệu ca tử vong <em>liên quan</em> đến AMR do vi khuẩn. Trong số đó, 1.27 triệu ca <em>quy thuộc</em> AMR, tức khoảng 26%. Ước tính cho năm 2021 cũng theo cấu trúc đó: 4.71 và 1.14 triệu <span class="citation" data-cites="gbdamr2024global">(<a href="#ref-gbdamr2024global" role="doc-biblioref">GBD 2021 Antimicrobial Resistance Collaborators 2024</a>)</span>. Số liên quan gấp 3.9 lần số quy thuộc, nhưng không con số nào sai. Chúng trả lời hai câu hỏi khác nhau.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>flowchart LR</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  A["Người bệnh nhiễm khuẩn CRE&lt;br/&gt;(thế giới thực)"] --&gt; B{"Nếu không có kháng thuốc thì sao?"}</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  B --&gt;|"Phản thực 1: nhiễm chủng nhạy cảm"| C["Gánh nặng QUY THUỘC&lt;br/&gt;= CRE trừ nhiễm khuẩn nhạy"]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  B --&gt;|"Phản thực 2: không nhiễm khuẩn"| D["Gánh nặng LIÊN QUAN&lt;br/&gt;= CRE trừ không nhiễm khuẩn"]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  A["Người bệnh nhiễm khuẩn CRE&lt;br/&gt;(thế giới thực)"] --&gt; B{"Nếu không có kháng thuốc thì sao?"}
  B --&gt;|"Phản thực 1: nhiễm chủng nhạy cảm"| C["Gánh nặng QUY THUỘC&lt;br/&gt;= CRE trừ nhiễm khuẩn nhạy"]
  B --&gt;|"Phản thực 2: không nhiễm khuẩn"| D["Gánh nặng LIÊN QUAN&lt;br/&gt;= CRE trừ không nhiễm khuẩn"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Gánh nặng nên được đo bằng cả tử vong lẫn thời gian nằm viện <span class="citation" data-cites="dekraker2011mortality">(<a href="#ref-dekraker2011mortality" role="doc-biblioref">de Kraker và c.s. 2011</a>)</span>. Trong dữ liệu nhiều bệnh viện châu Âu, nhiễm khuẩn huyết do Enterobacteriaceae kháng cephalosporin thế hệ 3 làm người bệnh nằm viện thêm 9.3 ngày so với không nhiễm khuẩn huyết, chủng nhạy làm nằm thêm 5.9 ngày, và phần quy thuộc đề kháng (kháng so với nhạy) là 4.9 ngày (KTC 95%: 1.1–8.7) <span class="citation" data-cites="stewardson2016health">(<a href="#ref-stewardson2016health" role="doc-biblioref">Stewardson và c.s. 2016</a>)</span>. Đây là ước tính đã điều chỉnh cho một người bệnh tham chiếu, nên khoảng tin cậy của hai số đầu hẹp bất thường. Số chưa điều chỉnh, được các tác giả dùng để tính chi phí, là 7.9, 4.4 và 3.5 ngày. Các số đã điều chỉnh không cộng được (5.9 + 4.9 = 10.8, không bằng 9.3) vì so sánh kháng-nhạy nằm trong một mô hình riêng; số chưa điều chỉnh thì gần cộng được (7.9 so với 7.9). Đẳng thức phân tách ở phần sau chỉ đúng trong một mô hình và một quần thể.</p>
<p>Với CRE, tổng quan của Falagas và cộng sự định nghĩa tử vong quy thuộc là <em>chênh lệch</em> tỷ lệ tử vong do mọi nguyên nhân giữa nhiễm khuẩn kháng và nhạy carbapenem. Chênh lệch này nằm trong khoảng 26 đến 44 điểm phần trăm ở 7 nghiên cứu, và là -4 và -3 điểm phần trăm ở hai nghiên cứu còn lại. Tám trong chín nghiên cứu là hồi cứu và số liệu gộp chưa điều chỉnh; tỷ số nguy cơ tử vong gộp là 2.05 (KTC 95%: 1.56–2.69) <span class="citation" data-cites="falagas2014deaths">(<a href="#ref-falagas2014deaths" role="doc-biblioref">Falagas và c.s. 2014</a>)</span>.</p>
<p>Ở Việt Nam, mạng giám sát VINARES ghi nhận 16% chủng <em>K. pneumoniae</em> kháng imipenem giai đoạn 2012–2013 <span class="citation" data-cites="vu2019antimicrobial">(<a href="#ref-vu2019antimicrobial" role="doc-biblioref">Vu và c.s. 2019</a>)</span>. Một khảo sát trực tuyến qua Bộ Y tế, công bố năm 2025, ở 324 bệnh viện từ tuyến huyện đến trung ương, ghi nhận 37% ở <em>K. pneumoniae</em> và 11% ở <em>E. coli</em>. Người nhiễm CRE có tỷ lệ tử vong thô 31.7%, so với 20.2% khi chủng nhạy carbapenem, và nằm viện 10.4 so với 8.9 ngày <span class="citation" data-cites="larsson2025burden">(<a href="#ref-larsson2025burden" role="doc-biblioref">Larsson và c.s. 2025</a>)</span>. Chênh lệch 11.5 điểm phần trăm là một ước tính quy thuộc thô: chưa điều chỉnh mức độ nặng, và thời gian nằm viện chưa xử lý sai lệch phụ thuộc thời gian (Bài 2). Khảo sát cũng báo cáo chi phí (1,025 so với 773), nhưng tóm tắt không nêu đơn vị tiền tệ, năm giá hay thành phần chi phí, nên bài không dùng hai số này. Tại bốn ICU ở Việt Nam, chi phí ICU trung vị của viêm hô hấp liên quan thở máy do Gram âm kháng carbapenem là US$6,053, so với US$3,131 khi vi khuẩn nhạy carbapenem <span class="citation" data-cites="phu2017ventilator">(<a href="#ref-phu2017ventilator" role="doc-biblioref">Phu và c.s. 2017</a>)</span>; nhóm này gồm cả <em>A. baumannii</em> và <em>P. aeruginosa</em>, nên không phải ước tính riêng cho CRE.</p>
</section>
<section id="kịch-bản-phản-thực-phải-khớp-với-can-thiệp" class="level3">
<h3 class="anchored" data-anchor-id="kịch-bản-phản-thực-phải-khớp-với-can-thiệp">Kịch bản phản thực phải khớp với can thiệp</h3>
<p>Quy tắc đơn giản: hỏi <em>can thiệp làm thay đổi điều gì?</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Can thiệp</th>
<th>Thế giới khi có can thiệp</th>
<th>Kịch bản phản thực phù hợp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Kháng sinh mới hoặc xét nghiệm nhanh giúp điều trị đúng sớm</td>
<td>Ca nhiễm vẫn xảy ra nhưng diễn tiến như nhiễm khuẩn nhạy</td>
<td>Quy thuộc (kháng so với nhạy)</td>
</tr>
<tr class="even">
<td>Kiểm soát nhiễm khuẩn, sàng lọc và cách ly</td>
<td>Ca nhiễm không xảy ra</td>
<td>Liên quan (kháng so với không nhiễm)</td>
</tr>
<tr class="odd">
<td>Quản lý sử dụng kháng sinh</td>
<td>Ít chủng kháng hơn; một phần ca nhiễm thành nhạy, một phần không xảy ra</td>
<td>Kết hợp, cần mô hình động (Bài 4, 5)</td>
</tr>
</tbody>
</table>
<p>Chủng kháng <em>thay thế</em> chủng nhạy hay <em>cộng thêm</em> vào? Nếu thay thế, phản thực “nhạy cảm” hợp lý; nếu cộng thêm, một phần ca kháng sẽ không tồn tại khi không có kháng thuốc. Với nhiễm khuẩn huyết, các tác giả châu Âu cho rằng chủng không nhạy nhiều khả năng cộng thêm hơn là thay thế chủng nhạy <span class="citation" data-cites="stewardson2016health">(<a href="#ref-stewardson2016health" role="doc-biblioref">Stewardson và c.s. 2016</a>)</span>; thực tế có thể nằm giữa hai cực. Vì vậy hãy báo cáo cả hai số đo, như các nghiên cứu gánh nặng toàn cầu <span class="citation" data-cites="amrcollaborators2022global gbdamr2024global">(<a href="#ref-amrcollaborators2022global" role="doc-biblioref">Antimicrobial Resistance Collaborators 2022</a>; <a href="#ref-gbdamr2024global" role="doc-biblioref">GBD 2021 Antimicrobial Resistance Collaborators 2024</a>)</span>. Kết quả còn phụ thuộc vào kết cục, quan điểm và phương pháp của từng nghiên cứu <span class="citation" data-cites="naylor2018estimating">(<a href="#ref-naylor2018estimating" role="doc-biblioref">Naylor và c.s. 2018</a>)</span>.</p>
</section>
<section id="tính-cho-một-bệnh-viện" class="level3">
<h3 class="anchored" data-anchor-id="tính-cho-một-bệnh-viện">Tính cho một bệnh viện</h3>
<p>Ta dùng một bệnh viện hạng đặc biệt với 300 ca nhiễm khuẩn CRE mỗi năm (giá trị minh họa; chưa có số ca công khai theo bệnh viện). Số đo vượt trội mỗi ca được lấy từ mô hình đa trạng thái mà Bài 2 sẽ mô phỏng. Với nguy cơ tức thời (hazard) không đổi, người bệnh ở một trạng thái có tổng nguy cơ rời trạng thái <span class="math inline">\(h_\bullet\)</span> sẽ nằm thêm trung bình <span class="math inline">\(1/h_\bullet\)</span> ngày, và tử vong với xác suất <span class="math inline">\(h_{\text{tử vong}}/h_\bullet\)</span>. Các nguy cơ tử vong sau nhiễm khuẩn được chọn để xác suất tử vong khớp số thô của khảo sát toàn quốc (31.7% sau nhiễm CRE, 20.2% sau nhiễm khuẩn nhạy); thời gian nằm viện và nhóm không nhiễm khuẩn là giá trị minh họa. Từ đó:</p>
<p><span class="math display">\[
\Delta_{\text{liên quan}} = g(R) - g(\varnothing), \qquad
\Delta_{\text{quy thuộc}} = g(R) - g(S), \qquad
\Delta_{\text{liên quan}} = \Delta_{\text{quy thuộc}} + \big[g(S) - g(\varnothing)\big],
\]</span></p>
<p>với <span class="math inline">\(g\)</span> là thời gian nằm viện còn lại hoặc xác suất tử vong sau sự kiện. Đẳng thức thứ ba cho thấy gánh nặng liên quan tách được thành phần do kháng thuốc và phần do bản thân nhiễm khuẩn. Trong mô hình, mỗi ca CRE làm tăng xác suất tử vong 24.3 điểm phần trăm so với không nhiễm khuẩn, nhưng chỉ 11.5 điểm phần trăm so với nhiễm khuẩn nhạy.</p>
<p>Số năm sống mất đi (YLL) của một ca tử vong lấy từ bảng sống WHO 2023 của Việt Nam (<code>vn_mx()</code>) ở tuổi 61, tuổi trung vị của người bệnh trong một điều tra nhiều ICU người lớn ở Việt Nam <span class="citation" data-cites="phu2016burden who2026lifetables">(<a href="#ref-phu2016burden" role="doc-biblioref">Phu và c.s. 2016</a>; <a href="#ref-who2026lifetables" role="doc-biblioref">World Health Organization 2026</a>)</span>, với tỷ suất tử vong nền nhân 2.0 lần cho người sống sót sau hồi sức (giá trị minh họa).</p>
<p>Chi phí bằng <em>lượng</em> nhân <em>giá</em>. Giá ngày giường là giá dịch vụ BHYT ở bệnh viện hạng đặc biệt: 1,017,300 VNĐ một ngày ICU và 327,100 VNĐ một ngày nội khoa loại 1 <span class="citation" data-cites="byt2024qd3220">(<a href="#ref-byt2024qd3220" role="doc-biblioref">Bộ Y tế 2024</a>)</span>; ta định giá phần 50% số ngày tăng thêm theo giá ICU và phần còn lại theo giá khoa thường (tỷ lệ này là minh họa). Kháng sinh dùng giá trúng thầu đưa về năm 2025: colistin phối hợp meropenem liều cao cho CRE, meropenem liều thường cho nhiễm khuẩn nhạy <span class="citation" data-cites="thainguyen2023thau cuchi2024thau">(<a href="#ref-thainguyen2023thau" role="doc-biblioref">Bệnh viện Trung ương Thái Nguyên 2023</a>; <a href="#ref-cuchi2024thau" role="doc-biblioref">Bệnh viện Đa khoa khu vực Củ Chi 2024</a>)</span>. Giá BHYT là giá thanh toán, không phải chi phí nguồn lực; và ngày giường giải phóng được dùng ngay cho người bệnh khác, nên giá trị của nó là chi phí cơ hội, không phải tiền mặt tiết kiệm được <span class="citation" data-cites="graves2010estimating stewardson2016health">(<a href="#ref-graves2010estimating" role="doc-biblioref">Graves và c.s. 2010</a>; <a href="#ref-stewardson2016health" role="doc-biblioref">Stewardson và c.s. 2016</a>)</span>.</p>
</section>
</section>
<section id="thực-hành" class="level2">
<h2 class="anchored" data-anchor-id="thực-hành">Thực hành</h2>
<p>Nạp các hàm dùng chung, giá trị dùng chung của khóa học (<code>vn_data.R</code>), hàm của module và mọi bảng tham số. Hàm <code>read_all_params()</code> ghép tham số của module với các dòng lấy từ <code>kb/_shared</code> (giá BHYT, giá thuốc, ngưỡng, chiết khấu). Kiểm tra: không có lỗi về tham số thiếu nguồn hay trùng tên.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vietnamese text in figures needs a UTF-8 locale (Rscript may start in the "C" locale)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">isTRUE</span>(<span class="fu">l10n_info</span>()[[<span class="st">"UTF-8"</span>]])) <span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_CTYPE"</span>, <span class="st">"en_US.UTF-8"</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/helpers.R"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/vn_data.R"</span>)   <span class="co"># course-wide values: vn_context(), vn_prices(), vn_mx(), inflate_vnd()</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"code/model.R"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">read_all_params</span>()      <span class="co"># module params/*.csv plus course-wide rows from ../_shared (file = "_shared")</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>H <span class="ot">&lt;-</span> <span class="fu">ms_hazards_true</span>(p)     <span class="co"># hazards of the hospital model (also used in Lesson 2)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Đặt hai số đo toàn cầu cạnh nhau. Kiểm tra: số quy thuộc nhỏ hơn số liên quan ở mọi năm.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Global burden (verified sources, see params/context.csv): associated vs attributable deaths</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>gram <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="fu">c</span>(<span class="dv">2019</span>, <span class="dv">2021</span>),</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">associated =</span> <span class="fu">c</span>(p<span class="sc">$</span>gram2019_assoc_deaths, p<span class="sc">$</span>gram2021_assoc_deaths),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">attributable =</span> <span class="fu">c</span>(p<span class="sc">$</span>gram2019_attr_deaths, p<span class="sc">$</span>gram2021_attr_deaths)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>gram<span class="sc">$</span>attr_share <span class="ot">&lt;-</span> gram<span class="sc">$</span>attributable <span class="sc">/</span> gram<span class="sc">$</span>associated</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>gram</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  year associated attributable attr_share
1 2019    4950000      1270000  0.2565657
2 2021    4710000      1140000  0.2420382</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(gram<span class="sc">$</span>attributable <span class="sc">&lt;</span> gram<span class="sc">$</span>associated))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>attr_share_2019 <span class="ot">&lt;-</span> gram<span class="sc">$</span>attr_share[gram<span class="sc">$</span>year <span class="sc">==</span> <span class="dv">2019</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Tóm tắt ba “thế giới” của cùng một người bệnh: thời gian nằm viện còn lại và xác suất tử vong sau sự kiện. Kiểm tra: xác suất trong đoạn 0–1; nhiễm CRE làm nằm viện lâu hơn nhiễm khuẩn nhạy; công thức đóng khớp với một mô phỏng lớn; và xác suất tử vong vẫn khớp số của khảo sát toàn quốc.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Three counterfactual worlds for the same patient, from the hazards of the hospital model:</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># remaining stay (days) and probability of dying in hospital after the event</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>states <span class="ot">&lt;-</span> <span class="fu">ms_state_summary</span>(H)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>states<span class="sc">$</span>state_vi <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Không nhiễm khuẩn"</span>, <span class="st">"Nhiễm khuẩn nhạy (CSE)"</span>, <span class="st">"Nhiễm khuẩn kháng (CRE)"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>states[, <span class="fu">c</span>(<span class="st">"state_vi"</span>, <span class="st">"remaining_los"</span>, <span class="st">"p_death"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 state_vi remaining_los    p_death
1       Không nhiễm khuẩn      9.259259 0.07407407
2  Nhiễm khuẩn nhạy (CSE)     14.285714 0.20200000
3 Nhiễm khuẩn kháng (CRE)     16.666667 0.31666667</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(states<span class="sc">$</span>p_death <span class="sc">&gt;=</span> <span class="dv">0</span>), <span class="fu">all</span>(states<span class="sc">$</span>p_death <span class="sc">&lt;=</span> <span class="dv">1</span>),</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>          states<span class="sc">$</span>remaining_los[<span class="dv">3</span>] <span class="sc">&gt;</span> states<span class="sc">$</span>remaining_los[<span class="dv">2</span>])</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Independent check of the closed forms: simulate 200,000 admissions without censoring and</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># compare the death proportion in each group, and the stay after infection, with the formulas</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">101</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>p_chk <span class="ot">&lt;-</span> p</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>p_chk<span class="sc">$</span>max_follow <span class="ot">&lt;-</span> <span class="fl">1e6</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>d_chk <span class="ot">&lt;-</span> <span class="fu">simulate_admissions</span>(p_chk, <span class="dv">200000</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>sim_death <span class="ot">&lt;-</span> <span class="fu">tapply</span>(d_chk<span class="sc">$</span>outcome <span class="sc">==</span> <span class="st">"Dead"</span>, d_chk<span class="sc">$</span>inf_type, mean)[<span class="fu">c</span>(<span class="st">"none"</span>, <span class="st">"S"</span>, <span class="st">"R"</span>)]</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>after <span class="ot">&lt;-</span> d_chk<span class="sc">$</span>los <span class="sc">-</span> d_chk<span class="sc">$</span>t_inf</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>sim_after <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">S =</span> <span class="fu">mean</span>(after[d_chk<span class="sc">$</span>inf_type <span class="sc">==</span> <span class="st">"S"</span>]), <span class="at">R =</span> <span class="fu">mean</span>(after[d_chk<span class="sc">$</span>inf_type <span class="sc">==</span> <span class="st">"R"</span>]))</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">rbind</span>(<span class="at">formula_death =</span> states<span class="sc">$</span>p_death, <span class="at">simulated_death =</span> sim_death), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 none     S     R
formula_death   0.074 0.202 0.317
simulated_death 0.074 0.202 0.317</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">rbind</span>(<span class="at">formula_stay_after =</span> states<span class="sc">$</span>remaining_los[<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>], <span class="at">simulated_stay_after =</span> sim_after), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         S     R
formula_stay_after   14.29 16.67
simulated_stay_after 14.36 16.45</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(sim_death <span class="sc">-</span> states<span class="sc">$</span>p_death) <span class="sc">&lt;</span> <span class="fl">0.02</span>),</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(<span class="fu">abs</span>(sim_after <span class="sc">-</span> states<span class="sc">$</span>remaining_los[<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>]) <span class="sc">&lt;</span> <span class="dv">1</span>))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The death probabilities after infection were chosen to reproduce the crude mortality of the</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Vietnamese national hospital survey (params/los_sim.csv); check that they still do</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(states<span class="sc">$</span>p_death[<span class="dv">2</span>] <span class="sc">-</span> p<span class="sc">$</span>larsson_mort_cse) <span class="sc">&lt;</span> <span class="fl">0.005</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>          <span class="fu">abs</span>(states<span class="sc">$</span>p_death[<span class="dv">3</span>] <span class="sc">-</span> p<span class="sc">$</span>larsson_mort_cre) <span class="sc">&lt;</span> <span class="fl">0.005</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Đoạn mã sau tính số đo vượt trội cho mỗi ca, kiểm tra đẳng thức phân tách ở trên, rồi đối chiếu với Falagas và cộng sự trên hai thang: chênh lệch tuyệt đối (điểm phần trăm) và tỷ số nguy cơ. Kiểm tra: hai dòng cuối cho biết mô hình nằm trong hay ngoài từng khoảng.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Excess per CRE infection under each counterfactual</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>ex <span class="ot">&lt;-</span> <span class="fu">excess_measures</span>(H)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(ex, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  los_R_none   los_S_none      los_R_S death_R_none death_S_none    death_R_S 
       7.407        5.026        2.381        0.243        0.128        0.115 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The two comparisons are linked: (R vs none) = (R vs S) + (S vs none). This is algebra,</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># so the check only guards against indexing typos; the simulation check above tests the formulas.</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(ex[[<span class="st">"los_R_none"</span>]] <span class="sc">-</span> (ex[[<span class="st">"los_R_S"</span>]] <span class="sc">+</span> ex[[<span class="st">"los_S_none"</span>]])) <span class="sc">&lt;</span> <span class="fl">1e-12</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>          <span class="fu">abs</span>(ex[[<span class="st">"death_R_none"</span>]] <span class="sc">-</span> (ex[[<span class="st">"death_R_S"</span>]] <span class="sc">+</span> ex[[<span class="st">"death_S_none"</span>]])) <span class="sc">&lt;</span> <span class="fl">1e-12</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Face validity against Falagas 2014. Their "attributable death" is a DIFFERENCE in mortality</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># between resistant and susceptible infections (percentage points), so compare it with</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># death_R_S, not with a share of the deaths. Their pooled unadjusted risk ratio is the</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="co"># like-for-like check on the relative scale.</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>ptab <span class="ot">&lt;-</span> <span class="fu">attr</span>(p, <span class="st">"table"</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>rd_model <span class="ot">&lt;-</span> ex[[<span class="st">"death_R_S"</span>]]</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>rr_model <span class="ot">&lt;-</span> states<span class="sc">$</span>p_death[<span class="dv">3</span>] <span class="sc">/</span> states<span class="sc">$</span>p_death[<span class="dv">2</span>]</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>rr_ci <span class="ot">&lt;-</span> <span class="fu">unlist</span>(ptab[ptab<span class="sc">$</span>name <span class="sc">==</span> <span class="st">"falagas_rr"</span>, <span class="fu">c</span>(<span class="st">"low"</span>, <span class="st">"high"</span>)])</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>rd_in_range <span class="ot">&lt;-</span> rd_model <span class="sc">&gt;=</span> p<span class="sc">$</span>falagas_attr_min <span class="sc">&amp;&amp;</span> rd_model <span class="sc">&lt;=</span> p<span class="sc">$</span>falagas_attr_max</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>rr_in_ci <span class="ot">&lt;-</span> rr_model <span class="sc">&gt;=</span> rr_ci[[<span class="st">"low"</span>]] <span class="sc">&amp;&amp;</span> rr_model <span class="sc">&lt;=</span> rr_ci[[<span class="st">"high"</span>]]</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">model_rd =</span> rd_model, <span class="at">falagas_min =</span> p<span class="sc">$</span>falagas_attr_min, <span class="at">falagas_max =</span> p<span class="sc">$</span>falagas_attr_max,</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">model_rr =</span> rr_model, <span class="at">falagas_rr =</span> p<span class="sc">$</span>falagas_rr, <span class="at">rr_low =</span> rr_ci[[<span class="st">"low"</span>]], <span class="at">rr_high =</span> rr_ci[[<span class="st">"high"</span>]]), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   model_rd falagas_min falagas_max    model_rr  falagas_rr      rr_low 
      0.115       0.260       0.440       1.568       2.050       1.560 
    rr_high 
      2.690 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">rd_in_range =</span> rd_in_range, <span class="at">rr_in_ci =</span> rr_in_ci)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>rd_in_range    rr_in_ci 
      FALSE        TRUE </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Words for the lesson text ("nằm dưới / trong / trên")</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>rd_pos <span class="ot">&lt;-</span> <span class="cf">if</span> (rd_model <span class="sc">&lt;</span> p<span class="sc">$</span>falagas_attr_min) <span class="st">"nằm dưới"</span> <span class="cf">else</span> <span class="cf">if</span> (rd_model <span class="sc">&gt;</span> p<span class="sc">$</span>falagas_attr_max) <span class="st">"nằm trên"</span> <span class="cf">else</span> <span class="st">"nằm trong"</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>rr_pos <span class="ot">&lt;-</span> <span class="cf">if</span> (rr_model <span class="sc">&lt;</span> rr_ci[[<span class="st">"low"</span>]]) <span class="st">"nằm dưới"</span> <span class="cf">else</span> <span class="cf">if</span> (rr_model <span class="sc">&gt;</span> rr_ci[[<span class="st">"high"</span>]]) <span class="st">"nằm trên"</span> <span class="cf">else</span> <span class="st">"nằm trong"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Chênh lệch tỷ lệ tử vong giữa nhiễm CRE và nhiễm khuẩn nhạy là 11.5 điểm phần trăm, nằm dưới khoảng 26–44 điểm phần trăm của Falagas và cộng sự. Tỷ số nguy cơ là 1.57, nằm trong khoảng tin cậy 95% của tỷ số gộp (1.56–2.69). Hai kết quả không mâu thuẫn: chênh lệch tuyệt đối phụ thuộc vào tỷ lệ tử vong nền (20.2% ở người nhiễm khuẩn nhạy), còn tỷ số ít phụ thuộc hơn. Vì các xác suất này lấy từ số thô của khảo sát Việt Nam, đây là đối chiếu số liệu Việt Nam với tổng quan quốc tế, không phải hiệu chuẩn; cả hai nguồn đều chưa điều chỉnh mức độ nặng.</p>
<p>Nhân với số ca mỗi năm ra gánh nặng của bệnh viện. Đoạn mã in trước số năm sống mất đi cho mỗi ca tử vong. Cột <code>share</code> là tỷ lệ quy thuộc trên liên quan.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Annual burden of the hospital's CRE infections: BHYT bed-day prices and tender drug prices</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (2025 prices, ../_shared), illustrative number of infections and ICU share of the extra days.</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Years of life lost per death come from the WHO life table (vn_mx()) at the median ICU age.</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>yll_per_death <span class="ot">&lt;-</span> <span class="fu">life_years_after_icu</span>(p, <span class="at">disc_rate =</span> <span class="dv">0</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">age =</span> p<span class="sc">$</span>age_icu, <span class="at">hr_post_icu =</span> p<span class="sc">$</span>hr_post_icu, <span class="at">yll_per_death =</span> yll_per_death), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          age   hr_post_icu yll_per_death 
         61.0           2.0          14.2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>bt <span class="ot">&lt;-</span> <span class="fu">burden_table</span>(p, H)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>bt<span class="sc">$</span>share <span class="ot">&lt;-</span> bt<span class="sc">$</span>attributable <span class="sc">/</span> bt<span class="sc">$</span>associated</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>bt_show <span class="ot">&lt;-</span> bt                      <span class="co"># round a copy for printing; keep bt exact for the text</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>bt_show[, <span class="sc">-</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(bt_show[, <span class="sc">-</span><span class="dv">1</span>], <span class="dv">2</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>bt_show</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           measure associated attributable share
1           deaths      72.78        34.40  0.47
2         bed_days    2222.22       714.29  0.32
3 cost_million_vnd   18127.46     16444.92  0.91
4              yll    1034.17       488.82  0.47</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(bt<span class="sc">$</span>attributable <span class="sc">&lt;=</span> bt<span class="sc">$</span>associated), <span class="fu">all</span>(bt<span class="sc">$</span>associated <span class="sc">&gt;=</span> <span class="dv">0</span>))</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>deaths_assoc <span class="ot">&lt;-</span> bt<span class="sc">$</span>associated[bt<span class="sc">$</span>measure <span class="sc">==</span> <span class="st">"deaths"</span>]</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>deaths_attr <span class="ot">&lt;-</span> bt<span class="sc">$</span>attributable[bt<span class="sc">$</span>measure <span class="sc">==</span> <span class="st">"deaths"</span>]</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>cost_assoc <span class="ot">&lt;-</span> bt<span class="sc">$</span>associated[bt<span class="sc">$</span>measure <span class="sc">==</span> <span class="st">"cost_million_vnd"</span>] <span class="sc">*</span> <span class="fl">1e6</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>cost_attr <span class="ot">&lt;-</span> bt<span class="sc">$</span>attributable[bt<span class="sc">$</span>measure <span class="sc">==</span> <span class="st">"cost_million_vnd"</span>] <span class="sc">*</span> <span class="fl">1e6</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Share of the attributable cost that is reserve antibiotics (colistin + high-dose meropenem minus meropenem)</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>drug_share_attr <span class="ot">&lt;-</span> p<span class="sc">$</span>n_inf_cre <span class="sc">*</span> p<span class="sc">$</span>dur_abx <span class="sc">*</span> (p<span class="sc">$</span>c_abx_r_day <span class="sc">-</span> p<span class="sc">$</span>c_abx_s_day) <span class="sc">/</span> cost_attr</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(drug_share_attr, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.97</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(drug_share_attr <span class="sc">&gt;</span> <span class="dv">0</span>, drug_share_attr <span class="sc">&lt;=</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Như vậy, mỗi năm bệnh viện có 72.8 ca tử vong liên quan đến CRE, trong đó 34.4 ca quy thuộc kháng thuốc; mỗi ca tử vong mất 14.2 năm sống (chưa chiết khấu). Chi phí liên quan là 18.1 tỷ VNĐ, chi phí quy thuộc là 16.4 tỷ VNĐ (giá 2025; số ca minh họa). Tiền kháng sinh dự trữ chiếm 97% chi phí quy thuộc, nên với chi phí, tỷ lệ quy thuộc trên liên quan (91%) cao hơn hẳn so với tử vong (47%). Hình dưới tách mỗi cột thành phần do bản thân nhiễm khuẩn và phần do kháng thuốc.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>measure_vi <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">deaths =</span> <span class="st">"Tử vong (ca)"</span>, <span class="at">bed_days =</span> <span class="st">"Ngày giường"</span>,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">cost_million_vnd =</span> <span class="st">"Chi phí (triệu VNĐ)"</span>, <span class="at">yll =</span> <span class="st">"Năm sống mất đi"</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>plot_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">measure =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(measure_vi[bt<span class="sc">$</span>measure], <span class="dv">2</span>), <span class="at">levels =</span> measure_vi),</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">part =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Do bản thân nhiễm khuẩn (S so với không nhiễm)"</span>,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Do kháng thuốc (R so với S)"</span>), <span class="at">each =</span> <span class="fu">nrow</span>(bt)),</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Do bản thân nhiễm khuẩn (S so với không nhiễm)"</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"Do kháng thuốc (R so với S)"</span>)),</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">c</span>(bt<span class="sc">$</span>associated <span class="sc">-</span> bt<span class="sc">$</span>attributable, bt<span class="sc">$</span>attributable)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>fig_cf <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(plot_df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> value, <span class="at">fill =</span> part)) <span class="sc">+</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>measure, <span class="at">scales =</span> <span class="st">"free_y"</span>, <span class="at">nrow =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> pal_course[<span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">2</span>)], <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="cf">function</span>(x) <span class="fu">fmt_num</span>(x)) <span class="sc">+</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Gánh nặng liên quan (cả cột) và gánh nặng quy thuộc kháng thuốc (phần đỏ)"</span>,</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">sprintf</span>(<span class="st">"Một năm, %s ca nhiễm khuẩn CRE của một bệnh viện (số ca minh họa; giá BHYT và giá thầu, năm %s)"</span>,</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">fmt_num</span>(p<span class="sc">$</span>n_inf_cre), <span class="st">"2025"</span>)) <span class="sc">+</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>() <span class="sc">+</span></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.direction =</span> <span class="st">"vertical"</span>)</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_cf, <span class="st">"l01-counterfactuals.png"</span>, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="fl">4.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l01-counterfactuals.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Gánh nặng liên quan và gánh nặng quy thuộc của các ca nhiễm khuẩn CRE trong một năm (số ca minh họa; giá BHYT và giá thầu năm 2025).</figcaption>
</figure>
</div>
<p>Cuối cùng, ta tính chi phí xã hội của một liệu trình meropenem theo kinh nghiệm. Với <span class="math inline">\(c_{AMR}\)</span> ≈ US$0.4 mỗi SU (trung điểm khoảng Thái Lan, tức 9,988 VNĐ theo tỷ giá 24,970 VNĐ/USD), phần ngoại ứng chiếm 15.8% chi phí xã hội. Meropenem generic rẻ (khoảng 53,088 VNĐ một lọ 1 g), nên phần ngoại ứng không nhỏ so với giá thuốc; con số này phụ thuộc hoàn toàn vào <span class="math inline">\(c_{AMR}\)</span>, tham số bất định nhất của cả bài (xem Bài tập 3).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Private vs social cost of one empirical carbapenem course: meropenem at its 2025 tender price,</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># external cost per SU from Shrestha et al. (Thai range, converted with the course exchange rate)</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">c_carb_day =</span> p<span class="sc">$</span>c_carb_day, <span class="at">su_per_day =</span> p<span class="sc">$</span>su_per_day, <span class="at">c_amr_su_vnd =</span> <span class="fu">amr_cost_su</span>(p))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  c_carb_day   su_per_day c_amr_su_vnd 
    159263.7          3.0       9988.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>ext <span class="ot">&lt;-</span> <span class="fu">externality_course</span>(p)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(ext[<span class="fu">c</span>(<span class="st">"private"</span>, <span class="st">"external"</span>, <span class="st">"social"</span>)] <span class="sc">/</span> <span class="fl">1e6</span>, ext[<span class="st">"external_share"</span>]), <span class="dv">3</span>)  <span class="co"># million VND; share</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       private       external         social external_share 
         1.115          0.210          1.325          0.158 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(ext[[<span class="st">"social"</span>]] <span class="sc">-</span> ext[[<span class="st">"private"</span>]] <span class="sc">-</span> ext[[<span class="st">"external"</span>]]) <span class="sc">&lt;</span> <span class="fl">1e-6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Mẹo thực hành">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mẹo thực hành
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Trước khi tính, viết ra một câu: “so với kịch bản trong đó…”. Nếu không viết được, bạn chưa có câu hỏi.</li>
<li>Báo cáo song song gánh nặng liên quan và gánh nặng quy thuộc, như các nghiên cứu gánh nặng toàn cầu đã làm.</li>
<li>Giữ mọi chi phí đơn vị kèm năm giá. Giá chung của khóa học nằm ở <code>kb/_shared</code>; khi bệnh viện của bạn có bảng giá hay giá thầu riêng, chỉ cần thay tệp CSV.</li>
<li>Đọc một bài báo về chi phí AMR, trước hết tìm nhóm so sánh và cách xử lý thời điểm nhiễm khuẩn <span class="citation" data-cites="wozniak2019using">(<a href="#ref-wozniak2019using" role="doc-biblioref">Wozniak và c.s. 2019</a>)</span>.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Lỗi thường gặp">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lỗi thường gặp
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Dùng gánh nặng liên quan cho can thiệp chỉ biến chủng kháng thành “như nhạy”.</strong> Lợi ích bị phóng đại nhiều lần. Kiểm tra bằng bảng “can thiệp làm thay đổi điều gì” ở trên.</li>
<li><strong>Cộng dồn gánh nặng quy thuộc của nhiều cặp vi khuẩn–kháng sinh.</strong> Một chủng đa kháng có thể bị đếm nhiều lần. Kiểm tra định nghĩa cặp và phần chồng lấn trước khi cộng.</li>
<li><strong>Coi ngày giường giảm được là tiền tiết kiệm được.</strong> Giường trống được lấp ngay, nên lợi ích là năng lực phục vụ thêm, không phải ngân sách được hoàn lại.</li>
<li><strong>Nhầm tỷ lệ tử vong của người nhiễm CRE với tử vong quy thuộc.</strong> Người nhiễm CRE thường nặng sẵn; một phần tử vong vẫn xảy ra khi không có nhiễm khuẩn.</li>
</ul>
</div>
</div>
</section>
<section id="bài-tập" class="level2">
<h2 class="anchored" data-anchor-id="bài-tập">Bài tập</h2>
<p><strong>Bài 1 (dễ).</strong> Tính tỷ lệ <em>K. pneumoniae</em> và <em>E. coli</em> kháng imipenem trong VINARES 2012–2013, kèm KTC 95% chính xác (Clopper–Pearson), rồi so với tỷ lệ của khảo sát toàn quốc công bố năm 2025.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>binom.test()</code> cho khoảng tin cậy chính xác của một tỷ lệ nhị thức.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 1: imipenem resistance in VINARES 2012-2013, with exact 95% CIs</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>vin <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">species =</span> <span class="fu">c</span>(<span class="st">"K. pneumoniae"</span>, <span class="st">"E. coli"</span>),</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">r =</span> <span class="fu">c</span>(p<span class="sc">$</span>vinares_kp_imi_r, p<span class="sc">$</span>vinares_ec_imi_r),</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">c</span>(p<span class="sc">$</span>vinares_kp_n, p<span class="sc">$</span>vinares_ec_n)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>vin<span class="sc">$</span>prop <span class="ot">&lt;-</span> vin<span class="sc">$</span>r <span class="sc">/</span> vin<span class="sc">$</span>n</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>vin<span class="sc">$</span>lo <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>vin<span class="sc">$</span>hi <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_len</span>(<span class="fu">nrow</span>(vin))) {</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  ci <span class="ot">&lt;-</span> <span class="fu">binom.test</span>(vin<span class="sc">$</span>r[i], vin<span class="sc">$</span>n[i])<span class="sc">$</span>conf.int   <span class="co"># exact (Clopper-Pearson) interval</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>  vin<span class="sc">$</span>lo[i] <span class="ot">&lt;-</span> ci[<span class="dv">1</span>]</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>  vin<span class="sc">$</span>hi[i] <span class="ot">&lt;-</span> ci[<span class="dv">2</span>]</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>vin_show <span class="ot">&lt;-</span> vin</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>vin_show[, <span class="fu">c</span>(<span class="st">"prop"</span>, <span class="st">"lo"</span>, <span class="st">"hi"</span>)] <span class="ot">&lt;-</span> <span class="fu">round</span>(vin_show[, <span class="fu">c</span>(<span class="st">"prop"</span>, <span class="st">"lo"</span>, <span class="st">"hi"</span>)], <span class="dv">3</span>)</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>vin_show</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        species   r    n  prop    lo    hi
1 K. pneumoniae 242 1526 0.159 0.141 0.178
2       E. coli 180 2977 0.060 0.052 0.070</code></pre>
</div>
</div>
<p><em>K. pneumoniae</em> kháng imipenem 15.9 (KTC 95%: 14.1–17.8) phần trăm, cao gấp khoảng 2.6 lần <em>E. coli</em>. Khảo sát công bố năm 2025 báo cáo 37% và 11%. Hai nguồn khác nhau về mạng lưới bệnh viện, cách chọn chủng và kháng sinh thử, nên chỉ nói được rằng kháng carbapenem đã phổ biến hơn, không nói được tăng chính xác bao nhiêu.</p>
</div>
</div>
</div>
<p><strong>Bài 2 (vừa).</strong> Bệnh viện cân nhắc hai can thiệp: (a) một kháng sinh mới khiến nhiễm khuẩn CRE diễn tiến như nhiễm khuẩn nhạy; (b) một gói kiểm soát nhiễm khuẩn ngăn được toàn bộ các ca nhiễm khuẩn CRE. Mỗi can thiệp tránh được bao nhiêu ca tử vong mỗi năm?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Can thiệp (a) dùng phản thực “nhạy cảm”, can thiệp (b) dùng phản thực “không nhiễm khuẩn”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 2: deaths averted per year by two kinds of intervention</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (a) a new drug that makes CRE infections behave like susceptible ones -&gt; R vs S</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co"># (b) infection prevention that stops the infections altogether        -&gt; R vs none</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>averted <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">new_drug =</span> p<span class="sc">$</span>n_inf_cre <span class="sc">*</span> ex[[<span class="st">"death_R_S"</span>]],</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">prevention =</span> p<span class="sc">$</span>n_inf_cre <span class="sc">*</span> ex[[<span class="st">"death_R_none"</span>]])</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(averted, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  new_drug prevention 
      34.4       72.8 </code></pre>
</div>
</div>
<p>Kiểm soát nhiễm khuẩn tránh được 72.8 ca, thuốc mới tránh được 34.4 ca. Cùng một bệnh viện, cùng số ca nhiễm, nhưng lợi ích khác nhau vì kịch bản phản thực khác nhau.</p>
</div>
</div>
</div>
<p><strong>Bài 3 (khó).</strong> Với giá trị <span class="math inline">\(c_{AMR}\)</span> nào thì chi phí ngoại ứng của một liệu trình meropenem bằng đúng giá mua thuốc? So sánh với khoảng ước tính của Shrestha và cộng sự (quy ra VNĐ), và cho biết bạn cần thêm thông tin gì để so sánh này có ý nghĩa.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Cho <span class="math inline">\(d \cdot n_{SU} \cdot c_{AMR} = d \cdot c_{\text{thuốc}}\)</span>, ta có <span class="math inline">\(c_{AMR} = c_{\text{thuốc}} / n_{SU}\)</span>, tức giá một lọ.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 3: value of the resistance cost per SU at which the external cost of a</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="co"># course equals its purchase price</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>c_amr_breakeven <span class="ot">&lt;-</span> p<span class="sc">$</span>c_carb_day <span class="sc">/</span> p<span class="sc">$</span>su_per_day                   <span class="co"># VND per SU</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>shrestha_vnd <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">low =</span> p<span class="sc">$</span>shrestha_su_min_usd, <span class="at">high =</span> p<span class="sc">$</span>shrestha_su_max_usd) <span class="sc">*</span> p<span class="sc">$</span>fx_vnd_per_usd</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">breakeven_vnd =</span> c_amr_breakeven, shrestha_vnd, <span class="at">breakeven_usd =</span> c_amr_breakeven <span class="sc">/</span> p<span class="sc">$</span>fx_vnd_per_usd), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>breakeven_vnd           low          high breakeven_usd 
     53087.91       2497.00      17479.00          2.13 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>p_be <span class="ot">&lt;-</span> p</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>p_be<span class="sc">$</span>c_amr_su_usd <span class="ot">&lt;-</span> c_amr_breakeven <span class="sc">/</span> p<span class="sc">$</span>fx_vnd_per_usd</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>ext_be <span class="ot">&lt;-</span> <span class="fu">externality_course</span>(p_be)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(ext_be[<span class="fu">c</span>(<span class="st">"private"</span>, <span class="st">"external"</span>, <span class="st">"social"</span>)] <span class="sc">/</span> <span class="fl">1e6</span>, ext_be[<span class="st">"external_share"</span>]), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       private       external         social external_share 
         1.115          1.115          2.230          0.500 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(ext_be[[<span class="st">"external_share"</span>]] <span class="sc">-</span> <span class="fl">0.5</span>) <span class="sc">&lt;</span> <span class="fl">1e-9</span>)       <span class="co"># break-even: external = private</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>be_pos <span class="ot">&lt;-</span> <span class="cf">if</span> (c_amr_breakeven <span class="sc">&gt;</span> shrestha_vnd[[<span class="st">"high"</span>]]) <span class="st">"cao hơn"</span> <span class="cf">else</span> <span class="cf">if</span> (c_amr_breakeven <span class="sc">&lt;</span> shrestha_vnd[[<span class="st">"low"</span>]]) <span class="st">"thấp hơn"</span> <span class="cf">else</span> <span class="st">"nằm trong"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Điểm hòa vốn là 53,088 VNĐ mỗi SU (khoảng US$2.13), cao hơn khoảng 2,497 VNĐ–17,479 VNĐ của Shrestha và cộng sự quy theo tỷ giá năm 2025. Để so sánh có ý nghĩa, cần năm giá của ước tính gốc (để đưa về giá 2025, M09), một ước tính riêng cho carbapenem trong bối cảnh Việt Nam, và phân biệt chi phí trung bình với chi phí biên (Bài 5).</p>
</div>
</div>
</div>
</section>
<section id="tài-liệu-tham-khảo" class="level2">
<h2 class="anchored" data-anchor-id="tài-liệu-tham-khảo">Tài liệu tham khảo</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-amrcollaborators2022global" class="csl-entry" role="listitem">
Antimicrobial Resistance Collaborators. 2022. <span>“Global burden of bacterial antimicrobial resistance in 2019: a systematic analysis”</span>. <em>The Lancet</em> 399 (10325): 629–55. <a href="https://doi.org/10.1016/S0140-6736(21)02724-0">https://doi.org/10.1016/S0140-6736(21)02724-0</a>.
</div>
<div id="ref-cuchi2024thau" class="csl-entry" role="listitem">
Bệnh viện Đa khoa khu vực Củ Chi. 2024. <span>“Danh mục giá thầu thuốc bệnh viện 2024 (Lần 2)”</span>. 2024. <a href="https://bvdkkvcuchi.vn/wp-content/uploads/2024/12/DANH-MUC-THUOC-DANG-WEBSITE-BV-nam-2024-lan-2.pdf">https://bvdkkvcuchi.vn/wp-content/uploads/2024/12/DANH-MUC-THUOC-DANG-WEBSITE-BV-nam-2024-lan-2.pdf</a>.
</div>
<div id="ref-thainguyen2023thau" class="csl-entry" role="listitem">
Bệnh viện Trung ương Thái Nguyên. 2023. <span>“Danh mục thuốc trúng thầu tại Bệnh viện Trung ương Thái Nguyên (áp dụng từ ngày 17/10/2023 theo Quyết định số 1580/<span>QĐ-BVTWTN</span>)”</span>. 17 Tháng Mười 2023. <a href="https://bvdktuthainguyen.gov.vn/uploads/media/tai%20lieu/danh%20muc%20thuoc/thuoc%202022-2023/DM%20thu%E1%BB%91c%20tr%C3%BAng%20th%E1%BA%A7u%202023%20BVTW%20TN%20(1).xlsx">https://bvdktuthainguyen.gov.vn/uploads/media/tai%20lieu/danh%20muc%20thuoc/thuoc%202022-2023/DM%20thu%E1%BB%91c%20tr%C3%BAng%20th%E1%BA%A7u%202023%20BVTW%20TN%20(1).xlsx</a>.
</div>
<div id="ref-byt2024qd3220" class="csl-entry" role="listitem">
Bộ Y tế. 2024. <span>“Quyết định số 3220/<span>QĐ-BYT</span> ngày 01/11/2024 về giá dịch vụ khám bệnh, chữa bệnh áp dụng tại Bệnh viện Bạch Mai”</span>. 1 Tháng Mười-Một 2024. <a href="https://apicms.bachmai.gov.vn/documents/37204/1543632/8_Nov_2024_022948_GMTupload_00004592.pdf/b3ab6717-2151-db08-9913-3cfbfd7e0738">https://apicms.bachmai.gov.vn/documents/37204/1543632/8_Nov_2024_022948_GMTupload_00004592.pdf/b3ab6717-2151-db08-9913-3cfbfd7e0738</a>.
</div>
<div id="ref-coast1996superbugs" class="csl-entry" role="listitem">
Coast, J., R. D. Smith, và M. R. Millar. 1996. <span>“Superbugs: should antimicrobial resistance be included as a cost in economic evaluation?”</span> <em>Health Economics</em> 5 (3): 217–26. <a href="https://doi.org/10.1002/(SICI)1099-1050(199605)5:3<217::AID-HEC200>3.0.CO;2-S">https://doi.org/10.1002/(SICI)1099-1050(199605)5:3&lt;217::AID-HEC200&gt;3.0.CO;2-S</a>.
</div>
<div id="ref-dekraker2011mortality" class="csl-entry" role="listitem">
de Kraker, Marlieke E. A., Peter G. Davey, Hajo Grundmann, và c.s. 2011. <span>“Mortality and hospital stay associated with resistant <span>Staphylococcus aureus</span> and <span>Escherichia coli</span> bacteremia: estimating the burden of antibiotic resistance in <span>Europe</span>”</span>. <em>PLoS Medicine</em> 8 (10): e1001104. <a href="https://doi.org/10.1371/journal.pmed.1001104">https://doi.org/10.1371/journal.pmed.1001104</a>.
</div>
<div id="ref-falagas2014deaths" class="csl-entry" role="listitem">
Falagas, Matthew E., Giannoula S. Tansarli, Drosos E. Karageorgopoulos, và Konstantinos Z. Vardakas. 2014. <span>“Deaths attributable to carbapenem-resistant <span>Enterobacteriaceae</span> infections”</span>. <em>Emerging Infectious Diseases</em> 20 (7): 1170–75. <a href="https://doi.org/10.3201/eid2007.121004">https://doi.org/10.3201/eid2007.121004</a>.
</div>
<div id="ref-gbdamr2024global" class="csl-entry" role="listitem">
GBD 2021 Antimicrobial Resistance Collaborators. 2024. <span>“Global burden of bacterial antimicrobial resistance 1990–2021: a systematic analysis with forecasts to 2050”</span>. <em>The Lancet</em> 404 (10459): 1199–1226. <a href="https://doi.org/10.1016/S0140-6736(24)01867-1">https://doi.org/10.1016/S0140-6736(24)01867-1</a>.
</div>
<div id="ref-graves2010estimating" class="csl-entry" role="listitem">
Graves, Nicholas, Stephan Harbarth, Jan Beyersmann, Adrian Barnett, Kate Halton, và Ben Cooper. 2010. <span>“Estimating the cost of health care-associated infections: mind your p’s and q’s”</span>. <em>Clinical Infectious Diseases</em> 50 (7): 1017–21. <a href="https://doi.org/10.1086/651110">https://doi.org/10.1086/651110</a>.
</div>
<div id="ref-larsson2025burden" class="csl-entry" role="listitem">
Larsson, M, L V N Truong, T D Nguyen, T N Do, T B N Hoang, M V Nong, M P Doan, và c.s. 2025. <span>“Burden of carbapenem-resistant <span>Gram</span>-negative bacterial infections in <span>Vietnam</span>: a national hospital survey”</span>. <em>Journal of Hospital Infection</em> 165: 189–98. <a href="https://doi.org/10.1016/j.jhin.2025.03.019">https://doi.org/10.1016/j.jhin.2025.03.019</a>.
</div>
<div id="ref-laxminarayan2013antibiotic" class="csl-entry" role="listitem">
Laxminarayan, Ramanan, Adriano Duse, Chand Wattal, Anita K. M. Zaidi, Heiman F. L. Wertheim, Nithima Sumpradit, và c.s. 2013. <span>“Antibiotic resistance—the need for global solutions”</span>. <em>The Lancet Infectious Diseases</em> 13 (12): 1057–98. <a href="https://doi.org/10.1016/S1473-3099(13)70318-9">https://doi.org/10.1016/S1473-3099(13)70318-9</a>.
</div>
<div id="ref-naylor2018estimating" class="csl-entry" role="listitem">
Naylor, Nichola R., Rifat Atun, Nina Zhu, Kavian Kulasabanathan, Sachin Silva, Anuja Chatterjee, và c.s. 2018. <span>“Estimating the burden of antimicrobial resistance: a systematic literature review”</span>. <em>Antimicrobial Resistance and Infection Control</em> 7: 58. <a href="https://doi.org/10.1186/s13756-018-0336-y">https://doi.org/10.1186/s13756-018-0336-y</a>.
</div>
<div id="ref-phu2017ventilator" class="csl-entry" role="listitem">
Phu, Vu Dinh, Behzad Nadjm, Nguyen Hoang Anh Duy, Dao Xuan Co, Nguyen Thi Hoang Mai, Dao Tuyet Trinh, và c.s. 2017. <span>“Ventilator-associated respiratory infection in a resource-restricted setting: impact and etiology”</span>. <em>Journal of Intensive Care</em> 5: 69. <a href="https://doi.org/10.1186/s40560-017-0266-4">https://doi.org/10.1186/s40560-017-0266-4</a>.
</div>
<div id="ref-phu2016burden" class="csl-entry" role="listitem">
Phu, Vu Dinh, Heiman F L Wertheim, Mattias Larsson, Behzad Nadjm, Quynh-Dao Dinh, Lennart E Nilsson, Ulf Rydell, và c.s. 2016. <span>“Burden of Hospital Acquired Infections and Antimicrobial Use in <span>Vietnamese</span> Adult Intensive Care Units”</span>. <em>PLoS One</em> 11 (1): e0147544. <a href="https://doi.org/10.1371/journal.pone.0147544">https://doi.org/10.1371/journal.pone.0147544</a>.
</div>
<div id="ref-shrestha2018enumerating" class="csl-entry" role="listitem">
Shrestha, Poojan, Ben S. Cooper, Joanna Coast, Raymond Oppong, Nga Do Thi Thuy, Tuangrat Phodha, và c.s. 2018. <span>“Enumerating the economic cost of antimicrobial resistance per antibiotic consumed to inform the evaluation of interventions affecting their use”</span>. <em>Antimicrobial Resistance and Infection Control</em> 7: 98. <a href="https://doi.org/10.1186/s13756-018-0384-3">https://doi.org/10.1186/s13756-018-0384-3</a>.
</div>
<div id="ref-stewardson2016health" class="csl-entry" role="listitem">
Stewardson, Andrew J., Arthur Allignol, Jan Beyersmann, Nicholas Graves, Martin Schumacher, Rodolphe Meyer, và c.s. 2016. <span>“The health and economic burden of bloodstream infections caused by antimicrobial-susceptible and non-susceptible <span>Enterobacteriaceae</span> and <span>Staphylococcus aureus</span> in <span>European</span> hospitals, 2010 and 2011: a multicentre retrospective cohort study”</span>. <em>Eurosurveillance</em> 21 (33): 30319. <a href="https://doi.org/10.2807/1560-7917.ES.2016.21.33.30319">https://doi.org/10.2807/1560-7917.ES.2016.21.33.30319</a>.
</div>
<div id="ref-vu2019antimicrobial" class="csl-entry" role="listitem">
Vu, Tien Viet Dung, Thi Thuy Nga Do, Ulf Rydell, Lennart E. Nilsson, Linus Olson, Mattias Larsson, và c.s. 2019. <span>“Antimicrobial susceptibility testing and antibiotic consumption results from 16 hospitals in <span>Viet Nam</span>: the <span>VINARES</span> project 2012–2013”</span>. <em>Journal of Global Antimicrobial Resistance</em> 18: 269–78. <a href="https://doi.org/10.1016/j.jgar.2019.06.002">https://doi.org/10.1016/j.jgar.2019.06.002</a>.
</div>
<div id="ref-who2026lifetables" class="csl-entry" role="listitem">
World Health Organization. 2026. <span>“Global Health Observatory: life tables by country, <span>Viet Nam</span>, 2023 (indicators <span>LIFE_0000000029</span> nMx, <span>LIFE_0000000030</span> nqx, <span>LIFE_0000000035</span> ex)”</span>. 2026. <a href="https://ghoapi.azureedge.net/api/LIFE_0000000029">https://ghoapi.azureedge.net/api/LIFE_0000000029</a>.
</div>
<div id="ref-wozniak2019using" class="csl-entry" role="listitem">
Wozniak, Teresa M., Louise Barnsbee, Xing J. Lee, và Rosana E. Pacella. 2019. <span>“Using the best available data to estimate the cost of antimicrobial resistance: a systematic review”</span>. <em>Antimicrobial Resistance and Infection Control</em> 8: 26. <a href="https://doi.org/10.1186/s13756-019-0472-z">https://doi.org/10.1186/s13756-019-0472-z</a>.
</div>
</div>
<div class="video-script">
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kịch bản video (~13 phút)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Slide</th>
<th>Lời giảng chính</th>
<th>Hình/Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Mở đầu: một ca CRE ở ICU</td>
<td>Một ngày colistin + meropenem so với lương tối thiểu; câu hỏi “tốn bao nhiêu” phụ thuộc vào “so với gì”</td>
<td>Hộp “Vì sao bạn nên quan tâm?”</td>
</tr>
<tr class="even">
<td>2</td>
<td>Kháng sinh là tài nguyên chung</td>
<td>Lợi ích riêng, chi phí chung; ngoại ứng tiêu cực; hệ quả: dùng quá mức</td>
<td>Công thức chi phí xã hội</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Chi phí ngoại ứng trên mỗi SU</td>
<td>Shrestha 2018: ước tính theo nhóm thuốc; meropenem generic rẻ nên phần ngoại ứng đáng kể</td>
<td><code>l01-externality</code></td>
</tr>
<tr class="even">
<td>4</td>
<td>Hai kịch bản phản thực</td>
<td>Liên quan: so với không nhiễm; quy thuộc: so với nhiễm chủng nhạy</td>
<td>Sơ đồ Mermaid</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Số liệu toàn cầu</td>
<td>Nhóm AMR Collaborators (2019) và GBD 2021 AMR (2021): hai con số, hai câu hỏi</td>
<td><code>l01-gram</code></td>
</tr>
<tr class="even">
<td>6</td>
<td>Bằng chứng thực nghiệm</td>
<td>Stewardson 2016, Falagas 2014; VINARES và khảo sát toàn quốc (tử vong thô CRE so với nhạy)</td>
<td>Bảng tham số <code>context.csv</code></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Chọn phản thực theo can thiệp</td>
<td>Thuốc mới so với kiểm soát nhiễm khuẩn so với quản lý kháng sinh</td>
<td>Bảng 3 dòng</td>
</tr>
<tr class="even">
<td>8</td>
<td>Tính cho một bệnh viện</td>
<td>Công thức 1/h và h_tử vong/h; giá BHYT và giá thầu; YLL từ bảng sống WHO</td>
<td><code>l01-states</code>, <code>l01-excess</code></td>
</tr>
<tr class="odd">
<td>9</td>
<td>Kết quả bệnh viện</td>
<td>Tử vong, ngày giường, chi phí, YLL; tiền thuốc chi phối chi phí quy thuộc</td>
<td><code>figs/l01-counterfactuals.png</code></td>
</tr>
<tr class="even">
<td>10</td>
<td>Lỗi thường gặp và tóm tắt</td>
<td>Đếm trùng, ngày giường không phải tiền mặt; chuyển sang Bài 2: thời điểm nhiễm khuẩn</td>
<td>Hộp “Lỗi thường gặp”</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../kb/m06-amr-economics/index.html" class="pagination-link" aria-label="M06 · Kinh tế học kháng kháng sinh (AMR)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">M06 · Kinh tế học kháng kháng sinh (AMR)</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../kb/m06-amr-economics/l02-attributable-los.html" class="pagination-link" aria-label="Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian">
        <span class="nav-page-text"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>