<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian – Mô hình Kinh tế Y tế với R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../kb/m06-amr-economics/l03-ward-transmission.html" rel="next">
<link href="../../kb/m06-amr-economics/l01-amr-burden.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9e7f0c659d5fa2cace8548cb57964278.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c18d72663580ed8ca19ce2a2f99af51b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="mermaid-theme" content="neutral">
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=JetBrains+Mono:wght@400;600&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m06-amr-economics/index.html">M06 · Kinh tế học kháng kháng sinh (AMR)</a></li><li class="breadcrumb-item"><a href="../../kb/m06-amr-economics/l02-attributable-los.html"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Mô hình Kinh tế Y tế với R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lời mở đầu</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m00-r-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M00 · R cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l02-vectors-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l03-functions-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hàm, cấu trúc điều khiển, vòng lặp và vectơ hóa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l04-data-frames.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Data frame — nhập, làm sạch, tóm tắt và chuyển dạng dữ liệu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l05-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Biểu đồ với ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l06-randomness-monte-carlo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 6: Ngẫu nhiên, mô phỏng Monte Carlo và sai số Monte Carlo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m01-ee-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M01 · Nền tảng đánh giá kinh tế và cây quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l01-evaluation-types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại đánh giá kinh tế, quan điểm, khung thời gian và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l02-health-outcomes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Năm sống, QALY và DALY</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l03-decision-rules.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l04-thresholds.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l05-decision-tree.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Xây cây quyết định từ đầu trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m02-cohort-markov/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l01-state-transition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao cần mô hình chuyển trạng thái</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l03-cohort-trace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l04-time-dependence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Phụ thuộc thời gian: lão hóa, trạng thái đường hầm và mảng 3 chiều</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l05-results-verification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị gắn với lần chuyển, đường biên hiệu quả và xác minh mô hình</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m03-uncertainty-voi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l01-deterministic-sa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại bất định và phân tích độ nhạy tất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l02-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Chọn phân phối cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l03-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích độ nhạy xác suất (PSA) trong R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l05-voi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m04-microsimulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M04 · Mô phỏng vi mô (microsimulation)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l01-why-microsimulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l02-microsim-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l03-vectorisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vectơ hóa theo cá thể và đo hiệu năng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l04-parallel-rcpp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tính toán song song và Rcpp cho vòng lặp nóng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l05-mc-error-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bao nhiêu cá thể là đủ? Sai số Monte Carlo, PSA và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m05-dynamic-transmission/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M05 · Mô hình lây truyền động</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l01-static-vs-dynamic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Mô hình tĩnh và mô hình lây truyền động</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l02-sir-seir-desolve.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình SIR và SEIR trong R với deSolve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l03-vaccination-herd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Tiêm chủng, hiệu quả trực tiếp và gián tiếp</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l04-dengue-host-vector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Mô hình vật chủ–véc tơ cho sốt xuất huyết Dengue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l05-dynamic-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế với mô hình lây truyền động</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m06-amr-economics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M06 · Kinh tế học kháng kháng sinh (AMR)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l01-amr-burden.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l02-attributable-los.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l03-ward-transmission.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Mô hình lây truyền CRE trong khoa hồi sức</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l04-two-strain-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m07-survival-psm/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M07 · Phân tích sống còn cho mô hình quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l01-survival-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ôn tập phân tích sống còn cho người làm mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l02-parametric-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình sống còn tham số với flexsurv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l03-extrapolation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Ngoại suy sống còn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l04-reconstruct-ipd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tái tạo dữ liệu cá thể từ đường KM đã công bố và dùng HR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l05-partitioned-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Mô hình sống còn phân vùng trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m08-calibration/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M08 · Hiệu chuẩn mô hình (calibration)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l01-why-calibrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l02-search-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l03-bayes-sir.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hiệu chuẩn Bayes và thuật toán SIR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l04-psa-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đưa kết quả hiệu chuẩn vào PSA, thẩm định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m09-inputs-vietnam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l01-costing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ước tính chi phí cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l05-decision-context.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bối cảnh ra quyết định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m10-policy-bia-equity/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m11-software-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l01-code-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Cấu trúc mã cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l02-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Xác minh và kiểm thử mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l03-version-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quản lý phiên bản với Git và tái lập môi trường với renv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l04-r-package.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đóng gói mô hình thành gói R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l05-shiny-living.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Ứng dụng Shiny và mô hình “sống”</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bảng thuật ngữ Anh–Việt</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../references.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tài liệu tham khảo</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Trong bài</h2>
   
  <ul class="collapse">
  <li><a href="#mục-tiêu-học-tập" id="toc-mục-tiêu-học-tập" class="nav-link active" data-scroll-target="#mục-tiêu-học-tập">Mục tiêu học tập</a></li>
  <li><a href="#ý-chính" id="toc-ý-chính" class="nav-link" data-scroll-target="#ý-chính">Ý chính</a></li>
  <li><a href="#nội-dung" id="toc-nội-dung" class="nav-link" data-scroll-target="#nội-dung">Nội dung</a></li>
  <li><a href="#thực-hành" id="toc-thực-hành" class="nav-link" data-scroll-target="#thực-hành">Thực hành</a></li>
  <li><a href="#bài-tập" id="toc-bài-tập" class="nav-link" data-scroll-target="#bài-tập">Bài tập</a></li>
  <li><a href="#tài-liệu-tham-khảo" id="toc-tài-liệu-tham-khảo" class="nav-link" data-scroll-target="#tài-liệu-tham-khảo">Tài liệu tham khảo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m06-amr-economics/index.html">M06 · Kinh tế học kháng kháng sinh (AMR)</a></li><li class="breadcrumb-item"><a href="../../kb/m06-amr-economics/l02-attributable-los.html"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></h1>
<p class="subtitle lead">Ước tính đúng số ngày nằm viện tăng thêm do nhiễm khuẩn CRE bằng mô hình đa trạng thái trên dữ liệu mô phỏng</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled" title="Vì sao bạn nên quan tâm?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vì sao bạn nên quan tâm?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ở ba ICU nhi của Bệnh viện Nhi Trung ương, trẻ mắc phải CRE trong lúc nằm viện ở lại lâu hơn 6.2 ngày và tốn thêm US$557 so với trẻ không mắc phải <span class="citation" data-cites="garpvall2021admission">(<a href="#ref-garpvall2021admission" role="doc-biblioref">Garpvall và c.s. 2021</a>)</span>. Chỉ riêng tiền giường, giá dịch vụ BHYT của một ngày ICU ở bệnh viện hạng đặc biệt là 1,017,300 VNĐ, bằng 25 bát phở <span class="citation" data-cites="byt2024qd3220">(<a href="#ref-byt2024qd3220" role="doc-biblioref">Bộ Y tế 2024</a>)</span>. Nhưng trẻ nằm lâu có nhiều ngày phơi nhiễm hơn, nên một phần khoảng chênh là những ngày đã nằm <em>trước khi</em> mắc CRE. Trong mô hình của bài, so sánh giản đơn cho số ngày tăng thêm gấp hơn hai lần giá trị thật. Bài này giúp bạn chọn đúng con số ngày nằm viện tăng thêm trước khi đưa nó vào đề xuất kinh phí cho kiểm soát nhiễm khuẩn.</p>
</div>
</div>
<section id="mục-tiêu-học-tập" class="level2">
<h2 class="anchored" data-anchor-id="mục-tiêu-học-tập">Mục tiêu học tập</h2>
<p>Sau bài này, bạn có thể:</p>
<ol type="1">
<li>Giải thích sai lệch phụ thuộc thời gian (time-dependent bias) và vì sao nó thổi phồng thời gian nằm viện (length of stay, LOS) tăng thêm do nhiễm khuẩn bệnh viện.</li>
<li>Chuyển dữ liệu nằm viện sang dạng đa trạng thái và ước tính các nguy cơ tức thời (hazard) chuyển trạng thái bằng tỷ số “số lần chuyển trên thời gian có nguy cơ”.</li>
<li>Tính số ngày nằm viện và xác suất tử vong tăng thêm theo hai kịch bản phản thực của Bài 1, nêu rõ người đối chứng là ai, kèm khoảng tin cậy bootstrap.</li>
<li>Quy đổi số ngày tăng thêm thành chi phí, và nêu giới hạn của cách quy đổi này.</li>
</ol>
</section>
<section id="ý-chính" class="level2">
<h2 class="anchored" data-anchor-id="ý-chính">Ý chính</h2>
<ul>
<li>Nhiễm khuẩn bệnh viện (healthcare-associated infection, NKBV) xảy ra <em>giữa</em> đợt nằm viện. So sánh tổng thời gian nằm viện của người có và không có NKBV tính cả những ngày <em>trước</em> nhiễm khuẩn vào “tác động”. Đó là sai lệch phụ thuộc thời gian; nó thường phóng đại kết quả nhiều lần <span class="citation" data-cites="barnett2011timedependent">(<a href="#ref-barnett2011timedependent" role="doc-biblioref">Barnett và c.s. 2011</a>)</span>.</li>
<li>Mô hình đa trạng thái (multistate model) coi nhiễm khuẩn là một <em>lần chuyển trạng thái</em>, không phải đặc điểm cố định lúc nhập viện <span class="citation" data-cites="schulgen1996estimation beyersmann2006use">(<a href="#ref-schulgen1996estimation" role="doc-biblioref">Schulgen và Schumacher 1996</a>; <a href="#ref-beyersmann2006use" role="doc-biblioref">Beyersmann và c.s. 2006</a>)</span>.</li>
<li>Với nguy cơ tức thời không đổi: <span class="math inline">\(\hat h_{jk}\)</span> = số lần chuyển <span class="math inline">\(j \to k\)</span> chia cho tổng số ngày ở trạng thái <span class="math inline">\(j\)</span>. Thời gian còn lại ở trạng thái <span class="math inline">\(j\)</span> trung bình là <span class="math inline">\(1/h_{j\bullet}\)</span>.</li>
<li>Ra viện còn sống và tử vong là hai nguy cơ cạnh tranh (competing risks). Không được coi tử vong là kiểm duyệt.</li>
<li>Có hai cách chọn người đối chứng: “bỏ nhiễm khuẩn” (không bao giờ nhiễm) và “chưa nhiễm tại thời điểm s” (còn có thể nhiễm về sau). Hai cách cho hai số khác nhau; gói <code>etm</code> tính theo cách thứ hai.</li>
<li>Kiểm tra phương pháp bằng dữ liệu mô phỏng có sẵn “giá trị thật”, kể cả kịch bản nhiễm khuẩn không có tác động gì.</li>
</ul>
</section>
<section id="nội-dung" class="level2">
<h2 class="anchored" data-anchor-id="nội-dung">Nội dung</h2>
<section id="một-so-sánh-trông-có-vẻ-hiển-nhiên" class="level3">
<h3 class="anchored" data-anchor-id="một-so-sánh-trông-có-vẻ-hiển-nhiên">Một so sánh trông có vẻ hiển nhiên</h3>
<p>Ở ba ICU nhi của Bệnh viện Nhi Trung ương, người bệnh mắc phải Enterobacterales kháng carbapenem (carbapenem-resistant Enterobacterales, CRE), tức định cư (colonisation) CRE trong lúc nằm viện, có tổng thời gian nằm viện 3.26 tuần, so với 2.37 tuần ở người không mắc phải <span class="citation" data-cites="garpvall2021admission">(<a href="#ref-garpvall2021admission" role="doc-biblioref">Garpvall và c.s. 2021</a>)</span>. Mẫu gồm 244 người âm tính khi nhập viện và được sàng lọc hơn hai lần. Đây là tổng thời gian nằm viện, không phải thời gian sau nhiễm khuẩn, và định cư khác nhiễm khuẩn: chỉ 14% so với 2% có nhiễm khuẩn bệnh viện xác nhận bằng nuôi cấy. Định cư CRE có làm người bệnh nằm thêm 6.2 ngày không? Chưa chắc. Người nằm viện lâu có nhiều ngày phơi nhiễm hơn nên dễ mắc phải CRE hơn, và một phần khoảng chênh là những ngày đã nằm <em>trước khi</em> mắc phải. Khảo sát toàn quốc công bố năm 2025 cũng chỉ có so sánh thô kiểu này: người nhiễm CRE nằm viện 10.4 ngày, người nhiễm chủng nhạy 8.9 ngày <span class="citation" data-cites="larsson2025burden">(<a href="#ref-larsson2025burden" role="doc-biblioref">Larsson và c.s. 2025</a>)</span>.</p>
<p>Hãy hình dung hai người bệnh giống hệt nhau. Người A nhiễm CRE vào ngày <span class="math inline">\(t\)</span> rồi nằm thêm <span class="math inline">\(u\)</span> ngày. Người B không nhiễm và ra viện đúng ngày <span class="math inline">\(t\)</span>. So sánh giản đơn (naive) quy cả <span class="math inline">\(t + u\)</span> ngày của A cho nhóm “có nhiễm khuẩn”, dù trong <span class="math inline">\(t\)</span> ngày đầu A hoàn toàn giống B. Cơ chế này giống sai lệch thời gian bất tử (immortal time bias): người bệnh phải “trụ lại” trong viện đến lúc bị nhiễm thì mới vào nhóm nhiễm. Trong mô phỏng của Barnett và cộng sự, cách làm bỏ qua thời điểm nhiễm khuẩn luôn ước tính quá cao số ngày tăng thêm <span class="citation" data-cites="barnett2011timedependent">(<a href="#ref-barnett2011timedependent" role="doc-biblioref">Barnett và c.s. 2011</a>)</span>.</p>
</section>
<section id="mô-hình-đa-trạng-thái" class="level3">
<h3 class="anchored" data-anchor-id="mô-hình-đa-trạng-thái">Mô hình đa trạng thái</h3>
<p>Người bệnh vào viện ở trạng thái “chưa nhiễm khuẩn”, từ đó có thể nhiễm khuẩn nhạy carbapenem (CSE), nhiễm CRE, ra viện còn sống hoặc tử vong. Sau khi nhiễm khuẩn, chỉ còn hai lối ra.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>flowchart LR</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  A["Đang nằm viện&lt;br/&gt;chưa nhiễm khuẩn"] --&gt;|"h(A→S)"| S["Nhiễm khuẩn nhạy&lt;br/&gt;(CSE)"]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  A --&gt;|"h(A→R)"| R["Nhiễm khuẩn CRE"]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  A --&gt; D["Ra viện còn sống"]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  A --&gt; X["Tử vong"]</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  S --&gt; D</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  S --&gt; X</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  R --&gt; D</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  R --&gt; X</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  A["Đang nằm viện&lt;br/&gt;chưa nhiễm khuẩn"] --&gt;|"h(A→S)"| S["Nhiễm khuẩn nhạy&lt;br/&gt;(CSE)"]
  A --&gt;|"h(A→R)"| R["Nhiễm khuẩn CRE"]
  A --&gt; D["Ra viện còn sống"]
  A --&gt; X["Tử vong"]
  S --&gt; D
  S --&gt; X
  R --&gt; D
  R --&gt; X
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Dữ liệu được chuyển sang dạng “đợt” (episode): mỗi người bệnh có một dòng cho mỗi trạng thái đã đi qua, với thời điểm vào, thời điểm ra và trạng thái đến. Người bệnh nhiễm CRE vào ngày <span class="math inline">\(t_1\)</span> và ra viện ngày <span class="math inline">\(t_2\)</span> có hai dòng: (chưa nhiễm, <span class="math inline">\(0\)</span>, <span class="math inline">\(t_1\)</span>, CRE) và (CRE, <span class="math inline">\(t_1\)</span>, <span class="math inline">\(t_2\)</span>, ra viện). Thời gian trước nhiễm khuẩn được tính cho trạng thái “chưa nhiễm”, đúng chỗ của nó.</p>
<p>Nếu nguy cơ tức thời không đổi theo thời gian, ước lượng hợp lý cực đại của nguy cơ chuyển <span class="math inline">\(j \to k\)</span> là</p>
<p><span class="math display">\[
\hat h_{jk} = \frac{d_{jk}}{T_j},
\]</span></p>
<p>với <span class="math inline">\(d_{jk}\)</span> là số lần chuyển quan sát được và <span class="math inline">\(T_j\)</span> là tổng số ngày mọi người bệnh đã ở trạng thái <span class="math inline">\(j\)</span>. Người bị kiểm duyệt (censoring) vẫn đóng góp thời gian vào <span class="math inline">\(T_j\)</span> nhưng không đóng góp sự kiện. Từ các <span class="math inline">\(\hat h\)</span>, ta tính số đo vượt trội như ở Bài 1. Có hai cách chọn người đối chứng, và chúng trả lời hai câu hỏi khác nhau.</p>
<p><strong>(i) Bỏ nhiễm khuẩn</strong> (infection removed): đối chứng là người không bao giờ nhiễm khuẩn. Số ngày tăng thêm mỗi ca CRE là</p>
<p><span class="math display">\[
e_R^{\text{bỏ}} = \frac{1}{h_{R\to\text{ra viện}} + h_{R\to\text{tử vong}}} - \frac{1}{h_{A\to\text{ra viện}} + h_{A\to\text{tử vong}}}.
\]</span></p>
<p>Đây là câu hỏi của can thiệp ngăn nhiễm khuẩn (Bài 1 và Bài 5): nếu ca nhiễm không xảy ra thì người bệnh nằm bao lâu?</p>
<p><strong>(ii) Chưa nhiễm tại thời điểm <span class="math inline">\(s\)</span></strong> (not yet infected): đối chứng là người cùng nằm viện, chưa nhiễm khuẩn, <em>nhưng vẫn có thể nhiễm về sau</em>. Cách này so sánh người đã nhiễm với người chưa nhiễm ở từng ngày, rồi lấy trung bình theo phân phối thời điểm nhiễm khuẩn <span class="citation" data-cites="schulgen1996estimation beyersmann2006use stewardson2016health">(<a href="#ref-schulgen1996estimation" role="doc-biblioref">Schulgen và Schumacher 1996</a>; <a href="#ref-beyersmann2006use" role="doc-biblioref">Beyersmann và c.s. 2006</a>; <a href="#ref-stewardson2016health" role="doc-biblioref">Stewardson và c.s. 2016</a>)</span>. Gói <code>etm</code> <span class="citation" data-cites="allignol2011empirical">(<a href="#ref-allignol2011empirical" role="doc-biblioref">Allignol, Schumacher, và Beyersmann 2011</a>)</span> có hàm <code>clos()</code> tính theo cách này (Bài tập 4 kiểm tra điều đó). Với nguy cơ không đổi, thời gian còn lại của người chưa nhiễm là</p>
<p><span class="math display">\[
L_A = \frac{1 + h_{AS}\,L_S + h_{AR}\,L_R}{h_A},
\]</span></p>
<p>với <span class="math inline">\(h_A\)</span> là tổng nguy cơ rời trạng thái “chưa nhiễm”, <span class="math inline">\(h_{AS}\)</span> và <span class="math inline">\(h_{AR}\)</span> là nguy cơ nhiễm khuẩn nhạy và kháng, <span class="math inline">\(L_S\)</span> và <span class="math inline">\(L_R\)</span> là thời gian còn lại sau nhiễm khuẩn. Vì nhiễm khuẩn làm kéo dài thời gian nằm viện, đối chứng này (còn có thể nhiễm về sau) ở lại lâu hơn đối chứng (i), nên số ngày tăng thêm nhỏ hơn. Hãy chọn theo câu hỏi chính sách: đánh giá can thiệp ngăn nhiễm khuẩn cần (i); kết quả của <code>clos</code> trả lời câu hỏi (ii). Khi nguy cơ thay đổi theo thời gian, như trong hầu hết dữ liệu thật, dùng ước lượng không tham số Aalen–Johansen (<code>etm</code>); logic của hai đối chứng vẫn như trên.</p>
</section>
<section id="từ-số-ngày-đến-chi-phí" class="level3">
<h3 class="anchored" data-anchor-id="từ-số-ngày-đến-chi-phí">Từ số ngày đến chi phí</h3>
<p>Như ở Bài 1, chi phí bằng <em>lượng</em> (số ngày giường và ngày kháng sinh tăng thêm) nhân <em>giá</em>: giá dịch vụ BHYT cho ngày giường <span class="citation" data-cites="byt2024qd3220">(<a href="#ref-byt2024qd3220" role="doc-biblioref">Bộ Y tế 2024</a>)</span> và giá trúng thầu cho kháng sinh, đưa về năm 2025 <span class="citation" data-cites="thainguyen2023thau cuchi2024thau">(<a href="#ref-thainguyen2023thau" role="doc-biblioref">Bệnh viện Trung ương Thái Nguyên 2023</a>; <a href="#ref-cuchi2024thau" role="doc-biblioref">Bệnh viện Đa khoa khu vực Củ Chi 2024</a>)</span>. Ngày giường là chi phí cơ hội chứ không phải tiền mặt. Hãy tách riêng chi phí biến đổi (thuốc, vật tư) nếu người ra quyết định cần biết tiền mặt <span class="citation" data-cites="graves2010estimating">(<a href="#ref-graves2010estimating" role="doc-biblioref">Graves và c.s. 2010</a>)</span>.</p>
</section>
</section>
<section id="thực-hành" class="level2">
<h2 class="anchored" data-anchor-id="thực-hành">Thực hành</h2>
<p>Ta mô phỏng dữ liệu từ các nguy cơ tức thời trong <code>params/los_sim.csv</code>, nên biết giá trị thật (<code>truth</code>) để kiểm tra phương pháp. Nguy cơ tử vong sau nhiễm khuẩn được chọn để xác suất tử vong khớp số thô của khảo sát toàn quốc (31.7% sau CRE, 20.2% sau nhiễm khuẩn nhạy); các nguy cơ khác là giá trị minh họa. Thời gian nằm viện còn lại sau nhiễm khuẩn trong mô hình là 16.7 ngày (CRE) và 14.3 ngày (nhiễm khuẩn nhạy), dài hơn tổng thời gian nằm viện thô của khảo sát toàn quốc (10.4 và 8.9 ngày). Chênh lệch CRE so với nhiễm khuẩn nhạy thì cùng bậc: 2.4 ngày trong mô hình, 1.5 ngày trong khảo sát. Vì vậy hãy đọc mức tuyệt đối của số ngày và chi phí trong bài như minh họa phương pháp.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">isTRUE</span>(<span class="fu">l10n_info</span>()[[<span class="st">"UTF-8"</span>]])) <span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_CTYPE"</span>, <span class="st">"en_US.UTF-8"</span>))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/helpers.R"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/vn_data.R"</span>)   <span class="co"># course-wide values: vn_context(), vn_prices(), vn_mx(), inflate_vnd()</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"code/model.R"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)          <span class="co"># Cox models with time-dependent covariates (comes with R)</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">read_all_params</span>()</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>H_true <span class="ot">&lt;-</span> <span class="fu">ms_hazards_true</span>(p)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>truth <span class="ot">&lt;-</span> <span class="fu">excess_measures</span>(H_true)   <span class="co"># known because we simulate the data ourselves</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>N_PATIENTS <span class="ot">&lt;-</span> p<span class="sc">$</span>n_cohort           <span class="co"># simulation size (a large tertiary hospital, ~1 year; params/los_sim.csv)</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>N_BOOT <span class="ot">&lt;-</span> <span class="dv">200</span>                      <span class="co"># bootstrap resamples (use &gt;= 1,000 for a paper)</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>N_BIG <span class="ot">&lt;-</span> <span class="dv">400000</span>                    <span class="co"># size of the large-sample check</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>s_day <span class="ot">&lt;-</span> <span class="dv">5</span>                         <span class="co"># day at which we look at who is still uninfected (estimand check)</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>N_HI <span class="ot">&lt;-</span> <span class="dv">8000</span>                       <span class="co"># Exercise 4: admissions simulated ...</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>H_INF_HI <span class="ot">&lt;-</span> <span class="fl">0.1</span>                    <span class="co"># ... with this (high) CRE infection hazard per day</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mỗi dòng của <code>d</code> là một trong 20,000 lượt nhập viện: loại nhiễm khuẩn, ngày nhiễm khuẩn, thời gian nằm viện và kết cục. Kiểm tra: số dòng đúng, và ngày nhiễm khuẩn không vượt quá ngày ra viện.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20261008</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">simulate_admissions</span>(p, N_PATIENTS)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d, <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  id inf_type    t_inf       los outcome
1  1     none       NA 18.377668   Disch
2  2     none       NA  1.474369   Disch
3  3     none       NA 12.676851   Disch
4  4        R 2.811902  5.967122   Disch</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">infection =</span> d<span class="sc">$</span>inf_type, <span class="at">outcome =</span> d<span class="sc">$</span>outcome)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         outcome
infection  Cens  Dead Disch
     none     0  1368 17423
     R        4   168   321
     S        5   140   571</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checks: one row per admission, infection happens during the stay, stays are positive</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">nrow</span>(d) <span class="sc">==</span> N_PATIENTS, <span class="fu">all</span>(d<span class="sc">$</span>los <span class="sc">&gt;</span> <span class="dv">0</span>),</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(d<span class="sc">$</span>t_inf[d<span class="sc">$</span>inf_type <span class="sc">!=</span> <span class="st">"none"</span>] <span class="sc">&lt;=</span> d<span class="sc">$</span>los[d<span class="sc">$</span>inf_type <span class="sc">!=</span> <span class="st">"none"</span>]))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>n_inf_r <span class="ot">&lt;-</span> <span class="fu">sum</span>(d<span class="sc">$</span>inf_type <span class="sc">==</span> <span class="st">"R"</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>n_inf_s <span class="ot">&lt;-</span> <span class="fu">sum</span>(d<span class="sc">$</span>inf_type <span class="sc">==</span> <span class="st">"S"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Có 493 ca nhiễm CRE và 716 ca nhiễm CSE. Thử so sánh giản đơn (naive): trung bình tổng thời gian nằm viện của người có nhiễm khuẩn trừ đi của người không nhiễm. Dòng cuối là ngày nhiễm khuẩn trung bình.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Naive (simple) analysis: compare the mean total stay of infected and uninfected patients</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>naive <span class="ot">&lt;-</span> <span class="fu">naive_excess</span>(d)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">rbind</span>(<span class="at">truth =</span> truth, <span class="at">naive =</span> naive)[, <span class="fu">c</span>(<span class="st">"los_R_none"</span>, <span class="st">"los_S_none"</span>, <span class="st">"los_R_S"</span>)], <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      los_R_none los_S_none los_R_S
truth       7.41       5.03    2.38
naive      15.83      13.75    2.08</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Why: an infected patient must first stay long enough to become infected</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>mean_t_inf <span class="ot">&lt;-</span> <span class="fu">tapply</span>(d<span class="sc">$</span>t_inf, d<span class="sc">$</span>inf_type, mean)[<span class="fu">c</span>(<span class="st">"S"</span>, <span class="st">"R"</span>)]   <span class="co"># mean day of infection</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(mean_t_inf, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  S   R 
8.9 8.5 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>naive_ratio <span class="ot">&lt;-</span> naive[[<span class="st">"los_R_none"</span>]] <span class="sc">/</span> truth[[<span class="st">"los_R_none"</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>So sánh giản đơn cho 15.8 ngày tăng thêm mỗi ca CRE, gấp 2.1 lần giá trị thật 7.4 ngày. Người nhiễm CRE đã nằm viện trung bình 8.5 ngày trước khi bị nhiễm, và so sánh giản đơn quy cả những ngày đó cho nhiễm khuẩn.</p>
<p>Chuyển dữ liệu sang dạng đợt và ước tính các nguy cơ tức thời. Kiểm tra: tổng thời gian có nguy cơ của mọi đợt bằng tổng số ngày nằm viện. Bảng in ước lượng (trên) và giá trị thật (dưới).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Multistate (episode) format: one row per state visited</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>ms <span class="ot">&lt;-</span> <span class="fu">to_multistate</span>(d)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ms[ms<span class="sc">$</span>id <span class="sc">%in%</span> d<span class="sc">$</span>id[d<span class="sc">$</span>inf_type <span class="sc">==</span> <span class="st">"R"</span>][<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], ])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      id from    to     entry       exit
4      4  Adm  InfR 0.0000000  2.8119020
20001  4 InfR Disch 2.8119020  5.9671223
6      6  Adm  InfR 0.0000000  0.1361436
20002  6 InfR Disch 0.1361436 31.0479916</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check: total time at risk across episodes equals total hospital days</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(<span class="fu">sum</span>(ms<span class="sc">$</span>exit <span class="sc">-</span> ms<span class="sc">$</span>entry) <span class="sc">-</span> <span class="fu">sum</span>(d<span class="sc">$</span>los)) <span class="sc">&lt;</span> <span class="fl">1e-6</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>H_hat <span class="ot">&lt;-</span> <span class="fu">estimate_hazards</span>(ms)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">rbind</span>(H_hat, H_true), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       InfS   InfR  Disch   Dead
Adm  0.0041 0.0028 0.1002 0.0079
InfS 0.0000 0.0000 0.0588 0.0144
InfR 0.0000 0.0000 0.0407 0.0213
Adm  0.0040 0.0030 0.1000 0.0080
InfS 0.0000 0.0000 0.0559 0.0141
InfR 0.0000 0.0000 0.0410 0.0190</code></pre>
</div>
</div>
<p>Đưa các nguy cơ ước lượng vào hàm <code>excess_measures()</code> của Bài 1 (đối chứng “bỏ nhiễm khuẩn”) và so với giá trị thật và so sánh giản đơn. Kiểm tra: ước lượng đa trạng thái gần giá trị thật, còn so sánh giản đơn thì không.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ms_est <span class="ot">&lt;-</span> <span class="fu">excess_measures</span>(H_hat)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="at">truth =</span> truth, <span class="at">naive =</span> naive, <span class="at">multistate =</span> ms_est)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(res, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           los_R_none los_S_none los_R_S death_R_none death_S_none death_R_S
truth           7.407      5.026   2.381        0.243        0.128     0.115
naive          15.831     13.754   2.078        0.268        0.123     0.145
multistate      6.888      4.399   2.488        0.271        0.124     0.147</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The multistate estimate is close to the truth; the naive one is not</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(ms_est[[<span class="st">"los_R_none"</span>]] <span class="sc">-</span> truth[[<span class="st">"los_R_none"</span>]]) <span class="sc">&lt;</span> <span class="dv">2</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>          naive[[<span class="st">"los_R_none"</span>]] <span class="sc">&gt;</span> <span class="fl">1.5</span> <span class="sc">*</span> truth[[<span class="st">"los_R_none"</span>]])</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># CRE vs CSE is much less biased than CRE vs no infection (both groups had to "survive" to infection)</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(naive[[<span class="st">"los_R_S"</span>]] <span class="sc">-</span> truth[[<span class="st">"los_R_S"</span>]]) <span class="sc">&lt;</span> <span class="fu">abs</span>(naive[[<span class="st">"los_R_none"</span>]] <span class="sc">-</span> truth[[<span class="st">"los_R_none"</span>]]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Tính cả hai đối chứng cho cùng bộ nguy cơ thật. Đoạn mã còn kiểm tra công thức <span class="math inline">\(L_A\)</span> bằng dữ liệu mô phỏng: thời gian còn lại của người chưa nhiễm ở ngày thứ 5 phải khớp với công thức.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Two comparators for the same infected patient (constant hazards):</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   infection removed: never infected                  stay = 1 / (h_dis0 + h_dth0)</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   not yet infected : in hospital, may be infected later   stay = (1 + h_AS * L_S + h_AR * L_R) / h_A</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>notyet <span class="ot">&lt;-</span> <span class="fu">excess_measures_notyet</span>(H_true)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>est_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">comparator =</span> <span class="fu">c</span>(<span class="st">"infection removed"</span>, <span class="st">"not yet infected"</span>),</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">los_R =</span> <span class="fu">c</span>(truth[[<span class="st">"los_R_none"</span>]], notyet[[<span class="st">"los_R_notyet"</span>]]),</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">los_S =</span> <span class="fu">c</span>(truth[[<span class="st">"los_S_none"</span>]], notyet[[<span class="st">"los_S_notyet"</span>]]),</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">death_R =</span> <span class="fu">c</span>(truth[[<span class="st">"death_R_none"</span>]], notyet[[<span class="st">"death_R_notyet"</span>]]),</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">death_S =</span> <span class="fu">c</span>(truth[[<span class="st">"death_S_none"</span>]], notyet[[<span class="st">"death_S_notyet"</span>]])</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>est_tab_show <span class="ot">&lt;-</span> est_tab</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>est_tab_show[, <span class="sc">-</span><span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(est_tab_show[, <span class="sc">-</span><span class="dv">1</span>], <span class="dv">3</span>)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>est_tab_show</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         comparator los_R los_S death_R death_S
1 infection removed 7.407 5.026   0.243   0.128
2  not yet infected 7.039 4.658   0.232   0.117</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the formula for the "not yet infected" stay against the simulated data: among patients</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># still in hospital and uninfected on day 5, the mean remaining stay must match it (the</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># exponential model has no memory). Censoring at 90 days is negligible for this group.</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>at_risk <span class="ot">&lt;-</span> d<span class="sc">$</span>los <span class="sc">&gt;</span> s_day <span class="sc">&amp;</span> (d<span class="sc">$</span>inf_type <span class="sc">==</span> <span class="st">"none"</span> <span class="sc">|</span> d<span class="sc">$</span>t_inf <span class="sc">&gt;</span> s_day)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>sim_notyet <span class="ot">&lt;-</span> <span class="fu">mean</span>(d<span class="sc">$</span>los[at_risk] <span class="sc">-</span> s_day)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">formula =</span> <span class="fu">ms_notyet_infected</span>(H_true)[[<span class="st">"los"</span>]], <span class="at">simulated =</span> sim_notyet, <span class="at">n =</span> <span class="fu">sum</span>(at_risk)), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  formula simulated         n 
     9.63      9.78  11074.00 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(sim_notyet <span class="sc">-</span> <span class="fu">ms_notyet_infected</span>(H_true)[[<span class="st">"los"</span>]]) <span class="sc">&lt;</span> <span class="fl">0.4</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(notyet[[<span class="st">"los_R_notyet"</span>]] <span class="sc">&lt;</span> truth[[<span class="st">"los_R_none"</span>]])   <span class="co"># the later-infection option shortens the contrast</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Hai đối chứng cho hai số khác nhau với cùng nguy cơ thật: 7.0 ngày cho “chưa nhiễm tại thời điểm <span class="math inline">\(s\)</span>”, so với 7.4 ngày cho “bỏ nhiễm khuẩn”; tử vong tăng thêm là 23.2 so với 24.3 điểm phần trăm. Công thức khớp với mô phỏng (9.8 so với 9.6 ngày).</p>
<p>Ước lượng đúng phải tìm lại được giá trị thật khi mẫu rất lớn; so sánh giản đơn thì không. Ta thử với 400,000 lượt nhập viện.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># With a very large sample the multistate estimate must recover the truth; the naive one must not</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">77</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>d_big <span class="ot">&lt;-</span> <span class="fu">simulate_admissions</span>(p, N_BIG)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>est_big <span class="ot">&lt;-</span> <span class="fu">excess_measures</span>(<span class="fu">estimate_hazards</span>(<span class="fu">to_multistate</span>(d_big)))</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>naive_big <span class="ot">&lt;-</span> <span class="fu">naive_excess</span>(d_big)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">rbind</span>(<span class="at">truth =</span> truth, <span class="at">multistate =</span> est_big, <span class="at">naive =</span> naive_big)[, <span class="fu">c</span>(<span class="st">"los_R_none"</span>, <span class="st">"los_R_S"</span>, <span class="st">"death_R_none"</span>)], <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           los_R_none los_R_S death_R_none
truth           7.407   2.381        0.243
multistate      7.451   2.421        0.236
naive          16.486   2.190        0.233</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>tol <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">los_R_none =</span> <span class="fl">0.7</span>, <span class="at">los_S_none =</span> <span class="fl">0.7</span>, <span class="at">los_R_S =</span> <span class="fl">0.9</span>, <span class="at">death_R_none =</span> <span class="fl">0.02</span>, <span class="at">death_S_none =</span> <span class="fl">0.02</span>, <span class="at">death_R_S =</span> <span class="fl">0.03</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(est_big <span class="sc">-</span> truth) <span class="sc">&lt;</span> tol), naive_big[[<span class="st">"los_R_none"</span>]] <span class="sc">-</span> truth[[<span class="st">"los_R_none"</span>]] <span class="sc">&gt;</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Với mẫu lớn, mô hình đa trạng thái cho 7.5 ngày (giá trị thật 7.4), còn so sánh giản đơn vẫn cho 16.5 ngày: sai lệch không biến mất khi có thêm dữ liệu.</p>
<p>Để có khoảng tin cậy, lấy mẫu lại người bệnh (bootstrap) 200 lần và lặp lại toàn bộ quy trình; một bài báo nên dùng nhiều lần lặp hơn.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>boot <span class="ot">&lt;-</span> <span class="fu">boot_excess</span>(d, N_BOOT)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">apply</span>(boot, <span class="dv">2</span>, quantile, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">rbind</span>(<span class="at">estimate =</span> ms_est, ci), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         los_R_none los_S_none los_R_S death_R_none death_S_none death_R_S
estimate      6.888      4.399   2.488        0.271        0.124     0.147
2.5%          5.462      3.322   0.794        0.223        0.097     0.094
97.5%         8.316      5.434   4.405        0.307        0.154     0.198</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>covered <span class="ot">&lt;-</span> truth <span class="sc">&gt;=</span> ci[<span class="dv">1</span>, ] <span class="sc">&amp;</span> truth <span class="sc">&lt;=</span> ci[<span class="dv">2</span>, ]</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>covered</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  los_R_none   los_S_none      los_R_S death_R_none death_S_none    death_R_S 
        TRUE         TRUE         TRUE         TRUE         TRUE         TRUE </code></pre>
</div>
</div>
<p>Mô hình đa trạng thái ước tính 6.9 (KTC 95%: 5.5–8.3) ngày tăng thêm mỗi ca CRE so với không nhiễm khuẩn, và 2.5 (KTC 95%: 0.8–4.4) ngày so với nhiễm khuẩn nhạy. Có 6 trên 6 khoảng tin cậy chứa giá trị thật. Với so sánh giản đơn, phép so sánh CRE với CSE ít bị sai lệch hơn (2.1 so với giá trị thật 2.4 ngày), vì cả hai nhóm đều phải “trụ lại” đến lúc nhiễm khuẩn. Với tử vong, so sánh giản đơn cho 26.8 điểm phần trăm, gần với mô hình đa trạng thái (27.1) và giá trị thật (24.3); với nguy cơ không đổi, sai lệch thời gian chủ yếu ảnh hưởng đến số ngày. Với dữ liệu thật, vấn đề lớn hơn thường là gây nhiễu do mức độ nặng.</p>
<p>Mô hình Cox cho cùng thông điệp trên thang tỷ số nguy cơ tức thời (hazard ratio, HR). Sự kiện là “rời bệnh viện” (ra viện hoặc tử vong); HR nhỏ hơn 1 nghĩa là nằm viện lâu hơn. Gói <code>survival</code> đi kèm R; <code>Surv(entry, exit, event)</code> nhận dữ liệu dạng đợt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Hazard of leaving hospital (discharge or death). True hazard ratios: exit rate after</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># infection divided by exit rate before infection.</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>ms<span class="sc">$</span>end_stay <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(ms<span class="sc">$</span>to <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Disch"</span>, <span class="st">"Dead"</span>))</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>ms<span class="sc">$</span>inf_s <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(ms<span class="sc">$</span>from <span class="sc">==</span> <span class="st">"InfS"</span>)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>ms<span class="sc">$</span>inf_r <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(ms<span class="sc">$</span>from <span class="sc">==</span> <span class="st">"InfR"</span>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>cox_td <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(entry, exit, end_stay) <span class="sc">~</span> inf_s <span class="sc">+</span> inf_r, <span class="at">data =</span> ms)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>ever_s <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(d<span class="sc">$</span>inf_type <span class="sc">==</span> <span class="st">"S"</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>ever_r <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(d<span class="sc">$</span>inf_type <span class="sc">==</span> <span class="st">"R"</span>)</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>cox_fixed <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(los, outcome <span class="sc">!=</span> <span class="st">"Cens"</span>) <span class="sc">~</span> ever_s <span class="sc">+</span> ever_r, <span class="at">data =</span> d)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>exit0 <span class="ot">&lt;-</span> <span class="fu">sum</span>(H_true[<span class="st">"Adm"</span>, <span class="fu">c</span>(<span class="st">"Disch"</span>, <span class="st">"Dead"</span>)])</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>hr_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">truth =</span> <span class="fu">c</span>(<span class="fu">sum</span>(H_true[<span class="st">"InfS"</span>, <span class="fu">c</span>(<span class="st">"Disch"</span>, <span class="st">"Dead"</span>)]), <span class="fu">sum</span>(H_true[<span class="st">"InfR"</span>, <span class="fu">c</span>(<span class="st">"Disch"</span>, <span class="st">"Dead"</span>)])) <span class="sc">/</span> exit0,</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">time_dependent =</span> <span class="fu">unname</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(cox_td))),</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">time_fixed =</span> <span class="fu">unname</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(cox_fixed))),</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">row.names =</span> <span class="fu">c</span>(<span class="st">"CSE"</span>, <span class="st">"CRE"</span>)</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(hr_tab, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    truth time_dependent time_fixed
CSE 0.648          0.688      0.373
CRE 0.556          0.581      0.340</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Treating infection as fixed from admission exaggerates the effect (HR further below 1)</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(hr_tab<span class="sc">$</span>time_fixed <span class="sc">&lt;</span> hr_tab<span class="sc">$</span>time_dependent))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mô hình có biến phụ thuộc thời gian cho HR 0.58 cho CRE, gần giá trị thật 0.56. Mô hình coi nhiễm khuẩn là đặc điểm cố định cho 0.34, tức là phóng đại tác động kéo dài nằm viện. Dù vậy, HR không phải là số ngày; người ra quyết định cần số ngày và tiền.</p>
<p>Hình tóm tắt ba phép so sánh bằng ba phương pháp. Kiểm tra: thanh của mô hình đa trạng thái nằm gần giá trị thật, thanh giản đơn của hai phép so sánh với “không nhiễm” cao hơn hẳn.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>cmp <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"los_R_none"</span>, <span class="st">"los_S_none"</span>, <span class="st">"los_R_S"</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>cmp_vi <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">los_R_none =</span> <span class="st">"CRE so với không nhiễm"</span>, <span class="at">los_S_none =</span> <span class="st">"CSE so với không nhiễm"</span>,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">los_R_S =</span> <span class="st">"CRE so với CSE"</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>plot_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">comparison =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(cmp_vi[cmp], <span class="dv">3</span>), <span class="at">levels =</span> cmp_vi),</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Giá trị thật (mô phỏng)"</span>, <span class="st">"So sánh giản đơn (naive)"</span>, <span class="st">"Mô hình đa trạng thái"</span>),</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">each =</span> <span class="dv">3</span>),</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Giá trị thật (mô phỏng)"</span>, <span class="st">"So sánh giản đơn (naive)"</span>, <span class="st">"Mô hình đa trạng thái"</span>)),</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">c</span>(truth[cmp], naive[cmp], ms_est[cmp]),</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">lo =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">6</span>), ci[<span class="dv">1</span>, cmp]),</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">hi =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">6</span>), ci[<span class="dv">2</span>, cmp])</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>fig_bias <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(plot_df, <span class="fu">aes</span>(comparison, value, <span class="at">fill =</span> method)) <span class="sc">+</span></span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.8</span>), <span class="at">width =</span> <span class="fl">0.75</span>) <span class="sc">+</span></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.8</span>),</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> pal_course[<span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">2</span>, <span class="dv">1</span>)], <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Số ngày nằm viện tăng thêm mỗi ca nhiễm khuẩn"</span>,</span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Sai lệch phụ thuộc thời gian: so sánh giản đơn thổi phồng số ngày tăng thêm"</span>,</span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Dữ liệu mô phỏng; thanh lỗi = KTC 95% bootstrap"</span>) <span class="sc">+</span></span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_bias, <span class="st">"l02-time-dependent-bias.png"</span>, <span class="at">width =</span> <span class="dv">8</span>, <span class="at">height =</span> <span class="fl">4.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l02-time-dependent-bias.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Số ngày nằm viện tăng thêm mỗi ca nhiễm khuẩn: giá trị thật, so sánh giản đơn và mô hình đa trạng thái (dữ liệu mô phỏng).</figcaption>
</figure>
</div>
<p>Cuối cùng, quy đổi ra tiền với chi phí đơn vị của Bài 1 (ngày giường tính theo hỗn hợp ICU và khoa thường; tỷ lệ ICU là minh họa). Kiểm tra: mọi chi phí dương, và chi phí liên quan lớn hơn chi phí quy thuộc. Dòng cuối là tỷ trọng tiền kháng sinh trong chi phí liên quan.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Excess cost per CRE infection (VND, 2025 prices): BHYT bed-day prices (ICU / ward mix, illustrative split)</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># + antibiotics at tender prices (colistin + high-dose meropenem vs meropenem; ../_shared)</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>cost_per_inf <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">associated =</span> <span class="fu">excess_bed_cost</span>(p, ms_est[[<span class="st">"los_R_none"</span>]]) <span class="sc">+</span> p<span class="sc">$</span>dur_abx <span class="sc">*</span> p<span class="sc">$</span>c_abx_r_day,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">attributable =</span> <span class="fu">excess_bed_cost</span>(p, ms_est[[<span class="st">"los_R_S"</span>]]) <span class="sc">+</span> p<span class="sc">$</span>dur_abx <span class="sc">*</span> (p<span class="sc">$</span>c_abx_r_day <span class="sc">-</span> p<span class="sc">$</span>c_abx_s_day),</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">naive_associated =</span> <span class="fu">excess_bed_cost</span>(p, naive[[<span class="st">"los_R_none"</span>]]) <span class="sc">+</span> p<span class="sc">$</span>dur_abx <span class="sc">*</span> p<span class="sc">$</span>c_abx_r_day</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(cost_per_inf <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">1</span>)    <span class="co"># million VND</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      associated     attributable naive_associated 
            60.1             54.9             66.1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(cost_per_inf <span class="sc">&gt;</span> <span class="dv">0</span>), cost_per_inf[[<span class="st">"associated"</span>]] <span class="sc">&gt;</span> cost_per_inf[[<span class="st">"attributable"</span>]])</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Share of the associated cost that is antibiotics (the rest is bed-days)</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>drug_share <span class="ot">&lt;-</span> p<span class="sc">$</span>dur_abx <span class="sc">*</span> p<span class="sc">$</span>c_abx_r_day <span class="sc">/</span> cost_per_inf[[<span class="st">"associated"</span>]]</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(drug_share, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.92</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Relative error of the naive comparison: on the days, and on the cost</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>rel_err <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">days =</span> naive[[<span class="st">"los_R_none"</span>]] <span class="sc">/</span> ms_est[[<span class="st">"los_R_none"</span>]] <span class="sc">-</span> <span class="dv">1</span>,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">cost =</span> cost_per_inf[[<span class="st">"naive_associated"</span>]] <span class="sc">/</span> cost_per_inf[[<span class="st">"associated"</span>]] <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(rel_err, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>days cost 
 1.3  0.1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(rel_err[[<span class="st">"cost"</span>]] <span class="sc">&lt;</span> rel_err[[<span class="st">"days"</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mỗi ca CRE tốn thêm 60.1 triệu VNĐ so với không nhiễm khuẩn và 54.9 triệu VNĐ so với nhiễm khuẩn nhạy (giá 2025). Nếu dùng so sánh giản đơn, con số đầu sẽ là 66.1 triệu VNĐ. Vì một ngày colistin phối hợp meropenem đắt gấp 3.9 lần một ngày giường ICU, tiền kháng sinh chiếm 92% chi phí liên quan; sai lệch phụ thuộc thời gian chỉ làm sai phần ngày giường, nên ở đây nó thổi phồng chi phí 10% trong khi thổi phồng số ngày 130% (cùng lấy ước lượng đa trạng thái làm mốc). Với một can thiệp chỉ rút ngắn thời gian nằm viện, sai số ngày lại là tất cả.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Mẹo thực hành">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mẹo thực hành
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Khi xin dữ liệu bệnh viện, phải có <strong>ngày nhập viện, ngày khởi phát nhiễm khuẩn (hoặc ngày lấy mẫu dương tính), ngày ra viện và kết cục</strong>. Thiếu ngày nhiễm khuẩn thì không thể sửa sai lệch phụ thuộc thời gian.</li>
<li>Thử phương pháp trên dữ liệu mô phỏng có tác động bằng 0 (Bài tập 1). Phương pháp nào “tìm thấy” tác động ở đó thì không dùng được.</li>
<li>Với dữ liệu thật, nguy cơ tức thời hiếm khi không đổi. Hãy vẽ nguy cơ tích lũy theo thời gian trước khi chọn mô hình hằng số.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Lỗi thường gặp">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lỗi thường gặp
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Ghép cặp hoặc hồi quy trên tổng thời gian nằm viện</strong> với biến “có NKBV” cố định từ lúc nhập viện. Ghép cặp theo mức độ nặng không sửa được sai lệch phụ thuộc thời gian.</li>
<li><strong>Coi tử vong là kiểm duyệt.</strong> Người tử vong sớm trông như “ra viện nhanh”; phải mô hình hóa tử vong như một lối ra cạnh tranh.</li>
<li><strong>Đọc HR như số ngày.</strong> Cùng một HR có thể ứng với số ngày tăng thêm rất khác nhau, tùy nguy cơ nền.</li>
</ul>
</div>
</div>
</section>
<section id="bài-tập" class="level2">
<h2 class="anchored" data-anchor-id="bài-tập">Bài tập</h2>
<p><strong>Bài 1 (dễ).</strong> Mô phỏng một bệnh viện trong đó nhiễm khuẩn <em>không</em> làm thay đổi nguy cơ ra viện hay tử vong. Hai phương pháp cho kết quả gì?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Đặt nguy cơ sau nhiễm khuẩn bằng nguy cơ trước nhiễm khuẩn, rồi chạy lại cả hai phương pháp.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 1: infection with NO effect on stay (post-infection hazards = pre-infection)</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>p0 <span class="ot">&lt;-</span> p</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>p0<span class="sc">$</span>h_dis_s <span class="ot">&lt;-</span> p<span class="sc">$</span>h_dis_0; p0<span class="sc">$</span>h_dth_s <span class="ot">&lt;-</span> p<span class="sc">$</span>h_dth_0</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>p0<span class="sc">$</span>h_dis_r <span class="ot">&lt;-</span> p<span class="sc">$</span>h_dis_0; p0<span class="sc">$</span>h_dth_r <span class="ot">&lt;-</span> p<span class="sc">$</span>h_dth_0</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11</span>)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>d0 <span class="ot">&lt;-</span> <span class="fu">simulate_admissions</span>(p0, N_PATIENTS)</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>res0 <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="at">truth =</span> <span class="fu">excess_measures</span>(<span class="fu">ms_hazards_true</span>(p0)),</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">naive =</span> <span class="fu">naive_excess</span>(d0),</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">multistate =</span> <span class="fu">excess_measures</span>(<span class="fu">estimate_hazards</span>(<span class="fu">to_multistate</span>(d0))))</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(res0[, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           los_R_none los_S_none los_R_S
truth            0.00       0.00    0.00
naive           10.08       9.12    0.96
multistate       0.16      -0.06    0.21</code></pre>
</div>
</div>
<p>Giá trị thật bằng không. So sánh giản đơn vẫn “tìm thấy” 10.1 ngày tăng thêm mỗi ca CRE; mô hình đa trạng thái cho 0.2 ngày. Toàn bộ con số của so sánh giản đơn là sai lệch.</p>
</div>
</div>
</div>
<p><strong>Bài 2 (vừa).</strong> Nhân ba nguy cơ nhiễm khuẩn (khoa có NKBV cao hơn nhiều, nên có nhiều ca hơn để phân tích). Sai lệch của so sánh giản đơn có giảm không? Hãy tìm công thức cho sai lệch đó khi nguy cơ không đổi.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 2: triple the infection hazards; how do the two methods respond?</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> p</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>p3<span class="sc">$</span>h_inf_s <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="sc">*</span> p<span class="sc">$</span>h_inf_s; p3<span class="sc">$</span>h_inf_r <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="sc">*</span> p<span class="sc">$</span>h_inf_r</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12</span>)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>d3 <span class="ot">&lt;-</span> <span class="fu">simulate_admissions</span>(p3, N_PATIENTS)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>res3 <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="at">truth =</span> <span class="fu">excess_measures</span>(<span class="fu">ms_hazards_true</span>(p3)),</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">naive =</span> <span class="fu">naive_excess</span>(d3),</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">multistate =</span> <span class="fu">excess_measures</span>(<span class="fu">estimate_hazards</span>(<span class="fu">to_multistate</span>(d3))))</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(res3[, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           los_R_none los_S_none los_R_S
truth            7.41       5.03    2.38
naive           16.85      14.08    2.77
multistate       7.69       5.07    2.61</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bias of the naive estimate (CRE vs none) at baseline and with tripled infection hazards</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>bias_naive <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">baseline =</span> naive[[<span class="st">"los_R_none"</span>]] <span class="sc">-</span> truth[[<span class="st">"los_R_none"</span>]],</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">tripled =</span> res3[<span class="st">"naive"</span>, <span class="st">"los_R_none"</span>] <span class="sc">-</span> res3[<span class="st">"truth"</span>, <span class="st">"los_R_none"</span>])</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(bias_naive, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>baseline  tripled 
    8.42     9.44 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># With constant hazards the naive excess stay (R vs none) equals the stay after infection, L_R,</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="co"># exactly, because infected and uninfected patients both leave hospital after 1 / h_A days on</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="co"># average. The true excess is L_R - 1 / h_none, so the bias is 1 / (h_dis0 + h_dth0) whatever</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co"># the infection hazard is. Both simulated biases should match it up to Monte Carlo error.</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>bias_analytic <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> (p<span class="sc">$</span>h_dis_0 <span class="sc">+</span> p<span class="sc">$</span>h_dth_0)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">analytic =</span> bias_analytic, bias_naive), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>analytic baseline  tripled 
    9.26     8.42     9.44 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(bias_naive <span class="sc">-</span> bias_analytic) <span class="sc">&lt;</span> <span class="fl">1.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Giá trị thật không đổi (7.4 ngày) vì tác động của nhiễm khuẩn sau khi xảy ra vẫn như cũ. Sai lệch của so sánh giản đơn là 8.4 ngày ở kịch bản cơ sở và 9.4 ngày khi nguy cơ nhiễm khuẩn tăng ba lần; mô hình đa trạng thái vẫn cho 7.7 ngày. Hai con số này không khác nhau về bản chất: với nguy cơ không đổi, người nhiễm và người không nhiễm đều ra khỏi trạng thái “chưa nhiễm” sau trung bình <span class="math inline">\(1/h_A\)</span> ngày, nên số ngày tăng thêm của so sánh giản đơn đúng bằng thời gian còn lại sau nhiễm khuẩn <span class="math inline">\(L_R\)</span>, và sai lệch đúng bằng <span class="math inline">\(1/(h_{\text{ra viện},0} + h_{\text{tử vong},0}) =\)</span> 9.3 ngày, dù nguy cơ nhiễm khuẩn là bao nhiêu. Khác biệt giữa hai con số mô phỏng chỉ là sai số Monte Carlo (và kiểm duyệt). Nhiều ca hơn làm khoảng tin cậy hẹp lại chứ không sửa được một phép so sánh sai.</p>
</div>
</div>
</div>
<p><strong>Bài 3 (khó).</strong> Với số liệu mô tả của Garpvall và cộng sự, chênh lệch thô về tổng thời gian nằm viện và tổng chi phí giữa người mắc phải và không mắc phải CRE là bao nhiêu? Bạn cần thêm biến nào, và sẽ phân tích thế nào, để ước tính đúng số ngày quy thuộc định cư CRE?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 3: a published descriptive comparison (paediatric ICUs, Viet Nam):</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="co"># total stay of patients who acquired CRE (colonisation) minus that of patients who did not,</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="co"># in days, before any time-dependent correction</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>garpvall_diff_days <span class="ot">&lt;-</span> (p<span class="sc">$</span>garpvall_los_acq <span class="sc">-</span> p<span class="sc">$</span>garpvall_los_noacq) <span class="sc">*</span> <span class="dv">7</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>garpvall_diff_cost <span class="ot">&lt;-</span> p<span class="sc">$</span>garpvall_cost_acq <span class="sc">-</span> p<span class="sc">$</span>garpvall_cost_noacq</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">extra_days =</span> garpvall_diff_days, <span class="at">extra_cost_usd =</span> garpvall_diff_cost), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    extra_days extra_cost_usd 
           6.2          557.0 </code></pre>
</div>
</div>
<p>Chênh lệch thô là 6.2 ngày và US$557 mỗi người bệnh (USD, năm giá không nêu). Đây là chênh lệch của <em>tổng</em> thời gian và chi phí. Cần ngày sàng lọc dương tính đầu tiên của từng người, dùng làm thời điểm định cư; sau đó chuyển sang dạng đợt, ước tính nguy cơ rời viện trước và sau khi nhiễm (Aalen–Johansen nếu nguy cơ thay đổi theo thời gian), và tính số ngày tăng thêm như trong bài.</p>
</div>
</div>
</div>
<p><strong>Bài 4 (khó, tùy chọn).</strong> Hàm <code>clos()</code> của gói <code>etm</code> có tính đúng đối chứng “chưa nhiễm tại thời điểm <span class="math inline">\(s\)</span>” không? Hãy thử ở nơi hai đối chứng khác nhau nhiều: một loại nhiễm khuẩn với nguy cơ cao.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Mô phỏng 8,000 lượt nhập viện với nguy cơ nhiễm CRE 0.1 mỗi ngày, rồi so <code>clos()</code> với hai công thức.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 4 (optional, needs the etm package): the Aalen-Johansen estimator behind etm::clos</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="co"># answers the "not yet infected" question. Test it where the two comparators differ a lot:</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="co"># one infection type with a high hazard (0.1 per day) and no censoring.</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>ex4_ran <span class="ot">&lt;-</span> <span class="fu">requireNamespace</span>(<span class="st">"etm"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>ex4 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">clos =</span> <span class="cn">NA_real_</span>, <span class="at">not_yet_infected =</span> <span class="cn">NA_real_</span>, <span class="at">infection_removed =</span> <span class="cn">NA_real_</span>)   <span class="co"># stays NA without etm</span></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (ex4_ran) {</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>  p_hi <span class="ot">&lt;-</span> p</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>  p_hi<span class="sc">$</span>h_inf_s <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>  p_hi<span class="sc">$</span>h_inf_r <span class="ot">&lt;-</span> H_INF_HI</span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>  p_hi<span class="sc">$</span>max_follow <span class="ot">&lt;-</span> <span class="fl">1e6</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(<span class="dv">21</span>)</span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>  d_hi <span class="ot">&lt;-</span> <span class="fu">simulate_admissions</span>(p_hi, N_HI)</span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a>  ms_hi <span class="ot">&lt;-</span> <span class="fu">to_multistate</span>(d_hi)</span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>  code <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">Adm =</span> <span class="st">"0"</span>, <span class="at">InfR =</span> <span class="st">"1"</span>, <span class="at">Disch =</span> <span class="st">"2"</span>, <span class="at">Dead =</span> <span class="st">"3"</span>)   <span class="co"># etm wants state labels as text</span></span>
<span id="cb54-15"><a href="#cb54-15" aria-hidden="true" tabindex="-1"></a>  dat_hi <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id =</span> ms_hi<span class="sc">$</span>id, <span class="at">from =</span> <span class="fu">unname</span>(code[ms_hi<span class="sc">$</span>from]), <span class="at">to =</span> <span class="fu">unname</span>(code[ms_hi<span class="sc">$</span>to]),</span>
<span id="cb54-16"><a href="#cb54-16" aria-hidden="true" tabindex="-1"></a>                       <span class="at">entry =</span> ms_hi<span class="sc">$</span>entry, <span class="at">exit =</span> ms_hi<span class="sc">$</span>exit, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb54-17"><a href="#cb54-17" aria-hidden="true" tabindex="-1"></a>  tra <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">FALSE</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="fu">unname</span>(code), <span class="fu">unname</span>(code)))</span>
<span id="cb54-18"><a href="#cb54-18" aria-hidden="true" tabindex="-1"></a>  tra[<span class="st">"0"</span>, <span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>)] <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb54-19"><a href="#cb54-19" aria-hidden="true" tabindex="-1"></a>  tra[<span class="st">"1"</span>, <span class="fu">c</span>(<span class="st">"2"</span>, <span class="st">"3"</span>)] <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb54-20"><a href="#cb54-20" aria-hidden="true" tabindex="-1"></a>  tr_hi <span class="ot">&lt;-</span> etm<span class="sc">::</span><span class="fu">etm</span>(dat_hi, <span class="fu">unname</span>(code), tra, <span class="cn">NULL</span>, <span class="dv">0</span>)</span>
<span id="cb54-21"><a href="#cb54-21" aria-hidden="true" tabindex="-1"></a>  clos_los <span class="ot">&lt;-</span> etm<span class="sc">::</span><span class="fu">clos</span>(tr_hi, <span class="at">aw =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>e.phi</span>
<span id="cb54-22"><a href="#cb54-22" aria-hidden="true" tabindex="-1"></a>  s_hi <span class="ot">&lt;-</span> <span class="fu">ms_state_summary</span>(<span class="fu">ms_hazards_true</span>(p_hi))</span>
<span id="cb54-23"><a href="#cb54-23" aria-hidden="true" tabindex="-1"></a>  a_hi <span class="ot">&lt;-</span> <span class="fu">ms_notyet_infected</span>(<span class="fu">ms_hazards_true</span>(p_hi))</span>
<span id="cb54-24"><a href="#cb54-24" aria-hidden="true" tabindex="-1"></a>  ex4 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">clos =</span> clos_los,</span>
<span id="cb54-25"><a href="#cb54-25" aria-hidden="true" tabindex="-1"></a>           <span class="at">not_yet_infected =</span> s_hi<span class="sc">$</span>remaining_los[<span class="dv">3</span>] <span class="sc">-</span> a_hi[[<span class="st">"los"</span>]],</span>
<span id="cb54-26"><a href="#cb54-26" aria-hidden="true" tabindex="-1"></a>           <span class="at">infection_removed =</span> s_hi<span class="sc">$</span>remaining_los[<span class="dv">3</span>] <span class="sc">-</span> s_hi<span class="sc">$</span>remaining_los[<span class="dv">1</span>])</span>
<span id="cb54-27"><a href="#cb54-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stopifnot</span>(<span class="fu">abs</span>(ex4[[<span class="st">"clos"</span>]] <span class="sc">-</span> ex4[[<span class="st">"not_yet_infected"</span>]]) <span class="sc">&lt;</span> <span class="dv">1</span>)   <span class="co"># far closer to this one than to "infection removed"</span></span>
<span id="cb54-28"><a href="#cb54-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(ex4, <span class="dv">2</span>)</span>
<span id="cb54-29"><a href="#cb54-29" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             clos  not_yet_infected infection_removed 
             3.72              3.85              7.41 </code></pre>
</div>
</div>
<p>Hàm <code>clos()</code> cho 3.7 ngày, gần với “chưa nhiễm tại thời điểm <span class="math inline">\(s\)</span>” (3.8 ngày) và xa “bỏ nhiễm khuẩn” (7.4 ngày). Cùng một dữ liệu có thể cho hai con số khác nhau tùy câu hỏi. (Nếu bạn thấy “NA”, hãy cài gói <code>etm</code>.)</p>
</div>
</div>
</div>
</section>
<section id="tài-liệu-tham-khảo" class="level2">
<h2 class="anchored" data-anchor-id="tài-liệu-tham-khảo">Tài liệu tham khảo</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-allignol2011empirical" class="csl-entry" role="listitem">
Allignol, Arthur, Martin Schumacher, và Jan Beyersmann. 2011. <span>“Empirical transition matrix of multi-state models: the <span>etm</span> package”</span>. <em>Journal of Statistical Software</em> 38 (4): 1–15. <a href="https://doi.org/10.18637/jss.v038.i04">https://doi.org/10.18637/jss.v038.i04</a>.
</div>
<div id="ref-barnett2011timedependent" class="csl-entry" role="listitem">
Barnett, Adrian G., Jan Beyersmann, Arthur Allignol, Victor D. Rosenthal, Nicholas Graves, và Martin Wolkewitz. 2011. <span>“The time-dependent bias and its effect on extra length of stay due to nosocomial infection”</span>. <em>Value in Health</em> 14 (2): 381–86. <a href="https://doi.org/10.1016/j.jval.2010.09.008">https://doi.org/10.1016/j.jval.2010.09.008</a>.
</div>
<div id="ref-beyersmann2006use" class="csl-entry" role="listitem">
Beyersmann, J., P. Gastmeier, H. Grundmann, S. Bärwolff, C. Geffers, M. Behnke, và c.s. 2006. <span>“Use of multistate models to assess prolongation of intensive care unit stay due to nosocomial infection”</span>. <em>Infection Control and Hospital Epidemiology</em> 27 (5): 493–99. <a href="https://doi.org/10.1086/503375">https://doi.org/10.1086/503375</a>.
</div>
<div id="ref-cuchi2024thau" class="csl-entry" role="listitem">
Bệnh viện Đa khoa khu vực Củ Chi. 2024. <span>“Danh mục giá thầu thuốc bệnh viện 2024 (Lần 2)”</span>. 2024. <a href="https://bvdkkvcuchi.vn/wp-content/uploads/2024/12/DANH-MUC-THUOC-DANG-WEBSITE-BV-nam-2024-lan-2.pdf">https://bvdkkvcuchi.vn/wp-content/uploads/2024/12/DANH-MUC-THUOC-DANG-WEBSITE-BV-nam-2024-lan-2.pdf</a>.
</div>
<div id="ref-thainguyen2023thau" class="csl-entry" role="listitem">
Bệnh viện Trung ương Thái Nguyên. 2023. <span>“Danh mục thuốc trúng thầu tại Bệnh viện Trung ương Thái Nguyên (áp dụng từ ngày 17/10/2023 theo Quyết định số 1580/<span>QĐ-BVTWTN</span>)”</span>. 17 Tháng Mười 2023. <a href="https://bvdktuthainguyen.gov.vn/uploads/media/tai%20lieu/danh%20muc%20thuoc/thuoc%202022-2023/DM%20thu%E1%BB%91c%20tr%C3%BAng%20th%E1%BA%A7u%202023%20BVTW%20TN%20(1).xlsx">https://bvdktuthainguyen.gov.vn/uploads/media/tai%20lieu/danh%20muc%20thuoc/thuoc%202022-2023/DM%20thu%E1%BB%91c%20tr%C3%BAng%20th%E1%BA%A7u%202023%20BVTW%20TN%20(1).xlsx</a>.
</div>
<div id="ref-byt2024qd3220" class="csl-entry" role="listitem">
Bộ Y tế. 2024. <span>“Quyết định số 3220/<span>QĐ-BYT</span> ngày 01/11/2024 về giá dịch vụ khám bệnh, chữa bệnh áp dụng tại Bệnh viện Bạch Mai”</span>. 1 Tháng Mười-Một 2024. <a href="https://apicms.bachmai.gov.vn/documents/37204/1543632/8_Nov_2024_022948_GMTupload_00004592.pdf/b3ab6717-2151-db08-9913-3cfbfd7e0738">https://apicms.bachmai.gov.vn/documents/37204/1543632/8_Nov_2024_022948_GMTupload_00004592.pdf/b3ab6717-2151-db08-9913-3cfbfd7e0738</a>.
</div>
<div id="ref-garpvall2021admission" class="csl-entry" role="listitem">
Garpvall, K., V. Duong, S. Linnros, T. N. Quốc, D. Mucchiano, S. Modeen, và c.s. 2021. <span>“Admission screening and cohort care decrease carbapenem resistant enterobacteriaceae in <span>Vietnamese</span> pediatric <span>ICU’s</span>”</span>. <em>Antimicrobial Resistance and Infection Control</em> 10 (1): 128. <a href="https://doi.org/10.1186/s13756-021-00994-9">https://doi.org/10.1186/s13756-021-00994-9</a>.
</div>
<div id="ref-graves2010estimating" class="csl-entry" role="listitem">
Graves, Nicholas, Stephan Harbarth, Jan Beyersmann, Adrian Barnett, Kate Halton, và Ben Cooper. 2010. <span>“Estimating the cost of health care-associated infections: mind your p’s and q’s”</span>. <em>Clinical Infectious Diseases</em> 50 (7): 1017–21. <a href="https://doi.org/10.1086/651110">https://doi.org/10.1086/651110</a>.
</div>
<div id="ref-larsson2025burden" class="csl-entry" role="listitem">
Larsson, M, L V N Truong, T D Nguyen, T N Do, T B N Hoang, M V Nong, M P Doan, và c.s. 2025. <span>“Burden of carbapenem-resistant <span>Gram</span>-negative bacterial infections in <span>Vietnam</span>: a national hospital survey”</span>. <em>Journal of Hospital Infection</em> 165: 189–98. <a href="https://doi.org/10.1016/j.jhin.2025.03.019">https://doi.org/10.1016/j.jhin.2025.03.019</a>.
</div>
<div id="ref-schulgen1996estimation" class="csl-entry" role="listitem">
Schulgen, G., và M. Schumacher. 1996. <span>“Estimation of prolongation of hospital stay attributable to nosocomial infections: new approaches based on multistate models”</span>. <em>Lifetime Data Analysis</em> 2 (3): 219–40. <a href="https://doi.org/10.1007/BF00128975">https://doi.org/10.1007/BF00128975</a>.
</div>
<div id="ref-stewardson2016health" class="csl-entry" role="listitem">
Stewardson, Andrew J., Arthur Allignol, Jan Beyersmann, Nicholas Graves, Martin Schumacher, Rodolphe Meyer, và c.s. 2016. <span>“The health and economic burden of bloodstream infections caused by antimicrobial-susceptible and non-susceptible <span>Enterobacteriaceae</span> and <span>Staphylococcus aureus</span> in <span>European</span> hospitals, 2010 and 2011: a multicentre retrospective cohort study”</span>. <em>Eurosurveillance</em> 21 (33): 30319. <a href="https://doi.org/10.2807/1560-7917.ES.2016.21.33.30319">https://doi.org/10.2807/1560-7917.ES.2016.21.33.30319</a>.
</div>
</div>
<div class="video-script">
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kịch bản video (~14 phút)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Slide</th>
<th>Lời giảng chính</th>
<th>Hình/Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Một so sánh hiển nhiên</td>
<td>ICU nhi Việt Nam: mắc phải (định cư) CRE thì nằm lâu hơn. Nhưng chiều nào gây ra chiều nào? Tổng thời gian, không phải thời gian sau nhiễm</td>
<td>Số liệu Garpvall 2021</td>
</tr>
<tr class="even">
<td>2</td>
<td>Người bệnh A và B</td>
<td>Ngày trước nhiễm khuẩn bị gán nhầm cho nhiễm khuẩn; liên hệ immortal time bias</td>
<td>Dòng thời gian vẽ tay</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Mô hình đa trạng thái</td>
<td>Năm trạng thái; nhiễm khuẩn là một lần chuyển</td>
<td>Sơ đồ Mermaid</td>
</tr>
<tr class="even">
<td>4</td>
<td>Dữ liệu dạng đợt</td>
<td>Một dòng cho mỗi trạng thái; kiểm tra tổng thời gian</td>
<td><code>l02-multistate</code></td>
</tr>
<tr class="odd">
<td>5</td>
<td>Ước lượng d/T</td>
<td>Số lần chuyển chia thời gian có nguy cơ; kiểm duyệt đóng góp thời gian</td>
<td>Công thức h-mũ</td>
</tr>
<tr class="even">
<td>6</td>
<td>Từ nguy cơ đến số ngày</td>
<td>1/h; hai đối chứng: “không bao giờ nhiễm” và “chưa nhiễm tại thời điểm s”; etm tính cách thứ hai</td>
<td>Công thức e_R, L_A, <code>l02-estimand</code></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Kết quả mô phỏng</td>
<td>Giản đơn gấp nhiều lần giá trị thật; đa trạng thái trúng</td>
<td><code>figs/l02-time-dependent-bias.png</code></td>
</tr>
<tr class="even">
<td>8</td>
<td>Bootstrap và Cox</td>
<td>KTC; HR phụ thuộc thời gian so với cố định</td>
<td><code>l02-boot</code>, <code>l02-cox</code></td>
</tr>
<tr class="odd">
<td>9</td>
<td>Ra tiền</td>
<td>Lượng nhân giá; ngày giường là chi phí cơ hội</td>
<td><code>l02-cost</code></td>
</tr>
<tr class="even">
<td>10</td>
<td>Kiểm tra bằng tác động 0</td>
<td>Phương pháp giản đơn tìm ra tác động không tồn tại; sai lệch 1/(h_ra viện,0 + h_tử vong,0)</td>
<td>Bài tập 1, 2</td>
</tr>
<tr class="odd">
<td>11</td>
<td>Tóm tắt</td>
<td>Cần ngày nhiễm khuẩn; dữ liệu thật dùng Aalen–Johansen (<code>etm</code>)</td>
<td>Hộp “Mẹo thực hành”</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../kb/m06-amr-economics/l01-amr-burden.html" class="pagination-link" aria-label="Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../kb/m06-amr-economics/l03-ward-transmission.html" class="pagination-link" aria-label="Bài 3: Mô hình lây truyền CRE trong khoa hồi sức">
        <span class="nav-page-text"><span class="chapter-title">Bài 3: Mô hình lây truyền CRE trong khoa hồi sức</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>