<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh – Mô hình Kinh tế Y tế với R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../kb/m07-survival-psm/index.html" rel="next">
<link href="../../kb/m06-amr-economics/l04-two-strain-selection.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9e7f0c659d5fa2cace8548cb57964278.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c18d72663580ed8ca19ce2a2f99af51b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=JetBrains+Mono:wght@400;600&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m06-amr-economics/index.html">M06 · Kinh tế học kháng kháng sinh (AMR)</a></li><li class="breadcrumb-item"><a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Mô hình Kinh tế Y tế với R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lời mở đầu</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m00-r-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M00 · R cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l02-vectors-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l03-functions-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hàm, cấu trúc điều khiển, vòng lặp và vectơ hóa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l04-data-frames.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Data frame — nhập, làm sạch, tóm tắt và chuyển dạng dữ liệu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l05-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Biểu đồ với ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l06-randomness-monte-carlo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 6: Ngẫu nhiên, mô phỏng Monte Carlo và sai số Monte Carlo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m01-ee-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M01 · Nền tảng đánh giá kinh tế và cây quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l01-evaluation-types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại đánh giá kinh tế, quan điểm, khung thời gian và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l02-health-outcomes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Năm sống, QALY và DALY</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l03-decision-rules.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l04-thresholds.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l05-decision-tree.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Xây cây quyết định từ đầu trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m02-cohort-markov/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l01-state-transition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao cần mô hình chuyển trạng thái</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l03-cohort-trace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l04-time-dependence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Phụ thuộc thời gian: lão hóa, trạng thái đường hầm và mảng 3 chiều</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l05-results-verification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị gắn với lần chuyển, đường biên hiệu quả và xác minh mô hình</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m03-uncertainty-voi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l01-deterministic-sa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại bất định và phân tích độ nhạy tất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l02-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Chọn phân phối cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l03-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích độ nhạy xác suất (PSA) trong R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l05-voi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m04-microsimulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M04 · Mô phỏng vi mô (microsimulation)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l01-why-microsimulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l02-microsim-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l03-vectorisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vectơ hóa theo cá thể và đo hiệu năng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l04-parallel-rcpp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tính toán song song và Rcpp cho vòng lặp nóng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l05-mc-error-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bao nhiêu cá thể là đủ? Sai số Monte Carlo, PSA và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m05-dynamic-transmission/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M05 · Mô hình lây truyền động</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l01-static-vs-dynamic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Mô hình tĩnh và mô hình lây truyền động</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l02-sir-seir-desolve.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình SIR và SEIR trong R với deSolve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l03-vaccination-herd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Tiêm chủng, hiệu quả trực tiếp và gián tiếp</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l04-dengue-host-vector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Mô hình vật chủ–véc tơ cho sốt xuất huyết Dengue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l05-dynamic-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế với mô hình lây truyền động</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m06-amr-economics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M06 · Kinh tế học kháng kháng sinh (AMR)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l01-amr-burden.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l02-attributable-los.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l03-ward-transmission.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Mô hình lây truyền CRE trong khoa hồi sức</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l04-two-strain-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m07-survival-psm/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M07 · Phân tích sống còn cho mô hình quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l01-survival-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ôn tập phân tích sống còn cho người làm mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l02-parametric-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình sống còn tham số với flexsurv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l03-extrapolation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Ngoại suy sống còn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l04-reconstruct-ipd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tái tạo dữ liệu cá thể từ đường KM đã công bố và dùng HR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l05-partitioned-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Mô hình sống còn phân vùng trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m08-calibration/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M08 · Hiệu chuẩn mô hình (calibration)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l01-why-calibrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l02-search-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l03-bayes-sir.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hiệu chuẩn Bayes và thuật toán SIR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l04-psa-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đưa kết quả hiệu chuẩn vào PSA, thẩm định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m09-inputs-vietnam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l01-costing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ước tính chi phí cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l05-decision-context.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bối cảnh ra quyết định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m10-policy-bia-equity/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m11-software-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l01-code-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Cấu trúc mã cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l02-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Xác minh và kiểm thử mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l03-version-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quản lý phiên bản với Git và tái lập môi trường với renv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l04-r-package.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đóng gói mô hình thành gói R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l05-shiny-living.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Ứng dụng Shiny và mô hình “sống”</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bảng thuật ngữ Anh–Việt</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Trong bài</h2>
   
  <ul class="collapse">
  <li><a href="#mục-tiêu-học-tập" id="toc-mục-tiêu-học-tập" class="nav-link active" data-scroll-target="#mục-tiêu-học-tập">Mục tiêu học tập</a></li>
  <li><a href="#ý-chính" id="toc-ý-chính" class="nav-link" data-scroll-target="#ý-chính">Ý chính</a></li>
  <li><a href="#nội-dung" id="toc-nội-dung" class="nav-link" data-scroll-target="#nội-dung">Nội dung</a></li>
  <li><a href="#thực-hành" id="toc-thực-hành" class="nav-link" data-scroll-target="#thực-hành">Thực hành</a></li>
  <li><a href="#bài-tập" id="toc-bài-tập" class="nav-link" data-scroll-target="#bài-tập">Bài tập</a></li>
  <li><a href="#tài-liệu-tham-khảo" id="toc-tài-liệu-tham-khảo" class="nav-link" data-scroll-target="#tài-liệu-tham-khảo">Tài liệu tham khảo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m06-amr-economics/index.html">M06 · Kinh tế học kháng kháng sinh (AMR)</a></li><li class="breadcrumb-item"><a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></h1>
<p class="subtitle lead">So sánh sàng lọc bằng nuôi cấy và bằng PCR nhanh kèm phòng ngừa tiếp xúc trong ICU, định giá kháng thuốc tương lai, và trình bày bất định</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled" title="Vì sao bạn nên quan tâm?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vì sao bạn nên quan tâm?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ban giám đốc một bệnh viện hạng đặc biệt cân nhắc sàng lọc CRE cho mọi người bệnh vào ICU 20 giường, khi nhập khoa và mỗi tuần. Theo giá dịch vụ BHYT, một xét nghiệm PCR phát hiện gen kháng carbapenem là 771,700 VNĐ, gấp 3.0 lần một lần cấy phết trực tràng <span class="citation" data-cites="byt2024qd3220">(<a href="../m00-r-foundations/index.html#ref-byt2024qd3220" role="doc-biblioref">Bộ Y tế 2024</a>)</span>. Trong mô hình của bài, riêng tiền xét nghiệm PCR một năm là khoảng 1.2 tỷ VNĐ, bằng 10 lần GDP bình quân đầu người. Khoản đó có mua được đủ sức khỏe không, khi mỗi QALY “đáng” khoảng 125.5 triệu VNĐ (1 × GDP bình quân đầu người)? Bài này giúp bạn so sánh thường quy, nuôi cấy và PCR nhanh một cách minh bạch, và nói rõ kết luận đứng vững đến đâu.</p>
</div>
</div>
<section id="mục-tiêu-học-tập" class="level2">
<h2 class="anchored" data-anchor-id="mục-tiêu-học-tập">Mục tiêu học tập</h2>
<p>Sau bài này, bạn có thể:</p>
<ol type="1">
<li>Liệt kê các chi phí và kết cục của một can thiệp chống kháng kháng sinh (AMR), và chọn kịch bản phản thực phù hợp.</li>
<li>Ghép mô hình lây truyền của Bài 3 với chi phí và năm sống điều chỉnh theo chất lượng (QALY) để so sánh ba chiến lược (đường biên hiệu quả, ICER, NMB), và nêu rõ giả định về thường quy và độ đặc hiệu.</li>
<li>Định giá phần “kháng thuốc tương lai” theo ba kênh: ngoại ứng, lan tỏa, và kháng thuốc gia tăng.</li>
<li>Thực hiện phân tích độ nhạy xác suất (PSA), vẽ mặt phẳng chi phí-hiệu quả và đường cong chấp nhận chi phí-hiệu quả (CEAC), và nêu rõ tham số nào vẫn cố định.</li>
</ol>
</section>
<section id="ý-chính" class="level2">
<h2 class="anchored" data-anchor-id="ý-chính">Ý chính</h2>
<ul>
<li>Can thiệp chống AMR có chi phí trước mắt và chắc chắn, còn lợi ích đến sau, qua lây truyền, và bất định. Chuỗi lợi ích: ca định cư tránh được → ca nhiễm khuẩn tránh được → tử vong, ngày giường, kháng sinh dự trữ tránh được → QALY và chi phí.</li>
<li>Chọn kịch bản phản thực như ở Bài 1: ngăn định cư thì so với <em>không nhiễm khuẩn</em>; xét nghiệm nhanh định hướng điều trị thì so với <em>nhiễm khuẩn nhạy</em>.</li>
<li>Sàng lọc kèm phòng ngừa tiếp xúc (contact precautions, PNTX) bảo vệ cả người không được phát hiện nhờ giảm lây truyền, nên cần mô hình động <span class="citation" data-cites="pitman2012dynamic">(<a href="../m00-r-foundations/index.html#ref-pitman2012dynamic" role="doc-biblioref">Pitman và c.s. 2012</a>)</span>. Xét nghiệm nhanh và nhạy hơn không tự động đáng tiền.</li>
<li>Hai giả định hay bị bỏ quên cần chạy như phân tích kịch bản: thường quy có phát hiện lâm sàng hay không, và độ đặc hiệu của xét nghiệm (dương tính giả đưa người không mang Enterobacterales kháng carbapenem, CRE, vào PNTX). Trong ICU của bài, coi thường quy “không phát hiện ai” đủ để đổi chiến lược được chọn.</li>
<li>Giá trị của việc giảm kháng thuốc tương lai đến qua ba kênh (ngoại ứng, lan tỏa, kháng thuốc gia tăng). Mô hình một ICU bỏ sót cả ba; hãy nêu rõ.</li>
<li>Báo cáo theo CHEERS 2022 <span class="citation" data-cites="husereau2022consolidated">(<a href="../m00-r-foundations/index.html#ref-husereau2022consolidated" role="doc-biblioref">Husereau và c.s. 2022</a>)</span>. Thời gian triển khai chương trình không phải khung thời gian phân tích: ở đây QALY được tính đến hết đời người bệnh.</li>
</ul>
</section>
<section id="nội-dung" class="level2">
<h2 class="anchored" data-anchor-id="nội-dung">Nội dung</h2>
<section id="chi-phí-và-kết-cục-nào-cần-tính" class="level3">
<h3 class="anchored" data-anchor-id="chi-phí-và-kết-cục-nào-cần-tính">Chi phí và kết cục nào cần tính?</h3>
<p>Ước tính chi phí của AMR dao động rất rộng, phần lớn vì khác nhau về kết cục, quan điểm và phương pháp, nhất là cách xử lý thời điểm nhiễm khuẩn <span class="citation" data-cites="naylor2018estimating wozniak2019using">(<a href="../m00-r-foundations/index.html#ref-naylor2018estimating" role="doc-biblioref">Naylor và c.s. 2018</a>; <a href="../m00-r-foundations/index.html#ref-wozniak2019using" role="doc-biblioref">Wozniak và c.s. 2019</a>)</span>; xem thêm <span class="citation" data-cites="gandra2014economic">(<a href="../m00-r-foundations/index.html#ref-gandra2014economic" role="doc-biblioref">Gandra, Barter, và Laxminarayan 2014</a>)</span>. Theo quan điểm hệ thống y tế (health-system perspective), có bốn nhóm thành phần: chi phí can thiệp (xét nghiệm, PNTX); chi phí tránh được (ngày giường là chi phí cơ hội, xem Bài 1; kháng sinh dự trữ); kết cục sức khỏe (nhiễm khuẩn, tử vong, QALY); và kháng thuốc tương lai (phần sau). Với sàng lọc và PNTX, can thiệp thay đổi việc <em>ca nhiễm khuẩn có xảy ra hay không</em>, nên dùng số đo “CRE so với bỏ nhiễm khuẩn” (Bài 2). Một xét nghiệm nhanh giúp chọn đúng kháng sinh cho người đã nhiễm, như cây quyết định ở M01, cần “CRE so với nhiễm khuẩn nhạy”.</p>
</section>
<section id="ba-chiến-lược-cho-một-icu" class="level3">
<h3 class="anchored" data-anchor-id="ba-chiến-lược-cho-một-icu">Ba chiến lược cho một ICU</h3>
<p>Ta so sánh ba chiến lược trong ICU 20 giường của Bài 3. Chương trình chạy 365 ngày; người bệnh được theo dõi tiếp đến hết đời để tính QALY.</p>
<p>Chi phí lấy theo giá năm 2025: giá dịch vụ BHYT cho xét nghiệm và ngày giường <span class="citation" data-cites="byt2024qd3220">(<a href="../m00-r-foundations/index.html#ref-byt2024qd3220" role="doc-biblioref">Bộ Y tế 2024</a>)</span>, giá trúng thầu cho kháng sinh <span class="citation" data-cites="thainguyen2023thau cuchi2024thau">(<a href="../m00-r-foundations/index.html#ref-thainguyen2023thau" role="doc-biblioref">Bệnh viện Trung ương Thái Nguyên 2023</a>; <a href="../m00-r-foundations/index.html#ref-cuchi2024thau" role="doc-biblioref">Bệnh viện Đa khoa khu vực Củ Chi 2024</a>)</span>. Một ngày phòng ngừa tiếp xúc (PNTX) gồm vật tư (áo choàng, găng; 150,000 VNĐ, giá trị minh họa) và 31 phút nhân viên mặc và cởi phương tiện phòng hộ <span class="citation" data-cites="vandijk2021daily">(<a href="../m00-r-foundations/index.html#ref-vandijk2021daily" role="doc-biblioref">van Dijk và c.s. 2021</a>)</span>, định giá theo thu nhập bình quân của người lao động <span class="citation" data-cites="gso2026population2025">(<a href="../m00-r-foundations/index.html#ref-gso2026population2025" role="doc-biblioref">Cục Thống kê (Bộ Tài chính) 2026</a>)</span>: tổng cộng 174,659 VNĐ.</p>
<ul>
<li><strong>Thường quy:</strong> không sàng lọc chủ động. Người mang CRE chỉ được phát hiện khi có nhiễm khuẩn lâm sàng (80% số ca được nhận diện), khi đó được đặt PNTX ngay. Giả định này áp dụng cho cả ba chiến lược.</li>
<li><strong>Nuôi cấy + PNTX:</strong> sàng lọc phết trực tràng khi nhập viện và mỗi 7 ngày, 261,000 VNĐ mỗi lần; độ nhạy 80%, độ đặc hiệu 98% (minh họa), kết quả sau 3 ngày.</li>
<li><strong>PCR nhanh + PNTX:</strong> cùng lịch, 771,700 VNĐ mỗi lần; độ nhạy 91% và độ đặc hiệu 99% theo tổng hợp các nghiên cứu Xpert Carba-R ở châu Á <span class="citation" data-cites="bai2024accuracy">(<a href="../m00-r-foundations/index.html#ref-bai2024accuracy" role="doc-biblioref">Bai, Liu, và Wang 2024</a>)</span>, kết quả sau 1 ngày. PCR chỉ tìm gen carbapenemase nên bỏ sót CRE kháng theo cơ chế khác (như mất porin), nên độ nhạy với mọi CRE có thể thấp hơn.</li>
</ul>
<p>So với Bài 3, mô hình có thêm hai nhóm ngăn. <span class="math inline">\(C_p\)</span>: người mang khuẩn có xét nghiệm dương tính nhưng <em>chưa có kết quả</em>; họ vẫn lây như người chưa phát hiện. <span class="math inline">\(U_p\)</span> và <span class="math inline">\(U_d\)</span>: người <em>không</em> mang CRE nhưng xét nghiệm dương tính giả (xác suất bằng 1 trừ độ đặc hiệu). Họ không lây, nhưng bị đặt PNTX sau khi có kết quả và tốn ngày PNTX. Nếu về sau họ bị lây, ta coi họ như người mang khuẩn chưa phát hiện, một giả định thận trọng vì không tính tác dụng bảo vệ của PNTX đã có sẵn. Mọi chiến lược bắt đầu từ trạng thái lưu hành của thường quy. Mô hình ODE cho giá trị kỳ vọng xấp xỉ; ở khoa nhỏ, trung bình ngẫu nhiên khác giá trị tất định (Bài 3), một giới hạn cần nêu khi báo cáo.</p>
<p>Chuỗi từ mô hình lây truyền đến kết cục kinh tế như sau. Gọi <span class="math inline">\(A\)</span> là số ca định cư mắc phải trong khoa (đã chiết khấu), <span class="math inline">\(\pi\)</span> là xác suất người mang CRE bị nhiễm khuẩn, <span class="math inline">\(\Delta_D\)</span> và <span class="math inline">\(\Delta_L\)</span> là xác suất tử vong và số ngày nằm viện tăng thêm mỗi ca nhiễm khuẩn so với bỏ nhiễm khuẩn (Bài 2), và <span class="math inline">\(P_R\)</span> là xác suất tử vong sau nhiễm CRE:</p>
<p><span class="math display">\[
\begin{aligned}
I &amp;= \pi A, \qquad D = I\,\Delta_D, \\
C &amp;= n_{\text{xét nghiệm}} c_{\text{xét nghiệm}} + n_{\text{ngày PNTX}} c_{\text{PNTX}} + I\,(\Delta_L c_{\text{giường}} + d\,c_{\text{kháng sinh}}), \\
\text{QALY mất} &amp;= D \cdot Q_{\text{tử vong}} + I\,(1 - P_R)\,q_{\text{nhiễm khuẩn}}.
\end{aligned}
\]</span></p>
<p><span class="math inline">\(n_{\text{ngày PNTX}}\)</span> gồm cả ngày của người dương tính giả. <span class="math inline">\(Q_{\text{tử vong}}\)</span> là số QALY đã chiết khấu mất đi khi một người bệnh tử vong; tổn thất do bệnh tật chỉ tính cho người sống sót. Xác suất <span class="math inline">\(\pi\)</span> lấy từ Tischendorf và cộng sự <span class="citation" data-cites="tischendorf2016risk">(<a href="../m00-r-foundations/index.html#ref-tischendorf2016risk" role="doc-biblioref">Tischendorf, de Avila, và Safdar 2016</a>)</span>. <span class="math inline">\(Q_{\text{tử vong}}\)</span> dùng bảng sống WHO của Việt Nam ở tuổi trung vị của người bệnh ICU, với tỷ suất tử vong nền nhân 2.0 lần và thỏa dụng 0.75 (hai giá trị minh họa). Người mang khuẩn từ ngoài vào giống nhau ở mọi chiến lược nên không cần tính.</p>
</section>
<section id="định-giá-kháng-thuốc-tương-lai" class="level3">
<h3 class="anchored" data-anchor-id="định-giá-kháng-thuốc-tương-lai">Định giá kháng thuốc tương lai</h3>
<p>Mô hình một ICU bỏ sót ba kênh giá trị. Ta tính chúng như phân tích kịch bản, không đưa vào kết quả cơ sở.</p>
<ol type="1">
<li><strong>Ngoại ứng của kháng sinh.</strong> Mỗi ca nhiễm khuẩn CRE tránh được là một đợt kháng sinh dự trữ không phải dùng, với chi phí ngoại ứng <span class="math inline">\(c_{AMR}\)</span> mỗi SU (Bài 1) <span class="citation" data-cites="shrestha2018enumerating coast1996superbugs">(<a href="../m00-r-foundations/index.html#ref-shrestha2018enumerating" role="doc-biblioref">Shrestha và c.s. 2018</a>; <a href="../m00-r-foundations/index.html#ref-coast1996superbugs" role="doc-biblioref">Coast, Smith, và Millar 1996</a>)</span>. Hai lưu ý. Ước tính của Shrestha và cộng sự gắn chi phí AMR với lượng kháng sinh tiêu thụ nên gần với chi phí trung bình hơn chi phí biên của một SU thêm vào. Và nếu mô hình đã đếm tác hại của ca nhiễm (QALY, chi phí điều trị) thì cộng thêm <span class="math inline">\(c_{AMR}\)</span> cho cùng lượng thuốc có nguy cơ đếm trùng.</li>
<li><strong>Lan tỏa.</strong> Người mang CRE ra viện mang CRE sang nơi khác. Ta dùng một tham số minh họa, số ca định cư mới ở nơi khác trên mỗi người ra viện, và định giá như một ca định cư mắc phải trong ICU. Mô hình mạng lưới bệnh viện sẽ thay tham số này.</li>
<li><strong>Kháng thuốc gia tăng.</strong> Nếu tỷ lệ mang CRE khi nhập viện tăng dần, thời gian triển khai dài hơn đổi kết quả vì chính mô hình thay đổi, không chỉ vì quy mô nhân lên. Ta thêm một xu hướng minh họa: tỷ lệ này tăng 3 điểm phần trăm mỗi năm.</li>
</ol>
<p>Hướng dẫn thực hành tốt về mô hình động khuyến cáo dùng mô hình lây truyền khi can thiệp tác động đến lây truyền, và báo cáo rõ cấu trúc và giả định <span class="citation" data-cites="pitman2012dynamic">(<a href="../m00-r-foundations/index.html#ref-pitman2012dynamic" role="doc-biblioref">Pitman và c.s. 2012</a>)</span>.</p>
</section>
</section>
<section id="thực-hành" class="level2">
<h2 class="anchored" data-anchor-id="thực-hành">Thực hành</h2>
<p>Giá xét nghiệm, ngày giường và kháng sinh, ngưỡng, quy mô và thời gian nằm ICU, tỷ lệ mang CRE khi nhập ICU, xác suất nhiễm khuẩn, xác suất tử vong và độ chính xác của PCR có nguồn. Tác dụng của PNTX, phát hiện lâm sàng, hệ số lây truyền, độ chính xác của nuôi cấy, vật tư PNTX và xu hướng kháng thuốc là giá trị minh họa. Kết quả gần với thực tế Việt Nam hơn một ví dụ thuần minh họa, nhưng vẫn không phải khuyến cáo cho bệnh viện nào.</p>
<p>Nạp hàm và tham số; đặt số lần rút PSA theo mặc định của khóa học.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">isTRUE</span>(<span class="fu">l10n_info</span>()[[<span class="st">"UTF-8"</span>]])) <span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_CTYPE"</span>, <span class="st">"en_US.UTF-8"</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/helpers.R"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/vn_data.R"</span>)   <span class="co"># course-wide values: vn_context(), vn_prices(), vn_mx(), inflate_vnd()</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"code/model.R"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">read_all_params</span>()</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>ptab <span class="ot">&lt;-</span> <span class="fu">attr</span>(p, <span class="st">"table"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>N_PSA <span class="ot">&lt;-</span> <span class="dv">1000</span>                        <span class="co"># PSA draws (course default)</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>SP_ALT <span class="ot">&lt;-</span> <span class="fl">0.95</span>                       <span class="co"># the alternative (lower) specificity of the scenario analysis</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>SP_LOW <span class="ot">&lt;-</span> <span class="fl">0.5</span>                        <span class="co"># lowest specificity searched for the break-even</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Bảng đầu cho tham số của từng chiến lược (<code>clin</code> là tốc độ phát hiện lâm sàng mỗi ngày). Dòng sau tính ba đại lượng nối mô hình lây truyền với kinh tế.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>strat_tab <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(STRATEGIES, <span class="cf">function</span>(s) <span class="fu">unlist</span>(<span class="fu">ward_parms</span>(p, s))))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(strat_tab) <span class="ot">&lt;-</span> STRATEGIES</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(strat_tab[, <span class="fu">c</span>(<span class="st">"se"</span>, <span class="st">"sp"</span>, <span class="st">"sigma"</span>, <span class="st">"delay"</span>, <span class="st">"eps"</span>, <span class="st">"clin"</span>)], <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          se   sp sigma delay eps  clin
usual   0.00 1.00 0.000     0 0.5 0.025
culture 0.80 0.98 0.143     3 0.5 0.025
pcr     0.91 0.99 0.143     1 0.5 0.025</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>av <span class="ot">&lt;-</span> <span class="fu">acquisition_value</span>(p, <span class="fu">ms_hazards_true</span>(p))     <span class="co"># cost and QALY loss of one ward-acquired colonisation</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>qaly_death <span class="ot">&lt;-</span> <span class="fu">qaly_per_death</span>(p)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>cost_per_infection <span class="ot">&lt;-</span> av[[<span class="st">"cost_per_infection"</span>]]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">qaly_per_death =</span> qaly_death, <span class="at">p_death_per_infection =</span> av[[<span class="st">"p_death_excess"</span>]],</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">cost_per_infection_million =</span> cost_per_infection <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">qaly_loss_per_infection =</span> av[[<span class="st">"qaly_loss_per_infection"</span>]]), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            qaly_per_death      p_death_per_infection 
                     8.284                      0.243 
cost_per_infection_million    qaly_loss_per_infection 
                    60.425                      2.023 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Unit costs of the strategies (VND, 2025): BHYT test prices and one day of contact precautions</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>cp_day <span class="ot">&lt;-</span> <span class="fu">cp_day_cost</span>(p)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">test_culture =</span> p<span class="sc">$</span>c_test_culture, <span class="at">test_pcr =</span> p<span class="sc">$</span>c_test_pcr, <span class="at">cp_day =</span> cp_day,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">cp_ppe =</span> p<span class="sc">$</span>c_cp_ppe_day, <span class="at">cp_staff =</span> p<span class="sc">$</span>cp_staff_min_day <span class="sc">*</span> p<span class="sc">$</span>wage_min))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>test_culture     test_pcr       cp_day       cp_ppe     cp_staff 
      261000       771700       174659       150000        24659 </code></pre>
</div>
</div>
<p>Mỗi ca tử vong làm mất 8.28 QALY (đã chiết khấu), và mỗi ca nhiễm khuẩn CRE tốn thêm 60.4 triệu VNĐ (giá 2025; ngày giường tính theo hỗn hợp ICU và khoa thường). Một ngày PNTX tốn 174,659 VNĐ, trong đó 24,659 VNĐ là thời gian nhân viên.</p>
<p>Trước khi tin kết quả, ta kiểm tra mô hình bằng ba phép thử có thể thất bại: thường quy ổn định ở nghiệm giải tích (đã gồm phát hiện lâm sàng); số giường được bảo toàn khi có dương tính giả và thời gian chờ; và khi thời gian chờ tiến về 0, mô hình có ngăn chờ cho kết quả như mô hình không có ngăn đó.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Three checks of the ward model that can fail (they do not hold by construction):</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (1) usual care settles at the analytic equilibrium that includes clinical detection;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># (2) the beds stay full when screening has false positives and a result delay;</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># (3) as the result delay shrinks to zero, the pending compartments must give the same answer</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">#     as the model without them.</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>pp_u <span class="ot">&lt;-</span> <span class="fu">ward_parms</span>(p, <span class="st">"usual"</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>o_u <span class="ot">&lt;-</span> <span class="fu">run_ward_det</span>(pp_u, <span class="dv">3000</span>, <span class="fu">ward_init</span>(pp_u, <span class="at">prev =</span> <span class="dv">0</span>))</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>prev_end <span class="ot">&lt;-</span> (o_u<span class="sc">$</span>Cu <span class="sc">+</span> o_u<span class="sc">$</span>Cp <span class="sc">+</span> o_u<span class="sc">$</span>Cd)[<span class="fu">nrow</span>(o_u)] <span class="sc">/</span> pp_u<span class="sc">$</span>N</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>y_start <span class="ot">&lt;-</span> <span class="fu">ward_init</span>(pp_u)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>max_gap_beds <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (s <span class="cf">in</span> <span class="fu">c</span>(<span class="st">"culture"</span>, <span class="st">"pcr"</span>)) {</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  o_s <span class="ot">&lt;-</span> <span class="fu">run_ward_det</span>(<span class="fu">ward_parms</span>(p, s), p<span class="sc">$</span>horizon_days, y_start)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  max_gap_beds <span class="ot">&lt;-</span> <span class="fu">max</span>(max_gap_beds, <span class="fu">abs</span>(<span class="fu">ward_total</span>(o_s) <span class="sc">-</span> pp_u<span class="sc">$</span>N))</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>pp_a <span class="ot">&lt;-</span> <span class="fu">ward_parms</span>(p, <span class="st">"culture"</span>)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>pp_b <span class="ot">&lt;-</span> pp_a</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>pp_a<span class="sc">$</span>delay <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>pp_b<span class="sc">$</span>delay <span class="ot">&lt;-</span> <span class="fl">1e-4</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>acq_a <span class="ot">&lt;-</span> <span class="fu">tail</span>(<span class="fu">run_ward_det</span>(pp_a, p<span class="sc">$</span>horizon_days, y_start)<span class="sc">$</span>Acq, <span class="dv">1</span>)</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>acq_b <span class="ot">&lt;-</span> <span class="fu">tail</span>(<span class="fu">run_ward_det</span>(pp_b, p<span class="sc">$</span>horizon_days, y_start)<span class="sc">$</span>Acq, <span class="dv">1</span>)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">prev_ode =</span> prev_end, <span class="at">prev_analytic =</span> <span class="fu">ward_equilibrium</span>(pp_u),</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">max_bed_gap =</span> max_gap_beds, <span class="at">acq_delay0 =</span> acq_a, <span class="at">acq_delay_tiny =</span> acq_b), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      prev_ode  prev_analytic    max_bed_gap     acq_delay0 acq_delay_tiny 
        0.8369         0.8369         0.0000       544.6884       544.6898 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(prev_end <span class="sc">-</span> <span class="fu">ward_equilibrium</span>(pp_u)) <span class="sc">&lt;</span> <span class="fl">1e-4</span>, max_gap_beds <span class="sc">&lt;</span> <span class="fl">1e-8</span>,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">abs</span>(acq_a <span class="sc">/</span> acq_b <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">&lt;</span> <span class="fl">1e-3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mô hình số cho 83.7% số giường có người mang CRE, nghiệm giải tích cho 83.7%.</p>
<p>Chạy ba chiến lược. Số ca, số xét nghiệm và số ngày PNTX là số đếm thô; chi phí và QALY đã chiết khấu. Kiểm tra: chi phí không âm, sàng lọc làm giảm số ca mắc mới, và PNTX ở thường quy chỉ đến từ phát hiện lâm sàng (có ngày PNTX, nhưng ít hơn khi sàng lọc).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">run_cea_ward</span>(p)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>show_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"acq"</span>, <span class="st">"infections"</span>, <span class="st">"deaths"</span>, <span class="st">"tests"</span>, <span class="st">"cp_days"</span>, <span class="st">"n_fp"</span>, <span class="st">"col_discharges"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(tab[, show_cols], <span class="dv">1</span>)                                                   <span class="co"># natural units, not discounted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          acq infections deaths  tests cp_days n_fp col_discharges
usual   603.3       99.5   24.2    0.0   834.0  0.0          954.6
culture 569.5       94.0   22.8 1649.8  2685.2 19.7          921.4
pcr     551.3       91.0   22.1 1626.7  3411.3 10.0          903.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(tab[, <span class="fu">c</span>(<span class="st">"cost_screen"</span>, <span class="st">"cost_cp"</span>, <span class="st">"cost_fp"</span>, <span class="st">"cost_inf"</span>, <span class="st">"cost"</span>)] <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">1</span>)   <span class="co"># million VND, discounted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        cost_screen cost_cp cost_fp cost_inf   cost
usual           0.0   143.5     0.0   5927.3 6070.8
culture       424.3   462.1     2.2   5595.0 6481.3
pcr          1237.0   587.0     2.2   5416.0 7240.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(tab<span class="sc">$</span>qaly, <span class="dv">2</span>)                                                           <span class="co"># QALY, discounted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -198.48 -187.35 -181.36</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checks: costs are non-negative; screening reduces acquisitions; usual care puts carriers on</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># precautions only through clinical detection (some days, but fewer than with screening);</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># a false positive stays on precautions for less than a mean ICU stay</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(tab[, <span class="fu">c</span>(<span class="st">"cost_screen"</span>, <span class="st">"cost_cp"</span>, <span class="st">"cost_fp"</span>, <span class="st">"cost_inf"</span>)] <span class="sc">&gt;=</span> <span class="dv">0</span>),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(tab[<span class="fu">c</span>(<span class="st">"culture"</span>, <span class="st">"pcr"</span>), <span class="st">"acq"</span>] <span class="sc">&lt;</span> tab[<span class="st">"usual"</span>, <span class="st">"acq"</span>]),</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>          tab[<span class="st">"usual"</span>, <span class="st">"cp_days"</span>] <span class="sc">&gt;</span> <span class="dv">0</span>, tab[<span class="st">"usual"</span>, <span class="st">"cp_days"</span>] <span class="sc">&lt;</span> tab[<span class="st">"culture"</span>, <span class="st">"cp_days"</span>],</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(tab[<span class="fu">c</span>(<span class="st">"culture"</span>, <span class="st">"pcr"</span>), <span class="st">"fp_cp_days"</span>] <span class="sc">/</span> tab[<span class="fu">c</span>(<span class="st">"culture"</span>, <span class="st">"pcr"</span>), <span class="st">"n_fp"</span>] <span class="sc">&lt;</span> p<span class="sc">$</span>los_icu))</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>d_screen_pcr <span class="ot">&lt;-</span> tab[<span class="st">"pcr"</span>, <span class="st">"cost_screen"</span>] <span class="sc">-</span> tab[<span class="st">"usual"</span>, <span class="st">"cost_screen"</span>]      <span class="co"># extra test spending of PCR vs usual</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>d_inf_pcr <span class="ot">&lt;-</span> tab[<span class="st">"usual"</span>, <span class="st">"cost_inf"</span>] <span class="sc">-</span> tab[<span class="st">"pcr"</span>, <span class="st">"cost_inf"</span>]               <span class="co"># infection cost saved by PCR vs usual</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>So với thường quy, nuôi cấy + PNTX tránh được 34 ca định cư mắc phải và 5.6 ca nhiễm khuẩn CRE trong một năm. PCR nhanh tránh thêm 3.0 ca nhiễm khuẩn so với nuôi cấy. Đổi lại, nuôi cấy tạo ra 20 lượt dương tính giả mỗi năm và PCR tạo ra 10.</p>
<p>Tiếp theo là phân tích gia tăng trên đường biên hiệu quả (M01). Đoạn mã còn thử hàm đường biên trên một ví dụ nhỏ có đáp án biết trước, và đòi hỏi đường biên chọn cùng chiến lược với NMB cao nhất.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>fr <span class="ot">&lt;-</span> <span class="fu">cea_frontier</span>(<span class="at">cost =</span> stats<span class="sc">::</span><span class="fu">setNames</span>(tab<span class="sc">$</span>cost, STRATEGIES),</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">effect =</span> stats<span class="sc">::</span><span class="fu">setNames</span>(tab<span class="sc">$</span>qaly, STRATEGIES))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>fr_show <span class="ot">&lt;-</span> fr</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>fr_show<span class="sc">$</span>cost_million <span class="ot">&lt;-</span> <span class="fu">round</span>(fr<span class="sc">$</span>cost <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">1</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>fr_show<span class="sc">$</span>effect <span class="ot">&lt;-</span> <span class="fu">round</span>(fr<span class="sc">$</span>effect, <span class="dv">2</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>fr_show<span class="sc">$</span>icer_million <span class="ot">&lt;-</span> <span class="fu">round</span>(fr<span class="sc">$</span>icer <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">1</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>fr_show[, <span class="fu">c</span>(<span class="st">"strategy"</span>, <span class="st">"cost_million"</span>, <span class="st">"effect"</span>, <span class="st">"status"</span>, <span class="st">"icer_million"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  strategy cost_million  effect   status icer_million
1    usual       6070.8 -198.48 frontier           NA
2  culture       6481.3 -187.35 frontier         36.9
3      pcr       7240.1 -181.36 frontier        126.6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>best_nmb <span class="ot">&lt;-</span> <span class="fu">rownames</span>(tab)[<span class="fu">which.max</span>(tab<span class="sc">$</span>nmb)]</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>best_nmb</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "culture"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>icer_pcr <span class="ot">&lt;-</span> fr<span class="sc">$</span>icer[fr<span class="sc">$</span>strategy <span class="sc">==</span> <span class="st">"pcr"</span>]</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>icer_culture <span class="ot">&lt;-</span> fr<span class="sc">$</span>icer[fr<span class="sc">$</span>strategy <span class="sc">==</span> <span class="st">"culture"</span>]</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The lesson text reads the ICERs as culture vs usual and PCR vs culture: all three must be on the frontier</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(fr<span class="sc">$</span>status <span class="sc">==</span> <span class="st">"frontier"</span>), fr<span class="sc">$</span>strategy[<span class="fu">order</span>(fr<span class="sc">$</span>cost)][<span class="dv">1</span>] <span class="sc">==</span> <span class="st">"usual"</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>d_cost_culture <span class="ot">&lt;-</span> tab[<span class="st">"culture"</span>, <span class="st">"cost"</span>] <span class="sc">-</span> tab[<span class="st">"usual"</span>, <span class="st">"cost"</span>]</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>d_qaly_culture <span class="ot">&lt;-</span> tab[<span class="st">"culture"</span>, <span class="st">"qaly"</span>] <span class="sc">-</span> tab[<span class="st">"usual"</span>, <span class="st">"qaly"</span>]</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>usual_status <span class="ot">&lt;-</span> fr<span class="sc">$</span>status[fr<span class="sc">$</span>strategy <span class="sc">==</span> <span class="st">"usual"</span>]</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co"># The frontier and the highest NMB must pick the same strategy at the threshold</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">frontier_choice</span>(fr, p<span class="sc">$</span>wtp) <span class="sc">==</span> best_nmb)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Test the frontier code on a toy case with a known answer: A is extendedly dominated (ICER O-&gt;A is</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 200, above O-&gt;B = 75), E is strongly dominated by D, and the frontier is O, B, D with ICER(D) = 250</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>toy <span class="ot">&lt;-</span> <span class="fu">cea_frontier</span>(<span class="at">cost =</span> <span class="fu">c</span>(<span class="at">O =</span> <span class="dv">0</span>, <span class="at">A =</span> <span class="dv">100</span>, <span class="at">B =</span> <span class="dv">150</span>, <span class="at">D =</span> <span class="dv">400</span>, <span class="at">E =</span> <span class="dv">500</span>),</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>                    <span class="at">effect =</span> <span class="fu">c</span>(<span class="at">O =</span> <span class="dv">0</span>, <span class="at">A =</span> <span class="fl">0.5</span>, <span class="at">B =</span> <span class="dv">2</span>, <span class="at">D =</span> <span class="dv">3</span>, <span class="at">E =</span> <span class="dv">1</span>))</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(toy<span class="sc">$</span>status[toy<span class="sc">$</span>strategy <span class="sc">==</span> <span class="st">"A"</span>] <span class="sc">==</span> <span class="st">"ext. dominated"</span>,</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>          toy<span class="sc">$</span>status[toy<span class="sc">$</span>strategy <span class="sc">==</span> <span class="st">"E"</span>] <span class="sc">==</span> <span class="st">"dominated"</span>,</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>          <span class="fu">all</span>(toy<span class="sc">$</span>status[toy<span class="sc">$</span>strategy <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"O"</span>, <span class="st">"B"</span>, <span class="st">"D"</span>)] <span class="sc">==</span> <span class="st">"frontier"</span>),</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>          <span class="fu">abs</span>(toy<span class="sc">$</span>icer[toy<span class="sc">$</span>strategy <span class="sc">==</span> <span class="st">"B"</span>] <span class="sc">-</span> <span class="dv">75</span>) <span class="sc">&lt;</span> <span class="fl">1e-9</span>, <span class="fu">abs</span>(toy<span class="sc">$</span>icer[toy<span class="sc">$</span>strategy <span class="sc">==</span> <span class="st">"D"</span>] <span class="sc">-</span> <span class="dv">250</span>) <span class="sc">&lt;</span> <span class="fl">1e-9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nuôi cấy + PNTX đắt hơn thường quy 410.5 triệu VNĐ và thêm 11.1 QALY mỗi năm triển khai, tức ICER 36.9 triệu VNĐ/QALY, thấp hơn ngưỡng 125.5 triệu VNĐ/QALY (1 × GDP bình quân đầu người). PCR nhanh + PNTX có ICER 126.6 triệu VNĐ/QALY so với nuôi cấy, cao hơn ngưỡng khoảng 0.9%. Chiến lược có NMB cao nhất là “Nuôi cấy + PNTX”, nhưng ICER của PCR sát ngưỡng đến mức một thay đổi nhỏ về giá hay độ nhạy có thể đổi lựa chọn (Bài tập 2 và phần PSA).</p>
<p>Hình sau tách chi phí một năm của từng chiến lược thành bốn thành phần. Kiểm tra: so phần xét nghiệm với phần điều trị nhiễm khuẩn giữa các chiến lược.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>cost_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">strategy =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(STRATEGY_LABELS[STRATEGIES], <span class="dv">4</span>), <span class="at">levels =</span> STRATEGY_LABELS),</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">component =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Xét nghiệm sàng lọc"</span>, <span class="st">"PNTX cho người mang CRE"</span>, <span class="st">"PNTX cho người dương tính giả"</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"Điều trị nhiễm khuẩn CRE"</span>), <span class="at">each =</span> <span class="dv">3</span>),</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Xét nghiệm sàng lọc"</span>, <span class="st">"PNTX cho người mang CRE"</span>, <span class="st">"PNTX cho người dương tính giả"</span>,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Điều trị nhiễm khuẩn CRE"</span>)),</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">c</span>(tab<span class="sc">$</span>cost_screen, tab<span class="sc">$</span>cost_cp <span class="sc">-</span> tab<span class="sc">$</span>cost_fp, tab<span class="sc">$</span>cost_fp, tab<span class="sc">$</span>cost_inf) <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>fig_costs <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(cost_df, <span class="fu">aes</span>(strategy, value, <span class="at">fill =</span> component)) <span class="sc">+</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> pal_course[<span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">2</span>)], <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="cf">function</span>(x) <span class="fu">fmt_num</span>(x)) <span class="sc">+</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Triệu VNĐ (giá 2025, chiết khấu)"</span>,</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="fu">sprintf</span>(<span class="st">"Chi phí một năm của ICU %s giường theo chiến lược"</span>, <span class="fu">fmt_num</span>(p<span class="sc">$</span>n_beds)),</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Sàng lọc tốn tiền xét nghiệm và PNTX, nhưng bớt được chi phí điều trị nhiễm khuẩn"</span>) <span class="sc">+</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="fu">guide_legend</span>(<span class="at">nrow =</span> <span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_costs, <span class="st">"l05-costs.png"</span>, <span class="at">width =</span> <span class="fl">7.5</span>, <span class="at">height =</span> <span class="fl">4.6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l05-costs.png" class="img-fluid figure-img" style="width:85.0%"></p>
<figcaption>Chi phí một năm theo chiến lược, tách theo thành phần (giá 2025; hiệu quả PNTX và một số tham số lâm sàng là minh họa).</figcaption>
</figure>
</div>
<p>Với PCR, tiền xét nghiệm tăng 1,237 triệu VNĐ so với thường quy, trong khi chi phí điều trị nhiễm khuẩn giảm 511 triệu VNĐ: phần tiền xét nghiệm tăng lớn hơn phần điều trị giảm được.</p>
<p>Hai giả định có thể đổi chiều kết luận. Đoạn mã sau chạy lại so sánh nuôi cấy với thường quy khi độ đặc hiệu là 100%, 95%, và khi thường quy không phát hiện lâm sàng ai (cách làm đơn giản hóa hay gặp), rồi tìm độ đặc hiệu thấp nhất mà nuôi cấy vẫn có NMB ít nhất bằng thường quy (tìm bằng <code>uniroot()</code> từ 50% đến 100%).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How much do two assumptions about the comparison matter?</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  - specificity of the screening tests (false positives are put on precautions)</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co">#  - clinical detection in usual care (carriers with an infection are recognised and isolated)</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>scen_row <span class="ot">&lt;-</span> <span class="cf">function</span>(p_x, <span class="at">clinical =</span> <span class="cn">TRUE</span>) {</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  tb <span class="ot">&lt;-</span> <span class="fu">run_cea_ward</span>(p_x, <span class="at">clinical =</span> clinical)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  fr_x <span class="ot">&lt;-</span> <span class="fu">cea_frontier</span>(stats<span class="sc">::</span><span class="fu">setNames</span>(tb<span class="sc">$</span>cost, STRATEGIES), stats<span class="sc">::</span><span class="fu">setNames</span>(tb<span class="sc">$</span>qaly, STRATEGIES))</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  dc <span class="ot">&lt;-</span> tb[<span class="st">"culture"</span>, <span class="st">"cost"</span>] <span class="sc">-</span> tb[<span class="st">"usual"</span>, <span class="st">"cost"</span>]</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  dq <span class="ot">&lt;-</span> tb[<span class="st">"culture"</span>, <span class="st">"qaly"</span>] <span class="sc">-</span> tb[<span class="st">"usual"</span>, <span class="st">"qaly"</span>]</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">d_cost_million =</span> dc <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">d_qaly =</span> dq,</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">icer_million =</span> <span class="cf">if</span> (dc <span class="sc">&gt;</span> <span class="dv">0</span>) dc <span class="sc">/</span> dq <span class="sc">/</span> <span class="fl">1e6</span> <span class="cf">else</span> <span class="cn">NA_real_</span>,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">usual_status =</span> fr_x<span class="sc">$</span>status[fr_x<span class="sc">$</span>strategy <span class="sc">==</span> <span class="st">"usual"</span>],</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">fp_cost_million =</span> tb[<span class="st">"culture"</span>, <span class="st">"cost_fp"</span>] <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">best =</span> <span class="fu">rownames</span>(tb)[<span class="fu">which.max</span>(tb<span class="sc">$</span>nmb)])</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>p_sp1 <span class="ot">&lt;-</span> p</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>p_sp1<span class="sc">$</span>sp_culture <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>p_sp1<span class="sc">$</span>sp_pcr <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>p_sp95 <span class="ot">&lt;-</span> p</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>p_sp95<span class="sc">$</span>sp_culture <span class="ot">&lt;-</span> SP_ALT</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>p_sp95<span class="sc">$</span>sp_pcr <span class="ot">&lt;-</span> SP_ALT</span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>scen <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="at">base =</span> <span class="fu">scen_row</span>(p),</span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>              <span class="at">perfect_specificity =</span> <span class="fu">scen_row</span>(p_sp1),</span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>              <span class="at">specificity_95 =</span> <span class="fu">scen_row</span>(p_sp95),</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>              <span class="at">no_clinical_detection =</span> <span class="fu">scen_row</span>(p, <span class="at">clinical =</span> <span class="cn">FALSE</span>))</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>scen_show <span class="ot">&lt;-</span> scen</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>scen_show[, <span class="fu">c</span>(<span class="st">"d_cost_million"</span>, <span class="st">"d_qaly"</span>, <span class="st">"icer_million"</span>, <span class="st">"fp_cost_million"</span>)] <span class="ot">&lt;-</span></span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(scen[, <span class="fu">c</span>(<span class="st">"d_cost_million"</span>, <span class="st">"d_qaly"</span>, <span class="st">"icer_million"</span>, <span class="st">"fp_cost_million"</span>)], <span class="dv">2</span>)</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>scen_show</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      d_cost_million d_qaly icer_million usual_status
base                          410.53  11.13        36.89     frontier
perfect_specificity           409.58  11.13        36.81     frontier
specificity_95                411.93  11.13        37.02     frontier
no_clinical_detection         458.49  12.86        35.66     frontier
                      fp_cost_million    best
base                             2.23 culture
perfect_specificity              0.00 culture
specificity_95                   5.53 culture
no_clinical_detection            2.11     pcr</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Lowest specificity of culture at which it still has at least the net monetary benefit of usual</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># care at the threshold (searched between SP_LOW and 1; NA if there is no switch in that range)</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>nmb_gap_sp <span class="ot">&lt;-</span> <span class="cf">function</span>(sp) {</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  p_x <span class="ot">&lt;-</span> p</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  p_x<span class="sc">$</span>sp_culture <span class="ot">&lt;-</span> sp</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  tb <span class="ot">&lt;-</span> <span class="fu">run_cea_ward</span>(p_x)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  tb[<span class="st">"culture"</span>, <span class="st">"nmb"</span>] <span class="sc">-</span> tb[<span class="st">"usual"</span>, <span class="st">"nmb"</span>]</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>gap_sp1 <span class="ot">&lt;-</span> <span class="fu">nmb_gap_sp</span>(<span class="dv">1</span>)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>gap_splow <span class="ot">&lt;-</span> <span class="fu">nmb_gap_sp</span>(SP_LOW)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(gap_sp1 <span class="sc">&gt;=</span> <span class="fu">nmb_gap_sp</span>(p<span class="sc">$</span>sp_culture), <span class="fu">nmb_gap_sp</span>(p<span class="sc">$</span>sp_culture) <span class="sc">&gt;=</span> gap_splow)   <span class="co"># more false positives never help</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>sp_breakeven <span class="ot">&lt;-</span> <span class="cf">if</span> (gap_sp1 <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;&amp;</span> gap_splow <span class="sc">&lt;</span> <span class="dv">0</span>) <span class="fu">uniroot</span>(nmb_gap_sp, <span class="fu">c</span>(SP_LOW, <span class="dv">1</span>))<span class="sc">$</span>root <span class="cf">else</span> <span class="cn">NA_real_</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>noncarrier_share <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> prev_end           <span class="co"># share of ICU beds without CRE in usual care (who can be false positive)</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">nmb_gap_sp1_million =</span> gap_sp1 <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">nmb_gap_splow_million =</span> gap_splow <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">sp_breakeven =</span> sp_breakeven), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  nmb_gap_sp1_million nmb_gap_splow_million          sp_breakeven 
              986.923               965.795                    NA </code></pre>
</div>
</div>
<p>Với độ đặc hiệu 98%, các lượt dương tính giả của nuôi cấy tốn 2.2 triệu VNĐ ngày PNTX mỗi năm; ở độ đặc hiệu 95% là 5.5 triệu VNĐ. Ngay cả khi độ đặc hiệu chỉ 50%, nuôi cấy vẫn có NMB cao hơn thường quy: trong ICU này chỉ 16% số giường là người không mang CRE, nên rất ít người có thể bị dương tính giả. Ở một khoa ít CRE, độ đặc hiệu sẽ quan trọng hơn nhiều. Nếu coi thường quy không phát hiện lâm sàng ai, nuôi cấy thêm 12.9 QALY thay vì 11.1, tức lợi ích của sàng lọc bị thổi phồng 16%, và chiến lược có NMB cao nhất thành “PCR nhanh + PNTX” thay vì “Nuôi cấy + PNTX”: giả định về thường quy đủ để đổi lựa chọn.</p>
<p>Bây giờ định giá kháng thuốc tương lai theo ba kênh đã nêu: (a) cộng chi phí ngoại ứng của kháng sinh dự trữ vào chi phí; (b) định giá người mang CRE ra viện; (c) chạy lại với thời gian triển khai 5 năm, có và không có xu hướng kháng thuốc gia tăng.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (a) Resistance externality of the reserve antibiotics used for CRE infections (average cost per SU)</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>ext_cost <span class="ot">&lt;-</span> tab<span class="sc">$</span>abx_su <span class="sc">*</span> <span class="fu">amr_cost_su</span>(p)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>nmb_ext <span class="ot">&lt;-</span> tab<span class="sc">$</span>qaly <span class="sc">*</span> p<span class="sc">$</span>wtp <span class="sc">-</span> (tab<span class="sc">$</span>cost <span class="sc">+</span> ext_cost)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">data.frame</span>(<span class="at">row.names =</span> STRATEGIES, <span class="at">abx_su =</span> tab<span class="sc">$</span>abx_su,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">ext_cost_million =</span> ext_cost <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">nmb_million =</span> tab<span class="sc">$</span>nmb <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">nmb_with_ext_million =</span> nmb_ext <span class="sc">/</span> <span class="fl">1e6</span>), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        abx_su ext_cost_million nmb_million nmb_with_ext_million
usual   4119.9             41.1    -30980.0             -31021.2
culture 3888.9             38.8    -29994.0             -30032.9
pcr     3764.6             37.6    -30000.8             -30038.4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>rank_same <span class="ot">&lt;-</span> <span class="fu">identical</span>(<span class="fu">order</span>(<span class="sc">-</span>tab<span class="sc">$</span>nmb), <span class="fu">order</span>(<span class="sc">-</span>nmb_ext))   <span class="co"># does the ranking change?</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>rank_same</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (b) Carriers discharged to other wards or hospitals: value the further colonisations they start</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>sp_val <span class="ot">&lt;-</span> <span class="fu">spillover_value</span>(p, tab)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>colonised_out_averted <span class="ot">&lt;-</span> tab[<span class="st">"usual"</span>, <span class="st">"col_discharges"</span>] <span class="sc">-</span> tab[<span class="fu">c</span>(<span class="st">"culture"</span>, <span class="st">"pcr"</span>), <span class="st">"col_discharges"</span>]   <span class="co"># raw counts</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>extra_acq_averted <span class="ot">&lt;-</span> sp_val<span class="sc">$</span>extra_acq[<span class="dv">1</span>] <span class="sc">-</span> sp_val<span class="sc">$</span>extra_acq[<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>]                                         <span class="co"># discounted</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>cost_sp <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">setNames</span>(tab<span class="sc">$</span>cost <span class="sc">+</span> sp_val<span class="sc">$</span>cost, STRATEGIES)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>qaly_sp <span class="ot">&lt;-</span> stats<span class="sc">::</span><span class="fu">setNames</span>(tab<span class="sc">$</span>qaly <span class="sc">+</span> sp_val<span class="sc">$</span>qaly, STRATEGIES)</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>fr_sp <span class="ot">&lt;-</span> <span class="fu">cea_frontier</span>(cost_sp, qaly_sp)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>icer_pcr_sp <span class="ot">&lt;-</span> fr_sp<span class="sc">$</span>icer[fr_sp<span class="sc">$</span>strategy <span class="sc">==</span> <span class="st">"pcr"</span>]</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">colonised_out_averted =</span> colonised_out_averted, <span class="at">extra_acq_averted =</span> extra_acq_averted,</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">icer_pcr_with_spillover_million =</span> icer_pcr_sp <span class="sc">/</span> <span class="fl">1e6</span>), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         colonised_out_averted1          colonised_out_averted2 
                           33.2                            51.1 
             extra_acq_averted1              extra_acq_averted2 
                            1.6                             2.5 
icer_pcr_with_spillover_million 
                          119.3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (c) Longer run: with a constant admission prevalence the model is stationary, so a longer</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># horizon only scales cost and QALY; resistance that grows (a rising admission prevalence) changes</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># the dynamics. Compare one year, five years stationary, and five years with a rising trend.</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>days_long <span class="ot">&lt;-</span> p<span class="sc">$</span>horizon_years_long <span class="sc">*</span> <span class="dv">365</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>tab5 <span class="ot">&lt;-</span> <span class="fu">run_cea_ward</span>(p, <span class="at">days =</span> days_long)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>tab5_trend <span class="ot">&lt;-</span> <span class="fu">run_cea_ward</span>(p, <span class="at">days =</span> days_long, <span class="at">phi_trend =</span> p<span class="sc">$</span>phi_trend_year)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>frontier_info <span class="ot">&lt;-</span> <span class="cf">function</span>(tb) {</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  f <span class="ot">&lt;-</span> <span class="fu">cea_frontier</span>(stats<span class="sc">::</span><span class="fu">setNames</span>(tb<span class="sc">$</span>cost, STRATEGIES), stats<span class="sc">::</span><span class="fu">setNames</span>(tb<span class="sc">$</span>qaly, STRATEGIES))</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">usual_status =</span> f<span class="sc">$</span>status[f<span class="sc">$</span>strategy <span class="sc">==</span> <span class="st">"usual"</span>],</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">icer_culture_million =</span> f<span class="sc">$</span>icer[f<span class="sc">$</span>strategy <span class="sc">==</span> <span class="st">"culture"</span>] <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">icer_pcr_million =</span> f<span class="sc">$</span>icer[f<span class="sc">$</span>strategy <span class="sc">==</span> <span class="st">"pcr"</span>] <span class="sc">/</span> <span class="fl">1e6</span>)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>runs <span class="ot">&lt;-</span> <span class="fu">list</span>(tab, tab5, tab5_trend)</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>horizon_tab <span class="ot">&lt;-</span> <span class="fu">cbind</span>(</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">scenario =</span> <span class="fu">c</span>(<span class="st">"1 year, stationary"</span>, <span class="st">"5 years, stationary"</span>, <span class="st">"5 years, rising prevalence"</span>),</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">acq_usual =</span> <span class="fu">sapply</span>(runs, <span class="cf">function</span>(tb) tb[<span class="st">"usual"</span>, <span class="st">"acq"</span>]),</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">d_cost_culture_million =</span> <span class="fu">sapply</span>(runs, <span class="cf">function</span>(tb) (tb[<span class="st">"culture"</span>, <span class="st">"cost"</span>] <span class="sc">-</span> tb[<span class="st">"usual"</span>, <span class="st">"cost"</span>]) <span class="sc">/</span> <span class="fl">1e6</span>),</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(runs, frontier_info))</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>horizon_show <span class="ot">&lt;-</span> horizon_tab</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>horizon_show[, <span class="fu">c</span>(<span class="st">"acq_usual"</span>, <span class="st">"d_cost_culture_million"</span>, <span class="st">"icer_culture_million"</span>, <span class="st">"icer_pcr_million"</span>)] <span class="ot">&lt;-</span></span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(horizon_tab[, <span class="fu">c</span>(<span class="st">"acq_usual"</span>, <span class="st">"d_cost_culture_million"</span>, <span class="st">"icer_culture_million"</span>, <span class="st">"icer_pcr_million"</span>)], <span class="dv">1</span>)</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>horizon_show</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    scenario acq_usual d_cost_culture_million usual_status
1         1 year, stationary     603.3                  410.5     frontier
2        5 years, stationary    3016.7                 1945.9     frontier
3 5 years, rising prevalence    2704.6                 2158.7     frontier
  icer_culture_million icer_pcr_million
1                 36.9            126.6
2                 37.0            127.1
3                 44.3            135.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>icer_pcr_5y <span class="ot">&lt;-</span> horizon_tab<span class="sc">$</span>icer_pcr_million[<span class="dv">2</span>] <span class="sc">*</span> <span class="fl">1e6</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>icer_pcr_trend <span class="ot">&lt;-</span> horizon_tab<span class="sc">$</span>icer_pcr_million[<span class="dv">3</span>] <span class="sc">*</span> <span class="fl">1e6</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>icer_change_5y <span class="ot">&lt;-</span> icer_pcr_5y <span class="sc">/</span> icer_pcr <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>icer_change_trend <span class="ot">&lt;-</span> icer_pcr_trend <span class="sc">/</span> icer_pcr <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>status_trend <span class="ot">&lt;-</span> horizon_tab<span class="sc">$</span>usual_status[<span class="dv">3</span>]</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>icer_culture_trend <span class="ot">&lt;-</span> horizon_tab<span class="sc">$</span>icer_culture_million[<span class="dv">3</span>] <span class="sc">*</span> <span class="fl">1e6</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>phi_year5 <span class="ot">&lt;-</span> p<span class="sc">$</span>phi_adm <span class="sc">+</span> p<span class="sc">$</span>phi_trend_year <span class="sc">*</span> p<span class="sc">$</span>horizon_years_long</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="co"># A stationary model must not change the ICER much; if it did, something other than scale is moving</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">abs</span>(icer_change_5y) <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Về kênh (a), với <span class="math inline">\(c_{AMR}\)</span> ≈ US$0.4 mỗi SU, phần ngoại ứng không làm thay đổi thứ hạng các chiến lược. Kênh (b): nuôi cấy giảm 33 và PCR giảm 51 người mang CRE ra viện mỗi năm (số đếm thô); với 0.05 ca định cư mới trên mỗi người ra viện (giá trị minh họa), ICER của PCR so với nuôi cấy là 119.3 thay vì 126.6 triệu VNĐ/QALY, đủ để đưa PCR sang phía bên kia ngưỡng. Kênh (c): khi tỷ lệ mang CRE khi nhập viện không đổi, 5 năm chỉ nhân quy mô lên (ICER của PCR 127.1 triệu VNĐ/QALY, chênh 0.3%). Khi tỷ lệ này tăng từ 31% lên 46%, ICER của PCR là 135.5 triệu VNĐ/QALY (chênh 7.0%) và ICER của nuôi cấy so với thường quy là 44.3 triệu VNĐ/QALY. Sàng lọc kém hiệu quả hơn khi kháng thuốc gia tăng, vì khi nhiều người mang khuẩn từ ngoài vào hơn thì còn ít người chưa mang khuẩn để bảo vệ. Thời gian dài chỉ có ý nghĩa khi mô hình có động lực thay đổi theo thời gian.</p>
<p>Cuối cùng là PSA với 1,000 bộ tham số. Mỗi tham số có phân phối beta, gamma hay lognormal trong <code>params/</code> được rút ngẫu nhiên với trung bình bằng giá trị cơ sở, khớp với khoảng thấp-cao (xem M03). PSA này cũng rút các nguy cơ tức thời của Bài 2 (gamma, với số sự kiện kỳ vọng của một đoàn hệ 20,000 lượt nhập viện), số năm sống mất đi và số ngày dùng kháng sinh, là những đầu vào bất định nhất và chi phối QALY. Các nguy cơ này chỉ mang sai số lấy mẫu, chưa mang sai lệch do gây nhiễu, nên khoảng bất định vẫn hẹp hơn thực tế. Kiểm tra: mọi kết quả hữu hạn, số sự kiện khớp đoàn hệ, và trung bình các phân phối khớp giá trị cơ sở.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">605</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>draws <span class="ot">&lt;-</span> <span class="fu">sample_params</span>(p, N_PSA)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>varied <span class="ot">&lt;-</span> <span class="fu">names</span>(draws)[<span class="fu">sapply</span>(draws, <span class="cf">function</span>(x) stats<span class="sc">::</span><span class="fu">sd</span>(x) <span class="sc">&gt;</span> <span class="dv">0</span>)]</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>varied</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "share_excess_icu" "dur_abx"          "hr_post_icu"      "c_amr_su_usd"    
 [5] "c_cp_ppe_day"     "p_inf_col"        "qaly_loss_inf"    "u_survivor"      
 [9] "h_dis_0"          "h_dth_0"          "h_dis_s"          "h_dth_s"         
[13] "h_dis_r"          "h_dth_r"          "los_icu"          "phi_adm"         
[17] "beta_tx"          "eps_cp"           "p_clin_cp"        "se_culture"      
[21] "sp_culture"       "se_pcr"           "sp_pcr"           "c_abx_s_day"     
[25] "c_abx_r_day"     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Parameters the ward CEA reads (the infection hazards h_inf_* do not affect the excess measures)</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>used_in_ward_cea <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"n_beds"</span>, <span class="st">"los_icu"</span>, <span class="st">"phi_adm"</span>, <span class="st">"beta_tx"</span>, <span class="st">"eps_cp"</span>, <span class="st">"p_clin_cp"</span>,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"se_culture"</span>, <span class="st">"sp_culture"</span>, <span class="st">"se_pcr"</span>, <span class="st">"sp_pcr"</span>, <span class="st">"screen_interval"</span>,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"delay_culture"</span>, <span class="st">"delay_pcr"</span>, <span class="st">"c_test_culture"</span>, <span class="st">"c_test_pcr"</span>,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"c_cp_ppe_day"</span>, <span class="st">"cp_staff_min_day"</span>, <span class="st">"wage_min"</span>,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"p_inf_col"</span>, <span class="st">"c_bedday"</span>, <span class="st">"c_bedday_ward"</span>, <span class="st">"share_excess_icu"</span>,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"c_abx_r_day"</span>, <span class="st">"dur_abx"</span>, <span class="st">"qaly_loss_inf"</span>, <span class="st">"u_survivor"</span>, <span class="st">"age_icu"</span>, <span class="st">"hr_post_icu"</span>,</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"disc_rate"</span>, <span class="st">"horizon_days"</span>, <span class="st">"wtp"</span>,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"h_dis_0"</span>, <span class="st">"h_dth_0"</span>, <span class="st">"h_dis_s"</span>, <span class="st">"h_dth_s"</span>, <span class="st">"h_dis_r"</span>, <span class="st">"h_dth_r"</span>)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>fixed_used <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(used_in_ward_cea, varied)</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>fixed_used</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "n_beds"           "screen_interval"  "delay_culture"    "delay_pcr"       
 [5] "c_test_culture"   "c_test_pcr"       "cp_staff_min_day" "wage_min"        
 [9] "c_bedday"         "c_bedday_ward"    "age_icu"          "disc_rate"       
[13] "horizon_days"     "wtp"             </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(used_in_ward_cea <span class="sc">%in%</span> <span class="fu">names</span>(p)))</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The event counts behind the hazard distributions (params/los_sim.csv) must match the cohort</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co"># and hazards they were derived from, otherwise the PSA width is not what the text says</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>H0 <span class="ot">&lt;-</span> <span class="fu">ms_hazards_true</span>(p)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>h_a <span class="ot">&lt;-</span> <span class="fu">sum</span>(H0[<span class="st">"Adm"</span>, ])</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>n_s <span class="ot">&lt;-</span> p<span class="sc">$</span>n_cohort <span class="sc">*</span> H0[<span class="st">"Adm"</span>, <span class="st">"InfS"</span>] <span class="sc">/</span> h_a</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>n_r <span class="ot">&lt;-</span> p<span class="sc">$</span>n_cohort <span class="sc">*</span> H0[<span class="st">"Adm"</span>, <span class="st">"InfR"</span>] <span class="sc">/</span> h_a</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>expected_events <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">h_dis_0 =</span> H0[<span class="st">"Adm"</span>, <span class="st">"Disch"</span>] <span class="sc">*</span> p<span class="sc">$</span>n_cohort <span class="sc">/</span> h_a,</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">h_dth_0 =</span> H0[<span class="st">"Adm"</span>, <span class="st">"Dead"</span>] <span class="sc">*</span> p<span class="sc">$</span>n_cohort <span class="sc">/</span> h_a,</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>                     <span class="at">h_dis_s =</span> H0[<span class="st">"InfS"</span>, <span class="st">"Disch"</span>] <span class="sc">*</span> n_s <span class="sc">/</span> <span class="fu">sum</span>(H0[<span class="st">"InfS"</span>, ]),</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>                     <span class="at">h_dth_s =</span> H0[<span class="st">"InfS"</span>, <span class="st">"Dead"</span>] <span class="sc">*</span> n_s <span class="sc">/</span> <span class="fu">sum</span>(H0[<span class="st">"InfS"</span>, ]),</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>                     <span class="at">h_dis_r =</span> H0[<span class="st">"InfR"</span>, <span class="st">"Disch"</span>] <span class="sc">*</span> n_r <span class="sc">/</span> <span class="fu">sum</span>(H0[<span class="st">"InfR"</span>, ]),</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>                     <span class="at">h_dth_r =</span> H0[<span class="st">"InfR"</span>, <span class="st">"Dead"</span>] <span class="sc">*</span> n_r <span class="sc">/</span> <span class="fu">sum</span>(H0[<span class="st">"InfR"</span>, ]))</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>csv_events <span class="ot">&lt;-</span> ptab<span class="sc">$</span>dist_p1[<span class="fu">match</span>(<span class="fu">names</span>(expected_events), ptab<span class="sc">$</span>name)]</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(csv_events <span class="sc">/</span> expected_events <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">&lt;</span> <span class="fl">0.02</span>))</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Each distribution is built to have mean equal to the base value (value = mean)</span></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>chk <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"beta_tx"</span>, <span class="st">"c_amr_su_usd"</span>, <span class="st">"hr_post_icu"</span>, <span class="st">"h_dth_r"</span>, <span class="st">"c_abx_r_day"</span>)</span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>tol <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">beta_tx =</span> <span class="fl">0.03</span>, <span class="at">c_amr_su_usd =</span> <span class="fl">0.07</span>, <span class="at">hr_post_icu =</span> <span class="fl">0.05</span>, <span class="at">h_dth_r =</span> <span class="fl">0.02</span>, <span class="at">c_abx_r_day =</span> <span class="fl">0.03</span>)</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">colMeans</span>(draws[chk]) <span class="sc">/</span> <span class="fu">unlist</span>(p[chk]), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     beta_tx c_amr_su_usd  hr_post_icu      h_dth_r  c_abx_r_day 
       0.995        1.011        0.998        0.998        0.994 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(<span class="fu">colMeans</span>(draws[chk]) <span class="sc">/</span> <span class="fu">unlist</span>(p[chk]) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">&lt;</span> tol[chk]))</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>psa <span class="ot">&lt;-</span> <span class="fu">run_psa_ward</span>(draws)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">is.finite</span>(psa<span class="sc">$</span>cost)), <span class="fu">all</span>(<span class="fu">is.finite</span>(psa<span class="sc">$</span>qaly)))</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>d_cost <span class="ot">&lt;-</span> psa<span class="sc">$</span>cost <span class="sc">-</span> psa<span class="sc">$</span>cost[, <span class="st">"usual"</span>]</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>d_qaly <span class="ot">&lt;-</span> psa<span class="sc">$</span>qaly <span class="sc">-</span> psa<span class="sc">$</span>qaly[, <span class="st">"usual"</span>]</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">rbind</span>(<span class="at">mean_d_cost_million =</span> <span class="fu">colMeans</span>(d_cost) <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">mean_d_qaly =</span> <span class="fu">colMeans</span>(d_qaly)), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    usual culture     pcr
mean_d_cost_million     0  396.37 1151.37
mean_d_qaly             0   12.03   19.06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probability that culture screening is cheaper AND better than usual care</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>p_culture_dominant <span class="ot">&lt;-</span> <span class="fu">mean</span>(d_cost[, <span class="st">"culture"</span>] <span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> d_qaly[, <span class="st">"culture"</span>] <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>nmb_psa <span class="ot">&lt;-</span> psa<span class="sc">$</span>qaly <span class="sc">*</span> p<span class="sc">$</span>wtp <span class="sc">-</span> psa<span class="sc">$</span>cost</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>p_best <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="fu">factor</span>(STRATEGIES[<span class="fu">apply</span>(nmb_psa, <span class="dv">1</span>, which.max)], <span class="at">levels =</span> STRATEGIES)) <span class="sc">/</span> N_PSA</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">p_culture_dominant =</span> p_culture_dominant, p_best), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>p_culture_dominant              usual            culture                pcr 
             0.052              0.045              0.480              0.475 </code></pre>
</div>
</div>
<p>Tham số vẫn cố định trong PSA: n_beds, screen_interval, delay_culture, delay_pcr, c_test_culture, c_test_pcr, cp_staff_min_day, wage_min, c_bedday, c_bedday_ward, age_icu, disc_rate, horizon_days, wtp. Nuôi cấy + PNTX vừa rẻ hơn vừa hiệu quả hơn thường quy trong 5% số lần rút. Ở ngưỡng 1 × GDP bình quân đầu người, xác suất mỗi chiến lược có NMB cao nhất là: thường quy 4%, nuôi cấy 48%, PCR nhanh 48%. Hai chiến lược sàng lọc gần như ngang nhau: lựa chọn giữa nuôi cấy và PCR rất bất định, đúng chỗ phân tích giá trị thông tin (M03) cho biết có nên nghiên cứu thêm trước khi quyết định. PSA chỉ phản ánh bất định của tham số đã có phân phối; bất định về cấu trúc, như hai giả định ở trên, nằm trong phân tích kịch bản.</p>
<p>Hai hình sau vẽ kết quả PSA: mặt phẳng chi phí-hiệu quả của hai so sánh liền kề và CEAC. Kiểm tra: xác suất trong CEAC cộng lại bằng 1 ở mọi mức sẵn lòng chi trả; so đám điểm với đường ngưỡng nét đứt.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>plane_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">comparison =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Nuôi cấy + PNTX so với thường quy"</span>, <span class="st">"PCR nhanh + PNTX so với nuôi cấy + PNTX"</span>),</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">each =</span> N_PSA),</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">d_qaly =</span> <span class="fu">c</span>(d_qaly[, <span class="st">"culture"</span>], psa<span class="sc">$</span>qaly[, <span class="st">"pcr"</span>] <span class="sc">-</span> psa<span class="sc">$</span>qaly[, <span class="st">"culture"</span>]),</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">d_cost =</span> <span class="fu">c</span>(d_cost[, <span class="st">"culture"</span>], psa<span class="sc">$</span>cost[, <span class="st">"pcr"</span>] <span class="sc">-</span> psa<span class="sc">$</span>cost[, <span class="st">"culture"</span>]) <span class="sc">/</span> <span class="fl">1e6</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>fig_plane <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(plane_df, <span class="fu">aes</span>(d_qaly, d_cost)) <span class="sc">+</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">colour =</span> <span class="st">"grey60"</span>) <span class="sc">+</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">colour =</span> <span class="st">"grey60"</span>) <span class="sc">+</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.25</span>, <span class="at">size =</span> <span class="fl">0.8</span>, <span class="at">colour =</span> pal_course[<span class="dv">1</span>]) <span class="sc">+</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> p<span class="sc">$</span>wtp <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> pal_course[<span class="dv">2</span>]) <span class="sc">+</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>comparison) <span class="sc">+</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="cf">function</span>(x) <span class="fu">fmt_num</span>(x)) <span class="sc">+</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"QALY tăng thêm"</span>, <span class="at">y =</span> <span class="st">"Chi phí tăng thêm (triệu VNĐ)"</span>,</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="fu">sprintf</span>(<span class="st">"Mặt phẳng chi phí-hiệu quả (PSA, %s lần rút)"</span>, <span class="fu">fmt_num</span>(N_PSA)),</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Nét đứt: ngưỡng 1 × GDP bình quân đầu người; điểm nằm dưới đường là chi phí-hiệu quả"</span>) <span class="sc">+</span></span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_plane, <span class="st">"l05-ce-plane.png"</span>, <span class="at">width =</span> <span class="fl">8.5</span>, <span class="at">height =</span> <span class="fl">4.2</span>)</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>wtp_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">400e6</span>, <span class="at">by =</span> <span class="fl">10e6</span>)</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>ce <span class="ot">&lt;-</span> <span class="fu">ceac</span>(psa, wtp_grid)</span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a>ce<span class="sc">$</span>strategy_vi <span class="ot">&lt;-</span> <span class="fu">factor</span>(STRATEGY_LABELS[ce<span class="sc">$</span>strategy], <span class="at">levels =</span> STRATEGY_LABELS)</span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>fig_ceac <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ce, <span class="fu">aes</span>(wtp <span class="sc">/</span> <span class="fl">1e6</span>, prob, <span class="at">colour =</span> strategy_vi)) <span class="sc">+</span></span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> p<span class="sc">$</span>wtp <span class="sc">/</span> <span class="fl">1e6</span>, <span class="at">linetype =</span> <span class="st">"dotted"</span>) <span class="sc">+</span></span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> pal_course[<span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">1</span>, <span class="dv">2</span>)], <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="cf">function</span>(x) <span class="fu">paste0</span>(<span class="dv">100</span> <span class="sc">*</span> x, <span class="st">"%"</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb47-28"><a href="#cb47-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mức sẵn lòng chi trả (triệu VNĐ/QALY)"</span>, <span class="at">y =</span> <span class="st">"Xác suất chi phí-hiệu quả nhất"</span>,</span>
<span id="cb47-29"><a href="#cb47-29" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Đường cong chấp nhận chi phí-hiệu quả (CEAC)"</span>) <span class="sc">+</span></span>
<span id="cb47-30"><a href="#cb47-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb47-31"><a href="#cb47-31" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_ceac, <span class="st">"l05-ceac.png"</span>, <span class="at">width =</span> <span class="dv">7</span>, <span class="at">height =</span> <span class="dv">4</span>)</span>
<span id="cb47-32"><a href="#cb47-32" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">abs</span>(<span class="fu">tapply</span>(ce<span class="sc">$</span>prob, ce<span class="sc">$</span>wtp, sum) <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">&lt;</span> <span class="fl">1e-12</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l05-ce-plane.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Mặt phẳng chi phí-hiệu quả của hai so sánh liền kề trên đường biên (PSA).</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l05-ceac.png" class="img-fluid figure-img" style="width:85.0%"></p>
<figcaption>Đường cong chấp nhận chi phí-hiệu quả của ba chiến lược.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Mẹo thực hành">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mẹo thực hành
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Viết chuỗi “định cư → nhiễm khuẩn → tử vong, ngày giường → QALY, chi phí” thành bảng trung gian (như <code>tab</code>) trước khi tính ICER, để người đọc kiểm tra từng mắt xích.</li>
<li>Bắt đầu mọi chiến lược từ cùng trạng thái hiện tại, không phải từ khoa “sạch” CRE.</li>
<li>Khi so sánh xét nghiệm, hãy tìm giá hòa vốn (Bài tập 2) và độ đặc hiệu hòa vốn: nhà quản lý thường đàm phán được giá.</li>
<li>Liệt kê các kênh giá trị mô hình <em>không</em> tính và các tham số vẫn cố định, như CHEERS 2022 yêu cầu.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Lỗi thường gặp">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lỗi thường gặp
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Dùng mô hình tĩnh</strong> với nguy cơ định cư cố định: chỉ thấy người được phát hiện, bỏ qua người được bảo vệ gián tiếp, nên đánh giá thấp lợi ích (so sánh M05 Bài 5).</li>
<li><strong>Tính chi phí ca nhiễm khuẩn từ so sánh giản đơn</strong> về thời gian nằm viện: lợi ích bị thổi phồng (Bài 2).</li>
<li><strong>Đếm cả người mang khuẩn từ ngoài vào</strong> như ca “tránh được”: can thiệp trong khoa không đổi số người mang khuẩn khi nhập viện.</li>
<li><strong>Chỉ nhìn độ nhạy và thời gian chờ.</strong> Bỏ qua độ đặc hiệu thì thiếu chi phí dương tính giả; coi thường quy là “không ai được phát hiện” thì thổi phồng lợi ích của sàng lọc.</li>
</ul>
</div>
</div>
</section>
<section id="bài-tập" class="level2">
<h2 class="anchored" data-anchor-id="bài-tập">Bài tập</h2>
<p><strong>Bài 1 (dễ).</strong> Nếu ngưỡng chi phí-hiệu quả là 3 × GDP bình quân đầu người, chiến lược nào có NMB cao nhất?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 1: which strategy has the highest NMB if the threshold were three times higher?</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>w3 <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="sc">*</span> p<span class="sc">$</span>wtp</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>nmb3 <span class="ot">&lt;-</span> tab<span class="sc">$</span>qaly <span class="sc">*</span> w3 <span class="sc">-</span> tab<span class="sc">$</span>cost</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(nmb3) <span class="ot">&lt;-</span> STRATEGIES</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(nmb3 <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   usual  culture      pcr 
-80798.4 -77019.5 -75522.2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(<span class="fu">which.max</span>(nmb3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "pcr"</code></pre>
</div>
</div>
<p>Ở ngưỡng 376 triệu VNĐ/QALY, chiến lược tốt nhất là “PCR nhanh + PNTX”. Điều này khớp với ICER của PCR (126.6 triệu VNĐ/QALY): PCR chỉ đáng chọn khi ngưỡng vượt ICER của nó.</p>
</div>
</div>
</div>
<p><strong>Bài 2 (vừa).</strong> Giá một xét nghiệm PCR phải bằng bao nhiêu để PCR nhanh + PNTX có NMB bằng nuôi cấy + PNTX ở ngưỡng 1 × GDP bình quân đầu người?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Dùng <code>uniroot()</code> trên hiệu NMB giữa hai chiến lược, theo giá xét nghiệm PCR.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 2: PCR test price at which PCR + PNTX and culture + PNTX have equal NMB</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>nmb_gap <span class="ot">&lt;-</span> <span class="cf">function</span>(price) {</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  p_x <span class="ot">&lt;-</span> p</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  p_x<span class="sc">$</span>c_test_pcr <span class="ot">&lt;-</span> price</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  t_x <span class="ot">&lt;-</span> <span class="fu">run_cea_ward</span>(p_x)</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  t_x[<span class="st">"pcr"</span>, <span class="st">"nmb"</span>] <span class="sc">-</span> t_x[<span class="st">"culture"</span>, <span class="st">"nmb"</span>]</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>price_threshold <span class="ot">&lt;-</span> <span class="fu">uniroot</span>(nmb_gap, <span class="fu">c</span>(<span class="dv">0</span>, p<span class="sc">$</span>c_test_pcr))<span class="sc">$</span>root</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(price_threshold)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 767485</code></pre>
</div>
</div>
<p>Giá hòa vốn là 767,485 VNĐ mỗi xét nghiệm, so với giá BHYT 771,700 VNĐ, tức thấp hơn 0.5%. Đây là con số để đưa vào đàm phán giá hoặc để quyết định chỉ dùng PCR cho nhóm nguy cơ cao.</p>
</div>
</div>
</div>
<p><strong>Bài 3 (khó).</strong> Dùng mô hình hai chủng của Bài 4 để đánh giá một năm quản lý sử dụng kháng sinh trong ICU ở ba mức giảm carbapenem (cận dưới, cơ sở, cận trên): số ca nhiễm khuẩn CRE và tử vong tránh được, QALY có thêm, chi phí ròng (chi phí chương trình trừ chi phí điều trị và tiền carbapenem tiết kiệm được, đã chiết khấu), và phần ngoại ứng tiết kiệm được. Nêu ít nhất hai giả định làm kết quả trông tốt hơn thực tế, và một nguy cơ đếm trùng.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Hai mô hình có mức mang CRE cơ sở khác nhau (mô hình hai chủng có tự hết mang khuẩn, mô hình ICU không có). Vì vậy ta chỉ lấy <em>mức giảm tương đối</em> số ca định cư CRE từ mô hình hai chủng, rồi áp vào số ca định cư của chính mô hình ICU ở thường quy. Chi phí và QALY đã chiết khấu; số ca là số đếm thô.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 3: one year of stewardship in a 20-bed ICU, using the two-strain model of Lesson 4 for</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the RELATIVE fall in CRE acquisitions. Its baseline carriage differs from the ward model's</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="co"># (it has spontaneous clearance, the ward model has not), so we apply the relative fall to the</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ward model's own acquisitions under usual care. Everything in cost and QALY is discounted.</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>tp <span class="ot">&lt;-</span> <span class="fu">twostrain_parms</span>(p)</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>eq0 <span class="ot">&lt;-</span> <span class="fu">twostrain_equilibrium</span>(tp)</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>disc365 <span class="ot">&lt;-</span> <span class="fu">discount_weights</span>((<span class="fu">seq_len</span>(<span class="dv">365</span>) <span class="sc">-</span> <span class="fl">0.5</span>) <span class="sc">/</span> <span class="dv">365</span>, p<span class="sc">$</span>disc_rate)</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>w_year <span class="ot">&lt;-</span> <span class="fu">mean</span>(disc365)                                   <span class="co"># average discount weight of a flow spread over the year</span></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>stew_year <span class="ot">&lt;-</span> <span class="cf">function</span>(reduction) {</span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>  f_new <span class="ot">&lt;-</span> p<span class="sc">$</span>f_abx <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> reduction)</span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>  tp_s <span class="ot">&lt;-</span> <span class="fu">twostrain_parms</span>(p, <span class="at">f_abx =</span> f_new)</span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>  yr0 <span class="ot">&lt;-</span> <span class="fu">run_twostrain</span>(tp, <span class="dv">365</span>, <span class="at">y0 =</span> eq0)</span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a>  yr1 <span class="ot">&lt;-</span> <span class="fu">run_twostrain</span>(tp_s, <span class="dv">365</span>, <span class="at">y0 =</span> eq0)</span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>  rel_u <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> yr1<span class="sc">$</span>AcqR[<span class="dv">366</span>] <span class="sc">/</span> yr0<span class="sc">$</span>AcqR[<span class="dv">366</span>]                                    <span class="co"># raw</span></span>
<span id="cb54-15"><a href="#cb54-15" aria-hidden="true" tabindex="-1"></a>  rel_d <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">sum</span>(<span class="fu">diff</span>(yr1<span class="sc">$</span>AcqR) <span class="sc">*</span> disc365) <span class="sc">/</span> <span class="fu">sum</span>(<span class="fu">diff</span>(yr0<span class="sc">$</span>AcqR) <span class="sc">*</span> disc365)    <span class="co"># discounted</span></span>
<span id="cb54-16"><a href="#cb54-16" aria-hidden="true" tabindex="-1"></a>  acq_u <span class="ot">&lt;-</span> tab[<span class="st">"usual"</span>, <span class="st">"acq"</span>] <span class="sc">*</span> rel_u</span>
<span id="cb54-17"><a href="#cb54-17" aria-hidden="true" tabindex="-1"></a>  acq_d <span class="ot">&lt;-</span> tab[<span class="st">"usual"</span>, <span class="st">"acq_d"</span>] <span class="sc">*</span> rel_d</span>
<span id="cb54-18"><a href="#cb54-18" aria-hidden="true" tabindex="-1"></a>  carb_days_saved <span class="ot">&lt;-</span> (p<span class="sc">$</span>f_abx <span class="sc">-</span> f_new) <span class="sc">*</span> p<span class="sc">$</span>n_beds <span class="sc">*</span> <span class="dv">365</span></span>
<span id="cb54-19"><a href="#cb54-19" aria-hidden="true" tabindex="-1"></a>  inf_u <span class="ot">&lt;-</span> acq_u <span class="sc">*</span> p<span class="sc">$</span>p_inf_col</span>
<span id="cb54-20"><a href="#cb54-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">reduction =</span> reduction, <span class="at">rel_fall_acq =</span> rel_u,</span>
<span id="cb54-21"><a href="#cb54-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">infections_averted =</span> inf_u, <span class="at">deaths_averted =</span> inf_u <span class="sc">*</span> av[[<span class="st">"p_death_excess"</span>]],</span>
<span id="cb54-22"><a href="#cb54-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">qaly_gain =</span> acq_d <span class="sc">*</span> av[[<span class="st">"qaly_loss"</span>]],</span>
<span id="cb54-23"><a href="#cb54-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">net_cost_million =</span> (p<span class="sc">$</span>c_stew_year <span class="sc">*</span> w_year <span class="sc">-</span> acq_d <span class="sc">*</span> av[[<span class="st">"cost"</span>]] <span class="sc">-</span></span>
<span id="cb54-24"><a href="#cb54-24" aria-hidden="true" tabindex="-1"></a>                          carb_days_saved <span class="sc">*</span> p<span class="sc">$</span>c_carb_day <span class="sc">*</span> w_year) <span class="sc">/</span> <span class="fl">1e6</span>,</span>
<span id="cb54-25"><a href="#cb54-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">ext_saving_million =</span> carb_days_saved <span class="sc">*</span> p<span class="sc">$</span>su_per_day <span class="sc">*</span> <span class="fu">amr_cost_su</span>(p) <span class="sc">*</span> w_year <span class="sc">/</span> <span class="fl">1e6</span>)</span>
<span id="cb54-26"><a href="#cb54-26" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb54-27"><a href="#cb54-27" aria-hidden="true" tabindex="-1"></a>row_s <span class="ot">&lt;-</span> ptab[ptab<span class="sc">$</span>name <span class="sc">==</span> <span class="st">"stew_reduction"</span>, ]</span>
<span id="cb54-28"><a href="#cb54-28" aria-hidden="true" tabindex="-1"></a>stew_tab <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">t</span>(<span class="fu">sapply</span>(<span class="fu">c</span>(row_s<span class="sc">$</span>low, row_s<span class="sc">$</span>value, row_s<span class="sc">$</span>high), stew_year)))</span>
<span id="cb54-29"><a href="#cb54-29" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(stew_tab, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  reduction rel_fall_acq infections_averted deaths_averted qaly_gain
1       0.1         0.03               2.54           0.62      5.06
2       0.3         0.09               8.48           2.06     16.90
3       0.5         0.16              15.79           3.83     31.48
  net_cost_million ext_saving_million
1           412.79               5.15
2             4.47              15.45
3          -485.69              25.76</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>stew <span class="ot">&lt;-</span> <span class="fu">unlist</span>(stew_tab[<span class="dv">2</span>, ])                                       <span class="co"># base case (middle row)</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">diff</span>(stew_tab<span class="sc">$</span>infections_averted) <span class="sc">&gt;</span> <span class="dv">0</span>), <span class="fu">all</span>(<span class="fu">diff</span>(stew_tab<span class="sc">$</span>qaly_gain) <span class="sc">&gt;</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ở mức giảm cơ sở (30%), chương trình làm giảm 9% số ca định cư, tránh 8.5 ca nhiễm khuẩn CRE và 2.1 ca tử vong, thêm 16.9 QALY, với chi phí ròng 4 triệu VNĐ (số âm nghĩa là tiết kiệm; chi phí chương trình 600 triệu VNĐ mỗi năm là giá trị minh họa). Kết quả nhạy với mức giảm: ở cận dưới (10%) chương trình tốn thêm 413 triệu VNĐ, ở cận trên (50%) tiết kiệm 486 triệu VNĐ. Hai giả định lạc quan: (1) ngày carbapenem giảm được không bị thay bằng kháng sinh khác có chi phí; (2) tỷ suất loại bỏ chủng nhạy, fitness cost và việc áp mức giảm tương đối từ mô hình này sang mô hình kia đều là giả định minh họa. Nguy cơ đếm trùng: phần ngoại ứng tiết kiệm (15.5 triệu VNĐ) đến từ cùng lượng carbapenem giảm đó, và tác hại của kháng thuốc đã nằm một phần trong số ca CRE tránh được; vì vậy không cộng nó vào chi phí ròng.</p>
</div>
</div>
</div>
</section>
<section id="tài-liệu-tham-khảo" class="level2">
<h2 class="anchored" data-anchor-id="tài-liệu-tham-khảo">Tài liệu tham khảo</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-bai2024accuracy" class="csl-entry" role="listitem">
Bai, Yuanyuan, Hanlin Liu, và Yueling Wang. 2024. <span>“Accuracy of <span>Xpert Carba-R</span> Assay for the Diagnosis of Carbapenemase-producing Organisms from Rectal Swabs in <span>Asia</span>: a Diagnostic Meta-analysis”</span>. <em>Indian Journal of Microbiology</em> 64 (3): 1215–21. <a href="https://doi.org/10.1007/s12088-024-01290-x">https://doi.org/10.1007/s12088-024-01290-x</a>.
</div>
<div id="ref-cuchi2024thau" class="csl-entry" role="listitem">
Bệnh viện Đa khoa khu vực Củ Chi. 2024. <span>“Danh mục giá thầu thuốc bệnh viện 2024 (Lần 2)”</span>. 2024. <a href="https://bvdkkvcuchi.vn/wp-content/uploads/2024/12/DANH-MUC-THUOC-DANG-WEBSITE-BV-nam-2024-lan-2.pdf">https://bvdkkvcuchi.vn/wp-content/uploads/2024/12/DANH-MUC-THUOC-DANG-WEBSITE-BV-nam-2024-lan-2.pdf</a>.
</div>
<div id="ref-thainguyen2023thau" class="csl-entry" role="listitem">
Bệnh viện Trung ương Thái Nguyên. 2023. <span>“Danh mục thuốc trúng thầu tại Bệnh viện Trung ương Thái Nguyên (áp dụng từ ngày 17/10/2023 theo Quyết định số 1580/<span>QĐ-BVTWTN</span>)”</span>. 17 Tháng Mười 2023. <a href="https://bvdktuthainguyen.gov.vn/uploads/media/tai%20lieu/danh%20muc%20thuoc/thuoc%202022-2023/DM%20thu%E1%BB%91c%20tr%C3%BAng%20th%E1%BA%A7u%202023%20BVTW%20TN%20(1).xlsx">https://bvdktuthainguyen.gov.vn/uploads/media/tai%20lieu/danh%20muc%20thuoc/thuoc%202022-2023/DM%20thu%E1%BB%91c%20tr%C3%BAng%20th%E1%BA%A7u%202023%20BVTW%20TN%20(1).xlsx</a>.
</div>
<div id="ref-byt2024qd3220" class="csl-entry" role="listitem">
Bộ Y tế. 2024. <span>“Quyết định số 3220/<span>QĐ-BYT</span> ngày 01/11/2024 về giá dịch vụ khám bệnh, chữa bệnh áp dụng tại Bệnh viện Bạch Mai”</span>. 1 Tháng Mười-Một 2024. <a href="https://apicms.bachmai.gov.vn/documents/37204/1543632/8_Nov_2024_022948_GMTupload_00004592.pdf/b3ab6717-2151-db08-9913-3cfbfd7e0738">https://apicms.bachmai.gov.vn/documents/37204/1543632/8_Nov_2024_022948_GMTupload_00004592.pdf/b3ab6717-2151-db08-9913-3cfbfd7e0738</a>.
</div>
<div id="ref-coast1996superbugs" class="csl-entry" role="listitem">
Coast, J., R. D. Smith, và M. R. Millar. 1996. <span>“Superbugs: should antimicrobial resistance be included as a cost in economic evaluation?”</span> <em>Health Economics</em> 5 (3): 217–26. <a href="https://doi.org/10.1002/(SICI)1099-1050(199605)5:3<217::AID-HEC200>3.0.CO;2-S">https://doi.org/10.1002/(SICI)1099-1050(199605)5:3&lt;217::AID-HEC200&gt;3.0.CO;2-S</a>.
</div>
<div id="ref-gso2026population2025" class="csl-entry" role="listitem">
Cục Thống kê (Bộ Tài chính). 2026. <span>“Thông cáo báo chí về tình hình dân số, lao động, việc làm quý <span>IV</span> và năm 2025”</span>. 5 Tháng Giêng 2026. <a href="https://www.nso.gov.vn/?p=59530">https://www.nso.gov.vn/?p=59530</a>.
</div>
<div id="ref-gandra2014economic" class="csl-entry" role="listitem">
Gandra, S., D. M. Barter, và R. Laxminarayan. 2014. <span>“Economic burden of antibiotic resistance: how much do we really know?”</span> <em>Clinical Microbiology and Infection</em> 20 (10): 973–80. <a href="https://doi.org/10.1111/1469-0691.12798">https://doi.org/10.1111/1469-0691.12798</a>.
</div>
<div id="ref-husereau2022consolidated" class="csl-entry" role="listitem">
Husereau, Don, Michael Drummond, Federico Augustovski, Esther de Bekker-Grob, Andrew H Briggs, Chris Carswell, Lisa Caulley, và c.s. 2022. <span>“Consolidated Health Economic Evaluation Reporting Standards 2022 (CHEERS 2022) statement: updated reporting guidance for health economic evaluations”</span>. <em>BMJ (Clinical research ed.)</em> 376: e067975. <a href="https://doi.org/10.1136/bmj-2021-067975">https://doi.org/10.1136/bmj-2021-067975</a>.
</div>
<div id="ref-naylor2018estimating" class="csl-entry" role="listitem">
Naylor, Nichola R., Rifat Atun, Nina Zhu, Kavian Kulasabanathan, Sachin Silva, Anuja Chatterjee, và c.s. 2018. <span>“Estimating the burden of antimicrobial resistance: a systematic literature review”</span>. <em>Antimicrobial Resistance and Infection Control</em> 7: 58. <a href="https://doi.org/10.1186/s13756-018-0336-y">https://doi.org/10.1186/s13756-018-0336-y</a>.
</div>
<div id="ref-pitman2012dynamic" class="csl-entry" role="listitem">
Pitman, Richard, David Fisman, Gregory S. Zaric, Maarten Postma, Mirjam Kretzschmar, John Edmunds, và c.s. 2012. <span>“Dynamic transmission modeling: a report of the <span>ISPOR-SMDM</span> Modeling Good Research Practices Task Force Working Group-5”</span>. <em>Medical Decision Making</em> 32 (5): 712–21. <a href="https://doi.org/10.1177/0272989X12454578">https://doi.org/10.1177/0272989X12454578</a>.
</div>
<div id="ref-shrestha2018enumerating" class="csl-entry" role="listitem">
Shrestha, Poojan, Ben S. Cooper, Joanna Coast, Raymond Oppong, Nga Do Thi Thuy, Tuangrat Phodha, và c.s. 2018. <span>“Enumerating the economic cost of antimicrobial resistance per antibiotic consumed to inform the evaluation of interventions affecting their use”</span>. <em>Antimicrobial Resistance and Infection Control</em> 7: 98. <a href="https://doi.org/10.1186/s13756-018-0384-3">https://doi.org/10.1186/s13756-018-0384-3</a>.
</div>
<div id="ref-tischendorf2016risk" class="csl-entry" role="listitem">
Tischendorf, Jessica, Rafael Almeida de Avila, và Nasia Safdar. 2016. <span>“Risk of infection following colonization with carbapenem-resistant <span>Enterobactericeae</span>: a systematic review”</span>. <em>American Journal of Infection Control</em> 44 (5): 539–43. <a href="https://doi.org/10.1016/j.ajic.2015.12.005">https://doi.org/10.1016/j.ajic.2015.12.005</a>.
</div>
<div id="ref-vandijk2021daily" class="csl-entry" role="listitem">
van Dijk, M D, A F Voor In ’t Holt, S Polinder, J A Severin, và M C Vos. 2021. <span>“The daily direct costs of isolating patients identified with highly resistant micro-organisms in a non-outbreak setting”</span>. <em>Journal of Hospital Infection</em> 109: 88–95. <a href="https://doi.org/10.1016/j.jhin.2020.12.013">https://doi.org/10.1016/j.jhin.2020.12.013</a>.
</div>
<div id="ref-wozniak2019using" class="csl-entry" role="listitem">
Wozniak, Teresa M., Louise Barnsbee, Xing J. Lee, và Rosana E. Pacella. 2019. <span>“Using the best available data to estimate the cost of antimicrobial resistance: a systematic review”</span>. <em>Antimicrobial Resistance and Infection Control</em> 8: 26. <a href="https://doi.org/10.1186/s13756-019-0472-z">https://doi.org/10.1186/s13756-019-0472-z</a>.
</div>
</div>
<div class="video-script">
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kịch bản video (~15 phút)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Slide</th>
<th>Lời giảng chính</th>
<th>Hình/Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Vì sao AMR khó đánh giá</td>
<td>Chi phí trước mắt, lợi ích gián tiếp và bất định</td>
<td>Bảng 4 thành phần</td>
</tr>
<tr class="even">
<td>2</td>
<td>Chọn phản thực</td>
<td>Ngăn định cư: so với không nhiễm; xét nghiệm định hướng điều trị: so với nhiễm khuẩn nhạy</td>
<td>Liên hệ Bài 1, M01</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Ba chiến lược</td>
<td>Thường quy (có phát hiện lâm sàng), nuôi cấy, PCR nhanh; giá BHYT; một ngày PNTX; ngăn chờ kết quả; dương tính giả</td>
<td><code>l05-strategies</code></td>
</tr>
<tr class="even">
<td>4</td>
<td>Chuỗi kết cục</td>
<td>Định cư → nhiễm khuẩn → tử vong, ngày giường → QALY, chi phí</td>
<td>Hệ phương trình chi phí</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Kết quả cơ sở</td>
<td>Số ca tránh được; chi phí từng thành phần</td>
<td><code>figs/l05-costs.png</code></td>
</tr>
<tr class="even">
<td>6</td>
<td>Đường biên hiệu quả</td>
<td>Dominance, ICER của PCR; kiểm tra bằng ví dụ nhỏ</td>
<td><code>l05-frontier</code></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Hai giả định</td>
<td>Độ đặc hiệu ít quan trọng khi gần như ai cũng mang CRE; thường quy không phát hiện ai thổi phồng lợi ích</td>
<td><code>l05-assumptions</code></td>
</tr>
<tr class="even">
<td>8</td>
<td>Kháng thuốc tương lai</td>
<td>Ba kênh: ngoại ứng (trung bình, đếm trùng), lan tỏa, kháng thuốc gia tăng</td>
<td><code>l05-future</code></td>
</tr>
<tr class="odd">
<td>9</td>
<td>PSA và CEAC</td>
<td>Những gì được rút, những gì vẫn cố định; mặt phẳng chi phí-hiệu quả, CEAC</td>
<td><code>figs/l05-ce-plane.png</code>, <code>figs/l05-ceac.png</code></td>
</tr>
<tr class="even">
<td>10</td>
<td>Giá hòa vốn</td>
<td>Con số để đàm phán</td>
<td>Bài tập 2</td>
</tr>
<tr class="odd">
<td>11</td>
<td>Quản lý sử dụng kháng sinh</td>
<td>Ghép mô hình Bài 4 vào chuỗi kinh tế; chiết khấu; giả định lạc quan</td>
<td>Bài tập 3</td>
</tr>
<tr class="even">
<td>12</td>
<td>Tóm tắt module</td>
<td>Phản thực, thời điểm, lây truyền, chọn lọc, kinh tế</td>
<td>Sơ đồ ở <code>index.qmd</code></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../kb/m06-amr-economics/l04-two-strain-selection.html" class="pagination-link" aria-label="Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../kb/m07-survival-psm/index.html" class="pagination-link" aria-label="M07 · Phân tích sống còn cho mô hình quyết định">
        <span class="nav-page-text">M07 · Phân tích sống còn cho mô hình quyết định</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>