<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="vi" xml:lang="vi"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.30">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bài 1: Khi mô hình đoàn hệ không đủ – Mô hình Kinh tế Y tế với R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../kb/m04-microsimulation/l02-microsim-loops.html" rel="next">
<link href="../../kb/m04-microsimulation/index.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-9e7f0c659d5fa2cace8548cb57964278.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c18d72663580ed8ca19ce2a2f99af51b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="mermaid-theme" content="neutral">
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400&amp;family=JetBrains+Mono:wght@400;600&amp;display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m04-microsimulation/index.html">M04 · Mô phỏng vi mô (microsimulation)</a></li><li class="breadcrumb-item"><a href="../../kb/m04-microsimulation/l01-why-microsimulation.html"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Mô hình Kinh tế Y tế với R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Lời mở đầu</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m00-r-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M00 · R cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l01-reproducible-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Quy trình làm việc tái lập với R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l02-vectors-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Vectơ, ma trận, mảng và phép nhân ma trận</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l03-functions-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hàm, cấu trúc điều khiển, vòng lặp và vectơ hóa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l04-data-frames.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Data frame — nhập, làm sạch, tóm tắt và chuyển dạng dữ liệu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l05-ggplot2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Biểu đồ với ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m00-r-foundations/l06-randomness-monte-carlo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 6: Ngẫu nhiên, mô phỏng Monte Carlo và sai số Monte Carlo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m01-ee-foundations/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M01 · Nền tảng đánh giá kinh tế và cây quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l01-evaluation-types.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại đánh giá kinh tế, quan điểm, khung thời gian và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l02-health-outcomes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Năm sống, QALY và DALY</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l03-decision-rules.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quy tắc ra quyết định: ICER, lấn át, đường biên hiệu quả, NMB và NHB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l04-thresholds.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Ngưỡng chi phí-hiệu quả cho Việt Nam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m01-ee-foundations/l05-decision-tree.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Xây cây quyết định từ đầu trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m02-cohort-markov/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M02 · Mô hình chuyển trạng thái đoàn hệ (Markov)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l01-state-transition.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao cần mô hình chuyển trạng thái</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l02-rates-probabilities.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tỷ suất, xác suất và độ dài chu kỳ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l03-cohort-trace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vết đoàn hệ, giá trị gắn với trạng thái và chiết khấu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l04-time-dependence.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Phụ thuộc thời gian: lão hóa, trạng thái đường hầm và mảng 3 chiều</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m02-cohort-markov/l05-results-verification.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị gắn với lần chuyển, đường biên hiệu quả và xác minh mô hình</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m03-uncertainty-voi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M03 · Bất định, phân tích độ nhạy và giá trị thông tin</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l01-deterministic-sa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Các loại bất định và phân tích độ nhạy tất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l02-distributions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Chọn phân phối cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l03-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích độ nhạy xác suất (PSA) trong R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l04-ceac-reporting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: CEAC, CEAF, tổn thất kỳ vọng và cách báo cáo bất định</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m03-uncertainty-voi/l05-voi.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Giá trị thông tin: EVPI, EVPPI và EVSI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m04-microsimulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M04 · Mô phỏng vi mô (microsimulation)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l01-why-microsimulation.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l02-microsim-loops.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l03-vectorisation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Vectơ hóa theo cá thể và đo hiệu năng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l04-parallel-rcpp.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tính toán song song và Rcpp cho vòng lặp nóng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m04-microsimulation/l05-mc-error-psa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bao nhiêu cá thể là đủ? Sai số Monte Carlo, PSA và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m05-dynamic-transmission/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M05 · Mô hình lây truyền động</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l01-static-vs-dynamic.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Mô hình tĩnh và mô hình lây truyền động</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l02-sir-seir-desolve.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình SIR và SEIR trong R với deSolve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l03-vaccination-herd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Tiêm chủng, hiệu quả trực tiếp và gián tiếp</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l04-dengue-host-vector.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Mô hình vật chủ–véc tơ cho sốt xuất huyết Dengue</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m05-dynamic-transmission/l05-dynamic-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế với mô hình lây truyền động</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m06-amr-economics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M06 · Kinh tế học kháng kháng sinh (AMR)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l01-amr-burden.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Kinh tế học kháng kháng sinh: ngoại ứng, gánh nặng và kịch bản phản thực</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l02-attributable-los.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Thời gian nằm viện và chi phí quy thuộc: sai lệch phụ thuộc thời gian</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l03-ward-transmission.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Mô hình lây truyền CRE trong khoa hồi sức</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l04-two-strain-selection.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Cạnh tranh giữa chủng nhạy và chủng kháng</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m06-amr-economics/l05-amr-intervention-ee.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Đánh giá kinh tế các can thiệp chống kháng kháng sinh</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m07-survival-psm/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M07 · Phân tích sống còn cho mô hình quyết định</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l01-survival-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ôn tập phân tích sống còn cho người làm mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l02-parametric-models.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Mô hình sống còn tham số với flexsurv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l03-extrapolation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Ngoại suy sống còn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l04-reconstruct-ipd.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tái tạo dữ liệu cá thể từ đường KM đã công bố và dùng HR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m07-survival-psm/l05-partitioned-survival.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Mô hình sống còn phân vùng trong R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m08-calibration/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M08 · Hiệu chuẩn mô hình (calibration)</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l01-why-calibrate.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Vì sao phải hiệu chuẩn mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l02-search-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Tìm kiếm tham số: ngẫu nhiên, siêu khối Latin và Nelder–Mead</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l03-bayes-sir.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Hiệu chuẩn Bayes và thuật toán SIR</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m08-calibration/l04-psa-validation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đưa kết quả hiệu chuẩn vào PSA, thẩm định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m09-inputs-vietnam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M09 · Dữ liệu đầu vào cho Việt Nam và LMIC</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l01-costing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Ước tính chi phí cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l02-cost-adjustment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Điều chỉnh chi phí về một năm tham chiếu</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l03-outcome-inputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Đầu vào về kết cục sức khỏe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l04-evidence-synthesis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Tổng hợp bằng chứng cho tham số</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m09-inputs-vietnam/l05-decision-context.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Bối cảnh ra quyết định và báo cáo</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m10-policy-bia-equity/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M10 · Từ mô hình đến chính sách: tác động ngân sách và công bằng</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l01-budget-impact.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Phân tích tác động ngân sách</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l02-distributional-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Phân tích chi phí-hiệu quả theo phân phối (DCEA)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l03-extended-cea.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Phân tích chi phí-hiệu quả mở rộng (ECEA) và bảo vệ rủi ro tài chính</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m10-policy-bia-equity/l04-communicating-hta.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Truyền đạt kết quả cho người ra quyết định và quy trình HTA</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../kb/m11-software-engineering/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">M11 · Kỹ thuật phần mềm cho mô hình kinh tế y tế</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l01-code-structure.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 1: Cấu trúc mã cho mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l02-testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 2: Xác minh và kiểm thử mô hình</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l03-version-control.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 3: Quản lý phiên bản với Git và tái lập môi trường với renv</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l04-r-package.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 4: Đóng gói mô hình thành gói R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/m11-software-engineering/l05-shiny-living.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bài 5: Ứng dụng Shiny và mô hình “sống”</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../kb/glossary.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bảng thuật ngữ Anh–Việt</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../references.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tài liệu tham khảo</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Trong bài</h2>
   
  <ul class="collapse">
  <li><a href="#mục-tiêu-học-tập" id="toc-mục-tiêu-học-tập" class="nav-link active" data-scroll-target="#mục-tiêu-học-tập">Mục tiêu học tập</a></li>
  <li><a href="#ý-chính" id="toc-ý-chính" class="nav-link" data-scroll-target="#ý-chính">Ý chính</a></li>
  <li><a href="#nội-dung" id="toc-nội-dung" class="nav-link" data-scroll-target="#nội-dung">Nội dung</a></li>
  <li><a href="#thực-hành" id="toc-thực-hành" class="nav-link" data-scroll-target="#thực-hành">Thực hành</a></li>
  <li><a href="#bài-tập" id="toc-bài-tập" class="nav-link" data-scroll-target="#bài-tập">Bài tập</a></li>
  <li><a href="#tài-liệu-tham-khảo" id="toc-tài-liệu-tham-khảo" class="nav-link" data-scroll-target="#tài-liệu-tham-khảo">Tài liệu tham khảo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../kb/m04-microsimulation/index.html">M04 · Mô phỏng vi mô (microsimulation)</a></li><li class="breadcrumb-item"><a href="../../kb/m04-microsimulation/l01-why-microsimulation.html"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Bài 1: Khi mô hình đoàn hệ không đủ</span></h1>
<p class="subtitle lead">Nhận ra lúc cần mô phỏng từng người, và phân biệt nhiễu ngẫu nhiên với bất định tham số</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled" title="Vì sao bạn nên quan tâm?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Vì sao bạn nên quan tâm?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ở một phòng khám ngoại trú HIV, hai người cùng được ghi “ổn định, lĩnh thuốc 3 tháng một lần”: một người hầu như không quên thuốc, người kia hay quên vào những tuần đi làm xa. Cả nước có 184,214 người đang điều trị ARV, và khoảng 4% chưa ức chế được virus, tức chừng 7,400 người <span class="citation" data-cites="baolaocai2025hiv35">(<a href="#ref-baolaocai2025hiv35" role="doc-biblioref">Báo Lào Cai 2025</a>)</span>. Mỗi người trong số đó sẽ cần thêm ít nhất một lần xét nghiệm tải lượng, giá BHYT tại một bệnh viện hạng đặc biệt là 979,700 VNĐ, bằng khoảng 4 ngày lương tối thiểu vùng I <span class="citation" data-cites="byt2024qd3220 chinhphu2025nd293 quochoi2019laborcode">(<a href="#ref-byt2024qd3220" role="doc-biblioref">Bộ Y tế 2024</a>; <a href="#ref-chinhphu2025nd293" role="doc-biblioref">Chính phủ 2025</a>; <a href="#ref-quochoi2019laborcode" role="doc-biblioref">Quốc hội 2019</a>)</span>. Họ không phải “người bệnh trung bình”: nguy cơ dồn vào nhóm tuân thủ kém. Bài này giúp bạn quyết định khi nào mô hình đoàn hệ dùng giá trị trung bình là đủ, và khi nào phải mô phỏng từng người.</p>
</div>
</div>
<section id="mục-tiêu-học-tập" class="level2">
<h2 class="anchored" data-anchor-id="mục-tiêu-học-tập">Mục tiêu học tập</h2>
<p>Sau bài này, bạn có thể:</p>
<ol type="1">
<li>Nêu ba tình huống làm mô hình Markov đoàn hệ cho kết quả sai hoặc khó dựng: tính không đồng nhất đi kèm quan hệ phi tuyến, phụ thuộc lịch sử, và bùng nổ số trạng thái.</li>
<li>Tính bằng R chênh lệch giữa “nguy cơ của người trung bình” và “nguy cơ trung bình của quần thể”, và giải thích chênh lệch đó bằng bất đẳng thức Jensen.</li>
<li>Giải thích vì sao nguy cơ tức thời của một quần thể không đồng nhất giảm dần theo thời gian dù nguy cơ của từng người không đổi.</li>
<li>Phân biệt bất định ngẫu nhiên (stochastic, bậc một), bất định tham số (parameter, bậc hai), tính không đồng nhất (heterogeneity) và bất định cấu trúc (structural); chỉ ra loại nào giảm khi tăng số cá thể mô phỏng.</li>
</ol>
</section>
<section id="ý-chính" class="level2">
<h2 class="anchored" data-anchor-id="ý-chính">Ý chính</h2>
<ul>
<li><strong>Mô phỏng vi mô</strong> (microsimulation) là mô hình chuyển trạng thái cấp cá thể: cùng trạng thái, cùng chu kỳ như M02, nhưng mỗi người mang đặc điểm và lịch sử riêng.</li>
<li>Khi kết cục phụ thuộc phi tuyến vào một đặc điểm khác nhau giữa các cá thể, chạy mô hình với <strong>giá trị trung bình</strong> của đặc điểm đó cho kết quả lệch (bất đẳng thức Jensen).</li>
<li>Người nguy cơ cao rời trạng thái trước, nên nguy cơ quan sát được của quần thể giảm dần. Mô hình đoàn hệ một nhóm không tái tạo được điều này.</li>
<li>Khi “đã thất bại virus học bao lâu” hay “còn mấy tháng tư vấn” ảnh hưởng bước sau, mô hình cần <strong>trí nhớ</strong>. Mã hóa trí nhớ bằng trạng thái làm số trạng thái nhân lên; mô phỏng vi mô chỉ thêm vài con số cho mỗi người.</li>
<li>Sai số Monte Carlo (Monte Carlo error) giảm theo <span class="math inline">\(1/\sqrt{N}\)</span>; bất định tham số thì không, nên phân tích độ nhạy xác suất (PSA) cần hai vòng lặp lồng nhau (Bài 5).</li>
<li>Mô phỏng vi mô ở đây không mô tả tương tác giữa người với người; khi cần lây truyền, dùng M05.</li>
</ul>
</section>
<section id="nội-dung" class="level2">
<h2 class="anchored" data-anchor-id="nội-dung">Nội dung</h2>
<section id="từ-đoàn-hệ-sang-từng-cá-thể" class="level3">
<h3 class="anchored" data-anchor-id="từ-đoàn-hệ-sang-từng-cá-thể">Từ đoàn hệ sang từng cá thể</h3>
<p>Mô hình Markov đoàn hệ ở M02 nhân một vectơ tỷ lệ với ma trận chuyển ở mỗi chu kỳ. Đó là cách tính giá trị kỳ vọng nhanh và minh bạch, với hai giả định ngầm: mọi người trong một trạng thái là như nhau, và xác suất chuyển chỉ phụ thuộc trạng thái hiện tại. <strong>Mô phỏng vi mô</strong> bỏ hai giả định này. Ta cho từng người đi qua mô hình, mỗi chu kỳ rút số ngẫu nhiên để quyết định người đó chết, chuyển trạng thái hay ở lại, rồi lấy trung bình trên rất nhiều người <span class="citation" data-cites="siebert2012statetransition krijkamp2018microsimulation">(<a href="#ref-siebert2012statetransition" role="doc-biblioref">Siebert và c.s. 2012</a>; <a href="#ref-krijkamp2018microsimulation" role="doc-biblioref">Krijkamp và c.s. 2018</a>)</span>. Theo <span class="citation" data-cites="brennan2006taxonomy">Brennan, Chick, và Davies (<a href="#ref-brennan2006taxonomy" role="doc-biblioref">2006</a>)</span>, đây là mô hình cá thể, ngẫu nhiên, không có tương tác giữa các cá thể.</p>
<p>Ví dụ xuyên suốt là người nhiễm HIV đang điều trị ARV (antiretroviral therapy, ART) bằng phác đồ bậc một (first-line regimen) TLD, xét nghiệm tải lượng 12 tháng một lần theo hướng dẫn quốc gia <span class="citation" data-cites="byt2021qd5968">(<a href="#ref-byt2021qd5968" role="doc-biblioref">Bộ Y tế 2021</a>)</span>; xem <a href="../../kb/m04-microsimulation/index.html">trang tổng quan</a>. Mức tuân thủ điều trị (adherence) khác nhau giữa người này với người khác, và chính sự khác nhau đó quyết định ai bị thất bại virus học (virological failure: tải lượng virus, viral load, không còn được ức chế, viral suppression), ai xuất hiện kháng thuốc mắc phải (acquired drug resistance), ai phải chuyển phác đồ bậc hai (second-line regimen). Mô hình cá thể có tuân thủ và kháng thuốc như vậy đã được dùng để đánh giá kinh tế các can thiệp HIV ở châu Phi cận Sahara, ví dụ can thiệp theo dõi tuân thủ ARV <span class="citation" data-cites="phillips2016cost">(<a href="#ref-phillips2016cost" role="doc-biblioref">Phillips và c.s. 2016</a>)</span>.</p>
</section>
<section id="lý-do-1-không-đồng-nhất-cộng-với-quan-hệ-phi-tuyến" class="level3">
<h3 class="anchored" data-anchor-id="lý-do-1-không-đồng-nhất-cộng-với-quan-hệ-phi-tuyến">Lý do 1: không đồng nhất cộng với quan hệ phi tuyến</h3>
<p>Trong mô hình, nguy cơ tức thời (hazard) bật lại tải lượng virus của một người có mức tuân thủ <span class="math inline">\(a\)</span> là</p>
<p><span class="math display">\[
r(a) = r_0 \cdot HR_{10}^{\,10(1-a)},
\]</span></p>
<p>với <span class="math inline">\(r_0 =\)</span> 0.009/năm khi tuân thủ 100% và <span class="math inline">\(HR_{10} =\)</span> 2 cho mỗi 10 điểm phần trăm tuân thủ bị mất. Mức tuân thủ trong quần thể theo phân phối Beta với trung bình 90%. Phân phối tuân thủ và độ dốc <span class="math inline">\(HR_{10}\)</span> là giá trị minh họa: chưa có số liệu công khai về tỷ lệ liều thuốc được uống của người bệnh Việt Nam. Còn <span class="math inline">\(r_0\)</span> được chọn để tỷ suất bật lại trung bình của cả quần thể vào khoảng 2.2 trên 100 người-năm, mức quan sát ở người dùng phác đồ có dolutegravir trong một đoàn hệ ở miền Bắc, đã ức chế virus lúc vào đoàn hệ <span class="citation" data-cites="matsumoto2025virological">(<a href="#ref-matsumoto2025virological" role="doc-biblioref">Matsumoto và c.s. 2025</a>)</span>. Quan hệ này cùng chiều với <span class="citation" data-cites="paterson2000adherence">Paterson và c.s. (<a href="#ref-paterson2000adherence" role="doc-biblioref">2000</a>)</span>: tuân thủ càng thấp, thất bại virus học càng nhiều. Nghiên cứu đó theo dõi 99 người Mỹ dùng thuốc ức chế protease, nên nó chỉ gợi ý chiều của quan hệ, không cho độ dốc.</p>
<p>Hàm <span class="math inline">\(r(a)\)</span> lồi theo <span class="math inline">\(a\)</span>. Với một hàm lồi <span class="math inline">\(f\)</span>, <strong>bất đẳng thức Jensen</strong> cho biết <span class="math inline">\(\mathbb{E}[f(A)] \ge f(\mathbb{E}[A])\)</span>: nguy cơ của “người có tuân thủ trung bình” thấp hơn nguy cơ trung bình thật của quần thể. Mô hình đoàn hệ dùng tuân thủ trung bình sẽ đánh giá thấp số ca thất bại virus học, và sai số càng lớn khi quần thể càng không đồng nhất. Bài này áp dụng Jensen cho nguy cơ 12 tháng <span class="math inline">\(1 - e^{-r(a)}\)</span>. Hàm này chỉ lồi khi <span class="math inline">\(r(a) &lt; 1\)</span>, tức chỉ ở vùng tuân thủ đủ cao; ta sẽ kiểm tra vùng đó rộng đến đâu ở phần Thực hành. Cách vá trong mô hình đoàn hệ là chia vài nhóm tuân thủ và chạy riêng từng nhóm, dùng được khi chỉ có một hai đặc điểm.</p>
</section>
<section id="lý-do-2-cạn-kiệt-nhóm-nguy-cơ-cao" class="level3">
<h3 class="anchored" data-anchor-id="lý-do-2-cạn-kiệt-nhóm-nguy-cơ-cao">Lý do 2: cạn kiệt nhóm nguy cơ cao</h3>
<p>Người tuân thủ kém bị bật lại sớm và rời trạng thái “ức chế virus”, nên người còn ở lại ngày càng là người tuân thủ tốt. Nguy cơ tức thời của nhóm còn lại, <span class="math inline">\(h(t) = \mathbb{E}[r(A)e^{-r(A)t}] / \mathbb{E}[e^{-r(A)t}]\)</span>, giảm dần theo thời gian dù nguy cơ của từng người không đổi. Mô hình đoàn hệ một nhóm với tỷ suất cố định cho một đường nằm ngang, sai ở đầu và sai ở cuối.</p>
</section>
<section id="lý-do-3-phụ-thuộc-lịch-sử-và-bùng-nổ-số-trạng-thái" class="level3">
<h3 class="anchored" data-anchor-id="lý-do-3-phụ-thuộc-lịch-sử-và-bùng-nổ-số-trạng-thái">Lý do 3: phụ thuộc lịch sử và bùng nổ số trạng thái</h3>
<p><strong>Giả định Markov</strong> cho rằng xác suất chuyển chỉ phụ thuộc trạng thái hiện tại. Trong ví dụ HIV, nhiều quy luật phụ thuộc vào quá khứ:</p>
<ul>
<li>Số tháng tích lũy sống với virus không ức chế làm tăng nguy cơ tử vong, kể cả sau khi đã ức chế lại.</li>
<li>Kháng thuốc mắc phải chỉ xuất hiện khi đang thất bại virus học trên phác đồ bậc một, và một khi đã có thì không mất đi.</li>
<li>Quy trình xử trí cần một “đồng hồ” riêng cho từng người: xét nghiệm định kỳ, phát hiện tải lượng cao, 3 tháng tư vấn tăng cường tuân thủ, xét nghiệm lại, rồi mới chuyển phác đồ.</li>
</ul>
<p>Mô hình đoàn hệ có thể mang trí nhớ bằng trạng thái đường hầm (tunnel state), như M02 Bài 4. Nhưng phải đếm cho đúng, vì ba loại thông tin xử lý khác nhau:</p>
<ul>
<li>Thứ <strong>thay đổi</strong> trong đường đi của một người và quyết định bước sau (trạng thái sức khỏe, cờ kháng thuốc, các đồng hồ, số tháng thất bại virus học tích lũy) phải thành <strong>trạng thái</strong>. Số mức của chúng nhân với nhau.</li>
<li>Thuộc tính <strong>cố định</strong> (nhóm tuân thủ, tuổi khi vào) chia đoàn hệ thành các <strong>lớp</strong> (strata) chạy riêng. Chúng tăng số lần chạy, không tăng số trạng thái.</li>
<li><strong>Tuổi</strong> theo thời gian xử lý bằng mảng chuyển ba chiều, mỗi chu kỳ một ma trận (M02 Bài 4), không phải một chiều của trạng thái.</li>
</ul>
<p>Đếm như vậy, số trạng thái vẫn rất lớn (con số cụ thể ở phần Thực hành), nhưng ma trận chuyển rất thưa nên máy tính xử lý được. Khó khăn thật là con người phải chỉ định và kiểm tra hàng trăm nghìn xác suất chuyển, và mỗi biến nhớ mới nhân số trạng thái lên một lần nữa, ví dụ cờ “đã từng bị phát hiện thất bại” nhân đôi tất cả. Mô phỏng vi mô giữ cùng thông tin bằng vài con số gắn với mỗi người.</p>
</section>
<section id="bốn-loại-bất-định" class="level3">
<h3 class="anchored" data-anchor-id="bốn-loại-bất-định">Bốn loại bất định</h3>
<p>Báo cáo của nhóm công tác ISPOR-SMDM về ước lượng tham số và phân tích bất định phân biệt bốn khái niệm <span class="citation" data-cites="briggs2012model">(<a href="#ref-briggs2012model" role="doc-biblioref">Briggs và c.s. 2012</a>)</span>; <span class="citation" data-cites="grootkoerkamp2010uncertainty">Groot Koerkamp và c.s. (<a href="#ref-grootkoerkamp2010uncertainty" role="doc-biblioref">2010</a>)</span> minh họa cách phân tích từng loại trong mô hình quyết định:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Loại</th>
<th>Câu hỏi</th>
<th>Trong mô phỏng vi mô</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bất định ngẫu nhiên (stochastic; còn gọi bậc một, first-order)</td>
<td>Hai người giống hệt nhau có kết cục khác nhau vì may rủi</td>
<td>Tạo ra sai số Monte Carlo; giảm khi tăng số cá thể <span class="math inline">\(N\)</span></td>
</tr>
<tr class="even">
<td>Bất định tham số (parameter; còn gọi bậc hai, second-order)</td>
<td>Giá trị thật của tham số là bao nhiêu?</td>
<td>Không giảm khi tăng <span class="math inline">\(N\)</span>; lượng hóa bằng phân tích độ nhạy xác suất (PSA)</td>
</tr>
<tr class="odd">
<td>Tính không đồng nhất (heterogeneity)</td>
<td>Kết cục khác nhau do đặc điểm khác nhau (tuân thủ, tuổi)</td>
<td>Đưa thẳng vào mô hình qua thuộc tính cá thể</td>
</tr>
<tr class="even">
<td>Bất định cấu trúc (structural)</td>
<td>Mô hình có đúng hình dạng không?</td>
<td>Phân tích kịch bản; không phải đối tượng của PSA</td>
</tr>
</tbody>
</table>
<p>Nhầm lẫn hay gặp nhất là coi độ phân tán giữa các cá thể mô phỏng là “khoảng tin cậy” của kết quả; đó là bất định ngẫu nhiên. Với quyết định cho cả quần thể, điều quan trọng là bất định tham số, và ta chỉ thấy nó rõ khi nhiễu ngẫu nhiên đủ nhỏ (Bài 5).</p>
</section>
<section id="khi-nào-không-nên-dùng-mô-phỏng-vi-mô" class="level3">
<h3 class="anchored" data-anchor-id="khi-nào-không-nên-dùng-mô-phỏng-vi-mô">Khi nào không nên dùng mô phỏng vi mô</h3>
<p>Mô phỏng vi mô chậm hơn, khó kiểm tra hơn và đòi dữ liệu cấp cá thể. Nếu kết cục gần tuyến tính theo đặc điểm, hoặc vài nhóm là đủ, mô hình đoàn hệ phân nhóm minh bạch và rẻ hơn. Nếu điều quan trọng là tương tác giữa người với người, cần mô hình lây truyền động hoặc mô phỏng sự kiện rời rạc <span class="citation" data-cites="brennan2006taxonomy rutter2011dynamic">(<a href="#ref-brennan2006taxonomy" role="doc-biblioref">Brennan, Chick, và Davies 2006</a>; <a href="#ref-rutter2011dynamic" role="doc-biblioref">Rutter, Zaslavsky, và Feuer 2011</a>)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>flowchart TD</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  A{"Kết cục phụ thuộc lịch sử&lt;br/&gt;hoặc đồng hồ riêng của từng người?"} --&gt;|Có| B{"Mã hóa bằng vài trạng thái&lt;br/&gt;đường hầm được không?"}</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  A --&gt;|Không| C{"Không đồng nhất có quan hệ&lt;br/&gt;phi tuyến với kết cục?"}</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  B --&gt;|Được| M["Markov đoàn hệ&lt;br/&gt;có trạng thái đường hầm"]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  B --&gt;|Không| MS["Mô phỏng vi mô"]</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  C --&gt;|Không| M0["Markov đoàn hệ"]</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  C --&gt;|Có, vài nhóm là đủ| MG["Markov đoàn hệ phân nhóm"]</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  C --&gt;|Có, nhiều đặc điểm liên tục| MS</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
  A{"Kết cục phụ thuộc lịch sử&lt;br/&gt;hoặc đồng hồ riêng của từng người?"} --&gt;|Có| B{"Mã hóa bằng vài trạng thái&lt;br/&gt;đường hầm được không?"}
  A --&gt;|Không| C{"Không đồng nhất có quan hệ&lt;br/&gt;phi tuyến với kết cục?"}
  B --&gt;|Được| M["Markov đoàn hệ&lt;br/&gt;có trạng thái đường hầm"]
  B --&gt;|Không| MS["Mô phỏng vi mô"]
  C --&gt;|Không| M0["Markov đoàn hệ"]
  C --&gt;|Có, vài nhóm là đủ| MG["Markov đoàn hệ phân nhóm"]
  C --&gt;|Có, nhiều đặc điểm liên tục| MS
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</section>
</section>
<section id="thực-hành" class="level2">
<h2 class="anchored" data-anchor-id="thực-hành">Thực hành</h2>
<p>Phần đầu nạp các hàm dùng chung, các hàm của mô hình và bảng tham số. Dòng in ra cho biết hai tham số Beta của phân phối tuân thủ, suy từ trung bình và độ tập trung <span class="math inline">\(\kappa\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vietnamese text in figures needs a UTF-8 locale (Rscript may start in the "C" locale)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">isTRUE</span>(<span class="fu">l10n_info</span>()[[<span class="st">"UTF-8"</span>]])) <span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="st">"LC_CTYPE"</span>, <span class="st">"en_US.UTF-8"</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/helpers.R"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"../_shared/R/vn_data.R"</span>)   <span class="co"># course-wide values: prices, threshold, life table</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"code/model.R"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">load_hiv_params</span>()             <span class="co"># params/hiv.csv + the shared Vietnamese inputs</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>ab <span class="ot">&lt;-</span> <span class="fu">adherence_beta</span>(p)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>ab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>shape1 shape2 
  10.8    1.2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>DEPLETION_YEARS <span class="ot">&lt;-</span> <span class="dv">30</span>              <span class="co"># depletion plot horizon: with low DTG-era rates selection is slow</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Đoạn sau tính nguy cơ bật lại trong 12 tháng theo hai cách: cho người có tuân thủ trung bình, và trung bình trên toàn phân phối tuân thủ (tích phân số bằng <code>integrate()</code>). Hãy kiểm tra tỷ số lớn hơn 1, đúng như bất đẳng thức Jensen dự báo. Phần cuối đoạn tìm mức tuân thủ mà dưới đó <span class="math inline">\(r(a) &gt; 1\)</span> và tính xem bao nhiêu người nằm ở vùng đó.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 12-month risk of viral rebound on first line, as a function of a person's adherence</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>risk12 <span class="ot">&lt;-</span> <span class="cf">function</span>(a) <span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fu">rebound_rate</span>(a, p<span class="sc">$</span>r_reb1, p))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># (a) risk of the "average person" (mean adherence) -- what a cohort model would use</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>risk_at_mean <span class="ot">&lt;-</span> <span class="fu">risk12</span>(p<span class="sc">$</span>adh_mean)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># (b) average risk over the whole adherence distribution -- what the population experiences</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>mean_risk <span class="ot">&lt;-</span> <span class="fu">integrate</span>(<span class="cf">function</span>(a) <span class="fu">risk12</span>(a) <span class="sc">*</span> <span class="fu">dbeta</span>(a, ab[[<span class="st">"shape1"</span>]], ab[[<span class="st">"shape2"</span>]]), <span class="dv">0</span>, <span class="dv">1</span>)<span class="sc">$</span>value</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>jensen_ratio <span class="ot">&lt;-</span> mean_risk <span class="sc">/</span> risk_at_mean</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">risk_at_mean =</span> risk_at_mean, <span class="at">mean_risk =</span> mean_risk, <span class="at">ratio =</span> jensen_ratio), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>risk_at_mean    mean_risk        ratio 
      0.0178       0.0220       1.2312 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(mean_risk <span class="sc">&gt;</span> risk_at_mean)    <span class="co"># convex risk curve: averaging inputs underestimates risk</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The 12-month risk 1 - exp(-r(a)) is convex only where r(a) &lt; 1 (its second derivative is</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># proportional to r * (1 - r) * exp(-r)). Where is that, and how many people lie outside it?</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>a_convex <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">log</span>(<span class="dv">1</span> <span class="sc">/</span> p<span class="sc">$</span>r_reb1) <span class="sc">/</span> (<span class="dv">10</span> <span class="sc">*</span> <span class="fu">log</span>(p<span class="sc">$</span>hr_adh10))   <span class="co"># r(a) = 1 at this adherence</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>share_not_convex <span class="ot">&lt;-</span> <span class="fu">pbeta</span>(a_convex, ab[[<span class="st">"shape1"</span>]], ab[[<span class="st">"shape2"</span>]])</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">adherence_where_r_equals_1 =</span> a_convex, <span class="at">share_of_people_below =</span> share_not_convex), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>adherence_where_r_equals_1      share_of_people_below 
                    0.3204                     0.0000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(share_not_convex <span class="sc">&lt;</span> <span class="fl">0.01</span>)     <span class="co"># text: almost nobody lies in the non-convex region</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Người có tuân thủ trung bình có nguy cơ 1.78% trong 12 tháng, còn quần thể có nguy cơ trung bình 2.20%. Nguy cơ thật của quần thể cao hơn 23% so với con số mà mô hình đoàn hệ dùng tuân thủ trung bình đưa ra. Nguy cơ 12 tháng chỉ lồi khi tuân thủ trên khoảng 32%; dưới mức đó chỉ có chưa đến 0.01% quần thể, nên kết luận vẫn đứng vững. Hình dưới cho thấy lý do: đuôi trái của phân phối tuân thủ rơi đúng vào phần dốc của đường nguy cơ.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.4</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.005</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>plot_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">adh =</span> grid, <span class="at">y =</span> <span class="fu">dbeta</span>(grid, ab[[<span class="st">"shape1"</span>]], ab[[<span class="st">"shape2"</span>]]),</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">panel =</span> <span class="st">"A. Phân phối mức tuân thủ giữa các cá thể"</span>),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">adh =</span> grid, <span class="at">y =</span> <span class="fu">risk12</span>(grid),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">panel =</span> <span class="st">"B. Nguy cơ bật lại tải lượng virus trong 12 tháng"</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>fig_jensen <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(plot_df, <span class="fu">aes</span>(adh, y)) <span class="sc">+</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">colour =</span> pal_course[<span class="dv">1</span>], <span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> p<span class="sc">$</span>adh_mean, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> pal_course[<span class="dv">2</span>]) <span class="sc">+</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>panel, <span class="at">ncol =</span> <span class="dv">1</span>, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> <span class="cf">function</span>(x) <span class="fu">paste0</span>(<span class="dv">100</span> <span class="sc">*</span> x, <span class="st">"%"</span>)) <span class="sc">+</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mức tuân thủ (tỷ lệ liều thuốc được uống)"</span>, <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Không đồng nhất + quan hệ phi tuyến: trung bình đầu vào ≠ trung bình đầu ra"</span>,</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Đường đứt: mức tuân thủ trung bình. Phân phối tuân thủ và độ dốc HR là giá trị minh họa."</span>) <span class="sc">+</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_jensen, <span class="st">"l01-jensen.png"</span>, <span class="at">width =</span> <span class="dv">7</span>, <span class="at">height =</span> <span class="fl">5.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l01-jensen.png" class="img-fluid figure-img" width="525"></p>
<figcaption>Phân phối tuân thủ (A, giá trị minh họa) và nguy cơ bật lại 12 tháng theo tuân thủ (B).</figcaption>
</figure>
</div>
</div>
</div>
<p>Tiếp theo ta tính nguy cơ tức thời của nhóm còn ức chế virus theo thời gian, bỏ qua tử vong để thấy rõ hiệu ứng chọn lọc. Vì tỷ suất bật lại thời dolutegravir thấp, quá trình chọn lọc diễn ra chậm, nên ta nhìn xa 30 năm. Điểm kiểm tra <code>stopifnot()</code> xác nhận nguy cơ quần thể giảm liên tục và cắt đường của mô hình đoàn hệ.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Hazard of first rebound over time among people still suppressed (ignoring death).</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Heterogeneous population: high-risk people fail first, so the population hazard falls.</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>years <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, DEPLETION_YEARS, <span class="at">by =</span> <span class="fl">0.25</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>rate_a <span class="ot">&lt;-</span> <span class="cf">function</span>(a) <span class="fu">rebound_rate</span>(a, p<span class="sc">$</span>r_reb1, p)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>dens <span class="ot">&lt;-</span> <span class="cf">function</span>(a) <span class="fu">dbeta</span>(a, ab[[<span class="st">"shape1"</span>]], ab[[<span class="st">"shape2"</span>]])</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>surv_het <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(years)); haz_het <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(years))</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k <span class="cf">in</span> <span class="fu">seq_along</span>(years)) {</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  tt <span class="ot">&lt;-</span> years[k]</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  surv_het[k] <span class="ot">&lt;-</span> <span class="fu">integrate</span>(<span class="cf">function</span>(a) <span class="fu">exp</span>(<span class="sc">-</span><span class="fu">rate_a</span>(a) <span class="sc">*</span> tt) <span class="sc">*</span> <span class="fu">dens</span>(a), <span class="dv">0</span>, <span class="dv">1</span>)<span class="sc">$</span>value</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  haz_het[k] <span class="ot">&lt;-</span> <span class="fu">integrate</span>(<span class="cf">function</span>(a) <span class="fu">rate_a</span>(a) <span class="sc">*</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fu">rate_a</span>(a) <span class="sc">*</span> tt) <span class="sc">*</span> <span class="fu">dens</span>(a), <span class="dv">0</span>, <span class="dv">1</span>)<span class="sc">$</span>value <span class="sc">/</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    surv_het[k]</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>haz_cohort <span class="ot">&lt;-</span> <span class="fu">rate_a</span>(p<span class="sc">$</span>adh_mean)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>show_years <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>, DEPLETION_YEARS)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>haz_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">year =</span> show_years, <span class="at">hazard_population =</span> haz_het[<span class="fu">match</span>(show_years, years)],</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>                      <span class="at">hazard_cohort =</span> haz_cohort)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(haz_tab, <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  year hazard_population hazard_cohort
1    0            0.0225         0.018
2   10            0.0192         0.018
3   30            0.0166         0.018</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>year_cross <span class="ot">&lt;-</span> years[<span class="fu">which</span>(haz_het <span class="sc">&lt;</span> haz_cohort)[<span class="dv">1</span>]]   <span class="co"># first time the population hazard is lower</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>year_cross</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">all</span>(<span class="fu">diff</span>(haz_het) <span class="sc">&lt;</span> <span class="dv">0</span>))      <span class="co"># depletion of high-risk people: hazard keeps falling</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(haz_het[<span class="dv">1</span>] <span class="sc">&gt;</span> haz_cohort, <span class="fu">tail</span>(haz_het, <span class="dv">1</span>) <span class="sc">&lt;</span> haz_cohort)   <span class="co"># the two curves cross</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Lúc đầu nguy cơ quần thể là 0.0225/năm, cao hơn mức 0.0180/năm của mô hình đoàn hệ dùng tuân thủ trung bình. Từ khoảng năm thứ 17.5, nguy cơ quần thể xuống dưới mức đó, và sau 30 năm chỉ còn 0.0166/năm. Hai đường cắt nhau: mô hình một nhóm sai theo cả hai chiều tùy thời điểm.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>dep_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">year =</span> years, <span class="at">hazard =</span> haz_het, <span class="at">model =</span> <span class="st">"Quần thể không đồng nhất (mô phỏng vi mô)"</span>),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">year =</span> years, <span class="at">hazard =</span> haz_cohort, <span class="at">model =</span> <span class="st">"Đoàn hệ với tuân thủ trung bình"</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>fig_dep <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(dep_df, <span class="fu">aes</span>(year, hazard, <span class="at">colour =</span> model)) <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> pal_course[<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)], <span class="at">name =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_limits</span>(<span class="at">y =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Năm kể từ khi vào mô hình"</span>, <span class="at">y =</span> <span class="st">"Nguy cơ tức thời bật lại (mỗi năm)"</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Người nguy cơ cao rời trạng thái ức chế trước: nguy cơ quần thể giảm dần"</span>) <span class="sc">+</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_dep, <span class="st">"l01-depletion.png"</span>, <span class="at">width =</span> <span class="dv">7</span>, <span class="at">height =</span> <span class="fl">4.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l01-depletion.png" class="img-fluid figure-img" width="525"></p>
<figcaption>Nguy cơ tức thời bật lại ở nhóm còn ức chế virus.</figcaption>
</figure>
</div>
</div>
</div>
<p>Bây giờ ta đếm số trạng thái một mô hình đoàn hệ cần để nhớ được những gì mô phỏng vi mô nhớ, theo ba loại thông tin ở trên: bảng <code>memory</code> là các biến nhớ nhân thành trạng thái; <code>strata</code> là thuộc tính cố định thành lớp chạy riêng; tuổi đi vào mảng ba chiều nên không có mặt trong số trạng thái. Điểm kiểm tra so sánh số trạng thái với tích các số mức.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How big would a cohort model be if it had to remember what the microsimulation remembers?</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (a) Things that CHANGE during a person's path and drive the next step: they must become</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co">#     states, so they multiply.</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>memory <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">feature =</span> <span class="fu">c</span>(<span class="st">"Trạng thái sức khỏe (S1, F1, S2, F2, D)"</span>, <span class="st">"Kháng thuốc mắc phải (có/không)"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>              <span class="st">"Số tháng tư vấn tăng cường còn lại"</span>, <span class="st">"Số tháng kể từ lần xét nghiệm trước"</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>              <span class="st">"Số tháng tích lũy thất bại virus học (0-120, cắt ở 10 năm)"</span>),</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, p<span class="sc">$</span>eac_months <span class="sc">+</span> <span class="dv">1</span>, p<span class="sc">$</span>vl_soc, <span class="dv">121</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>memory<span class="sc">$</span>states <span class="ot">&lt;-</span> <span class="fu">cumprod</span>(memory<span class="sc">$</span>levels)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>n_states_mem <span class="ot">&lt;-</span> <span class="fu">tail</span>(memory<span class="sc">$</span>states, <span class="dv">1</span>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>memory</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                     feature levels states
1                    Trạng thái sức khỏe (S1, F1, S2, F2, D)      5      5
2                            Kháng thuốc mắc phải (có/không)      2     10
3                         Số tháng tư vấn tăng cường còn lại      4     40
4                        Số tháng kể từ lần xét nghiệm trước     12    480
5 Số tháng tích lũy thất bại virus học (0-120, cắt ở 10 năm)    121  58080</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (b) Fixed attributes are NOT states: each stratum is a separate cohort run</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>strata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">feature =</span> <span class="fu">c</span>(<span class="st">"Nhóm tuân thủ"</span>, <span class="st">"Nhóm tuổi khi vào mô hình (10 năm)"</span>),</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">9</span>))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>n_runs <span class="ot">&lt;-</span> <span class="fu">prod</span>(strata<span class="sc">$</span>levels)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># (c) Age changes with time since entry: one transition matrix per cycle (M02 Lesson 4),</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co">#     not a state dimension. Each row has at most 4 non-zero cells (stay, die, change</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co">#     viral state, acquire resistance), because the counters move deterministically.</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>nnz_per_row <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>dense_gb <span class="ot">&lt;-</span> n_states_mem<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> <span class="dv">8</span> <span class="sc">/</span> <span class="fl">1e9</span>                    <span class="co"># dense matrix, 8 bytes per cell</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>sparse_mb <span class="ot">&lt;-</span> n_states_mem <span class="sc">*</span> nnz_per_row <span class="sc">*</span> <span class="dv">12</span> <span class="sc">/</span> <span class="fl">1e6</span>      <span class="co"># sparse: 8-byte value + 4-byte index</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>cells_to_specify <span class="ot">&lt;-</span> n_states_mem <span class="sc">*</span> nnz_per_row          <span class="co"># formulas to write and check</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="co"># The microsimulation stores 8 numbers per person: state, adherence, age, resistance,</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="co"># cumulative viraemia, counselling clock, next test month, "ever detected" flag</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>bytes_per_person <span class="ot">&lt;-</span> <span class="dv">8</span> <span class="sc">*</span> <span class="dv">8</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>mb_microsim <span class="ot">&lt;-</span> <span class="fl">1e5</span> <span class="sc">*</span> bytes_per_person <span class="sc">/</span> <span class="fl">1e6</span>             <span class="co"># 100,000 people</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">n_states =</span> n_states_mem, <span class="at">n_runs =</span> n_runs, <span class="at">dense_gb =</span> dense_gb, <span class="at">sparse_mb =</span> sparse_mb,</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">cells_to_specify =</span> cells_to_specify, <span class="at">mb_microsim_100k =</span> mb_microsim), <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        n_states           n_runs         dense_gb        sparse_mb 
         58080.0             90.0             27.0              2.8 
cells_to_specify mb_microsim_100k 
        232320.0              6.4 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(n_states_mem <span class="sc">==</span> <span class="dv">5</span> <span class="sc">*</span> <span class="dv">2</span> <span class="sc">*</span> (p<span class="sc">$</span>eac_months <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">*</span> p<span class="sc">$</span>vl_soc <span class="sc">*</span> <span class="dv">121</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mô hình đoàn hệ cần 58,080 trạng thái, chạy 90 lần (mỗi nhóm tuân thủ và tuổi vào một lần). Một ma trận chuyển đầy đủ sẽ nặng khoảng 27 GB, nhưng dạng thưa với tối đa 4 ô khác 0 mỗi hàng chỉ khoảng 2.8 MB. Vậy bộ nhớ không phải rào cản; rào cản là phải chỉ định và kiểm tra khoảng 232,320 xác suất chuyển. Mô phỏng vi mô lưu cùng thông tin cho 100,000 người trong khoảng 6.4 MB.</p>
<p>Cuối cùng là bất định ngẫu nhiên và bất định tham số trên cùng một đầu ra: tỷ lệ người bật lại trong 12 tháng. Ta lặp lại nhiều lần với 100 người, với 10,000 người, và với 10,000 người nhưng rút <span class="math inline">\(r_0\)</span> từ phân phối của nó (một PSA thu nhỏ).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First-order (stochastic) versus second-order (parameter) uncertainty, on one output:</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the share of people with viral rebound within 12 months.</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>share_rebound <span class="ot">&lt;-</span> <span class="cf">function</span>(n, r_reb1) {</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  a <span class="ot">&lt;-</span> <span class="fu">rbeta</span>(n, ab[[<span class="st">"shape1"</span>]], ab[[<span class="st">"shape2"</span>]])</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(<span class="fu">runif</span>(n) <span class="sc">&lt;</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fu">rebound_rate</span>(a, r_reb1, p)))</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>reps <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>first_100 <span class="ot">&lt;-</span> <span class="fu">replicate</span>(reps, <span class="fu">share_rebound</span>(<span class="dv">100</span>, p<span class="sc">$</span>r_reb1))</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>first_10k <span class="ot">&lt;-</span> <span class="fu">replicate</span>(reps, <span class="fu">share_rebound</span>(<span class="dv">10000</span>, p<span class="sc">$</span>r_reb1))</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>dp <span class="ot">&lt;-</span> <span class="fu">dist_params</span>(<span class="fu">attr</span>(p, <span class="st">"table"</span>))</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> dp[dp<span class="sc">$</span>name <span class="sc">==</span> <span class="st">"r_reb1"</span>, ]</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>r_draws <span class="ot">&lt;-</span> <span class="fu">rgamma</span>(reps, <span class="at">shape =</span> g<span class="sc">$</span>p1, <span class="at">scale =</span> g<span class="sc">$</span>p2)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>second_10k <span class="ot">&lt;-</span> <span class="fu">sapply</span>(r_draws, <span class="cf">function</span>(r) <span class="fu">share_rebound</span>(<span class="dv">10000</span>, r))</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>unc_tab <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">source =</span> <span class="fu">c</span>(<span class="st">"Ngẫu nhiên, N = 100"</span>, <span class="st">"Ngẫu nhiên, N = 10,000"</span>, <span class="st">"Tham số (PSA), N = 10,000"</span>),</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> <span class="fu">c</span>(<span class="fu">mean</span>(first_100), <span class="fu">mean</span>(first_10k), <span class="fu">mean</span>(second_10k)),</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> <span class="fu">c</span>(<span class="fu">sd</span>(first_100), <span class="fu">sd</span>(first_10k), <span class="fu">sd</span>(second_10k))</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>unc_tab<span class="sc">$</span>mean <span class="ot">&lt;-</span> <span class="fu">round</span>(unc_tab<span class="sc">$</span>mean, <span class="dv">4</span>); unc_tab<span class="sc">$</span>sd <span class="ot">&lt;-</span> <span class="fu">round</span>(unc_tab<span class="sc">$</span>sd, <span class="dv">4</span>)</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>unc_tab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     source   mean     sd
1       Ngẫu nhiên, N = 100 0.0215 0.0142
2    Ngẫu nhiên, N = 10,000 0.0219 0.0015
3 Tham số (PSA), N = 10,000 0.0214 0.0082</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The third box mixes both sources: Var(total) = Var(parameter) + Var(noise at N = 10,000).</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Subtracting the noise variance leaves the parameter part alone (Lesson 5 does this for a PSA).</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>sd_param_only <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">max</span>(<span class="fu">var</span>(second_10k) <span class="sc">-</span> <span class="fu">var</span>(first_10k), <span class="dv">0</span>))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">sd_total =</span> <span class="fu">sd</span>(second_10k), <span class="at">sd_noise_only =</span> <span class="fu">sd</span>(first_10k), <span class="at">sd_param_only =</span> sd_param_only), <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     sd_total sd_noise_only sd_param_only 
       0.0082        0.0015        0.0081 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>sd_ratio_first <span class="ot">&lt;-</span> <span class="fu">sd</span>(first_100) <span class="sc">/</span> <span class="fu">sd</span>(first_10k)        <span class="co"># theory: sqrt(10000 / 100) = 10</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(sd_ratio_first <span class="sc">&gt;</span> <span class="dv">7</span>, sd_ratio_first <span class="sc">&lt;</span> <span class="dv">13</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Text: the parameter part is real and larger than the noise at N = 10,000 (Exercise 3)</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(sd_param_only <span class="sc">&gt;</span> <span class="fu">sd</span>(first_10k))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Qua 500 lần lặp, tăng từ 100 lên 10,000 người làm độ lệch chuẩn giảm 9.5 lần, gần đúng <span class="math inline">\(\sqrt{100}\)</span> theo lý thuyết. Hộp thứ ba có độ lệch chuẩn 0.82%, gồm cả nhiễu của 10,000 người lẫn bất định của <span class="math inline">\(r_0\)</span>. Trừ phương sai nhiễu đi, riêng phần do tham số là 0.81%. Phần này nằm ở tham số, không ở số người mô phỏng; Bài 5 làm phép trừ này cho một PSA thật.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>unc_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">value =</span> <span class="fu">c</span>(first_100, first_10k, second_10k),</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">source =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(unc_tab<span class="sc">$</span>source, <span class="at">each =</span> reps), <span class="at">levels =</span> unc_tab<span class="sc">$</span>source))</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>fig_unc <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(unc_df, <span class="fu">aes</span>(source, value)) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> pal_course[<span class="dv">5</span>], <span class="at">outlier.size =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="cf">function</span>(x) <span class="fu">paste0</span>(<span class="dv">100</span> <span class="sc">*</span> x, <span class="st">"%"</span>)) <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Tỷ lệ bật lại trong 12 tháng"</span>,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Tăng N làm giảm nhiễu ngẫu nhiên, nhưng không xóa được bất định tham số"</span>) <span class="sc">+</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_course</span>()</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="fu">save_fig</span>(fig_unc, <span class="st">"l01-uncertainty.png"</span>, <span class="at">width =</span> <span class="dv">7</span>, <span class="at">height =</span> <span class="fl">4.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/l01-uncertainty.png" class="img-fluid figure-img" width="525"></p>
<figcaption>Bất định ngẫu nhiên giảm khi tăng N; bất định tham số thì không.</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Mẹo thực hành">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mẹo thực hành
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Trước khi viết mô phỏng vi mô, hãy viết ra danh sách “những gì mô hình phải nhớ” về mỗi người. Nếu danh sách chỉ có một hai mục rời rạc, thử mô hình đoàn hệ phân nhóm hoặc có trạng thái đường hầm trước.</li>
<li>Kiểm tra độ cong của các quan hệ quan trọng như trong hình B: đường gần thẳng thì giá trị trung bình dùng được.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled" title="Lỗi thường gặp">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lỗi thường gặp
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Chạy mô hình đoàn hệ với đặc điểm trung bình</strong> khi kết cục phi tuyến theo đặc điểm đó. Cách phát hiện: tính kết cục cho vài nhóm rồi so trung bình có trọng số với kết quả dùng giá trị trung bình.</li>
<li><strong>Báo cáo độ phân tán giữa các cá thể như khoảng bất định của quyết định.</strong> Đó là bất định ngẫu nhiên.</li>
<li><strong>Đưa tính không đồng nhất vào PSA</strong>, ví dụ rút ngẫu nhiên tuổi của cả đoàn hệ. Tuổi là thuộc tính cá thể, không phải phân phối của tham số.</li>
<li><strong>Nhân cả thuộc tính cố định vào số trạng thái</strong> để “chứng minh” mô hình đoàn hệ không dựng nổi. Thuộc tính cố định là lớp chạy riêng, tuổi là chiều thời gian.</li>
</ul>
</div>
</div>
</section>
<section id="bài-tập" class="level2">
<h2 class="anchored" data-anchor-id="bài-tập">Bài tập</h2>
<ol type="1">
<li><strong>(Dễ)</strong> Tăng độ tập trung của phân phối tuân thủ lên <span class="math inline">\(\kappa = 50\)</span>, tức quần thể đồng nhất hơn. Tỷ số giữa nguy cơ trung bình của quần thể và nguy cơ của người trung bình thay đổi thế nào?</li>
<li><strong>(Vừa)</strong> Một nhóm đề xuất mô hình đoàn hệ “gọn hơn”: chỉ nhớ tối đa 24 tháng thất bại virus học, 3 nhóm tuân thủ, tuổi theo nhóm 10 năm. Mô hình này cần bao nhiêu trạng thái và bao nhiêu lần chạy? Bạn có muốn tự kiểm tra các ma trận chuyển của nó không?</li>
<li><strong>(Khó)</strong> Dựa vào bảng bất định ở trên, giải thích vì sao tăng số cá thể lên vô hạn vẫn không làm hẹp được khoảng bất định của quyết định. Tính tỷ số giữa độ lệch chuẩn do tham số riêng và độ lệch chuẩn do nhiễu khi <span class="math inline">\(N\)</span> = 10,000.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Lời giải">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lời giải
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Bài 1.</strong> Quần thể càng đồng nhất thì giá trị trung bình càng gần đúng; tỷ số tiến về 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 1: less heterogeneity (kappa = 50) shrinks the gap between (a) and (b)</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>p_ex <span class="ot">&lt;-</span> p</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>p_ex<span class="sc">$</span>adh_kappa <span class="ot">&lt;-</span> <span class="dv">50</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>ab_ex <span class="ot">&lt;-</span> <span class="fu">adherence_beta</span>(p_ex)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>mean_risk_ex <span class="ot">&lt;-</span> <span class="fu">integrate</span>(<span class="cf">function</span>(a) <span class="fu">risk12</span>(a) <span class="sc">*</span> <span class="fu">dbeta</span>(a, ab_ex[[<span class="st">"shape1"</span>]], ab_ex[[<span class="st">"shape2"</span>]]),</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                          <span class="dv">0</span>, <span class="dv">1</span>)<span class="sc">$</span>value</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">ratio_kappa12 =</span> jensen_ratio, <span class="at">ratio_kappa50 =</span> mean_risk_ex <span class="sc">/</span> risk_at_mean), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ratio_kappa12 ratio_kappa50 
        1.231         1.045 </code></pre>
</div>
</div>
<p><strong>Bài 2.</strong> Nhân số mức của các biến nhớ để ra số trạng thái; nhân số nhóm của thuộc tính cố định để ra số lần chạy:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 2: a leaner cohort model (viraemia memory capped at 24 months, 3 adherence groups,</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># age in 10-year bands). Memory dimensions -&gt; states; fixed attributes -&gt; separate runs.</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>lean_memory <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">health =</span> <span class="dv">5</span>, <span class="at">resistance =</span> <span class="dv">2</span>, <span class="at">eac =</span> p<span class="sc">$</span>eac_months <span class="sc">+</span> <span class="dv">1</span>, <span class="at">since_test =</span> p<span class="sc">$</span>vl_soc,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">cum_vir =</span> <span class="dv">25</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>lean_runs <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="sc">*</span> <span class="dv">9</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">states =</span> <span class="fu">prod</span>(lean_memory), <span class="at">runs =</span> lean_runs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>states   runs 
 12000     27 </code></pre>
</div>
</div>
<p>Vẫn cần 12,000 trạng thái và 27 lần chạy. Mỗi trạng thái là một hàng trong ma trận chuyển, nên kiểm tra bằng tay là không khả thi.</p>
<p><strong>Bài 3.</strong> Tăng <span class="math inline">\(N\)</span> chỉ làm giảm nhiễu ngẫu nhiên theo <span class="math inline">\(1/\sqrt{N}\)</span>. Phần bất định đến từ tham số giữ nguyên dù <span class="math inline">\(N\)</span> lớn đến đâu. Với 10,000 người, độ lệch chuẩn do tham số riêng gấp khoảng 5.4 lần độ lệch chuẩn do nhiễu.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 3: first-order spread falls with 1 / sqrt(N); parameter spread does not</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">sd_ratio_first =</span> sd_ratio_first, <span class="at">theory =</span> <span class="fu">sqrt</span>(<span class="dv">10000</span> <span class="sc">/</span> <span class="dv">100</span>),</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">sd_param_vs_noise =</span> sd_param_only <span class="sc">/</span> <span class="fu">sd</span>(first_10k)), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   sd_ratio_first            theory sd_param_vs_noise 
             9.47             10.00              5.39 </code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="tài-liệu-tham-khảo" class="level2">
<h2 class="anchored" data-anchor-id="tài-liệu-tham-khảo">Tài liệu tham khảo</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-baolaocai2025hiv35" class="csl-entry" role="listitem">
Báo Lào Cai. 2025. <span>“35 năm <span>Việt Nam</span> ứng phó với <span>HIV/AIDS</span>: Từ <span>‘án tử’</span> đến cuộc sống có ý nghĩa”</span>. 1 Tháng Chạp 2025. <a href="https://baolaocai.vn/35-nam-viet-nam-ung-pho-voi-hivaids-tu-an-tu-den-cuoc-song-co-y-nghia-post887935.html">https://baolaocai.vn/35-nam-viet-nam-ung-pho-voi-hivaids-tu-an-tu-den-cuoc-song-co-y-nghia-post887935.html</a>.
</div>
<div id="ref-byt2021qd5968" class="csl-entry" role="listitem">
Bộ Y tế. 2021. <span>“Quyết định số 5968/<span>QĐ-BYT</span> ngày 31/12/2021 ban hành Hướng dẫn điều trị và chăm sóc <span>HIV/AIDS</span>”</span>. 31 Tháng Chạp 2021. <a href="https://luatvietnam.vn/y-te/quyet-dinh-5968-qd-byt-215146-d1.html">https://luatvietnam.vn/y-te/quyet-dinh-5968-qd-byt-215146-d1.html</a>.
</div>
<div id="ref-byt2024qd3220" class="csl-entry" role="listitem">
———. 2024. <span>“Quyết định số 3220/<span>QĐ-BYT</span> ngày 01/11/2024 về giá dịch vụ khám bệnh, chữa bệnh áp dụng tại Bệnh viện Bạch Mai”</span>. 1 Tháng Mười-Một 2024. <a href="https://apicms.bachmai.gov.vn/documents/37204/1543632/8_Nov_2024_022948_GMTupload_00004592.pdf/b3ab6717-2151-db08-9913-3cfbfd7e0738">https://apicms.bachmai.gov.vn/documents/37204/1543632/8_Nov_2024_022948_GMTupload_00004592.pdf/b3ab6717-2151-db08-9913-3cfbfd7e0738</a>.
</div>
<div id="ref-brennan2006taxonomy" class="csl-entry" role="listitem">
Brennan, Alan, Stephen E. Chick, và Ruth Davies. 2006. <span>“A taxonomy of model structures for economic evaluation of health technologies”</span>. <em>Health Economics</em> 15 (12): 1295–1310. <a href="https://doi.org/10.1002/hec.1148">https://doi.org/10.1002/hec.1148</a>.
</div>
<div id="ref-briggs2012model" class="csl-entry" role="listitem">
Briggs, Andrew H., Milton C. Weinstein, Elisabeth A. L. Fenwick, Jonathan Karnon, Mark J. Sculpher, và A. David Paltiel. 2012. <span>“Model parameter estimation and uncertainty analysis: a report of the <span>ISPOR-SMDM</span> Modeling Good Research Practices Task Force Working Group-6”</span>. <em>Medical Decision Making</em> 32 (5): 722–32. <a href="https://doi.org/10.1177/0272989X12458348">https://doi.org/10.1177/0272989X12458348</a>.
</div>
<div id="ref-chinhphu2025nd293" class="csl-entry" role="listitem">
Chính phủ. 2025. <span>“Nghị định 293/2025/<span>NĐ-CP</span> quy định mức lương tối thiểu đối với người lao động làm việc theo hợp đồng lao động (hiệu lực từ 1/1/2026)”</span>. 2025. <a href="https://hatinh.gov.vn/vi/bai-viet/tang-luong-toi-thieu-vung-tu-112026">https://hatinh.gov.vn/vi/bai-viet/tang-luong-toi-thieu-vung-tu-112026</a>.
</div>
<div id="ref-grootkoerkamp2010uncertainty" class="csl-entry" role="listitem">
Groot Koerkamp, Bas, Milton C. Weinstein, Theo Stijnen, M. H. Heijenbrok-Kal, và M. G. Myriam Hunink. 2010. <span>“Uncertainty and patient heterogeneity in medical decision models”</span>. <em>Medical Decision Making</em> 30 (2): 194–205. <a href="https://doi.org/10.1177/0272989X09342277">https://doi.org/10.1177/0272989X09342277</a>.
</div>
<div id="ref-krijkamp2018microsimulation" class="csl-entry" role="listitem">
Krijkamp, Eline M., Fernando Alarid-Escudero, Eva A. Enns, Hawre J. Jalal, M. G. Myriam Hunink, và Petros Pechlivanoglou. 2018. <span>“Microsimulation modeling for health decision sciences using <span>R</span>: a tutorial”</span>. <em>Medical Decision Making</em> 38 (3): 400–422. <a href="https://doi.org/10.1177/0272989X18754513">https://doi.org/10.1177/0272989X18754513</a>.
</div>
<div id="ref-matsumoto2025virological" class="csl-entry" role="listitem">
Matsumoto, Shoko, Moeko Nagai, Linh Khanh Tran, Tsunefusa Hayashida, Hoai Dung Thi Nguyen, Truong Manh Nguyen, Giang Van Tran, và c.s. 2025. <span>“Virological outcomes and treatment retention in <span>North Vietnam</span> amidst transition to social insurance-based <span>HIV</span> services and dolutegravir-based regimens”</span>. <em>Scientific Reports</em> 15 (1): 42657. <a href="https://doi.org/10.1038/s41598-025-26866-5">https://doi.org/10.1038/s41598-025-26866-5</a>.
</div>
<div id="ref-paterson2000adherence" class="csl-entry" role="listitem">
Paterson, D. L., S. Swindells, J. Mohr, M. Brester, E. N. Vergis, C. Squier, M. M. Wagener, và N. Singh. 2000. <span>“Adherence to protease inhibitor therapy and outcomes in patients with <span>HIV</span> infection”</span>. <em>Annals of Internal Medicine</em> 133 (1): 21–30. <a href="https://doi.org/10.7326/0003-4819-133-1-200007040-00004">https://doi.org/10.7326/0003-4819-133-1-200007040-00004</a>.
</div>
<div id="ref-phillips2016cost" class="csl-entry" role="listitem">
Phillips, Andrew N., Valentina Cambiano, Fumiyo Nakagawa, Loveleen Bansi-Matharu, Papa Salif Sow, Peter Ehrenkranz, Deborah Ford, và c.s. 2016. <span>“Cost effectiveness of potential <span>ART</span> adherence monitoring interventions in <span>Sub-Saharan Africa</span>”</span>. <em>PLoS ONE</em> 11 (12): e0167654. <a href="https://doi.org/10.1371/journal.pone.0167654">https://doi.org/10.1371/journal.pone.0167654</a>.
</div>
<div id="ref-quochoi2019laborcode" class="csl-entry" role="listitem">
Quốc hội. 2019. <span>“Bộ luật Lao động 2019, Điều 105: Thời giờ làm việc bình thường”</span>. 2019. <a href="https://lsvn.vn/thoi-gio-lam-viec-binh-thuong-cua-nguoi-lao-dong-duoc-quy-dinh-nhu-the-nao1630840022.html">https://lsvn.vn/thoi-gio-lam-viec-binh-thuong-cua-nguoi-lao-dong-duoc-quy-dinh-nhu-the-nao1630840022.html</a>.
</div>
<div id="ref-rutter2011dynamic" class="csl-entry" role="listitem">
Rutter, Carolyn M., Alan M. Zaslavsky, và Eric J. Feuer. 2011. <span>“Dynamic microsimulation models for health outcomes: a review”</span>. <em>Medical Decision Making</em> 31 (1): 10–18. <a href="https://doi.org/10.1177/0272989X10369005">https://doi.org/10.1177/0272989X10369005</a>.
</div>
<div id="ref-siebert2012statetransition" class="csl-entry" role="listitem">
Siebert, Uwe, Oguzhan Alagoz, Ahmed M. Bayoumi, Beate Jahn, Douglas K. Owens, David J. Cohen, và Karen M. Kuntz. 2012. <span>“State-transition modeling: a report of the <span>ISPOR-SMDM</span> Modeling Good Research Practices Task Force-3”</span>. <em>Medical Decision Making</em> 32 (5): 690–700. <a href="https://doi.org/10.1177/0272989X12455463">https://doi.org/10.1177/0272989X12455463</a>.
</div>
</div>
<div class="video-script">
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kịch bản video (~12 phút)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Slide</th>
<th>Lời giảng chính</th>
<th>Hình/Code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Câu hỏi mở đầu</td>
<td>Hai người cùng “ổn định, lĩnh thuốc 3 tháng” có cùng nguy cơ không? Mô hình đoàn hệ trả lời: có</td>
<td>Khung “Vì sao bạn nên quan tâm?”, sơ đồ mô hình</td>
</tr>
<tr class="even">
<td>2</td>
<td>Mô phỏng vi mô là gì</td>
<td>Cùng trạng thái, cùng chu kỳ; mô phỏng từng người; lấy trung bình trên nhiều người</td>
<td>Bảng so sánh đoàn hệ và cá thể</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Jensen</td>
<td>Hàm nguy cơ lồi; người trung bình ≠ quần thể trung bình; con số từ R</td>
<td><code>figs/l01-jensen.png</code>, chunk <code>l01-jensen</code></td>
</tr>
<tr class="even">
<td>4</td>
<td>Cạn kiệt nhóm nguy cơ cao</td>
<td>Người tuân thủ kém rời trạng thái trước; nguy cơ quần thể giảm; hai đường cắt nhau</td>
<td><code>figs/l01-depletion.png</code></td>
</tr>
<tr class="odd">
<td>5</td>
<td>Giả định Markov</td>
<td>Ba thứ mô hình HIV phải nhớ: thời gian thất bại virus học tích lũy, cờ kháng thuốc, đồng hồ xử trí</td>
<td>Danh sách “trí nhớ”</td>
</tr>
<tr class="even">
<td>6</td>
<td>Bùng nổ số trạng thái</td>
<td>Biến nhớ nhân thành trạng thái; thuộc tính cố định thành lớp; tuổi thành mảng ba chiều; khó khăn là chỉ định và kiểm tra</td>
<td>Bảng <code>memory</code>, chunk <code>l01-explosion</code></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Bốn loại bất định</td>
<td>Ngẫu nhiên, tham số, không đồng nhất, cấu trúc; loại nào giảm khi tăng N</td>
<td>Bảng bốn loại bất định</td>
</tr>
<tr class="even">
<td>8</td>
<td>Bằng chứng mô phỏng</td>
<td>N nhỏ, N lớn, PSA: hộp nào co lại, hộp nào không</td>
<td><code>figs/l01-uncertainty.png</code></td>
</tr>
<tr class="odd">
<td>9</td>
<td>Khi nào không dùng</td>
<td>Gần tuyến tính, vài nhóm là đủ, cần tương tác giữa người với người</td>
<td>Sơ đồ quyết định</td>
</tr>
<tr class="even">
<td>10</td>
<td>Tóm tắt và chuyển tiếp</td>
<td>Bài 2: viết mô phỏng vi mô bằng vòng lặp</td>
<td>Ý chính</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../kb/m04-microsimulation/index.html" class="pagination-link" aria-label="M04 · Mô phỏng vi mô (microsimulation)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">M04 · Mô phỏng vi mô (microsimulation)</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../kb/m04-microsimulation/l02-microsim-loops.html" class="pagination-link" aria-label="Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản">
        <span class="nav-page-text"><span class="chapter-title">Bài 2: Mô phỏng vi mô bằng vòng lặp trong R cơ bản</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>